### ISSUE TITLE
incorrect permissions /dev/lp0 and /dev/usb/lp0

### ISSUE THREAD

**Issue by trentasis** [Thinstation/thinstation#101]
With 5.4 versión printer devices  /dev/lp0 and /dev/usb/lp0 work if printers are attached and up before to boot thinstation, because in 
ts / build / packages / lprng / etc / init.d / lprng 

exist this:
chmod 666 /dev/lp0 
chmod 666 /dev/usb/lp0 

Our problem is if you attached or start your printer after thinstation boot, in this siutation printer can't work until thinstation is rebooted. We have tried with 2.2 versions and was working and problem is with permissions that are incorrect. I have searched but I can't find the issue... 

Where is  the problem?

Thanks

**Comment by Thinstation** [comment]
Might be an udev rule issue.

**Comment by trentasis** [comment]
Where I can check this and comapre with 2.2 version?

**Comment by Thinstation** [comment]
2.2 did not use udev for hardware detection. It's hard to make this comparison. I'll try and take a look at this over the holidays.

**Comment by trentasis** [comment]
I have tried to replace in /ts/build/packages/automount/etc/udev/rules.d/99-udev.rules

KERNEL=="lp[0-9]*",      SYMLINK=="printers/%n"

by 

KERNEL=="lp[0-9]*",      SYMLINK=="printers/%n", MODE="0666"

But permissions are the same 660... 

Where could be the problem?

Thanks

**Comment by shweew** [comment]
I don't know, just works for me, problems weren't.

2016-04-08 13:13 GMT+04:00 trentasis <notifications@github.com>:

**Comment by trentasis** [comment]
can you show ls -lisah /dev/usb/lp0 after disconnect and reconnect without reboot thinstation?

Thanks

**Comment by shweew** [comment]
Now Thinstation is unavailable.

2016-04-08 15:12 GMT+04:00 trentasis <notifications@github.com>:

**Comment by trentasis** [comment]
hi,

can you show ls -lisah /dev/usb/lp0 output after boot thinstation and same command after disconnect and connect usb printer? I  like to compare both results.

thanks

**Comment by Doncuppjr** [comment]
Shouldn't be to hard. Boot TS, run the command. Disconnect and Reconnect printer, run command again. Did I miss part of the challenge? 

    On Saturday, April 9, 2016 6:27 AM, trentasis <notifications@github.com> wrote:
 

 hi,can you show ls -lisah /dev/usb/lp0 output after boot thinstation and same command after disconnect and connect usb printer? I like to compare both results.thanks—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub 

   

A lightning fast message from Yahoo Mail. Get it now    On Saturday, April 9, 2016 6:27 AM, trentasis <notifications@github.com> wrote:
 

 hi,can you show ls -lisah /dev/usb/lp0 output after boot thinstation and same command after disconnect and connect usb printer? I like to compare both results.thanks—

**Comment by trentasis** [comment]
Correct Don, I hope that shweew  can show this commands otuputs, for me fails after disconnect, but for shweew works...

**Comment by trentasis** [comment]
solved with 
https://github.com/Thinstation/thinstation/pull/219
https://github.com/Thinstation/thinstation/pull/220

**Comment by trentasis** [comment]
Hi Don,

I have detected that seems that udev is not applying this changes, also tried with script like is used in floppy devices, but udev rules cahnge is not working but if you execute the commands manually works. Do you know if we need any other modification in thinstation to refredh this change to udev rules?


Thanks

**Comment by Doncuppjr** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } I don't know. You might try simulating the event in udev, to see what order the rules are applied, and if that one is being applied correctly.


Sent from Yahoo Mail for iPhone


On Thursday, June 1, 2017, 10:49 AM, trentasis <notifications@github.com> wrote:


Hi Don,

I have detected that seems that udev is not applying this changes, also tried with script like is used in floppy devices, but udev rules cahnge is not working but if you execute the commands manually works. Do you know if we need any other modification in thinstation to refredh this change to udev rules?

Thanks

**Comment by trentasis** [comment]
Hi @Doncuppjr 

After some test I have found:

It seems that in /etc/udev/rules.d/99-udev.rules related with printer are not applied
KERNEL=="lp[0-9]*", SYMLINK=="printers/%n", OWNER="root", GROUP="lp", MODE="0666"

and if you replace by 
KERNEL=="lp[0-9]*", GROUP="lp", MODE="0666"

then works, but I'm not sure why SYMLINK was defined because without this /dev/usb/lp0 persist and seems correct... It could be for multiple printers or works without?
@Doncuppjr do you know why exist this rule and what do you think about my suggestion?

I have found this rule debugging with default rules that really are applied from 
/lib/udev/rules.d/50-udev-default.rules

Thanks

**Comment by trentasis** [comment]
solved in 
https://github.com/Thinstation/thinstation/pull/229
https://github.com/Thinstation/thinstation/pull/230

**Comment by trentasis** [comment]
Solved
