### ISSUE TITLE
SPICE support?

### ISSUE THREAD

**Issue by fossxplorer** [Thinstation/thinstation#106]
Does it support SPICE so it can be used with oVirt?

**Comment by regrubtgit** [comment]
Hi, we have got the spice protocol working using virt-viewer (in a firefox kiosk mode and with usb-redirection.)

There are a couple of packages and/or ports you will need to install in order for spice to work.
Some of them you need to recompile and/or repackage
curl, spice, gtkdialog, libxml2, virt-viewer, systemd, libusb, usbredir, spice-protocol

When I have the time, I will try and explain in detail how to get this working.

For now, good luck

**Comment by Thinstation** [comment]
Cool, do get back to us with a nice explanation. I'm sure there are others that would benefit from this solution.

**Comment by jphein** [comment]
I would also love if SPICE remote-viewer was included in Thinstation. That would make integration with KVM-VDI so easy.

My project is to have a wireless PC using a 1MB iSCSI image on usb flash, booting into a Windows 10 pro desktop KVM virtual machine using the KVM-VDI project with virtual snapshots enabled.

Custom iPXE image made with rom-o-matic, pointing to my fork of the boot.rackspace.com iPXE LiveCD project. 

I want to use Thinstation as the running in RAM OS that iPXE boots. Then by using the thinstation.conf create a remote-viewer Session wrapped by KVM-VDI script. 

Not so hard, right?
We are sooo close. I'll I need is to run remote-viewer on thinstation, and have it remastered.
Any advice?

**Comment by jphein** [comment]
https://github.com/jphein/thinstation/tree/5.4-Stable/ts/build/packages/spice

There seems to be a package for it. Also, a configuration example.

https://github.com/jphein/thinstation/blob/5.4-Stable/ts/build/conf/spice.conf.sample

**Comment by jphein** [comment]
Adding 

> package  spice                   # SPICE client
Seems to have installed a spice client

**Comment by djasa** [comment]
Please note that spicy is a test tool, the client intended for real-world use cases is remote-viewer from virt-viewer package (built with spice-gtk support).

**Comment by Thinstation** [comment]
remote-viewer is integrated since 5.5
