### ISSUE TITLE
Default install of /ts/ports/binary-core/firmware failed.

### ISSUE THREAD

**Issue by jens-maus** [Thinstation/thinstation#109]
I just recognized that in a completely fresh thinstation checkout some firmware files were missing when the build job finished. After checking "/var/log/firmware.log" log file I could see the following:

-- cut here --
[...]
=======> WARNING: Footprint ignored.
=======> Building '/ts/ports/binary-core/firmware/firmware#git-1.pkg.tar.gz' succeeded.
prt-get: Using PKGMK_PACKAGE_DIR: /ts/ports/binary-core/firmware
prt-get: installing firmware git-1
prt-get: /usr/bin/pkgadd firmware#git-1.pkg.tar.gz
prt-get: build done Mon Nov  9 10:48:13 2015

lib/firmware/ath10k/QCA6174/hw2.1/board.bin
lib/firmware/ath10k/QCA6174/hw2.1/firmware-5.bin
lib/firmware/ath10k/QCA6174/hw3.0/board.bin
lib/firmware/ath10k/QCA6174/hw3.0/firmware-4.bin
lib/firmware/ath10k/QCA6174/hw3.0/notice_ath10k_firmware-4.txt
lib/firmware/ath10k/QCA988X/hw2.0/board.bin
pkgadd: listed file(s) already installed (use -f to ignore and overwrite)
-- cut here --

so it seems some other package is already installing some of these files which the main firmware file tries to install during build.

Also within the chroot I then got the same error:

-- cut here --
[root@TS_chroot]/ts/ports/binary-core/firmware# pkgadd firmware#git-1.pkg.tar.gz 
lib/firmware/ath10k/QCA6174/hw2.1/board.bin
lib/firmware/ath10k/QCA6174/hw2.1/firmware-5.bin
lib/firmware/ath10k/QCA6174/hw3.0/board.bin
lib/firmware/ath10k/QCA6174/hw3.0/firmware-4.bin
lib/firmware/ath10k/QCA6174/hw3.0/notice_ath10k_firmware-4.txt
lib/firmware/ath10k/QCA988X/hw2.0/board.bin
pkgadd: listed file(s) already installed (use -f to ignore and overwrite)
-- cut here --

Using "-f" in the pkgadd job solved the problem and it overwrote the duplicate files accordingly and the subsequent build then didn't complain about missing firmware files when generating the pxe images.

**Comment by Thinstation** [comment]
ath10k removed
