### ISSUE TITLE
freerdp option with coma is not parse correctly

### ISSUE THREAD

**Issue by tomarch** [Thinstation/thinstation#110]
i use lastest git master.

I use this freerdp option: 
SESSION_0_FREERDP_OPTIONS="/cert-ignore /sound /drive:*,hotplug"

In the rdp session explorer: i see this drive : "* on thinclient" (thinclient is my hostname) with nothing inside, and hotplug is not working.

in the root shell i see the ck-launch-session which is correct : 
<code>ck-launch-session xfreerdp /f /cert-ignore /sound /drive:\*,hotplug /u:user</code>
but for the xfreerdp process, the comma has been replace by a space:
<code>xfreerdp /f /cert-ignore /sound /drive:* hotplug /u:user</code>

I've try to escape the coma (/drive:*\,hotplug) with no success.

**Comment by Doncuppjr** [comment]
Escape the asterisk as well \*\,


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by tomarch** [comment]
This doesn't work.
I've also try, with no success:
<code>/drive:\\*\\,hotplug</code>
<code>/drive:'*,hotplug'</code>
<code>/drive:'\*\,hotplug'</code>

**Comment by tomarch** [comment]
it's work with : 
<pre>/drive:\*,hotplug</pre>

The missing coma in the ck-launch-session is not important.
