### ISSUE TITLE
FLASH Problem

### ISSUE THREAD

**Issue by qamarhafeez** [Thinstation/thinstation#111]
here is my terminal output

FLASH is not installed, we need to setup binary file.
This only needs to be done once.

Continue? (Y/N)
y

Downloading from Net.....
Using system proxy, or not using any proxy to connect to Internet.
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2015-11-25 04:27:09--  http://fpdownload.adobe.com/get/flashplayer/pdc/11.2.202.481/install_flash_player_11_linux.i386.tar.gz
Resolving fpdownload.adobe.com (fpdownload.adobe.com)... 23.49.10.146
Connecting to fpdownload.adobe.com (fpdownload.adobe.com)|23.49.10.146|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-11-25 04:27:10 ERROR 404: Not Found.

WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2015-11-25 04:27:10--  http://fpdownload.adobe.com/get/flashplayer/pdc/11.2.202.481/install_flash_player_11_linux.i386.tar.gz
Resolving fpdownload.adobe.com (fpdownload.adobe.com)... 23.49.10.146
Connecting to fpdownload.adobe.com (fpdownload.adobe.com)|23.49.10.146|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-11-25 04:27:11 ERROR 404: Not Found.

Error has occured downloading file
Build Aborted

**Comment by Doncuppjr** [comment]
You will need to update the url for Adobe flash. /build/build.urls , then send me a merge request for both 5.4 and master.


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by Thinstation** [comment]
urls updated
