### ISSUE TITLE
freerdp upgrade and bug 

### ISSUE THREAD

**Issue by trentasis** [Thinstation/thinstation#115]
Hi,

We have detected some problems with latest versions of rdekstop 1.8.3, and seems that latest versions of freerdp (git from master) has solved this issues, it will be great to upgrade freerdp to latest master branch

Also, we have detected that during test of freerdp appears a dialog "preparing to run freerdp", I have tested removing files:
./ts/build/packages/freerdp/build/extra/etc/cmd/freerdp.getuser
./ts/build/packages/freerdp/etc/cmd/freerdp.getuser

and then withi dialog has disappeared

With rdekstop was working OK, without dialog and double auth

Can you remove both files and upgrade freerdp to latest master branch?

PKG file used to upgrade 
# Description: Free RDP client
# URL: http://www.freerdp.com/
# Maintainer: Donald A. Cupp Jr. (don cupp jr at ya hoo dot com)
# Depends on: xorg-libx11

name=freerdp
version=2.0-dev
release=master

build() {
        git clone git://github.com/FreeRDP/FreeRDP.git -b ${release}
        cd FreeRDP
        cmake . -DCMAKE_INSTALL_PREFIX=/usr \
                -DCMAKE_INSTALL_LIBDIR=lib \
                -DDOCBOOKXSL_DIR=/usr/share/sgml/docbook/xsl-ns-stylesheets \
                -DCMAKE_BUILD_TYPE=Release \
                -DWITH_PCSC=ON \
                -DBUILD_SHARED_LIBS=ON \
                -DWITH_CHANNELS=ON \
                -DWITH_CHANNELS_PRINT=ON \
                -DWITH_SERVER=OFF \
                -DWITH_CLIENT=ON \
                -DWITH_PULSE=ON \
                -DWITH_ALSA=ON \
                -DWITH_CUPS=ON \
                -DWITH_FFMPEG=ON \
                -DCHANNEL_URBDRC_CLIENT=ON \
                -DWITH_GSTREAMER=ON \
                -DWITH_DIRECTFB=OFF \
                -DWITH_XINERAMA=ON \
                -DWITH_CUNIT=OFF \
                -DWITH_JPEG=ON \
                -DWITH_IPP=OFF \
                -DWITH_NPP=OFF \
                -DWITH_MANPAGES=ON \
                -DWITH_SAMPLE=ON

        make
        make DESTDIR=$PKG install
}

and then 
		pkgmk -u -d -um 
		pkgmk -u 
		pkgmk -uf 
		pkgmk -u 
		update freerdp

Latest version freerdp solved many errors, for example allow rdp to w2003

Can you upgrade freerdp and then delete freerdp.getuser that generates problems with freerdp dialog?

Thanks

**Comment by Thinstation** [comment]
Does freerdp have a gui of it's own now?

**Comment by trentasis** [comment]
I don't know exactly what are you asking... with this modification is used as it was used with rdesktop, directly asks user/pwd in rdp server...

**Comment by Doncuppjr** [comment]
Disables NLA by default?


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by trentasis** [comment]
Correct, we have migrated same parameters from rdesktop to freerdp with similar options and any additional and with this pull request works!

Can you upgrade freerdp and getuser file to solve this issue in thinstation?

Thanks

**Comment by trentasis** [comment]
can you upgrade freerdp and delete getuser file to solve issue?
thanks

**Comment by trentasis** [comment]
Hi,

After trying with latest commit, with latest freerdp we have a problems with libssl and libcrypto when we try to run xfreerdp:

# xfreerdp
xfreerdp: error while loading shared libraries: libssl.so.1.0.2: cannot open shared object file: No such file or directory

if then we copy 
cp /lib/libssl.so.1.0.1 /lib/libssl.so.1.0.2

then we receive
# xfreerdp
xfreerdp: error while loading shared libraries: libcrypto.so.1.0.2: cannot open shared object file: No such file or directory

if then we copy 
cp /lib/libssl.so.1.0.1 /lib/libssl.so.1.0.2

and after that works

My question, what is the correct way to solve this problems only copy 1.0.1 to 1.0.2 or exactly what is the correct way. Can you update or give me detail how to do this?

Thanks

**Comment by Doncuppjr** [comment]
Strange, I just did a build with master, and I get all sixlibssl.so.1.0.0libssl.so.1.0.1
libssl.so.1.0.2libcrypto.so.1.0.0libcrypto.so.1.0.1libcrypto.so.1.0.2All the libcrypto are actually the same, and all the libssl are actually the same. They just have different names to satisfy anything that linked against them. They are hardlinked, so they don't take up any extra space. Am I missing something? 

    On Friday, January 15, 2016 1:25 AM, trentasis <notifications@github.com> wrote:
 

 Hi,After trying with latest commit, with latest freerdp we have a problems with libssl and libcrypto when we try to run xfreerdp:
xfreerdp
xfreerdp: error while loading shared libraries: libssl.so.1.0.2: cannot open shared object file: No such file or directoryif then we copy 
cp /lib/libssl.so.1.0.1 /lib/libssl.so.1.0.2then we receive
xfreerdp
xfreerdp: error while loading shared libraries: libcrypto.so.1.0.2: cannot open shared object file: No such file or directoryif then we copy 
cp /lib/libssl.so.1.0.1 /lib/libssl.so.1.0.2and after that worksMy question, what is the correct way to solve this problems only copy 1.0.1 to 1.0.2 or exactly what is the correct way. Can you update or give me detail how to do this?Thanks—

**Comment by trentasis** [comment]
A search in master appears this  
ts/ports/core/openssl/.footprint
Showing the top seven matches. Last indexed on 30 Sep 2015.
-rw-r--r--	root/root	usr/lib/libssl.a
lrwxrwxrwx	root/root	usr/lib/libssl.so -> libssl.so.1.0.1
lrwxrwxrwx	root/root	usr/lib/libssl.so.1.0.0 -> libssl.so.1.0.1
-rwxr-xr-x	root/root	usr/lib/libssl.so.1.0.1
and 

 ts/ports/core/openssl/.footprint
Showing the top seven matches. Last indexed on 30 Sep 2015.
-rw-r--r--	root/root	usr/lib/libcrypto.a
lrwxrwxrwx	root/root	usr/lib/libcrypto.so -> libcrypto.so.1.0.1
lrwxrwxrwx	root/root	usr/lib/libcrypto.so.1.0.0 -> libcrypto.so.1.0.1
-rwxr-xr-x	root/root	usr/lib/libcrypto.so.1.0.1
-rw-r--r--	root/root	usr/lib/libssl.a

From github I can't seen 1.0.2 in any path... or where is it?

**Comment by Doncuppjr** [comment]
It's not in 5.4-Stable, but it is in master
 

    On Friday, January 15, 2016 9:28 AM, trentasis <notifications@github.com> wrote:
 

 A search in master appears this

ts/ports/core/openssl/.footprint
Showing the top seven matches. Last indexed on 30 Sep 2015.
-rw-r--r-- root/root usr/lib/libssl.a
lrwxrwxrwx root/root usr/lib/libssl.so -> libssl.so.1.0.1
lrwxrwxrwx root/root usr/lib/libssl.so.1.0.0 -> libssl.so.1.0.1
-rwxr-xr-x root/root usr/lib/libssl.so.1.0.1
and ts/ports/core/openssl/.footprint
Showing the top seven matches. Last indexed on 30 Sep 2015.
-rw-r--r-- root/root usr/lib/libcrypto.a
lrwxrwxrwx root/root usr/lib/libcrypto.so -> libcrypto.so.1.0.1
lrwxrwxrwx root/root usr/lib/libcrypto.so.1.0.0 -> libcrypto.so.1.0.1
-rwxr-xr-x root/root usr/lib/libcrypto.so.1.0.1
-rw-r--r-- root/root usr/lib/libssl.aFrom github I can't seen 1.0.2 in any path... or where is it?—

**Comment by Doncuppjr** [comment]
Cherry-picked to Stable. 

    On Friday, January 15, 2016 9:52 AM, Don Cupp <doncuppjr@yahoo.com> wrote:
 

 It's not in 5.4-Stable, but it is in master
 

    On Friday, January 15, 2016 9:28 AM, trentasis <notifications@github.com> wrote:
 

 A search in master appears this

ts/ports/core/openssl/.footprint
Showing the top seven matches. Last indexed on 30 Sep 2015.
-rw-r--r-- root/root usr/lib/libssl.a
lrwxrwxrwx root/root usr/lib/libssl.so -> libssl.so.1.0.1
lrwxrwxrwx root/root usr/lib/libssl.so.1.0.0 -> libssl.so.1.0.1
-rwxr-xr-x root/root usr/lib/libssl.so.1.0.1
and ts/ports/core/openssl/.footprint
Showing the top seven matches. Last indexed on 30 Sep 2015.
-rw-r--r-- root/root usr/lib/libcrypto.a
lrwxrwxrwx root/root usr/lib/libcrypto.so -> libcrypto.so.1.0.1
lrwxrwxrwx root/root usr/lib/libcrypto.so.1.0.0 -> libcrypto.so.1.0.1
-rwxr-xr-x root/root usr/lib/libcrypto.so.1.0.1
-rw-r--r-- root/root usr/lib/libssl.aFrom github I can't seen 1.0.2 in any path... or where is it?—

**Comment by trentasis** [comment]
solved with latest version.
Thanks!
