### ISSUE TITLE
How to remove display error logs? or disable it.

### ISSUE THREAD

**Issue by Maxchip** [Thinstation/thinstation#117]
Hello friends,

How I remove display error logs? or disable it.

Thanks

Thinstation is the best +1: 

![errorthinstation](https://cloud.githubusercontent.com/assets/11981239/12263505/bec03b16-b916-11e5-8737-ecf913a17a03.png)

**Comment by Thinstation** [comment]
in thinstation.conf.<something>
SHOW_ERROR_REPORT=false

**Comment by Maxchip** [comment]
Thank you very much for help.
Team Thinstation is very smart.
Thinstation is a excellent solution, I like it :)
