### ISSUE TITLE
cups printing

### ISSUE THREAD

**Issue by trentasis** [Thinstation/thinstation#122]
Hi we are trying to migrate our rdp client from rdesktop to freerdp, and with this new version we need cups for printing. We have two questions:

1) We can print with hp printers with USB, but we have problems with other models, for example we are trying with a brother HL5450DN.

HP and brothers are added from localhost:631 but our problems is that brother pritners are not correctly detected, are detected as HP... I think that the problem is with drivers, but we don't know how to add new drivers for brother... 

we have used in build.conf 
package hpijs
package ghostscript

package brotherij
package brotherhl
package brotherhllpr
package brotherijlpr
package brotherijcups

package gutenprint

#package lp_server              # Remote printing daemon (JetDirect compatible)
#package lpr                    # LPR Print Server, for use with samba-server package
package lprng                   # LPRng Print Server, supports network based printing
package cups
package system-config-printer

But with Brothers we can't print...
What can I do?

2) 
Second question is related with printer on boot configuration, with previous versins we were using rdesktop with lprng and wit this and a basic configuration like for example:
network printer:
PRINTER_0_NAME=LASER
PRINTER_0_DEVICE=192.169.169.57%9100           #printer_id%9100
PRINTER_0_TYPE=N

and 

SESSION_0_RDESKTOP_OPTIONS="-k es -a 24 -u '' -d domain-r
printer:LASER='Brother PCL5e Driver' -r scard"

was working great, without any specific configuration in thinstation, and only installrequired drivers in TS SERVER.

what is the best way to do this with cups and freerdp ?

Thanks

**Comment by trentasis** [comment]
Hi Don,

I have tried to add some addtional support for exampel HL5240, HL 5250  and HL5450 adding correct url cupswrapper form brother to pkgfile and then:
cd /ts/ports/components/brotherhlcups 
pkgmk -u -d -um 
pkgmk -u 
pkgmk -uf 
pkgmk -u 
update brotherhlcups

but after that update brotherhlcups fails, where is the problem?

Cups is printing correctly with HP but with brother we can't print with cups, can you give some details how I can solve?

Thanks

**Comment by trentasis** [comment]
Hi,

Anybody can upgrade cups to 2.1.2, we have tried cups 2.1.2 with debian testing and with this versions cups works with brothers or how can I upgrade, only replace file https://crux.nu/ports/crux-3.2/opt/cups/Pkgfile from thinstation source?

Thanks

**Comment by Thinstation** [comment]
That might work.

**Comment by trentasis** [comment]
It seems that doesn't work, is required cups-filter and I don't know how to add...
any suggestions?

tried with package cups-filters without success...

Thanks

**Comment by trentasis** [comment]
With cups 1.5.4 https://github.com/Thinstation/thinstation/pull/134 now I can configure to print, usb and network printers.

Last problem is that this configuration was made with localhost:631 web interface, I need to configure on boot like it was used with lprng.  

Possible options could be:
- module_pkg
- copy printers.conf during boot
- other?

What is the best way to make a boot config with cups?

Thanks

**Comment by Thinstation** [comment]
You might need to write a bridge script. You essentially have to reverse engineer the configuration file/s of cups, and then define the fewest number of variables that a boot script could use to write the configuration files. Examples of this can be seen in xfwm4.functions, and xconf

**Comment by trentasis** [comment]
Please recompile with cups and freerdp with  https://github.com/Thinstation/thinstation/pull/136 and commit

How it Works?
Only deifne printer with:
CUPS_PRINTER_0_NAME="laser_hp_usb"
 CUPS_PRINTER_0_DEVICEURI="file:///dev/usb/lp0"
 CUPS_PRINTER_0_DRIVER="drv:///sample.drv/generpcl.ppd"

Thanks
