### ISSUE TITLE
Geode xorg driver not available anymore ?

### ISSUE THREAD

**Issue by glauriol** [Thinstation/thinstation#126]
A lots of low-end thin clients are using the ubiquitous Geode for video, but the driver is not available anymore ? (was OK in 5.3).

**Comment by Doncuppjr** [comment]
You can use uvesafb and the org fb driver. Nothing special about the geode driver. 

    On Wednesday, March 16, 2016 6:38 AM, glauriol <notifications@github.com> wrote:
 

 A lots of low-end thin clients are using the ubiquitous Geode for video, but the driver is not available anymore ? (was OK in 5.3).—

**Comment by glauriol** [comment]
I beg to differ, there are some things quite "special" in the Geode driver, especially regarding LVDS and flat panels support (Option "PanelMode") and screen rotation. some point-of-sale hardware consists of just a panel and an embedded Geode-based PC.  The vesa driver cannot deal with these.

**Comment by Doncuppjr** [comment]
I did not suggest the Vesa driver. I am not a fan. Uvesafb on the other hand works really nice and when paired with the Xorg fb driver should give really good coverage on just about any hardware out there.


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by glauriol** [comment]
Sorry, typed too quiclky, intended to say " The uvesafb driver cannot deal with these".

Is there a particular reason you did not include the Geode driver in 5.4 ? I see it's still here (or back ?) in 6.0-unstable

**Comment by Doncuppjr** [comment]
6.0 is actually older than 5.4. I think the geode driver stopped compiling with the newer Xorg, or at least no one had gotten around to maintaining it when I was doing the Xorg update. 

    On Wednesday, March 16, 2016 8:42 AM, glauriol <notifications@github.com> wrote:
 

 Sorry, typed too quiclky, intended to say " The uvesafb driver cannot deal with these".Is there a particular reason you did not include the Geode driver in 5.4 ? I see it's still here (or back ?) in 6.0-unstable —

**Comment by ipitcher** [comment]
Since [XAA was removed](https://lists.x.org/archives/xorg-devel/2012-January/028641.html) entirely from X.Org, and an alternative acceleration for old drivers like Geode doesn't seem to be in place, you'll probably just find the performance of X.Org Server past version 1.13 to be frustrating at best. That's been my experience, anyway.

**Comment by ipitcher** [comment]
@Doncuppjr, since you mentioned it, could you put an xorg-fbdev package in master? I noticed that it's not there, and it would probably be more useful than xorg-vesa for a lot of situations, as you said.

**Comment by Doncuppjr** [comment]
fbdev is in the Xorg7 base package. It's very tiny.


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by ipitcher** [comment]
OK, thanks.

**Comment by trentasis** [comment]
Solves?

**Comment by Thinstation** [comment]
Or won't do. But there is nothing that can be done from here.

**Comment by trentasis** [comment]
I think that can be closed this issue...

**Comment by glauriol** [comment]
I agree
