### ISSUE TITLE
update freerdp, cups and cups-filters

### ISSUE THREAD

**Issue by trentasis** [Thinstation/thinstation#131]
Hi,

I can't upgrade  freerdp cups and cups-filters with:
pkgmk -u -d -um 
pkgmk -u 
pkgmk -uf 
pkgmk -u 
update package

during update package fails...

Where is the problem? Can you give some detail how to update correctly this package and how to upload this change as pull request to all users?

Thanks

**Comment by trentasis** [comment]
Also tried prt-get remove package and prt-get install package not succcess

prt-get update package... no success...

**Comment by Thinstation** [comment]
cd /ts/ports/components/freerdp
nano Pkgfile, and make updates to version strings or git commits, save with ctrl-o, then ctrl-x to exit
pkgmk -um
pkgmk -u
pkgmk -uf
pkgmk -u
update freerdp, then build

**Comment by trentasis** [comment]
Freeredp updated, but during compile some errors, for example:
=======> ERROR: Footprint mismatch found:
=======> ERROR: Building '/ts/ports/opt/freerdp/freerdp#2.0-dev-20160407_git_0e2c4f2-master.pkg.tar.gz' failed.

Also trying to update cups and cups-filters but cups appears updated, but has as requirement cups-filters and I hace tried to add:
package cups-filters 
but  cups-filters is not installed?

How can I update cups and cups-filters to latest versions?
Can you add to master branch, pull request https://github.com/Thinstation/thinstation/pull/134 freerdp update?

Thanks

**Comment by trentasis** [comment]
solved with https://github.com/Thinstation/thinstation/pull/134
