### ISSUE TITLE
Open RDP or VNC connection with single host?

### ISSUE THREAD

**Issue by thebeline** [Thinstation/thinstation#146]
Is it possible to have the Thinstation automatically open a connection a single computer (not a server) on boot?  Either via RDP or VNC?

I am not going to much about with Windows Server or Citrix, etc.  I just want to spin up virtual machines in my existing vSphere environment, and have a thinstation open a connection to it automatically.

Not sure if this is the right place to ask this question...

**Comment by Doncuppjr** [comment]
Yes, you can do that. Lots of people do. 

    On Saturday, June 11, 2016 11:08 AM, Michael Mulligan <notifications@github.com> wrote:
 

 Is it possible to have the Thinstation automatically open a connection a single computer (not a server) on boot? Either via RDP or VNC?I am not going to much about with Windows Server or Citrix, etc. I just want to spin up virtual machines in my existing vSphere environment, and have a thinstation open a connection to it automatically.Not sure if this is the right place to ask this question...—

**Comment by Thinstation** [comment]
This is more a mailing list question than an issue.
