### ISSUE TITLE
TS 5.5 nvidia.ko and mesa3d

### ISSUE THREAD

**Issue by beremour** [Thinstation/thinstation#148]
While building  --allmodules , getting:
```
cp: cannot stat 'nvidia.ko': No such file or directory
pkgadd: could not open /ts/ports/xorg/mesa3d/mesa3d#11.2.2-1.pkg.tar.gz: No such file or directory
```

but real file is  not GZ but XZ
```
ls -l /ts/ports/xorg/mesa3d/mesa3d*
-rw-r--r-- 1 root root 7385528 Jun 20 04:51 /ts/ports/xorg/mesa3d/mesa3d#11.2.2-1.pkg.tar.xz
```

**Comment by Thinstation** [comment]
Fixed

**Comment by beremour** [comment]
Sorry, but after
```
./clean_chroot 
exit
./setup-chroot

```getting
`Installing Port mesa3d                                  Could not find an archive.`

**Comment by Thinstation** [comment]
might need to do a factory reset

**Comment by beremour** [comment]
Is  "./clean_chroot "  a Factory reset ?

**Comment by Doncuppjr** [comment]
No, that's a cleanup that I use to check my work, but you could use it along with git checkout -f ts/ports/xorg/mesa3d
 

    On Monday, June 20, 2016 12:56 PM, beremour <notifications@github.com> wrote:
 

 Is "./clean_chroot " a Factory reset ?—
