### ISSUE TITLE
CUPS  init.d script

### ISSUE THREAD

**Issue by beremour** [Thinstation/thinstation#152]
CUPS script "... /ts/build/packages/cups/etc/init.d" has command
`echo "FileDevice yes" >> /etc/cups/cupsd.conf`
but shouldn't it be:
`echo "FileDevice yes" >> /etc/cups/cups-files.conf`
?

When adding printer manualy:
`lpadmin -p TEST -v file:///dev/usb/lp0  -E`
I've got:
`lpadmin: File device URIs have been disabled. To enable, see the FileDevice directive in "/etc/cups/cups-files.conf"
`

**Comment by Doncuppjr** [comment]
Maybe, might have changed between versions.

Sent from Yahoo Mail on Android 
 
  On Fri, Jul 1, 2016 at 4:35 AM, beremour<notifications@github.com> wrote:   
CUPS script "... /ts/build/packages/cups/etc/init.d" has command
echo "FileDevice yes" >> /etc/cups/cupsd.conf
but shouldn't it be:
echo "FileDevice yes" >> /etc/cups/cups-files.conf
?

When adding printer manualy:
lpadmin -p TEST -v file:///dev/usb/lp0 -E
I've got:
lpadmin: File device URIs have been disabled. To enable, see the FileDevice directive in "/etc/cups/cups-files.conf"

**Comment by trentasis** [comment]
beremour,

Can you try with this patch 
https://github.com/Thinstation/thinstation/pull/170

**Comment by trentasis** [comment]
Don,

Latest cups changes are not correct, now are merged to 5.4 and is not correct this change only isrequired in 5.5. Please, can you revert 5.4 cahnge about cups and add to master and 5.5

About freerdp cahnge freerdp.getuser is correct in 5.4, but also will be great to add 5.5 and master

Thanks
