### ISSUE TITLE
i915 Graphics problems with 4.6 kernel.

### ISSUE THREAD

**Issue by subsequent2** [Thinstation/thinstation#168]
Following error message in messages.

[drm:intel_set_cpu_fifo_underrun_reporting [i915]] _ERROR_ pipe A underrun
[drm:intel_cpu_fifo_underrun_irq_handler [i915]] _ERROR_ CPU pipe A FIFO underrun
[drm:intel_psr_work [i915]] _ERROR_ Timed out waiting for PSR Idle for re-enable

Screen keeps flickering and blink.

https://bugs.freedesktop.org/show_bug.cgi?id=95176#c28 <- thread with same problems. 

Solution is to upgrade to Kernel 4.7

**Comment by trentasis** [comment]
Solved, 5.5, has 4.9

**Comment by trentasis** [comment]
I think that can be closed this issue...
