### ISSUE TITLE
Minumim 2GB of RAM for installer

### ISSUE THREAD

**Issue by fallen-uk** [Thinstation/thinstation#169]
Hello,

I have thinclient with 2gb of ram, when i tried to install thinstation i see error that i need minimum 2GB of RAM for install, is it correct?

**Comment by Doncuppjr** [comment]
The DevStation image is for developing thinclient images and takes considerably more ram than a typical thinclient image. Try installing on a regular workstation and making an image for your thinclient.
Sent from Yahoo Mail on Android 
 
  On Tue, Aug 16, 2016 at 11:07 PM, fallen-uk<notifications@github.com> wrote:   
Hello,

I have thinclient with 2gb of ram, when i tried to install thinstation i see error that i need minimum of 2GB of RAM for install, is it correct?
