### ISSUE TITLE
freerdp don't remember last user and add fronted by default

### ISSUE THREAD

**Issue by trentasis** [Thinstation/thinstation#171]
Two questions:

1.- I need to configure that user is not saved and load after ctr+alt+backspace or new freerdp, I have detected that is saved in 
ts/build/packages/base/etc/dialog.functions
	if [ -e /tmp/.dialog_${client}_user ]; then
		DIALOG_USER=$(cat /tmp/.dialog_${client}_user)
	fi

we can remove this lines, but we like to know if exsit another option for example any environment to disable remember last user, where and how can I do this?

It seems that exist 	if [ -z $SHOW_USER ]; then
		SHOW_USER=false
	fi
but not sure when is used...

Tried to define REMUSER=" " or REMUSER="usertest" and tehn first tiem show this value, but I like that always appears empty... How can I do?

2.- Please can you add https://github.com/Thinstation/thinstation/pull/170 to recover freerdp frontend

Thanks

**Comment by trentasis** [comment]
1.- solved with 
https://github.com/Thinstation/thinstation/pull/176
and
https://github.com/Thinstation/thinstation/pull/175

2.- Was solved by Don

Thanks

**Comment by Doncuppjr** [comment]
I think this code should be selective, maybe CLEAR_USER=true. You could also get there by rebooting after every session.

Sent from Yahoo Mail on Android 
 
  On Mon, Aug 22, 2016 at 12:32 PM, trentasis<notifications@github.com> wrote:   
1.- solved with 
#176
and
#175

2.- Was solved by Don

Thanks

**Comment by trentasis** [comment]
Hi,

Our users are working with RDP, and to change user they make ctrl+alt+backpace (fast user change restarting Xorg), with this pull request 175 and 176 if they make ctrl+alt+backpace user is notremembered, but if one user login, or fails login and then returns to login page user is remembered, 

Only is cleared in one situation restart xorg, other situations will keeps the users.
I think that with this configuration is more easy for users...

What do you think?

thanks

**Comment by trentasis** [comment]
last days we  have tested this config and works perfect  keeeping user only when same user reenter and not after restart xorg.
please can you add this pull requests?

thanks

**Comment by trentasis** [comment]
REMEMBER_USER=false has solved

thanks
