### ISSUE TITLE
Problem to install, not enogh memory 

### ISSUE THREAD

**Issue by diablowizard** [Thinstation/thinstation#180]
Hi i have trying to install in a Fujitsu Futro S450-2 that has 1gb of memory, but appears a message that not enough, in BIOS recognized the memory like extended i think that must be the problem, but i want to install.

**Comment by Doncuppjr** [comment]
Please read "Getting Started"

Sent from Yahoo Mail on Android 
 
  On Tue, Aug 30, 2016 at 3:18 AM, diablowizard<notifications@github.com> wrote:   
Hi i have trying to install in a Fujitsu Futro S450-2 that has 1gb of memory, but appears a message that not enough, in BIOS recognized the memory like extended i think that must be the problem, but i want to install.

**Comment by Thinstation** [comment]
The DevStation ISO is not a thin client. It's an installer for a build environment that will make and host thin client images.
