### ISSUE TITLE
Chromium not starting

### ISSUE THREAD

**Issue by c-boeckler** [Thinstation/thinstation#182]
I tried out the new chromium package, but it failed to start:

```
$ chromium 
[3934:3953:0925/123052:ERROR:nss_util.cc(744)] Error initializing NSS with a persistent database (sql:/root/.pki/nssdb): libsoftokn3.so: cannot open shared object file: No such file or directory
[3934:3953:0925/123052:ERROR:nss_util.cc(212)] Error initializing NSS without a persistent database: NSS error code: -5925
[3934:3953:0925/123052:FATAL:nss_util.cc(214)] nss_error=-5925, os_error=0
#0 0x000055f8af6b <unknown>
#1 0x000055fa6842 <unknown>
#2 0x0000560474ee <unknown>
#3 0x000056047a12 <unknown>
#4 0x0000562b01e9 <unknown>
#5 0x000056254636 <unknown>
#6 0x0000562bb9d4 <unknown>
#7 0x000055bd7a1f <unknown>
#8 0x000059019a59 <unknown>
#9 0x0000592b5a2e <unknown>
#10 0x000055fe5375 <unknown>
#11 0x000055fe0d28 <unknown>
#12 0x000076c3868d start_thread
#13 0x00007649f29e clone

Aborted
```

**Comment by Doncuppjr** [comment]
Where did you get chromium from?

Sent from Yahoo Mail on Android 
 
  On Sun, Sep 25, 2016 at 3:03 AM, Christof Böckler<notifications@github.com> wrote:   
I tried out the new chromium package, but it failed to start:

$ chromium 
[3934:3953:0925/123052:ERROR:nss_util.cc(744)] Error initializing NSS with a persistent database (sql:/root/.pki/nssdb): libsoftokn3.so: cannot open shared object file: No such file or directory
[3934:3953:0925/123052:ERROR:nss_util.cc(212)] Error initializing NSS without a persistent database: NSS error code: -5925
[3934:3953:0925/123052:FATAL:nss_util.cc(214)] nss_error=-5925, os_error=0
#0 0x000055f8af6b 
#1 0x000055fa6842 
#2 0x0000560474ee 
#3 0x000056047a12 
#4 0x0000562b01e9 
#5 0x000056254636 
#6 0x0000562bb9d4 
#7 0x000055bd7a1f 
#8 0x000059019a59 
#9 0x0000592b5a2e 
#10 0x000055fe5375 
#11 0x000055fe0d28 
#12 0x000076c3868d start_thread
#13 0x00007649f29e clone

Aborted

**Comment by c-boeckler** [comment]
Actually there was a directory build/packages/chromium/ – which I didn’t 
create or even populate – in my repository so I thought “let’s try 
package chromium” in build.conf.

Am 25.09.2016 um 16:02 schrieb Donald A. Cupp Jr.:
> Where did you get chromium from?
>

**Comment by Doncuppjr** [comment]
Hmmm. I know that one works, because it's the browser for DevStation. Did you also have firefox installed? 

    On Sunday, September 25, 2016 10:07 PM, Christof Böckler <notifications@github.com> wrote:
 

 Actually there was a directory build/packages/chromium/ – which I didn’t 
create or even populate – in my repository so I thought “let’s try 
package chromium” in build.conf.

Am 25.09.2016 um 16:02 schrieb Donald A. Cupp Jr.:
> Where did you get chromium from?
>

**Comment by c-boeckler** [comment]
I don’t remember that, but I tried again with and without firefox: it 
doesn’t matter. I always see the reported behaviour.

Am 26.09.2016 um 19:24 schrieb Donald A. Cupp Jr.:
> Hmmm. I know that one works, because it's the browser for DevStation. Did you also have firefox installed?

**Comment by bcs78** [comment]
Replace the empty `dependencies` file in the Chromium package directory with the one from the Chrome package dir. It'll fix this.
