### ISSUE TITLE
usb mount error with device name

### ISSUE THREAD

**Issue by trentasis** [Thinstation/thinstation#183]
Hi,

 I'am trying to work with usbdevices in thinstation 5 and I can works with  usb, is mounted on /mnt/usdbdevices/sda1, only problem is that if we disconnect and connect then is mounted with other name  /mnt/usdbdevices/sdb1,..., then sdc1... 

 I like to pass to freerdp but for this I need to ensure that always is  mounted with same name, how can I ensure this?
I have searched some info in thinstation code and I think that the best way could be to add a new option, for example:
USB_MOUNT_USELABEL=FIXED
to ensure that always is mounted with same label. 
I think taht code used to implement could be in  
/thinstation/ts/build/packages/automount/etc/udev/scripts/scsi.sh

But changing this, I'm not sure if this for example can affect to hdupdate script...

But I'm not sure what is the best way to make this change, anybody can help or suggest ho to solve this issue?

Thanks

**Comment by ecoutinho** [comment]
Try to plug two usb devices and you'll see that one is mounted on sda1, and the other on sdb1. You should pass '/mnt/usdbdevices' to freerdp and let users deal with it.
