### ISSUE TITLE
Size of thinstation

### ISSUE THREAD

**Issue by qamarhafeez** [Thinstation/thinstation#184]
Can you mention somewhere on your web page or in readme about the downloading size of https://github.com/Thinstation/thinstation/archive/5.5-Stable.zip, So that if i have internet connection in MBs i would like to estimate how long it will take to download the zip file from github

Thanks
Qamar

**Comment by bcs78** [comment]
It's 1.3GB. Is this the info you're looking for?

**Comment by trentasis** [comment]
Solved, 1.3GB

**Comment by trentasis** [comment]
I think that can be closed this issue...
