### ISSUE TITLE
Vmware PCoIP Download failing

### ISSUE THREAD

**Issue by alekou** [Thinstation/thinstation#185]
During the build process if i have enabled the vmviewpcoip   package the system tries to download the following: VMware-Horizon-Client-3.5.0-2999900.x86.bundle which is old and the link is broken or at least does not work.

If i download manually the latest vmware pcoip client, rename it to: VMware-Horizon-Client-3.5.0-2999900.x86.bundle  and put it to the path /thinstation/Downloads then the installer is able to extract the files and complete the build but in the produced .iso file, the vmware view client does not start automatically nor any configuration i made in the file 50vmviewpcoip is getting applied.

Any suggestions on how to get this working preferably with the latest version?

**Comment by ajooluz** [comment]
You need manually put the bundle into /thinstation/Downloads because it is written in the thinstation/ts/build/build.urls. Probably no permanent links to the bundle.
For automatically start you can put into thinstation.conf.buildtime some parameters, for example:
```
SESSION_1_TITLE="VDI"
SESSION_1_TYPE=vmview
SESSION_1_AUTOSTART=on
SESSION_1_VMVIEW_FULLSCREEN=true
SESSION_1_VMVIEW_SERVERURL=view-server-address
SESSION_1_VMVIEW_NOMENUBAR=true
```

**Comment by emuhuron** [comment]
Here's the latest:  https://download3.vmware.com/software/view/viewclients/CART16Q2/VMware-Horizon-Client-4.1.0-3976982.x86.bundle.  I have it working in my build.  Weird part of my install is that I'm getting 2 icons: 1st icon-VMWare Horizon...  and  2nd icon--the Title name that I put in my Session.  The  2nd icon is useless.  I'm trying to figure why the working VMWare icon isn't named the way I want it.

**Comment by emuhuron** [comment]
addendum:  I have the above link in Build.urls

**Comment by ajooluz** [comment]
emuhuron,
> 1st icon-VMWare Horizon...

is it 3.5 version?

**Comment by emuhuron** [comment]
https://download3.vmware.com/software/view/viewclients/CART16Q2/VMware-Horizon-Client-4.1.0-3976982.x86.bundle


Brian Koch
IT Dept
City of Taylor, MI
(734) 374-1514 or Ext. 7550 (internal use)
Please have a ticket put in if you need an issue resolved.

**Comment by Thinstation** [comment]
All vmview variants should now be merged to just vmview, it is PCoIP, but downloads are still at the discretion of VMware......
