### ISSUE TITLE
Openbox skips autostart

### ISSUE THREAD

**Issue by c-boeckler** [Thinstation/thinstation#186]
Openbox is able to run `~/.config/openbox/autostart` automatically at startup [if it is called as `openbox-session`](http://openbox.org/wiki/Help:Autostart). This is currently not the case since `build/packages/openbox/etc/cmd/openbox.global` contains

```
CMD_GLOBAL="openbox_startup"
```

This should be changed somewhere upstream in Thinstation (I have no clue where) into

```
CMD_GLOBAL="openbox-session"
```

**Comment by Doncuppjr** [comment]
I think there is a compatibility layer script in bin called openbox_startup that can be used to start up openbox as well a variety of autostart locations.

We could probably add the default one that openbox-session would try to open to that script.

**Comment by Thinstation** [comment]
This should be complete in 6.1
