### ISSUE TITLE
Include install script for VMware View Client 4

### ISSUE THREAD

**Issue by mezhmal** [Thinstation/thinstation#187]
Current stable release 5.5-Stable includes install script for VMware View Client version 3.5. But version 4 bundle is not correctly install for its. This version has another file structure.
Could anyone include the install script for VMware View Client version 4?
I might try to write this script, but don't know how to start. Can anyone help me?

**Comment by emuhuron** [comment]
This may help:  https://download3.vmware.com/software/view/viewclients/CART16Q2/VMware-Horizon-Client-4.1.0-3976982.x86.bundle

**Comment by ajooluz** [comment]
emuhuron, unfortunately it isn't sufficient

**Comment by emuhuron** [comment]
version 4.1.0 is what I'm using. 

Added in build.urls:
param vmviewpcoipurl  https://download3.vmware.com/software/view/viewclients/CART16Q2/VMware-Horizon-Client-4.1.0-3976982.x86.bundle

In Thinstation.conf.buildtime, in my SESSION_1_TYPE=vmviewpcoip

In Build.conf, uncomment "package VMVIEWPCOIP", NOT VMVIEW if using PCOIP.  Of course, comment out "package VMVIEW"

**Comment by emuhuron** [comment]
ugh, don't use VMVIEW if using PCOIP is what I meant
