### ISSUE TITLE
Missing /tmp/user/0/ directory in chroot environment

### ISSUE THREAD

**Issue by bcs78** [Thinstation/thinstation#189]
When I run the `build` script for the first time in a fresh chroot environment it creates a faulty boot image (stopping with kernel panic during boot time). After checking the build log I realized that a lot of scripts couldn't run for some reason (with errors like "No such file or directory"). It turned out the root cause was the missing `/tmp/user/0/` directory in the chroot environment so after I created it manually the build script managed to create a working boot image.

Please fix the `setup-chroot` or the `build` script to make sure that the necessary temporary work directories are set. Thanks!

**Comment by Thinstation** [comment]
What is the host distribution?

**Comment by bcs78** [comment]
It was a long time ago but you're right. It was most likely a local issue. The host was a Debian distro and had an automated temp folder cleanup task and I'm quite sure that was the root cause.
