### ISSUE TITLE
Display issue in Chromium kiosk session

### ISSUE THREAD

**Issue by bcs78** [Thinstation/thinstation#190]
When I start a Chromium type session to run Chromium in kiosk mode the settings in the current `Preferences.tpl` file in `thinstation/ts/build/packages/chromium/build/extra/etc/chromium/Default/` causing display issues with resolutions higher than 1024x768. I mean every part of the screen which is outside the 1024x768 area is black. Plus there is a distinct black border around the browser. I found no Chromium command line option to override this (tried to tweak with `--ash-host-window-bounds`, `--content-shell-host-window-size`, `--window-position`, `--window-size`, `--window-workspace`, etc).

I have to adjust the following settings before build in the above mentioned `Preferences.tpl` to fix this:

> "browser":{
> ...
> "window_placement":{
> ...
> "bottom":727,
> "left":10,
> "right":1014,
> "top":10,
> "work_area_bottom":737,
> "work_area_left":0,
> "work_area_right":1024,
> "work_area_top":0
> }

So I set bottom and work_area_bottom to 1080, right and work_area_right to 1920, left, work_area_left, top and work_area_top to 0 to get rid of the black border and make Chromium visible on a FullHD screen.

I didn't test what happens if I remove the whole `windows_placement` entry.

**Comment by Thinstation** [comment]
This should be fixed in 6.1
