### ISSUE TITLE
Problem with nvidia ION on thin client

### ISSUE THREAD

**Issue by SoNWarrioR** [Thinstation/thinstation#194]
Hello. We are have thin client with two system:

1. based on intel vga driver
2. based on nvidia ion vga driver

We have problem with rendering on the nvidia thin client. For example, if open on rdp excel, drag and scroll down, he infinite scrolling down without an opportunity to stop begins. On intel video we no have this problem. Driver from nvidia normaly no work on thin client. 
With Regards Artem. Thank you.

**Comment by SoNWarrioR** [comment]
lshw -c video
`*-display
    description: VGA compatible controller
    product: ION VGA
    vendor: NVIDIA Corporation
    physical id: 0
    bus info: pci@0000:02:00.0
    version: b1
    width: 64 bits
    clock: 33MHz
    capabilities: pm msi vga_controller bus_master cap_list rom
    ocnfiguration: driver=nouveau latency=0
    resources: irq:25  memory:fb000000-fbffffff memory:e0000000-efffffff memory:f8000000-f9ffffff ioport:ec00(size=128) memory: c0000-dffff`

**Comment by Thinstation** [comment]
Is this still an issue?

**Comment by SoNWarrioR** [comment]
Hello.
On new version thinstation not ckecked it. Did you manage to check this problem?

**Comment by Doncuppjr** [comment]
I have no idea. I don't have the system that was failing.
    On Wednesday, December 5, 2018, 4:18:46 PM PST, SoNWarrioR <notifications@github.com> wrote:  
 
 
Hello.
On new version thinstation not ckecked it. Did you manage to check this problem?

**Comment by SoNWarrioR** [comment]
> I have no idea. I don't have the system that was failing. On Wednesday, December 5, 2018, 4:18:46 PM PST, SoNWarrioR <notifications@github.com> wrote: Hello. On new version thinstation not ckecked it. Did you manage to check this problem? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

I try, now i don't work there anymore, but I'll ask a former co-worker.
