### ISSUE TITLE
Connecting to a RDP session with a laptop.[SOLVED]

### ISSUE THREAD

**Issue by Erirt** [Thinstation/thinstation#196]
Hi everyone.

I'm currently working at a hospital and i'm trying to use some of our old laptop as thin clients.

We already have quite the amount of thinstation( 5.1) on wired computers, but after 3 days of effort I can't seem to find how to apply a wireless configuration.

So, I'm using Thinstation 5.4 for this one. I have looked for every known issue about wireless connection ( autonet missing, wireless package missing etc etc ) and I can't find where I am wrong.

So basically, when I boot on my ISO, and access the console, there's no ip adress on the interfaces ( wired or wireless ) and obviously I can't connect to anything... I have tried several things... hope you can help ! 

Here are my conf files, I have removed sensible data, RDP parameters are correct so you don't need to see it :p 

I want to use static adress on this laptop, that's why wpa-supplicant is commented.

Thanks in advance for your help, and sorry for my english.

#####################################################################
#####################################################################

#####################################################################
# Système	#
#################
AUDIO_LEVEL=90
MIC_LEVEL=0
CLOCK=24HR
TIME_ZONE=Europe/Paris

TFTP_BLOCKSIZE=1024
BIND_MOUNT0="home:/root"
BIND_MOUNT1="boot:/boot"
BIND_MOUNT2="tsdev:/thinstation"

USB_ENABLED=ON
USB_STORAGE_SYNC=ON
USB_MOUNT_USELABEL=Yes
USB_MOUNT_OPTIONS="rw"

X_NUMLOCK=ON

STORAGE_CONFIG1=/mnt/usbdevice/THINSTATION/

SAMBA_SECURITY=user
SAMBA_WORKGROUP=WORKGROUP

#DEBUGPAUSE=TRUE
#####################################################################

#####################################################################
# Network	#
#################
NET_USE=BOTH
NET_USE_DHCP=OFF

NET_HOSTNAME=WIFI_229		
NET_FILE_ENABLED=OFF
NET_TELNETD_ENABLED=ON

NET_IP_ADDRESS=192.168.x.y	
NET_MASK=255.255.255.0		
NET_GATEWAY=192.168.x.y	

NET_DNS1=192.168.x.y		
NET_DNS1=192.168.x.y		
NET_DNS_SEARCH=DNS name 	

WIRELESS_ESSID="myessid"
WIRELESS_MODE="managed"
#WIRELESS_WPAKEY="mykey"
WIRELESS_DRIVER="wext"

NET_TIME_SERVER="myservername"
NET_REMOTE_ACCESS_FROM="0.0.0.0"
#####################################################################

#####################################################################
# ThinStation	#
#################
RECONNECT_PROMPT=MENU01
NO_SESSION="poweroff"

#################
# Session xfwm4
###
#SESSION_0_TYPE=xfwm4
#SESSION_0_AUTOSTART=ON

#XFWM4_COMPOSITING=TRUE
#XFWM4_BRIGHTNESS="-33"
#XFWM4_THEME=Default
#XFWM4_RED=0
#XFWM4_BLUE=0
#XFWM4_GREEN=0

#################
# Session icewm
###
#SESSION_0_TYPE=icewm
#SESSION_0_AUTOSTART=OFF

#ICEWM_THEME=blueCrux

#################
# Session rdp
###
SESSION_0_TITLE=""
SESSION_0_TYPE=
SESSION_0_FREERDP_SERVER=
SESSION_0_FREERDP_OPTIONS=
SESSION_0_AUTOSTART=ON

#X_DPI=100
#USE_XRANDR=TRUE
#XRANDR_OPTIONS="-s 1680x1050"
#MEMORY_CONSTRAINED="TRUE"
#SESSION_1_FIREFOX_HOMEPAGE=http://www.doncuppjr.net/projects
DESKTOP_ICON_SIZE=48
DESKTOP_FONT_SIZE=8
GTK_THEME=Xfce
PANEL_PAGER=false
PANEL_USER=false
PANEL_REV_CLOCKSYSTRAY=true
ICONS_THEME="gnome"
ICONS_CUT_SIZES="256x256 scalable"
#SERVER=192.168.21.100
#MENU_SHOWRES=off
#MENU_SHOWAPPS=off
#MENU_SHOWABOUT=off
#MENU_SHOWLOGOUT=off
#HIDE_CONTROLS=on
#SCREEN_BLANK_TIME=0
#SCREEN_STANDBY_TIME=0
#SCREEN_SUSPEND_TIME=0
#SCREEN_OFF_TIME=0
#SCREEN_HORIZSYNC="30-70 | *"
#DONT_VT_SWITCH_STATE=TRUE
#DONT_ZAP_STATE=TRUE
#ALWAYS_ENTER_SERVER=TRUE
#FASTBOOT_URL=http://192.168.21.51
#EGALAX_DEVICE=/dev/ttyS1
#EGALAX_DEVICE=usbauto
#EGALAX_PARAMFILE=/boot/eeti.param
#X_DRIVER_OPTION1="HWcursor False"
#X_DRIVER_OPTION2="PanelSize 1024x600"

################################################
################################################

########################################################
########################################################
################################################
################################################

#!Hardware
#!!Machine module list
#machine m704				# Gigabyte m704 Rover PC
#machine WYSE9150se			# WYSE 9150se Thin Client
#machine NT-A3500			# Foxconn AMD E-350 Barebone
#machine NT-535				# Foxconn Intel D525 Barebone
#machine Dell-FX170			# Dell FX170 D525 Atom Machine
#machine VMWare				# A good set of modules for a VmWare Virtual Machine
#machine Virtualbox-4.1			# A good set of modules for a Virtualbox Virtual Machine
#machine VIA-Epia-CLE266		# VIA Epia/Eden based on the the CLE266 chip. Rather common in thin clients a few years old
#machine classic_generic		# Big list of modules that you can choose by unremarking them
#machine IGEL-M300C                     # Igel CX700 Via
#machine HP-t5135                       # HP CX700 Via

#!!Wireless Stuff
#package wpa_supplicant
package wireless
package wifi-connect
#!!!Misc Modules

#!!Filesystem Support
# Every mounted device needs a filesystem, so choose which ones you need.
module usb-storage
#module autofs4          	# Automount and autofs support
module isofs            	# ISO9960 file system support for CDRoms
module udf			# CDRom UDF file system support
module vfat             	# Fat and VFat file system support
module ntfs             	# NTFS file system support
#module ext2             	# Ext2 file system support
#module ext3	            	# Ext3 file system support
module ext4			# Ext4 file system support
#module nfs             	# NFS file system support
#module cifs			# CIFS support (use either this or smbfs - not both)
module squashfs

#################################################
#################################################

# --- Packages to include in boot image
# --- Packages below may be "package" or "pkg"
#!!Miscellaneous
package ts-classic              # The classic ts logic for network/netfiles/hostname/mounting/telnetd/telnet/playcd
package automount
#package networkmanager
#package udisks-glue
package ntp			# Utility to obtain date & time from network
#package sound-esd		# Enable sound-esd or sound-nasd if you want to be able to control
#package sound-nasd		#  sound on your thin client from another computer or
                        	#  your remote session.
#package alsa-lib
package alsa-utils
#package gnome-media
package gnome-network-properties
package gnome-core
package volumeicon
#package kismet
#package gst-plugins-base
#package gst-plugins-good
#package crystalhd
#package libva
#package iptables		# IP Tables support
package autonet
#package cpufreq
#package cpuspeed
#package wine			# Windows Application Execution Platform

#!!X related
# --- XOrg 7.6
#package xorg7-apm
#package xorg7-ark
#package xorg7-chips
#package xorg7-cirrus
#package xorg7-glint
#package xorg7-i128
#package xorg7-mach64
#package xorg7-mga
#package xorg7-neomagic
#package xorg7-r128
#package xorg7-rendition
#package xorg7-s3
#package xorg7-s3virge
#package xorg7-savage
#package xorg7-siliconmotion
#package xorg7-sis
#package xorg7-sisusb
#package xorg7-sun
#package xorg7-tdfx
#package xorg7-tga
#package xorg7-trident
#package xorg7-tseng
#package xorg7-v4l
#package xorg7-vesa		#A fallback driver that works with almost everything. Does allow resolution changes
#package xorg7-vmware
#package xorg7-ztv	
#package xorg7-ati		#ATI video driver for most modern ATI chipsets. Usually requires several firmwares
#package xorg7-nv		#Old opensource nvidia driver
#package xorg7-nouveau		#New opensource nvidia driver
#package xorg7-nvidia		#Proprietary nvidia driver
#package xorg7-openchrome	#Via Video Chipsets driver
#package xorg7-geode		#Geode Video driver
#package xorg7-i740		#Intel video driver for really old chipsets
#package xorg7-intel		#Intel video driver for most modern chipsets except the GMA3500/3600
package xorg7-fbdev		#A fallback driver that works with almost everything. Does *not* allow resolution changes

#!!Locale or localization files for keyboard and fonts.  (Language/Country)
#package locale-cs_CZ  # Czech
#package locale-da_DK  # Danish
#package locale-de_DE  # German
#package locale-en_GB  # English-Great Britain
#package locale-en_US  # English-US
#package locale-es_ES  # Spanish
#package locale-fi_FI  # Finnish
#package locale-fr_BE  # French Belgium
#package locale-fr_CA  # French Canadian
#package locale-fr_CH  # French Switzerland
package locale-fr_FR  # French
#package locale-hr_HR  # Croation
#package locale-hu_HU  # Hungarian
#package locale-it_IT  # Italian
#package locale-ja_JP  # Japanese
#package locale-nb_NO  # Norwegian (bokmål)
#package locale-pl_PL  # Polish
#package locale-pt_PT  # Portuguese
#package locale-pt_BR  # Portuguese-Brazil
#package locale-ru_RU  # Russian
#package locale-sv_SE  # Swedish
#package locale-tr_TR  # Turkish

#!Applications
#!!Connection Package types.  Choose *at least* one!
package freerdp		# X RDP Client - fork of rdesktop
#package rdesktop		# X RDP client for Windows Terminal Services (ver 1.7)
#package vncviewer		# VNC client (vncviewer)
package xorg7vnc		# Remote Control Client Workstation
#package ica			# Citrix ICA client support
#package tarantella		# Tarantella client support
#package xnest			# XDM in a window client
#package urxvt            	# Light Xterm Client (vt102)
#package xterm           	# Xterm Client (vt220)
#package ssh 			# Secure Shell client
#package tn5250          	# 5250 terminal emulator
#package dillo			# Dillo light web browser
#package thinlinc		# Cendio ThinLinc client support
#package nx              	# No Machine NX client
#package 2x			# 2X client
#package java			# Java runtime
#package firefox_lowmem		# Firefox 3 for low resource machines
#package firefox		# Firefox current Web Browser
#package chrome			# Google Chrome Web Browser
#package kiosk			# Rkiosk Plugin for Firefox
#package flash_lowmem		# Flash 9 browser plugin for firefox and low resource machines
#package flash			# Flash Current
#package filezilla		# FileZilla FTP Client for X
#package git			# GIT Version Control System
#package gparted		# Gnome Partition Manager
#package open-vm-tools
#package medit			# Notepad
#package mplayer		# DVD and video player
#package vmview                 # VMware Open-View Client, no PCoIP
#package vmviewpcoip            # VMware Open-View Client, PCOIP
#package xbmc			# XBMC Media Center for X
#package xpdf			# X PDF Viewer

#!!Window Managers. Choose no more than 1 window manager.
# Not needed if you don t want to manage windows.
#package openbox		# A spartin clean/fast window manager.
#package xdesktop-kiosk		# A locked down desktop kiosk using the openbox wm (See packages/xdesktop-kiosk/build/conf for 
				# more help.
#package icewm			# "ICEWM" window manager.  Makes TS a light workstation.
#package icewm-theme-xp
#package icewm-themes		# Extra IceWM themes
#package icewm-theme-bernstein
#package icewm-theme-bluecrux
#package icewm-theme-liquid

package xfwm4
#package xfwm4-extra
package terminal		# Terminal emulator for xfwm4 -- Pulls in xfwm4
package thunar			# File Manager for xfwm4 -- Pulls in xfwm4

#!!Window Manager Utils
#package idle-shutdown		# Package that lets you specify automatic shutdown settings and logic.
#package wbar         		# Adds icons to desktop
#package idesk

#!!Other services
#package www 			# Web access to client.  From a browser: "http://<IP number>"
                        	#  The standard page is for general user settings, administrative access
                        	#  is on port 6800.
#package lp_server		# Remote printing daemon (JetDirect compatible)
#package lpr             	# LPR Print Server, for use with samba-server package
#package lprng           	# LPRng Print Server, supports network based printing
#package sshd 			# Dropbear secure shell server
#package tftpd 			# Built in tftpd server. Useful for making a tftpserver
				#  for thinstation on a WAN over a slow link.
#package samba-server		# Samba server FS Support, allows you to share
                        	#  local floppy/cdrom/hd/printer to other Windows
				#  PCs. Needs supermount for removeable media.
#package samba-client		# Samba smbclient, gives a shell like environment to access an samba server
#package hdupdate       	# Package for updating TS images on a hardisk over a network connection
#package scp	            	# Add ability to download files over internet using scp.  This package
                        	#  adds some networking based options for downloading configuration files or
                        	#  in using hdupdate package.
#package openvpn                # OpenVPN Client Support

#!!PCSCD Card Readers
#package gemplus410             # Card reader Gemplus 410 (Serial) and Gemplus 430 (USB)
#package ccidreader             # Generic USB card reader

#!!Miscellaneous
package gtk-2.0			# Full gtk-2.0 plus clearlooks theme
package icons-cursor		# Anti Aliased Mouse Cursor Theme
package icons-hicolor           # Hi-Color icons for some applications and themes. Does not really contain any icons.
package icons-gnome             # gnome Hi-Color icons theme. Needed by most other icon themes.
#package icons-tango             # tango Hi-Color icons theme
#package icons-neu               # neu Hi-Color icons theme
package fonts-misc
#package fonts-TTF-liberation
#package fonts-jis-misc		# Japanese Industrial
#package fonts-util
#package fonts-cyrillic
package fonts-Speedo-Bitstream
package fonts-TTF-BH		# This one works nicely most of the time and is small.
package fonts-TTF-vera
#package fonts-TTF-liberation
#package fonts-75dpi-Adobe
#package fonts-75dpi-Adobe-Utopia
#package fonts-75dpi-BH
#package fonts-75dpi-BH-Typewriter
#package fonts-75dpi-Bitstream
#package fonts-100dpi-Adobe
#package fonts-100dpi-Adobe-Utopia
#package fonts-100dpi-BH
#package fonts-100dpi-BH-Typewriter
#package fonts-100dpi-Bitstream
package fonts-Type1-Adobe-Utopia
package fonts-Type1-BH
package fonts-Type1-Bitstream
package fonts-Type1-IBM
package fonts-Type1-xfree86
#package lshw			# list hardware
#package e3 			# Basic vi like Editor
#package rox			# Basic File Manager
#package debug			# metapackage to include other debugging packages and stop during bootup to check things.
#package extensions		# Adds various shell commands, will increase image size.
#package extensions-x		# Adds various utility s for the X Environment !!!! INCLUDES hwlister.sh !!!!
#package eGalax                 # eGalax TouchKit Drivers/Utility for serial and usb touchscreens by EETI.
#package installer		# Wipes a drive, makes partitions and downloads thinstation from a pxe server
#package devstation		# Starts a tftp server that hosts files from the boot-images/pxe folder

# Parameters
########################################
########################################
#!!Basic

#param fastboot       true				# Mangles the filesystem a special way as to improve boot spead and reduce
							# memory utilization. Cool/Dangerous . Harder to dubug other packages. (Finishing Touch)
							# Set to 'true' to enable or 'lotsofmem' for slightly slower booting but no squash lag on app launch.
#param tsuser         tsuser                            # Name of the user that thinstation will run as. Needs userauto package.
param rootpasswd     mypassword			# Do Change!  Console/telnet password for root
                                        		# If this is enabled, Telnetd will be enabled.
param xorgvncpasswd  mypassword			# VNC Access Password
param storagepasswd  mypassword				# Password for storage server
param dialuppasswd   mypassword				# Password for dialin account
param sambapasswd    mypassword	  			# Password for samba shares when using user mode security
#param kernelcmdline "radeon.modeset=0"                 # Add additional kernel command lines. e.g. disable radeon framebuffer
#param stripelf       yes				# Strip extraneous information from elf binaries (Maybe not Safe)
#param acpisupport    disable				# Tells the kernel not to load acpi modules. (Breaks some Intel Chipsets if disabled)
#param uvesafb        disable				# Disable uvesafb (legacy option like modesetfb)
#param extra_vid      LVDS-1:d				# Add an extra video= parameter to kernel cmd line (good for disabling outputs on video cards)
param bootlogo       true				# Enable or Disable the use of the Boot splash.
param boottheme	     default           			# Backgound picture during boot
#param splash	     verbose				# kernel splash setting (0=off, silent or verbose (default=silent)
param splash	     silent
param fbmtrr         0                                  # MTRR value for uvesafb (default = 0, 4 is the best) grep your log to make sure you have not set it to high
#param fbnocrtc      true                               # This is usually a good thing.
param fbsm           ywrap                              # Window scrolling method (redraw, ypan, ywrap) ywrap is best, but may not work correctly for all people
#param fbvtotal       16                                # Override Video Bios Reported Memory in MB
#param fbmaxhf        67                                # Override Video Negotiated Max Horizontal Frequency
#param fbmaxvf        61                                # Override Video Negotiated Max Vertical Frequency
#param fbmaxclk       155                               # Override Video Negotiated Max Clock Frequency
#param fbnoedid       true                              # Don t do video edid
#param bootresolution 1024x600-32                       # Resolution used during Thinstation boot.
param bootresolution 1024x768-32                        # You can wright your own resolution mode here, if you know it.
#param bootresolution 1152x864-32
#param bootresolution 1280x768-32
#param bootresolution 1366x768-32                       # Otherwise, you may want to refer to the vbe_modes.list you created with hwlister.sh
#param bootresolution 1280x1024-32                      # for modes that your card supports.
#param bootresolution 1400x900-32                       # It is also used by xrandr if no xrandr options are specified.
#param bootresolution 1680x1050-32
#param bootresolution 1920x1080-32
#param bootresolution 1400x1050-32

#param desktop file:./backgrounds/White_And_Blue_bg.jpg	# Custom image to load as desktop background
param defaultconfig  thinstation.conf.buildtime  	# The file with default setup.  No other config file is found
                                                 	#  during boot.
param basename       thinstation     			# Used for all config/tftp/scp file names
param basepath       ts5.0               		# Used to determine path to tftp/scp files
#param baseurl        http://www.doncuppjr.net		# Used to determine url to wget files
#param keyfile        ./id_rsa       			# Path for private key file used for ssh/scp
#param knownhosts     ./known_hosts  			# Path for ssh known_hosts file for ssh/scp
#param localpkgs      false				# to determine is PKG files are to be loaded locally
param fulllocales    true	      			# Use full locale support for packages
#param icaencryption  false      			# Use ica encryption support, add 290k to image
param haltonerror    false				# Will halt on error, default is true
param hardlinkfs     true
param sametimestmp   true                               # When enabled, the timestamps for all files and folders will be set to 00:00 of todays date in your timezone
param initrdcmd	     "gzip -9"				# Compression mode and level of initrd file. none, gzip -9, lzma -9 ,bzip2 -9
param bootverbosity   3          			# Increased vebosity when booting TS
                                			#   0 no verbose messages
                                			#   1 boot
                                			#   2 network
                                			#   4 init
                                			#   8 kernel
                                			#  16 modules
                                			#  32 packages
                                			#  64 email bootlog file to SMTP server & user set in
                                			#     thinstation.conf file.  This will only work
                                			#     if networking is working.
                                			#
                                			#  Combinations can be used (e.g.12 does Kernel and Module Messages)

#!!Advanced
# Leave this alone unless you can t download (wget required on your Linux box):
param downloads         /downloads
param bootimages        "iso syslinux pxe"
param syslinuxtheme     "default"
#param httpproxy	http://192.168.1.2:8080

#param bootfssize     50%                               # Modify the size of the tmpfs filesystem

#package alltimezone
#package allres				# Includes a lot of resolution splash images for live-cd s
#package allfirmware			# Includes a lot of firmwares for live-cd s

**Comment by Doncuppjr** [comment]
If you are connecting to a wpa protected network, you need wpa_supplicant. IP address is one layer of the OSI higher, so unrelated.

**Comment by Erirt** [comment]
Yesterday I have made some tests. When I boot my iso on a wired computer there's no issue, ip configuration is okay and I can reach my rdp server. I think it comes from the network card driver, because on the laptop, when I access the console as root, "none" is shown instead of WIFI_229.

**Comment by Erirt** [comment]
Sooooooo,

I managed to fix drivers issue, my Thinstation has taken into account the host name ( WIFI_229 ) but doesn't seem to apply ip configuration for the wireless interface.( But at least I can see it now )

I'm completely stuck. Changing ip config manually doesn't work either. I have looked for every topic I could find on internet and can't find the solution...

**Comment by Doncuppjr** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Sounds like a driver issue. All modules/allfirmware and build?


Sent from Yahoo Mail for iPhone


On Friday, December 30, 2016, 12:12 AM, Erirt <notifications@github.com> wrote:


Yesterday I have made some tests. When I boot my iso on a wired computer there's no issue, ip configuration is okay and I can reach my rdp server. I think it comes from the network card driver, because on the laptop, when I access the console as root, "none" is shown instead of WIFI_229.

**Comment by Doncuppjr** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } So I would start with a less specific image, and let's do some diagnostics. We will make an default build allmodules/allfirmware and make sure we have networkmanager instead of autonet. Boot the image and connect to the wireless like you would with a regular desktop.


Sent from Yahoo Mail for iPhone


On Friday, December 30, 2016, 5:42 AM, Erirt <notifications@github.com> wrote:


Sooooooo,

I managed to fix drivers issue, my Thinstation has taken into account the host name ( WIFI_229 ) but doesn't seem to apply ip configuration for the wireless interface.( But at least I can see it now )

I'm completely stuck. Changing ip config manually doesn't work either. I have looked for every topic I could find on internet and can't find the solution...

**Comment by Erirt** [comment]
I'll try this. Thank you for your advices, i'll keep you update.

**Comment by Erirt** [comment]
After making a clear iso without any parameters but packages/firmwares, I am able to see all of my networks, wired and wireless, but now there's another problem.

I can connect to the wired one, using a special static IP reserved for temporary settings ( when we make laptop with windows, we first connect it on wired network to gather certificate and some drivers, using the ip 10.200, then we swap to wifi. )

Problem is, to connect to wifichp, the computer need to be in the domain and I can't see how I can do that... I've read some things about kerberos and stuff but I would like to find a less invasive solution, before complicating my install.

So, right now, I have access to internet with my static IP 10.200 on my Vlan 10. But It doesn't allow me to connect on my rdp server ( wrong certificate ), neither I can connect to my wireless network because I am not in the domain.

I may sound a bit unqualified regarding all of this, but I started this job 3 month ago and the only skills I had previously was software developpment. So this is all new to me and I wish I can sort this out without asking my co-workers...

Sum up : 
- connected to wired network on Vlan 10 with static 10.200
- can use internet freely and ping/be pinged on the network
-can't connect to wifichp because it requires to be included in the domain 
- can't find how to include my thinstation in the domain
- can't connect to the rds server because of wrong certificate.

Any advice would be good, tho you did really help me with your previous posts. I'll keep on searching about kerberos servers and see if it is a viable solution ( meaning, if I can deploy it without breaking everything.)

**Comment by Doncuppjr** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } So your dealing with 802.1x eh?
Well that's both good and trickey. A device need not be joined to a windows domain to participate in an 802.1x network. A modern windows domain does assign a certificate automatically to domain joined clients, but that's not the only way to get it done. You need to work out how to assign machine certs to non-domain joined devices, then decide where and how you want to store certs for TS clients.

Sent from Yahoo Mail for iPhone


On Tuesday, January 3, 2017, 4:36 AM, Erirt <notifications@github.com> wrote:


After making a clear iso without any parameters but packages/firmwares, I am able to see all of my networks, wired and wireless, but now there's another problem.

I can connect to the wired one, using a special static IP reserved for temporary settings ( when we make laptop with windows, we first connect it on wired network to gather certificate and some drivers, using the ip 10.200, then we swap to wifi. )

Problem is, to connect to wifichp, the computer need to be in the domain and I can't see how I can do that... I've read some things about kerberos and stuff but I would like to find a less invasive solution, before complicating my install.

So, right now, I have access to internet with my static IP 10.200 on my Vlan 10. But It doesn't allow me to connect on my rdp server ( wrong certificate ), neither I can connect to my wireless network because I am not in the domain.

I may sound a bit unqualified regarding all of this, but I started this job 3 month ago and the only skills I had previously was software developpment. So this is all new to me and I wish I can sort this out without asking my co-workers...

Sum up :
   
   - connected to wired network on Vlan 10 with static 10.200
   - can use internet freely and ping/be pinged on the network   
-can't connect to wifichp because it requires to be included in the domain
   - can't find how to include my thinstation in the domain
   - can't connect to the rds server because of wrong certificate.

Any advice would be good, tho you did really help me with your previous posts. I'll keep on searching about kerberos servers and see if it is a viable solution ( meaning, if I can deploy it without breaking everything.)

**Comment by Erirt** [comment]
"So your dealing with 802.1x eh?
Well that's both good and trickey. A device need not be joined to a windows domain to participate in an 802.1x network. A modern windows domain does assign a certificate automatically to domain joined clients, but that's not the only way to get it done. You need to work out how to assign machine certs to non-domain joined devices, then decide where and how you want to store certs for TS clients."

Thanks a lot ! 

It is indeed exactly what happens on my network. I was able to reach my rds server on wired connection using /cert-ignore, but it is clearly not optimal. I'll look for a solution, as you said, to grant access to non-included machines.

I'm close, thanks again !

**Comment by Doncuppjr** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } While an RDS server cert can be used as a machine cert for 802.1x, the two are really not part of the same auth mechanism. Even after getting certs into the client for 802.1x port authentication, you still need to tell it which server certs or CA's to trust.


Sent from Yahoo Mail for iPhone


On Tuesday, January 3, 2017, 5:31 AM, Erirt <notifications@github.com> wrote:


"So your dealing with 802.1x eh?
Well that's both good and trickey. A device need not be joined to a windows domain to participate in an 802.1x network. A modern windows domain does assign a certificate automatically to domain joined clients, but that's not the only way to get it done. You need to work out how to assign machine certs to non-domain joined devices, then decide where and how you want to store certs for TS clients."

Thanks a lot !

It is indeed exactly what happens on my network. I was able to reach my rds server on wired connection using /cert-ignore, but it is clearly not optimal. I'll look for a solution, as you said, to grant access to non-included machines.

I'm close, thanks again !

**Comment by Erirt** [comment]
After some research, I won't be able to do it on my own. First because i'm clearly unqualified to go yolo and modify security parameters, and second,because my co-workers are absent untill next week so I can't really ask for approbation...

BUT, problem solved, I know now why I had trouble first, and my thinstation can connect to my rds server using public wifi, so, mission accomplished (sort of, it's not optimal because of the public wifi and the lack of certificate ). I'll discuss with my co-workers next week to see if we do any modification on our security to allow non-domain joined. Our network only allows Computer from the domain to join. I think if we allow authentified users as well, my thinstation could connect to the wifi using its domain credentials, but I'll see with them.

Thanks a lot, you really helped me and I learned a lot of things !!!
