### ISSUE TITLE
Help me for a launch scrypt and put my ISO image on TFTP server

### ISSUE THREAD

**Issue by bopowwa** [Thinstation/thinstation#197]
Hi it is with a little of evil that I created my image for my thinstation.

He misses me that 2 stages that is why I need your help!

The first one : i would be,  in the starting up of my station, starts only on a rdesktop session (in the ideal on a disctinct server by group. I do not know which file to modify to make it "thinstation.conf.buildtime"?

The second it is because I did not much understand to load how my image in PXE, I would like more advice at present I work with the .ISO and I start it on my pc via USB.
In the final everything must be stored in the server so that nothing is write on the hard disk.

**Comment by Thinstation** [comment]
https://youtu.be/9R5eKjE618s
