### ISSUE TITLE
Russian layout of the keypad in rdesktop

### ISSUE THREAD

**Issue by shweew** [Thinstation/thinstation#198]
In standard delivery of Caps Lock works incorrectly.
Replace please with the enclosed file.
[ru.zip](https://github.com/Thinstation/thinstation/files/736740/ru.zip)

**Comment by Doncuppjr** [comment]
Replace what? Where does this go?

**Comment by shweew** [comment]
packages/rdesktop/build/extra/lib/rdesktop/keymaps/

2017-11-28 19:03 GMT+04:00 Donald A. Cupp Jr. <notifications@github.com>:

**Comment by trentasis** [comment]
generate pr with this file

**Comment by Thinstation** [comment]
Pull Request

**Comment by Thinstation** [comment]
Attachments won't go through.

**Comment by Thinstation** [comment]
Shouldn’t this go upstream into the rdesktop project?

**Comment by shweew** [comment]
Approved these changes into the rdesktop project.
