### ISSUE TITLE
Thin Client N380 CLG7700 800MHz TS660

### ISSUE THREAD

**Issue by tuman31** [Thinstation/thinstation#199]
Hello
 have ThinClient TS660 CLG7700 800MHz.
The board has a connector UART Rx/Tx (socket J11 & J13). 
Help me find where Rx, Tx, Gnd, +5V, 3v3.

Maybe your have datasheet for a scheme? spica 121130 ver:3.1

**Comment by trentasis** [comment]
Is this a thinstation issue?
