### ISSUE TITLE
Use signed version of rkiosk

### ISSUE THREAD

**Issue by Skinney** [Thinstation/thinstation#200]
The kiosk firefox plugin does not work as it is not signed, and firefox refuses to load it. Easily solved by using a signed version (0.9.0.1 instead of 0.9.0.0).

I would send a PR, but am not familiar enough with thinstation to know how this is done.

**Comment by Thinstation** [comment]
So the real problem is that we unzip the plugin and make changes to it. This breaks the signing. We would have to put it back together and submit for signing again.

**Comment by Thinstation** [comment]
I think this plugin is deprecated. We should delete it.
