### ISSUE TITLE
Freerdp dollar in password fails

### ISSUE THREAD

**Issue by alexcrow** [Thinstation/thinstation#204]
Hi,

I've been having a play with devstation for access to a Windows rdp cluster. Using the built-in gtkdialog prompt, which I need for NLA auth, users who have dollar characters in their passwords cannot sign in successfully. I've had a look around all the scripts involved but I just can't seem to find any place where I can fix this issue.

Can anyone please help with this niggle?

Many thanks

Alex

**Comment by Thinstation** [comment]
So, I looked at the code that handles the password in the TS dialogs, and we pass the password around in a quoted string until it is finally handed to xfreerdp as such. If there is a bug related to dollar signs, it will be in that code.

**Comment by alexcrow** [comment]
Hi,
It's definitely not related to xfreerdp. The same password works ok in freerdp from the command line.
I think it's something in gtkdialog itself that's causing the problem.

**Comment by Doncuppjr** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } I did set -x, and I was able to see that we correctly hold the password in a quoted string. The $ is there the whole time, and passed to the xfreerdp cmd.


Sent from Yahoo Mail for iPhone


On Tuesday, March 14, 2017, 5:14 AM, alexcrow <notifications@github.com> wrote:


Hi,
It's definitely not related to xfreerdp. The same password works ok in freerdp from the command line.
I think it's something in gtkdialog itself that's causing the problem.

**Comment by trentasis** [comment]
Verified, works correctly with gtk dialog with pwd taht contains $

**Comment by iceemike** [comment]
I'm having the same issue and it does seem like the GTK dialog is causing it. I placed set -x in dialog.functions and the run_dialog() function it is not holding the password with a dollar sign correctly. 

++ run_dialog
++ I='
'
++ IFS=
+++ gtkdialog -c --program=MAIN_DIALOG
++ for STATEMENTS in '$(gtkdialog -c --program=MAIN_DIALOG)'
++ eval 'DIALOG_OPTIONS="/rfx /gfx-h264 /sec:nla /d:DOMAIN
/dvc:urbdrc,dev:04df:0030#04df:0012#04df:001f +auto-reconnect
/auto-reconnect-max-retries:0"
DIALOG_PASSWORD="23$temp12#"
DIALOG_SERVER="XXXXXX.XXXXX"
DIALOG_USER="test"
windowed="false"
EXIT="ok"'
+++ DIALOG_OPTIONS='/rfx /gfx-h264 /sec:nla /d:DOMAIN
/dvc:urbdrc,dev:04df:0030#04df:0012#04df:001f +auto-reconnect
/auto-reconnect-max-retries:0'
+++ DIALOG_PASSWORD=23#
+++ DIALOG_SERVER=XXX.XXX
+++ DIALOG_USER=test
+++ windowed=false
+++ EXIT=ok
++ IFS='
