### ISSUE TITLE
Stops RDP session

### ISSUE THREAD

**Issue by DS455** [Thinstation/thinstation#205]
Hey. I use old hardware (motherboard asus p5pe-VM, Celeron D 2.5, 2GB RAM) to connect to the terminal server (RDP). When you open a heavy sites, the client hangs. How do I fix this problem? Thinsttaion 5.5.

**Comment by ecoutinho** [comment]
I'm also having that same issue using freerdp: the session freezes when the browser is on a site with lots of activity (usually publicity boxes). I've found this fix that seems to address that problem:

https://github.com/FreeRDP/FreeRDP/pull/3364

It was created in october, while thinstation's freerdp was compiled in june. 

So, how can freerdp be update to the latest git version?

**Comment by Doncuppjr** [comment]
cd /ts/ports/opt/freerdpnano Pkgfilechange some stuff or don't, it already uses git.ctrl-o to save, ctrl-x to exit nano.pkgmk -d -if -impkgmk -uupdate freerdpcd /build./build yada yada 

    On Thursday, March 2, 2017 6:48 AM, Elio Coutinho <notifications@github.com> wrote:
 

 I'm also having that same issue using freerdp: the session freezes when the browser is on a site with lots of activity (usually publicity boxes). I've found this fix that seems to address that problem:FreeRDP/FreeRDP#3364It was created in october, while thinstation's freerdp was compiled in june.So, how can freerdp be update to the latest git version?—

**Comment by ecoutinho** [comment]
Thanks! I've confirmed that Pkgfile is already configured to use latest git version, so I've just updated freerdp before building. I'm repeating the commands for better reading:

`cd /ts/ports/opt/freerdp/`
`pkgmk -d -if -im`
`pkgmk -u`
`update freerdp`
`cd /ts/build`

**Comment by DS455** [comment]
I did not understand that to register in this file Pkgfile

**Comment by ecoutinho** [comment]
As I said, you don't need to edit  Pkgfile, just execute the previous commands to update freerdp before building TS.

**Comment by trentasis** [comment]
Hi @Doncuppjr @DS455 

With pull request:
https://github.com/Thinstation/thinstation/pull/208
https://github.com/Thinstation/thinstation/pull/209

will solve many bugs with freerdp and pcscd and ccid, @Doncuppjr  can you rebuild 3 packages with Ts 5.4 and 5.5 (freerdp pcsc-lite and ccid)

Thanks!

**Comment by ecoutinho** [comment]
I confirm that after updating freerdp to the latest git version, the problem described did not appear any more.
