### ISSUE TITLE
freerdp gtk dialog issues (mouse cursor & change password)

### ISSUE THREAD

**Issue by trentasis** [Thinstation/thinstation#210]
Hi,

I have detected two issues with gtkdialog and freerdp:

1) When you use freerdp with gtk dialog as frontend and you move mouse cursor out of gtk dialog, then you can try to enter any char to username/password, but keyboard is not working... until you move mouse cursor into gtk dialog.
When thinstation boots by default focus is correct in username and cursor in the middle of screen (in gtk dialog), but sometime users move cursor out of gtk dialog...
Where is the problem and how can I solve this?

2) When users logs on and must to change password and after to enter new password (2 to confirm new password), password is changed, but then, first log on after this change fails, It seems that gtk dialog have saved password entered before password change. After this users log in fails, and user must log on with new password and then works!
I suspect that this is the problem...

Thanks

**Comment by Thinstation** [comment]
XFWM?

**Comment by trentasis** [comment]
Not, without xfwm, session 0 is freerdp or rdesktop without X manager

2017-04-12 17:59 GMT+02:00 Thinstation <notifications@github.com>:

**Comment by Thinstation** [comment]
I suspected so. Use a window manager, and your issue goes away.

**Comment by trentasis** [comment]
Thanks, we will try...



2017-04-13 14:48 GMT+02:00 Thinstation <notifications@github.com>:
