### ISSUE TITLE
Update ocsinventory-agent to version 1.2

### ISSUE THREAD

**Issue by jackburton79** [Thinstation/thinstation#215]
Hi, I fixed a couple of things in my ocsinventory agent.
Specifically, I added a new option (-D) to daemonize the process and thus avoiding slowing down boot.

The new source is available here:
https://github.com/jackburton79/agent/archive/v1.2.tar.gz

I'll try to create a patch, if no one gets there first (I'm still catching up with thinstation, since we still use version 5.2 where I work).

**Comment by jackburton79** [comment]
#216

**Comment by jackburton79** [comment]
Other changes in this version:
The agent no longer creates a file in the current directory if launched without configuration.
There is now a specific option to do that (but I guess it won't ever be used in Thinstation like that).

**Comment by Thinstation** [comment]
Done.
