### ISSUE TITLE
flexible network configuraton in liveCD

### ISSUE THREAD

**Issue by chichangspawar** [Thinstation/thinstation#217]
As a newbie of thinstation, I just install the thinstation (5.5.1) on my VMware player and used DevStaion to create my first bootable thinstation liveCD.  It looks good.  However, I intend to use the TC LiveCD in our network which does not provide DHCP, so each of LiveCD has its static IP to use when lodging into our network.  I did not find any network configuration capability in my first liveCD iso and when I reviewed the build.conf and thinstation.conf.buildtime, I did not find any related, except package neworkmanager (which is enabled by default).  I found in another site about network setup with no DHCP. But it requires to assign a static ip and related detail. Is there another way to build the iso with flexible network configuration, so I do not need to create the liveCD individually, i.e. only configuring the static ip when connect to Network?

**Comment by Thinstation** [comment]
You can customize and add the following lines to your thinstation.conf.user file.
NET_IPV4_MODE=manual
NET_IPV4_ADDRESS=192.168.1.10/24
NET_IPV4_GATEWAY=192.168.1.1
NET_IPV4_DNS1=192.168.1.1
NET_IPV4_DNS2=8.8.8.8
NET_IPV4_DNS_SEARCH=thinstation.local

**Comment by trentasis** [comment]
Solved?
