### ISSUE TITLE
package chrome and flash failure

### ISSUE THREAD

**Issue by chichangspawar** [Thinstation/thinstation#218]
I selected the chrome and flash packages within the build.con to build a new iso.  However, when it built, both packages were failed to downloaded, the installation logs responded with ERROR: Not Found. I saw the ip dest been accessed on both.  Are there any deeper conf needed to be updated?   This is based on 5.5.1 stable iso.

**Comment by Thinstation** [comment]
Flash can be updated, but google dropped 32 bit last year, and they don't
maintain downloads for older builds.

**Comment by chichangspawar** [comment]
Thanks.  so how to update the flash package? when it built and failed at flash, the build aborted. Do i need to change some other conf file?  I intend to use this liveCD to access the vmware vsphere through its web service. vsphere (ver > 6) provides html protocol but old version need the flash as plugin or extension.  I noticed that chrome provides better extension/plugin than that of chromium.   Based on the chromium package, it might work.

**Comment by Doncuppjr** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } build.urls


Sent from Yahoo Mail for iPhone


On Saturday, April 8, 2017, 10:08 AM, chichangspawar <notifications@github.com> wrote:


Thanks. so how to update the flash package? when it built and failed at flash, the build aborted. Do i need to change some other conf file? I intend to use this liveCD to access the vmware vsphere through its web service. vsphere (ver > 6) provides html protocol but old version need the flash as plugin or extension. I noticed that chrome provides better extension/plugin than that of chromium. Based on the chromium package, it might work.

**Comment by chichangspawar** [comment]
Your answer totally confused me.  Do you mean to comment out the flashurl in build.urls ?

**Comment by Thinstation** [comment]
Update to something that works. I have done this now, and it should work now in master and 5.5-Stable.
