### ISSUE TITLE
linux distribution 

### ISSUE THREAD

**Issue by chichangspawar** [Thinstation/thinstation#221]
I used UNetbootin to burn a bootable USB with thinstation iso.   Does anyone know which distribution of the thinstation belongs to? I use the Debian (NetInstall).  It worked.  I might be lucky. But what exact distribution of TS should be?

**Comment by Thinstation** [comment]
None of the standard ones. ThinStation is based on it's own binaries. It barrows a source based package management system from crux, several packages from crux, arch linux, debian, fedora, ubuntu and suse. It comes with it's own utility for making bootable thumbdrives. mkmbrdrv or mkgptdrv depending on the desired end result.
