### ISSUE TITLE
remote-viewer does not support USB redirection

### ISSUE THREAD

**Issue by watertoeast** [Thinstation/thinstation#224]
Add package spice to build.conf, the remote-viewer run ok, but it does not support USB redirection, the menu 'File--USB device selection' is gray.

**Comment by qixuxiang** [comment]
Can a thinstation implement USB redirection via rdesktop other than spice?

**Comment by Thinstation** [comment]
http://www.incentivespro.com/usb-server-rdp.html

**Comment by Thinstation** [comment]
Is this still an issue?

**Comment by qixuxiang** [comment]
NO
