### ISSUE TITLE
Missing tool cryptmd5

### ISSUE THREAD

**Issue by BobFox2** [Thinstation/thinstation#225]
I have a problem with installing Tinstation (DeStation) in Hyper-V on Ubuntu 16

Git clone is successful 
Setup-chroot is successful

./build give a lot of error of missing tools. I can find them all except one that is crypymd5. 

./build
Checking for required commands... FAIL
Your Thinstation installation is broken; the following needed tools
are missing: cryptmd5
This build system requires them; aborting build
Are you inside the chroot environment?

Can someone please tel me how I can get cryptmd5?

King regards,
Bob

**Comment by Doncuppjr** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } ./setup-chroot cd /build./build


Sent from Yahoo Mail for iPhone


On Tuesday, April 25, 2017, 1:27 AM, BobFox2 <notifications@github.com> wrote:


I have a problem with installing Tinstation (DeStation) in Hyper-V on Ubuntu 16

Git clone is successful
Setup-chroot is successful

./build give a lot of error of missing tools. I can find them all except one that is crypymd5.

./build
Checking for required commands... FAIL
Your Thinstation installation is broken; the following needed tools
are missing: cryptmd5
This build system requires them; aborting build
Are you inside the chroot environment?

Can someone please tel me how I can get cryptmd5?

King regards,
Bob

**Comment by amilom** [comment]
So where can I find this utility and how to install it?

**Comment by Thinstation** [comment]
You will need to be inside the chroot environment for any TS specific
commands to work. ./setup-chroot to enter.
