### ISSUE TITLE
Issue Logitech wireless keyboard K270

### ISSUE THREAD

**Issue by trentasis** [Thinstation/thinstation#226]
Hi,

Using Thinstaiton 5.4 and a wireless keyboard k270 (Logitech) we have detected that some keys are not working, we are using spanish locale and rdesktop with spanish locale. Other keyboards are working great, and only with this keyboard.

also tried to connect this keyboard (wireless) and also other keyboard that is working, then both keyboards are working without issues...

Any suggestions about where is the issue?

thanks

**Comment by Thinstation** [comment]
It's gonna be a udev rule. Likely one of the default ones that come
standard with udev.

**Comment by trentasis** [comment]
Hi,

Can you give more information about how to find this issue?
Thanks

**Comment by Thinstation** [comment]
http://naiveprogrammer.blogspot.com/2011/01/using-udev-to-catch-keyboard-and-mouse.htmlhttps://superuser.com/questions/249064/udev-rule-to-auto-load-keyboard-layout-when-usb-keyboard-plugged-in

**Comment by trentasis** [comment]
I have searched in default udev rules from thinstation and I can't find any confguration related with this keyboard issue... any suggestion?

also I have found same error in thinstation list, but not sure if It was solved  http://thinstation.4464.n7.nabble.com/logitech-k270-wireless-keyboard-bad-spanish-mapping-td25895.html

**Comment by Doncuppjr** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } I dunno, we use the rules that come with udev. The KEYBOARD_MAP var was deprecated for LOCALE. If multiple locales are included in the build, and one is not specified with LOCALE, then the last one alphabeticaly, is selected by default.


Sent from Yahoo Mail for iPhone


On Thursday, May 4, 2017, 12:41 PM, trentasis <notifications@github.com> wrote:


I have searched in default udev rules from thinstation and I can't find any confguration related with this keyboard issue... any suggestion?

also I have found same error in thinstation list, but not sure if It was solved http://thinstation.4464.n7.nabble.com/logitech-k270-wireless-keyboard-bad-spanish-mapping-td25895.html

**Comment by trentasis** [comment]
I have made some test and from command line ctrl+alt+f2, works without problems, and problems is reproduced only in Xorg session, but if you execute 

 setxkbmap -layout es

then start to work!

Also detected if you have this wireless keyboard and other keyboard that always work, then both keyboards are working...

It seems a Xorg bug with some wireless keyboards

more information 
https://bugs.freedesktop.org/show_bug.cgi?id=49950

**Comment by trentasis** [comment]
Tried with 5.4 and 5.5 and doesn't  work
