### ISSUE TITLE
Cannot upgrade TS 5.4 to 5.5

### ISSUE THREAD

**Issue by joemac96** [Thinstation/thinstation#228]
When in the chroot environment, "git fetch origin 5.5-Stable:5.5-Stable" works, but "git branch --set-upstream-to=origin/5.5-Stable 5.5-Stable" does not work. It says the branch does not exist.

**Comment by Thinstation** [comment]
I think that makes sense. An older 5.4 checkout would not know about the 5.5-Stable branch, and so would bark about it not existing..
