### ISSUE TITLE
VMview resolution 

### ISSUE THREAD

**Issue by Hyde94** [Thinstation/thinstation#233]
Hello, 

I've some trouble with the resolution of my view session. I've no problems with the boot resolution (1920x1080), session is on 1920x1080 too, but VMview is in 800x640 whereas I ask for full screen and the window is at the top left. I've done many test but nothing work. 

Here, my thinstation.conf.buildtime : 

AUDIO_LEVEL=90
MIC_LEVEL=0
SESSION_0_AUTOSTART=on
NET_USE_DHCP=on
NET_HOSTNAME=
LOCALE=fr_FR
#SCREEN_AUTO_CONFIG=ON                     #tested, doesn"t work
AUTOSTART=ON
#SESSION_0_CUSTOM_CONFIG=OFF           #tested, doesn"t work 
VMVIEW_AUTOCONNECT=TRUE
VMVIEW_DEFAULTBROKER=
SCREEN_RESOLUTION=1920x1080

# VMWare View Session options
SESSION_0_TITLE="VDI"
SESSION_0_TYPE=vmview
SESSION_0_AUTOSTART=On
SESSION_0_VMVIEW_SERVERURL=
SESSION_0_VMVIEW_FULLSCREEN=true
#SESSION_0_SCREEN_AUTO_CONFIG=ON                    #tested, doesn't work
#SESSION_0_SCREEN_RESOLUTION="1920x1080"       #tested, doesn't work
SESSION_0_VMVIEW_DOMAINNAME=
SESSION_0_VMVIEW_DESKTOPNAME=

Thanks you in advance.

**Comment by Hyde94** [comment]
So... I don't know why, but now my session is in 1920x1080... But! view is still in 1920x1080, it's not in full screen whereas I've this param : SESSION_0_VMVIEW_FULLSCREEN=ON

**Comment by Thinstation** [comment]
So, a lot of applications don't work fullscreen without the aid of a window manager. Super annoying, but that is the state of things. I recommend putting xfwm4 into session 0, and moving vmview to session 1.

**Comment by Hyde94** [comment]
Thanks, I'll try this, and I tell you if it's work or not.

**Comment by Hyde94** [comment]
I can't use the computer that I used to do my tests, so I've done it on vmware player. I don't know if the full screen work but I've a another problem I like the start menu mostly the logout icon but how can I disable the others shortcut ?

**Comment by Hyde94** [comment]
So... THANKS YOU VERY MUCH!! It's work exactly how I want! Now, if you know how I can deploy it with WDS or how I can install on the hard disk, it will be perfect!

**Comment by Doncuppjr** [comment]
It depends on how much customization you want to apply during install. Look at the installer package for insights into how I solved the problem for a lot of customization, and look at ts/bin/mkmbrdrv for a solution where not much is customized at all. 

    On Wednesday, July 5, 2017 7:03 AM, Hyde94 <notifications@github.com> wrote:
 

 So... THANKS YOU VERY MUCH!! It's work exactly how I want! Now, if you know how I can deploy it with WDS or how I can install on the hard disk, it will be perfect!—

**Comment by Hyde94** [comment]
I just want to deploy the image that I've done, without more customization. I've not find the installer package... I've just my iso boot image.

**Comment by Doncuppjr** [comment]
Look at mkmbrdrv. It's in the chroot build environment.


Sent from Yahoo Mail for iPhone


On Thursday, July 6, 2017, 12:54 AM, Hyde94 <notifications@github.com> wrote:


I just want to deploy the image that I've done, without more customization. I've not find the installer package... I've just my iso boot image.
