### ISSUE TITLE
Update ocsinventory agent

### ISSUE THREAD

**Issue by jackburton79** [Thinstation/thinstation#235]
Hi, I've been updating the ocsinventory agent lately.
I was wondering if it would be better for Thinstation to point to a specific release tag of my repository (like it does now), or to the release branch I created lately, which will always contain the latest stable release.
With the former, the Thinstation package would need to be adjusted to point to the new version, every time.
With the latter, the new release would be included "automatically".
What do you think ?

I will create a pull request for the update, anyway.

**Comment by Thinstation** [comment]
I don't mind either way. That port and package are good contributions by
yourself, and I support however you want to maintain them.

**Comment by trentasis** [comment]
Hi, 

Interesting! In my opinion stable software like ocs agent could be interesting use a named version, for example now 1.4, if you are interested I have in testing 1.4 in my branch (https://github.com/trentasis/thinstation/commit/cd7bdb3cdee42e5d019816ae16ab569e64ce7de3)

Both options are good!

Good Job

**Comment by jackburton79** [comment]
Il 10 lug 2017 7:08 PM, "trentasis" <notifications@github.com> ha scritto:

Hi,

Interesting! In my opinion stable software like ocs agent could be
interesting use a named version, for example now 1.4, if you are interested
I have in testing 1.4 in my branch (trentasis/thinstation@cd7bdb3
<https://github.com/trentasis/thinstation/commit/cd7bdb3cdee42e5d019816ae16ab569e64ce7de3>
)

Both options are good!

Good Job


Yeah, I think I'll go with that option.
I'm almost ready to release version 1.5.
If you want to test It now, you can point to the release branch.

**Comment by trentasis** [comment]
OK, I'll wait until 1.5 is released in github and then we will test
Thanks

2017-07-10 19:34 GMT+02:00 Stefano Ceccherini <notifications@github.com>:

**Comment by jackburton79** [comment]
Pull request #236

**Comment by jackburton79** [comment]
Thank you for applying. Is branch thinstation-5.4 still active ? If so, I guess we should do the same on that branch, too.

**Comment by Thinstation** [comment]
Sure. I think it still gets used.

**Comment by jackburton79** [comment]
Applied in 5.5 and 5.4.
