### ISSUE TITLE
VMview usb redirection

### ISSUE THREAD

**Issue by Hyde94** [Thinstation/thinstation#238]
Hi, 
I've seen many things to configure the usb redirection on view but it doesn't work. 
Here, that's I've test :
Build.conf 
package usb-redirector
package systemd
package libusb

thinstation.conf.buildtime 
USB_STORAGE_SYNC=on
USB_ENABLED=ON
USB_MOUNT_DIR='/mnt/usbdevice'
SESSION_1_VMVIEW_REDIRECT1="disk:usb=/mnt/usbdevice/sda1"
SESSION_1_VMVIEW_USB1="????" 
SESSION_1_VMVIEW_USB2="????"
SESSION_1_VMVIEW_RDESKTOPOPTIONS="-r disk:USBDrive=/mnt/usbdevice -r sound:local" //not sure...

Thanks in advance.

**Comment by bherbal** [comment]
Hello!  Did you ever get this to work?  If so can you please let me know


Thanks!
