### ISSUE TITLE
F2 not working at boot with usb keyboards

### ISSUE THREAD

**Issue by trentasis** [Thinstation/thinstation#240]
Hi,

I have detected that during bootup when appears "F2 to view boot messages", F2 is not working with usb keyboards (tried with Spanish/catalan keyboards)
Same computer/motherboard has ps/2 connector, and if you try in this same computer with ps/2 keyboard this works perfect, and with both keyboards connected, usb and ps/2 only usb keyboards allow to use f2 key.

Tried with default build.conf and thinstation.conf.buildtime that all locales are generated, no success

Anybody can confirm is with english usb keyboard also fails (sorry, but I don't have)

With thinstation 2.2 was working perfect

Where could be the problem?

Additional information in issue https://github.com/Thinstation/thinstation/issues/73

Thanks

**Comment by trentasis** [comment]
Hi,

I have made some additional test and I have found this in  thinstation code 

ts/build/packages/splash/etc/splash.functions

# Set the input device if it exists. This will make it possible to use F2 to
# switch from verbose to silent.
splash_set_event_dev() {
        local t="$(grep -Hsi keyboard /sys/class/input/input*/name | sed -e 's#.*input\([0-9]*\)/name.*#event\1#')"
        if [ -z "${t}" ]; then
                t="$(grep -Hsi keyboard /sys/class/input/event*/device/driver/description | grep -o 'event[0-9]\+')"
                if [ -z "${t}" ]; then
                        for i in /sys/class/input/input* ; do
                                if [ "$((0x$(cat $i/capabilities/ev) & 0x100002))" = "1048578" ]; then
                                        t="$(echo $i | sed -e 's#.*input\([0-9]*\)#event\1#')"
                                fi
                        done

                        if [ -z "${t}" ]; then
                                # Try an alternative method of finding the event device. The idea comes
                                # from Bombadil <bombadil(at)h3c.de>. We're couting on the keyboard controller
                                # being the first device handled by kbd listed in input/devices.
                                t="$(/bin/grep -s -m 1 '^H: Handlers=kbd' /proc/bus/input/devices | grep -o 'event[0-9]*')"
                        fi
                fi
        fi
        [ -n "${t}" ] && splash_comm_send "set event dev /dev/input/${t}"
}


and if I compare a keyboard that works F2 (ps/2) and other that doesn't work (usb) with this command that is used in this code:
usb not woking 
# grep -Hsi keyboard /sys/class/input/input*/name | sed -e 's#.*input\([0-9]*\)/name.*#event\1#'
event4


ps/2 with f2 working:
# grep -Hsi keyboard /sys/class/input/input*/name | sed -e 's#.*input\([0-9]*\)/name.*#event\1#'
event2


I don't know exactly what does it means, and if this could be the issue...

First question issue with F2 is in this code? anybody can help to understand this code?

Thanks

**Comment by trentasis** [comment]
not sure if this is the problem

with usb keyboard and F2 not working:

ls -lisah /dev/input/by-path/
total 0
    367      0 drwxr-xr-x    2 root     root          80 Aug  4 15:56 .
   1192      0 drwxr-xr-x    4 root     root         300 Aug  4 15:56 ..
    368      0 lrwxrwxrwx    1 root     root           9 Aug  4 15:56 pci-0000:00:1a.1-usb-0:2:1.0-event-kbd -> ../event2
    910      0 lrwxrwxrwx    1 root     root           9 Aug  4 15:56 platform-pcspkr-event-spkr -> ../event8
ts:~# ls -lisah /dev/input/by-id/
total 0
    359      0 drwxr-xr-x    2 root     root          60 Aug  4 15:56 .
   1192      0 drwxr-xr-x    4 root     root         300 Aug  4 15:56 ..
    360      0 lrwxrwxrwx    1 root     root           9 Aug  4 15:56 usb-LITEON_Technology_USB_Multimedia_Keyboard-event-kbd -> ../event2


with ps/2 keyboard and with F2 working
 ls -lisah /dev/input/by-id/
ls: /dev/input/by-id/: No such file or directory
ts:~# ls -lisah /dev/input/by-path/
total 0
   1800      0 drwxr-xr-x    2 root     root          80 Aug  4 16:54 .
   1192      0 drwxr-xr-x    3 root     root         280 Aug  4 16:54 ..
   1801      0 lrwxrwxrwx    1 root     root           9 Aug  4 16:54 platform-i8042-serio-0-event-kbd -> ../event2
    752      0 lrwxrwxrwx    1 root     root           9 Aug  4 16:54 platform-pcspkr-event-spkr -> ../event4

It could be the problem?

Thanks

**Comment by Doncuppjr** [comment]
I think your on to it. I'm not sure what the solution is yet though. 

    On Friday, August 4, 2017 7:52 AM, trentasis <notifications@github.com> wrote:
 

 not sure if this is the problemwith usb keyboard and F2 not working:ls -lisah /dev/input/by-path/
total 0
367 0 drwxr-xr-x 2 root root 80 Aug 4 15:56 .
1192 0 drwxr-xr-x 4 root root 300 Aug 4 15:56 ..
368 0 lrwxrwxrwx 1 root root 9 Aug 4 15:56 pci-0000:00:1a.1-usb-0:2:1.0-event-kbd -> ../event2
910 0 lrwxrwxrwx 1 root root 9 Aug 4 15:56 platform-pcspkr-event-spkr -> ../event8
ts:~# ls -lisah /dev/input/by-id/
total 0
359 0 drwxr-xr-x 2 root root 60 Aug 4 15:56 .
1192 0 drwxr-xr-x 4 root root 300 Aug 4 15:56 ..
360 0 lrwxrwxrwx 1 root root 9 Aug 4 15:56 usb-LITEON_Technology_USB_Multimedia_Keyboard-event-kbd -> ../event2with ps/2 keyboard and with F2 working
ls -lisah /dev/input/by-id/
ls: /dev/input/by-id/: No such file or directory
ts:~# ls -lisah /dev/input/by-path/
total 0
1800 0 drwxr-xr-x 2 root root 80 Aug 4 16:54 .
1192 0 drwxr-xr-x 3 root root 280 Aug 4 16:54 ..
1801 0 lrwxrwxrwx 1 root root 9 Aug 4 16:54 platform-i8042-serio-0-event-kbd -> ../event2
752 0 lrwxrwxrwx 1 root root 9 Aug 4 16:54 platform-pcspkr-event-spkr -> ../event4It could be the problem?Thanks—

**Comment by trentasis** [comment]
Ok, I'll try to investigate, but one question:
Do you know where is configured /dev/input/by-path/ or by-id in thinstation? Are generated by udev rules, if this is correct, where are rules affected to keyboards?

Thanks

**Comment by Thinstation** [comment]
I think the kernel creates those paths. Udev might be able to rename.

**Comment by trentasis** [comment]
OK!
Do you know what is the code in message 1 that talks about F2 in splash.functions? I don't understand...

Thanks!

**Comment by trentasis** [comment]
Do you know what is the code in message 1 that talks about F2 in splash.functions? I don't understand...

Thanks!

**Comment by trentasis** [comment]
Solved with https://github.com/Thinstation/thinstation/pull/241

**Comment by Thinstation** [comment]
Should be solved with commit
9c58929a34e05bd3e4cb4fdb764fbbadbc85e293

**Comment by trentasis** [comment]
Hi,
I have tried with latest version and error persist, a possible workaround
that I have found is ctrl+alt+f1 to show messages during boot.

2017-08-11 4:29 GMT+02:00 Thinstation <notifications@github.com>:

**Comment by Doncuppjr** [comment]
What is the output of "find /dev/input |grep -e kbd" ?


Sent from Yahoo Mail for iPhone


On Monday, August 14, 2017, 1:40 AM, trentasis <notifications@github.com> wrote:

Hi,
I have tried with latest version and error persist, a possible workaround
that I have found is ctrl+alt+f1 to show messages during boot.

2017-08-11 4:29 GMT+02:00 Thinstation <notifications@github.com>:

**Comment by trentasis** [comment]
Hi,

# find /dev/input |grep -e kbd
/dev/input/by-path/pci-0000:00:1d.0-usb-0:1.6:1.0-event-kbd
/dev/input/by-id/usb-04d9_1400-event-kbd

Thanks

**Comment by Thinstation** [comment]
And if you do readlink on the by-path link?

**Comment by trentasis** [comment]
This
--> readlink /dev/input/by-path/pci-0000:00:1d.0-usb-0:1.6:1.0-ev
ent-kbd -f
and returns 
/dev/input/event2

**Comment by Doncuppjr** [comment]
That is the same event I get, and why I added this code.

if [ -z "${t}" ]; then
    by_path="`find /dev/input/by-path |grep -e kbd -m1`" 
    if [ -n "$by_path" ]; then 
        t="`basename $( readlink -f $by_path )`" 
    fi 
fi 


Do you still have the function commented out?

**Comment by trentasis** [comment]
Correct, is not working with this code that was added, f2 is not working, only can see boot messages using ctrl alt f1

**Comment by Thinstation** [comment]
Could you please run this test script like this
./keyboard-finder >key.test 2>&1
and send me back the results?

**Comment by Thinstation** [comment]
Minor fix to script.

**Comment by trentasis** [comment]
Hi,

Where I can find this script?
Thanks

2017-08-21 19:57 GMT+02:00 Thinstation <notifications@github.com>:

> Minor fix to script.
>
>

**Comment by Thinstation** [comment]
Hmmmm. Put it on as an attachment, but here is the content.


#!/bin/bash
set -x

t="$(grep -Hsi keyboard /sys/class/input/input*/name | sed -e
's#.*input\([0-9]*\)/name.*#event\1#')"
if [ -z "${t}" ]; then
t="$(grep -Hsi keyboard /sys/class/input/event*/device/driver/description |
grep -o 'event[0-9]\+')"
fi
if [ -z "${t}" ]; then
for i in /sys/class/input/input* ; do
if [ "$((0x$(cat $i/capabilities/ev) & 0x100002))" = "1048578" ]; then
t="$(echo $i | sed -e 's#.*input\([0-9]*\)#event\1#')"
fi
done
fi
if [ -z "${t}" ]; then
by_path="`find /dev/input/by-path |grep -e kbd -m1`"
if [ -n "$by_path" ]; then
t="`basename $( readlink -f $by_path )`"
fi
fi
if [ -z "${t}" ]; then
t="$(/bin/grep -s -m 1 '^H: Handlers=kbd' /proc/bus/input/devices | grep -o
'event[0-9]*')"
fi

[ -n "${t}" ] && echo "Keyboard device is ${t}"

**Comment by trentasis** [comment]
Hi,

Attached output ./keyboard-finder >key.txt 2>&1

[key.txt](https://github.com/Thinstation/thinstation/files/1243039/key.txt)

Thanks!

**Comment by Doncuppjr** [comment]
Somehow the script got mangled. Let me try plain text


#!/bin/bash
set -x

t="$(grep -Hsi keyboard /sys/class/input/input*/name | sed -e 's#.*input\([0-9]*\)/name.*#event\1#')"
if [ -z "${t}" ]; then
    t="$(grep -Hsi keyboard /sys/class/input/event*/device/driver/description | grep -o 'event[0-9]\+')"
fi
if [ -z "${t}" ]; then
    for i in /sys/class/input/input* ; do
        if [ "$((0x$(cat $i/capabilities/ev) & 0x100002))" = "1048578" ]; then
            t="$(echo $i | sed -e 's#.*input\([0-9]*\)#event\1#')"
        fi
    done
fi
if [ -z "${t}" ]; then
    by_path="`find /dev/input/by-path |grep -e kbd -m1`"
    if [ -n "$by_path" ]; then
        t="`basename $( readlink -f $by_path )`"
    fi
fi
if [ -z "${t}" ]; then
    t="$(/bin/grep -s -m 1 '^H: Handlers=kbd' /proc/bus/input/devices | grep -o 'event[0-9]*')"
fi

[ -n "${t}" ] && echo "Keyboard device is ${t}"



On Tuesday, August 22, 2017 11:49 AM, trentasis <notifications@github.com> wrote:



Hi,
Attached output ./keyboard-finder >key.txt 2>&1
key.txt
Thanks!

**Comment by trentasis** [comment]
attached results
./keyboard-finder >key2.txt 2>&1
[key2.txt](https://github.com/Thinstation/thinstation/files/1246007/key2.txt)
[keyboard-finder.txt](https://github.com/Thinstation/thinstation/files/1246010/keyboard-finder.txt)

Thanks

**Comment by Thinstation** [comment]
How many keyboards do you have plugged into the system? Keypads? Gaming
Controllers?

**Comment by trentasis** [comment]
Only one usb keyboard

**Comment by Thinstation** [comment]
So what kind of system is this? It looks like the script found two keyboard
devices, not even the usb one.

**Comment by trentasis** [comment]
Sorry, I have checked and this computer has an adapter usb to ps/2.
Now I have attached output from computer with a native usb keyboard
[key3.txt](https://github.com/Thinstation/thinstation/files/1246304/key3.txt)

Sorry, for this mistake

**Comment by Thinstation** [comment]
O.k. I'll just move the usb kbd detection to the top. See if that works.

**Comment by trentasis** [comment]
It seems that now works with usb and ps/2 keyboards, I'll try to do more tests but for me seems that works!!!
Great job!!!

Thanks for you help
