### ISSUE TITLE
RDesktop

### ISSUE THREAD

**Issue by m0bYczE** [Thinstation/thinstation#243]
Hello, can you help me with creating rdesktop connection after boot thinstation image, please ? I don't found any tutorial.

Thanks.

**Comment by Thinstation** [comment]
Are you still working on this issue?

**Comment by trentasis** [comment]
see this example   thinstation/ts/build/conf/rdesktop.conf.sample, this will help
solved?

**Comment by trentasis** [comment]
solved?
