### ISSUE TITLE
Thinstation.conf. is not applied

### ISSUE THREAD

**Issue by mgarciaHWL** [Thinstation/thinstation#247]
Dears

I'm doing my first steps with Thinstation (5.5.1) , until now I have been using succesfully thinstation with USB drive , but I want go one step ahead a setup an evniroment base in PXE booting TFTP server and multiple configurations files.

Right now I have a working prototype with TFTP server (Synologic NAS) and DHCP server . On the PXE booting the computer can contact successfully with the TFTP server and get the Thinstation image.

My issue comes when I want have a different configurations files , I've done many many test but any off them with successfull result .

What I did?

On the thinstation image I have enabled the following parameters build.conf.
param basename thinstation
param basepath ts5.5

and at Thinstation.conf.builtime
NET_FILE_ENABLED=On
NET_FILE_METHOD=tftp

The second step has been create the thinstation.conf files for get a different settings applied.

I have test with the following files

thinstation.conf.network
thinstation.conf-
thinstation.conf-

We have place the files on the folder ts5.5 and the folder is located on the TFTP root and aslo in boot folder and pxelinux , but at any of them works.

Where I should placed the conf files?

Thank you !!

**Comment by Doncuppjr** [comment]
If you review you Tftp logs(sometimes in syslog), you should see the path that the client is actually trying to download files from.


Sent from Yahoo Mail for iPhone


On Wednesday, October 25, 2017, 9:05 AM, mgarciaHWL <notifications@github.com> wrote:


Dears

I'm doing my first steps with Thinstation (5.5.1) , until now I have been using succesfully thinstation with USB drive , but I want go one step ahead a setup an evniroment base in PXE booting TFTP server and multiple configurations files.

Right now I have a working prototype with TFTP server (Synologic NAS) and DHCP server . On the PXE booting the computer can contact successfully with the TFTP server and get the Thinstation image.

My issue comes when I want have a different configurations files , I've done many many test but any off them with successfull result .

What I did?

On the thinstation image I have enabled the following parameters build.conf.
param basename thinstation
param basepath ts5.5

and at Thinstation.conf.builtime
NET_FILE_ENABLED=On
NET_FILE_METHOD=tftp

The second step has been create the thinstation.conf files for get a different settings applied.

I have test with the following files

thinstation.conf.network
thinstation.conf-
thinstation.conf-

We have place the files on the folder ts5.5 and the folder is located on the TFTP root and aslo in boot folder and pxelinux , but at any of them works.

Where I should placed the conf files?

Thank you !!

**Comment by mgarciaHWL** [comment]
You are right.

On the TFTP log I see that thinstation is getting the files correctly my mistake is not in the file location.



Log | Date & Time | IP address | User | Event | File/Folder | File size | File name
-- | -- | -- | -- | -- | -- | -- | --
TFTP file transfer | 25/10/2017 16:41 | 172.25.161.220 | -- | get | File | 1.27 KB | /Thinstation/ts5/thinstation.conf-10604b5d4b5c
TFTP file transfer | 25/10/2017 16:41 | 172.25.161.220 | -- | get | File | 1.27 KB | /Thinstation/ts5/thinstation.conf.network
TFTP file transfer | 25/10/2017 16:21 | 172.25.161.220 | -- | get | File | 1.27 KB | /Thinstation/ts5/thinstation.conf.network
TFTP file transfer | 25/10/2017 15:52 | 172.25.161.220 | -- | get | File | 1.27 KB | /Thinstation/ts5.5/thinstation.conf.network

My error should be in the file or some missconfiguration at buid.config.

Below the thinstation.conf.network

AUDIO_LEVEL=90
MIC_LEVEL=0
SESSION_0_TYPE=xfwm4
SESSION_0_AUTOSTART=on
XFWM4_COMPOSITING=true
XFWM4_BRIGHTNESS="-33"
XFWM4_RED=0
XFWM4_GREEN=0
XFWM4_BLUE=0
XFWM4_START_POSITION="BOTTOM"
DESKTOP_ICON_SIZE=48
DESKTOP_FONT_SIZE=8
DESKTOP_SHOWTRASH=false
DEKSTOP_SHOWHOME=false
DESKTOP_SHOWREMOVEABLE=true
DESKTOP_SHOWFILESYSTEM=false
GTK_THEME=Xfce
XFWM4_THEME=Default
PANEL_PAGER=false
PANEL_USER=false
PANEL_REV_CLOCKSYSTRAY=true
ICONS_THEME="gnome"
ICONS_CUT_SIZES="256x256 scalable"
XTERM_CMD="xfce4-terminal"
NET_USE=BOTH
NET_USE_DHCP=on
NET_HOSTNAME=ES_2*
NET_TELNETD_ENABLED=ON
TIME_ZONE=Europe/Madrid
NET_TIME_SERVER=us.pool.ntp.org
NET_REMOTE_ACCESS_FROM="0.0.0.0"
TFTP_BLOCKSIZE=1024
BIND_MOUNT0="storage:/mnt/storage"
STORAGE_CONFIG1=/mnt/storage
USB_STORAGE_SYNC=on
LOCALE=es_ES
MOUNT_0="LABEL=boot     /boot           auto    x-mount.mkdir,defaults  0       0"
MOUNT_1="LABEL=home     /root           auto    x-mount.mkdir,defaults  0       0"
MOUNT_2="LABEL=swap     swap            swap    defaults        0       0"
USE_XRANDR=true
USB_ENABLED=ON
USB_STORAGE_SYNC=ON
STORAGE_PATH=/mnt/usbdevice/sdb1
USB_MOUNT_USELABEL=NO
STORAGE_CONFIG1=$STORAGE_PATH 
SET_RESOLUTION_MULTIMONITOR_EXPAND='mirror'
SET_RESOLUTION_MULTIMONITOR_AUTOSCALE='scale'

**Comment by Doncuppjr** [comment]
Depending on what you are trying to configure, it might be to late by the time network files are downloaded. Specifically, the network can’t be reconfigured, and storage volumes have already been mounted. What are you trying to change dynamically?


Sent from Yahoo Mail for iPhone


On Tuesday, October 31, 2017, 6:26 AM, mgarciaHWL <notifications@github.com> wrote:


as per the TFTP log the files are read correctly , but the config is not applied

**Comment by mgarciaHWL** [comment]
First I tried a simple change like hostname (NET_HOSTNAME=ES_2*) , but the final wish is be able to have multiple configuration files define settings like monitor resolution , double screen and mouse left/right buttons.

**Comment by Doncuppjr** [comment]
The monitor and mouse stuff should work, but the hostname is part of network configuration, so it’s already done, so that you could download files.


Sent from Yahoo Mail for iPhone


On Tuesday, October 31, 2017, 7:10 AM, mgarciaHWL <notifications@github.com> wrote:


First I tried a simple change like hostname (NET_HOSTNAME=ES_2*) , but the final wish is be able to have multiple configuration files define settings like monitor resolution , double screen and mouse left/right buttons.

**Comment by Thinstation** [comment]
Do you have any more questions about this issue?

**Comment by ferfebles** [comment]
I had the same problem.

Could you add to the documentation the list of options that can (or can not if it’s shorter)  be used in thinstation.conf.network?

By the way, great job, thanks for the work you are doing in Thinstation.

**Comment by Thinstation** [comment]
A fair request.

**Comment by trentasis** [comment]
solved?

**Comment by Thinstation** [comment]
I did add some documentation. I don’t know if it is sufficient.

**Comment by ferfebles** [comment]
Much better, thank you.
