### ISSUE TITLE
DevStation - Internet Connectivity Test Failed

### ISSUE THREAD

**Issue by rodrigoreimberg** [Thinstation/thinstation#248]
First of all I want to congratulate you for the excellent DevStation tool.

But I'm having difficulty installing, my internet connection is normal, but the messages appear as attached.

Would you help me? 

Thank you so much.
![print1](https://user-images.githubusercontent.com/28633776/32137831-3e1fa7d6-bc06-11e7-9dd5-6b7b38676d24.png)
![print2](https://user-images.githubusercontent.com/28633776/32137832-3e3f8b50-bc06-11e7-99b7-34d52eb7fff0.png)

**Comment by Thinstation** [comment]
Sometimes Sourceforge has issues. Wait 24 hours, and try again.

**Comment by rodrigoreimberg** [comment]
Hello, I have been trying since February 2017, version TS-5.5.2-Installer-0628.iso

Tks,

**Comment by Doncuppjr** [comment]
Do you need DevStation, or just thinstation? We could try and work it out in IRC.


Sent from Yahoo Mail for iPhone


On Saturday, October 28, 2017, 9:03 AM, rodrigoreimberg <notifications@github.com> wrote:


Hello, I have been trying since February 2017, version TS-5.5.2-Installer-0628.iso

Tks,

**Comment by rodrigoreimberg** [comment]
I need DevStation.
What is the syntax used for the connection test and on which server does it test? Could inform me? Thank you

**Comment by rodrigoreimberg** [comment]
![print1](https://user-images.githubusercontent.com/28633776/32137866-bae5122e-bc06-11e7-9d2d-ab4987c3cef6.png)
![print2](https://user-images.githubusercontent.com/28633776/32137867-bb049f22-bc06-11e7-8c13-a60d15e983fe.png)

**Comment by Doncuppjr** [comment]
| test_http() |
|  | { |
|  |  if ! wget -t 3 -T 30 http://sourceforge.net/projects/thinstation/files/DevStation-Source/image.md5 ; then |
|  |  http=false |
|  |  http_display=Fail |
|  |  return 1 |
|  |  else |
|  |  http=true |
|  |  http_display=Success |
|  |  rm image.md5 |
|  |  touch /tmp/http_tested |
|  |  return 0 |
|  |  fi |
|  | } |
|  |  |
|  | test_https() |
|  | { |
|  |  if ! wget -t 2 -T 10 https://www.ssllabs.com/ssltest/viewMyClient.html ; then |
|  |  https=false |
|  |  https_display=Fail |
|  |  return 1 |
|  |  else |
|  |  https=true |
|  |  https_display=Success |
|  |  rm -r viewMyClient.html |
|  |  touch /tmp/https_tested |
|  |  return 0 |
|  |  fi |
|  | } |

**Comment by rodrigoreimberg** [comment]
Hello,

When I execute the syntax:

wget -t 3 -T 30 http://sourceforge.net/projects/thinstation/files/DevStation-Source/image.md5

![image](https://user-images.githubusercontent.com/28633776/32169874-520b38a6-bd59-11e7-9b50-263161aa6a82.png)

**Comment by Thinstation** [comment]
Looks like your behind a proxy, and bad one, and it’s not signing fake certs correctly. What country?

**Comment by rodrigoreimberg** [comment]
Brazil

**Comment by Doncuppjr** [comment]
Could try and putcheck_certificate=offinto ~/.wgetrc


Sent from Yahoo Mail for iPhone


On Monday, October 30, 2017, 7:08 AM, rodrigoreimberg <notifications@github.com> wrote:


Brazil

**Comment by rodrigoreimberg** [comment]
Sorry, I do not understand. Where I change this, I simply run the "Install to HD"

**Comment by Doncuppjr** [comment]
Open a terminal, then typeecho “check_certificates=off” > ~/.wgetrc
Then Install to HD.


Sent from Yahoo Mail for iPhone


On Monday, October 30, 2017, 7:57 AM, rodrigoreimberg <notifications@github.com> wrote:


Sorry, I do not understand. Where I change this, I simply run the "Install to HD"

**Comment by Doncuppjr** [comment]
check_certificate no s at the end


Sent from Yahoo Mail for iPhone


On Monday, October 30, 2017, 7:57 AM, rodrigoreimberg <notifications@github.com> wrote:


Sorry, I do not understand. Where I change this, I simply run the "Install to HD"

**Comment by rodrigoreimberg** [comment]
It's allright now, but i used “check_certificate=off” > ~/.wgetrc without "s" 

Tks,

**Comment by rashedayyash** [comment]
hi 
i have same problem can you help me ???

**Comment by rodrigoreimberg** [comment]
Hi,

Open Terminal -> Type: echo “check_certificate=off” > ~/.wgetrc

Try again to run "Install to HD"

**Comment by rashedayyash** [comment]
t try this but remain the same problem

**Comment by rodrigoreimberg** [comment]
On terminal, type echo ~/.wgetrc. 

Put result here.

**Comment by rashedayyash** [comment]
![image](https://user-images.githubusercontent.com/35422199/34915971-8e92aca8-f938-11e7-9bf8-0c058c8ead1b.png)

**Comment by rodrigoreimberg** [comment]
Now, type: more .wgetrc and put result here.

**Comment by rashedayyash** [comment]
no such file or directory

**Comment by Doncuppjr** [comment]
I think he meant cat ~/.wgetrc

**Comment by DiegoBean** [comment]
I'l do all steps that was described below and still have same problem with massage "Internet Connectivity Test Failed". Can You help me?

**Comment by rodrigoreimberg** [comment]
On terminal, type : cat ~/.wgetrc

Put result here, please.

**Comment by DiegoBean** [comment]
rodrigoreimberg,
![default](https://user-images.githubusercontent.com/36824094/36654600-75ed3eac-1ac6-11e8-9d3f-eed9c761fc0c.PNG)

**Comment by rodrigoreimberg** [comment]
On terminal, type :
wget -t 3 -T 30 http://sourceforge.net/projects/thinstation/files/DevStation-Source/image.md5

Put result here

**Comment by rodrigoreimberg** [comment]
On terminal, type:
echo “check_certificate=off” > ~/.wgetrc

Try to Install HD again.

**Comment by AnthonyPiva** [comment]
I had installed DevStation, but, for issues reasons, i had to install it again, and i got this issue
This is my terminal output
ts_000c291a3ba5:~# wget -t 3 -T 30 http://sourceforge.net/projects/thinstation/files/DevStation-Source/image.md5

--2018-03-03 09:04:22--  http://sourceforge.net/projects/thinstation/files/DevStation-Source/image.md5
Resolving sourceforge.net (sourceforge.net)... 13.32.178.35
Connecting to sourceforge.net (sourceforge.net)|13.32.178.35|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://sourceforge.net/#!/projects/thinstation/files/DevStation-Source/image.md5 [following]
--2018-03-03 09:04:22--  https://sourceforge.net/
Connecting to sourceforge.net (sourceforge.net)|13.32.178.35|:443... connected.
OpenSSL: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
Unable to establish SSL connection.
ts_000c291a3ba5:~# cat .wgetrc 
check_certificate=off

Can someone help me?

**Comment by Thinstation** [comment]
Behind a proxy?

**Comment by communitysteps** [comment]
The sourceforge.net website is temporarily in static offline mode. Only a very limited set of project pages are available until the main website returns to service.

https://twitter.com/sfnet_ops

**Comment by AnthonyPiva** [comment]
@Thinstation I'm not behind a proxy, as a said, a installed same way like 3 days ago, using the same iso and the same configurations on the VM.

@communitysteps thanks for the reply

**Comment by Thinstation** [comment]
So what is happening, is that the SSL connection is not trusted. You usually see this kind of stuff when you are behind a proxy, a transparent proxy, or when sourceforge goes down.
