### ISSUE TITLE
Is there support for ARM board?

### ISSUE THREAD

**Issue by roysbike** [Thinstation/thinstation#249]
Hello! The Linux kernel supports many ARM processors. Is it possible to build an assembly for this platform?

**Comment by Doncuppjr** [comment]
At this time, there is no support for ARM. You could sponsor the research.


Sent from Yahoo Mail for iPhone


On Wednesday, November 1, 2017, 2:26 AM, roysbike <notifications@github.com> wrote:


Hello! The Linux kernel supports many ARM processors. Is it possible to build an assembly for this platform?
