### ISSUE TITLE
CA-Certificate

### ISSUE THREAD

**Issue by deToekomst** [Thinstation/thinstation#250]
I want to use freerdp on a thinclient (Im currently just testing Thinstation). Now in our company we need a certificate to connect to a Server/Workstation. Now i have 2 questions.

1. Where do i need to put the Certifcate so it will be available in a image/iso?

2. Does somebody have an example of a script so when i boot from the iso the Certificate will run automatic?

I'm sorry if i ask  dumb questions i'm new to linux. :)

**Comment by Doncuppjr** [comment]
Not dumb, PKI is heady stuff.Do you have the CA cert in PEM format?
I was meaning to add a cert import feature.


Sent from Yahoo Mail for iPhone


On Wednesday, November 1, 2017, 4:01 AM, deToekomst <notifications@github.com> wrote:


I want to use freerdp on a thinclient (Im currently just testing Thinstation). Now in our company we need a certificate to connect to a Server/Workstation. Now i have 2 questions.
   
   -    
Where do i need to put the Certifcate so it will be available in a image/iso?

   -    
Does somebody have an example of a script so when i boot from the iso the Certificate will run automatic?


I'm sorry if i ask dumb questions i'm new to linux. :)

**Comment by deToekomst** [comment]
I will send the CA cert through e-mail.

**Comment by Doncuppjr** [comment]
I added some code and new folders at /build/Certs. If you update your checkout, you should be able to put your certs in one of those dirs. Also make sure to include ca-bundle package in your build.

**Comment by Thinstation** [comment]
Update: Certs are now in /build/packages/\<your packages\>/certs/ca
