### ISSUE TITLE
DevStation updates

### ISSUE THREAD

**Issue by Killbrum** [Thinstation/thinstation#251]
Is there any way to update DevStation? My current DevStation is a bit old. It was installed one and half year ago. It seems there are new updates and I would be glad to install them. But apt-get is absent in DevStation (or I did something wrong?), and I was not able to find anything in the FAQ. So, at first look, I see only one solution - reinstall the whole DevStation from the new image. But it is a bit painful thing because I will need to move all my work from old to new one. So, is there any way to automatically update DevStation to the last build? Thanks!

**Comment by Doncuppjr** [comment]
DevStation is just an image built with thinstation. There should be an update button to pull the latest build for your branch, but it's not updated very often. If you want to jump to a new branch, things get a little more tricky.
