### ISSUE TITLE
Can't compile kernel-TS_SMP

### ISSUE THREAD

**Issue by Babay156** [Thinstation/thinstation#255]
Thinstation 5.6 Stable, everythin by default
i need change kernel options, try to compile:
[root@TS_chroot]/prt-get update kernel-TS_SMP --install-scripts -f -im -if

=======> Building '/ts/ports/kernel-modules/kernel-TS_SMP/kernel-TS_SMP#1-1.pkg.tar.xz'.
bsdtar -p -o -C /ts/ports/kernel-modules/kernel-TS_SMP/work/src -xf /ts/ports/kernel-modules/kernel-TS_SMP/linux-4.9.44.tar.xz
cp ts.config /ts/ports/kernel-modules/kernel-TS_SMP/work/src
+ build
+ export MAKEFLAGS=-j7
+ MAKEFLAGS=-j7
+ cd linux-4.9.44
+ cp /ts/ports/kernel-modules/kernel-TS_SMP/work/src/ts.config ./.config
+ '[' -e /etc/ssl/keys/kernel.key ']'
+ touch certs/x509.genkey
+ cp /etc/ssl/keys/kernel.key certs/signing_key.pem
+ openssl x509 -inform DER -in /etc/ssl/certs/kernel.crt -outform PEM
+ cp /etc/ssl/certs/kernel-ca.crt certs/extra_certificates
+ make modules_prepare headers_install
  HOSTCC  scripts/basic/fixdep
  SHIPPED scripts/kconfig/zconf.tab.c
  HOSTCC  scripts/kconfig/conf.o
  SHIPPED scripts/kconfig/zconf.lex.c
  SHIPPED scripts/kconfig/zconf.hash.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
scripts/kconfig/conf  --silentoldconfig Kconfig
  CHK     include/config/kernel.release
  SYSHDR  arch/x86/entry/syscalls/../../include/generated/uapi/asm/unistd_64.h
  SYSHDR  arch/x86/entry/syscalls/../../include/generated/uapi/asm/unistd_32.h
  SYSTBL  arch/x86/entry/syscalls/../../include/generated/asm/syscalls_32.h
  SYSHDR  arch/x86/entry/syscalls/../../include/generated/uapi/asm/unistd_x32.h
  WRAP    arch/x86/include/generated/asm/clkdev.h
  WRAP    arch/x86/include/generated/asm/early_ioremap.h
  WRAP    arch/x86/include/generated/asm/dma-contiguous.h
  WRAP    arch/x86/include/generated/asm/cputime.h
  WRAP    arch/x86/include/generated/asm/mcs_spinlock.h
  WRAP    arch/x86/include/generated/asm/mm-arch-hooks.h
  CHK     include/generated/uapi/linux/version.h
  UPD     include/generated/uapi/linux/version.h
  HOSTCC  scripts/kallsyms
  HOSTCC  scripts/conmakehash
  HOSTCC  scripts/sortextable
  HOSTCC  scripts/asn1_compiler
  CC      scripts/mod/empty.o
  HOSTCC  scripts/mod/mk_elfconfig
  CC      scripts/mod/devicetable-offsets.s
  HOSTCC  scripts/sign-file
  HOSTCC  scripts/extract-cert
  MKELF   scripts/mod/elfconfig.h
  GEN     scripts/mod/devicetable-offsets.h
  HOSTCC  scripts/mod/sumversion.o
  HOSTCC  scripts/mod/file2alias.o
  HOSTCC  scripts/mod/modpost.o
/tmp/cc18EQbX.o: In function `main':
extract-cert.c:(.text.startup+0x1a): undefined reference to `OPENSSL_add_all_algorithms_noconf'
extract-cert.c:(.text.startup+0x1f): undefined reference to `ERR_load_crypto_strings'
collect2: error: ld returned 1 exit status
scripts/Makefile.host:107: recipe for target 'scripts/extract-cert' failed
make[1]: *** [scripts/extract-cert] Error 1
make[1]: *** Waiting for unfinished jobs....
/tmp/cc6Ta97T.o: In function `main':
sign-file.c:(.text.startup+0x44): undefined reference to `OPENSSL_add_all_algorithms_noconf'
sign-file.c:(.text.startup+0x49): undefined reference to `ERR_load_crypto_strings'
sign-file.c:(.text.startup+0x792): undefined reference to `OpenSSL_add_all_digests'
collect2: error: ld returned 1 exit status
scripts/Makefile.host:107: recipe for target 'scripts/sign-file' failed
make[1]: *** [scripts/sign-file] Error 1
  UPD     include/config/kernel.release
  HOSTCC  arch/x86/tools/relocs_64.o
  HOSTCC  arch/x86/tools/relocs_32.o
  HOSTCC  arch/x86/tools/relocs_common.o
  CHK     include/generated/utsrelease.h
  HOSTLD  scripts/mod/modpost
  HOSTLD  arch/x86/tools/relocs
  HOSTCC  scripts/unifdef
Makefile:560: recipe for target 'scripts' failed
make: *** [scripts] Error 2
make: *** Waiting for unfinished jobs....
  UPD     include/generated/utsrelease.h
=======> ERROR: Building '/ts/ports/kernel-modules/kernel-TS_SMP/kernel-TS_SMP#1-1.pkg.tar.xz' failed.

-- Packages where update failed
kernel-TS_SMP

Any idea?

**Comment by Doncuppjr** [comment]
5.6 currently has a mixed openssl state. It's setup right for the most part, but some very particular apps need 1.0. For the purposes of compiling the kernel, do the following,
enter chrootcp -a /usr/local/lib/* /usr/lib/.rebuild-kernels
When you want to put it back to right for everything else,pkgadd /ts/ports/core/openssl/openssl#*.pkg.tar.xz -f


    On Monday, November 13, 2017, 5:46:59 AM PST, Babay156 <notifications@github.com> wrote:  
 
 
Thinstation 5.6 Stable, everythin by default
i need change kernel options, try to compile:
[root@TS_chroot]/prt-get update kernel-TS_SMP --install-scripts -f -im -if

=======> Building '/ts/ports/kernel-modules/kernel-TS_SMP/kernel-TS_SMP#1-1.pkg.tar.xz'.
bsdtar -p -o -C /ts/ports/kernel-modules/kernel-TS_SMP/work/src -xf /ts/ports/kernel-modules/kernel-TS_SMP/linux-4.9.44.tar.xz
cp ts.config /ts/ports/kernel-modules/kernel-TS_SMP/work/src
   
   - build
   - export MAKEFLAGS=-j7
   - MAKEFLAGS=-j7
   - cd linux-4.9.44
   - cp /ts/ports/kernel-modules/kernel-TS_SMP/work/src/ts.config ./.config
   - '[' -e /etc/ssl/keys/kernel.key ']'
   - touch certs/x509.genkey
   - cp /etc/ssl/keys/kernel.key certs/signing_key.pem
   - openssl x509 -inform DER -in /etc/ssl/certs/kernel.crt -outform PEM
   - cp /etc/ssl/certs/kernel-ca.crt certs/extra_certificates
   - make modules_prepare headers_install   
HOSTCC scripts/basic/fixdep   
SHIPPED scripts/kconfig/zconf.tab.c   
HOSTCC scripts/kconfig/conf.o   
SHIPPED scripts/kconfig/zconf.lex.c   
SHIPPED scripts/kconfig/zconf.hash.c   
HOSTCC scripts/kconfig/zconf.tab.o   
HOSTLD scripts/kconfig/conf   
scripts/kconfig/conf --silentoldconfig Kconfig   
CHK include/config/kernel.release   
SYSHDR arch/x86/entry/syscalls/../../include/generated/uapi/asm/unistd_64.h   
SYSHDR arch/x86/entry/syscalls/../../include/generated/uapi/asm/unistd_32.h   
SYSTBL arch/x86/entry/syscalls/../../include/generated/asm/syscalls_32.h   
SYSHDR arch/x86/entry/syscalls/../../include/generated/uapi/asm/unistd_x32.h   
WRAP arch/x86/include/generated/asm/clkdev.h   
WRAP arch/x86/include/generated/asm/early_ioremap.h   
WRAP arch/x86/include/generated/asm/dma-contiguous.h   
WRAP arch/x86/include/generated/asm/cputime.h   
WRAP arch/x86/include/generated/asm/mcs_spinlock.h   
WRAP arch/x86/include/generated/asm/mm-arch-hooks.h   
CHK include/generated/uapi/linux/version.h   
UPD include/generated/uapi/linux/version.h   
HOSTCC scripts/kallsyms   
HOSTCC scripts/conmakehash   
HOSTCC scripts/sortextable   
HOSTCC scripts/asn1_compiler   
CC scripts/mod/empty.o   
HOSTCC scripts/mod/mk_elfconfig   
CC scripts/mod/devicetable-offsets.s   
HOSTCC scripts/sign-file   
HOSTCC scripts/extract-cert   
MKELF scripts/mod/elfconfig.h   
GEN scripts/mod/devicetable-offsets.h   
HOSTCC scripts/mod/sumversion.o   
HOSTCC scripts/mod/file2alias.o   
HOSTCC scripts/mod/modpost.o   
/tmp/cc18EQbX.o: In function main': extract-cert.c:(.text.startup+0x1a): undefined reference toOPENSSL_add_all_algorithms_noconf'   
extract-cert.c:(.text.startup+0x1f): undefined reference to ERR_load_crypto_strings' collect2: error: ld returned 1 exit status scripts/Makefile.host:107: recipe for target 'scripts/extract-cert' failed make[1]: *** [scripts/extract-cert] Error 1 make[1]: *** Waiting for unfinished jobs.... /tmp/cc6Ta97T.o: In functionmain':   
sign-file.c:(.text.startup+0x44): undefined reference to OPENSSL_add_all_algorithms_noconf' sign-file.c:(.text.startup+0x49): undefined reference toERR_load_crypto_strings'   
sign-file.c:(.text.startup+0x792): undefined reference to `OpenSSL_add_all_digests'   
collect2: error: ld returned 1 exit status   
scripts/Makefile.host:107: recipe for target 'scripts/sign-file' failed   
make[1]: *** [scripts/sign-file] Error 1   
UPD include/config/kernel.release   
HOSTCC arch/x86/tools/relocs_64.o   
HOSTCC arch/x86/tools/relocs_32.o   
HOSTCC arch/x86/tools/relocs_common.o   
CHK include/generated/utsrelease.h   
HOSTLD scripts/mod/modpost   
HOSTLD arch/x86/tools/relocs   
HOSTCC scripts/unifdef   
Makefile:560: recipe for target 'scripts' failed   
make: *** [scripts] Error 2   
make: *** Waiting for unfinished jobs....   
UPD include/generated/utsrelease.h   
=======> ERROR: Building '/ts/ports/kernel-modules/kernel-TS_SMP/kernel-TS_SMP#1-1.pkg.tar.xz' failed.

-- Packages where update failed
kernel-TS_SMP

Any idea?

**Comment by Thinstation** [comment]
Do you have any more concerns with this issue?
