### ISSUE TITLE
DNS

### ISSUE THREAD

**Issue by brent-mac** [Thinstation/thinstation#257]
Goal, setup a computer in the conference room with basic interface for Remote Desktop capabilities to any user's desktop in our local network (All users have Windows 7). Using ESXi 6.0 and vSphere I have created a Dev Station, and then following [this guide](https://www.youtube.com/watch?v=VN0DQlL6V4o), created an iso for the Conference VM. The Conference VM loads up and has internet connection. Looking at the Connection Information, I can see it is looking at the correct IP for Gateway, and both DNS servers. 

- I am able to ping IP addresses inside and outside our network.
- I am able to ping www.google.com
- I am NOT able to ping any computer name inside the company.
- I was able to RDP using RDesktoP but only using the IP Address or  Fully Qualified Domain Name 
- I am NOT able to RDP to anything using FreeRDP

I am able to stumble through linux usually, but I am far from an expert. Any and all help would be greatly appreciated.

**Comment by Thinstation** [comment]
Domain search order is configured slightly differently in UNIX world, from Microsoft. We use option 119, which is not available by default with MS DHCP, but it can be added. It's a comma separated string list of domains to search. It would at-least contain the contents of option 15. 
I would need the output of freerdp to be sure, but I suspect your RDP servers support weak authentication, and freerdp is defaulting to nla.

**Comment by Thinstation** [comment]
Do you have any more concerns on this issue?

**Comment by Thinstation** [comment]
We need to get to a terminal, so we can see the output of freerdp when run without a dialog box front end.

**Comment by Thinstation** [comment]
Still open?
