### ISSUE TITLE
Segfault by Installing syslinux in local-install.sh

### ISSUE THREAD

**Issue by havrazO** [Thinstation/thinstation#262]
https://github.com/Thinstation/thinstation/blob/3b90a04ac2a9663798a2b1ac6acb85e08a219839/ts/build/packages/local-install/bin/local-install.sh#L108

hi,
after running the local-install.sh it gets to the point where it says Download was successful, copying files to boot partition..
then the massege "Segmentation fault" 
at the end "Installation complete. You must reboot to use the new version."

(after reboot from hdd , it doesn't/can't boot the image)

i treid to run syslinux manualy and i got the same falult 
tmp/local-install/image/boot/syslinux/syslinux /dev/sad1

this from log masseges:
![screenshot_1](https://user-images.githubusercontent.com/26874844/33174211-476e6b1e-d057-11e7-8be9-bba3bc3335d0.png)

I get this fault everytime i try to local install the image which been downloaded from a webserver 
but when i gave DevStation IP-Adress as i webServer in my test Env. i dont get the segfault.

**Comment by Thinstation** [comment]
What are you installing too? VMware, Virtualbox? A machine?

**Comment by havrazO** [comment]
On a machine"small pc ssd drive"  i tried also on other pc's

**Comment by MarcusEyre** [comment]
Hi,

Author of the local-install package (if that matters) here but actually not an expert on Linux so I might be way off...

You say that it works when you enter the ip of the DevStation but when you have your production (?) webserver it does not work? What web server do you use to download from? I know that I had issues using when using IIS (still do) and found the solution to add MIME type octet for it to work.

PowerShell for adding mimetype for extension . and .* as octet stream. Warning though I am not sure if that has negative affects on any other files you might have on that IIS web site (guess you have a separate site for thinstation). You can of course add the mime type manually in IIS but below is a ready to go script which just need adjustment for the path to your site IIS:\Sites\<YourSiteName>\

    $MimeTypes = @('.', '.*')

    $MimeTypes | ForEach-Object {
        if ((Get-WebConfigurationProperty -PSPath 'IIS:\Sites\Thinstation\' -Name '.' -Filter "system.webServer/staticContent/mimeMap[@fileExtension='$_']").mimeType -eq 'application/octet-stream') {
            Write-Host "MimeType for '$_' as 'application/octet-stream' already exists"
        } else {
            Add-WebConfigurationProperty -PSPath 'IIS:\Sites\Thinstation\' -Name '.' -Filter 'system.webServer/staticContent' -Value @{fileExtension="'$_'";mimeType='application/octet-stream'}
        }
    }

Another thing, saw in Another issue that you mentioned cron-job for running update. It will do that during boot so it might not be necessary depending on your situation but I will make a comment about that in that thread insted...

/Marcus

**Comment by havrazO** [comment]
Hi,
thx for respond 👍 
i don't really have much permissions yet on the web server, which i am useing now for production. i can upload/make changes on files and folders not more.
YES! as i used DevStation in the test Network everything good no segfault.
and yes its a sparete site for thinstation.
i will ask my kollege about the kind of our Web server and about your suggestions and update you with more info.

while searching for solution (for the segfult )we found a checksum differences when uploading files using integrated filezilla in DevStation to the webserver. so i moved to use the file manager insteade.

i hope we get this issue out of the way, i am too close now to make a final production version of thinstation with local-install functionalities. also cuz im a big fan of your work guys.

**Comment by MarcusEyre** [comment]
If I remember correctly I hade the same issue with FileZilla to my ftp- and web server (hosted on IIS) and the solution was to
reg. ftp, in FileZilla change transport to Binary
web issue downloading files (mainly local install and thinstation.conf files) the MimeType fix in my post above.

**Comment by havrazO** [comment]
we are using Apache ..and we done the MimeType fix also i changed the transport to Binary on FileZilla now everything works is as it schuld be.
 I get no Segfault wenn it comes to install syslinux :) 
it seems to me that the problem was not changing FileZilla trasport to Binary.
Thanks Alot
