### ISSUE TITLE
HP T630 Hardware

### ISSUE THREAD

**Issue by Dubby650** [Thinstation/thinstation#266]
Hello, First time poster here.

I have inherited someone else Thinstation build and while i have been coming to grips with how it all slots together, HP have EOL the T620 devices we have been using. As a result I got a new T630 placved in my lap to play with to get it all working.

The trick is that when I try to do a syslinux USB boot of a --allmodules image, the image crashes out as it cannot find the hard disk (not a good start!). The first error message I get is Unknown file system type overlay. then a lot of expected cannot make or find file errors.

I tried to PXE boot with the same image my T620 models use and the PXE agent actually gets further, it downloads the global config and can get the MAC address  specific config! then it shuts down as it cannot find a valid session type.

I 'think' this is because it cannot find the video driver but as the system halts i cannot get any logs (boo).

This gave me some hope as I thought I could PXE boot it into debug mode (https://github.com/Thinstation/thinstation/wiki/Debugging)

When I include the debug package and the "param haltonerror false" 

instead of halting, it shuts down 👎 

Need some help!

**Comment by Thinstation** [comment]
You will want to look at the
NO_SESSION=poweroff
NO_XORG_CMD="/bin/shutdown --systemfail"
settings.
NO_XORG_CMD might be the best option, as that could be set to "sh", and
would drop you to a shell the first time that X fails.

**Comment by Dubby650** [comment]
Hello,

Yes this helped me stop the thinstation from shutting down, the NO_SESSION=exit seems to have worked. I say seems to have worked as now after loading config files i get a screen with 3 purple dots. 

I updated the PXE image to include --allmodules and hte initrd is over 200MB so i am confident that teh command worked. 

From what I can see:
Disk boot is failing as it does not have the controller driver
Video is failing as the video driver is out of date.

The AMD SoC chip definetly seems to combine everything on the one chip so I am fairly certain that if I can update the SoC driver i can get this working. 

I have downloaded AMD drivers to see if I can figure out how to get this into Thinstation but I am not having much luck. Thinstation seems to use .KO files and i dont see an obvius way to drag these out of the AMD package.

From what i can see the GE420GAAY43KA Proccessor/Chipset/video card is very new. 

Any ideas on how i can update Thinstation with a ubunto or other based driver?

**Comment by Thinstation** [comment]
I am working on an updated kernel config. It’s already pushed to git(recently), but not compiled. You can try compiling, by updating the VERSION file in kernel modules with a 4.14 kernel version, and running rebuild kernels.

**Comment by Thinstation** [comment]
Did you get a kernel recompiled? Is this still an issue?

**Comment by Dubby650** [comment]
Hello,
Sorry I was not willing to put it into production because I did not
have a large enough pilot group. I ended up buying more legacy
hardware.

----- Original Message -----
