### ISSUE TITLE
rdesktop cache bitamps not working (-P)

### ISSUE THREAD

**Issue by trentasis** [Thinstation/thinstation#267]
Hi

Trying to use rdesktop with -P to use bitmaps cache we receive mkdir faile in /root/.rdesktop folder, I have tested that if I remove this file then rdesktop generates correctly this folder and us this features

I have two questions why exist .rdesktop file in /root/.rdesktop? and If it is possible how can I remove this empty file from thinstation, I have searched in github without success...

Thanks

**Comment by Thinstation** [comment]
Hmm well that file was committed a long time ago. If it’s no longer needed, you can got rm the file and send a pr.

https://github.com/Thinstation/thinstation/tree/5.5-Stable/ts/build/packages/rdesktop/build/extra/etc/skel

**Comment by trentasis** [comment]
Thanks, I'll try to do some test, and then remove this file if is not
needed and then I'll send a PR

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-01-08 23:59 GMT+01:00 Thinstation <notifications@github.com>:

> Hmm well that file was committed a long time ago. If it’s no longer
> needed, you can got rm the file and send a pr.
>
> https://github.com/Thinstation/thinstation/tree/
> 5.5-Stable/ts/build/packages/rdesktop/build/extra/etc/skel
>
> Sent from my iPhone
>

**Comment by trentasis** [comment]
Tested and solved in this PR https://github.com/Thinstation/thinstation/pull/297
Please update

Thanks

**Comment by trentasis** [comment]
Solved!
