### ISSUE TITLE
Nvidia compling failed

### ISSUE THREAD

**Issue by rohrbachger** [Thinstation/thinstation#268]
package xorg7_nvidia

/build/wget_tmp/NVIDIA-Linux-x86-367.27

WARNING: The '--no-runlevel-check' option is deprecated:  nvidia-installer will ignore this option.

WARNING: You do not appear to have an NVIDIA GPU supported by the 367.27 NVIDIA Linux graphics driver installed in this system.  For further details, please see the appendix
         SUPPORTED NVIDIA GRAPHICS CHIPS in the README available on the Linux driver download page at www.nvidia.com.

WARNING: You specified the '--no-kernel-module' command line option, nvidia-installer will not install a kernel module as part of this driver installation, and it will not remove
         existing NVIDIA kernel modules not part of an earlier NVIDIA driver installation.  Please ensure that an NVIDIA kernel module matching this driver version is installed
         seperately.

ERROR: Installation has failed.  Please see the file './nvidia-installer.log' for details.  You may find suggestions on fixing installation problems in the README available on the
       Linux driver download page at www.nvidia.com.

Press any key to continue or CTRL-C to abort

**nvidia-installer.log**
Looking for install checker script at ./libglvnd_install_checker/check-libglvnd-install.sh
   executing: '/bin/sh ./libglvnd_install_checker/check-libglvnd-install.sh'...
   Checking for libglvnd installation.
   Checking libGLdispatch...
   Can't load library libGLdispatch.so.0: libGLdispatch.so.0: cannot open shared object file: No such file or directory
Will install libglvnd libraries.
-> Searching for conflicting files:
-> done.
-> Installing 'NVIDIA Accelerated Graphics Driver for Linux-x86' (367.27):
   executing: '/sbin/ldconfig'...
-> done.
-> Driver file installation is complete.
-> Running post-install sanity check:
-> done.
-> Post-install sanity check passed.
-> Running runtime sanity check:
ERROR: The runtime configuration check failed for library 'libEGL.so.1' (expected: '/build/packages/xorg7_nvidia/lib/libEGL.so.1', found: (not found)).  The most likely reason for this is that the library was installed to the wrong location or that your system's dynamic loader configuration needs to be updated.  Please check the OpenGL library installation prefix and/or the dynamic loader configuration.
-> done.
-> Runtime sanity check failed.
ERROR: Installation has failed.  Please see the file './nvidia-installer.log' for details.  You may find suggestions on fixing installation problems in the README available on the Linux driver download page at www.nvidia.com.

**I copied the missing file in the expected folder, but run into the next issue.**
Looking for install checker script at ./libglvnd_install_checker/check-libglvnd-install.sh
   executing: '/bin/sh ./libglvnd_install_checker/check-libglvnd-install.sh'...
   Checking for libglvnd installation.
   Checking libGLdispatch...
   Checking libGLdispatch dispatch table
   Checking call through libGLdispatch
   All OK
   libGLdispatch is OK
   Checking for libGLX
   libGLX is OK
   Checking entrypoint library libOpenGL.so.0
   Checking call through libGLdispatch
   Checking call through library libOpenGL.so.0
   All OK
   Entrypoint library libOpenGL.so.0 is OK
   Checking entrypoint library libGL.so.1
   Checking call through libGLdispatch
   Checking call through library libGL.so.1
   glGetString was not called
-> An incomplete installation of libglvnd was found. Do you want to install a full copy of libglvnd? This will overwrite any existing libglvnd libraries. (Answer: Abort installation.)
ERROR: Installation has failed.  Please see the file './nvidia-installer.log' for details.  You may find suggestions on fixing installation problems in the README available on the Linux driver download page at www.nvidia.com.

**Comment by Thinstation** [comment]
This should be fixed now in 5.6-Stable. Please test and report.

**Comment by Thinstation** [comment]
Should also be fixed in 6.1-Stable.
