### ISSUE TITLE
2XClient download url is out of date

### ISSUE THREAD

**Issue by kahvis** [Thinstation/thinstation#273]
When try to ./build, script cannot download 2XClient from out dated url.

And the new version of 2XClient is called RASClient? Should us to change to non comercial x2go?

[https://www.parallels.com/eu/products/ras/download/client/#lin](url)

**Comment by Thinstation** [comment]
You can send a pull request, and I will look at your solution.

**Comment by kahvis** [comment]
Actually this was more lika a question to resolve the issue because I am very new here.

**Comment by Thinstation** [comment]
I don’t use 2X, so I shouldn’t comment on the best course of action here.

**Comment by communitysteps** [comment]
I updated the build.urls in patch [278](https://github.com/Thinstation/thinstation/pull/278) to point to the new RASClient download now hosted at Parallels after the 2X acquisition.

**Comment by Thinstation** [comment]
Merged in 5.5-Stable
