### ISSUE TITLE
Problem with Sound in RDesktop

### ISSUE THREAD

**Issue by m0bYczE** [Thinstation/thinstation#282]
Hello,
I've got a problem with sound on thinstation beacause it's not working.
This is command: `SESSION_0_RDESKTOP_OPTIONS="-f -u 'Boss' -d BSFM -a 24 -x l -r sound:local:alsa -k cs"`

**Comment by Doncuppjr** [comment]
How about using pulse instead?

**Comment by m0bYczE** [comment]
How can I use it ? What packages is needed and how it implement to rdekstop.

Thanks.

**Comment by m0bYczE** [comment]
Sorry, but I don't understand. What package I need and what I must write in te rdesktop options.

**Comment by m0bYczE** [comment]
I found in terminal in /proc/asound/modules, this:
`0 snd_pcsp
1 snd_hda_intel
2 snd_usb_audio`

**Comment by m0bYczE** [comment]
Ok, I fixed by removing the **snd_pcsp**. Thanks and you can close it.
