### ISSUE TITLE
set-resolution fails

### ISSUE THREAD

**Issue by xamber123** [Thinstation/thinstation#283]
I think i've found a breaking bug. When running set-resolution i get this... 
` /bin/set-resolution: line 696: syntax error: unexpected "(" (expecting ";;")`

This is on the client-side thinstation, after building the image.
(live-build)

However i can run set-resolution in the devstation.

####Background####
Trying to utilize the set persistent resolution feature, and i did not work. (I'm using thinstation as a live iso, it's not installed on the clients machine.) I've updated **conf.buildtime** to use:
```
STORAGE_PATH=/mnt/local-install/part2
STORAGE_CONFIG1=/mnt/local-install/part2
```
(I also tried using /mnt/union (then it actually created some files, guessing since the dir union actually exists) 

Please advice.

**Comment by Thinstation** [comment]
This might be related to whether or not you have full gnu bash installed in your image. busybox bash is really only sh, and a limited version of that as well.
