### ISSUE TITLE
Touchscreen - help with serial Penmount touchcontroller

### ISSUE THREAD

**Issue by dannaughton** [Thinstation/thinstation#284]
I was hoping someone could give me a tip on getting this Penmount touchcontroller working with TS 5.5-Stable.  The hardware works (tested it with Win10 with Penmount drivers - during the setup, they polled each COM port  - this one is on COM3 in windows for whatever that's worth).   the "module penmount" is of course added to the build and it will go in with modprobe - but it doesn't do anything.

looking through some very old mailing lists - I found this parameter:
X_TOUCH_DEVICE="/dev/ttyS2"
but I can't tell if this does anything.  (I've tried all of the ttySX ports). 

If anyone can offer me a few points to try things, I will report back.   Thanks all.

**Comment by Thinstation** [comment]
Where is your Xorg.log?

**Comment by dannaughton** [comment]
Please see the following for Xorg.0.log.  It's not even close.  There is nothing in the build about an input section for the xorg.conf - so I'm not sure where to start. There does not appear to be a penmount package - just the driver.  I'm stuggling to find out where all the pieces go to add the right sections to the xorg.conf.d pieces.


Xorg.0.log
[    17.766] 
X.Org X Server 1.18.3
Release Date: 2016-04-04
[    17.766] X Protocol Version 11, Revision 0
[    17.766] Build Operating System: ThinStation Thinstation
[    17.766] Current Operating System: Linux ts_00804cbc984d 4.9.44TS_SMP #1 SMP PREEMPT Tue Aug 22 23:01:51 UTC 2017 i686
[    17.766] Kernel command line: usbhid.quirks=0x1bfd:0x3050:0x40 BOOT_IMAGE=::/boot/vmlinuz initrd=::/boot/initrd  splash=silent,theme:default load_ramdisk=1 ramdisk_blocksize=4096 root=/dev/ram0 ramdisk_size=786432 console=tty1 vt.global_cursor_default=0 quiet loglevel=3 LM=3
[    17.767] Build Date: 02 June 2016  03:08:29AM
[    17.767] Donald A. Cupp Jr. 
[    17.767] Current version of pixman: 0.34.0
[    17.767] 	Before reporting problems, check http://www.thinstation.org
	to make sure that you have the latest version.
[    17.767] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[    17.767] (==) Log file: "/var/log/Xorg.0.log", Time: Tue Feb 20 04:08:20 2018
[    17.768] (==) Using config directory: "/etc/X11/xorg.conf.d"
[    17.768] (==) No Layout section.  Using the first Screen section.
[    17.768] (==) No screen section available. Using defaults.
[    17.768] (**) |-->Screen "Default Screen Section" (0)
[    17.768] (**) |   |-->Monitor "<default monitor>"
[    17.768] (==) No monitor specified for screen "Default Screen Section".
	Using a default monitor configuration.
[    17.768] (**) Option "IgnoreABI" "true"
[    17.768] (**) Option "AutoAddDevices" "true"
[    17.768] (**) Option "AutoEnableDevices" "true"
[    17.768] (**) Ignoring ABI Version
[    17.768] (**) Automatically adding devices
[    17.768] (**) Automatically enabling devices
[    17.768] (==) Automatically adding GPU devices
[    17.769] (==) Max clients allowed: 256, resource mask: 0x1fffff
[    17.769] (WW) The directory "/usr/share/fonts/X11/OTF/" does not exist.
[    17.769] 	Entry deleted from font path.
[    17.769] (WW) The directory "/usr/share/fonts/X11/Type1/" does not exist.
[    17.769] 	Entry deleted from font path.
[    17.769] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[    17.769] 	Entry deleted from font path.
[    17.769] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[    17.769] 	Entry deleted from font path.
[    17.769] (==) FontPath set to:
	/usr/share/fonts/X11/misc/,
	/usr/share/fonts/X11/TTF/
[    17.769] (==) ModulePath set to "/usr/lib/xorg/modules"
[    17.769] (II) The server relies on udev to provide the list of input devices.
	If no devices become available, reconfigure udev or disable AutoAddDevices.
[    17.769] (II) Loader magic: 0x827cb20
[    17.769] (II) Module ABI versions:
[    17.769] 	X.Org ANSI C Emulation: 0.4
[    17.769] 	X.Org Video Driver: 20.0
[    17.769] 	X.Org XInput driver : 22.1
[    17.769] 	X.Org Server Extension : 9.0
[    17.770] (II) xfree86: Adding drm device (/dev/dri/card0)
[    17.772] (--) PCI:*(0:0:2:0) 8086:0f31:8086:2212 rev 17, Mem @ 0xd0000000/4194304, 0xc0000000/268435456, I/O @ 0x0000e020/8, BIOS @ 0x????????/131072
[    17.772] (II) Open ACPI successful (/var/run/acpid.socket)
[    17.772] (II) LoadModule: "glx"
[    17.773] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[    17.804] (II) Module glx: vendor="X.Org Foundation"
[    17.804] 	compiled for 1.18.3, module version = 1.0.0
[    17.804] 	ABI class: X.Org Server Extension, version 9.0
[    17.804] (==) AIGLX enabled
[    17.804] (==) Matched intel as autoconfigured driver 0
[    17.804] (==) Matched intel as autoconfigured driver 1
[    17.804] (==) Matched modesetting as autoconfigured driver 2
[    17.804] (==) Matched fbdev as autoconfigured driver 3
[    17.804] (==) Matched vesa as autoconfigured driver 4
[    17.804] (==) Assigned the driver to the xf86ConfigLayout
[    17.804] (II) LoadModule: "intel"
[    17.804] (II) Loading /usr/lib/xorg/modules/drivers/intel_drv.so
[    17.816] (II) Module intel: vendor="X.Org Foundation"
[    17.816] 	compiled for 1.18.3, module version = 2.99.917
[    17.816] 	Module class: X.Org Video Driver
[    17.816] 	ABI class: X.Org Video Driver, version 20.0
[    17.816] (II) LoadModule: "modesetting"
[    17.816] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[    17.818] (II) Module modesetting: vendor="X.Org Foundation"
[    17.818] 	compiled for 1.18.3, module version = 1.18.3
[    17.818] 	Module class: X.Org Video Driver
[    17.818] 	ABI class: X.Org Video Driver, version 20.0
[    17.818] (II) LoadModule: "fbdev"
[    17.818] (II) Loading /usr/lib/xorg/modules/drivers/fbdev_drv.so
[    17.820] (II) Module fbdev: vendor="X.Org Foundation"
[    17.820] 	compiled for 1.18.3, module version = 0.4.4
[    17.820] 	Module class: X.Org Video Driver
[    17.820] 	ABI class: X.Org Video Driver, version 20.0
[    17.820] (II) LoadModule: "vesa"
[    17.820] (II) Loading /usr/lib/xorg/modules/drivers/vesa_drv.so
[    17.820] (II) Module vesa: vendor="X.Org Foundation"
[    17.820] 	compiled for 1.18.3, module version = 2.3.4
[    17.820] 	Module class: X.Org Video Driver
[    17.820] 	ABI class: X.Org Video Driver, version 20.0
[    17.820] (II) intel: Driver for Intel(R) Integrated Graphics Chipsets:
	i810, i810-dc100, i810e, i815, i830M, 845G, 854, 852GM/855GM, 865G,
	915G, E7221 (i915), 915GM, 945G, 945GM, 945GME, Pineview GM,
	Pineview G, 965G, G35, 965Q, 946GZ, 965GM, 965GME/GLE, G33, Q35, Q33,
	GM45, 4 Series, G45/G43, Q45/Q43, G41, B43
[    17.820] (II) intel: Driver for Intel(R) HD Graphics: 2000-6000
[    17.820] (II) intel: Driver for Intel(R) Iris(TM) Graphics: 5100, 6100
[    17.820] (II) intel: Driver for Intel(R) Iris(TM) Pro Graphics: 5200, 6200, P6300
[    17.820] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[    17.820] (II) FBDEV: driver for framebuffer: fbdev
[    17.820] (II) VESA: driver for VESA chipsets: vesa
[    17.820] (++) using VT number 5

[    17.850] (II) intel(0): Using Kernel Mode Setting driver: i915, version 1.6.0 20160919
[    17.850] (II) intel(0): SNA compiled from 
[    17.855] (WW) Falling back to old probe method for modesetting
[    17.855] (WW) Falling back to old probe method for fbdev
[    17.855] (II) Loading sub module "fbdevhw"
[    17.855] (II) LoadModule: "fbdevhw"
[    17.856] (II) Loading /usr/lib/xorg/modules/libfbdevhw.so
[    17.858] (II) Module fbdevhw: vendor="X.Org Foundation"
[    17.858] 	compiled for 1.18.3, module version = 0.0.2
[    17.858] 	ABI class: X.Org Video Driver, version 20.0
[    17.858] (WW) Falling back to old probe method for vesa
[    17.861] (--) intel(0): Integrated Graphics Chipset: Intel(R) HD Graphics
[    17.861] (--) intel(0): CPU: x86, sse2, sse3, ssse3, sse4.1, sse4.2; using a maximum of 4 threads
[    17.861] (II) intel(0): Creating default Display subsection in Screen section
	"Default Screen Section" for depth/fbbpp 24/32
[    17.861] (==) intel(0): Depth 24, (--) framebuffer bpp 32
[    17.861] (==) intel(0): RGB weight 888
[    17.861] (==) intel(0): Default visual is TrueColor
[    17.864] (II) intel(0): Output eDP1 has no monitor section
[    17.869] (--) intel(0): Found backlight control interface intel_backlight (type 'raw') for output eDP1
[    17.869] (II) intel(0): Enabled output eDP1
[    17.869] (II) intel(0): Output VGA1 has no monitor section
[    17.869] (II) intel(0): Enabled output VGA1
[    17.869] (II) intel(0): Output DP1 has no monitor section
[    17.869] (II) intel(0): Enabled output DP1
[    17.869] (II) intel(0): Output HDMI1 has no monitor section
[    17.869] (II) intel(0): Enabled output HDMI1
[    17.869] (--) intel(0): Using a maximum size of 256x256 for hardware cursors
[    17.869] (II) intel(0): Output VIRTUAL1 has no monitor section
[    17.869] (II) intel(0): Enabled output VIRTUAL1
[    17.869] (--) intel(0): Output eDP1 using initial mode 1024x768 on pipe 0
[    17.869] (==) intel(0): TearFree disabled
[    17.869] (==) intel(0): DPI set to (96, 96)
[    17.869] (II) Loading sub module "dri2"
[    17.869] (II) LoadModule: "dri2"
[    17.870] (II) Module "dri2" already built-in
[    17.870] (II) Loading sub module "present"
[    17.870] (II) LoadModule: "present"
[    17.870] (II) Module "present" already built-in
[    17.870] (II) UnloadModule: "modesetting"
[    17.870] (II) Unloading modesetting
[    17.870] (II) UnloadModule: "fbdev"
[    17.870] (II) Unloading fbdev
[    17.870] (II) UnloadSubModule: "fbdevhw"
[    17.870] (II) Unloading fbdevhw
[    17.870] (II) UnloadModule: "vesa"
[    17.870] (II) Unloading vesa
[    17.870] (==) Depth 24 pixmap format is 32 bpp
[    17.887] (II) intel(0): SNA initialized with Baytrail (gen7) backend
[    17.887] (==) intel(0): Backing store enabled
[    17.888] (==) intel(0): Silken mouse enabled
[    17.888] (II) intel(0): HW Cursor enabled
[    17.888] (II) intel(0): RandR 1.2 enabled, ignore the following RandR disabled message.
[    17.888] (==) intel(0): DPMS enabled
[    17.888] (==) intel(0): Display hotplug detection enabled
[    17.888] (II) intel(0): [DRI2] Setup complete
[    17.888] (II) intel(0): [DRI2]   DRI driver: i965
[    17.888] (II) intel(0): [DRI2]   VDPAU driver: va_gl
[    17.888] (II) intel(0): direct rendering: DRI2 enabled
[    17.888] (II) intel(0): hardware support for Present enabled
[    17.888] (--) RandR disabled
[    17.986] (II) AIGLX: enabled GLX_MESA_copy_sub_buffer
[    17.986] (II) AIGLX: enabled GLX_ARB_create_context
[    17.986] (II) AIGLX: enabled GLX_ARB_create_context_profile
[    17.986] (II) AIGLX: enabled GLX_EXT_create_context_es{,2}_profile
[    17.986] (II) AIGLX: enabled GLX_INTEL_swap_event
[    17.986] (II) AIGLX: enabled GLX_SGI_swap_control and GLX_MESA_swap_control
[    17.986] (II) AIGLX: enabled GLX_EXT_framebuffer_sRGB
[    17.986] (II) AIGLX: enabled GLX_ARB_fbconfig_float
[    17.986] (II) AIGLX: enabled GLX_EXT_fbconfig_packed_float
[    17.986] (II) AIGLX: GLX_EXT_texture_from_pixmap backed by buffer objects
[    17.986] (II) AIGLX: enabled GLX_ARB_create_context_robustness
[    17.986] (II) AIGLX: Loaded and initialized i965
[    17.986] (II) GLX: Initialized DRI2 GL provider for screen 0
[    17.990] (II) intel(0): switch to mode 1024x768@60.0 on eDP1 using pipe 0, position (0, 0), rotation normal, reflection none
[    18.004] (II) intel(0): Setting screen physical size to 270 x 203
[    18.101] (II) config/udev: Adding input device Power Button (/dev/input/event1)
[    18.101] (**) Power Button: Applying InputClass "Keyboard Defaults"
[    18.101] (**) Power Button: Applying InputClass "evdev keyboard catchall"
[    18.101] (II) LoadModule: "evdev"
[    18.101] (II) Loading /usr/lib/xorg/modules/input/evdev_drv.so
[    18.108] (II) Module evdev: vendor="X.Org Foundation"
[    18.108] 	compiled for 1.18.3, module version = 2.10.3
[    18.108] 	Module class: X.Org XInput Driver
[    18.108] 	ABI class: X.Org XInput driver, version 22.1
[    18.108] (II) Using input driver 'evdev' for 'Power Button'
[    18.108] (**) Power Button: always reports core events
[    18.108] (**) evdev: Power Button: Device: "/dev/input/event1"
[    18.108] (--) evdev: Power Button: Vendor 0 Product 0x1
[    18.108] (--) evdev: Power Button: Found keys
[    18.108] (II) evdev: Power Button: Configuring as keyboard
[    18.108] (**) Option "config_info" "udev:/sys/devices/LNXSYSTM:00/LNXPWRBN:00/input/input1/event1"
[    18.108] (II) XINPUT: Adding extended input device "Power Button" (type: KEYBOARD, id 6)
[    18.108] (**) Option "xkb_rules" "evdev"
[    18.108] (**) Option "xkb_layout" "us"
[    18.109] (II) config/udev: Adding input device Video Bus (/dev/input/event4)
[    18.109] (**) Video Bus: Applying InputClass "Keyboard Defaults"
[    18.109] (**) Video Bus: Applying InputClass "evdev keyboard catchall"
[    18.109] (II) Using input driver 'evdev' for 'Video Bus'
[    18.109] (**) Video Bus: always reports core events
[    18.109] (**) evdev: Video Bus: Device: "/dev/input/event4"
[    18.109] (--) evdev: Video Bus: Vendor 0 Product 0x6
[    18.109] (--) evdev: Video Bus: Found keys
[    18.109] (II) evdev: Video Bus: Configuring as keyboard
[    18.109] (**) Option "config_info" "udev:/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:00/input/input6/event4"
[    18.109] (II) XINPUT: Adding extended input device "Video Bus" (type: KEYBOARD, id 7)
[    18.110] (**) Option "xkb_rules" "evdev"
[    18.110] (**) Option "xkb_layout" "us"
[    18.110] (II) config/udev: Adding input device Sleep Button (/dev/input/event0)
[    18.110] (**) Sleep Button: Applying InputClass "Keyboard Defaults"
[    18.110] (**) Sleep Button: Applying InputClass "evdev keyboard catchall"
[    18.110] (II) Using input driver 'evdev' for 'Sleep Button'
[    18.110] (**) Sleep Button: always reports core events
[    18.111] (**) evdev: Sleep Button: Device: "/dev/input/event0"
[    18.111] (--) evdev: Sleep Button: Vendor 0 Product 0x3
[    18.111] (--) evdev: Sleep Button: Found keys
[    18.111] (II) evdev: Sleep Button: Configuring as keyboard
[    18.111] (**) Option "config_info" "udev:/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0E:00/input/input0/event0"
[    18.111] (II) XINPUT: Adding extended input device "Sleep Button" (type: KEYBOARD, id 8)
[    18.111] (**) Option "xkb_rules" "evdev"
[    18.111] (**) Option "xkb_layout" "us"
[    18.112] (II) config/udev: Adding input device HID 0566:3107 (/dev/input/event2)
[    18.112] (**) HID 0566:3107: Applying InputClass "Keyboard Defaults"
[    18.112] (**) HID 0566:3107: Applying InputClass "evdev keyboard catchall"
[    18.112] (II) Using input driver 'evdev' for 'HID 0566:3107'
[    18.112] (**) HID 0566:3107: always reports core events
[    18.112] (**) evdev: HID 0566:3107: Device: "/dev/input/event2"
[    18.112] (--) evdev: HID 0566:3107: Vendor 0x566 Product 0x3107
[    18.112] (--) evdev: HID 0566:3107: Found keys
[    18.112] (II) evdev: HID 0566:3107: Configuring as keyboard
[    18.112] (**) Option "config_info" "udev:/sys/devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.0/0003:0566:3107.0001/input/input4/event2"
[    18.112] (II) XINPUT: Adding extended input device "HID 0566:3107" (type: KEYBOARD, id 9)
[    18.113] (**) Option "xkb_rules" "evdev"
[    18.113] (**) Option "xkb_layout" "us"
[    18.114] (II) config/udev: Adding input device HID 0566:3107 (/dev/input/event3)
[    18.114] (**) HID 0566:3107: Applying InputClass "Keyboard Defaults"
[    18.114] (**) HID 0566:3107: Applying InputClass "evdev keyboard catchall"
[    18.114] (II) Using input driver 'evdev' for 'HID 0566:3107'
[    18.114] (**) HID 0566:3107: always reports core events
[    18.114] (**) evdev: HID 0566:3107: Device: "/dev/input/event3"
[    18.114] (--) evdev: HID 0566:3107: Vendor 0x566 Product 0x3107
[    18.114] (--) evdev: HID 0566:3107: Found 1 mouse buttons
[    18.114] (--) evdev: HID 0566:3107: Found scroll wheel(s)
[    18.114] (--) evdev: HID 0566:3107: Found relative axes
[    18.114] (II) evdev: HID 0566:3107: Forcing relative x/y axes to exist.
[    18.114] (--) evdev: HID 0566:3107: Found absolute axes
[    18.114] (II) evdev: HID 0566:3107: Forcing absolute x/y axes to exist.
[    18.114] (--) evdev: HID 0566:3107: Found keys
[    18.114] (II) evdev: HID 0566:3107: Configuring as mouse
[    18.114] (II) evdev: HID 0566:3107: Configuring as keyboard
[    18.114] (II) evdev: HID 0566:3107: Adding scrollwheel support
[    18.114] (**) evdev: HID 0566:3107: YAxisMapping: buttons 4 and 5
[    18.114] (**) evdev: HID 0566:3107: EmulateWheelButton: 4, EmulateWheelInertia: 10, EmulateWheelTimeout: 200
[    18.114] (**) Option "config_info" "udev:/sys/devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.1/0003:0566:3107.0002/input/input5/event3"
[    18.114] (II) XINPUT: Adding extended input device "HID 0566:3107" (type: KEYBOARD, id 10)
[    18.114] (**) Option "xkb_rules" "evdev"
[    18.114] (**) Option "xkb_layout" "us"
[    18.115] (II) evdev: HID 0566:3107: initialized for relative axes.
[    18.115] (WW) evdev: HID 0566:3107: ignoring absolute axes.
[    18.115] (**) HID 0566:3107: (accel) keeping acceleration scheme 1
[    18.115] (**) HID 0566:3107: (accel) acceleration profile 0
[    18.115] (**) HID 0566:3107: (accel) acceleration factor: 2.000
[    18.115] (**) HID 0566:3107: (accel) acceleration threshold: 4


##########  End of Xorg..0.log################

**Comment by dannaughton** [comment]
Last comment - is the the right place for this - or should I use the mailing list?
