### ISSUE TITLE
Black screen on DevStation boot

### ISSUE THREAD

**Issue by rchildress87** [Thinstation/thinstation#285]
Hello,

I installed DevStation on a virtual machine today by booting TS-5.5.2-Installer-0628.iso and running the standard installer.  I was using VirtualBox 5.2.6 and the VM had 2GB RAM, 20GB virtual disk, 2 virtual CPUs, 32MB video memory, and bridged networking.

After reboot and selecting "Standard" from the boot loader, I received a black screen without a cursor.  I waited several minutes before rebooting and beginning to debug.

I found that changing `console=tty1` to `console=tty0` in the boot loader menu entry allowed DevStation to boot properly. However, the following warning is displayed during boot, before XFCE starts:

> You don't appear to have a correct console= setting on your kernel command line.  Client splash will not be enabled.  Please add console=tty1 or CONSOLE=/dev/tty1 to your kernel command line to avoid this message.

**Comment by rchildress87** [comment]
I have confirmed that I am able to recreate the issue using a default VirtualBox Linux VM with 2 vCPUs, 2GB RAM, 20GB storage, and 16MB video memory.

Here is a screenshot of the bug, including some graphical errors.  The red marks at the top do not always appear when recreating the bug.

![image](https://user-images.githubusercontent.com/13559499/36451983-cb7364ec-1660-11e8-899d-1c9434418ac6.png)

**Comment by rchildress87** [comment]
Testing further, I found that setting console=tty0 is not the actual workaround.  Setting console= to something other than tty1 disables client splash, which is the culprit.

Simply removing "splash=silent,theme:default" from the kernel command line in the boot loader entry allows DevStation to boot properly without errors.

**Comment by Thinstation** [comment]
You could probably increase vga ram to 128

**Comment by rchildress87** [comment]
Yes, that was the trick.  The boot splash will break the boot process unless 65MB or more of video memory is available to the machine.

This is not a bug.  I just missed the video ram requirement in the DevStation docs.  I do find it odd though, that in VirtualBox on my computer, 64MB is not enough memory.  Video memory must be >= 65MB.
