### ISSUE TITLE
Graphics not working on IGEL H700C (Via Chrome 9)

### ISSUE THREAD

**Issue by SZenglein** [Thinstation/thinstation#287]
Hi,

the graphics either don't work at all or look garbled. My screen has a resolution of 1680x1050.

What I tried: Thinstation 5.5 with Vesa and openchrome drivers enabled.

Vesa: Graphics seem to almost work. I can see a reaction to input, but the lines are strangely shifted.

Openchrome: There is an unresponsive section of red artefacts at the top of the screen.

I would be glad if you could help me out with this. 

Vesa: ![vesa](https://user-images.githubusercontent.com/13049685/36939652-bf3a3c1e-1f34-11e8-973c-2ea40868ca13.jpg)

Openchrome: ![openchrome](https://user-images.githubusercontent.com/13049685/36939646-b81c5db8-1f34-11e8-9760-dd0913a0e62d.jpg)

**Comment by SZenglein** [comment]
It's connected via DVI. 

Do you know of some options that could be related? Any X configuration? I could also compile stuff if necessary. Any help is appreciated.

Also, how can I troubleshoot this? I can't access tty or view logs. Unfortunately the wiki link to opening a console is not working.

**Comment by Thinstation** [comment]
Put DEBUGPAUSE= true in thinstation.conf.buildtime, build and boot, will leave you at the cli. Manually run X

**Comment by SZenglein** [comment]
Unfortunately that doesn't work. The display does not even detect the client anymore (it turns off).

Before, it would also turn off after the kernel messages and try to find the graphics adapter again, but it eventually worked.

**Comment by SZenglein** [comment]
I now have an image with vesa when running build *without* --allmodules. But the resolution is too low and can't be changed.

**Comment by Thinstation** [comment]
find /lib/modules -name via.ko -delete, then do an all modules build

**Comment by SZenglein** [comment]
Unfortunately, that results in a black screen. I have no idea if it was even found.

What fixed my problems was doing a build without '--allmodules'. I think it falls back to the vesa driver. There are a number of issues but it is working:

- Screen resolution can't be changed.  The screen resolution is fixed on the boot resolution specified in build.conf this is obviously a major inconvenience.
- Graphics are pretty slow. I have no reference on how fast the graphics should be, but I suspect it's using software emulation. It's better than having no image at all.

**Comment by SZenglein** [comment]
I'd be happy to hear another suggestion from you, otherwise please just close the issue.
