### ISSUE TITLE
Logitech Mouse with unify does not work

### ISSUE THREAD

**Issue by meddi** [Thinstation/thinstation#288]
I created an image with kernel modules for logitech unify (hid-logitech-dj and hid-logitech-hiddpp). When the system boots, I don't see any udev events to load these drivers.
After you reconnect the Unify receiver, the driver will load and everything will work fine.
An image with all modules works right from the start.
Does anyone have any idea where I can look?

Information: Thinstation Version 5.3

**Comment by Doncuppjr** [comment]
Interesting. YouTube 3D?


Sent from Yahoo Mail for iPhone


On Saturday, March 17, 2018, 10:25 AM, meddi <notifications@github.com> wrote:


I created an image with kernel modules for logitech unify (hid-logitech-dj and hid-logitech-hiddpp). When the system boots, I don't see any udev events to load these drivers.
After you reconnect the Unify receiver, the driver will load and everything will work fine.
An image with all modules works right from the start.
Does anyone have any idea where I can look?

Information: Thinstation Version 5.3

**Comment by Thinstation** [comment]
Should really go up to 5.6, I'm sure udev was updated, and may work better with small module sets.
