### ISSUE TITLE
Freerdp fails because of Microsoft Updates - update of freerdp required

### ISSUE THREAD

**Issue by alphafalcon** [Thinstation/thinstation#289]
Last week, my prototype device stopped connecting to our terminal server farm.
I've since traced the problem to a MS update that breaks freerdp's NLA implementation.
The problem was fixed on freerdps side in FreeRDP/FreeRDP#4510 

edit:
I'm working with the 5.6 branch, so this might be different for other branches - but as long as they reference the freerdp/master branch, it should work.
/edit

I've managed to manually get my build connecting again by commenting out the patch in `/ts/ports/opt/freerdp/Pkgfile`
and running
`prt-get -uf update freerdp` and `repackage freerdp`
and rebuilding my images.

Sadly I lack the knowledge to provide a fix for the thinstation repo.

**Comment by havrazO** [comment]
@alphafalcon 
Thanks for the info, i faced the same problem so i had to deactivat nla with -sec-nla 
now i am trying to update my freerdp to the last commit...but no success
can you please give more details/steps on how you did the update of freerdp package ? specially about commenting out the patch in Pkgfile.

**Comment by havrazO** [comment]
Thanks alot for the quick response and for the clear how-to.
in my /ts/ports/opt/freerdp/Pkgfile there is no line with patch -Np.... thats way ididnt get it the first time 

the TS branch where i need to upgrade freerdp is 5.5-which comes in DevStation
i did the other steps anyway and now waiting the image to finish building. then i'll test it and report the resault here.

**Comment by alphafalcon** [comment]
Ah, sorry, I'm running on 5.6 - edited the original issue to reflect that.
If I'm reading the 5.5 freerdp Pkgfile correctly, it clones freerdp/master as well, so you should be good.

**Comment by havrazO** [comment]
finally finished build with --allmodules --kernel 64

it didn't worked, i'm still stuck with version 2.0.0 dev git f8c9f43

**Comment by communitysteps** [comment]
Submitted pull request [#290](https://github.com/Thinstation/thinstation/pull/290) removing references to freerdp-2.0.0-tprdp.patch in 5.6-Stable. 

As previously noted, 5.5-Stable already pulls from FreeRDP release=master

**Comment by eaydin** [comment]
As of 5.6-stable release it still seems to ship FreeRDP version 2.0.0-dev (git f8c9f43)

As per @communitysteps ' comment, he says that 5.5-Stable pulls from FreeRDP release=master, yet I've installed that version too and it also has the precompiled 2.0.0-dev (git f8c9f43) version.

Is there a way to compile the latest version before waiting for an updated shipment of Thinstation?

**Comment by Thinstation** [comment]
Just pushed some updates to 5.6-Stable, including a recompile of the freerdp port to the tip of master as of 04/13/2018
