### ISSUE TITLE
PXE Boot Fails

### ISSUE THREAD

**Issue by Seg22** [Thinstation/thinstation#294]
Hey Guys,

it´s more a Problem then an issue but i dont see any other option to contact you so... hope you can help me.

I´ve already got everything to work like i want, so now i switched the tftp server from devstation to my windows server, of course i´ve put all my files with me in the correct tftp-root folder. Now, when i start pxe, i can see how he loads:
pxelinux.0
ldlinux.c32
pxelinux.cfg\default
vmlinuz
initrd
and then stops with the error "Booting Kernel Failed: invalid argument"

I only change the server ip (in dhcp 66) to devstation and it works, in both folders are the same data, i´ve already tried different tftp servers like openTFTP and Solarwind TFTP and different block sizez, nothing works for me.

Hope you can help.

**Comment by Thinstation** [comment]
^M
It’s the way you transferred the files to your windows server. Md5, and you should see.

**Comment by Seg22** [comment]
Oh wow... so easy.

Thanks mate and sorry for wasting your time.

Changed ftp mode to binary and it´s done.
