### ISSUE TITLE
Help required 450 computers needed

### ISSUE THREAD

**Issue by AzureusNation** [Thinstation/thinstation#304]
Im currently looking at getting this installed on 450 computers across our school trust. We want this to be installed on the hard drives rather than pxe as we are notgoing to be having servers on site no more.

We need help configuring this for RDP connection broker and maing deployment to all of these machines as easy as possible. They are mainly Dell Optiplex 740s or Dell Optiple 3010s. Your help would be greatly appreciated.

Is there anyway of also making this bootable from usb and then automaticly formating the client hard drive and install ThinStation.

Thanks

Ashley

**Comment by Thinstation** [comment]
You should be able to work through those things in irc.
