### ISSUE TITLE
Freerdp, +drives option

### ISSUE THREAD

**Issue by havrazO** [Thinstation/thinstation#308]
i'm trying to redirect usb drives and a usb cdrom in freerdp session 
when i pass a static parameters like 
/drive:USB,/mnt/usbdrives freerdp won't connect to the TS if the usb drive not mounted on the device 
and when i use the option +drive to pass all mounted devices, this redirect only the cdrom and without /drive:CDROM,/mnt/cdrom0

i thought +drive Option does not recognise the usb devices so i tried to make a dir manuly in the webserver configs 
AUTORUNS_RC5_#="mkdir /mnt/usbdevice"   but this works only ones. cuz by unplugging the usb-drive this dir is removed and freerdp makes no connection again.
 
using master branch now, downloaded couple of days ago

in conf.buildtime contains 
...
BIND_MOUNT0="storage:/mnt/storage"
STORAGE_CONFIG1=/mnt/storage
USB_ENABLED=on
USB_STORAGE_SYNC=on
USB_MOUNT_DIR=usbdevice
USB_MOUNT_USELABEL="Yes"
BASE_MOUNT_PATH=/mnt
CDROM_MOUNT_OPTION="rw,uid=1000,gid=1000"
USB_MOUNT_OPTION="rw,uid=1000,gid=1000"
RNGD=enabled
MOUNT_0="LABEL=boot       /boot        auto   x-mount.mkdir,defaults   0    0"
MOUNT_1="LABEL=home       /tsuser        auto   x-mount.mkdir,defaults   0    0"
MOUNT_2="LABEL=swap        swap           swap     defaults   0     0"
..

and those packages are included  build.conf

package  overlays
package  ts-classic
package  automount
package  udisks
package udisks-glue
package switchuser
package cdrtools
package usbmodeswitch

i noticed that some usb-drives with deferent fs appears under /media and they get a desktop shortcut not like FAT32 formatted usbdirve.. i dont know if this is how it supposed to work 

did i miss something ? is there a way to make +drives option in freerdp  works ?

**Comment by andycher11** [comment]
I have the same issue whith ts5.6 and freerdp. Yesturday i switched from ts 5.5, which work fine. When i try with /drive:'USB,/mnt/usbdevice/' or /drive:'CDROM,/mnt/cdrom0'  freerdp does not connect. Вut if i started whith plugged in drive, all is working.

**Comment by Doncuppjr** [comment]
FreeRDP Friday?


Sent from Yahoo Mail for iPhone


On Friday, May 18, 2018, 3:52 AM, andycher11 <notifications@github.com> wrote:


I have the same issue whith ts5.6 and freerdp. Yesturday i switched from ts 5.5, which work fine. When i try with /drive:'USB,/mnt/usbdevice/' or /drive:'CDROM,/mnt/cdrom0' freerdp does not connect. Вut if i started whith plugged in drive, all is working.

**Comment by andycher11** [comment]
No, i installed thinstation yesturday Thursday at 14 00 UTC

**Comment by havrazO** [comment]
Don, 
I  faced this problem on Monday,  but I was thinking  maybe it's sth I did wrong and trying to solve it by my self before posting an issue 

I have now a second workaround ,
With cronjob
Every minute mkdir   /mnt/usbdevice 

Not optimal .. But do the job for now

**Comment by Thinstation** [comment]
This should be fixed in 6.1
