### ISSUE TITLE
how to add script file aften autologin on console 

### ISSUE THREAD

**Issue by windyma** [Thinstation/thinstation#310]
Hi bro
I want to add a script file , it's used to autostart vmware-view (TS-5.5.2-Installer-0628)
Can you tell me how to do?
Thanks

**Comment by windyma** [comment]
No, I have installed it into hdisk by TS-5.5.2-Installer-0628.iso and Builded a boot image .
Now, my thinpc can autologin on console  via pxeboot this image, it's work fine.
So i want to add a startup script file in this boot image to autostart vmware view client .if it's ok, the end-user only need enter username and password,they can remote to vmware connection server
-------script command------------------------------------------------------------------------
vmware-view --serverURL=connection_server --domainName=xxxx -q --nomenubar --fullscreen --once

**Comment by Doncuppjr** [comment]
So this is the scenario around which TS was designed. A script is not necessary, as you need only define VMware view as a session. 0 is generally reserved for the WM, but can be allocated to an client application. A better solution is to leave them WM at 0, and put the client on session 1, and set it to auto start. Might also want to put the WM in kiosk mode. Please search the mail archives for details.


Sent from Yahoo Mail for iPhone


On Thursday, June 28, 2018, 6:35 PM, windyma <notifications@github.com> wrote:


No, I have installed it into hdisk by TS-5.5.2-Installer-0628.iso and Builded a boot image .
Now, my thinpc can autologin on console via pxeboot this image, it's work fine.
So i want to add a startup script file in this boot image to autostart vmware view client .if it's ok, the end-user only need enter username and password,they can remote to vmware connection server

-------script command------------------------------------------------------------------------
vmware-view --serverURL=connection_server --domainName=xxxx -q --nomenubar --fullscreen --once

**Comment by windyma** [comment]
Thank you for reply.But i have not found out this config file which it can define vmware view as a ssesson and put it in kiosk mode ,Please tell me where can find it

**Comment by Doncuppjr** [comment]
thinstation.conf.buildtime, can use netfiles as well, if you need a dynamic solution beyond built iso


Sent from Yahoo Mail for iPhone


On Thursday, June 28, 2018, 7:35 PM, windyma <notifications@github.com> wrote:


Thank you for reply.But i have not found out this config file which it can define vmware view as a ssesson and put it in kiosk mode ,Please tell me where can find it

**Comment by windyma** [comment]
Add below text in end of thinstation.conf.buildtime 
---------------------------------------------
vmware-view_LEVEL=1
SESSION_1_TYPE=kiosk
SESSION_1_AUTOSTART=on
---------------------------------------------
And, add below text in build.conf.example
param vmware-view --serverURL=connection_server --domainName=xxxx -q --nomenubar --fullscreen --once
then ./rebuild , is it right?

**Comment by Doncuppjr** [comment]
Ehh, no. Post your .conf and .buildtime, I will review.


Sent from Yahoo Mail for iPhone


On Thursday, June 28, 2018, 8:12 PM, windyma <notifications@github.com> wrote:


Add below text in end of thinstation.conf.buildtime

vmware-view_LEVEL=1
SESSION_1_TYPE=kiosk
SESSION_1_AUTOSTART=on

And, add below text in build.conf.example
param vmware-view --serverURL=connection_server --domainName=xxxx -q --nomenubar --fullscreen --once
then ./rebuild , is it right?

**Comment by windyma** [comment]
Add below text in end of thinstation.conf.buildtime 
vmware-view_LEVEL=1
SESSION_1_TYPE=kiosk
SESSION_1_AUTOSTART=on

And, add below text in build.conf.example
param vmware-view --serverURL=connection_server --domainName=xxxx -q --nomenubar --fullscreen --once
then ./rebuild , is it right?

**Comment by Thinstation** [comment]
Sigh, seems like this package is very broken at the moment. I'll try and
patch it up. Your not really making the right moves either, but right now
there is not a smooth solution, so a little confusion is to be expected.

**Comment by windyma** [comment]
@Thinstation thank you very much

**Comment by windyma** [comment]
[thinstation conf.zip](https://github.com/Thinstation/thinstation/files/2151174/thinstation.conf.zip)
Yesterday I did a try, above is my configuration files,it can rebuild boot a image.
but when the thinPC load system via pxeboot this image , show error:package vmhorizonclient doesn't exist,aborting bootup, check your thinstation.conf file and build.conf file to make sure you have the package loaded.

**Comment by Doncuppjr** [comment]
Yeah, change session to vmview without any additional characters. About 4 more road blocks after that. Actually made a sample, but it’s broken build/conf/vmviewpcoip/*


Sent from Yahoo Mail for iPhone


On Friday, June 29, 2018, 4:17 PM, windyma <notifications@github.com> wrote:


thinstation conf.zip
Yesterday I did a try, above is my configuration files,it can rebuild boot a image.
but when the thinPC load system via pxeboot this image , show error:package vmhorizonclient doesn't exist,aborting bootup, check your thinstation.conf file and build.conf file to make sure you have the package loaded.

**Comment by windyma** [comment]
@ @ @Doncuppjr Thanks a lot

**Comment by windyma** [comment]
[thinstaton confuration.zip](https://github.com/Thinstation/thinstation/files/2151380/thinstaton.confuration.zip)
i have rebuilded a new boot image by this configuration files,The thinpc can autostart vmware view client and connect my connection server

**Comment by windyma** [comment]
now, i have two questions
1. vmware-view application option "-q, --nonInteractive  connect automatically if enough value are given on the command line."  is which one of vmwareview session option?
2. how to shutdown thinpc in system, if not press power button on thinpc 's box
