### ISSUE TITLE
Problem with testing connection

### ISSUE THREAD

**Issue by mostafa-amaan** [Thinstation/thinstation#311]
Hello
I am Mostafa from Egypt.

I  have implemented your steps in the explanation Until I reached a step that thinstation testing connection.
But he keep to say internet connectivity test failed !
Knowing that I am testing the connection through ping command & I get a response. 

What can I do to solve this problem?

Thank you

![001](https://user-images.githubusercontent.com/27233796/42138174-4c94cf5a-7d79-11e8-91f0-13c5b676e4a9.png)
![002](https://user-images.githubusercontent.com/27233796/42138175-4cb9e768-7d79-11e8-8e9e-42b22ea2db87.png)
![003](https://user-images.githubusercontent.com/27233796/42138176-4ce09c5a-7d79-11e8-8fd4-6b76bf18a9b5.png)
![004](https://user-images.githubusercontent.com/27233796/42138177-4d0793c8-7d79-11e8-9e58-5e2f42d7ec51.png)
![005](https://user-images.githubusercontent.com/27233796/42138178-4d2e59fe-7d79-11e8-8d7d-ef2da364e1a4.png)
![006](https://user-images.githubusercontent.com/27233796/42138179-4d5707e6-7d79-11e8-90d5-24c1984219ee.png)

**Comment by Doncuppjr** [comment]
Are you behind a proxy?


Sent from Yahoo Mail for iPhone


On Sunday, July 1, 2018, 12:56 PM, Mostafa Amaan <notifications@github.com> wrote:


Hello
I am Mostafa from Egypt.

I have implemented your steps in the explanation Until I reached a step that thinstation testing connection.
But he keep to say internet connectivity test failed !
Knowing that I am testing the connection through ping command & I get a response.

What can I do to solve this problem?

Thank you

**Comment by mostafa-amaan** [comment]
No
I am directly connected to the router.

**Comment by Doncuppjr** [comment]
Does your provider proxy your connection?


Sent from Yahoo Mail for iPhone


On Sunday, July 1, 2018, 1:11 PM, Mostafa Amaan <notifications@github.com> wrote:


No
I am directly connected to the router.

**Comment by havrazO** [comment]
I also had this Problem,  try many times or reinstall tell it works ..
Or just use a Linux Distro like openSUSE as I did.

**Comment by Doncuppjr** [comment]
Might be sourceforge, but you really don’t need devstation. It does get you up and running quickly, but only when you can get it installed. Try just cloning on a regular distribution.


Sent from Yahoo Mail for iPhone


On Sunday, July 1, 2018, 1:35 PM, havrazO <notifications@github.com> wrote:


I also had this Problem, try many times or reinstall tell it works ..
Or just use a Linux Distro like openSUSE as I did.

**Comment by mostafa-amaan** [comment]
Check this out
When i have pressed the Yes button to make proxy setup, And when i pressed help button he said my location is not supported ?!!
<img width="960" alt="007" src="https://user-images.githubusercontent.com/27233796/42139784-2b9aeb06-7d95-11e8-8e94-f6ea7fc34891.png">
<img width="960" alt="008" src="https://user-images.githubusercontent.com/27233796/42139785-2bc55116-7d95-11e8-88fc-cd1d116700b1.png">

**Comment by carlosadelson** [comment]
I have the same problem
I can not install it because connectivity failed

**Comment by Thinstation** [comment]
For the time being DevStation is on hiatus. The current thinstation release is 6.1.0, and can be downloaded on just about any desktop focused Linux disto as either a tar.gz or fit clone.
