### ISSUE TITLE
Console font from locale not apply at boot

### ISSUE THREAD

**Issue by svalx** [Thinstation/thinstation#312]
I have an issue with console font on TTY TS 5.6 Git. I am use ru_RU.UTF-8 locale. In boot.log I see: _Loading console font : default8x16.psfu.gz_ - without errors. Then I  go to TTY2, login, switch to Russian keyboard (it works fine), but instead local chars I see small rectangles... Typing **setfont /lib/kbd/consolefonts/default8x16.psfu.gz** (default font for my locale for package locale-ru_RU) loads font successful and instead rectangles I see question marks now :( 
Well, I found a correct console font with Cyrillic symbols - LatArCyrHeb-16.psfu.gz and add it to packages/locale-ru_RU/lib/kbd/consolefonts. Now I see in boot.log: _Loading console font : LatArCyrHeb-16.psfu.gz_. But for my console all the same, it does not change font at boot - I see small rectangles instead a Russian symbols. I need type  **setfont /lib/kbd/consolefonts/LatArCyrHeb-16.psfu.gz** after login to console, and only then I will get a right symbols look.
How I can apply needed console font at boot time to all TTY?
As a temporary solution I copy next lines from packages/locale/etc/init.d/console-keymap to packages/base/etc/profile:
```
if [ -e /lib/kbd/consolefonts/$CONSOLE_FONT ] && [ "$CONSOLE_FONT" != "" ] ; then
                setfont /lib/kbd/consolefonts/$CONSOLE_FONT
fi
```
Place this code to begin of file. It works, but I'm not sure that's the right way.

**Comment by Doncuppjr** [comment]
Try 6.1


Sent from Yahoo Mail for iPhone


On Thursday, July 5, 2018, 4:29 AM, Alexey Svistunov <notifications@github.com> wrote:


I have an issue with console font on TTY TS 5.6 Git. I am use ru_RU.UTF-8 locale. In boot.log I see: Loading console font : default8x16.psfu.gz - without errors. Then I go to TTY2, login, switch to Russian keyboard (it works fine), but instead local chars I see small rectangles... Typing setfont /lib/kbd/consolefonts/default8x16.psfu.gz (default font for my locale fro package locale-ru_RU) loads font successful and instead rectangles I see question marks now :(
Well, I found a correct console font with Cyrillic symbols - LatArCyrHeb-16.psfu.gz and add it to packages/locale-ru_RU/lib/kbd/consolefonts. Now I see in boot.log: Loading console font : LatArCyrHeb-16.psfu.gz. But for my console all the same, it does not change font at boot - I see small rectangles instead a Russian symbols. I need type setfont /lib/kbd/consolefonts/LatArCyrHeb-16.psfu.gz after login to console, and only then I will get a right symbols look.
How I can apply needed console font at boot time to all TTY?
As a temporary solution I copy next lines from packages/locale/etc/init.d/console-keymap to packages/base/etc/profile:
if [ -e /lib/kbd/consolefonts/$CONSOLE_FONT ] && [ "$CONSOLE_FONT" != "" ] ; then
                setfont /lib/kbd/consolefonts/$CONSOLE_FONT
fi

Place this code to begin of file. It works, but I'm not sure that's the right way.

**Comment by svalx** [comment]
Is 6.1 x64 only? I have a 32bit machines...

**Comment by Doncuppjr** [comment]
Yes, 6.1 is 64 bit only.


Sent from Yahoo Mail for iPhone


On Friday, July 6, 2018, 2:29 AM, Alexey Svistunov <notifications@github.com> wrote:


Is 6.1 x64 only? I have a 32bit machines...

**Comment by svalx** [comment]
Sorry, then I can not check. There is global changes there?

**Comment by Doncuppjr** [comment]
Yes. Switched to systemd init. 


Sent from Yahoo Mail for iPhone


On Friday, July 6, 2018, 7:59 AM, Alexey Svistunov <notifications@github.com> wrote:


Sorry, then I can not check. There is global changes there?

**Comment by Thinstation** [comment]
I have merged your PR, and made it a little smarter. Please review and let me know if it still works for you.

**Comment by svalx** [comment]
This not worked. echo `find /dev/vcs[1-6] | grep -o [1-6]` gives only "1" at boot time (to logfile), but after init it gives "1 2 3 4 5". Font changed for console 1, but not for other consoles. I suggest to explicitly set console numbers in the parameters.

**Comment by Doncuppjr** [comment]
I doubt that would work, and is likely only to produce errors in the log file. If the kernel hasn’t opened an fd for the vc, no commands that operate on the vc will work. Your original course of action of adding set font to profile might be the most correct.

**Comment by svalx** [comment]
I tested the option:
```
                 for TTY in 1 2 3 4 5; do
                         setfont -C /dev/tty$TTY /lib/kbd/consolefonts/$CONSOLE_FONT
                 done
```
  and it works. Errors in boot.log and dmesg is not observed.
Adding setfont to profile cause error `putfont: KDFONTOP: Operation not permitted` when login through SSH.

**Comment by Doncuppjr** [comment]
The problem with that approach, is that if the vc does not exist already, and your run setfont, the vc will be created. That is not a secure solution.

**Comment by Thinstation** [comment]
I have added the font and keymap setup to profile, but with a test to see
if we are on a tty or a pts. This should work for ssh, and not make any
extra fd's via parallel configuration.
