### ISSUE TITLE
CentOS 7.3 compile failure 

### ISSUE THREAD

**Issue by JohnCaiJun** [Thinstation/thinstation#313]
When I clone the thinstation from there, and i do the work 

~]# cd thinstation
~]# ./setup-chroot

but there have a failure like this
rm: command not found 
set: command not found
mkdir: command not found
....

i know the PATH lack /bin ， so I find the file thinstation/ts/TS_ENV， and I add this '/bin'  at PATH , like this 

 old： PATH=$PATH:/ts/bin:/sbin:
 new ：PATH=$PATH:/ts/bin:/sbin:/bin

yes ,  it's work .

I forget the version , it somes like is 5.1-Stable , or 6.1-Statble.

so i wish you know.......

my English is not good, this is my first time to do this , if i do something wrong ,  plz forgive me....

**Comment by Doncuppjr** [comment]
Is your CentOS 32bit?


Sent from Yahoo Mail for iPhone


On Sunday, July 8, 2018, 11:13 PM, CAIJUN <notifications@github.com> wrote:


When I clone the thinstation from there, and i do the work

~]# cd thinstation
~]# ./setup-chroot

but there have a failure like this
rm: command not found
set: command not found
mkdir: command not found
....

i know the PATH lack /bin ， so I find the file thinstation/ts/TS_ENV， and I add this '/bin' at PATH , like this

old： PATH=$PATH:/ts/bin:/sbin:
new ：PATH=$PATH:/ts/bin:/sbin:/bin

yes , it's work .

I forget the version , it somes like is 5.1-Stable , or 6.1-Statble.

so i wish you know.......

my English is not good, this is my first time to do this , if i do something wrong , plz forgive me....

**Comment by Doncuppjr** [comment]
I’ll look into it.


Sent from Yahoo Mail for iPhone


On Sunday, July 8, 2018, 11:13 PM, CAIJUN <notifications@github.com> wrote:


When I clone the thinstation from there, and i do the work

~]# cd thinstation
~]# ./setup-chroot

but there have a failure like this
rm: command not found
set: command not found
mkdir: command not found
....

i know the PATH lack /bin ， so I find the file thinstation/ts/TS_ENV， and I add this '/bin' at PATH , like this

old： PATH=$PATH:/ts/bin:/sbin:
new ：PATH=$PATH:/ts/bin:/sbin:/bin

yes , it's work .

I forget the version , it somes like is 5.1-Stable , or 6.1-Statble.

so i wish you know.......

my English is not good, this is my first time to do this , if i do something wrong , plz forgive me....

**Comment by JohnCaiJun** [comment]
Not 32bit， this is my CentOS :

Linux centos 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux


And there still have a problem about chrome application, but I solved by myself.

In this file "thinstation/build/build.conf" 

package chrome

And the question is in this file '' thinstation/build/build.urls”

param chromeurl        https://dl.google.com/linux/direct/google-chrome-stable_current_i386.deb

When I run "./build" , and it’s need to be download chrome , and I input “Y”, it’s failure.

(I dont’t know if because I’m in china )

And I changed this url like this 

Param chromeurl 	 https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb <https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb>

It’s work, I download this chrome, but there still have a question , and I still solved .

In this file “thinstation/build/packages/chrome/install”

I changed like this:

	ar -x $gzname
  
	#lzma -d data.tar.xz

	tar -Jxf data.tar.xz

It’s work again. So lzma can’t run normally.

I don’t know if it is a package problem, I want to know if the first url I can get download chrome, so I would not change this "chrome/install” file?.

Maybe it’s because I’m in china , generate so many problems……

I don’t know why, but I finally resolved these problem.

thks . 


> 在 2018年7月9日，下午10:32，Donald A. Cupp Jr. <notifications@github.com> 写道：
> 
> Is your CentOS 32bit?
> 
> 
> Sent from Yahoo Mail for iPhone
> 
>

**Comment by JohnCaiJun** [comment]
Not 32bit， this is my CentOS :Linux centos 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/LinuxAnd there still have a problem about chrome application, but I solved by myself.In this file "thinstation/build/build.conf" package chromeAnd the question is in this file '' thinstation/build/build.urls”param chromeurl        https://dl.google.com/linux/direct/google-chrome-stable_current_i386.debWhen I run "./build" , and it’s need to be download chrome , and I input “Y”, it’s failure.(I dont’t know if because I’m in china )And I changed this url like this Param chromeurl 	 https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.debIt’s work, I download this chrome, but there still have a question , and I still solved .In this file “thinstation/build/packages/chrome/install”I changed like this:	ar -x $gzname  	#lzma -d data.tar.xz	tar -Jxf data.tar.xzIt’s work again. So lzma can’t run normally.I don’t know if it is a package problem, I want to know if the first url I can get download chrome, so I would not change this "chrome/install” file?.Maybe it’s because I’m in china , generate so many problems……I don’t know why, but I finally resolved these problem.thks . 在 2018年7月9日，下午10:32，Donald A. Cupp Jr. <notifications@github.com> 写道：Is your CentOS 32bit?


Sent from Yahoo Mail for iPhone


On Sunday, July 8, 2018, 11:13 PM, CAIJUN <notifications@github.com> wrote:


When I clone the thinstation from there, and i do the work

~]# cd thinstation
~]# ./setup-chroot

but there have a failure like this
rm: command not found
set: command not found
mkdir: command not found
....

i know the PATH lack /bin ， so I find the file thinstation/ts/TS_ENV， and I add this '/bin' at PATH , like this

old： PATH=$PATH:/ts/bin:/sbin:
new ：PATH=$PATH:/ts/bin:/sbin:/bin

yes , it's work .

I forget the version , it somes like is 5.1-Stable , or 6.1-Statble.

so i wish you know.......

my English is not good, this is my first time to do this , if i do something wrong , plz forgive me....

**Comment by JohnCaiJun** [comment]
Hi ,  maybe it's because thinstation are not support by centos, i'm using ubuntu try again.

**Comment by JohnCaiJun** [comment]
if so ,  that's great !  !  
i  am more proficient in using CentOS,  so many people use CentOS in china.
because Many educational institutions are teaching linux based CentOS in my country as i know . 
this is what i want to tell you.
if thinstation can support centos , all of them will happy .....
thks.

**Comment by Thinstation** [comment]
I have made the PATH explicit, and so it should now work on your favorite distribution, in your locale, without modification.
