### ISSUE TITLE
setup_chroot error on 32 bit dev station

### ISSUE THREAD

**Issue by falco76** [Thinstation/thinstation#314]
hi all
i need make a 32 bit pxe kernel (ts6.1 stable) with vmware pcoip

I install a 32 bit devstation and when i run ./setup_chroot 

chroot: failed to run command ‘/ts/TS_ENV’: Exec format error

can i use a 32 bit machine for dev station?

**Comment by Doncuppjr** [comment]
If you go back to 5.6-Stable, which should have a good vmview package.


Sent from Yahoo Mail for iPhone


On Tuesday, July 10, 2018, 10:36 AM, Salvatore Todaro <notifications@github.com> wrote:


hi all
i need make a 32 bit pxe kernel (ts6.1 stable) with vmware pcoip

I install a 32 bit devstation and when i run ./setup_chroot

chroot: failed to run command ‘/ts/TS_ENV’: Exec format error

can i use a 32 bit machine for dev station?

**Comment by falco76** [comment]
build 5.6

Dependencies are clean!
Adding and install non-distributable binaries
INFO: vmviewpcoip included
Adding Packages to Filetree

on boot 
ERROR: package vmviewpcoip doesn't exists aborting bootup ....

**Comment by falco76** [comment]
update ..

it's ok
thinstation can't add vmviewpcoip session if several session parameters aren't set

**Comment by Thinstation** [comment]
I have moved the vmviewpcoip package to vmview, and it should work with minimal change. vmview is a keyword within the package.
