### ISSUE TITLE
add Vivaldi web browser in thinstation

### ISSUE THREAD

**Issue by JohnCaiJun** [Thinstation/thinstation#316]
please i add download link in build.urls and add 'package vivaldi', compiling 'not found vivaldi', i run 'mkdir build/packages/vivaldi' , and 'cp -r build/packages/template/* build/packages/vivaldi' , and i don't know how to do edit install file . i read a lot of ports、package REAME, still don't know how to add new application in thinstation.  i'm a newbie.......

**Comment by Doncuppjr** [comment]
Get the port for the browser, put it into one of the ports directories, maybe components. Pet-get install vibaldi, if that works, mkrepackage vivaldi.


Sent from Yahoo Mail for iPhone


On Thursday, July 19, 2018, 1:26 AM, CAIJUN <notifications@github.com> wrote:


please i add download link in build.urls and add 'package vivaldi', compiling 'not found vivaldi', i run 'mkdir build/packages/vivaldi' , and 'cp -r build/packages/template/* build/packages/vivaldi' , and i don't know how to do edit install file . i read a lot of ports、package REAME, still don't know how to add new application in thinstation. i'm a newbie.......

**Comment by JohnCaiJun** [comment]
I try to do this:
   1. add source=vivaldi.tar.gz link in Pkgfile , and run "pkgmk -d" 
   2. prt-get install vivaldi 

I'm failure again, where  can i get the port ?  

There has another question, how can i add an application tarball in thinstation (the tartall had been compiled by myself like freerdp, which i modified some functions)

I am very sorry to bother you. 

thank you for your help.

**Comment by JohnCaiJun** [comment]
I'm reading CRUX handbook.....
