### ISSUE TITLE
6.1 stable -  splash screen not showing

### ISSUE THREAD

**Issue by rohrbachger** [Thinstation/thinstation#323]
I have a working 5.6 version and tried to move now to 6.1.
I'ḿ running viewpcoip with client version 4.6

I have enabled the splash screen like in the older version and also I tried
the original standard settings.
The splash screen does not come up. 
As there are several differences between 5.6 and 6.1 itś hard for me to
find the reason. Is it true that now thinstation uses a 64bit architecture as default?

Is this a general issue in 6.1 or has it to do with a configuration error?
Does it work on someone else hardware?

**Comment by Doncuppjr** [comment]
6.1 is 64 bit only, and systemd based. Where there was once a long serial init process that allowed for a splash screen, now there is a multiprocess init that goes so fast, that the splash was more of a flash. It was removed altogether, to improve UX and security 


Sent from Yahoo Mail for iPhone


On Sunday, August 12, 2018, 5:48 AM, rohrbachger <notifications@github.com> wrote:


I have a working 5.6 version and tried to move now to 6.1.
I'ḿ running viewpcoip with client version 4.6

I have enabled the splash screen like in the older version and also I tried
the original standard settings.
The splash screen does not come up.
As there are several differences between 5.6 and 6.1 itś hard for me to
find the reason. Is it true that now thinstation uses a 64bit architecture as default?

Is this a general issue in 6.1 or has it to do with a configuration error?
Does it work on someone else hardware?

**Comment by rohrbachger** [comment]
On two different machines it takes 10-14 seconds to get the desktop screen,
before I only have a black screen. One no name and one Desktop Optiplex 790.
Both booting from PXE and the time 10-14 is measured after the ISO was already downloaded to the PC. On the 5.6 version it takes the same time.
Time is okay, but it was nice to have a picture and see the process.
I know there are a lot of changes in 6.1 so probably the whole splash is to redesign.
As this is only cosmetic and not functional I can understand that this is less important.
Maybe others do have faster machines booting or itś a difference with PXE.
If I would know where to search I would spend the time to search for a way to get back the splash screen.

**Comment by Thinstation** [comment]
Plymouthd
