### ISSUE TITLE
error build ts 5.6

### ISSUE THREAD

**Issue by trentasis** [Thinstation/thinstation#328]
With ./build --allmodules using default config files fails to generate thinstation

Adding contributed files

Building PKG Packages

Building Module PKG Packages

Running File System Fixups
        Building Charmap Cache
        Removing Extra Files
        Running mkfontdir and mkfontscale
        Caching pixbuf loaders
        Caching gtk-2.0 immodules
        Compiling Schemas
        Linking BusyBox

        Running Finalize

update-mime-database: error while loading shared libraries: libpcre.so.0: cannot open shared object file: No such file or directory
update-desktop-database: error while loading shared libraries: libpcre.so.0: cannot open shared object file: No such file or directory
        Caching icons
        Rehashing Certificates

+ Adding splash boot logo

Issue with libpcre? Required a softlink?

**Comment by Thinstation** [comment]
Should be fixed
