### ISSUE TITLE
Raspberry

### ISSUE THREAD

**Issue by rodrigoreimberg** [Thinstation/thinstation#333]
Hello,

Is there any possible to config the great tool Devstation to work with raspberry?

Tks,

Rodrigo Reimberg

**Comment by Thinstation** [comment]
Sure, just recompile all the ports for arm, and it should work.

**Comment by rodrigoreimberg** [comment]
Hello, i`m using Thinstation with pxe boot from tftpd server, with any motherboard i can do network boot.

My hardware is Raspberry  PI 3 B+, and network boot just work if exist bootcode.bin in tftpd root folder.

Please, help me to recompile.

Tks,

**Comment by Thinstation** [comment]
https://crux-arm.nu/Documentation/BuildingPackages

**Comment by rodrigoreimberg** [comment]
I did thes steps conform whith document, but i don't know the next step.

Please, help me.

**Comment by Thinstation** [comment]
Diligence, patience, research and grit.
