### ISSUE TITLE
Unable to connect to WiFi - "(2) Active connection removed before it was initialized"

### ISSUE THREAD

**Issue by LegsAJimbo** [Thinstation/thinstation#334]
I seem to be unable to connect to wireless laptops when booting on both an Advent (shivers) Monza Red and a Lenovo Thinkpad Yoga.

I have enabled wpa-supplicant and wireless packages and I am building with --allmodules. This happens with both the internal WiFi cards and USB adapters.

As soon as I click on the wireless network (using the network manager tray icon) I wish to connect to I receive the error "Failed to add/activate connection, (2) Active connection removed before it was initialized".

I have attached my build.conf as well as output from dmesg and journalctl in case these contain anything useful.

[dmesg.txt](https://github.com/Thinstation/thinstation/files/2371585/dmesg.txt)
[journalctl.txt](https://github.com/Thinstation/thinstation/files/2371586/journalctl.txt)
[build.conf.txt](https://github.com/Thinstation/thinstation/files/2371599/build.conf.txt)

Any assistance would be greatly appreciated!

**Comment by Doncuppjr** [comment]
Which wireless chipset?


Sent from Yahoo Mail for iPhone


On Tuesday, September 11, 2018, 8:26 AM, LegsAJimbo <notifications@github.com> wrote:


I seem to be unable to connect to wireless laptops when booting on both an Advent (shivers) Monza Red and a Lenovo Thinkpad Yoga.

I have enabled wpa-supplicant and wireless packages and I am building with --allmodules. This happens with both the internal WiFi cards and USB adapters.

As soon as I click on the wireless network I wish to connect to I receive the error "Failed to add/activate connection, (2) Active connection removed before it was initialized".

I have attached my build.conf as well as output from dmesg and journalctl in case these contain anything useful.

dmesg.txt
journalctl.txt
build.conf.txt

Any assistance would be greatly appreciated!

**Comment by LegsAJimbo** [comment]
Hi Donald,

Thanks for responding so quickly!

The USB adaptor is a Realtek RT5370, and the internal adaptors are the RTL8188CE and the Intel 7260.

**Comment by Thinstation** [comment]
go back to 5.6

**Comment by Thinstation** [comment]
Fixed.
