### ISSUE TITLE
Two monitors on HPT630

### ISSUE THREAD

**Issue by MatheusFrizzo** [Thinstation/thinstation#335]
Hi,

This is my first post.
I am starting to configure the thinstation and I would like to know if for to use two monitors is it necessary to use two types output, eg HDMI and VGA?

I have an HPT630 thin client, but I can not work with two monitors.

Regards,
Matheus

**Comment by Doncuppjr** [comment]
No, the outputs can be the same type.
    On Tuesday, September 11, 2018, 11:13:34 AM PDT, MatheusFrizzo <notifications@github.com> wrote:  
 
 
Hi,

This is my first post.
I am starting to configure the thinstation and I would like to know if for to use two monitors is it necessary to use two types output, eg HDMI and VGA?

I have an HPT630 thin client, but I can not work with two monitors.

Regards,
Matheus
