### ISSUE TITLE
thinstation 6.1 loading error

### ISSUE THREAD

**Issue by mihalich1988** [Thinstation/thinstation#337]
I buy a two Lenovo AIO C260, and thinstation doesn't loading on it.
I have two Lenovo AIO C200 - thinstation work fine, and many other PC - too!

thinstation build with parameter --allmodules

In build.conf enabled all items for debug:
```
package debug
package extensions
package extensions-x
param fastboot false
param splash verbose
param bootverbosity 63
param haltonerror false
```

While loading I see only this and nothing more (After loading initrd, monitor flashes once):
![img_4299](https://user-images.githubusercontent.com/1499133/45426805-e86b3800-b6a5-11e8-8693-e0b91b6d8e00.JPG)

How can I see errors?

**Comment by Thinstation** [comment]
I dunno, out of memory? Send me a unit, I'll take a look.

**Comment by mihalich1988** [comment]
LENOVO C260

Intel® Celeron® J1800
Memory - 4Gb
Video - Intel®

>  Send me a unit, I'll take a look.

What is this "unit"? ))

I was able to boot it!!!
But there is a big oddity - if in usb 3.0 port insert USB Zalman Virtual SD - then Thinstation is loaded correctly!

How do I enable boot logs? And see what happens?

**Comment by Thinstation** [comment]
Unit="The computer you are having trouble with" a Lenovo C260

reduce verbosity to 4, and param splash off

**Comment by mihalich1988** [comment]
I'll run build with:
```
param splash off
param bootverbosity 4
```

I'll let you know what happens in the end.

**Comment by mihalich1988** [comment]
APPEND initrd=http://192.168.22.200/boot/initrd  splash=off load_ramdisk=1 ramdisk_blocksize=4096 root=/dev/ram0 ramdisk_size=786432 console=tty1 vt.global_cursor_default=0 quiet loglevel=3  LM=3

I remove from this string `quiet` and change `console=tty1` to `console=tty0`
But no boot logs...

**Comment by Thinstation** [comment]
You shouldn't have to change anything on the kernel cmd line. Just build.conf. Verbose startup in 6.1 is not there yet. Systemd is getting in the way, but I will work it out eventually. Use 5.6 for now, if you need EFI, build with --kernel 64

**Comment by mihalich1988** [comment]
> You shouldn't have to change anything on the kernel cmd line. Just build.conf. 

If I don't change this, I see only `Thinstation Linux` and nothing more.

> Use 5.6 for now, if you need EFI, build with --kernel 64

OK, I'll try using 5.6

Thank you!

**Comment by mihalich1988** [comment]
Error:

![img_4312](https://user-images.githubusercontent.com/1499133/45488919-955bb880-b76b-11e8-87ff-42544183e5ac.jpg)

**Comment by Thinstation** [comment]
What’s the error! I see some noise, but nothing fatal.
