### ISSUE TITLE
Fresh 5.5 Appliance Install + Update To 6.1-Stable = "failed to run command '/ts/TS_ENV': Exec format error

### ISSUE THREAD

**Issue by vampire337** [Thinstation/thinstation#338]

**Comment by Thinstation** [comment]
Yeah, that's not gonna work. 32 vs 64 bit.

**Comment by vampire337** [comment]
Oh, that makes sense then.  Well, thanks for the info.  Any word on when an ISO of the 64bit will be available?

**Comment by Thinstation** [comment]
Ah man, just go back to 5.6 and use the 64bit kernel for the time being.
6.1 is more unstable than stable.

**Comment by vampire337** [comment]
Fair enough.  FYI, where the thinstation.org main page says "The latest stable release is version 6.1.0 Please be aware that not all docs have been updated yet but all basic concepts apply.", that 6.1.0 links directly to 5.5.  I just clicked and missed that 5.6 even exists.  Since I'm just testing this out, I'll stick to 5.6.

Thanks for the quick response!
