### ISSUE TITLE
Systemd unit errors

### ISSUE THREAD

**Issue by andycher11** [Thinstation/thinstation#339]
Hi, in  6.1 stable options,  described in the freerdp.init and which are located in network files  do not work fo me. 
i found that: 
1.	In freerdp.init.service
 After=profile_setup.service net.profle_setup.service
But services are called profile-setup.service and net.profile-setup.service

2.	In session.service and Network_files.service
After=profile_setup.service

**Comment by andycher11** [comment]
for example in 
https://github.com/Thinstation/thinstation/blob/6.1-Stable/ts/build/packages/freerdp/build/extra/lib/systemd/system/freerdp.init.service

**Comment by andycher11** [comment]
I installed the thihstation from   git clone --depth 1 git://github.com/Thinstation/thinstation.git -b 6.1-Stable 6 days ago, so bug still  present

**Comment by Thinstation** [comment]
Maybe fixed now.

**Comment by Thinstation** [comment]
Fixed?

**Comment by andycher11** [comment]
i think fixed,I tried it, it worked,but I didn't check everything, I do not have much time, I need a few days to answer.
