### ISSUE TITLE
6.1 stable vmware view - Reconnect - autoconnect

### ISSUE THREAD

**Issue by rohrbachger** [Thinstation/thinstation#340]
I have some minor issues with the actual version.
view 4.9 client works fine in general.

But I can't get the desktop icons running.
If I start vmview from the menu it works fine.
The desktop icons I have, but view client does not start.
It has to do with the parameters pkg fullscreen vmview "VDI" ""
If I delete the last two parameters view starts up.
If I once have started the view I can add back the parameters and it will start from the desktop icons.
I was not able to figure out what the first manual call changed.

The shortcut VDI parameter comes from SESSION_1_TITLE
But also when I changed this to MyViewServer.de it does not connect.
Starting from Terminal works with:
pkg fullscreen view MyViewServer.de
But not: pkg fullscreen view "VDI" ""

This are my settings.
VMVIEW_AUTOCONNECT=TRUE
VMVIEW_SSLVERIFYMODE=1
VMVIEW_DEFAULTBROKER=MyViewServer.de

SESSION_1_VMVIEW_AUTOCONNECT=TRUE
SESSION_1_ICON=ON
SESSION_1_TITLE="VDI"
SESSION_1_TYPE=vmview
SESSION_1_AUTOSTART=ON
SESSION_1_VMVIEW_SERVERURL=MyViewServer.de
SESSION_1_VMVIEW_FULLSCREEN=True
SESSION_1_VMVIEW_DEFAULTDESKTOPSIZE=1

I'm also not able to get the autoconnect  for view working, probably related to the first issue.
I want after start direct the logon windows for view.

--------------------------------------------------------------------------------
Since the 6.1 version I have a Reconnect Box on the screen.
If I switch this off in the thinstation.conf.build, the client will not start.
So there is somehow a difference to the 5.6 version.
Iḿ using ts_classic. Iḿ not using networkmanager.

**If I could get some hints, that would be great.**

**Comment by rohrbage** [comment]
I found the detail whats wrong, but I´, m not able to fix it now.
The .desktop file is created with:
Exec= pkg fullscreen vmview "VDI" "" but should be Exec = pkg fullscreen vmview "VDI.vdm" ""
That the same for VDI.desktop file in ./local/share/application
Probably this is stopping also the autostart from view.
I´ll find a dirty fix for this, but I´m not sure about the order when it is created.

Still I have no idead about the Connect Box, how to disable this.

**Comment by rohrbachger** [comment]
I found a solution for autostart and desktop icons ( using xfmw4)
package/base/etc/init.d/session-setup
           if [ -n "$WMNAME" ] && [ "$type" != "$WMNAME" ]; then

                        **if [ "$type" = "vmview" ]; then
                                echo "pkg auto $type \"$server.vdm\" \"$options\" \"$WMWORKSPACE\" &" >> $WKDIR/$WMNAME.autostart
                        else
                                echo "pkg auto $type \"$server\" \"$options\" \"$WMWORKSPACE\" &" >> $WKDIR/$WMNAME.autostart**
                        fi

                        echo "sleep .2" >> $WKDIR/$WMNAME.autostart

                elif [ -n "$WMNAME" ] && [ "$type" == "$WMNAME" ]; then

/packages/xfwm4/etc/xfwm4.functions
       echo "[Desktop Entry]"                  >"$LINK"
        echo "Version=1.0"                      >>"$LINK"
        echo "Name=$title"                      >>"$LINK"
        echo "Comment=$title"                   >>"$LINK"
**# Change GR.
        OLDIFS=$IFS
        IFS=' '
        set $command

        if [ $3 = "vmview" ]; then
                echo "TryExec=$1 $2 $3 $title.vdm $5"   >>"$LINK"
                echo "Exec=$1 $2 $3 $title.vmd $5"      >>"$LINK"

        else
                echo "TryExec=$command"                 >>"$LINK"
                echo "Exec=$command"                    >>"$LINK"
        fi

        IFS=$OLDIFS


Still I have the connect Box on the screen. I do not need it, but its in the background now.

**Comment by ts-michaelk** [comment]
The session configuration includes invalid options.  If any are wrong, the executable ignores all of them.  The fixes described above are incorrect.  All they do is force run_vmview to try to read the non-existent file $title.vdm.vdm.  It works because it bypasses the broken arguments by not including any of them.  Essentially in this case, only the default broker option (VMVIEW_DEFAULTBROKER) is used.

The two incorrect ones are:
SESSION_1_VMVIEW_AUTOCONNECT=TRUE
SESSION_1_VMVIEW_DEFAULTDESKTOPSIZE=1

There is no command line argument for autoconnect that I am aware of.  The use of the global VMVIEW_AUTOCONNECT is correct however and should do the trick.

The other would probably be SESSION_1_VMVIEW_DESKTOPSIZE=large|small|full|all|WxH or maybe trying to invoke the "monitors" command instead.
