### ISSUE TITLE
6.1 stable language support

### ISSUE THREAD

**Issue by boailql** [Thinstation/thinstation#341]
Does ThinStation support Chinese?How to install other language packages.

**Comment by Thinstation** [comment]
You would need to make a locale package

**Comment by boailql** [comment]
I'm a green hand,could you describe in more detail?

**Comment by boailql** [comment]
> You would need to make a locale package
> […](#)
> Sent from my iPhone
> On Oct 24, 2018, at 6:40 PM, boailql ***@***.***> wrote: Does ThinStation support Chinese?How to install other language packages. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

I'm a green hand,could you describe in more detail?

**Comment by Planevector** [comment]
Can you be more detailed, thank you

**Comment by Thinstation** [comment]
I could give a seminar on the construction of a language package, but I’d
want money for that ;)
