### ISSUE TITLE
devstation tftpboot folder not linked to boot-images/pxe

### ISSUE THREAD

**Issue by sky-flix** [Thinstation/thinstation#342]
It appears that the latest devstation image does not have /var/lib/tftpboot linked to /thinstation/build/boot-images/pxe. In fact, when I manually destroy the existing hard folder and create the link, the tftp server works as it should, however the link is destroyed and the original folder restored upon reboot.

**Comment by sky-flix** [comment]
My apologies. 6.1

**Comment by Thinstation** [comment]
Fixed
