### ISSUE TITLE
6.1 stable,  "Ctrl + Alt + F2"  Black Screen

### ISSUE THREAD

**Issue by boailql** [Thinstation/thinstation#343]
On 6.1 stable，desktop and connection app is available,but press "Ctrl + Alt + F2" to console is black screen.
no such problem occurred in the 5.6 stable.

**Comment by Thinstation** [comment]
What is the expected behavior?

**Comment by boailql** [comment]
enter the console

**Comment by Doncuppjr** [comment]
I love it here.


Sent from Yahoo Mail for iPhone


On Thursday, December 6, 2018, 7:16 PM, boailql <notifications@github.com> wrote:


enter the console

**Comment by Thinstation** [comment]
This appears to be fixed.
