### ISSUE TITLE
Problem with sound on 6.1.1

### ISSUE THREAD

**Issue by maa7** [Thinstation/thinstation#345]
Hello,
I try thinstation-6.1.1.tar.gz for create bootable usb flash drive for Intel NUC.
All works fine, but some issues:
1) sound don't work.
2) the network is initializing too slowly, the Horizon Client has time to start earlier.

**Comment by AmazingBeu** [comment]
I found a workaround for the sound, you have to comment on these lines in the **/ts/build/build** file :
```
       if [ ! -e ./tmp-tree/lib/thinstation/system/audio ]; then
               for sound in `find ./tmp-tree/lib/modules -type d -name sound`; do
                       rm -rf $sound
               done
       fi 
```
and build with the correct sound modules

**Comment by Doncuppjr** [comment]
This fix has been pushed, and should already be available in new checkouts.


Sent from Yahoo Mail for iPhone


On Tuesday, November 27, 2018, 6:31 AM, AmazingBeu <notifications@github.com> wrote:


I found a workaround for the sound, you have to comment on these lines in the /ts/build/build file :
       if [ ! -e ./tmp-tree/lib/thinstation/system/audio ]; then
               for sound in `find ./tmp-tree/lib/modules -type d -name sound`; do
                       rm -rf $sound
               done
       fi 

and build with the correct sound modules
