### ISSUE TITLE
Adding a certificat problem

### ISSUE THREAD

**Issue by 30rush** [Thinstation/thinstation#350]
Hey man!

So your solution is being used by the company I work for and It's properly working till now. Everything works fine.

Now we have a last problem to solve and I am not so sure how.

I have a certificate I'd like to add to the ca-bundle. 
I use vmview (VMware horizon client) and if I ignore the cert everything works well but whenever I click never enter an untrusted source it denies me the entry.

So I have took the ca cert that we have here and I've copied the content in the end of ca-bundle in /package/ca-bundle/etc/ssl/certs and it also have the beginning of cert and end of cert attached to it.

Then I build my image again and it still tells me that It doesn't trust it.

It's my last step to the completion of the project so if you can please just explain to me how to do it I'd really appreciate that.

Thank you very much.

**Comment by Thinstation** [comment]
Which branch?
Is the certificate still in the bundle after the image is booted?

**Comment by 30rush** [comment]
Hey man,

Thanks again for the fast reply. 

So look, I've solved that problem already in the week-end I have 2 last little issues to ask you if you can help me I would be really grateful.

So the first one is how can I add a host file for the dns in the image?

And second I'd like to plug a usb on the computer and be able to transfer data from my computer over VMware horizon so I added 2 lignes on thinstation.build.conf, and they are : 

USB_ENABLED=on
SESSION_1_VMVIEW_REDIRECT1="disk:usb=/mnt/usbdevice/sda1"

I would like to know with you if that would be enough or if they are correct lignes to add for my transfer to work.

Thank you very much man you are a great help!

**Comment by Doncuppjr** [comment]
That looks right.
    On Monday, December 17, 2018, 8:06:58 AM PST, 30rush <notifications@github.com> wrote:  
 
 
Hey man,

Thanks again for the fast reply.

So look, I've solved that problem already in the week-end I have 2 last little issues to ask you if you can help me I would be really grateful.

So the first one is how can I add a host file for the dns in the image?

And second I'd like to plug a usb on the computer and be able to transfer data from my computer over VMware horizon so I added 2 lignes on thinstation.build.conf, and they are :

USB_ENABLED=on
SESSION_1_VMVIEW_REDIRECT1="disk:usb=/mnt/usbdevice/sda1"

I would like to know with you if that would be enough or if they are correct lignes to add for my transfer to work.

Thank you very much man and like always you are a great help!

**Comment by 30rush** [comment]
alright thanks man I appreciate that we can close this !
