### ISSUE TITLE
/roor directory is missing

### ISSUE THREAD

**Issue by svalx** [Thinstation/thinstation#352]
No root home directory "/root" on target systems with 6.1, but in /etc/passwd I see a line `root:x:0:0:root:/root:/bin/sh`. It is cause of:
```
$ su
Password:
sh: cd: line 77: can't cd to /root: No such file or directory
```
Perhaps for this reason sudo does not work all - permanent "Sorry, try again."

**Comment by Doncuppjr** [comment]
You might be receiving extraneous messages, but su and sudo both work.


Sent from Yahoo Mail for iPhone


On Tuesday, December 25, 2018, 10:06 PM, Alexey Svistunov <notifications@github.com> wrote:


No root home directory "/root" on target systems with 6.1, but in /etc/passwd I see a line root:x:0:0:root:/root:/bin/sh. It is cause of:
$ su
Password:
sh: cd: line 77: can't cd to /root: No such file or directory

Perhaps for this reason sudo does not work all - permanent "Sorry, try again."

**Comment by svalx** [comment]
su really works though swears, and sudo problem is not related to the /root directory. I mostly used openSUSE, there a different logic of sudo, and I tried to enter the root password. If use tsuser password, I get `tsuser is not in sudoers file. This incident will be reported.` 
How I can get `/root` directory in current filesystem by default?

**Comment by Doncuppjr** [comment]
Comment out tsuser in build.conf, and the image will default to a root login.


Sent from Yahoo Mail for iPhone


On Wednesday, December 26, 2018, 11:35 PM, Alexey Svistunov <notifications@github.com> wrote:


su really works though swears, and sudo problem is not related to the /root directory. I mostly used openSUSE, there a different logic of sudo, and I tried to enter the root password. If use tsuser password, I get tsuser is not in sudoers file. This incident will be reported.
How I can get /root directory in current filesystem by default?

**Comment by svalx** [comment]
But I do not want lose tsuser. I only need /root directory. Is there any parameter or package for this effect?

**Comment by Doncuppjr** [comment]
You could make one.....mkdir -p /build/packages/home/root
Then addpackage hometo build.conf

Sent from Yahoo Mail for iPhone


On Friday, December 28, 2018, 2:49 AM, Alexey Svistunov <notifications@github.com> wrote:


But I do not want lose tsuser. I only need /root directory. Is there any parameter or package for this effect?

**Comment by svalx** [comment]
I found a solution. It needed uncomment a line `#mkdir -m 700 /root` in the file packages/switchuser/build/finalize. This package contain `su` binary, and I think it's right to create needed directory when using it.
What a reason to commented it?
