### ISSUE TITLE
continued 32 bit support

### ISSUE THREAD

**Issue by SZenglein** [Thinstation/thinstation#353]
According to the mailing lists, Thinstation 6.1 will only support 64bit processors. Also, 5.6 will supposedly not get many more updates. I only found this out after spending a lot of time configuring the new version, a single-line note added to the documentation would be nice.

Is this information is correct? I think many thin clients are still using 32 bit hardware, which is also usually powerful enough for the purpose of thin clients. Would it be possible to still support a 32 bit version, even if some packages could not run on it?

If 5.6 will get continued (security) updates it might be fine, but I think 32 bit devices will still be around in quite some time.

Please consider continued support for 32 bit architectures. If not, please add a small notice to the documentation.

**Comment by Doncuppjr** [comment]
I hear what your saying, but I don’t have the resources to maintain two branches. The hard pivot to 64bit is a forced move, but a safe one.

The last 32bit intel and amd processors were discontinued in 2002,  via stopped in 2008. This should give us 11 years of total coverage and 16 years of mainstream support, which is roughly 2-3 times the expected service life of commodity hardware. 

Even the kernel developers are considering dropping 32bit code paths.

**Comment by SZenglein** [comment]
Thanks for clarifying. I understand that you only have limited time. A update for the minimal requirements would still be nice.
