### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [Thinstation/thinstation#355]
Dear @Thinstation team,

It is possible to migrate the personal account to organization?

Converting:
- https://help.github.com/articles/converting-a-user-into-an-organization/

It is possible to rename this account and create the organization and move/transfer the repository to the organization.

Rename account:
- https://docs.github.com/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/changing-your-github-username

Create an organization:
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository

Like:
- https://github.com/IBM
- http://github.com/gnome
- http://github.com/kde
- ...

**Comment by Neustradamus** [comment]
Why have you closed this ticket?

It is for be more pro ^^
And better to use it.

The personal account to thinstation-account, the creation of thinstation organization, the transfer of the project (not a fork), easy to manage it...

**Comment by Thinstation** [comment]
This is not relevant.

**Comment by Neustradamus** [comment]
Why?
You do not want more visibility and devs etc?

**Comment by Thinstation** [comment]
This is a free opensource project. It does not generate any funds to pay
organization fees.

**Comment by Neustradamus** [comment]
There are not organization fees...
https://help.github.com/articles/differences-between-user-and-organization-accounts/

@Thinstation Can you reopen?

**Comment by Neustradamus** [comment]
@Thinstation: Any news for this change?
Easy to do it :)
For example: Exiftool has done it few days ago: https://github.com/exiftool

**Comment by Doncuppjr** [comment]
How does this help?

**Comment by Neustradamus** [comment]
It is to show that it is easy to do!

**Comment by Thinstation** [comment]
So is cutting off a finger, not really interested in doing that either.

**Comment by Neustradamus** [comment]
@Doncuppjr, @Thinstation: There is no lost, no links lost...

You can see for examples:
- http://github.com/gnome
- http://github.com/kde

**Comment by Thinstation** [comment]
I already have that.

**Comment by Neustradamus** [comment]
No, you are a personal account not an organization ^^
https://help.github.com/articles/converting-a-user-into-an-organization/

**Comment by Doncuppjr** [comment]
This is o.k.

**Comment by Neustradamus** [comment]
Nice @Doncuppjr, when have you planned to do it for the @Thinstation account?

**Comment by Thinstation** [comment]
I won’t be going forward with this. It has no apparent value.

**Comment by Neustradamus** [comment]
@Thinstation: I think that the best solution is (in few minutes):
- Change your username to thinstationaccount (or other): https://github.com/settings/admin
- Create thinstation (without uppercase) organization: https://github.com/organizations/new

And:
- Transfer thinstation into thinstation org: https://github.com/NEWACCOUNTUSERNAME/thinstation/settings

No lost, you can see, for examples:
- https://github.com/nerzhul/ocsms
- https://github.com/tigaseinc/tigase-server

Some links:
- https://help.github.com/en/github/getting-started-with-github/types-of-github-accounts
- https://github.community/t/best-practices-for-organizations/10205
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams

**Comment by Thinstation** [comment]
?

**Comment by Neustradamus** [comment]
To have a perfect thinstation organization, all are specified :)

**Comment by Thinstation** [comment]
There is only me.

**Comment by Neustradamus** [comment]
It is not a problem ^^
It will be really better.

All from https://github.com/Doncuppjr/thinstation are already in upstream?
Please remove your fork after confirmation.

- Change your Thinstation username to thinstationaccount (or other): https://github.com/settings/admin
- Few second after, create thinstation (without uppercase) organization (with the current account or your real personal Doncuppjr account): https://github.com/organizations/new
- Add owner rights to the second account (your real or the old-bad account of the project): https://github.com/orgs/thinstation/people ("Invite a member", add the account, select Owner and validate that it is you)
- Transfer thinstation into your real personal Doncuppjr account: https://github.com/NEWACCOUNTUSERNAME/thinstation/settings
- Transfer shim-review into your real personal Doncuppjr account: https://github.com/NEWACCOUNTUSERNAME/shim-review/settings
- Transfer thinstation from your real personal account into new thinstation organization
- Transfer shim-review from your real personal account into new thinstation organization

All redirections will be here :)

Now, you can directly publish new code with your real personal account.

And the old "Thinstation" account is not needed now.

**Comment by Doncuppjr** [comment]
This project has been defunded and will cease development in July.

**Comment by Neustradamus** [comment]
A better reason to do it and found new people ;)

**Comment by Thinstation** [comment]
You seem to really want this, but you haven't made a case as why I should.

**Comment by Neustradamus** [comment]
I think you have not looked all...
- https://help.github.com/en/github/getting-started-with-github/types-of-github-accounts
- https://github.community/t/best-practices-for-organizations/10205
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams

**Comment by Thinstation** [comment]
I am not an organization
I do not have a team

**Comment by Neustradamus** [comment]
Do you listen advice from people?
Do you want the end of Thinstation?

If you can not do it, I can do it quickly, I have already done several times without any problems.

**Comment by Thinstation** [comment]
Doesn't matter what I want. ThinStation is no longer funded.

**Comment by Neustradamus** [comment]
@Thinstation, @Doncuppjr: It is for this, plan the future, search new sponsors etc.

I can help you to do it in GitHub with all steps that I have specified you.

**Comment by Thinstation** [comment]
Why do you want this? I don’t see how a third account makes my life easier.

**Comment by Neustradamus** [comment]
@Thinstation, @Doncuppjr: You mix, organization is not a third account.
The organization with you like owner, and when you commit, you commit with your personal account.
The current "Thinstation" account can be removed or not used after.

You can see for example:
- Tigase organization: https://github.com/tigase
- The old account of Tigase: https://github.com/tigaseinc

**Comment by Doncuppjr** [comment]
No sale.

**Comment by Neustradamus** [comment]
No sale?

**Comment by Thinstation** [comment]
There is no apparent value in making this change. Just a lot of busy work and broken documentation.

**Comment by Neustradamus** [comment]
It takes 5mn less to do it...

**Comment by Thinstation** [comment]
That's an over simplification. Why do you want this?

**Comment by Neustradamus** [comment]
Only to show you the simplicity and the best solution to manage this project.

**Comment by Thinstation** [comment]
Thank you for the info.

**Comment by Neustradamus** [comment]
Dear @Thinstation,

It is possible to look my request?

Thanks in advance.

**Comment by Doncuppjr** [comment]
I looked at it. I don't think it's the right fit for the project.
    On Friday, July 28, 2023 at 02:51:59 PM MDT, Neustradamus ***@***.***> wrote:  
 
 


Dear @Thinstation,

It is possible to look my request?

Thanks in advance.

**Comment by Neustradamus** [comment]
A project is not a physical person.
You have your personal account and it is easy to convert the project into an organization, to be legally good.

**Comment by Thinstation** [comment]
?? Legally good for what purpose? It’s free software. What on earth could
this conversion do for me, that’s not also more work?

**Comment by Neustradamus** [comment]
A physical person can have a personal account, a project is an organization, free software yes :)

It is easy to do, please read the original issue to do it.

Examples:
- https://github.com/asciimoo/searx -> https://github.com/searx/searx
- https://github.com/boothj5/profanity -> https://github.com/profanity-im/profanity
- https://github.com/nerzhul/ocsms -> https://github.com/nextcloud/ocsms
- https://github.com/tigaseinc/tigase-server -> https://github.com/tigase/tigase-server

- https://github.com/virtualmin has been converted
- https://github.com/ekg2 has been converted
- https://github.com/bcgit has been converted
- https://github.com/libreswan has been converted
- https://github.com/xelerance has been converted
- https://github.com/libreswan has been converted
- https://github.com/exiftool has been converted
- https://github.com/starpu-runtime has been converted
- https://github.com/ZOSOpenTools has been converted
- https://github.com/hmailserver has been converted

**Comment by Neustradamus** [comment]
Dear @Doncuppjr,

Good news, the Thinstation project is alive!

Can you convert the @Thinstation personal account to organization?

Thanks in adance.

**Comment by Neustradamus** [comment]
Dear @Doncuppjr,

Good news, the Thinstation project is alive!
- https://sourceforge.net/p/thinstation/mailman/message/58838023/
- https://github.com/Thinstation/thinstation
- https://sourceforge.net/p/thinstation/activity/

Can you convert the @Thinstation personal account to organization?

Thanks in adance.

**Comment by Neustradamus** [comment]
Dear @Doncuppjr,

Congratulations, thanks a lot for the converting of the @Thinstation account!
The future starts now!
