### ISSUE TITLE
HP T530 fail on 6.1 (4.14.94) - no screen

### ISSUE THREAD

**Issue by netromnetrom** [Thinstation/thinstation#356]
The amdgpu driver seems unable to run the graphics correct. It will not operate with the modelines. 
When I remove and reconnect the display cable, the screen starts but only at 25 Hz!

When I boot with from a USB  (Kubuntu 18.10 kernel 4.18) it runs perfect out of the box.

Will there be a never kernel available soon?

**Comment by Doncuppjr** [comment]
You can rev the kernel fairly easily yourself, change value in /ts/ports/kernel-modules/VERSION, then execute rebuild-kernels


Sent from Yahoo Mail for iPhone


On Tuesday, January 22, 2019, 8:50 AM, netromnetrom <notifications@github.com> wrote:


The amdgpu driver seems unable to run the graphics correct. It will not operate with the modelines.
When I remove and reconnect the display cable, the screen starts but only at 25 Hz!

When I boot with from a USB (Kubuntu 18.10 kernel 4.18) it runs perfect out of the box.

Will there be a never kernel available soon?

**Comment by Thinstation** [comment]
4.19.17 - Done.
