### ISSUE TITLE
6.1 Stable install root certificate for vmview client

### ISSUE THREAD

**Issue by mcsn747** [Thinstation/thinstation#358]
Hi Donald!

In 5.5 we add cert in pem format in folder /ca-bundle/etc/ssl/certs and make setup-chroot. 

In 6.1 this method does not work. We have ca-bundle.crt and root certificate in folder  /ca-bundle/etc/ssl/cert, but vmview client still don't trust  our certificates.
-rw-r--r-- 1 root root 1330 фев  1 13:03 ca-bundle.crt
-rw-r--r-- 1 root root 1330 фев  1 13:03 root-dc03.pem

How to install root certificate for vmview client?

Thanks!

**Comment by Thinstation** [comment]
You should now be able to create a package with a /certs/ca subfolder. In the subfolder, place certificates in PEM format with the .crt extension. Include the package in your build along with the ca-bundle package. (New Feature)

**Comment by mcsn747** [comment]
I create folder /build/packages/**mycerts**/certs/ca and place my root certificate inside this folder. Later i add string "package **mycerts**" in build.conf,  ca-bundle already exists. After build i don't see my certificate in image.

In https://github.com/Thinstation/thinstation/issues/250 you wrote that added some folders at /build/certs. 

Now i don't understand where i should put certs!

**Comment by Doncuppjr** [comment]
Yeah, there was a discussion after that post was made, and the certs were moved out of /build, and into /build/<a package>/certs/ca. You might need to pull the latest code for this to work.
    On Sunday, February 10, 2019, 9:52:48 PM PST, mcsn747 <notifications@github.com> wrote:  
 
 
I create folder /build/packages/mycerts/certs/ca and place my root certificate inside this folder. Later i add string "package mycerts" in build.conf, ca-bundle already exists. After build i don't see my certificate in image.

In #250 you wrote that added some folders at /build/certs.

Now i don't understand where i should put certs!

**Comment by mcsn747** [comment]
So i need more detailed explanation. I described my action above, and i have no success. I clone repo a couple days ago and i sure that i have a latest code . Please help!

**Comment by Thinstation** [comment]
I just made changes over the weekend, so do a git pull

**Comment by Doncuppjr** [comment]
O.k. That new code is a little inflexible. It should work if you only add one cert, and it ends in .crt. I buffed it out a little, so it's more flexible and tolerant.
    On Monday, February 11, 2019, 10:34:25 PM PST, mcsn747 <notifications@github.com> wrote:  
 
 
So i need more detailed explanation. I described my action above, and i have no success. I clone repo a couple days ago and i sure that i have a latest code . Please help!

**Comment by mcsn747** [comment]
Now I find in log these strings:

```
        Running Finalize

/build.finalize: line 1: openssl: not found
/build.finalize: line 1: openssl: not found
```

I fix the issue by manually append my cert in /ca-bundle/etc/ssl/cert.pem

**Comment by Thinstation** [comment]
Nuke and unwind again, or ‘update ca-bundle’ should fix that.
