### ISSUE TITLE
some cdrom not recognized

### ISSUE THREAD

**Issue by trentasis** [Thinstation/thinstation#359]
Hi,

We have detected that some cdrom are not recnized i  thinstation and any data is showed from this cd, same cd tested with windows are showed correctly

Any suggestio abput where is the issue?

Thanks

**Comment by Thinstation** [comment]
Did you do an all modules build?

**Comment by trentasis** [comment]
Correct

**Comment by trentasis** [comment]
right, ans some cd disks are detected and other not...
Thanks

**Comment by jackburton79** [comment]
I have the same problem (Thinstation 5.6), and I noticed that DVD work, but
CD-Rom do not. The log shows i/o errors.

Il giorno sab 2 feb 2019, 09:59 trentasis <notifications@github.com> ha
scritto:

**Comment by trentasis** [comment]
Can you post error and where are showed?

Thanks

**Comment by Thinstation** [comment]
Interesting.....when was the last cd-rom drive manufactured? Model Numbers?

**Comment by trentasis** [comment]
Attached screenshot of recorder and logs with an exmaple of cd recognized and other not
Example Detected
Jan  8 01:47:44 (none) user.warn kernel: VFS: busy inodes on changed media or resized disk sr0
Jan  8 01:47:44 (none) user.info kernel: sr 0:0:0:0: [sr0] tag#0 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Jan  8 01:47:44 (none) user.info kernel: sr 0:0:0:0: [sr0] tag#0 Sense Key : Not Ready [current]
Jan  8 01:47:44 (none) user.info kernel: sr 0:0:0:0: [sr0] tag#0 Add. Sense: Medium not present - tray open
Jan  8 01:47:44 (none) user.info kernel: sr 0:0:0:0: [sr0] tag#0 CDB: Read(10) 28 00 00 00 00 2b 00 00 01 00
Jan  8 01:47:44 (none) user.err kernel: blk_update_request: I/O error, dev sr0, sector 172
Jan  8 01:48:00 (none) cron.info crond[3627]: USER root pid 6933 cmd /bin/check_x11vnc
Jan  8 01:48:08 (none) user.info kernel: sr 0:0:0:0: [sr0] tag#0 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Jan  8 01:48:08 (none) user.info kernel: sr 0:0:0:0: [sr0] tag#0 Sense Key : Medium Error [current]
Jan  8 01:48:08 (none) user.info kernel: sr 0:0:0:0: [sr0] tag#0 Add. Sense: No seek complete
Jan  8 01:48:08 (none) user.info kernel: sr 0:0:0:0: [sr0] tag#0 CDB: Read(10) 28 00 00 00 00 00 00 00 02 00
Jan  8 01:48:08 (none) user.err kernel: blk_update_request: I/O error, dev sr0, sector 0
Jan  8 01:48:09 (none) user.debug kernel: ISO 9660 Extensions: Microsoft Joliet Level 1
Jan  8 01:48:09 (none) user.debug kernel: ISOFS: changing to secondary root


Example not detected
Jan  8 01:48:57 (none) user.info kernel: sr 0:0:0:0: [sr0] tag#0 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Jan  8 01:48:57 (none) user.info kernel: sr 0:0:0:0: [sr0] tag#0 Sense Key : Medium Error [current]
Jan  8 01:48:57 (none) user.info kernel: sr 0:0:0:0: [sr0] tag#0 Add. Sense: L-EC uncorrectable error
Jan  8 01:48:57 (none) user.info kernel: sr 0:0:0:0: [sr0] tag#0 CDB: Read(10) 28 00 00 00 7e 30 00 00 02 00
Jan  8 01:48:57 (none) user.err kernel: blk_update_request: I/O error, dev sr0, sector 129216
Jan  8 01:49:00 (none) user.info kernel: sr 0:0:0:0: [sr0] tag#0 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Jan  8 01:49:00 (none) user.info kernel: sr 0:0:0:0: [sr0] tag#0 Sense Key : Medium Error [current]
Jan  8 01:49:00 (none) user.info kernel: sr 0:0:0:0: [sr0] tag#0 Add. Sense: L-EC uncorrectable error
Jan  8 01:49:00 (none) user.info kernel: sr 0:0:0:0: [sr0] tag#0 CDB: Read(10) 28 00 00 00 7e 30 00 00 02 00
Jan  8 01:49:00 (none) user.err kernel: blk_update_request: I/O error, dev sr0, sector 129216
Jan  8 01:49:00 (none) user.err kernel: Buffer I/O error on dev sr0, logical block 16152, async page read


On not detected situation /mnt/cdrom0 is not mounted never, in first situation works

**Comment by trentasis** [comment]
screenshot

**Comment by trentasis** [comment]
Attached screenshot

Missatge de Thinstation <notifications@github.com> del dia ds., 2 de febr.
2019 a les 17:11:

**Comment by Thinstation** [comment]
That kinda reads like the device itself is reporting that it can't read a sector. Is the media good? Is the drive good?

**Comment by jackburton79** [comment]
This happens to me, too, with any support. I can assure the device and
support are ok.

Il giorno gio 7 feb 2019, 14:32 Thinstation <notifications@github.com> ha
scritto:

**Comment by trentasis** [comment]
media is right, because tested with windows works!!!
Not sure but I'm reading that seems could be a bug with some linux software
and media cd with multisession, not sure...

Any suggestion?

Missatge de Thinstation <notifications@github.com> del dia dj., 7 de febr.
2019 a les 14:32:

**Comment by Doncuppjr** [comment]
Your still making multisession cd’s?


Sent from Yahoo Mail for iPhone


On Thursday, February 7, 2019, 6:53 AM, trentasis <notifications@github.com> wrote:

media is right, because tested with windows works!!!
Not sure but I'm reading that seems could be a bug with some linux software
and media cd with multisession, not sure...

Any suggestion?

Missatge de Thinstation <notifications@github.com> del dia dj., 7 de febr.
2019 a les 14:32:

**Comment by trentasis** [comment]
Are not recorded for our users, in some situations, some companies record
with multisession, but I'm not really sure if this is the problem

Missatge de Donald A. Cupp Jr. <notifications@github.com> del dia dj., 7 de
febr. 2019 a les 16:02:

> Your still making multisession cd’s?
>
>
> Sent from Yahoo Mail for iPhone
>
>
> On Thursday, February 7, 2019, 6:53 AM, trentasis <

**Comment by Thinstation** [comment]
Soooo, where do you wanna go with this bug? If it's inherent of the Linux kernel to behave this way, what resolution can I provide?

**Comment by trentasis** [comment]
Not really sure, but some information related with systemd and this issue, Now I don't have more information. I'll try to get more information
Thanks

**Comment by trentasis** [comment]
Not sure if this can be the problem https://github.com/systemd/systemd/issues/2872

In our case in thinstation 5.5

**Comment by Thinstation** [comment]
Ty. I can update the library, but I can’t test it.

**Comment by trentasis** [comment]
Ok, If you need I can try to test with our 5.5
Thanks

**Comment by Thinstation** [comment]
We were only a point release behind. 2.33 vs 2.33.1. Not sure it that is going to fix the issue, but it's pushed.

**Comment by trentasis** [comment]
Hi,

Have you pushed to 5.5 or 6.1?
Issue was reproduced on 5.5 stable

thanks

Missatge de Thinstation <notifications@github.com> del dia dj., 28 de febr.
2019 a les 15:59:

**Comment by Doncuppjr** [comment]
6.1 is on almost the latest version of blkid, but it was only a bump from 2.33 to 2.33.1
