### ISSUE TITLE
Slow network initialization

### ISSUE THREAD

**Issue by maa7** [Thinstation/thinstation#360]
Hello,
I have bootable usb flash drive witn Thinstation 6.1 with VMware View autoconnect, and Intel NUC.

1) As I reported earlier (https://github.com/Thinstation/thinstation/issues/345), there is a problem with slow network initialization. At system startup I receive an error "Error: Failed to connect to server". After pressing the button "x Close" I can connect.

2) Also, at system startup always a window appears:
Panel
Welcome to the first start of the panel
Choose below which setup you want for the first startup.
[Use default config] [One empty panel]

**Comment by Doncuppjr** [comment]
When was your last checkout?

**Comment by maa7** [comment]
I reinstalled Thinstation five days ago

**Comment by Thinstation** [comment]
edit build/extra/etc/cmd/vmview.global
add
NETWORK_REQUIRED=true

**Comment by Thinstation** [comment]
as for the xfce panel, I would need to know more about your configs.

**Comment by rohrbachger** [comment]
We noticed also on some clients, that thee was  no or very slow connection to the view broker and showing Error Failed to connect to server.
After some testing we found out, that we need to open the internet connection, probably for certificate checks. We have reduced the access to those we figured out. Is there a way arround his without using untrusted connections?

**Comment by maa7** [comment]
I added
NETWORK_REQUIRED=true
to \thinstation\build\packages\vmview\build\extra\etc\cmd\vmview.global

but no success

**Comment by Doncuppjr** [comment]
It should have added a progress bar that waits for the network, before starting the application.

**Comment by DtNeo** [comment]
Hi
I have same issue on my NUC NUC5CPYH - lpxe boot - session vncviewer
But with the same image and lpxe too, my PC have not this trouble.
the problem come from only NUCs ?

**Comment by Doncuppjr** [comment]
Perhaps it is a firmware issue. You can enable the network countdown dialog by setting the NETWORK_REQUIRED flag on the package. It won't make the network any come up any faster, but it will delay the application launch until the network is up.
    On Friday, March 8, 2019, 4:39:54 AM PST, Aurélien DENOT <notifications@github.com> wrote:  
 
 
Hi
I have same issue on my NUC NUC5CPYH - lpxe boot - session vncviewer
But with the same image and lpxe too, my PC have not this trouble.
the problem come from only NUCs ?

**Comment by DtNeo** [comment]
Dear Don,

Sorry I didn't try your solution with network required. But It's now solved for me on my NUC.

I worked on Configuration of my builtime.conf.X for dissociation my NUC to my PC :
thinstation.conf-MACaddress - Over HTTP
wiki here : https://github.com/Thinstation/thinstation/wiki/Configuration

### My conf. Before :
**build.conf**
```
#package ts-classic
package netfiles
package networkmanager
package udisks-glue
#param baseurl http://192.168.1.2
#param basepath conf
```

### My conf. After :

**thinstation.conf.buildtime (the base)**
```
NET_FILE_METHOD=wget
NET_REMOTE_ACCESS_FROM=192.168.1.2
```

**thinstation.conf.005004AABBCC (The NUC)**
```
#Session VNC
SESSION_0_TYPE=vncviewer
SESSION_0_SERVER=192.168.1.3
SESSION_0_SERVER_OPTIONS="-Log *:stdout:100 > vncviewer.log -FUllScreenAllMonitors -shared"
SESSION_0_AUTOSTART=On
```

**build.conf**

```
package ts-classic
#package netfiles
package udisks
#package networkmanager
#package udisks-glue
```
```
param baseurl http://192.168.1.2
param basepath conf
```

And now, my NUC haven't this error before log on VNC.
P.S.: of course my files have more variable than I show, but I hope be helpfull for other with this informations. If they have mistake, contact me and I will edit this answer.
Have a nice day !
