### ISSUE TITLE
HP T530 fail 6.1 (4.19) - driver is missing

### ISSUE THREAD

**Issue by netromnetrom** [Thinstation/thinstation#361]
I get a black screen when booting this HP Thin Client. (AMD Embedded G-Series GX-215JJ Radeon R2E )

I get this in the Xorglog:
 ```
12.163] (II) LoadModule: "amdgpu"
 [    12.163] (WW) Warning, couldn't open module amdgpu
 [    12.163] (EE) Failed to load module "amdgpu" (module does not exist, 0) 
```
Is this related to a missing amdgpu_drv.so from xf86-video-amdgpu?

**Comment by Thinstation** [comment]
Added an xorg7-amdgpu package. Please test and report.

**Comment by netromnetrom** [comment]
The screen still goes black and don't respond to the keyboard. I can see that no X.org.log is created.
However when i boot without ten monitor connected I can ssh into the box. When reconnect the monitor I get the error with dmesg:

`[  181.243669] [drm] fb mappable at 0xC0766000
[  181.243676] [drm] vram apper at 0xC0000000
[  181.243678] [drm] size 33177600
[  181.243680] [drm] fb depth is 24
[  181.243682] [drm]    pitch is 15360
[  181.243810] fbcon: amdgpudrmfb (fb1) is primary device
[  181.243812] fbcon: Remapping primary device, fb1, to tty 1-63
[  181.253617] BUG: unable to handle kernel NULL pointer dereference at 0000000000000018
[  181.253621] PGD 9f68c067 P4D 9f68c067 PUD bc06f067 PMD 0 
[  181.253630] Oops: 0000 [#1] PREEMPT SMP NOPTI
[  181.253636] CPU: 1 PID: 181 Comm: kworker/1:3 Tainted: G           O      4.19.18TS #1
[  181.253639] Hardware name: HP HP t530 Thin Client/8267, BIOS M41 v01.04 05/14/2018
[  181.253771] Workqueue: events dm_irq_work_func [amdgpu]
[  181.253863] RIP: 0010:dc_link_aux_transfer+0x86/0x160 [amdgpu]
[  181.253867] Code: 00 00 00 00 c6 44 24 03 00 48 c7 44 24 08 00 00 00 00 48 8b 16 48 8b 00 8b 52 14 48 8b 80 38 01 00 00 48 8b 9c d0 b0 01 00 00 <48> 8b 43 18 48 89 df 48 8b 40 48 e8 0a 5c 09 f1 8b 44 24 78 4c 89
[  181.253869] RSP: 0018:ffffba6f009478a0 EFLAGS: 00010246
[  181.253872] RAX: ffffa0e72ef49800 RBX: 0000000000000000 RCX: ffffba6f009479c7
[  181.253874] RDX: 0000000000000002 RSI: ffffa0e730f506e0 RDI: ffffa0e72ef4a000
[  181.253876] RBP: 0000000000000600 R08: 0000000000000001 R09: 0000000000000000
[  181.253878] R10: ffffa0e79ac03680 R11: 0000000000000001 R12: 0000000000000001
[  181.253880] R13: ffffba6f009479c7 R14: ffffba6f0094793d R15: 0000000000000000
[  181.253883] FS:  0000000000000000(0000) GS:ffffa0e79b280000(0000) knlGS:0000000000000000
[  181.253886] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  181.253888] CR2: 0000000000000018 CR3: 000000009f772000 CR4: 00000000001406e0
[  181.253890] Call Trace:
[  181.253991]  dm_dp_aux_transfer+0xc0/0x110 [amdgpu]
[  181.254013]  drm_dp_dpcd_access+0x74/0x110 [drm_kms_helper]
[  181.254026]  drm_dp_dpcd_write+0x21/0x90 [drm_kms_helper]
[  181.254118]  dm_helpers_dp_write_dpcd+0x22/0x40 [amdgpu]
[  181.254210]  dp_receiver_power_ctrl+0x43/0x60 [amdgpu]
[  181.254303]  power_down_all_hw_blocks+0x197/0x1c0 [amdgpu]
[  181.254396]  dce110_enable_accelerated_mode+0x61/0x1b0 [amdgpu]
[  181.254485]  dc_commit_state+0x226/0x540 [amdgpu]
[  181.254573]  ? set_freesync_on_streams.part.7+0x8e/0x260 [amdgpu]
[  181.254661]  ? mod_freesync_set_user_enable+0x148/0x180 [amdgpu]
[  181.254756]  amdgpu_dm_atomic_commit_tail+0x38c/0xdb0 [amdgpu]
[  181.254767]  ? wait_for_completion_timeout+0x10b/0x130
[  181.254770]  ? wait_for_completion_interruptible+0x11a/0x170
[  181.254863]  ? dm_plane_helper_prepare_fb+0x1a1/0x300 [amdgpu]
[  181.254885]  commit_tail+0x38/0x60 [drm_kms_helper]
[  181.254899]  drm_atomic_helper_commit+0xf7/0x100 [drm_kms_helper]
[  181.254912]  restore_fbdev_mode_atomic+0x1ce/0x1e0 [drm_kms_helper]
[  181.254927]  drm_fb_helper_restore_fbdev_mode_unlocked+0x40/0x90 [drm_kms_helper]
[  181.254940]  drm_fb_helper_set_par+0x24/0x50 [drm_kms_helper]
[  181.254946]  set_con2fb_map+0x191/0x410
[  181.254951]  fbcon_fb_registered+0x80/0x1b0
[  181.254957]  notifier_call_chain+0x42/0x60
[  181.254961]  blocking_notifier_call_chain+0x39/0x60
[  181.254965]  ? down+0xd/0x50
[  181.254969]  register_framebuffer+0x24a/0x350
[  181.254983]  __drm_fb_helper_initial_config_and_unlock+0x21d/0x400 [drm_kms_helper]
[  181.254996]  drm_kms_helper_hotplug_event+0x21/0x30 [drm_kms_helper]
[  181.255099]  handle_hpd_irq+0xdb/0x100 [amdgpu]
[  181.255191]  dm_irq_work_func+0x49/0x60 [amdgpu]
[  181.255198]  process_one_work+0x1c0/0x340
[  181.255202]  worker_thread+0x28/0x3c0
[  181.255206]  ? process_one_work+0x340/0x340
[  181.255210]  kthread+0x109/0x120
[  181.255213]  ? kthread_create_worker_on_cpu+0x70/0x70
[  181.255217]  ret_from_fork+0x22/0x40
[  181.255221] Modules linked in: vfat fat sd_mod amdkfd amd_iommu_v2 joydev amdgpu chash gpu_sched i2c_algo_bit edac_mce_amd ttm ccp drm_kms_helper kvm hp_wmi sparse_keymap wmi_bmof ahci snd_hda_codec_realtek libahci irqbypass crct10dif_pclmul crc32_pclmul snd_hda_codec_generic snd_hda_codec_hdmi crc32c_intel ghash_clmulni_intel snd_hda_intel drm libata snd_hda_codec snd_hda_core snd_hwdep pcspkr r8169 snd_pcm scsi_mod sp5100_tco fam15h_power k10temp snd_timer realtek i2c_piix4 snd drm_panel_orientation_quirks soundcore wmi rfkill_gpio rfkill video uvesafb cfbfillrect cfbimgblt cfbcopyarea fuse autofs4
[  181.255288] CR2: 0000000000000018
[  181.255293] ---[ end trace 230acf61802b1488 ]---
[  181.255388] RIP: 0010:dc_link_aux_transfer+0x86/0x160 [amdgpu]
[  181.255392] Code: 00 00 00 00 c6 44 24 03 00 48 c7 44 24 08 00 00 00 00 48 8b 16 48 8b 00 8b 52 14 48 8b 80 38 01 00 00 48 8b 9c d0 b0 01 00 00 <48> 8b 43 18 48 89 df 48 8b 40 48 e8 0a 5c 09 f1 8b 44 24 78 4c 89
[  181.255394] RSP: 0018:ffffba6f009478a0 EFLAGS: 00010246
[  181.255397] RAX: ffffa0e72ef49800 RBX: 0000000000000000 RCX: ffffba6f009479c7
[  181.255399] RDX: 0000000000000002 RSI: ffffa0e730f506e0 RDI: ffffa0e72ef4a000
[  181.255401] RBP: 0000000000000600 R08: 0000000000000001 R09: 0000000000000000
[  181.255403] R10: ffffa0e79ac03680 R11: 0000000000000001 R12: 0000000000000001
[  181.255404] R13: ffffba6f009479c7 R14: ffffba6f0094793d R15: 0000000000000000
[  181.255407] FS:  0000000000000000(0000) GS:ffffa0e79b280000(0000) knlGS:0000000000000000
[  181.255410] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  181.255412] CR2: 0000000000000018 CR3: 000000009f772000 CR4: 00000000001406e0
`

I then tried to boot with amdgpu.dc=0 which gave this dmesg error:

`[   15.759883] [drm:uvd_v6_0_start [amdgpu]] *ERROR* UVD not responding, trying to reset the VCPU!!!
[   16.780905] [drm:uvd_v6_0_start [amdgpu]] *ERROR* UVD not responding, trying to reset the VCPU!!!
[   17.801913] [drm:uvd_v6_0_start [amdgpu]] *ERROR* UVD not responding, trying to reset the VCPU!!!
[   18.822953] [drm:uvd_v6_0_start [amdgpu]] *ERROR* UVD not responding, trying to reset the VCPU!!!
[   19.844034] [drm:uvd_v6_0_start [amdgpu]] *ERROR* UVD not responding, trying to reset the VCPU!!!
[   20.865059] [drm:uvd_v6_0_start [amdgpu]] *ERROR* UVD not responding, trying to reset the VCPU!!!
[   21.886075] [drm:uvd_v6_0_start [amdgpu]] *ERROR* UVD not responding, trying to reset the VCPU!!!
[   22.907103] [drm:uvd_v6_0_start [amdgpu]] *ERROR* UVD not responding, trying to reset the VCPU!!!
[   23.928134] [drm:uvd_v6_0_start [amdgpu]] *ERROR* UVD not responding, trying to reset the VCPU!!!
[   24.949150] [drm:uvd_v6_0_start [amdgpu]] *ERROR* UVD not responding, trying to reset the VCPU!!!
[   24.969344] [drm:uvd_v6_0_start [amdgpu]] *ERROR* UVD not responding, giving up!!!
[   24.969471] [drm:amdgpu_device_ip_set_powergating_state [amdgpu]] *ERROR* set_powergating_state of IP block <uvd_v6_0> failed -1
[   25.022927] kauditd_printk_skb: 20 callbacks suppressed
[   25.022929] audit: type=1130 audit(1549632333.783:60): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=user@1000 comm="systemd" exe="/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   25.064297] audit: type=1131 audit(1549632333.827:61): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=NetworkManager-dispatcher comm="systemd" exe="/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   25.121063] audit: type=1112 audit(1549632333.884:62): pid=3698 uid=0 auid=1000 ses=1 msg='op=login acct="tsuser" exe="/bin/login" hostname=? addr=? terminal=/dev/tty1 res=success'
[   25.982397] [drm:amdgpu_uvd_ring_test_ib [amdgpu]] *ERROR* amdgpu: (0)IB test timed out.
[   25.982546] [drm:amdgpu_ib_ring_tests [amdgpu]] *ERROR* amdgpu: failed testing IB on ring 11 (-110).
[   26.083448] [drm:process_one_work] *ERROR* ib ring test failed (-110).
[   37.438454] [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring gfx timeout, signaled seq=1, emitted seq=2
[   37.438466] [drm] IP block:gmc_v8_0 is hung!
[   37.438471] [drm] IP block:gfx_v8_0 is hung!
[   37.438477] [drm] IP block:uvd_v6_0 is hung!
[   37.438564] [drm] GPU recovery disabled.
`

The X.org then ends up with this unsupported mode:

`26.889] (II) AMDGPU(0): Setting screen physical size to 1016 x 571
`

**Comment by netromnetrom** [comment]
Ups.. wrong button

**Comment by Thinstation** [comment]
Hmmm. Looks like I at least need to add amdgpu to my pre-udev tests. Might be enough.

**Comment by Thinstation** [comment]
Can you retest?

**Comment by netromnetrom** [comment]
That helped a lot! 
It first crashed when I used the default settings, but when I disabled the Display Core driver (amdgpu.dc=0) It started perfectly.

**Comment by netromnetrom** [comment]
That helped a lot! 
It first crashed when I used the default settings, but when I disabled the Display Core driver (amdgpu.dc=0) it started perfectly.

**Comment by netromnetrom** [comment]
That helped a lot! 
It first crashed when I used the default settings, but when I disabled the Display Core driver (amdgpu.dc=0) it started perfectly.

**Comment by netromnetrom** [comment]
I did another test with a AMD Ryzen 2400G with Radeon. Here I needed to set amdgpu.dc=1 in order to start X.

**Comment by Thinstation** [comment]
Sounds like that driver is a little unstable. We have an init script for
dealing with such quirks(pre-udev), but you would need to develop a method
for distinguishing between the two needed modes, and setting module load
options correctly.

**Comment by netromnetrom** [comment]
I'm able to put the HP-t530 into production. Thanks a lot.
