### ISSUE TITLE
USB Flash Problems

### ISSUE THREAD

**Issue by jeefo** [Thinstation/thinstation#364]
Hi.

There is some issue with USB-flash-drive mounting. It's mounted OK, but when drive ejected out of the USB port  physically it's stays mounted into folder, so we're have tons of IO errors in dmesg. Seems that udev-rules doesn't handle remove ? So if we insert that flash once again it's will be sdb1 and so on.

Another problem is that NTFS drives is not recognized. Probably because we have "module ntfs" inside build.conf, however the kernel itself  built without ntfs driver (native). After rebuild of kernel with ntfs & nls_utf8 it's started working OK, but they are still not unmounted on eject.

**Comment by Doncuppjr** [comment]
There was another report of this behavior. I believe the bugs were found, and fixed. Try pulling the latest and building again.
