### ISSUE TITLE
6.1 stable read-only filesystem

### ISSUE THREAD

**Issue by mcsn747** [Thinstation/thinstation#365]
Hi!

I have some trouble with Thinstation network boot. Filesystem is read-only at boot, how fix it?
![img_20190215_152041](https://user-images.githubusercontent.com/42139514/52851486-0c8ce280-3138-11e9-9fe4-fe8a4271d6fa.jpg)
I use almost default configs with:

```
package overlayfs     

param fastboot       true  
param initrdcmd     "squashfs"
param squashopt     "-comp xz -Xdict-size 100%"


```
Same image boot successfully via USB.

Thanks you!

**Comment by Thinstation** [comment]
Which version are you using? ThinStation.init is deprecated.

**Comment by Thinstation** [comment]
Your now using 6.1-Stable. Maybe your have mixed components.

**Comment by mcsn747** [comment]
I'm using version that I can clone now from thinstation.git without parameters. 
Uname show me:
`Linux thinstation-linux 4.19.18TS #1 SMP PREEMPT Wed Jan 30 03:27:53 UTC 2019 x86_64 GNU/Linux
`
And this is files from /etc folder from thinstation machine that I manage boot via network.

![img_20190220_143158](https://user-images.githubusercontent.com/42139514/53082472-ba283900-351e-11e9-892f-fc77c97adf12.jpg)
I see that thinstation.init still in use.

**Comment by mcsn747** [comment]
I found that network boot work well if use  **param initrdcmd  "gzip"** option in build.conf file. Thanks!

**Comment by Doncuppjr** [comment]
It might exist(not deleted), but it’s not being used.
