### ISSUE TITLE
USB Boot

### ISSUE THREAD

**Issue by l0s3rr** [Thinstation/thinstation#371]
Hey, how are you?

I tried to make a ThinStation iso bootable in USB, but it is not working.

This iso I used to boot into PXE and the same via PXE works perfectly.

Can you help me?

**Comment by Thinstation** [comment]
How did you make the usb drive?

**Comment by l0s3rr** [comment]
I tried with the Rufus program and tried it with Yumi too.

**Comment by Thinstation** [comment]
Please follow the directions at
https://github.com/Thinstation/thinstation/wiki/Deployment

Go down to the Syslinux section and follow the how to. TS has special
features that Rufus does not address.

**Comment by l0s3rr** [comment]
Ok, thank you.

**Comment by l0s3rr** [comment]
Good Morning, are you okay?

I followed the tutorial, however, when I plugged the pendrive, it is not appearing as bootavel.

Here are the commands I used:

mount /dev/sdb1 /mnt

cd /mnt && cp -a /ThinStation/build/boot-images/syslinux/ .

umount /mnt

syslinux --install /dev/sdb1

Can you Help Me?

**Comment by Thinstation** [comment]
try using
mkmbrdrv -o /build/boot-images/syslinux -p d:0:boot /dev/sdb

**Comment by l0s3rr** [comment]
![image](https://user-images.githubusercontent.com/42104711/53340266-5ec3c580-38e7-11e9-97f7-8ab88384b256.png)

This is normal?

**Comment by Doncuppjr** [comment]
No, that's not normal.
    On Monday, February 25, 2019, 5:23:40 AM PST, L0s3rr <notifications@github.com> wrote:  
 
 


This is normal?

**Comment by Doncuppjr** [comment]
I've never seen it fail right at the end like that.
    On Monday, February 25, 2019, 5:23:40 AM PST, L0s3rr <notifications@github.com> wrote:  
 
 


This is normal?

**Comment by l0s3rr** [comment]
I am root and the pendrive was disassembled.

**Comment by Doncuppjr** [comment]
try running the command again, sometimes the drive is an issue.

**Comment by l0s3rr** [comment]
I running again but same problem.

**Comment by Doncuppjr** [comment]
Do you have an environment variable "loopfile" ?

**Comment by l0s3rr** [comment]
I do not think so, but how to do it?

**Comment by Doncuppjr** [comment]
Anyway, based on where that happens, I think this is a non-fatal error. The drive should work.

**Comment by Doncuppjr** [comment]
set |grep -e loopfile

**Comment by l0s3rr** [comment]
> 
> 
> set |grep -e loopfile

Empty result, I tested the drive and it does not even appear as bootavel in BIOS.

**Comment by Doncuppjr** [comment]
are you trying to boot efi?

**Comment by l0s3rr** [comment]
Yes and legacy also the same problem occurs.

**Comment by Doncuppjr** [comment]
That drive should be bootable via legacy bios boot mode. 
mkgptdrv is used when trying to make efi bootable, but you need to build different boot images.
Let me confirm the instructions......

**Comment by l0s3rr** [comment]
I followed the tutorial of this link https://github.com/Thinstation/thinstation/wiki/Deployment#HowTo in the Syslinux section.

**Comment by Doncuppjr** [comment]
Yes, that's for a default build and bios boot

**Comment by l0s3rr** [comment]
I understand, may be something in my configs, but via PXE works perfectly.

**Comment by Doncuppjr** [comment]
mkgptdrv -o /build/boot-images/refind -p ESP:0:boot /dev/sdb

**Comment by l0s3rr** [comment]
Uploaded ThinStation but did not connect to RDP.

Should I change something in my config?

Thank you for your help.

**Comment by l0s3rr** [comment]
I tried to change in build.conf to generate a new refind however when it goes up thinstation it neither connects in RDP nor shows anything in hers.

**Comment by Doncuppjr** [comment]
What's your native language?

**Comment by l0s3rr** [comment]
Português/Brazilian

**Comment by l0s3rr** [comment]
Link to my build.conf and thinstation.conf.buildtime:

https://ghostbin.com/paste/ratpm/raw

If you see something that should be changed just let me know.

**Comment by l0s3rr** [comment]
I tried uploading the same image on a Virtualizer (VirtualBox) and the same error occurred.

**Comment by macserv** [comment]
For what it's worth, the instructions on the Deployment page did not result in a bootable USB stick for me, either.  I did manage to make it work, and once I had a working process, I created a quick `zsh` script so I could repeat it reliably.  I've shared it here:

https://gist.github.com/macserv/a8ba84a26ad6373f5a492a8ac66f7e2a

**Comment by l0s3rr** [comment]
> 
> 
> For what it's worth, the instructions on the Deployment page did not result in a bootable USB stick for me, either. I did manage to make it work, and once I had a working process, I created a quick `zsh` script so I could repeat it reliably. I've shared it here:
> 
> https://gist.github.com/macserv/a8ba84a26ad6373f5a492a8ac66f7e2a

Thanks Man.
