### ISSUE TITLE
VNCviewer can't -fullscreen with Xorg 1.20 compatibility

### ISSUE THREAD

**Issue by DtNeo** [Thinstation/thinstation#375]
Hello,

Hope I'll usefull.
This combinaison of packages :
Xorg 1.20
TigerVNC/tigervnc 1.6

vncviewer -fullscreen => "Adjusting window size to avoid accidental full screen request"
[TigerVNC/tigervnc#660](https://github.com/TigerVNC/tigervnc/issues/660)

Resolve in branch 1.8 of TigerVNC/tigervnc
[TigerVNC/tigervnc#661](https://github.com/TigerVNC/tigervnc/pull/661)
[void-linux/void-packages#180](https://github.com/void-linux/void-packages/pull/180)

Thank you

**Comment by DtNeo** [comment]
Sorry for spam, do you need more details or you know and need time for make changes.
Thank you for your time

**Comment by Thinstation** [comment]
Pushed.

**Comment by DtNeo** [comment]
I have update twice (kernel panic at first time)
I builded my image... (three times, I wanted try differents options, maybe it's my fault ?!)
Still a grey screen.

It works without the option, despite the error :
"Adjusting window size to avoid accidental full screen request"
But the desk have a margin on top and so it's cut on bottom (when no fullscreen option) so it's not operational like that.
F8 works and show me all possibilities, vnc isn't broken.
-> if I select option fullscreen, a gray screen apear and the screen is totaly freeze (have to reboot).
I share you the log vncviewer with the -fullscreen option :

`
Thu Feb 28 23:01:05 2019
 Config:      set FullScreen(Bool) to 1
 TcpSocket:   Connecting to 10.0.1.3 [10.0.1.3] port 5900
 CConn:       connected to host 10.0.1.3 port 5900
 CConnection: reading protocol version
 CConnection: Server supports RFB protocol version 3.8
 CConnection: Using RFB protocol version 3.8
 CConnection: processing security types message
 CConnection: Server offers security type None(1)
 CConnection: Choosing security type None(1)
 CConnection: processing security message
 CConnection: processing security result message
 CConnection: processing security result message
 CConnection: Authentication success!
 CConnection: reading server initialisation
 CConnection: initialisation done
 X11PixelBuffer: Using default colormap and visual, TrueColor, depth 24.
 X11PixelBuffer: Using shared memory XImage
 DesktopWindow: Adjusting window size to avoid accidental full screen request
 Config:      set FullScreen(Bool) to 1
 CConn:       Using pixel format depth 24 (32bpp) little-endian rgb888
 CConn:       Using Tight encoding
`

My session config :

SESSION_0_TYPE=vncviewer
SESSION_0_AUTOSTART=On
SESSION_0_VNCVIEWER_SERVER='10.0.1.3'
SESSION_0_VNCVIEWER_OPTION='-Log *stdout:100 > vncviewer.log -FullScreen'

**Comment by DtNeo** [comment]
**/var/log/Xorg.0.log**

`    10.350]
X.Org X Server 1.20.3
X Protocol Version 11, Revision 0
[    10.350] Build Operating System: Composer ThinStation
[    10.350] Current Operating System: Linux TSpxe_94c6911911df 4.14.91TS #1 SMP PREEMPT Tue Jan 8 22:53:59 UTC 2019 x86_64
[    10.350] Kernel command line: usbhid.quirks=0x1bfd:0x3050:0x40 BOOT_IMAGE=http://10.0.1.2/boot/vmlinuz initrd=http://10.0.1.2/boot/ucode,http://10.0.1.2/boot/initrd  splash=off load_ramdisk=1 ramdisk_start=633 ramdisk_blocksize=4096$
[    10.350] Build Date: 27 October 2018  05:47:16PM
[...]`

**Comment by DtNeo** [comment]
![20190228_233533](https://user-images.githubusercontent.com/48035247/53603465-e5abc300-3bb1-11e9-8e59-fa6190c0f73f.jpg)

**Comment by DtNeo** [comment]
My fault, I didn't understand how update, what you did for me.
I was lost between "kernel not found", "RAMDISK error" ...

For other, who want understand and don't want lose 3 or 4 days like me : 
helpfull : https://github.com/Thinstation/thinstation/wiki/Update-a-package 

I did this : 
in terminal chroot
cd /ts/ports/components/tigervnc/
pkgmk -u -d -um
pkgmk -u
pkgmk -uf
pkgmk -u

AND ! read carefully : 
update vncviewer
(and not tigervnc like I tried millions times)

Enjoy the update of TigerVNC Viewer 64-bit v1.9 !

Thank you for this beautiful project,
