### ISSUE TITLE
2 displays + rdekstop + xrandr

### ISSUE THREAD

**Issue by m0bYczE** [Thinstation/thinstation#377]
Hello, I need connect 2 monitors to pc with xrandr function --same-as. Every time, when I try use command to set this, I get error: "Configure crtc 0 failed" or "Configure crtc 1 failed". I'm using rdesktop.

Thank you.

**Comment by Doncuppjr** [comment]
That's not really a specific ThinStation issue. Try just looking into xrandr and it's functionality.

**Comment by shweew** [comment]
Through addition of resolutions of monitors, roughly two monitors 1024х768:
-g 2048x768
receive one desktop on both monitors.

**Comment by m0bYczE** [comment]
Sorry, my bad. I have in config USE_XRADR without N. USE_XRANDR=true fixed it.
Thank you.
