### ISSUE TITLE
Windows button doesn't work

### ISSUE THREAD

**Issue by l0s3rr** [Thinstation/thinstation#379]
Hi,

I did the ThinStation setup via PXE, but when I connect to RDP the windows button is not working, could anyone help me?

Here are my settings:

### build.conf

#!!Machine module list
machine m704                # Gigabyte m704 Rover PC
machine WYSE9150se          # WYSE 9150se Thin Client
machine NT-A3500            # Foxconn AMD E-350 Barebone
machine NT-535              # Foxconn Intel D525 Barebone
machine Dell-FX170          # Dell FX170 D525 Atom Machine
machine VMWare              # A good set of modules for a VmWare Virtual Machine
machine Virtualbox-4.1          # A good set of modules for a Virtualbox Virtual Machine#machine VIA-Epia-CLE266        # VIA Epia/Eden based on the the CLE266 chip. Rather common in thin clients a few years old
machine classic_generic     # Big list of modules that you can choose by unremarking them
machine IGEL-M300C                     # Igel CX700 Via
machine HP-t5135                       # HP CX700 Via
 
#!!Wireless Stuff
package wpa_supplicant
package wireless
package wifi-connect
#!!!Misc Modules
 
#!!Filesystem Support

module usb-storage
module autofs4              # Automount and autofs support
module isofs                # ISO9960 file system support for CDRoms
module udf          # CDRom UDF file system support
module vfat                 # Fat and VFat file system support
module ntfs                 # NTFS file system support
module ext2                 # Ext2 file system support
module ext3                 # Ext3 file system support
module ext4         # Ext4 file system support
module nfs              # NFS file system support
module cifs         # CIFS support (use either this or smbfs - not both)
 

#!!Miscellaneous
package aufs            # This is needed in order for squashfs compression mode to work.
#package ts-classic              # The classic ts logic for network/netfiles/hostname/mounting/telnetd/telnet/playcd
package automount
package networkmanager
#package udisks-glue
package ntp         # Utility to obtain date & time from network
package sound-esd       # Enable sound-esd or sound-nasd if you want to be able to control
package sound-nasd      #  sound on your thin client from another computer or
                            #  your remote session.
package alsa
package gnome-media
package gnome-network-properties
package gnome-core
package volumeicon
package kismet
package gst-plugins-base
package gst-plugins-good
#package crystalhd
#package libva
package iptables        # IP Tables support
package cpufreq
#package cpuspeed
#package wine           # Windows Application Execution Platform
 
#!!X related

package xorg7-v4l
package xorg7-vesa      #A fallback driver that works with almost everything. Does allow resolution changes
package xorg7-vmware
package xorg7-ati       #ATI video driver for most modern ATI chipsets. Usually requires several firmwares
package xorg7-nouveau       #New opensource nvidia driver
package xorg7_nvidia        #Proprietary nvidia driver
package xorg7_nvidia_64         # Additional 64bit module
package xorg7-openchrome    #Via Video Chipsets driver
package xorg7-geode     #Geode Video driver
package xorg7-intel     #Intel video driver for most modern chipsets except the GMA3500/3600
package xorg7-sis
 
#!!Locale or localization files for keyboard and fonts.  (Language/Country)
#package locale-cs_CZ  # Czech
#package locale-da_DK  # Danish
#package locale-de_DE  # German
package locale-en_GB  # English-Great Britain
package locale-en_US  # English-US
#package locale-es_ES  # Spanish
#package locale-fi_FI  # Finnish
#package locale-fr_BE  # French Belgium
#package locale-fr_CA  # French Canadian
#package locale-fr_CH  # French Switzerland
#package locale-fr_FR  # French
#package locale-hr_HR  # Croation
#package locale-hu_HU  # Hungarian
#package locale-it_IT  # Italian
#package locale-ja_JP  # Japanese
#package locale-nb_NO  # Norwegian (bokmål)
#package locale-pl_PL  # Polish
package locale-pt_PT  # Portuguese
package locale-pt_BR  # Portuguese-Brazil
#package locale-ru_RU  # Russian
#package locale-sv_SE  # Swedish
#package locale-tr_TR  # Turkish
#
#!Applications
#!!Connection Package types.  Choose *at least* one!
package freerdp     # X RDP Client - fork of rdesktop
package rdesktop        # X RDP client for Windows Terminal Services (ver 1.7)
#package vncviewer      # VNC client (vncviewer)
#package xorg7vnc       # Remote Control Client Workstation
#package ica            # Citrix ICA client support
#package tarantella     # Tarantella client support
#package xnest          # XDM in a window client
#package urxvt              # Light Xterm Client (vt102)
#package xterm              # Xterm Client (vt220)
#package ssh            # Secure Shell client
#package tn5250             # 5250 terminal emulator
#package dillo          # Dillo light web browser
#package thinlinc       # Cendio ThinLinc client support
#package nx                 # No Machine NX client
#package 2x         # 2X client
#package java           # Java runtime
#package firefox_lowmem     # Firefox 3 for low resource machines
#package firefox        # Firefox current Web Browser
#package chrome         # Google Chrome Web Browser
#package kiosk          # Rkiosk Plugin for Firefox
#package flash_lowmem       # Flash 9 browser plugin for firefox and low resource machines
#package flash          # Flash Current
#package filezilla      # FileZilla FTP Client for X
#package git            # GIT Version Control System
#package gparted        # Gnome Partition Manager
package open-vm-tools
#package medit          # Notepad
#package mplayer        # DVD and video player
#package vmview                 # VMware Open-View Client, no PCoIP
#package vmviewpcoip            # VMware Open-View Client, PCOIP
#package xbmc           # XBMC Media Center for X
#package evince         # X PDF Viewer
 
#!!Window Managers. Choose no more than 1 window manager.

#package openbox        # A spartin clean/fast window manager.
#package xdesktop-kiosk     # A locked down desktop kiosk using the openbox wm (See packages/xdesktop-kiosk/build/conf for
                # more help.
#package icewm          # "ICEWM" window manager.  Makes TS a light workstation.
#package icewm-theme-xp
#package icewm-themes       # Extra IceWM themes
#package icewm-theme-bernstein
#package icewm-theme-bluecrux
#package icewm-theme-liquid
 
package xfwm4
package xfwm4-extra
package xfce4-power-manager
package terminal        # Terminal emulator for xfwm4 -- Pulls in xfwm4
package thunar          # File Manager for xfwm4 -- Pulls in xfwm4
 
#!!Window Manager Utils
#package idle-shutdown      # Package that lets you specify automatic shutdown settings and logic.
#package wbar               # Adds icons to desktop
#package idesk
 
#!!Other services
#package www            # Web access to client.  From a browser: "http://<IP number>"
                            #  The standard page is for general user settings, administrative access
                            #  is on port 6800.
#package lp_server      # Remote printing daemon (JetDirect compatible)
#package lpr                # LPR Print Server, for use with samba-server package
#package lprng              # LPRng Print Server, supports network based printing
package cups
#package sshd           # Dropbear secure shell server
#package tftpd          # Built in tftpd server. Useful for making a tftpserver
                #  for thinstation on a WAN over a slow link.
#package samba-server       # Samba server FS Support, allows you to share
                            #  local floppy/cdrom/hd/printer to other Windows
                #  PCs. Needs supermount for removeable media.
#package samba-client       # Samba smbclient, gives a shell like environment to access an samba server
#package hdupdate           # Package for updating TS images on a hardisk over a network connection
#package scp                    # Add ability to download files over internet using scp.  This package
                            #  adds some networking based options for downloading configuration files or
                            #  in using hdupdate package.
#package openvpn                # OpenVPN Client Support
 
 
#!!PCSCD Card Readers
package gemplus410             # Card reader Gemplus 410 (Serial) and Gemplus 430 (USB)
package ccidreader             # Generic USB card reader
 
 
#!!Miscellaneous
package gtk-2.0         # Full gtk-2.0 plus clearlooks theme
package icons-cursor        # Anti Aliased Mouse Cursor Theme
package icons-hicolor           # Hi-Color icons for some applications and themes. Does not really contain any icons.
package icons-gnome             # gnome Hi-Color icons theme. Needed by most other icon themes.
#package icons-tango             # tango Hi-Color icons theme
#package icons-neu               # neu Hi-Color icons theme
#package fonts-misc
#package fonts-jis-misc     # Japanese Industrial
#package fonts-util
#package fonts-cyrillic
#package fonts-Speedo-Bitstream
package fonts-TTF-BH        # This one works nicely most of the time and is small.
package fonts-TTF-vera
#package fonts-TTF-MS       # Fonts for rendering documents developed on the MS Platform.
                # Might want to talk to a lawyer before using these.
package fonts-TTF-liberation
#package fonts-75dpi-Adobe
#package fonts-75dpi-Adobe-Utopia
#package fonts-75dpi-BH
#package fonts-75dpi-BH-Typewriter
#package fonts-75dpi-Bitstream
#package fonts-100dpi-Adobe
#package fonts-100dpi-Adobe-Utopia
#package fonts-100dpi-BH
#package fonts-100dpi-BH-Typewriter
#package fonts-100dpi-Bitstream
#package fonts-Type1-Adobe-Utopia
#package fonts-Type1-BH
#package fonts-Type1-Bitstream
#package fonts-Type1-IBM
#package fonts-Type1-xfree86
#package lshw           # list hardware
#package e3             # Basic vi like Editor
#package rox            # Basic File Manager
#package debug          # metapackage to include other debugging packages and stop during bootup to check things.#package extensions        # Adds various shell commands, will increase image size.
#ackage extensions-x        # Adds various utility s for the X Environment !!!! INCLUDES hwlister.sh !!!!
#package eGalax                 # eGalax TouchKit Drivers/Utility for serial and usb touchscreens by EETI.
#package installer      # Wipes a drive, makes partitions and downloads thinstation from a pxe server
#package devstation     # Starts a tftp server that hosts files from the boot-images/pxe folder
#param tsuser         tsuser                            # Name of the user that thinstation will run as. Needs userauto package.
#param tsuserpasswd   pleasechangeme            # Do Change! Console/telnet password for non-root
 
param rootpasswd     5sec123            # Do Change!  Console/telnet password for root
                                                # If this is enabled, Telnetd will be enabled.
#param xorgvncpasswd  pleasechangeme            # VNC Access Password
#param storagepasswd  pleasechangeme            # Password for storage server
#param dialuppasswd   pleasechangeme            # Password for dialin account
#param sambapasswd    pleasechangeme            # Password for samba shares when using user mode security
#param kernelcmdline "radeon.modeset=0"                 # Add additional kernel command lines. e.g. disable radeon framebuffer
#param stripelf       yes               # Strip extraneous information from elf binaries (Maybe not Safe)
#param acpisupport    disable               # Tells the kernel not to load acpi modules. (Breaks some Intel Chipsets if disabled)
#param uvesafb        disable               # Disable uvesafb (legacy option like modesetfb)
#param extra_vid      LVDS-1:d              # Add an extra video= parameter to kernel cmd line (good for disabling outputs on video cards)
param bootlogo       true               # Enable or Disable the use of the Boot splash.
param boottheme      default                    # Backgound picture during boot
param splash         verbose                # kernel splash setting (0=off, silent or verbose (default=silent)
param splash         silent
param fbmtrr         0                                  # MTRR value for uvesafb (default = 0, 4 is the best) grep your log to make sure you have not set it to high
param fbnocrtc      true                               # This is usually a good thing.
param fbsm           ywrap                              # Window scrolling method (redraw, ypan, ywrap) ywrap is best, but may not work correctly for all people
#param fbvtotal       16                                # Override Video Bios Reported Memory in MB
#param fbmaxhf        67                                # Override Video Negotiated Max Horizontal Frequency
#param fbmaxvf        61                                # Override Video Negotiated Max Vertical Frequency
#param fbmaxclk       155                               # Override Video Negotiated Max Clock Frequency
#param fbnoedid       true                              # Don t do video edid
param bootresolution 1024x600-32                       # Resolution used during Thinstation boot.
param bootresolution 1024x768-32                        # You can wright your own resolution mode here, if you know it.
param bootresolution 1152x864-32
param bootresolution 1280x768-32
param bootresolution 1366x768-32                       # Otherwise, you may want to refer to the vbe_modes.list you created with hwlister.sh
param bootresolution 1280x1024-32                      # for modes that your card supports.
param bootresolution 1400x900-32                       # It is also used by xrandr if no xrandr options are specified.
param bootresolution 1680x1050-32
param bootresolution 1920x1080-32
param bootresolution 1400x1050-32
 
param desktop file:./backgrounds/Hive_Lite.jpg      # Custom image to load as desktop background
param defaultconfig  thinstation.conf.buildtime     # The file with default setup.  No other config file is found
                                                    #  during boot.
param basename       thinstation                # Used for all config/tftp/scp file names
param basepath       ts5.3                      # Used to determine path to tftp/scp files
#param baseurl        http://www.doncuppjr.net      # Used to determine url to wget files
#param keyfile        ./id_rsa                  # Path for private key file used for ssh/scp
#param knownhosts     ./known_hosts             # Path for ssh known_hosts file for ssh/scp
#param localpkgs      false             # to determine is PKG files are to be loaded locally
#param fulllocales    true                  # Use full locale support for packages
#param icaencryption  false                 # Use ica encryption support, add 290k to image
param haltonerror    false              # Will halt on error, default is true
param hardlinkfs     true
param sametimestmp   true                               # When enabled, the timestamps for all files and folders will be set to 00:00 of todays date in your timezone
param initrdcmd      "squashfs"             # Compression mode and level of initrd file. none, gzip -9, lzma -9 ,bzip2 -9
param bootverbosity   3                     # Increased vebosity when booting TS
                                            #   0 no verbose message
                                            #   1 boot
                                            #   2 network
                                            #   4 init
                                            #   8 kernel
                                            #  16 modules
                                            #  32 packages
                                            #  64 email bootlog file to SMTP server & user set in
                                            #     thinstation.conf file.  This will only work
                                            #     if networking is working.
                                            #
                                            #  Combinations can be used (e.g. 24 does Kernel and Module Messages)
 
#!!Advanced
param downloads         /downloads
param bootimages        "iso syslinux pxe refind"
param syslinuxtheme     "default"
#param httpproxy    http://192.168.1.2:8080
 
#param bootfssize     50%                               # Modify the size of the tmpfs filesystem
 
package alltimezone
param allres        true        # Includes a lot of resolution splash images for live-cd s
param allfirmware   true        # Includes a lot of firmwares for live-cd s

### thinstation.conf.buildtime

AUDIO_LEVEL=67
KEYBOARD_MAP=en-us
MIC_LEVEL=0
SESSION_0_TYPE=xfwm4
SESSION_0_AUTOSTART=on
SESSION_1_TYPE=rdesktop
SESSION_1_RDESKTOP_SERVER=172.22.3.211
SESSION_1_RDESKTOP_OPTIONS="-d ezex -k pt-br"
SESSION_1_AUTOSTART=On
SCREEN_BLANK_TIME=10
SCREEN_STANDBY_TIME=20
SCREEN_SUSPEND_TIME=30
SCREEN_OFF_TIME=60
MOUSE_RESOLUTION=100
XFWM4_COMPOSITING=true
XFWM4_BRIGHTNESS="-33"
XFWM4_RED=0
XFWM4_GREEN=0
XFWM4_BLUE=0
XFWM4_START_POSITION="BOTTOM"
DESKTOP_ICON_SIZE=48
DESKTOP_FONT_SIZE=8
GTK_THEME=Xfce
XFWM4_THEME=Default
PANEL_PAGER=false
PANEL_USER=false
PANEL_REV_CLOCKSYSTRAY=true
ICONS_THEME="gnome"
ICONS_CUT_SIZES="256x256 scalable"
XTERM_CMD="xfce4-terminal"
NET_USE=BOTH
NET_USE_DHCP=on
NET_HOSTNAME=ts_*
NET_TELNETD_ENABLED=ON
TIME_ZONE=America/Sao_Paulo
NET_TIME_SERVER=us.pool.ntp.org
#NET_REMOTE_ACCESS_FROM="0.0.0.0"
TFTP_BLOCKSIZE=1024
BIND_MOUNT0="storage:/mnt/storage"
STORAGE_CONFIG1=/mnt/storage
USB_STORAGE_SYNC=on
LOCALE=en_US

**Comment by Thinstation** [comment]
It is an actual english keyboard

**Comment by l0s3rr** [comment]
Yes, why?

**Comment by Thinstation** [comment]
Idk. I don't even know anybody that uses that key.

**Comment by l0s3rr** [comment]
ThinStation can not play that key, right?

**Comment by Doncuppjr** [comment]
Not sure if that's a limitation of ThinStation. Maybe freerdp doesn't send that key. Maybe your locale isn't setup correctly. 
    On Monday, March 4, 2019, 3:30:39 AM PST, L0s3rr <notifications@github.com> wrote:  
 
 
ThinStation can not play that key, right?

**Comment by l0s3rr** [comment]
I've already tried using freerdp and rdesktop, and neither will, would you like to see my settings?

**Comment by Doncuppjr** [comment]
Does the key work in other distributions?

**Comment by l0s3rr** [comment]
I did not get to test in linux distributions this button, however, in all the windows I tested it did not work, if you tell me it's a limitation okay ...

**Comment by Doncuppjr** [comment]
So it doesn’t work anywhere?

**Comment by l0s3rr** [comment]
Exactly, I already tried using external keyboard and it also did not work.

**Comment by Doncuppjr** [comment]
I don’t understand. If it never works with any distribution, why are you reporting this issue here?

**Comment by l0s3rr** [comment]
I got it wrong, sorry, thinstation does not work, if you climb a Windows on the machine, it works.

**Comment by Thinstation** [comment]
I'm not sure how relevant this issue is to the project. Please let me know if you think this issue should be re-opened.
