### ISSUE TITLE
Update intel-microcode

### ISSUE THREAD

**Issue by Jello146** [Thinstation/thinstation#383]
Now used version 20140430
The current version is now 20180807a

I have problems on new processors from Intel with graphics.

I managed to update the microcode to version 20171117, but I cannot upgrade to 20180807a. Apparently you need to change the Pkgfile, but I do not know how to do this for thinstation.

Pkgfile:
name=intel-microcode
version=20180807a
trans=28087
release=1
source=(http://downloadmirror.intel.com/$trans/eng/microcode-$version.tgz
        LICENSE
        intel-microcode2ucode.c)

build() {
  cd $SRC
  gcc -Wall ${CFLAGS} -o intel-microcode2ucode intel-microcode2ucode.c
  ./intel-microcode2ucode ./microcode.dat

  install -d -m755 $PKG/lib/firmware/intel-ucode/
  cp intel-ucode/* $PKG/lib/firmware/intel-ucode/
  install -D -m644 LICENSE $PKG/lib/firmware/intel-ucode/.
}

Error:
=======> WARNING: Signature file not found, falling back to old md5sum checking.
=======> WARNING: Md5sum not found, creating new.
=======> Building '/ts/ports/binary-core/intel-microcode/intel-microcode#20180807a-1.pkg.tar.xz'.
bsdtar -p -o -C /ts/ports/binary-core/intel-microcode/work/src -xf /ts/ports/binary-core/intel-microcode/microcode-20180807a.tgz
cp LICENSE /ts/ports/binary-core/intel-microcode/work/src
cp intel-microcode2ucode.c /ts/ports/binary-core/intel-microcode/work/src
+ build
+ cd /ts/ports/binary-core/intel-microcode/work/src
+ gcc -Wall -O2 -pipe -D_FORTIFY_SOURCE=2 -mno-tls-direct-seg-refs -fstack-protector-strong -march=x86-64 -o intel-microcode2ucode intel-microcode2ucode.c
intel-microcode2ucode.c: In function 'main':
intel-microcode2ucode.c:133:3: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
   asprintf(&filename, "intel-ucode/%02x-%02x-%02x", family, model, stepping);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ ./intel-microcode2ucode ./microcode.dat
open ./microcode.dat: No such file or directory
=======> ERROR: Building '/ts/ports/binary-core/intel-microcode/intel-microcode#20180807a-1.pkg.tar.xz' failed.

Help!

**Comment by Doncuppjr** [comment]
Intel changed the format, it's no longer required to process the dat file into individual files after download. Pushed.
    On Sunday, March 3, 2019, 10:58:38 PM PST, Jello146 <notifications@github.com> wrote:  
 
 
Now used version 20140430
The current version is now 20180807a

I have problems on new processors from Intel with graphics.

I managed to update the microcode to version 20171117, but I cannot upgrade to 20180807a. Apparently you need to change the Pkgfile, but I do not know how to do this for thinstation.

Pkgfile:
`# Description: Thinstation essential package

URL: http://www.thinstation.org

Maintainer: Donald A. Cupp Jr. (don cupp jr at ya hoo dot com)

name=intel-microcode
version=20180807a
trans=28087
release=1
source=(http://downloadmirror.intel.com/$trans/eng/microcode-$version.tgz
LICENSE
intel-microcode2ucode.c)

build() {
cd $SRC
gcc -Wall ${CFLAGS} -o intel-microcode2ucode intel-microcode2ucode.c
./intel-microcode2ucode ./microcode.dat

install -d -m755 $PKG/lib/firmware/intel-ucode/
cp intel-ucode/* $PKG/lib/firmware/intel-ucode/
install -D -m644 LICENSE $PKG/lib/firmware/intel-ucode/.
}
Error:=======> WARNING: Signature file not found, falling back to old md5sum checking.
=======> WARNING: Md5sum not found, creating new.
=======> Building '/ts/ports/binary-core/intel-microcode/intel-microcode#20180807a-1.pkg.tar.xz'.
bsdtar -p -o -C /ts/ports/binary-core/intel-microcode/work/src -xf /ts/ports/binary-core/intel-microcode/microcode-20180807a.tgz
cp LICENSE /ts/ports/binary-core/intel-microcode/work/src
cp intel-microcode2ucode.c /ts/ports/binary-core/intel-microcode/work/src
   
   - build
   - cd /ts/ports/binary-core/intel-microcode/work/src
   - gcc -Wall -O2 -pipe -D_FORTIFY_SOURCE=2 -mno-tls-direct-seg-refs -fstack-protector-strong -march=x86-64 -o intel-microcode2ucode intel-microcode2ucode.c   
intel-microcode2ucode.c: In function 'main':   
intel-microcode2ucode.c:133:3: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]   
asprintf(&filename, "intel-ucode/%02x-%02x-%02x", family, model, stepping);   
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   - ./intel-microcode2ucode ./microcode.dat   
open ./microcode.dat: No such file or directory   
=======> ERROR: Building '/ts/ports/binary-core/intel-microcode/intel-microcode#20180807a-1.pkg.tar.xz' failed.   
`

Help!

**Comment by Jello146** [comment]
Thank you!

I started collecting some ports from here https://crux.nu/ports/crux-3.4/.
Are they compatible with thinstation?
Why are they not used in thinstation?


I still do not understand what the module? I understand what a package or port is, but I don’t understand what a module is.
Let me explain if I need to collect --allmodules after updating the microcode, or the modules are old, but the libraries and ucode sets have changed.

Thanks again for the support.

**Comment by Doncuppjr** [comment]
Crux ports are compatible with TS. I don’t include all crux ports because I don’t use them all, and all current ports are compiled as proof of compatibility with each other.
Most modules are scanned for needed firmware. ucode files are slightly different in that their loading is dependent on the CPU. param allfirmware trueWill get them all on there for an hwlister run.


Sent from Yahoo Mail for iPhone


On Monday, March 4, 2019, 9:49 PM, Jello146 <notifications@github.com> wrote:


Thank you!

I started collecting some ports from here https://crux.nu/ports/crux-3.4/.
Are they compatible with thinstation?
Why are they not used in thinstation?

I still do not understand what the module? I understand what a package or port is, but I don’t understand what a module is.
Let me explain if I need to collect --allmodules after updating the microcode, or the modules are old, but the libraries and ucode sets have changed.

Thanks again for the support.

**Comment by Jello146** [comment]
Okay, I'll try
