### ISSUE TITLE
realtek 8168 thinstation doesn't work

### ISSUE THREAD

**Issue by l0s3rr** [Thinstation/thinstation#384]
Good morning, are you okay?

I'm using a PXE image on multiple machines, it's all working, however, I have a DELL GAMER laptop, and it has this "realtek 8168" network card, when I boot from PXE, thinstation is locking the machine and not is booting up, could you help me?

**Comment by Doncuppjr** [comment]
How big is the image?   On Monday, March 4, 2019, 3:54:26 AM PST, L0s3rr <notifications@github.com> wrote:  
 
 
Good morning, are you okay?

I'm using a PXE image on multiple machines, it's all working, however, I have a DELL GAMER laptop, and it has this "realtek 8168" network card, when I boot from PXE, thinstation is locking the machine and not is booting up, could you help me?

**Comment by l0s3rr** [comment]
The image contain 148 Mb

**Comment by Thinstation** [comment]
try making some smaller images. Try the tiny build with your machine profile. Sometimes there is a weird max boot file size.

**Comment by l0s3rr** [comment]
I already tried with the minimum settings but the same thing happened, and the PXE server is working normally.

**Comment by l0s3rr** [comment]
[t_video5181567391934447727.zip](https://github.com/Thinstation/thinstation/files/2927289/t_video5181567391934447727.zip)
Here's a video of what's happening.

**Comment by l0s3rr** [comment]
I got it wrong, sorry, thinstation does not work, if you climb a Windows on the machine, it works.

**Comment by Thinstation** [comment]
Your chainloading? Why? You probably ran out of RAM on your memdisk.

**Comment by l0s3rr** [comment]
I could not understand you, could you explain it again?

**Comment by Thinstation** [comment]
Don't chainload.

**Comment by l0s3rr** [comment]
And how do I do that?

**Comment by Thinstation** [comment]
Make a proper usb thumbdrive, don't chainload the iso.
mkmbrdrv -o /build/boot-images/syslinux -p d:0:boot <drive ex. /dev/sdb>

**Comment by l0s3rr** [comment]
Okay, but I'm using the image via PXE, how will I use this command if I do not have any external devices besides a network cable?

**Comment by Thinstation** [comment]
If your using pxe, then you need to use the file layout under /build/boot-images/pxe

**Comment by l0s3rr** [comment]
I already tried with the format of the pxe files but the problem persisted.

**Comment by Thinstation** [comment]
Which version of lpxelinux are you using?

**Comment by l0s3rr** [comment]
last version.

**Comment by z3xddd** [comment]
for me same problem ocorred.

**Comment by Thinstation** [comment]
Don't chainload. That's completely unnecessary.
