### ISSUE TITLE
6.1 stable build error with background image

### ISSUE THREAD

**Issue by mcsn747** [Thinstation/thinstation#390]
Hello!
I saw the build aborted if set in build.conf parameter
`param desktop file:./backgrounds/Hive_Lite.jpg `
and
`param fastboot       true `

```
Dependencies are clean!
Boot Logo Disabled. Removing splash package.

Adding and install non-distributable binaries

Adding Packages to Filetree

Setting Passwords
Setting basepath
Setting baseurl
Checking for Key File
Checking for Desktop background
Using file:./backgrounds/Hive_Lite.jpg as desktop background

Can't determine installation type, should be http(s): or ftp(s) or file:
Build Aborted

```
If I comment fastboot then build finish successfully. 

Also, param bootlogo defined in conf as true. At startup,  there is no background image showed.

I think this is a bug.

**Comment by Se7ven** [comment]
`param fastboot true` doesn't concern to any Background options.

**Comment by Thinstation** [comment]
I think you must have another issue with your build.conf or something else is wrong.
I get these results.

Dependencies are clean!
Boot Logo Disabled. Removing splash package.

Adding and install non-distributable binaries


Adding Packages to Filetree

Setting Passwords
Setting basepath
Setting baseurl
Checking for Key File
Checking for Desktop background
Using file:./backgrounds/Hive_Lite.jpg as desktop background
Checking for Known Hosts File
Checking for ICA encryption support
Checking for Debug Verbosity
Checking for Halt on Error Override

Adding locales to archive.

and it continues to completion.

**Comment by mcsn747** [comment]
After I re-download stable git, the error does not occur.
