### ISSUE TITLE
Non US codepage issue

### ISSUE THREAD

**Issue by Se7ven** [Thinstation/thinstation#391]
https://github.com/Thinstation/thinstation/blob/c54d8b4f88a2a86c5b175c310796f755bdb68d4b/ts/build/packages/base/etc/init.d/profile-setup#L74

`cat -v` breaks non US encoding. It's adding M- notation with any UTF-8 character.

I suggest use 
`sed -e 's/^M//g' $filename >> $TS_USER 2> /dev/null` to remove CR/LF.

**Comment by Thinstation** [comment]
I think I have all of these fixed.
