### ISSUE TITLE
Sleep Option Rdesktop/FreeRDP

### ISSUE THREAD

**Issue by l0s3rr** [Thinstation/thinstation#393]
Good morning, how are you?

I would like to take a question, I have the thinstation configured to upload rdesktop / freerdp automatically, I just wonder if there is a way to put it automatically after 5 seconds?

I researched but did not find much ..

Thankful.

**Comment by Thinstation** [comment]
I'm not quite sure what your asking for here.

**Comment by l0s3rr** [comment]
I have the thinstation compiled with the function that when it uploads the image it automatically connects in an RDP, however I would like to know if it has how I do that after the upload thinstation, it connect in RDP after a certain time, managed to understand ?

**Comment by Thinstation** [comment]
If your using xfwm, you can add the xfce4-power-manager package and maybe change settings in 
/build/packages/xfce4-power-manager/etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml to suit your needs.

**Comment by Thinstation** [comment]
Otherwise your have the acpi package to manage idle events.

**Comment by l0s3rr** [comment]
Ok I understand, another question, is it possible for me to create a script in bash and put to start together with ThinStation?

**Comment by Thinstation** [comment]
Yes. We use systemd, so create a service.

**Comment by l0s3rr** [comment]
OK, Where can I add the service?

**Comment by Thinstation** [comment]
Make a new package with all the service elements.

**Comment by l0s3rr** [comment]
Sorry but I do not get it, do I create the service on my local machine, or do I create it and play in some directory?

**Comment by Doncuppjr** [comment]
You will need to create a package in /build/packages that has the file/folder structure you need 


Sent from Yahoo Mail for iPhone


On Thursday, March 21, 2019, 11:16 AM, L0s3rr <notifications@github.com> wrote:


Sorry but I do not get it, do I create the service on my local machine, or do I create it and play in some directory?

**Comment by l0s3rr** [comment]
I need to build a binaries files or i need to create a script and place it in this directory?

**Comment by Thinstation** [comment]
You can make a script. Then add that package to your build.

**Comment by l0s3rr** [comment]
ok, thanks for attencion.
