### ISSUE TITLE
Demo LiveCD cannot boot

### ISSUE THREAD

**Issue by maa7** [Thinstation/thinstation#396]
Hello,

Demo LiveCD (https://sourceforge.net/projects/thinstation/files/LiveCD/TS-Multiclient-Desktop-LiveCD-Demo.iso) cannot boot:
![img_ts_boot](https://user-images.githubusercontent.com/45234995/54925866-3f3cae80-4f20-11e9-8a28-2ebb36d8e4a0.jpg)

**Comment by Thinstation** [comment]
Fixed.
