### ISSUE TITLE
TS 6.1 Image for PXE boot is very big.

### ISSUE THREAD

**Issue by imax78** [Thinstation/thinstation#397]
Hello, 
When I try to build a TS 6.1 image for PXE boot, I get image more than 400 MB.
The image contains lib.squash file, that make it biger.
What is lib.squash?
Can I disable lib.squash for a smaller image size?

**Comment by Doncuppjr** [comment]
lib.squash contains all the files you need to run your application.... a browser, the desktop, vmview. You could remove it, but then you would only get past init and dropped to a cli with very limited resources.
You need it. How many applications did you include?  Reduce locales, apps, modules and firmware, the size will go down.


Sent from Yahoo Mail for iPhone


On Wednesday, March 27, 2019, 1:01 AM, imax78 <notifications@github.com> wrote:


Hello,
When I try to build a TS 6.1 image for PXE boot, I get image more than 400 MB.
The image contains lib.squash file, that make it biger.
What is lib.squash
Can I disable lib.squash for a smaller image size?
