### ISSUE TITLE
ThinStation not working v6.1

### ISSUE THREAD

**Issue by z3xddd** [Thinstation/thinstation#402]
Good morning,

I already compile the .iso but when the image went up some erros occored.

![image](https://user-images.githubusercontent.com/49065131/55336488-5ffe8a00-5473-11e9-8cff-36b6315a8769.png)

This file thinstation.conf.user i already create and the directory thinstation.profile also.

Can you help me?

**Comment by Thinstation** [comment]
You made an image without any explicit contents. Only the absolute necessities were included.
