### ISSUE TITLE
Download url for 2X Client

### ISSUE THREAD

**Issue by sazhyk** [Thinstation/thinstation#403]
Hi! Please change link for download 2X Client in `ts/build/build.urls` from
`param 2xurl             http://www.2x.com/downloads/AppServer-LoadBalancer/2XClient.tar.bz2`
to 
`param 2xurl             https://download.parallels.com/ras/v16/16.5.3.20735/RASClient-16.5.20735_i386.tar.bz2`
for download latest version of 2X RAS Client.

**Comment by Doncuppjr** [comment]
Why?

**Comment by sazhyk** [comment]
This is `./build --allmodules` log

> INSTALLING 2X
> 
> Downloading from Net.....
> Using system proxy, or not using any proxy to connect to Internet.
> WARNING: timestamping does nothing in combination with -O. See the manual
> for details.
> 
> --2019-04-11 07:09:05--  http://www.2x.com/downloads/AppServer-LoadBalancer/2XClient.tar.bz2
> Resolving www.2x.com... 195.214.234.136
> Connecting to www.2x.com|195.214.234.136|:80... connected.
> HTTP request sent, awaiting response... 301 Moved Permanently
> Location: https://www.parallels.com/products/ras/remote-application-server/ [following]
> --2019-04-11 07:09:05--  https://www.parallels.com/products/ras/remote-application-server/
> Resolving www.parallels.com... 104.16.48.63, 104.16.47.63
> Connecting to www.parallels.com|104.16.48.63|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: unspecified [text/html]
> Saving to: './wget_tmp/2XClient.tar.bz2'
> 
> ./wget_tmp/2XClient.tar.bz2                         [ <=>                                                                                                    ]  82.18K  --.-KB/s    in 0.05s   
> 
> 2019-04-11 07:09:06 (1.71 MB/s) - './wget_tmp/2XClient.tar.bz2' saved [84151]
> 
> bzip2: ./wget_tmp/2XClient.tar.bz2 is not a bzip2 file.
> tar: wget_tmp/2XClient.tar: Cannot open: No such file or directory
> tar: Error is not recoverable: exiting now
> cp: cannot stat './wget_tmp/opt/2X/Client/bin/2XClient': No such file or directory
> cp: cannot stat './wget_tmp/opt/2X/Client/bin/appserverclient': No such file or directory
> cp: cannot stat './wget_tmp/opt/2X/Client/lib/lib*': No such file or directory
> 
> Error has occured while installing package 2x
> Build Aborted

_On my Ubuntu 18.04_
```
user@dir:# tar xjf 2XClient.tar.bz2 
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

The archive _2XClient.tar.bz2_ was saved but it is broken.
This [link](https://www.parallels.com/products/ras/download/client/) has a list of downloads. Probably 2X developers have changed the addresses of downloaded files. (Sorry for my English)

**Comment by Thinstation** [comment]
I updated the url, but I think this package is likely still very out of date. Anyone want to give it the love it really needs?
