### ISSUE TITLE
Update latest versions

### ISSUE THREAD

**Issue by trentasis** [Thinstation/thinstation#404]
Hi,

I have checked and some packages are a little old (from 5.5), and would be great upgrade to latest versions:
- freerdp
- rdesktop
- pcsc-lite (pcscd)
- ccidreader
- ocsinventory

Is this possible?

Thanks

**Comment by Thinstation** [comment]
Just the latest release?.....git version? That's a pack of problem children.

**Comment by trentasis** [comment]
Correct, latest stable version 6.1, evaluating upgrade from5.5 to 6.1, It seems that this version contains a version of this packages with some bugs

**Comment by trentasis** [comment]
latest 6.1, from git, master branch

Missatge de Thinstation <notifications@github.com> del dia dc., 17 d’abr.
2019 a les 1:16:

**Comment by Thinstation** [comment]
Not sure which bugs your talking about. Everyone seems very happy with it.

**Comment by trentasis** [comment]
Hi,

Issues related with smartcards with rdesktop and freerdp, latest versions with multiple fixes related with this, and also ccid and pcscd
Is this possible?
