### ISSUE TITLE
6.1.1 no spice?

### ISSUE THREAD

**Issue by denyxi** [Thinstation/thinstation#405]

**Comment by Thinstation** [comment]
It's in there. What issue are you having with it?

**Comment by denyxi** [comment]
thinstation/ts/build/build.conf.example There is no spice configuration in it.，
Can I support the SPICE connection of ovirt?

**Comment by Doncuppjr** [comment]
The packages are there, maybe just the line in .conf is missing. Put it back in.


Sent from Yahoo Mail for iPhone


On Thursday, April 25, 2019, 1:15 AM, jhxhj <notifications@github.com> wrote:


thinstation/ts/build/build.conf.example There is no spice configuration in it.，
Can I support the SPICE connection of ovirt?

**Comment by Thinstation** [comment]
Added package to build.conf.example
