### ISSUE TITLE
SCREEN_BLANK_TIME does not sets

### ISSUE THREAD

**Issue by ghost** [Thinstation/thinstation#406]
When i am set SCREEN_BLANK_TIME in buildtime config file, it not applyed and in power manager it stil a set to 10min and screen turns off after that time.

in /etc/X11/xorg.conf.d/10-serverlayout.conf it sets to 0 as expected, but no effect.

How get it work as expected?

**Comment by Thinstation** [comment]
the xfwm4 power manager really only respects 
SCREEN_OFF_TIME
SCREEN_SUSPEND_TIME

**Comment by ghost** [comment]
it uses 
```xml
<property name="blank-on-ac" type="int" value="10"/>
```
from _~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml_
but SCREEN_BLANK_TIME does not sets that value.

may be need add that in /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml
when skel copied to profile?

After line
https://github.com/Thinstation/thinstation/blob/68a8de557c21952de94c91c3139a0248d114cae3/ts/build/packages/base/sbin/session#L30

insert some code that correct _xfce4-power-manager.xml_ file 

and SCREEN_BLANK_TIME var exists in that file?

or in that time https://github.com/Thinstation/thinstation/blob/32791919b7ec48179907ff078ed7ced67c2edb0b/ts/build/packages/xorg7/etc/init.d/xconf#L165

exists file _~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml_

**Comment by Thinstation** [comment]
O.k., it's true that we are not setting that, but isn't it kind of redundant at this point? Blank was a power management feature of CRT's and the era of analog signals. I'm not sure that modern displays do anything on vblank.

**Comment by ghost** [comment]
When i am using Nettop pc with VGA and xfwm4 desktop - screen is turn off after 10min, and needs click mouse or kb to on it or open power manager any restart and set first slider("blank screen") to 0 again.

I am developing extended kiosk pc - if it screen be blank - user may think - "it does not working".

May be HDMI is not "Blanks" but i am not sure about that. 

In what time i am need configure xfce4-power-manager ? At xconf or at session runs?

**Comment by Doncuppjr** [comment]
Allrighty, pushed a change. Let me know if it works for ya.
    On Wednesday, April 24, 2019, 9:21:58 PM PDT, NeiroNx <notifications@github.com> wrote:  
 
 
When i am using Nettop pc with VGA and xfwm4 desktop - screen is turn off after 10min, and needs click mouse or kb to on it or open power manager any restart and set first slider("blank screen") to 0 again.

I am developing extended kiosk pc - if it screen be blank - user may think - "it does not working".

May be HDMI is not "Blanks" but i am not sure about that.
