### ISSUE TITLE
ThinStation HardDisk

### ISSUE THREAD

**Issue by z3xddd** [Thinstation/thinstation#407]
Hi,

I need to install an ISO of custom thinstation and would like to know if it is possible to install it on the hard disk and how should I perform this installation?

**Comment by Thinstation** [comment]
Here is a good place to start.

https://github.com/Thinstation/thinstation/wiki/Deployment#booting-with-syslinux

**Comment by z3xddd** [comment]
Okay, I tested it now on a VM and I got this error, I'm letting something go?

![image](https://user-images.githubusercontent.com/49065131/56968517-a6f6a280-6b39-11e9-9f5b-8d41697b5c5e.png)

**Comment by Thinstation** [comment]
I don’t know how you got there. What’s was your procedure?

**Comment by z3xddd** [comment]
I have a vm with a debian installed in which I compile my thinstation images, so I added a new disk, I ran the mkmbrdrv -o / build / boot-images / syslinux -pd: 0: boot / dev / sdb command, done that, I gave boot by this HD and this error occurred to me.

**Comment by Thinstation** [comment]
Something wrong with your van config. Make sure it’s 64bit with PAE

**Comment by z3xddd** [comment]
ok, maybe this error occurred because I'm doing this test on a VM?

**Comment by Thinstation** [comment]
Depends on how you configured the VM and what modules you included in your
build.

**Comment by z3xddd** [comment]
Okay, I checked this out now and it already includes the VirtualBox module and my VM is created as 64Bits, should I create the same as 32?

**Comment by Thinstation** [comment]
No, is PAE enabled?

**Comment by z3xddd** [comment]
Yes, PAE is enabled.

**Comment by Doncuppjr** [comment]
Try an —allmodules build.


Sent from Yahoo Mail for iPhone


On Tuesday, April 30, 2019, 7:37 AM, z3xdd <notifications@github.com> wrote:


Yes, PAE is enabled.

**Comment by z3xdd** [comment]
> 
> Try an —allmodules build. Sent from Yahoo Mail for iPhone On Tuesday, April 30, 2019, 7:37 AM, z3xdd <notifications@github.com> wrote: Yes, PAE is enabled. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

https://github.com/Thinstation/thinstation/issues/407#issuecomment-487984437

**Comment by z3xddd** [comment]
> 
> Try an —allmodules build. Sent from Yahoo Mail for iPhone On Tuesday, April 30, 2019, 7:37 AM, z3xdd <notifications@github.com> wrote: Yes, PAE is enabled. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

I just tested and the same problem occurred.
