### ISSUE TITLE
ThinStation boot with GRUB2

### ISSUE THREAD

**Issue by z3xddd** [Thinstation/thinstation#408]
Hi

I installed on a local machine a Debian 9 and I configured a second option in Grub to boot into thinstation .iso, however the following error is running:

![image](https://user-images.githubusercontent.com/49065131/56982416-a53bd780-6b57-11e9-89d6-532315943bbb.png)

Follows also a print of how is my configuration of grub:

![image](https://user-images.githubusercontent.com/49065131/56982631-22ffe300-6b58-11e9-9afa-f2b236bf9b5c.png)

Can help me? Is it possible to boot this .iso with GRUB2?

**Comment by Thinstation** [comment]
Maybe not enough ram. I doubt the standard build would chainload.

**Comment by z3xddd** [comment]
Hmm, this machine contain 2 GB memory RAM.. Are you telling me then that it is not possible?

**Comment by Thinstation** [comment]
In the vm.

**Comment by z3xddd** [comment]
hmm, I understand, thanks for the response.

**Comment by Doncuppjr** [comment]
You could disable fastboot, change the initrdcmd back to squashfs, and add the overlay package for old school live cd  behavior


Sent from Yahoo Mail for iPhone


On Tuesday, April 30, 2019, 11:09 AM, z3xdd <notifications@github.com> wrote:


Closed #408.
