### ISSUE TITLE
ThinStation HardDisk IDE

### ISSUE THREAD

**Issue by z3xddd** [Thinstation/thinstation#410]
Hi,

I need to install ThinStation on a computer that contains an HD IDE and I can not take the hd from the machine, plug in another one and run the command mkmbrdrv -o / build / boot-images / syslinux -p d: 0: boot <drive ex. / dev / sdb> for example.

How do I get a USB to install a custom ThinStation ISO on any machine?

**Comment by z3xddd** [comment]
Does this still work for what I need?

http://thinstation.sourceforge.net/syslinux-hd.html

**Comment by Doncuppjr** [comment]
I am fairly sure that’s outdated. 
There are several ways to make ThinStation deploy’able. You really need to way the multitude of options against your time and money resources.


Sent from Yahoo Mail for iPhone


On Wednesday, May 8, 2019, 10:46 AM, z3xdd <notifications@github.com> wrote:


Does this still work?

http://thinstation.sourceforge.net/syslinux-hd.html

**Comment by z3xddd** [comment]
Could you please tell me some of these ways?

**Comment by Thinstation** [comment]
What I understand about deployment can’t be summarized. It’s been a focus
of study, and can only really be consulted.

**Comment by z3xddd** [comment]
OK, I understand, I'm going to try to perform the deployment with the document I sent above, if it works I'll respond in this resport.

**Comment by Thinstation** [comment]
ThinStation now supports making isohybrid images. 

make sure that 
param bootimages has at least systemd-boot-iso or refind-iso
and then use either the iso from /build/boot-images/systemd-boot-iso or refind-iso

you can dd them to a thumb drive or hard drive.

**Comment by chirag90851** [comment]
> bootimages

Hi , It's work for you ?
