### ISSUE TITLE
Including package extensions breaks vi in 6.1.1

### ISSUE THREAD

**Issue by streetworkr** [Thinstation/thinstation#413]
Including package extensions in v6.1.1 makes vi fail:

`
# w/o package extensions

$ which vi
/bin/vi

$ ls -lag /bin/vi /bin/busybox
-rwsr-xr-x    1 root        714360 May 10 02:00 /bin/busybox
lrwxrwxrwx    1 root            12 May 10 02:00 /bin/vi -> /bin/busybox

$ vi x.x
$

# with package extensions

$ which vi
/bin/vi

$ ls -lag /bin/vi /bin/busybox
-rwsr-xr-x    1 root        714360 May 10 02:00 /bin/busybox
lrwxrwxrwx    1 root             7 May 10 02:00 /bin/vi -> busybox

$ vi x.x
Segmentation fault
$
`

**Comment by Doncuppjr** [comment]
Interesting. I'll take a look at full sized vi, which is what is included when you add package extensions.
    On Friday, May 10, 2019, 1:05:24 AM PDT, streetworkr <notifications@github.com> wrote:  
 
 
Including package extensions in v6.1.1 makes vi fail:

`

w/o package extensions

$ which vi
/bin/vi

$ ls -lag /bin/vi /bin/busybox
-rwsr-xr-x 1 root 714360 May 10 02:00 /bin/busybox
lrwxrwxrwx 1 root 12 May 10 02:00 /bin/vi -> /bin/busybox

$ vi x.x
$

with package extensions

$ which vi
/bin/vi

$ ls -lag /bin/vi /bin/busybox
-rwsr-xr-x 1 root 714360 May 10 02:00 /bin/busybox
lrwxrwxrwx 1 root 7 May 10 02:00 /bin/vi -> busybox

$ vi x.x
Segmentation fault
$
`

**Comment by Thinstation** [comment]
Fixed
