### ISSUE TITLE
Extra quotes around username in session connect dialog in 6.1.1

### ISSUE THREAD

**Issue by streetworkr** [Thinstation/thinstation#414]
The gtkdialog connection dialog for new sessions has an annoying bug.

Every time you choose to reconnect to the remote system a pair of single quotes
is put around the username, which of course makes the login fail.
Unless you manually remove the quotes, an additional pair of quotes is put 
around the username on every reconnect.

I guess this happens somewhere in /etc/dialog.functions .

**Comment by Doncuppjr** [comment]
Ill look into that.
    On Friday, May 10, 2019, 1:19:47 AM PDT, streetworkr <notifications@github.com> wrote:  
 
 
The gtkdialog connection dialog for new sessions has an annoying bug.

Every time you choose to reconnect to the remote system a pair of single quotes
is put around the username, which of course makes the login fail.
Unless you manually remove the quotes, an additional pair of quotes is put
around the username on every reconnect.

I guess this happens somewhere in /etc/dialog.functions .

**Comment by Thinstation** [comment]
I was not able to reproduce this error. Is there anything unusual about the username?

**Comment by streetworkr** [comment]
Steps to reproduce the issue:

1, RECONNECT_PROMPT=On
2. Configure a FreeRDP Session
3. Enter a username, say john. Connect.
4. Click yes when prompted to reconnect 
5. Username is now 'john' (enclosed in single quotes)

**Comment by Thinstation** [comment]
Fixed.
