### ISSUE TITLE
How to get information about OS release?

### ISSUE THREAD

**Issue by mcsn747** [Thinstation/thinstation#416]
Hello!
We use Lansweeper for network inventory.
Lansweeper parse previous releases, 5.5 for example, as "ThinStation 5.5 VGER", yet 
Thinstation 6.1 detect as "GNU/Linux". 
I suppose Lansweeper get OS info from file /etc/release or /etc/os-release. I ask to return those files in build.
Thanks!

**Comment by Thinstation** [comment]
lsb_release was not working correctly. This might be fixed now.
