### ISSUE TITLE
RDP with black wallpaper

### ISSUE THREAD

**Issue by z3xddd** [Thinstation/thinstation#417]
Hi everyone, all right?

I am using thinstation to automatically connect to my TS server and when the same connects the wallpaper is getting black.

I think I'm letting something go, could you help me?

**Comment by Thinstation** [comment]
Did you pass the argument to show the wallpaper as an option to your remote desktop application?

**Comment by z3xddd** [comment]
Hi,

Here is my thinstation.conf.buildtime:

AUDIO_LEVEL=90
MIC_LEVEL=0
SESSION_0_TYPE=xfwm4
SESSION_0_AUTOSTART=on
SESSION_1_TYPE=rdesktop
SESSION_1_RDESKTOP_SERVER=172.22.3.211
SESSION_1_RDESKTOP_OPTIONS="-d ezex -a 16"
SESSION_1_AUTOSTART=on.
RECONNECT_PROMPT=OFF
XFWM4_COMPOSITING=true
XFWM4_BRIGHTNESS="-33"
XFWM4_RED=0
XFWM4_GREEN=0
XFWM4_BLUE=0
XFWM4_START_POSITION="BOTTOM"
DESKTOP_ICON_SIZE=48
DESKTOP_FONT_SIZE=8
DESKTOP_SHOWTRASH=false
DEKSTOP_SHOWHOME=false
DESKTOP_SHOWREMOVEABLE=true
DESKTOP_SHOWFILESYSTEM=false
GTK_THEME=Xfce
XFWM4_THEME=Default
PANEL_PAGER=false
PANEL_USER=false
PANEL_REV_CLOCKSYSTRAY=true
ICONS_THEME="gnome"
ICONS_CUT_SIZES="256x256 scalable"
XTERM_CMD="xfce4-terminal"
NET_USE=BOTH
NET_USE_DHCP=on
NET_HOSTNAME=ts_*
NET_TELNETD_ENABLED=ON
TIME_ZONE=America/Los_Angeles
NET_TIME_SERVER=us.pool.ntp.org
NET_REMOTE_ACCESS_FROM="0.0.0.0"
TFTP_BLOCKSIZE=1024
BIND_MOUNT0="storage:/mnt/storage"
STORAGE_CONFIG1=/mnt/storage
USB_STORAGE_SYNC=on
LOCALE=pt_BR
MOUNT_0="LABEL=boot     /boot           auto    x-mount.mkdir,defaults  0       0"
MOUNT_1="LABEL=home     /root           auto    x-mount.mkdir,defaults  0       0"
MOUNT_2="LABEL=swap     swap            swap    defaults        0       0"
SET_RESOLUTION_MULTIMONITOR_EXPAND='mirror'
SET_RESOLUTION_MULTIMONITOR_AUTOSCALE='scale'

Something is wrong?

**Comment by Doncuppjr** [comment]
Try looking at the rdesktop options, and see if there is anything about wallpapers.


Sent from Yahoo Mail for iPhone


On Thursday, May 16, 2019, 4:42 AM, z3xdd <notifications@github.com> wrote:


Hi,

Here is my thinstation.conf.buildtime:

AUDIO_LEVEL=90
MIC_LEVEL=0
SESSION_0_TYPE=xfwm4
SESSION_0_AUTOSTART=on
SESSION_1_TYPE=rdesktop
SESSION_1_RDESKTOP_SERVER=172.22.3.211
SESSION_1_RDESKTOP_OPTIONS="-d ezex -a 16"
SESSION_1_AUTOSTART=on.
RECONNECT_PROMPT=OFF
XFWM4_COMPOSITING=true
XFWM4_BRIGHTNESS="-33"
XFWM4_RED=0
XFWM4_GREEN=0
XFWM4_BLUE=0
XFWM4_START_POSITION="BOTTOM"
DESKTOP_ICON_SIZE=48
DESKTOP_FONT_SIZE=8
DESKTOP_SHOWTRASH=false
DEKSTOP_SHOWHOME=false
DESKTOP_SHOWREMOVEABLE=true
DESKTOP_SHOWFILESYSTEM=false
GTK_THEME=Xfce
XFWM4_THEME=Default
PANEL_PAGER=false
PANEL_USER=false
PANEL_REV_CLOCKSYSTRAY=true
ICONS_THEME="gnome"
ICONS_CUT_SIZES="256x256 scalable"
XTERM_CMD="xfce4-terminal"
NET_USE=BOTH
NET_USE_DHCP=on
NET_HOSTNAME=ts_*
NET_TELNETD_ENABLED=ON
TIME_ZONE=America/Los_Angeles
NET_TIME_SERVER=us.pool.ntp.org
NET_REMOTE_ACCESS_FROM="0.0.0.0"
TFTP_BLOCKSIZE=1024
BIND_MOUNT0="storage:/mnt/storage"
STORAGE_CONFIG1=/mnt/storage
USB_STORAGE_SYNC=on
LOCALE=pt_BR
MOUNT_0="LABEL=boot /boot auto x-mount.mkdir,defaults 0 0"
MOUNT_1="LABEL=home /root auto x-mount.mkdir,defaults 0 0"
MOUNT_2="LABEL=swap swap swap defaults 0 0"
SET_RESOLUTION_MULTIMONITOR_EXPAND='mirror'
SET_RESOLUTION_MULTIMONITOR_AUTOSCALE='scale'

Something is wrong?
