### ISSUE TITLE
How to upgrade Thinstation?

### ISSUE THREAD

**Issue by maa7** [Thinstation/thinstation#419]
Hello,
I have Thinstation installed from thinstation-6.1.1.tar.gz
Now i need upgrade it as described in https://github.com/Thinstation/thinstation/wiki/Updating-your-repository
but after
**git pull**
i get error:
_fatal: not a git repository (or any of the parent directories): .git_

**Comment by Doncuppjr** [comment]
Yeah, you will want to not use the tar.gz, and just clone with git.


Sent from Yahoo Mail for iPhone


On Tuesday, May 21, 2019, 12:41 AM, maa7 <notifications@github.com> wrote:


Hello,
I have Thinstation installed from thinstation-6.1.1.tar.gz
Now i need upgrade it as described in https://github.com/Thinstation/thinstation/wiki/Updating-your-repository
but after
git pull
i get error:
fatal: not a git repository (or any of the parent directories): .git

**Comment by maa7** [comment]
I need offline initial installation

**Comment by Thinstation** [comment]
Why??

**Comment by maa7** [comment]
some ip addresses are blocked in my country

**Comment by Doncuppjr** [comment]
Hmm, well it’s possible make offline git clones, but you need to make an initial clone online somewhere, and then use it as the source for an offline clone. 
You might have to work with tar balls... as a fallback. Our distribution method wasn’t really intended for your scenario.


Sent from Yahoo Mail for iPhone


On Tuesday, May 21, 2019, 8:38 AM, maa7 <notifications@github.com> wrote:


some ip addresses are blocked in my country

**Comment by maa7** [comment]
Maybe you can publish releases more often?
https://github.com/Thinstation/thinstation/releases

**Comment by Thinstation** [comment]
This should always be current.
https://github.com/Thinstation/thinstation/archive/6.2-Stable.tar.gz

**Comment by maa7** [comment]
Please give a link for always latest version 6.2.x
