### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by netrogue** [Thinstation/thinstation#420]
I just used TS-6.1.1-Install-0222.iso to create a build environment.
But installation failed, and the prompt is as follows：

During post install checks, we discovered /thinstation/setup-chroot: Missing Your installation is not likely to work.  Aborting! 

Would you help me?
Thank you so much.

**Comment by Thinstation** [comment]
Were you connected to the internet? Was your internet connection interrupted during installation?

**Comment by shNanChen** [comment]
I have the same problem.

```
git clone --depth 1 git://github.com/Thinstation/thinstation.git -b 6.1-Stable
Cloning into 'thinstation'...
remote: Enumerating objects: 11375, done.
remote: Counting objects: 100% (11375/11375), done.
remote: Compressing objects: 100% (8727/8727), done.
fatal: the remote end hung up unexpectedly63 MiB | 649.00 KiB/s   
fatal: early EOF
fatal: index-pack failed
```

**Comment by Thinstation** [comment]
That’s a github issue, not TS.
