### ISSUE TITLE
Sound issue #344 & #345 back ?

### ISSUE THREAD

**Issue by trezel** [Thinstation/thinstation#421]
Hi,
I got no sound in thinstation 6.1.
I used the workaround reported on posts 344 and 345 (comment lines in ts/build/build file), and sound works perfectly.
Does November's fix disappear ?

Thanks
E.T.

**Comment by trezel** [comment]
I looked at the push you did on November 26th, and the line you changed is back to its original shape (line  1229 in November, but 1195 today)

**Comment by Thinstation** [comment]
Not sure where you got your checkout, but those lines are still commented out. Try including pulseaudio

**Comment by trezel** [comment]
Hi,
I checked on the files I use (.tar.gz). I didn't realize this archive was a "frozen" version created in November 2018 (I thought it was regularly updated).
I downloaded the zip archive from github, and with up to date files, it works.
Thanks
E.T.
