### ISSUE TITLE
need to update atftp

### ISSUE THREAD

**Issue by triquichoque** [Thinstation/thinstation#422]
Having an issue trying to PXE boot. Image is kind of large and fails to boot with an atftpd error when trying to get the initrd file. The error is:
"Requested file to big, increase BLKSIZE"
Tried specifying a bigger BLKZISE but doesn't help. Found the following bug with atftpd affecting serving big files:
https://sourceforge.net/p/atftp/bugs/1/

Version v0.7.2 from 2019-04-21 seems to include a fix for downloading big files. 

How can I update the atftpd binary on DEVSTATION?
Tried compiling from source on DEVSTATION but seems to be missing compiler

current versions:
Thinstation 6.1.1
atftpd-0.7.1 (server)

**Comment by Doncuppjr** [comment]
I'll update and push

    On Monday, June 3, 2019, 10:21:43 AM PDT, triquichoque <notifications@github.com> wrote:  
 
 
Having an issue trying to PXE boot. Image is kind of large and fails to boot with an atftpd error when trying to get the initrd file. The error is:
"Requested file to big, increase BLKSIZE"
Tried specifying a bigger BLKZISE but doesn't help. Found the following bug with atftpd affecting serving big files:
https://sourceforge.net/p/atftp/bugs/1/

Version v0.7.2 from 2019-04-21 seems to include a fix for downloading big files.

How can I update the atftpd binary on DEVSTATION?
Tried compiling from source on DEVSTATION but seems to be missing compiler

current versions:
Thinstation 6.1.1
atftpd-0.7.1 (server)

**Comment by Thinstation** [comment]
Updated. 
Try updating your devstation and rebooting.

**Comment by triquichoque** [comment]
That was fast!
The problem still persists but I must be missing something. After updating Thinstation following:
cd thinstation
./setup-chroot
clean_chroot
exit
git pull

Inside the chroot I see the new versions of atftp and aftpd
atftp-0.7.2 (client)
atftp-0.7.2 (server)

but outside the chroot is still showing the older version
atftp-0.7.1 (client)
atftp-0.7.1 (server)

Is there another step to update DEVSTATION using the files from inside the chroot?

**Comment by Thinstation** [comment]
Yes., You need to click the Update DevStation button in the start menu

**Comment by triquichoque** [comment]
Running Update DevStation from the start menu downloaded around 400MB. Rebooted, ran the update again and shows its updated. Rebooted again but still shows atftp version 0.7.1
Ran the clean_chroot update process , rebooted but still shows the same old version

So its still showing the old version on the DEVSTATION OS but the newer version inside the chroot

**Comment by Thinstation** [comment]
Hmmm, my bad, I may have forgotten to run one little update.....after lunch.

**Comment by Thinstation** [comment]
Fixed?

**Comment by triquichoque** [comment]
Its updated now. Its showing v0.7.0.2
It takes more than 5 minutes to boot the client but at least now its actually PXE booting

In DEVSTATION the mesages log shows atftp serving the files but once it gets to initrd it gives 4 timeout erros each 5 seconds apart and then the error "client (192.168.x.x) not responding".  No more messages after that one.
Client side it sits on "Loading ::/boot/initrd" for around 5 minutes and then boots into thinstation. I'll do some more testing and try to confirm if its an atftp bug

thanks

**Comment by Thinstation** [comment]
There could be a multitude of factors at play here.
TFTP blocksize.
Network Speed.
Bridges.
STP
Adapter speed.
