### ISSUE TITLE
Issue with idesk... and workaround

### ISSUE THREAD

**Issue by trezel** [Thinstation/thinstation#425]
Hi,

I had a lot of weird behaviors using idesk : xterm didn't launch, firefox opened four tabs on file:///root/, background disappeared...
Trying to understand, I looked at the command associated to these icons in .idesk file, and I noticed command where shaping like this :
pkg fullscreen xterm "" ". . . ."
This kind of command work badly (but, for example pkg fullscreen xterm "" "" works well) 
Looking at the code in idesk.functions, I noticed line 95 was responsible for this : 
 if [ "$options" = "." ] ; then options= ; fi
I modified it like this :
 if [ -z "$(echo ${options} | sed 's/\.//g;s/ //g')"  ] ; then options= ; fi
and now it works well, now : icons get a well formed command and act like they should.
(maybe the same modification should be applied to the previous line).
I don't know if I'm the only one who met this kind of issue, and if this workaround is the best way to do, but if it can help...
E.T.

**Comment by Thinstation** [comment]
I needed to extend the options read a little bit, inline with changes made to other windowmanager packages. Thank you for reporting.
