### ISSUE TITLE
vmware view black screen

### ISSUE THREAD

**Issue by triquichoque** [Thinstation/thinstation#426]
Currently have an image booting via PXE with vmware view autostarting. When login in to a VDI pool it was getting stuck in a black screen. vmview logs showed an error loading SSL libraries. It seems vmview expects the SSL libraries to reside on /usr/lib/vmware and wont look in /usr/lib where the libraries are located. 
As a workaround copied the libraries libssl* from /lib to the vmview package lib folder and comented out the section of the vmview install script that deletes any libraries that already exists elsewhere
inside chroot:
cp /lib/libssl* /build/packages/vmview/lib/vmware
cp /lib/libcrypto* /build/packages/vmview/lib/vmware

lines 207 to 216 of /build/packages/vnview/build/install
#Delete libraries we already have in our build system
#for lib in ........
#.....
#done

deleted "installed" & "license" files so the package gets reinstalled. After a ./build vmview works and presents the VDI desktop

What would be the proper way to "fix" this?

thinstation 6.1
vmview 4.10

**Comment by Doncuppjr** [comment]
I was afraid that we would have to keep those libs. *sigh*, I'll comment out the lines.
    On Wednesday, June 5, 2019, 11:58:27 AM PDT, triquichoque <notifications@github.com> wrote:  
 
 
Currently have an image booting via PXE with vmware view autostarting. When login in to a VDI pool it was getting stuck in a black screen. vmview logs showed an error loading SSL libraries. It seems vmview expects the SSL libraries to reside on /usr/lib/vmware and wont look in /usr/lib where the libraries are located.
As a workaround copied the libraries libssl* from /lib to the vmview package lib folder and comented out the section of the vmview install script that deletes any libraries that already exists elsewhere
inside chroot:
cp /lib/libssl* /build/packages/vmview/lib/vmware
cp /lib/libcrypto* /build/packages/vmview/lib/vmware

lines 207 to 216 of /build/packages/vnview/build/install

Delete libraries we already have in our build system

#for lib in ........
#.....
#done

deleted "installed" & "license" files so the package gets reinstalled. After a ./build vmview works and presents the VDI desktop

What would be the proper way to "fix" this?

**Comment by Thinstation** [comment]
commented out the library thinning routine. lmk

**Comment by triquichoque** [comment]
No more black screen after the update. The libssl and libcrypto libraries are no longer deleted when reisntalling the vmview package. There are no more SSL erros on the vmview client logs and the VDI desktop loads without issues

Realted to this, I'm trying to enable smartcard authentication but it seems a pkcs11 library needs to be included. Tried creating the folder /build/pacakes/vmview/lib/vmware/vmview/pkcs11 and copying some lib files there but the folder gets removed and not copied to the bootable image. Also the setting VMVIEW_PKCS11 might have been renamed to VMVIEW_MODULE from what I could understand from an older forum post but couldnt find documentation on this (https://sourceforge.net/p/thinstation/mailman/message/34858688/)

Should I open a new ticket or is there documentation I'm missing?

**Comment by Thinstation** [comment]
I'm not sure when your trying to copy those file into vmview folder, but you should probably just make a separate package that contains the folder structure needed. This way, it won't get nuked if/when you reset the view package.

**Comment by triquichoque** [comment]
Thanks, I'll try creating a package with the needed directories and libraries.
For the pkcs11 conf entry, is it VMVIEW_PKCS11 or PKCS11_MODULE ?

**Comment by Thinstation** [comment]
I think the relevant piece of code looks like this.

if [ -n "$PKCS11_MODULE" ] && [ -e "$PKCS11_MODULE" ]; then
  mkdir -p /lib/vmware/view/pkcs11
  ln -s $PKCS11_MODULE /lib/vmware/view/pkcs11/
fi
