### ISSUE TITLE
bootfssize has no effect

### ISSUE THREAD

**Issue by ghost** [Thinstation/thinstation#429]
I have 2Gb RAM nettop and want to reduse memory usage,
using:
```
param bootfssize 20%
```
But it shows about 500 Mb free on ram disk - booth times (commented,50%,20%)
I want set it to 200Mb.

**Comment by ghost** [comment]
Just add memory to 4Gb. 
2Gb RAM Is too lower for chrome and desktop...
May be swap partition helps me, but i am do not know how to add it.

**Comment by Thinstation** [comment]
It depends on how you made your image, as to whether or not bootfssize has any effect. I think it's only relevant if you use squashfs initrd and overlay package.
