### ISSUE TITLE
install opensc port 

### ISSUE THREAD

**Issue by triquichoque** [Thinstation/thinstation#431]
Need to add opensc for smartcard authentication. 
Created directory 
`/ts/ports/components/opensc`

Doenloaded Pkgfile from 
`https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/opensc `

Adjusted by adding name , version, and release variables. Changed _sheetdir 
```
name=opensc
version=0.19.0
release=2
  _sheetdir=(/usr/share/sgml/docbook/xsl-ns-stylesheets)
```

Intalled by running 
`prt-get install opensc`

Installation fails with:
```
=======> Build result:
bsdtar: *: Cannot stat: No such file or directory
bsdtar: Error exit delayed from previous errors.
=======> ERROR: Building '/ts/ports/opt/opensc/opensc#0.19.0-2.pkg.tar.xz' failed.

-- Packages where install failed
opensc
```

Haven't been able to figure out why its failing with a bsderror. Am I missing a step or dependency?

[install-output.txt](https://github.com/Thinstation/thinstation/files/3294537/install-output.txt)
[Pkgfile.txt](https://github.com/Thinstation/thinstation/files/3294538/Pkgfile.txt)

**Comment by Thinstation** [comment]
You need source files.

**Comment by triquichoque** [comment]
How do you add source files to the port?
Looking for examples in other port directories couldn't find any reference to source files

**Comment by Thinstation** [comment]
You could try this for Pkgfile content.


[Pkgfile.txt](https://github.com/Thinstation/thinstation/files/3302177/Pkgfile.txt)

**Comment by triquichoque** [comment]
The opensc port is working now. Still need to manually copy and adjust the libraries for the vmview package but the Horizon view client is loading the smartcard now

It seems the opensc pkcs library must be named libopensc-pkcs11.so but gets built as opensc-pkcs11.so. 
[https://docs.vmware.com/en/VMware-Horizon-Client-for-Linux/4.10/horizon-client-linux-installation/GUID-6CB5F6EE-E7DC-4BF7-8E2A-4542E4A78182.html](https://docs.vmware.com/en/VMware-Horizon-Client-for-Linux/4.10/horizon-client-linux-installation/GUID-6CB5F6EE-E7DC-4BF7-8E2A-4542E4A78182.html)
So I'm copying opensc-pkcs11.so as libopensc-pkcs11.so in packaes/vmview/build/extra/lib/vmware/view/pkcs11

The parameter on thinstation.conf.builtime might need adjustment too but seems to be working with this:
`PKCS11_MODULE=/lib/opensc-pkcs11.so`

additionally, a copy of libssl.so under packages/vmview/build/extra/lib/vmware to solve the blackscreen issue from earlier



Thanks for the help
