### ISSUE TITLE
pavucontrol incompatible with Horizon Client 4.10

### ISSUE THREAD

**Issue by sky-flix** [Thinstation/thinstation#432]
Thinstation 6.1.1:
When adding the vmview 4.10 package to a build, pavucontrol stops working with 'symbol lookup error'. undefined symbol: _ZN4Glib17SignalProxyNormal13connect_impl_EbON4sigc9slot_baseEb

I have not yet tried downgrading to an earlier release to see if that corrects the problem.

**Comment by sky-flix** [comment]
Horizon Client 4.6 does not exhibit this problem. Will also test 4.7, 4.8, and 4.9

**Comment by Thinstation** [comment]
try removing build/packages/vmview/build/extra/etc/ld.so.conf.d/vmview.conf , 
then running 'update vmview' , before doing your next build.

**Comment by sky-flix** [comment]
No joy. I reverted back to our original snapshot containing 4.10, removed the vmview.conf, and ran the 'update vmview'. The update reported numerous errors on touch and remove processes. The build then failed as well, again outputting a number of touch and remove errors. I have reverted back to a later snapshot that has had 4.10 replaced with 4.6 for now.

**Comment by Thinstation** [comment]
Not sure why removing that file would give you grief, but try 4.10 and
manually remove the etc/ld.so.conf.d after the first build and before your
second.

**Comment by sky-flix** [comment]
Excellent. That seems to have fixed her right up. Thank you. Cheers sir!
