### ISSUE TITLE
thinstation 6.1 fastboot error -- networkmanager 

### ISSUE THREAD

**Issue by shNanChen** [Thinstation/thinstation#434]
Hi, 

Sorry, my English is not good, relying on Google Translate help.

I have a working thinstation build, clients booting on pxe.
I try now to speed boot with fastboot, but it unsuccessful.
thinstation build with parameter `--allmodules`

* In build.conf, I have :
```
  package debug
  param fastboot true
  param bootlogo false
  param splash verbose
  param bootverbosity 4
```

* In thinstation.conf.buildtime, I added :
```
  FASTBOOT_URL="http://192.168.12.44/boot"    _pxe server is the DevStation_
  NET_USE=BOTH
  NET_USE_DHCP=off     _also tried on_
  NET_IP_ADDRESS=192.168.12.51
  NET_MASK=255.255.255.0
  NET_GATEWAY=192.168.12.254
  NET_DNS1=192.168.12.254
```

I used the Porxmox qemu virtual machine to test pxe to start the thinstation,
The startup process stops at __`thinstation-linux:~$`__ , 
and there is __no get lib.squash access log__ on the Devstation server.

1. poweron
  ![boot](https://user-images.githubusercontent.com/6256701/60002774-e1913d00-969b-11e9-99a0-16444a6fd0f3.png)

2. Devstation log
  ![server](https://user-images.githubusercontent.com/6256701/60002837-071e4680-969c-11e9-9911-9a09d4f24a36.png)

3. just stop here
  ![stop](https://user-images.githubusercontent.com/6256701/60002894-27e69c00-969c-11e9-955f-6d7b507889e0.png)

4. /var/log/boot.log & /var/log/messages, no IPv4 ADDRESS ?
  ![info](https://user-images.githubusercontent.com/6256701/60003088-8f9ce700-969c-11e9-99a5-3e881fd845ad.png)

5. dmesg
  ![dmesg](https://user-images.githubusercontent.com/6256701/60003111-9a577c00-969c-11e9-809e-37e397828ce3.png)

EOF ,
Help me, please!

**Comment by trezel** [comment]
Hi,
Just a little suggestion : Did you try ipxe ?
I had issues with fastboot too (not the same as you have). I "took the opportunity" to migrate to ipxe instead of pxe. Now initrd and vmlinuz are downloaded with http, just like fastboot, and ipxe gives a lot more features you don't find in PXE.

It doesn't answer your question, sorry, but it may be a good workaround ;-)

**Comment by hadyos** [comment]
You can see in the first screenshot that it does use ipxe...

**Comment by Thinstation** [comment]
can you set an ip address manually? Ping the network? download the file manually?

**Comment by hadyos** [comment]
I have the same problem, Once I drop to the ipxe shell (CTRL B) and execute dhcp command I can ping and even set a new ip manually....

**Comment by shNanChen** [comment]
> can you set an ip address manually? Ping the network? download the file manually?

`ip addr add 192.168.12.25/24 dev ens18`
`ip: RTNETLINK answers: Operation not permitted` 

![snipaste_20190626_183142](https://user-images.githubusercontent.com/6256701/60173251-e0e5db80-9840-11e9-8a2a-60294089787a.png)

**Comment by Thinstation** [comment]
Do you have autonet package?

**Comment by shNanChen** [comment]
Modify the `build.conf` ，
```
package ts-classic
#package networkmanager
```

Fastboot started successfully on pxe.

reference: [Network problem while PXE boot](http://thinstation.4464.n7.nabble.com/Fwd-Network-problem-while-PXE-boot-td25074.html)
　　`Don't include networkmanager. It conflicts with autonet included via ts-classic.`

Defalut enable `package networkmanager`, It seems that ipv4 is disabled.
![noipv4](https://user-images.githubusercontent.com/6256701/60241418-d5002500-98e5-11e9-8d73-f635d213cf95.png)

**Comment by shNanChen** [comment]
[thinstation.conf.group- not working with networkmanager inTS5.4](http://thinstation.4464.n7.nabble.com/thinstation-conf-group-not-working-with-networkmanager-inTS5-4-td25405.html)

> Yes, this is a known issue, but there is a work around. Because of the type of dhcp request that **networkmanager** sends to the DHCP server, the next-server is not handed out. If your dhcp server also has a field for tftp server, set that to the same ip as your next-server, and you should be good to go.

**Comment by Doncuppjr** [comment]
Kinda silly to use networkfiles in conjunction with networkmanager. You should use auto net.
