### ISSUE TITLE
Two monitors and chrome

### ISSUE THREAD

**Issue by Jello146** [Thinstation/thinstation#439]
packages/chrome/etc/cmd/chrome.global

Two monitors: 
~# xrandr | grep \* | cut -d' ' -f4|sed -e 's/x/,/g'
1280,1024
1280,1024

Start:
/opt/google/chrome/chrome --no-sandbox --user-data-dir --kiosk --window-size=1280,1024 --window-position=0,0 1280,1024

Not open default page.

**Comment by Jello146** [comment]
Change in packages/chrome/etc/cmd/chrome.global:
xrandr | grep \* | cut -d' ' -f4|sed -e 's/x/,/g' | uniq

This is not a very beautiful solution, but it works for monitors with the same resolution.

**Comment by Thinstation** [comment]
I'll use head -n1 instead. Won't die if the resolution is a mismatch.
