### ISSUE TITLE
Freerdp CDROM redirection

### ISSUE THREAD

**Issue by kaduceusz** [Thinstation/thinstation#440]
Hi,
I have some problems with CDROM/DVD redirection. Small image, only for freerdp. 
1. freerdp is not connecting if /drive:DVD,/mnt/cdrom0 is in conn string
2. +drive option works, but ... inserted CD is mounted as /media/xxxx and on remote MS RDP this CD is mounted/redirected as cdrom0 and is empty. When I boot image with xfwm4, mounted CD is opened in Linux desktop, then redirection is OK, on remote MS machine i can see files.

some help? :)

**Comment by Doncuppjr** [comment]
Maybe disable udisks and just use automount

**Comment by kaduceusz** [comment]
thx,
didn't help, but i've noticed that CD is mounted with uid=0 and guid=0, and from root everything looks ok, besides that, that ts user (and redirection) can't work because of privileges. 
Option in buildtime.conf:
CDROM_MOUNT_OPTION="ro,uid=1000,gid=1000" (i want read only)
doesn't work either. But i won't give up. ;)

build includes autofs4 module and automount package

**Comment by kaduceusz** [comment]
quick question ;) ... it seems that on boot ts doesn't apply option:  CDROM_MOUNT_OPTION used in scsii.sh from automount package :(. When I manually mount CD/DVD with uid=1000 and gid=100 everythink works fine on freerdp. 
What did i missed in config?
CDROM_MOUNT_OPTION is in thinstation.conf.buildtime and also in thinstation.conf.network on tftp


thx in advance

**Comment by Doncuppjr** [comment]
I’ll take a look.

**Comment by kaduceusz** [comment]
thx,
just in case my thinstation.conf.buildtime.
When changed in scsi.sh ;)
line: 133 - mount_opts="$CDROM_MOUNT_OPTIONS" -> mount_opts="ro,uid=1000,gid=1000"
pxe image works fine.


[thinstation.conf.buildtime.txt](https://github.com/Thinstation/thinstation/files/3406466/thinstation.conf.buildtime.txt)

**Comment by Thinstation** [comment]
So, I opened up the default mounting permissions a little bit. I'm not sure where you are specifying CDROM_MOUNT_OPTIONS, but if it's in buildtime, it should have an effect.

Maybe you used 
CDROM_MOUNT_OPTION
instead of 
CDROM_MOUNT_OPTIONS
