### ISSUE TITLE
vmiew 5.x support in TS 6.1

### ISSUE THREAD

**Issue by mcsn747** [Thinstation/thinstation#441]
Hello!
Do you planing support vmview client 5.x?
Thanks!

**Comment by Thinstation** [comment]
It looks like it works. Just update the url before making your first build.

**Comment by mcsn747** [comment]
I have a successful build with 5.0 Horizon client and an error with 5.1.

> Extracting VMware Installer...done.
Component Name                     Component Long Name                                          Component Version
================================== ============================================================ ====================
vmware-installer                   VMware Installer                                             2.1.0.2040127
vmware-horizon-mmr                 VMware Horizon Multimedia Redirection (MMR)                  5.1.0.13956721
vmware-horizon-smartcard           VMware Horizon Smart Card                                    5.1.0.13956721
vmware-horizon-rtav                VMware Horizon Real-Time Audio-Video                         5.1.0.13956721
vmware-horizon-integrated-printing VMware Horizon Integrated Printing                           5.1.0.13956721
vmware-horizon-pcoip               VMware Horizon PCoIP                                         5.1.0.13956721
vmware-horizon-usb                 VMware Horizon USB Redirection                               5.1.0.13956721
vmware-horizon-serialportclient    VMware Horizon SerialPort Redirection                        5.1.0.13956721
An unknown error occurred during installation.  Please check the
installation log at /var/log/vmware-installer for more information.
vmview: Setup Complete

5.1 client introduces a new integrated printing feature, this may cause an error.

**Comment by mcsn747** [comment]
Unfortunately, I have an error on version 5.0 as well. And I don't know how to see vmware-installer log. 

The shutdown procedure has changed.  In version 4.x, after exiting the session, the user sees "Click yes to reconnect" window. In version 5.x, after exiting the session, the user returns to the pool selection window. To complete the work, the user must click File - Quit - Click yes to reconnect - No. If he doesn't, another person can use his saved credentials for login.

I read release notes for VMware Horizon client for Linux and found no related changes.

I have a Ubuntu machine with VMware Horizon client. All client versions - 4.x and 5.x - after exiting the session returns user to the pool selection window. Hence, the simplified behavior was specific to Thinstation.

How can I return old behavior from version 4.x?
