### ISSUE TITLE
TS on Odroid-h2

### ISSUE THREAD

**Issue by DtNeo** [Thinstation/thinstation#442]
Hello,
you or someone have try deploy TS on an [ODROID-H2 ](https://www.hardkernel.com/shop/odroid-h2/)?
I'm interesting to know if it works. I could maybe buy some for my society

Thank you for your great job and sharing it.

**Comment by Doncuppjr** [comment]
It’s x86, so it should work.

**Comment by DtNeo** [comment]
thanks for your answer.
Yeah, I think I will try it on september.
I can make a feedback here when I'll test.
(you can closed this issue if you want)
Good continuation
