### ISSUE TITLE
horizon view client smartcard C_Sign failed

### ISSUE THREAD

**Issue by triquichoque** [Thinstation/thinstation#443]
Looking for help on figuring out why the Horizon view client fails smartcard authentication. Smartcard is detected and testing with opensc-tools everything seems to be working correctly. On Horizon view, it prompts to select a certificate from the smartcard and asks for the PIN. After the PIN is input it gives a very generic "An SSL error ocurred". 
Authentication via username/password works and the windows guest can access the smartcard without problems
Enabling debuging on the view client shows an error when trying to cdk_cryptoki_rsa_sign. From the log:

```
[ALL] cdk_cryptoki_rsa_get_session:742: Entry
[ALL] cdk_cryptoki_rsa_get_session:742: Exit
C_Sign failed: 0x101 [LASTNAME NAME]
[ALL] cdk_cryptoki_rsa_get_session:919: Exit
```

Support from VMware was very limited as ThinStation is not an offically supported distro. We did prepare a CentOS 7 VM as similar as posible to the ThinStation build with Horizon view , opensc, etc.. and the error does not occur. It authenitcates using smartcard and PIN without any issues

The same log section on CentOS7 is as follows:

```
[ALL] cdk_cryptoki_rsa_get_session:742: Entry
[ALL] cdk_cryptoki_rsa_get_session:742: Exit
Returned 256 bytes of signed data
[ALL] cdk_cryptoki_rsa_get_session:919: Exit
```

opensc:
CentOS version  
opensc-0.16.0-10.20170227git777e2a3.el7.x86_64

On ThinStation have tried opensc versions 0.19 , 0.18, 0.17, and 0.16 but error doesn't change

openssl:

CentOS7 version  
OpenSSL 1.0.2k-fips 26 Jan 2017

ThinStation openssl:
OpenSSL 1.1.oi-fips 14 Aug 2018

havent been able to figure out how to downgrade the version of OpenSSL in ThinStation to see if it solves the error

How can I downgrade OpenSSL on ThinStation to the same level as the known to be working version being used in CentOS7?

Any pointers on how to troubleshoot  ?

**Comment by Thinstation** [comment]
I'm guessing your on the right path. They are likely requesting a crypto technique that was considered insecure and dropped from the latest fips ssl library. Downgrading.....hmmm, I don't know if that is the right course of action. Might need to talk to VMWare and find out what the max supported version of openssl is. VMWare does maintain a library set that they have identified as critical and not always available, so installed in an rpath folder. Possibly you could put a different version of openssl in that folder.

**Comment by triquichoque** [comment]
Just as an exercise to confirm that openssl version 1.0.2k works on ThinStation, how can I downgrade or override the current 1.1 version?
I see an openssl package directory but theres no openssl ports directory

**Comment by triquichoque** [comment]
Just did a test and upgraded the CentOS7 openssl library from source to 
OpenSSL 1.1.1 11 Sep 2018 
and its still working. It might not be an incompatibility with the latest version after all.


Any idea what else might be the issue?

**Comment by Doncuppjr** [comment]
Did you compile the library yourself? Did you leave the 1.0.2k library in place?
    On Thursday, July 25, 2019, 03:28:00 PM PDT, triquichoque <notifications@github.com> wrote:  
 
 
Just did a test and upgraded the CentOS7 openssl library from source to
OpenSSL 1.1.1 11 Sep 2018
and its still working. It might not be an incompatibility with the latest version after all.

Any idea what else might be the issue?

**Comment by Doncuppjr** [comment]
Which version of horizon are you using?
    On Thursday, July 25, 2019, 03:28:00 PM PDT, triquichoque <notifications@github.com> wrote:  
 
 
Just did a test and upgraded the CentOS7 openssl library from source to
OpenSSL 1.1.1 11 Sep 2018
and its still working. It might not be an incompatibility with the latest version after all.

Any idea what else might be the issue?

**Comment by triquichoque** [comment]
Im using latest version available : 5.1.0
Same error happens on 4.10 and 5.0 

Wanted to test if the horizon client had problems using the newer version of openssl. Pretty much followed this procedure to install the latest version of openssl from source

https://www.osradar.com/how-to-install-the-latest-version-of-openssl-on-centos-7/

Horizon client still authenticates with smartcard and PIN after updating openssl to 1.1.1. This is even newer than the version included in ThinStation where its giving the C_Sign error I posted previously

**Comment by Doncuppjr** [comment]
Our compile recipe is significantly different from default, perhaps that is at issue.
https://github.com/Thinstation/thinstation/blob/6.1-Stable/ts/ports/core/openssl/Pkgfile

**Comment by Thinstation** [comment]
I wonder if the stripping is an issue. You can try commenting out the stripping command from the install script, reinstall the package and try again.

**Comment by triquichoque** [comment]
Is the script build/packages/vmview/build/install ?

**Comment by Doncuppjr** [comment]
yes

**Comment by Thinstation** [comment]
Which version of glibc?

**Comment by triquichoque** [comment]
glibc in CentOS7 :

```
glibc-2.17-260.el7_6.6.x86_64
glibc-headers-2.17-260.el7_6.6.x86_64
glibc-common-2.17-260.el7_6.6.x86_64
glibc-devel-2.17-260.el7_6.6.x86_64
```

Tried commenting out the strip command on the vmview package install script, removed the files "installed" and "license" from the vmview/build directory and rebuilt image. Trying to authenticate with smartcard still reslts in the "C_Sign failed" error

I have noticed that the vmview installation during the build gives an error after installing the vmware components.
"An unkown error ocurred during installation. Please check the installation log at /var/log/vmware-installer for more information.
vmview: Setup Complete"

Theres no /var/log/vmware-installer file. Running the installer manually inside the chroot completes successfully with no errors. Besides the smartcard auth issue everything vmview related works on the thinclient

**Comment by Thinstation** [comment]
I would try a couple of things. First, install the vmview client directly into the chroot environment, and run it. Does it still fail? Yes. our library's, No, might be the kernel. Overwrite 2.17 with our glibc in the CentOS container.....what does that do?

**Comment by triquichoque** [comment]
From inside the chroot:

was not detecting the smartcard. DevStation is running as a VMware workstation VM with the usb smartcard reader attached
```
opensc-tool -l
"No smart card readers found"
```

dmesg showed the USB device correctly identified

manually running the pcscd daemon enabled the smartcard
/usr/sbin/pcscd --foreground --auto-exit

```
opensc-tool -l
# Detected readers (pcsc)
Nr.       Card    Features    Name
0          Yes                        Identive CLOUD 2700 F Smart Card Reader [CCID Interface]
```


view log complained about missing pkcs11 module
had to create /usr/lib/vmware/view/pkcs11 and linked the opensc-pkcs11 libs Im using for the vmview package

```
ln -s /build/packages/vmview/build/extra/lib/vmware/view/pkcs11/opensc-pkcs11.so /usr/lib/vmware/view/pkcs11/libopensc-pkcs11.so
ln -s /build/packages/vmview/build/extra/lib/vmware/view/pkcs11/opensc-pkcs11.so /usr/lib/vmware/view/pkcs11/libopensc-pkcs11
```
added a link without extension as vmview seems to add the extension ".so" when looking for the lib


had to copy libopensc.so.6 libs from the package directory to /usr/lib

`cp /ts/build/packages/opensc/usr/lib/libopensc.* /usr/lib`

Now vmview prompts for cetificate and PIN. Using the PIN results in "Error: An SSL error ocurred". vmview debug log shows the same "C_Sign failed: 0x101" error

Following your analysis this seems to point to thinStation's library as the problem. Do we need to try copying libs from ThinStation to CentOS? Let me know what needs to be transferred and I'll try the test

**Comment by Thinstation** [comment]
I guess I was hoping that you were running the chroot on a different distro, and using someone else's kernel.

**Comment by triquichoque** [comment]
Let me know what else to test that night help figure this out. Been looking how to replicate the problem using basic openssl and opensc commands but I'm not sure what exactly is vmview trying to do

**Comment by Thinstation** [comment]
Can you try a different kernel(another distro host)?

**Comment by triquichoque** [comment]
You mean running "ThinStation" on a different distro or changing the kernel of DevStation?
I could try installing the [Thin|Dev]Station environment in the CentOS 7 VM if that helps troubleshooting

**Comment by Doncuppjr** [comment]
Yes. Install chroot on CentOS VM

**Comment by triquichoque** [comment]
Got the chroot running on CentOS 7 but the thinclient still gives the same C_sign error.  Running the view client directly on CentOS outside the chroot works without the error. Installing the view client inside the chroot and adjusting for smartcard support (copy opensc libs and binary to the bin and lib directories inside the chroot) results in the C_Sign error.
**Works outside chroot, gives error indide chroot and on thin clients**


For reference heres what I did to get the chroot working:

Tired configuring the thinstation chroot on CentOS 7 but ./setup_chroot failed with the error: "FATAL: kernel too old". Latest official kernel available for CentOS 7 is 3.10 . Installed kernel 4.4 from elrepo.org and made it boot by default. ./setup_chroot ran succesfully

Copies over files from DevStation into the CentOS chroot:
packages directories for:
ca-bundle
vmview
opensc

port directory for:
opensc

machine definition directory for:
wyse7040

configuration files:
build.conf
build.urls
thinstation.conf.buildtime


Pointed the tftp root to:
/thinstation/build/boot-images/pxe

**Comment by Doncuppjr** [comment]
So, I guess it doesn’t like our libs. Specifically, I think it’s clashing with our libc, as view is actually including their own version of OpenSSL. Takes a while to compile, but it’s fairly easy to increment.

**Comment by triquichoque** [comment]
As a note, previously I had a black screen issue that was solved by copying libssl to the vmview package lib directory. We had to comment out the section of the vmview install script that deletes libs if they already exists elsewhere so it would find libssl during runtime.
Could this and the C_Sign error be related symptoms?

**Comment by Thinstation** [comment]
No. I thought we could purge their copy, but it turns out they are special builds needed for PCoIP. I leave them alone now. Might just be our version of glibc, possibly the strong fstack protector. I would try centos glibc in our chroot next, and vice versa.

**Comment by triquichoque** [comment]
Do you need me to test swapping glibc?
Can you provide some instructions on how to test CentOS7 glibc inside the chroot and vice versa ?

**Comment by Thinstation** [comment]
Yes.

in chroot, prt-get remove glibc
exit
then find the centos glibc install archive. not sure what format those are in, unpack and drop ontop of chroot, then try and go back in.

**Comment by triquichoque** [comment]
CentOS uses rpm for package management. Trying to figure out if a source RPM can be used for prt-get or a regular "./configure; make; make install" will work inside the chroot

**Comment by Doncuppjr** [comment]
You should be able to convert or extract something like a tar.gz from the rpm. Source is too far to go

**Comment by triquichoque** [comment]
Downloaded the source rpm of the current CentOS 7 glibc-2.17 with
`yumdownloader --source glibc`

extracted with
`rpm -i glibc-2.17-260.el7_6.6.src.rpm`

This created a SOURCES directory with glibc-2.17-c758a686.tar.gz and 880 patch files
tar.gz file md5sum matches with this one:
[https://src.fedoraproject.org/lookaside/pkgs/glibc/glibc-2.17-c758a686.tar.gz/d91ac2e9667310fa815c2316d542567e/glibc-2.17-c758a686.tar.gz](https://src.fedoraproject.org/lookaside/pkgs/glibc/glibc-2.17-c758a686.tar.gz/d91ac2e9667310fa815c2316d542567e/glibc-2.17-c758a686.tar.gz)


There's a smaller file named glibc-2.17-c758a686-releng.tar.gz but not sure if its need by prt-get

Do I need to modify /ts/ports/core/glibc/Pkgfile to use this tar.gz file and the 880 patch files?

The current Pkgfile includes kernel-headers-4.1.tar.xz as a source but the file is not in the directory. Should I get the kernel-headers-4.4.src.rpm (the CentOS current kernel) and extract the tar.gz too?

**Comment by Thinstation** [comment]
You don’t want to compile. Find the regular rpm, and extract the tar.gz.
Expand that over the chroot, it’s dirty I know, but only a test.

**Comment by triquichoque** [comment]
"prt-get remove glibc" seems to have removed more stuff than whats included on the glibc.rpm. Removed glibc and then used rsync to copy/merge the contents of the rpm into the chroot directories. The rpm had stuff for /etc , /lib64 , /sbin , /usr , /var that got merged into the corresponding directories under /thinstation

Now while inside the chroot trying to run vmview results in missing libraries errors:

/sbin/ldconfig: Cant't open cache file /etc/ld.so.cache: No such file or directory
[...] libbfd-2.27.so
[...] libatk-1.0.so.0

After exiting the chroot and running ./setup_chroot it fails with more missig library errors:
```
[root@centos7 thinstation]# ./setup-chroot
groff: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
most: error while loading shared libraries: libslang.so.2: cannot open shared object file: No such file or directory
/usr/lib/ruby/gems/2.4/gems/ronn-0.7.3/bin/ronn:203:in `write': Broken pipe (Errno::EPIPE)
        from /usr/lib/ruby/gems/2.4/gems/ronn-0.7.3/bin/ronn:203:in `puts'
        from /usr/lib/ruby/gems/2.4/gems/ronn-0.7.3/bin/ronn:203:in `block (2 levels) in <top (required)>'
        from /usr/lib/ruby/gems/2.4/gems/ronn-0.7.3/bin/ronn:181:in `each'
        from /usr/lib/ruby/gems/2.4/gems/ronn-0.7.3/bin/ronn:181:in `block in <top (required)>'
        from /usr/lib/ruby/gems/2.4/gems/ronn-0.7.3/bin/ronn:167:in `each'
        from /usr/lib/ruby/gems/2.4/gems/ronn-0.7.3/bin/ronn:167:in `<top (required)>'
        from /usr/bin/ronn:22:in `load'
        from /usr/bin/ronn:22:in `<main>'

Development Environment Active. Type 'exit' to leave when done.

[root@TS_chroot]/#
```

reverted the VM to just before removing glibc from the chroot and tired just merging the files by overwriting the existing ones. Running ./setup_chroot results in an empty "README" screen and this when exiting:
```
[root@centos7 thinstation]# ./setup-chroot
groff: /lib/libc.so.6: version `GLIBC_2.18' not found (required by /usr/lib/libstdc++.so.6)

Development Environment Active. Type 'exit' to leave when done.

[root@TS_chroot]/# 
```

vmware-view

```
[root@TS_chroot]/# vmware-view
/usr/lib/vmware/view/bin/vmware-view-crtbora: /lib/libc.so.6: version `GLIBC_2.18' not found (required by /usr/lib/libstdc++.so.6)

[root@TS_chroot]/#
```


Any pointers on how to proceed?

**Comment by Thinstation** [comment]
Might need to do the same trick with gcc

**Comment by triquichoque** [comment]
running "prt-get remove" broke more stuff then just overwriting the libs. Will just overwriting glibc and gcc work or is the "prt-get remove" needed?

**Comment by Thinstation** [comment]
Sure, try just overwriting.

**Comment by triquichoque** [comment]
Did same download and extract from rpm process for gcc-4.8.5-36.el7_6.2.x86_64. This gives a usr/ directory that got merged into /thinstation/usr/

results:

```
[root@centos7 thinstation]# ./setup-chroot
groff: /lib/libc.so.6: version `GLIBC_2.18' not found (required by /usr/lib/libstdc++.so.6)

Development Environment Active. Type 'exit' to leave when done.

[root@TS_chroot]/#
```

```
[root@TS_chroot]/# vmware-view
/usr/lib/vmware/view/bin/vmware-view-crtbora: /lib/libc.so.6: version `GLIBC_2.18' not found (required by /usr/lib/libstdc++.so.6)

[root@TS_chroot]/#
```

**Comment by Thinstation** [comment]
doesnt look like glibc got removed.

**Comment by triquichoque** [comment]
Did not execute "prt-get remove glibc", just overwrote the libs with the files from the rpm. I'll try removing again but including gcc this time

**Comment by Doncuppjr** [comment]
Possibly could do
pet-get remove glibc gcc 
as a single command

**Comment by triquichoque** [comment]
removed both with
```
prt-get remove glic gcc
[...]
-- Packages removed
glibc

-- Packages where removal failed
gcc

```




then used rsync to merge the gcc and glibc files into the /thinstation directory
```

[root@centos7 thinstation]# ./setup-chroot
groff: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
most: error while loading shared libraries: libslang.so.2: cannot open shared object file: No such file or directory
/usr/lib/ruby/gems/2.4/gems/ronn-0.7.3/bin/ronn:203:in `write': Broken pipe (Errno::EPIPE)
        from /usr/lib/ruby/gems/2.4/gems/ronn-0.7.3/bin/ronn:203:in `puts'
        from /usr/lib/ruby/gems/2.4/gems/ronn-0.7.3/bin/ronn:203:in `block (2 levels) in <top (required)>'
        from /usr/lib/ruby/gems/2.4/gems/ronn-0.7.3/bin/ronn:181:in `each'
        from /usr/lib/ruby/gems/2.4/gems/ronn-0.7.3/bin/ronn:181:in `block in <top (required)>'
        from /usr/lib/ruby/gems/2.4/gems/ronn-0.7.3/bin/ronn:167:in `each'
        from /usr/lib/ruby/gems/2.4/gems/ronn-0.7.3/bin/ronn:167:in `<top (required)>'
        from /usr/bin/ronn:22:in `load'
        from /usr/bin/ronn:22:in `<main>'

Development Environment Active. Type 'exit' to leave when done.

[root@TS_chroot]/#
```

**Comment by Thinstation** [comment]
Progress.

**Comment by triquichoque** [comment]
```
[root@TS_chroot]/# vmware-view
/sbin/ldconfig: Can't open cache file /etc/ld.so.cache
: No such file or directory
strings: error while loading shared libraries: libbfd-2.27.so: cannot open shared object file: No such file or directory
/usr/lib/vmware/view/bin/vmware-view-crtbora: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory

[root@TS_chroot]/#
```

**Comment by Thinstation** [comment]
Don't worry about ronn.

**Comment by triquichoque** [comment]
vmware-view wont start with the error posted before
`libbfd-2.27.so: cannot open shared object file`

Maybe CentOS7 is "too old". Going to try with Fedora 30, that should include latest of everything

**Comment by Doncuppjr** [comment]
That would be better.

**Comment by Doncuppjr** [comment]
Sorry I cant be more helpful on this one, but I don’t have a test environment. Instead of whole packages, f30 and TS should be close enough to just copy libs around.

**Comment by triquichoque** [comment]
recreated the chroot on Fedora 30 following the same process I did before for CentOS 7 . Smartcard authentication for Horizon view is working now on the thin clients booted from the Fedora 30 thinstation images. No more C_Sign error

Once CentOS 8 is released I'll try it again. For now Fedora 30 will do

Thanks for all the help

**Comment by Thinstation** [comment]
Soooooo, no bad libraries? Just being built on CentOS caused this?

**Comment by triquichoque** [comment]
Problem started with DevStation. The C_Sign error would happen both inside and outside the chroot. Next tried on CentOS 7 where the error would happen only while inside the chroot. Outside the chroot the error wouldn't occur. Finally on Fedora 30 the error doesn't occur neither inside or outside the chroot. Horizon view is working perfectly with smartcards on the thinclients

Not sure where the above points to be the problem but if you want me to run more tests on the original DevStation just let me know.

**Comment by Doncuppjr** [comment]
I can’t think of anything to test. That’s really weird.

**Comment by Doncuppjr** [comment]
I guess you could make an image on DevStation and F30, confirm that one works and one doesn’t, and send them both to me for analysis.

**Comment by triquichoque** [comment]
I can provide the images for comparison. Do you need the whole boot-images directory or just the pxe directory ?

**Comment by Thinstation** [comment]
Just the ISO's, if you made them. Harder to get the individual pieces mixed up.

**Comment by Thinstation** [comment]
So, it looks like your DevStation has an old checkout, probably all kinds of bugs. Your f30 checkout is more current. You would need to do a factory reset on the DevStation to bring it up to date, then add your configs and build.
