### ISSUE TITLE
Install DevStation on physical computer: Memory detection false results

### ISSUE THREAD

**Issue by crefohb** [Thinstation/thinstation#450]
Hello,
I've got problems to install DevStation on Lenovo M90 ThinkCentre. That computer actually has 5 GB (3x1,1x2) of RAM installed. After booting DevStation from USB-Key it says "Not enough memory". The hardware detection tool says: 2868 MB detected. If I select the memory banks, all installed RAM-Modules sizes are displayed correctly.

**Comment by Doncuppjr** [comment]
Hmmm, the memory size tool, is code provided by the Syslinux project. That’s an interesting report, but I can’t debug it without the malfunctioning unit. Might have to use another distribution for a development base. 

Sent from Yahoo Mail for iPhone


On Tuesday, August 27, 2019, 3:59 AM, crefohb <notifications@github.com> wrote:


Hello,
I've got problems to install DevStation on Lenovo M90 ThinkCentre. That computer actually has 5 GB (3x1,1x2) of RAM installed. After booting DevStation from USB-Key it says "Not enough memory". The hardware detection tool says: 2868 MB detected. If I select the memory banks, all installed RAM-Modules sizes are displayed correctly.

**Comment by crefohb** [comment]
Hello Doncuppjr,
it's working on Lenovo ThinkCentre M83 model.

**Comment by Thinstation** [comment]
Maybe DVMT settings? Video/System memory splitting can sometimes have undesirable effects, especially when being ‘dynamic’. I’d fiddle with the bios. Your only dealing with it and syslinux at that point in the boot process.
