### ISSUE TITLE
USB on FreeRDP

### ISSUE THREAD

**Issue by m0bYczE** [Thinstation/thinstation#451]
Hello, i have a question. How can I mount usb flash drive in freerdp? Has anyone got completed soulution?

Thank you.

**Comment by Thinstation** [comment]
Just search the mail archives, it’s all anybody does ;)

**Comment by m0bYczE** [comment]
I search a lot of topics, but i don't found solution.

**Comment by N0odlez** [comment]
You can add them via the config file. Please see link below for all options for FreeRDP:
https://github.com/Thinstation/thinstation/blob/6.2-Stable/ts/build/conf/freerdp.conf.sample

You will be looking to add /drive:hotplug,* to your freerdp string
