### ISSUE TITLE
Issue with boot 

### ISSUE THREAD

**Issue by jeniha** [Thinstation/thinstation#455]
On few terminals give me this error and stay in loop:"compat: exports duplicate symbol pcie_capability_clear_and_set_dword(owned by kernel)"
When change the terminals everything is work, after wait few hours and start this terminal that give me this error before everthing is work smooth.
How to prevent this error message and why give me this error?

**Comment by Doncuppjr** [comment]
I dunno, is someone trying to hack you, inserting a random module?
