### ISSUE TITLE
Frozen on loading bar

### ISSUE THREAD

**Issue by N0odlez** [Thinstation/thinstation#459]
Thinstation 5.6.0 DevStation installer, Devstation and Thinstation Build loads absolutely fine after building a custom build and a standard build. 

Thinstation 5.5.2 loads but then errors when trying to execute the install or the terminal. However on Thinstation 5.6 and above it will hang on the loading screen at 100%.

Terminal error for 5.6.1 is (139):
/etc/init.d/terminal: line 129:  4575 Segmentation fault xfce4-terminal

The background i dont think is rendering correctly on Thinstation 5.6.1 installer as it is rather quite pink although the mouse and the task bar are rendered correctly.

I have tried many things, making a machine profile, all modules build, leaving as standard but still it will not load in to the build. The thinstation installer loads absolutely fine and so does the Dev Station but the thinstation builds will not load.

Currently i am having to stick with 5.6.0 but this is not a great solution as i need updates to ensure we meet compliance.

The hardware im running this on is a Dell Optiplex 740 - 4GB Ram - 128GB SSD and AMD Athlon 64 processor.

I would love to be able to submit logs but as the screen freezes on 100% i cant get to the terminal to submit.

**Comment by Doncuppjr** [comment]
If you see anything pink, you must be having a hardware problem.

**Comment by N0odlez** [comment]
The pink only happens on older builds 5.5, 5.6 installers. The actual builds are fine. But 5.6 and above builds freeze 100% on the loading bar and when pressing F2 where it should take you to the cli but just presents a black screen.

The bit that I'm wondering is the 6.0+ installers all boot fine and loads all the drivers fine but a build with the default config but with all modules will not load and freezes on the the loading bar at 100%.

Hop you can help Don. :)

**Comment by Thinstation** [comment]
It is sometimes confusing to use the word modules. It’s slightly overused in technology. There are kernel modules and Xorg modules. Perhaps you haven’t included the correct xorg module for your video card. If the hardware is really old, maybe it’s support was dropped in recent xorg.

**Comment by N0odlez** [comment]
Sorry, when i say modules i specifically mean an "All Modules" build (all firmware). but i have enabled all Xorg modules and that doesnt help either.

The thing that i dont understand and ill say again is the Dev Station installers look and run absolutely fine. It is only an issue on the ThinStation builds that will not load.

Are there any differences in the Dev Stations to the ThinStation builds? I think there maybe or the ThinStation is missing an Xorg or graphics driver that is in the Dev Station install. And i really want to stress and hope you can understand, if the Dev Station installer works, why doesn't the ThinStation builds work.

**Comment by Doncuppjr** [comment]
Perhaps it is firmware related then. Linux has a lot of disparate components that work together. The conf files for the the DevStation build can be used or reviewed in the /build/conf/devstation folder. This has all kernel modules, the free Xorg modules, and allfirmware.

**Comment by mcsn747** [comment]
I regularly have similar error. It must have something to do with the size of the image.

**Comment by N0odlez** [comment]
I will take a look today and use 6.2 and try get this working with the devstation configs. Many thanks for that Don, i will feedback my findings.

**Comment by N0odlez** [comment]
Okay another update, 6.2 Dev Station wont boot and has the same issue im facing. 6.1.1 does boot fine.

I've used the suggested build file and that doesnt work either. Now going to look through the build.log and see whats happening in there.

**Comment by N0odlez** [comment]
I think i have found the issue.

The build log shows a LOAD of missing firmware messages. All of the firmware files ending in .ko are fine but other modules that end with .d56, .boot, .xlx all show error and are not able to be found. See 
[build.log](https://github.com/Thinstation/thinstation/files/3651856/build.log)

**Comment by N0odlez** [comment]
Further to back this up i have looked in the /usr/lib/firmware directory and can see all of the firmware that is missing. I have also looked in /thinstation/ts/firmware_notfound and there are loads of the firmware error files in there that are all missing.

It is safe to say this is the issue and i need to some how fix this.

**Comment by Doncuppjr** [comment]
Did any of the firmware ports fail to build when you did the install? ls /var/log/pkgbuild ?

**Comment by Doncuppjr** [comment]
After reviewing your build.log, it looks like your missing the firmware ports. These usually install for you during the unwind, perhaps you have a poor internet connection. 
prt-get install /ts/ports/binary-core/*
you'll also need to purge the missing firmware cache files before your next build.

**Comment by N0odlez** [comment]
Thanks Don,

After having a look that was a red herring. Done a fresh install and it now builds fine. Just now testing the Devstation build configs and will see what happens next.

**Comment by N0odlez** [comment]
Okay back to square one.

ThinStation 6.1.1 will finally boot a little further, i get thrown in to a cli now and nothing else.

Looked at the messages log and only 5 entries:
syslogd started: BusyBox v1.30.1
crond (BusyBox v1.30.1) started, log level 8
pam_succeed_if(login:account): requirement "user = tsuser" was met by user "tsuser"
pam_systemd(login:session): Failed to connect to system bus: Broken pipe
pam_unix(login:session): session opened for user tsuser by LOGIN(uid=0)

I think line 4 of that log says it all i think. It couldn't open a session so fell back to the cli

And in the boot.log there are a few notices:
No local found
No keymap found
No console font found

the last 2 entrys are:
xconf
session-setup

This is becoming more and more interesting but also more frustrating. Not sure what i can try next?

**Comment by N0odlez** [comment]
Where is the ThinStation boot script and ill try and work my way forwards through it and see what is happening.

I try and run xserverrc and it runs but running xinitrc throws errors sayung xfconfig-query command not found.

**Comment by N0odlez** [comment]
I think i need to know exactly how the Dev Station is created as this loads fine.

No custom builds or even using the Devstation configs are working to create a custom image. This is becoming a joke and i dont know what to do next :(

Next month i need to deploy this to over 400 computers and i want to use the latest version possible and not have to revert to 5.5.2.

**Comment by N0odlez** [comment]
Plot thickens more, just tried to boot the latest Live CD and that freezes on the loading bar at around 95%

**Comment by Thinstation** [comment]
The latest 6.2 has a new feature that speeds up app launching, but this might be problematic on lower resource machines. What are your specs? See /ts/bin/release for my full build recipe.

**Comment by Doncuppjr** [comment]
Your boot medium didn’t mount. Most loading is delayed until after kernel init, but that means we have to come back to the media, mount it, and continue loading. You will need the kernel modules to load any appropriate file system or network resources. If network booting, autonet package, else automount package should be enough 

Sent from Yahoo Mail for iPhone


On Thursday, September 26, 2019, 2:16 AM, AzureusNation <notifications@github.com> wrote:


Where is the ThinStation boot script and ill try and work my way forwards through it and see what is happening.

I try and run xserverrc and it runs but running xinitrc throws errors sayung xfconfig-query command not found.

**Comment by N0odlez** [comment]
@Thinstation to answer the specs question:
Dell Optiplex 740 - 4GB Ram - 128GB SSD and AMD Athlon 64 processor

I've finally gotten to be able to get to the logs when the loading bar has frozen :D

i have a new file called faillog and it contains the following:
^@^@^@^@^@ty4^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@

I have switched through all of the tty sessions from 1 to 6 and all of them are as a cli. what can i try from here?

**Comment by N0odlez** [comment]
So i've had a look at 6.2 and as the installer wont boot ive looked at the changes made to the devstation configs since 6.1. The only big change i can see is that fastboot has been enabled for 6.2 so ive ran a test.

if i disable fast boot on my builds, it no longer freezes the loading bar. and finally i get an xorg log. Although it was unable to go graphical this is a huge step in the right direction.

Please see attached Xorg log.
![20190927_122350](https://user-images.githubusercontent.com/3342020/65766254-6324bb00-e122-11e9-98b0-30f1a41249ac.jpg)
![20190927_122403](https://user-images.githubusercontent.com/3342020/65766255-6324bb00-e122-11e9-9bcf-10b90e4cd857.jpg)
![20190927_122411](https://user-images.githubusercontent.com/3342020/65766257-63bd5180-e122-11e9-81be-0e3d37c40be2.jpg)

**Comment by Thinstation** [comment]
Can you give me an lsmod after xorg fail. Also send journalctl -xe. You should have enough system to network and push files.

**Comment by N0odlez** [comment]
Sure will do. Just trying to build the DevStation instead now to see if that will go through. if it doesnt ill send over these logs, if it does go through i'll rebuild the default config with fastboot disabled and send them over.

Thanks

**Comment by N0odlez** [comment]
Its working....??? and i havent changed anything apart from the above... this is most strange
