### ISSUE TITLE
HDMI/DisplayPort based audio sporadically not working after boot up...

### ISSUE THREAD

**Issue by jens-maus** [Thinstation/thinstation#46]
Since a few kernel versions (I think since 3.11.x) we are having problems with thinstation in combination with intel NUC based thin clients and HDMI/DisplayPort audio output being recognized on boot up.

After some investigation it bounds down to seeing the following in "dmesg" output if HDMI output is not being recognized:

```
...
snd_hda_intel 0000:00:1b.0: irq 59 for MSI/MSI-X
hda-i915: get_power symbol get fail
hda-intel Error request power-well from i915
input: HDA Intel PCH Headphone as /devices/pci0000:00/0000:00:1b.0/sound/card1/input5
input: HDA Intel PCH Mic as /devices/pci0000:00/0000:00:1b.0/sound/card1/input4
[drm] Memory usable by graphics device = 2048M
i915 0000:00:02.0: setting latency timer to 64
i915 0000:00:02.0: irq 60 for MSI/MSI-X
...
```

Please note the ```get_power symbol get fail``` message and that only two audio devices (headphone and mic are recognized. As a results pulseaudio then ends up showing only these devices and omitting the HDMI/DisplayPort connected devices.

However, with no particular logic/reason sometimes the boot up of the same machine setup results in working HDMI/DisplayPort audio output . In these cases the dmesg output shows correctly all audio devices:

```
...
i915 0000:00:02.0: setting latency timer to 64
i915 0000:00:02.0: irq 59 for MSI/MSI-X
...
snd_hda_intel 0000:00:1b.0: irq 60 for MSI/MSI-X
snd_hda_intel 0000:00:03.0: irq 61 for MSI/MSI-X
Switched to clocksource tsc
input: HDA Intel HDMI HDMI/DP,pcm=7 as /devices/pci0000:00/0000:00:03.0/sound/card0/input6
input: HDA Intel HDMI HDMI/DP,pcm=3 as /devices/pci0000:00/0000:00:03.0/sound/card0/input5
input: HDA Intel PCH Headphone as /devices/pci0000:00/0000:00:1b.0/sound/card1/input8
input: HDA Intel PCH Mic as /devices/pci0000:00/0000:00:1b.0/sound/card1/input7
...
```

Please note the difference in the order of i915 setup (different irq assignments even) and that there are two snd_hda_intel assignments if the HDMI/DP setup works.

Question is now, why does it sometimes fail and sometimes it works? In fact, when booting the latest Ubuntu 14.04 version (with kernel 3.13.0) it always works no matter how often the system is rebooted.

So any hint in fixing or even debugging the issue a bit more is very welcome. Please find attached the corresponding dmesg outputs for the working and broken case including the ```pactl``` outputs showing that only one sink is available in case no HDMI/DP audio is setup. Please also not that, despite not seeing the second snd_hda_intel device in the dmesg message it always shows up in the "lspci" output.

**Comment by Thinstation** [comment]
Jens,

I made a script in for 5.3 that will recompile all the kernels for you. It's called rebuild-kernels, and can be run from the chroot. You can change the version of the kernel by updating ts/ports/kernel-modules/VERSION, to which ever version you want.
