### ISSUE TITLE
Update ocsinventory agent (unofficial) to version 1.8.0

### ISSUE THREAD

**Issue by jackburton79** [Thinstation/thinstation#460]
I released a new version of my unofficial ocsinventory agent: 1.8.0.

https://github.com/jackburton79/ocs-agent/releases/tag/v1.8.0

It contains various improvements to the version currently included in Thinstation (1.6.4):

Enhancements:
- Display Manufacturer is shown with the full description string (I.E: Hewlett Packard) instead of the three-letter code (HWP)
- Network interface speed and memory description (including empty slots) are included in the inventory
- Logs now go through the syslog api
- New agent string (with fallback to the old one)

Fixes:
- Crash when the server host name was unresolvable

**Comment by jackburton79** [comment]
I can provide pull requests for any Thinstation branch you want, if needed

**Comment by Thinstation** [comment]
Updated in 6.2, ty. How is your 6.2 testing coming?
