### ISSUE TITLE
Old hardware compatibility

### ISSUE THREAD

**Issue by N0odlez** [Thinstation/thinstation#462]
https://github.com/Thinstation/thinstation/blob/7c2dd8add8fb9918f0e60ee3d3b88209a2175e9d/ts/build/conf/devstation/build.conf.example#L320

Please could this be returned to false to enable older hardware compatibility.

**Comment by Doncuppjr** [comment]
I don't understand. What can't be made to work with fastboot?    On Sunday, September 29, 2019, 02:16:16 PM PDT, AzureusNation <notifications@github.com> wrote:  
 
 
https://github.com/Thinstation/thinstation/blob/7c2dd8add8fb9918f0e60ee3d3b88209a2175e9d/ts/build/conf/devstation/build.conf.example#L320

Please could this be returned to false to enable older hardware compatibility.

**Comment by N0odlez** [comment]
My old Dells will not boot an image with fastboot enabled but they will boot an image with it disabled. This was the whole issue i was having with the screen freezing on the loading bar.

**Comment by Thinstation** [comment]
It’s not a mandatory feature. It’s optional, but set to the best default position for most systems.

**Comment by Thinstation** [comment]
It would likely work with your older dells, just need to cut down the size of the image. Maybe drop some fonts.

**Comment by N0odlez** [comment]
I cant drop any fonts as the actual TS 6.2 installer iso will not boot. This leaves me and possibly a few others in a sticky situation where we wont be able to move from 6.1 to 6.2

**Comment by Thinstation** [comment]
The does not include the big font package. It doesn't have a browser.

What issue are you having booting the installer?

**Comment by Thinstation** [comment]
The installer is really for DevStation, which should be a machine or VM with lots of resources. Your builds can be pared down considerably more than the installer for specific hardware.

**Comment by N0odlez** [comment]
Oh... in that case I didn't realise it was mainly for a virtual machine. I shall close this.
