### ISSUE TITLE
DPI Font Scaling - Vmware-View

### ISSUE THREAD

**Issue by rohrbachger** [Thinstation/thinstation#463]
Some of our older people do have on windows the font size scaled to 120%.
To migrate to thinstation we need to get this feature running.

Start/Configuration/DesktopSettings/Fonts/DPI
Custom DPI Settings

I have tested with thinstation 6.2 in the package set-resolution there is the possibilty to do this manually, each time when thinstation starts.
If we scale to 110% also the vmware view agent using this factor. This is as expected the effect we want to have, that´s fine.

Now we do have the challenge to save that by machine
Testing with the conf value SET_RESOLUTION_DPI=110 does not make any difference.
We tested in the thinstation.conf.buildtime first. 

Can someone give a hint, how is the right usage to set the Font DPI size?

**Comment by Thinstation** [comment]
Try X_DPI=110
