### ISSUE TITLE
TS 6.2 Thousands of fonts!

### ISSUE THREAD

**Issue by mcsn747** [Thinstation/thinstation#464]
I built a brand new Thinstation 6.2 and got near 280 MB of fonts in the boot image.  
Thinstation must be THIN-station, not THICK- ;-)

**Comment by mcsn747** [comment]
I have enabled:
package fonts-TTF-BH
package fonts-TTF-vera
package fonts-TTF-liberation
package fonts-TTF-noto

**Comment by Thinstation** [comment]
TTF-noto is the big one. Google has been padding it out over the last couple years. Was only like 29mb, now it’s over 200. Might need to break it down.

**Comment by mcsn747** [comment]
I removed the fonts-TTF-noto package and saved over 100 MB in a squezzed image. You should comment this package in the sample file. Thanks!

**Comment by Thinstation** [comment]
I made some changes to this font package. Might not work for all locales, but it's smaller.
