### ISSUE TITLE
Vmware-View-Horizon-TimeZone

### ISSUE THREAD

**Issue by rohrbachger** [Thinstation/thinstation#465]
Thinstation is right configured with timezone=Europe/Berlin,
It shows the right time on the desktop.

If I start with the view client 5.2 a session, I noticed that in the session the time is 2 hours behind.
After some testing I created in /etc/timezone file with Europe/Berlin
Starting after that a view session the time is correct.
So it looks like, that the view client is looking for this timezone file.

Am I doing something wrong with the time setting, or do other people have the same with view sessions.
Probably a solution is to create the file automatically, because it is the same setting as in thinstation.conf.buildtime.
Or is there a simpler way?

**Comment by Thinstation** [comment]
Build should already create that link for you. What does the link point to before you change it?

**Comment by Thinstation** [comment]
Reading through the FreeRDP code, it looks like it correctly falls back to /etc/timezone only after trying /etc/localtime and /etc/TZ which normally link to a zone info file. As long as that link is set up correctly, the FreeRDP component of Horizon should work correctly. 

/etc/timezone is kind of crufty.

**Comment by rohrbachger** [comment]
Looks like this old stuff is still in use.
We are using PCOIP and not the RDP connection, maybe that is a difference.
To create the timezone file is an easy solution.
In our case it is easy, we are working with all subsidiaries in one timezone.
But I did not found a switch in VMware to ignore the local time zone.

**Comment by mcsn747** [comment]
I test Horizon 5.2 client and have correct time and timezone in the Thinstation and Windows client. I'm changed my timezone to Europe/Berlin and rebuilt the image. Time has changed right. Check your settings. 
In Horizon you can enable or disable time zone forwarding from client to virtual desktop. This is configurable in group policy templates in Computer Configuration - Administrative Templates - VMware Horizon Client Configuration.

**Comment by rohrbachger** [comment]
Yes, we do not have this setting on the Group policy. Thanks for the tip.
This explains it. When the view environment was setup, I think they just forgot.
In our case we are picking up the thinstation time and timezone information.
As we are working in one time zone only the way to use the central server time is the better way.
So we can not run in time issues in case of false local times.
However, if someone is working with different timezones, it might be helpfull to work with the timezone file. It depends on the business.

**Comment by rohrbachger** [comment]
After some testing I figured out:
The hardware clock needs to be set to CET.
Than it works fine with local time in thinstation with the timezone setting,
and also it works out of the box with the view client.

**Comment by Doncuppjr** [comment]
The standard for unix is to store the time as UTC in the RTC. It's not an issue unless you switch back and forth between unix and windows(stores local time !UTC). It's very unlikely that the VIEW client would take it's own reads of the RTC. You can try setting RTC_CMOS=LOCAL, and ThinStation will store and retrieve time from the RTC the same way windows does.

**Comment by Thinstation** [comment]
I found an error in the alltimezone package that may have caused issues when using a different timezone in a runtime .conf vs the buildtime.conf file.
