### ISSUE TITLE
Webfiltering Signed Certificate

### ISSUE THREAD

**Issue by N0odlez** [Thinstation/thinstation#466]
How can i add a self signed certificate (.crt) to a custom ca-bundle package. I need this for Chrome on the thinstation to be able to use our webfiltering.

**Comment by Thinstation** [comment]
ts/build/packages/ca-bundle/build/finalize

**Comment by Thinstation** [comment]
Basically create a package with a folder called certs, and put your cert in there, then include the package in the build.
