### ISSUE TITLE
build pkg remmina

### ISSUE THREAD

**Issue by dronmaxman** [Thinstation/thinstation#467]
Hi. I tried to build pkg remmina. I maked package remmine, but not all plugins exists into an TS image. Where I need to copy /build/packages/remmina/usr/lib64/plugins ?

My manual:
cd ts/ports/static-source/
httpup sync https://www.mizrahi.com.ve/crux/ports/#remmina remmina
cd remmina
pkgmk -d
pkgmk -uf
pkgmk -i
cd /build
add package remmine to build.conf.
mkdir -p /build/packages/remmina/build
cp /build/packages/rdesktop/build/install /build/packages/remmina/build/install
cat /build/packages/remmina/build/install
#!/bin/sh

export PACKAGE=remmina
export PORTS=$PACKAGE
repackage -e

returnval=$?

exit $returnval

After ./build we have
[root@TS_chroot]/build# ls /build/packages/remmina/
bin  build  lib  usr

[root@TS_chroot]/build# ls /build/packages/remmina/usr/lib64/*
/build/packages/remmina/usr/lib64/pkgconfig:
remmina.pc

/build/packages/remmina/usr/lib64/remmina:
plugins

But this PLUGINS does not exist in TS image after build.

**Comment by Thinstation** [comment]
mkrepackage remmina will handle the install and remove scripts. I think we are not using lib64 nomenclature, but rather just /lib. We make a link lib64 that points to lib for compat, but if a port has a dir lib64, that could break things. I'll look at your port.

**Comment by Thinstation** [comment]
basic integration of remmina done.
