### ISSUE TITLE
TS 6.2 Disconnect from vmview leads to empty desktop

### ISSUE THREAD

**Issue by mcsn747** [Thinstation/thinstation#468]
Hello.
I have the issue about disconnect from the vmview client 5.2. In former versions (4.10 for example) "Disconnect" and "Disconnect and Log off" buttons had same result: a window "Click yes to reconnect". Now retains this behavior "Disconnect and Log off" button only.  The "Disconnect" button leads to empty desktop without any possibility to return. The same happens if click to **x** button in upper right corner - it's a new feature in the Horizon client.
![IMG_20191002_102842](https://user-images.githubusercontent.com/42139514/66103030-ca80b600-e5cd-11e9-8377-4210a3e33d1b.jpg)
I think that all these cases should be handled the same way. The user should not see an empty desktop. It should always see "Click yes to reconnect" window when going out from vmview client.

**Comment by rohrbachger** [comment]
I can not confirm this behaviour with client 5.2.
After the x it takes some seconds, but the reconnect button comes up.

As we do have a vmvware-Horizon icon on the desktop itś easy for the user, a second way.
We are using the --once option also, so that a new login is necessary. 

This are the settings:
VMVIEW_AUTOCONNECT=TRUE
VMVIEW_SSLVERIFYMODE=1
VMVIEW_DEFAULTBROKER=View01.Myserver.de

SESSION_1_ICON=ON
SESSION_1_TITLE="HORIZON"
SESSION_1_TYPE=vmview
SESSION_1_AUTOSTART=ON

SESSION_1_VMVIEW_FULLSCREEN=True
SESSION_1_VMVIEW_ONCE=True

**Comment by mcsn747** [comment]
Thank you for reply. 
My settings in build file:
SESSION_1_TYPE=vmview
SESSION_1_AUTOSTART=on
SESSION_1_VMVIEW_FULLSCREEN=true
SESSION_1_VMVIEW_ONCE=true
VMVIEW_DEFAULTBROKER=vdi.server.name

Also I have view-preferences file in ../packages/vmview/etc/skel/.vmware:
view.autoConnectBroker = "TRUE"
view.sslVerificationMode = "2"
view.defaultBroker = "vdi.server.name"
view.once = "TRUE"
view.autoConnectDesktop = "TRUE"
view.enableH264 = "FALSE"
view.autoHideToolbar = "TRUE"
view.defaultDomain = "domain.name"

I waited half an hour after closing session, and nothing come up.
Moreover I set SESSION_1_ICON=ON and see no icon on the desktop. Can you  explain how it work?

**Comment by rohrbachger** [comment]
I  have not changed something in the packages/vmview folder.
Iḿ using xfwm windows manager.
Attached my configs. For view only the settings as I posted before.


[thinstation.conf.buildtime.txt](https://github.com/Thinstation/thinstation/files/3698657/thinstation.conf.buildtime.txt)
[build.conf.txt](https://github.com/Thinstation/thinstation/files/3698659/build.conf.txt)

**Comment by mcsn747** [comment]
I see the difference: you have RECONNECT_PROMPT=ON option.
I added this option and had this behavior:
1. "Disconnect" button leads to the vmview main window.
2. "Disconnect and Log off" button leads to the vmview main window.
3. X button leads to "Click yes to reconnect" menu.
4. Logoff from Windows client leads to the vmview main window.

Then I changed option to RECONNECT_PROMPT=MENU: 
1. "Disconnect" button leads to desktop. No "Click yes to reconnect" menu showed.
2. "Disconnect and Log off" button leads to the vmview main window.
3. X button leads to desktop. No "Click yes to reconnect" menu showed.
4. Logoff from Windows client leads to the vmview main window.

It's strange that I can't go back to my initial state (without reconnect option), may be I should  clean chroot.

**Comment by mcsn747** [comment]
Ok, built a new chroot with latest changes (from yesterday). 

4.10 vmview client:
 1.  "Disconnect" -> reconnect prompt.
 2.  "Disconnect and Log off" -> reconnect prompt.
 3.  X button -> reconnect prompt.
 4.  Logoff from Windows vmview machine -> reconnect prompt.

5.2 vmview client:
 1.  "Disconnect" -> desktop.
 2.  "Disconnect and Log off" -> desktop.
 3.  X button -> desktop.
 4.  Logoff from Windows vmview machine -> desktop.

Here is my thinstation config file:
```

AUDIO_LEVEL=90
MIC_LEVEL=0
SESSION_0_TYPE=icewm
SESSION_0_AUTOSTART=on
SESSION_1_TYPE=vmview
SESSION_1_AUTOSTART=on
SESSION_1_VMVIEW_FULLSCREEN=true
SESSION_1_VMVIEW_ONCE=true
SESSION_1_ICON=ON
HIDE_CONTROLS=true
ICONS_CUT_SIZES="256x256 scalable"
TIME_ZONE=Asia/Yekaterinburg
TFTP_BLOCKSIZE=1024
BIND_MOUNT0="storage:/mnt/storage"
STORAGE_CONFIG1=/mnt/storage
USB_STORAGE_SYNC=on
LOCALE=en_US

VMVIEW_DEFAULTBROKER=vdi.server.loc
VMVIEW_AUTOCONNECT=TRUE
X_NUMLOCK=ON

# RECONNECT_PROMPT=MENU
# RECONNECT_PROMPT=ON


# XKEYBOARD="us,ru"
# X_KEYBOARD_OPTION1="XkbModel pc105"
# X_KEYBOARD_OPTION1="XkbLayout us,ru"
# X_KEYBOARD_OPTION3="XkbOptions grp:ctrl_shift_toggle"

SET_RESOLUTION_MULTIMONITOR_EXPAND='left'
SET_RESOLUTION_MULTIMONITOR_AUTOSCALE='scale'

NET_USE=BOTH
NET_USE_DHCP=on
NET_HOSTNAME=ts_*
NET_LINKWAIT=20
NET_DHCP_DELAY=20
NET_DHCP_TIMEOUT=10
NET_FILE_ENABLED=On
NET_FILE_METHOD=tftp
NET_TIME_SERVER=192.168.1.1
NET_REMOTE_ACCESS_FROM="0.0.0.0"
```

After that I took a @rohrbachger 's config and got the same results. The only difference is that rohrbachger have the icons on desktop and start-stop button. Without those button you cannot shutdown your thin client now.

**Comment by Thinstation** [comment]
I see that you have reconnect prompt # commented out. Is it enabled somewhere else?

**Comment by Thinstation** [comment]
Also maybe make sure you have fullsize bash installed. Some advanced dialog code might need "bashisms" to work.

**Comment by mcsn747** [comment]
> 
> 
> I see that you have reconnect prompt # commented out. Is it enabled somewhere else?

I built thinstation image several times. Maybe I lost reconnect prompt in config. Further I added RECONNECT_PROMPT=ON to my config.

> Also maybe make sure you have fullsize bash installed. Some advanced dialog code might need "bashisms" to work.

I have bash installed. Let's go back to the first message. 

Here is an example of my actions.
I press several times the Disconnect and Log off button, and every time I have reconnect prompt. After that I press "Disconnect" button and have no reconnect prompt. After that I can't call reconnect prompt any way.
The same thing happens if I press X button.

**Comment by Doncuppjr** [comment]
Did you figure it out?

**Comment by mcsn747** [comment]
Hi,  this year we tested several Thinstation builds and VMware clients:
1. Thinstation 6.1 + Horizon Client 4.10 = OK
2. Thinstation 6.1 + Horizon Client 5.5 = OK
3. Thinstation 6.1 + Horizon Client 2006 = OK
4. Thinstation 6.2.6 + Horizon Client 4.10 = Reconnect Y/N dialog immediately after loading
5. Thinstation 6.2.6 + Horizon Client 5.5 = Reconnect Y/N dialog immediately after loading
6. Thinstation 6.2.7 + Horizon Client 5.5 = Reconnect Y/N dialog immediately after loading
7. Thinstation 6.2.7 + Horizon Client 2006 = Reconnect Y/N dialog immediately after loading
Subject issue is not reproducted with new builds.

**Comment by Doncuppjr** [comment]
So this is fixed?

**Comment by mcsn747** [comment]
> 
> 
> So this is fixed?

Yes.
