### ISSUE TITLE
Vmware View - Dual Screen

### ISSUE THREAD

**Issue by rohrbachger** [Thinstation/thinstation#469]
As we want to use dual screens with Vmware view I run into a problem with
parameter --allmonitors.

As in /etc/cmd/vmview.global CMD_GLOBAL="run_vmview --fullscreen" is standard,
an additional parameter --allmonitor does not work. Obviously you can use only one from both.
I think it should be CMD_GLOBAL="run_vmview --allmonitors" 

--fullscreen is doing fullscreen on one screen, --allmonitors is doing fullscreen on all monitors.

So maybe the standard setting is to change, nobody else runś in the issue with 2 screens.

**Comment by Thinstation** [comment]
Done.
