### ISSUE TITLE
Background not working in 6.2

### ISSUE THREAD

**Issue by rohrbachger** [Thinstation/thinstation#470]
The background setting is not anymore applied.
build.conf  param desktop file:./backgrounds/Hive_Lite.jpg
On the client the file is under /etc/background.jpg

I probably found one typo in the code, unfortunately after fixing still it does not work.
6.2-Stable/ts/build/packages/xfwm4/build/extra/etc/xfwm4.functions

Line: 135
	for display in monitorVirtual{1,2,-1,-2}; do
		if [ -n "**$backgrund**" ]; then
I changed to "$background" but still no background.
There were some actual changes in the code.

**Comment by Doncuppjr** [comment]
Hmmm. fixing the typo worked for me. Can you send me the contents of ~/.config from the client that failed?

**Comment by rohrbachger** [comment]
Here the requested informations.
[.config.zip](https://github.com/Thinstation/thinstation/files/3690671/default.config.zip)

**Comment by Thinstation** [comment]
What kind of video card is this? The old desktop setting code worked for you?

**Comment by rohrbachger** [comment]
On one its standard Dell Optiplex 790, should be an Intel onboard
in the second one itś the same model, but a Zotac Geforce GT710. Using noveau.
This is for Dual Screen and working in general fine.
On both I have this missing background with 6.2 This has been working on both on 6.1 and before.
I have the splash screen switched on, as you have repaired it a while ago already with 6.1.

I'm using XFWM4 as window manager.  The background is not black, I think it is more very dark blue. I have tested now a lot still no success.
Just double checked, 6.1 with kernel Version 4.19.18.TS is working fine.
I attached the two config files.

[build.conf.txt](https://github.com/Thinstation/thinstation/files/3694309/build.conf.txt)
[thinstation.conf.buildtime.txt](https://github.com/Thinstation/thinstation/files/3694310/thinstation.conf.buildtime.txt)

**Comment by Doncuppjr** [comment]
O.k. It looks like we need both the old and new cold to handle all situations. Pushed, can you retest?

**Comment by rohrbachger** [comment]
git pull does not recognized any change
githubs last change was 14 hours ago.
Pushed really?

Today I tested, no improvement.

**Comment by Doncuppjr** [comment]
I pushed code that set the background the old way and new, between messages yesterday. Something changed in the way that X names display’s. When did you notice that backgrounds broke? If you use xfwm4.functions from commit 1ce84a39f, does it work?

**Comment by Thinstation** [comment]
Went a different way. Should be more universal now.

**Comment by rohrbachger** [comment]
Tested, working fine now
