### ISSUE TITLE
Thinstation 6.2 conf

### ISSUE THREAD

**Issue by sqnoc** [Thinstation/thinstation#472]
Hi,
my network card is not initialised in my image of thinstation 6.2 since the commit on Sep 27, 2019 (rebuild kernel).
I build it with allmodules parameters and without change the build.conf and thinstation.conf.builtime.
I had tested this image on HP dc5750 and Dell Optiplex Gx780.

**Comment by Thinstation** [comment]
What kernel module does it use?

**Comment by Thinstation** [comment]
Does the card come up without an address, or not at all?

**Comment by sqnoc** [comment]
The driver used is Intel e1000e:
ls -la /sys/bus/pci/devices/0000:00:19.0/
driver -> ../../../bus/pci/drivers/e1000e
And ifconfig return its MAC adress
In the previous version the fastboot/bin and fastboot/sbin directories doesnot contained the same file.
For exemple if I find "lspci" in 6.1: find -name lspci
./lib/sbin/lspci
./fastboot/sbin/lspci

same command in 6.2: find -name lspci
./lib/bin/lspci
./lib/sbin/lspci
./fastboot/bin/lspci
./fastboot/sbin/lspci

These path are linked to:
./lib/bin/lspci -> /fastboot/bin/lspci
./lib/sbin/lspci -> /fastboot/sbin/lspci
/fastboot/sbin/lspci
/fastboot/bin/lspci -> /bin/busybox

When I use "lspci" command it's busybox is used.

**Comment by Thinstation** [comment]
make sure param allfirmware true is in build.conf

**Comment by sqnoc** [comment]
Yes "allfirmware" is true in my build.conf.
I had disable fastboot and it work.
The problem is in FASTBOOT...

**Comment by Thinstation** [comment]
No. It only makes the actual problem harder to find.

**Comment by sqnoc** [comment]
Ok sorry.
I forgot to add autonet package in my build.conf (I use netfiles option and disable networkmanager).

I have change fastboot.service file to use FASTBOOT_URL:
After=systemd-udev-settle.service choose-network.service

And for the busybox link in /bin duplicated with same named file in /sbin I have added this lines in build file after line 1754:
        chroot ./tmp-tree /bin/busybox --install -s
        list_files_sbin=`find -P ./tmp-tree/sbin -type f -exec basename {} \;`
        list_files_bin=`find -P ./tmp-tree/bin -type f -exec basename {} \;`
        for file in $list_files_sbin; do
                ln -sf /sbin/$file ./tmp-tree/bin/$file
        done
        for file in $list_files_bin; do
                ln -sf /bin/$file ./tmp-tree/sbin/$file
        done

Best regards,
Stéphane

**Comment by sqnoc** [comment]
I think you must change /packages/base/etc/init.d/fastboot script in line 104:
- WPROGRESS=`cat -v /var/log/wget_progress |grep -e "%" |tail -n 1 |cut -c **63-65**`
+ WPROGRESS=`cat -v /var/log/wget_progress |grep -e "%" |tail -n 1 |cut -c **22-24**`

"cut -c 63-65" is collumn of the size file downloaded:
lib.squash            44% |**************                  |  **124M**  0:00:15 ETA

In the line 102 "while" check $WPROGRESS with the % progress collumn:
while [ "**$WPROGRESS" != "100"** ] && [ ! -z "`pidof wget`" ]; do

**Comment by Thinstation** [comment]
we want the percentage, not the size.
