### ISSUE TITLE
pxe boot failure

### ISSUE THREAD

**Issue by ecoutinho** [Thinstation/thinstation#479]
Hi,

After updating 6.2-Stable to the latest version, pxe boot of an EFI machine (Intel NUC7CJYH) stopped working. The boot process stops at

Loading initrd...OK

It doesn't try to download lib.squash from the ftp server.

I've been checking out previous versions and it turns out that it fails at commit

ceb6e428ca7064208099e11f65bd471e7be07e27

At the previous commit, it boots fine. Any idea on what changed that might be affecting the boot process?

Thanks,
Elio

**Comment by Thinstation** [comment]
A few kernels ago, the default unwinder changed from FramePointer to ORC. This necessitated an update to syslinux. We are are distributing a good working version, please make updates to your environment as necessary.

**Comment by ecoutinho** [comment]
I'm sorry, it still doesn't go past initrd. The syslinux.efi that the client downloads is the one from the build environment:

[root@TS_chroot /]$ ls -l /usr/share/syslinux/efi64/syslinux.efi
-rwxr-xr-x 1 root root 171400 Sep 11 16:15 /usr/share/syslinux/efi64/syslinux.efi
[root@TS_chroot /]$ pkginfo -i|grep -i syslinux
syslinux 6.04-pre2-2

Is this not compatible with kernel 5.3.6TS?

Thanks,
Elio

**Comment by Doncuppjr** [comment]
Hmmmm. It’s working over here in both qemu and vmware. Do you have any other machines to try? Is this a production network or private development network?

**Comment by ecoutinho** [comment]
I've tried on another machine and it boots fine, but it's 64b non EFI. I don't have another EFI machine. It's on production network.
How can I increase intrd logs? I have 'splash off' and tried 'bootverbosity 4' or 32 but I'm not getting any debug messages. I've noticed the client doesn't ask the dhcp server for an IP, after loading initrd. The network driver is 'r8169', which I've confirmed is part of initrd.

**Comment by Doncuppjr** [comment]
Do you have a development machine with two network interfaces and enough memory to run the DevStation VM? I heard somewhere that Syslinux would die if it receives a packet it wasn’t expecting.

**Comment by ecoutinho** [comment]
In the meantime I've got hold of a laptop with EFI, and it booted fine through pxe. It seems to be an issue with this hardware in particular. I'll try DevStation. Thanks

**Comment by Thinstation** [comment]
It's more about testing on a quiet network, DevStation makes that pretty easy, but however you get there is fine.

**Comment by ecoutinho** [comment]
I've installed DevStation, built with allmodules option, redirected the client to boot from DevStation and it also got stuck at:
Loading http://x.x.x.x/boot/initrd...ok
At this point the client stops replying to ping.
Is there any way to enable debug at this phase?
Thanks

**Comment by Thinstation** [comment]
I did a lot of tweaks to get things to be as quiet as they are. You would have to unpatch systemd, recompile the kernel without a cmd line, then it *might give you more information. 

The DevStation test was more to get you onto a quiet network, then to test DevStation. Did you create a new private network?, or just change where the client was pointing on your production network?

**Comment by ecoutinho** [comment]
They both were on a dedicated vlan, with no other traffic. It seems that it either can't mount initrd, or it mounts it but doesn't load the network driver. As further debug seems to be a not so easy task, I'll roll back to the commit previous to the kernel update.

**Comment by Doncuppjr** [comment]
Did the cursor stop blinking after loading initrd?

**Comment by ecoutinho** [comment]
There isn't any cursor throughout the boot process (vmlinuz or initrd).

**Comment by Thinstation** [comment]
Does anything like sha256 flash on the screen?

**Comment by Thinstation** [comment]
Does the screen clear, or just stay there after loading initrd indefinitely?

**Comment by ecoutinho** [comment]
It looks like this:

![image](https://user-images.githubusercontent.com/2861461/67292851-78032d00-f4db-11e9-9456-06c5a2cad06c.png)

**Comment by Doncuppjr** [comment]
If it stays there, then kernel execution did not happen.

So now the question is , Linux or Syslinux

You should be able test an older Syslinux, maybe the one from 6.1-Stable.

**Comment by ecoutinho** [comment]
But this same syslinux.efi works fine up until commit https://github.com/Thinstation/thinstation/commit/ceb6e428ca7064208099e11f65bd471e7be07e27 when kernel 5.2 was in use. It's only when the kernel is bumped to 5.3 that it fails.

**Comment by Thinstation** [comment]
O.k. Maybe 5.3 added some new randomization that’s confusing Syslinux. I’ll take a look at Syslinux channel

**Comment by ecoutinho** [comment]
OK, thanks

**Comment by Thinstation** [comment]
I think I see where the problem is. splash_progress is broken with pxe.
