### ISSUE TITLE
Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block

### ISSUE THREAD

**Issue by ravenich** [Thinstation/thinstation#480]
Hi, i'm new in thinstation. Tried to create simple freerdp only station. Stuck with first step. Create image on DevStation with options:
all xorg-video packages, xterm and openbox, extensions-x
initrdcmd "gzip"
fastboot false (because hwlistner.sh says so)
allfirmware and allres are true
lpxelinux: only splash=off console=tty1 LM=3
initrd size = 244565K
When i tried to boot with this image i get error "vfs unable to mount root fs on unknown block"
I try to edit lpxelinux to load_ramdisk=1 ramdisk_blocksize=4096 root=/dev/ram0 ramdisk_size=786432 and get "Kernel panic - not syncing: System is deadlocked on memory"
Same error on physical and virtual machine (same amount of RAM).
I think for my purposes (freerdp only) 1GB of RAM is more than enough, but i don't know which modules and firmware i need.

**Comment by Thinstation** [comment]
1GB will be enough, but the fingerprinting process to find out what parts you need is going to be more difficult. Initially providing every single kernel module, xorg module and firmware in a fully read-write state, might need 2gigs. 

Maybe figure out which xorg, then remove the others. Could you increase RAM on a test machine to get through this part?

**Comment by Doncuppjr** [comment]
Maybe do it in two runs. First run with fastboot enabled, get the kernel modules and xorg. Make a machine profile with them, then make a build fastboot disabled, still allfirmware, but not all xorg and not allmodules. run hwlister again to get the firmware.

**Comment by ravenich** [comment]
> 
> Maybe figure out which xorg, then remove the others. Could you increase RAM on a test machine to get through this part?

After increasing memory to 2 Gb everything works perfectly. Thanks for advice.
