### ISSUE TITLE
TS62 nx package obsolete

### ISSUE THREAD

**Issue by ecoutinho** [Thinstation/thinstation#484]
The NX package included on TS62 is 32b, so the libraries it needs are not present any more. It doesn't work. I've tested with a 64b version but also had dependencies issues. I ended up installing xrdp at the linux server, and connect to it using the RDP client (freerdp or rdesktop). As such, I propose that NX package is removed from TS 64b.

**Comment by Thinstation** [comment]
Well, that latest version of nx usb module won't compile against kernel 5.3, but other than that....
It needs updating, but dropping it might be a bit much.
