### ISSUE TITLE
Can't boot i686 HP T5745

### ISSUE THREAD

**Issue by enoch85** [Thinstation/thinstation#485]
Hi!

Thanks a ton for this software, I especially like the DEV image, what a great tool!

We have one issue though, we can't boot HP T5475 since it says that i686 aren't supported. If the support for i686 was removed, why did you do that?

If it's still possible to run i686 with the latest DevStation, how would I create the boot image? I've been reading the wiki but couldn't seem to find how that's done.

cc @Doncuppjr

**Comment by Doncuppjr** [comment]
I686 is 64 bit and should be supported. Where are you seeing that it is not?

**Comment by Thinstation** [comment]
Some older machines had a mixed boot protocol for EFI, and may not be compatible with the default boot loader. Try moving these machines to CSM boot instead.

**Comment by enoch85** [comment]
Thanks for your quick response. 

Actually I downgraded to ThinStation 5.6 yesterday and been trying all day to get it functional but without succeeding. In some cases I get to the ThinStation splash screen and then it just sits there, for hours. In some cases TFTP isn't even loading correctly which results in that it doesn't boot at all.

I'm guessing the [T5745](https://support.hp.com/ph-en/document/c01926343) isn't compatible with ThinStaion, even though I saw some posts regarding `modules.list` for that PC. I couldn't find so much info online, maybe you guys can help?

Right now I'm trying to get LTSP to work, and it loads the kernels alright, but not more than that. As you can see in the specs of this PC, it's very limited, and old. Hence my hunt in something that can run. I really hope ThinStation can be made working!

**Comment by Thinstation** [comment]
It's compatible. 1GB of RAM is a little tight, but if your only running a web browser or a remote desktop it should be enough.

**Comment by enoch85** [comment]
@Thinstation OK, that's promising. We only need to RDP from it.

With all your years of expertise, do you have any example config for `thinstation.conf.buildtime` or `modules.conf`? Do I need to activate something special in `build.conf` I read that some network modules doesn't work that well.

End goal here is to PXE boot from the DevStation. 

Btw, this is the error I'm getting on 6.2 (not actual picture from the ThinStation):
![image](https://user-images.githubusercontent.com/4511254/67972468-0465cc00-fc0f-11e9-9d44-e74e1f4955b9.png)

**Comment by Doncuppjr** [comment]
On the DevStation installer ISO, is a secondary image hwlister. Give that a shot.    On Thursday, October 31, 2019, 10:35:52 AM PDT, Daniel Hansson <notifications@github.com> wrote:  
 
 
Thanks for your quick response.

Actually I downgraded to ThinStation 5.6 yesterday and been trying all day to get it functional but without succeeding. In some cases I get to the ThinStation splash screen and then it just sits there, for hours. In some cases TFTP isn't even loading correctly which results in that it doesn't boot at all.

I'm guessing the T5745 isn't compatible with ThinStaion, even though I saw some posts regarding modules.list for that PC. I couldn't find so much info online, maybe you guys can help?

Right now I'm trying to get LTSP to work, and it loads the kernels alright, but not more than that. As you can see in the specs of this PC, it's very limited, and old. Hence my hunt in something that can run. I really hope ThinStation can be made working!

**Comment by enoch85** [comment]
> On the DevStation installer ISO, is a secondary image hwlister.

Thanks, that's what I'm trying to do. But how could I if I can't even boot from the ISO, or PXE? :)

**Comment by Thinstation** [comment]
If you have a system that needs a 32 efi boot loader, you might have to make a more customized build. You can start by switching to CSM mode(Legacy BIOS). That should allow you to develop your solution before worrying about he intricacies of boot loaders.

**Comment by Thinstation** [comment]
Well, I guess you have to stay with 5.6. 6.x is pure 64bit. I thought Intel stopped manufacturing 32bit only chips back in `02

**Comment by enoch85** [comment]
Thanks!
