### ISSUE TITLE
Link in Releases

### ISSUE THREAD

**Issue by maa7** [Thinstation/thinstation#488]
Hello,
In Releases (https://github.com/Thinstation/thinstation/releases) i see only 6.1.1 instead of 6.2.1

I tried also link https://github.com/Thinstation/thinstation/tarball/6.2-Stable
but this is for some unknown reason downloading file Thinstation-thinstation-6.1.1-425-g37d6c16.tar.gz

**Comment by Thinstation** [comment]
I'm not sure why your getting an old tarball. Perhaps there is a proxy between you and github. I tested the link and download the latest that is in git. I'll make the release Monday.
