### ISSUE TITLE
xkb layout indicator

### ISSUE THREAD

**Issue by ghost** [Thinstation/thinstation#491]
Any ideas to show indicaor?
xfce4-xkb-plugin-0.5.4.3 - do not cofigure(need corrections)
any binary solution? may be python script?

**Comment by Thinstation** [comment]
It was easy enough to add the plugin. Pushed.
There is no code to handle setting it up though. Where should it go?

**Comment by ghost** [comment]
https://goodies.xfce.org/projects/panel-plugins/xfce4-xkb-plugin
First - try build without **chroot** env, and it do not builds.
After chroot it builds, but provide executable file - not library.
Second try to install it maually in **xfwm4** folder /lib/xfce4/pannel/plugins

How to add it on pannel? Need example for skel/.config/ xml

**Comment by Doncuppjr** [comment]
I pushed the port to github. try mkrepackage < port name >, then add the package to your build.

**Comment by Thinstation** [comment]
Pushed.

**Comment by ghost** [comment]
and it do not configurable with ts config script...
only manual editing panel xml config in skel

**Comment by Doncuppjr** [comment]
I pushed code yesterday to enable this plugin if it is detected.
