### ISSUE TITLE
xrandr options not working after SCREEN_OFF_TIME

### ISSUE THREAD

**Issue by fanuelsen** [Thinstation/thinstation#492]
Hello, i have a dual screen setup on some of my thinclients that expands the desktop. After the screens goes to sleepmode and i wake them back up, the screen changes to mirror. If i reload the session it goes back to the way it should be. 

Is this a xrandr issue? Looks to me like it wont resume after sleepmode.

my current config looks like this:
SCREEN_RESOLUTION="1920x1200"
XRANDR_OPTIONS="dualscreen"

**Comment by Thinstation** [comment]
That's probably a bug in the acpi, but we could possibly set a hook that resets video on wake.

**Comment by fanuelsen** [comment]
How could we proceed to do this? Could you point me in the right direction?

Thanks :)

**Comment by Thinstation** [comment]
There is an acpi package. After the first build that uses it, it will be populated with almost everything we need. The scripts are in build/packages/acpi/etc/acpi. We need to add one that will process TS variables on resume and rerun the xrandr command.

**Comment by Thinstation** [comment]
might need to play with pm-utils as well.

**Comment by Thinstation** [comment]
you might only need to make a quirk file.

**Comment by fanuelsen** [comment]
I'm not following here, whats a quirk file?

**Comment by Doncuppjr** [comment]
pm-utils has a vga quirk database made up of files.

**Comment by Thinstation** [comment]
If you configure the display's via xfwm display configuration instead of xrandr commands, does sleep and restore work correctly?

**Comment by Thinstation** [comment]
I'm thinking maybe we can use the new display settings feature of xfce 4.14.

**Comment by fanuelsen** [comment]
I get the same result if i configure it manually via the display settings in xfwm. It switchs back to mirror.

**Comment by Doncuppjr** [comment]
Which vga adapter? Xorg module?

**Comment by Thinstation** [comment]
My test systems automatically go into span, so I wonder why your adapter is defaulting to mirror. Accelerated driver or generic vesafb?

**Comment by fanuelsen** [comment]
xorg7-intel i use this on my nucs

**Comment by Thinstation** [comment]
I can't reproduce this error. 
Admittedly, I'm not using a NUC, but just a cheesy laptop with an Intel chipset. I made the following changes to my default config, then built with --allmodules.

#SET_RESOLUTION_MULTIMONITOR_EXPAND='mirror'
#SET_RESOLUTION_MULTIMONITOR_AUTOSCALE='scale'
SCREEN_BLANK_TIME=1
SCREEN_SUSPEND_TIME=2
SCREEN_OFF_TIME=3
XRANDR_OPTIONS="dualscreen"
USE_XRANDR=true

This worked without issue. Even after extended display off time, resume was still in "Extended" mode.

You can send me a unit, and I'll tinker with it.

**Comment by fanuelsen** [comment]
This problem is related to us running our thinstation building environment inside a podman container without running it in privileged mode. Simply adding --privileged solved the problems. Thanks for taking the time. And sorry for not finding this out sooner.
