### ISSUE TITLE
openkiosk reset timer not working

### ISSUE THREAD

**Issue by staples1347** [Thinstation/thinstation#494]
In branch: 6.2-Stable, it looks like commit: https://github.com/Thinstation/thinstation/commit/a8e39d34de0ab475e4fec426cdf6e9c466540092 broke the openkiosk reset timer option by removing the single quotes surrounding $OK_RESET_TIMER when echoing the user_pref:

`echo 'user_pref("openkiosk.session.inactiveTerminal.minutes", $OK_RESET_TIMER);' >> $OK_PREFS`

should be

`echo 'user_pref("openkiosk.session.inactiveTerminal.minutes", '$OK_RESET_TIMER');' >> $OK_PREFS`

**Comment by ecoutinho** [comment]
Thanks for pointing that out! I've just submitted a fix.

**Comment by Thinstation** [comment]
Merged.
