### ISSUE TITLE
imagemagick port do not installs in build/packages

### ISSUE THREAD

**Issue by ghost** [Thinstation/thinstation#497]
try install with
prt-get install imagemagick
```
prt-get: installing /ts/ports/opt/imagemagick
=======> Package '/ts/ports/opt/imagemagick/imagemagick#7.0.8-62-1.pkg.tar.xz' is up to date.
prt-get: installing imagemagick 7.0.8-62-1

-- Packages installed
imagemagick

prt-get: installed successfully
```
but directorry build/packages/imagemagick do not created.
sloved by manualy creating(from imagemagick#7.0.8-62-1.pkg.tar.xz to etc bin lib folders), but it is not normal.
Were is my misstake?

sane port alredy have that problem.
prt-get install sane 
says: package sane is installed
but no build/packages/sane directory

**Comment by Thinstation** [comment]
Ports and Packages are separate but related entities. Much of the administration of TS is maintaining those relationships. I have never needed all of imagemagick, but if you want a "package" of imagemagick that is based on the "port", try 
mkrepackage imagemagick
