### ISSUE TITLE
mimeapps.list generating

### ISSUE THREAD

**Issue by ghost** [Thinstation/thinstation#502]
Anyone try generate mimeapps.list from .desktop files?
on 6.2 i am have problem - files do not opens with any default app - it ask every session...
File mimeapps.list do not exist in any place. May be i am lose some option in build.conf?
it depend on port desktop-file-utils of gnome-core package.
It realy needs all gnome-core to enable mime associations just for generating /lib/applications/mimeinfo.cache?
Maybe just generate it at buildtime by run update-desktop-database from build system not depend on gnome-core package.

**Comment by Thinstation** [comment]
I guess we could move that to base.

**Comment by Thinstation** [comment]
Actually, xorg7 is a better place, the utility belongs to freedesktop.

**Comment by ghost** [comment]
I am think mime associations file can be created at build time once forever. I am try that tomorrow.

**Comment by ghost** [comment]
https://github.com/Thinstation/thinstation/pull/503

**Comment by Thinstation** [comment]
Please try latest commit.
