### ISSUE TITLE
6.2.2 cannot UEFI boot

### ISSUE THREAD

**Issue by maa7** [Thinstation/thinstation#506]
Hello,
On 6.1 and 6.1.1 version I successfully created bootable usb flash drives for UEFI boot Intel NUC7CJYH.
But after change version to 6.2.2 my NUC cannot boot in UEFI:
![DSC02668_](https://user-images.githubusercontent.com/45234995/70346701-f4758380-186f-11ea-8d0c-0810c3aad7ba.png)

**Comment by Thinstation** [comment]
Try with systemd-boot-iso

**Comment by maa7** [comment]
How to create systemd-boot-iso usb flash drive from Windows?

**Comment by Doncuppjr** [comment]
It’s isohybrid , so you should be able to use any image writer to write the iso like an hd image to a thumbdrive

**Comment by maa7** [comment]
Which image should I write, and where is it located?

**Comment by Thinstation** [comment]
systemd-boot-iso

**Comment by maa7** [comment]
where is it located?

**Comment by Doncuppjr** [comment]
bootimages/systemd-boot-iso

**Comment by maa7** [comment]
there is no such folder:
![Image_ts622](https://user-images.githubusercontent.com/45234995/70433799-a771f700-1a93-11ea-9f68-948324cde576.png)

**Comment by Thinstation** [comment]
You might be declaring which images you want in your build.conf. That’s
unnecessary and you should comment out that line and rebuild.

**Comment by maa7** [comment]
I tried to write usb flash drive (using Rufus 3.8)
systemd-boot-iso\thinstation-efi.iso
and
refind-iso\thinstation-refind.iso

but no success - cannot boot in uefi:
"A bootable device has not been detected"

**Comment by Thinstation** [comment]
Some bug fixes.....
After a pull,
You should be able to write images for systemd-boot-iso as an ISO image in Rufus.
IF you use FASTBOOT, then.... you will also need to make sure of the following.
in .conf.buildtime, you will need a mount declared for the volume name to /boot(ALL CAPS), ie
MOUNT_0="LABEL=BOOT     /boot           auto    x-mount.mkdir,defaults  0	0"

in Rufus, 
Select your disk
Select Disk or ISO image
double click "SELECT", and select thinstation-efi.iso
In Partition Schemea, select GPT
UEFI (non CSM) should change in Target system
make sure that Volume label  is equal to whatever you put in your thinstation.conf.buildtime for MOUNT_0
Click start.

**Comment by maa7** [comment]
I reinstalled using Thinstation-thinstation-6.2.2-32-gea3326d.tar.gz.
But now systemd-boot-iso\thinstation-efi.iso show on boot screen:
_"SHA256 validated"_
and cannot boot.

**Comment by Thinstation** [comment]
The sha256 means it made it to the bootloader. Maybe your having another
issue. What kind of system? RAM, CPU, VIdeo? Image specs?

**Comment by maa7** [comment]
Intel NUC7CJYH, Celeron J4005, 4GB RAM.
(worked great with UEFI boot on 6.1.1 version with same config)

**Comment by Doncuppjr** [comment]
The kernel unwinder changed, and the bootloaders needed updating. You could try the kernel from 6.1 and see what happens. I also updated refind last night, so another test there as well.
