### ISSUE TITLE
Install on a hard drive or flash drive

### ISSUE THREAD

**Issue by shaulyn** [Thinstation/thinstation#509]
please tell me how to install the system on a hard drive or flash drive? the system is loaded but the graphical shell does not start. 

/lib is not a mountpoint
Fastboot was enbled, but something went wrong with the transfer or mount

Dropping to shell

**Comment by Doncuppjr** [comment]
When using fastboot, the volume name is critical. By default, it’s looking for a volume named “boot” case sensitive. The volume should contain the lib.squash that the system needs.


Sent from Yahoo Mail for iPhone


On Tuesday, December 10, 2019, 5:35 AM, shaulyn <notifications@github.com> wrote:


please tell me how to install the system on a hard drive or flash drive? the system is loaded but the graphical shell does not start.

/lib is not a mountpoint
Fastboot was enbled, but something went wrong with the transfer or mount

Dropping to shell

**Comment by shaulyn** [comment]
I laid out my configs below. after assembling the image, I copy the thinstation file. from the boot-itages directory and write to the USB flash drive through the rufus program

build.conf 
`
module usb-storage
module autofs4                  # Automount and autofs support
module vfat                     # Fat and VFat file system support
module ntfs                     # NTFS file system support
module ext4                     # Ext4 file system support



package ts-classic             
package automount
package autonet
package alsa


package xorg7-vesa    
package xorg7-ati    
package xorg7-amdgpu
package xorg7-intel 

package locale-en_US  
package locale-ru_RU 

package freerdp         
package rdesktop             
package vncviewer               
package xorg7vnc              
package xterm               
package ssh                     


package samba-client    
package scp      


package gemplus410 
package ccidreader            
package asedriveiiie-usb                                                                                                                                                               


package gtk-2.0                 
package gtk-3.0
package gtk-theme-adwaita
package icons-cursor            
package icons-hicolor    
package icons-adwaita
package fonts-TTF-BH 
package fonts-TTF-vera

package fonts-TTF-liberation
package fonts-TTF-noto

package lshw
package e3  


param fastboot       true   
param tsuser         rem
param tsuserpasswd   12345 

param rootpasswd     12345  

param xorgvncpasswd  1q2w3e              
param storagepasswd  pleasechangeme 
param dialuppasswd   pleasechangeme
param sambapasswd    pleasechangeme 
param bootlogo       true                                                                                                                                                                                            use of the Boot splash.
param boottheme      default                                
param splash         silent
param fbmtrr         0  
param fbsm           ywrap 


param desktop file:./backgrounds/Hive_Lite.jpg          # Custom image to load a                                                                                                                                                             s desktop background
param defaultconfig  thinstation.conf.buildtime         # The file with default                                                                                                                                                              setup.  No other config file is found
                                                        #  during boot.
param basename       thinstation                        # Used for all config/tf                                                                                                                                                             tp/scp file names
param basepath       ts6.2                              # Used to determine path                                                                                                                                                              to tftp/scp files
param baseurl        http://www.doncuppjr.net           # Used to determine url                                                                                                                                                              to wget files
#param baseurl        http://192.168.78.17              # Used to determine url                                                                                                                                                              to wget/http files - your local web server
#param baseurl        'http://${SERVER_IP}'             # Used to determine url                                                                                                                                                              to wget/http files - if you wan't to use a web server on the same server as the                                                                                                                                                              TFTP server
#param keyfile        ./id_rsa                          # Path for private key f                                                                                                                                                             ile used for ssh/scp
#param knownhosts     ./known_hosts                     # Path for ssh known_hos                                                                                                                                                             ts file for ssh/scp
#param localpkgs      false                             # to determine is PKG fi                                                                                                                                                             les are to be loaded locally
#param fulllocales    true                              # Use full locale suppor                                                                                                                                                             t for packages
#param icaencryption  false                             # Use ica encryption sup                                                                                                                                                             port, add 290k to image
param haltonerror    false                              # Will halt on error, de                                                                                                                                                             fault is true
param hardlinkfs     true
param sametimestmp   true                               # When enabled, the time                                                                                                                                                             stamps for all files and folders will be set to 00:00 of todays date in your tim                                                                                                                                                             ezone
param initrdcmd      "gzip"                             # Compression mode and l                                                                                                                                                             evel of initrd file. none, gzip -9, lzma -9 ,bzip2 -9
param bootverbosity   3                                 # Increased vebosity whe                                                                                                                                                             n booting TS
                                                        #   0 no verbose message                                                                                                                                                             s
                                                        #   1 boot
                                                        #   2 network
                                                        #   4 init
                                                        #   8 kernel
                                                        #  16 modules
                                                        #  32 packages
                                                        #  64 email bootlog file                                                                                                                                                              to SMTP server & user set in
                                                        #     thinstation.conf f                                                                                                                                                             ile.  This will only work
                                                        #     if networking is w                                                                                                                                                             orking.
                                                        #
                                                        #  Combinations can be u                                                                                                                                                             sed (e.g. 24 does Kernel and Module Messages)

#!!Advanced
# Leave this alone unless you can t download (wget required on your Linux box):
param downloads         /downloads
param bootimages        "iso syslinux pxe refind"
#param bootserver        "192.168.1.1"          # Used for the pxe image config                                                                                                                                                              files to specify where to download
                                                                               #                                                                                                                                                              the syslinux image from. Result is generated in
                                                                               #                                                                                                                                                              /ts/build/boot-images/pxe/boot/lpxelinux/pxelinux.cfg/default
                                                                               #                                                                                                                                                              so that you can specify APPEND initrd=http://<bootserver>/boot/initrd
param syslinuxtheme     "default"
#param httpproxy        http://192.168.1.2:8080

#param bootfssize     50%                               # Modify the size of the                                                                                                                                                              tmpfs filesystem

package alltimezone
param allres            true            # Includes a lot of resolution splash im                                                                                                                                                             ages for live-cd s
param allfirmware       true            # Includes a lot of firmwares for live-c                                                                                                                                                             d s
param earlymicrocode    false           # Builds microcode initramfs for early l                                                                                                                                                             oading
                                        # by kernel. Needs kernel with MICROCODE                                                                                                                                                             _EARLY=y.
param blacklist "snd-pcsp.ko pcspkr.ko"
#param mesa_3d disable                  # The Mesa 3D Graphics Library disable
`
thinstation.conf.buildtime
`AUDIO_LEVEL=90
MIC_LEVEL=0
SESSION_0_TYPE=freerdp
SESSION_0_AUTOSTART=on

FREERDP_SELECT_SERVER=true
FREERDP_SERVER_0="SELECT_USER 10.10.2.2"
FREERDP_SERVER_0_OPTIONS="/u:' ' /d:DIB5 /cert-tofu /cert-ignore /fonts -themes -bitmap-cache /rfx /smartcard"

TIME_ZONE=Europe/Moscow
NET_TIME_SERVER=us.pool.ntp.org
USB_STORAGE_SYNC=on
LOCALE=en_US

NET_FILE_ENABLED=Off
STORAGE_CONFIG1=/mnt/disk/sdb/part1
STORAGE_CONFIG2=/mnt/usbdevice/sda1

NET_USE_DHCP=Off
NET_IP_ADDRESS=10.10.3.248
NET_MASK=255.255.248.0
NET_GATEWAY=10.10.1.254
NET_DNS1=8.8.8.8

MOUNT_0="LABEL=boot     /boot           auto    x-mount.mkdir,defaults  0       0"
MOUNT_1="LABEL=home     /home           auto    x-mount.mkdir,defaults  0       0"
MOUNT_2="LABEL=swap     swap            swap    defaults        0       0"
`

**Comment by Thinstation** [comment]
Can you pass the usb through to the VM you are hosting your build on?
If so, and if it is recognized as sdb, then just type 
flash gpt

**Comment by shaulyn** [comment]
No I can not

**Comment by Thinstation** [comment]
After a pull,
You should be able to write images for systemd-boot-iso as an ISO image in Rufus.
IF you use FASTBOOT, then.... you will also need to make sure of the following.
in .conf.buildtime, you will need a mount declared for the volume name to /boot(ALL CAPS), ie
MOUNT_0="LABEL=BOOT /boot auto x-mount.mkdir,defaults 0 0"

in Rufus,
Select your disk
Select Disk or ISO image
double click "SELECT", and select thinstation-efi.iso
In Partition Schemea, select GPT
UEFI (non CSM) should change in Target system
make sure that Volume label is equal to whatever you put in your thinstation.conf.buildtime for MOUNT_0
Click start.

**Comment by shaulyn** [comment]
Can you pass the usb through to the VM you are hosting your build on?
If so, and if it is recognized as sdb, then just type
flash gpt

defined as /dev/sdc

**Comment by Thinstation** [comment]
Edit the script /ts/bin/flash and change sdb to sdc

**Comment by shaulyn** [comment]
Device     Boot Start      End  Sectors  Size Id Type
/dev/sdc1  *     2048 30965759 30963712 14.8G  c W95 FAT32 (LBA)

+ case $1 in
+ mkgptdrv -p ESP:2g:boot -p l:0:home -o /build/boot-images/refind /dev/sdc
All data on the selected device is about to be overwritten!
Are you sure you want to do this?


Invalid response.****

**Comment by Thinstation** [comment]
try mkgptdrv -f -p ESP:2g:boot -p l:0:home -o /build/boot-images/refind /dev/sdc

**Comment by shaulyn** [comment]
the same mistake as in the previous post

mkgptdrv -f -p ESP:2g:boot -p l:0:home -o /build/boot-images/refind /dev/sdc
All data on the selected device is about to be overwritten!
Are you sure you want to do this?


Invalid response.

**Comment by Thinstation** [comment]
I'm guessing your trying to script this, and can't type 'y', so try export AGREE=true, then the command

**Comment by shaulyn** [comment]
thanks a lot, it seems to have worked

**Comment by fstrier** [comment]
Hi everyone! I´m beginning to use linux/unix and I need rdp client from a small GIGABYTE gb-blce-4105c computer. Was not possible to boot, same problem than this topic, but I can´t found the conf files that you told here. I used RUFUS to create the USB bootable. I can`t disable fastboot on UEFI.
I appreciate your help.

**Comment by Thinstation** [comment]
After doing the initial unwind of the chroot environment, try the following.
enter the chroot
prt-get install rufus
stb
then use the image from 
build/boot-images/systemd-boot-iso

**Comment by fstrier** [comment]
Sorry, is a little bit hard to understand. I read what you wrote on 10-dec-2019, I do not understand what is .conf.buildtime.
I just have 2 files thinstation.conf and loader.conf, and no more.
I will try again with RUFUS choosing GPT.

**Comment by fstrier** [comment]
Also I used the file TS-6.2.4-installer-0220.ISO. Is it right? thanks a lot

**Comment by Thinstation** [comment]
Depends on what you are trying to do. Install the development environment, yes. Deploy your own images, no.

**Comment by fstrier** [comment]
OK, I understand now I must build my own enviroment, at first booting in a VM Development Station. From there I suposse I will can build what I need. Not easy like at tought, but I want to avoid using MSFT for a simple RDP client.

**Comment by Doncuppjr** [comment]
It’s really easy, just not the same as everybody else. A slight mind shift, and you’ll be good to go.

**Comment by fstrier** [comment]
> After doing the initial unwind of the chroot environment, try the following.
> enter the chroot
> prt-get install rufus
> stb
> then use the image from
> build/boot-images/systemd-boot-iso

Hi, I build my ISO file using devstation and following the youtube help but it doenst work. I need to understand when you say "enter the chroot", "prt-get install rufus" and "stb".
Sorry for the simple questions that I can't resolve.

**Comment by fstrier** [comment]
Also on the build file, I dont know which machine I must choose from the list: easy for VMware, but not for real hardware. I have a thin client GIgabyte. 4105C.
Thanks again.

**Comment by fstrier** [comment]
> After doing the initial unwind of the chroot environment, try the following.
> enter the chroot
> prt-get install rufus
> stb
> then use the image from
> build/boot-images/systemd-boot-iso

OK, I made all of this, but I can't boot. Now the error is:
Error loading \boot\vmlinuz: Access denied
I'm using a GIGABYTE thinclient 4105C.
Thank you again!

**Comment by Doncuppjr** [comment]
Disable secureboot

**Comment by fstrier** [comment]
OK I did it, now I just see a cursor blinking, not prompt/GUI
