### ISSUE TITLE
Network settings not applied in DevStation

### ISSUE THREAD

**Issue by CendioOssman** [Thinstation/thinstation#510]
The current version of DevStation is unfortunately broken and does not apply network settings from `thinstation.conf.user`. The problem is that it has Python 2.x code in it, but runs it through `python`, which is Python 3.x in the DevStation image.

Log output:

```
  File "<string>", line 1
    import uuid;print str(uuid.uuid1());
                        ^
SyntaxError: invalid syntax
```

Is a workaround possible until an update is out?

**Comment by Doncuppjr** [comment]
Try Updating DevStation, and reboot.

    On Thursday, December 12, 2019, 05:58:56 AM MST, Pierre Ossman (Work account) <notifications@github.com> wrote:  
 
 
The current version of DevStation is unfortunately broken and does not apply network settings from thinstation.conf.user. The problem is that it has Python 2.x code in it, but runs it through python, which is Python 3.x in the DevStation image.

Log output:
  File "<string>", line 1
    import uuid;print str(uuid.uuid1());
                        ^
SyntaxError: invalid syntax

Is a workaround possible until an update is out?

**Comment by CendioOssman** [comment]
I have. It claims it is fully updated. Also note that I just downloaded and installed this image.

**Comment by Doncuppjr** [comment]
I generated a new image a few minutes ago.
    On Thursday, December 12, 2019, 06:36:54 AM MST, Pierre Ossman (Work account) <notifications@github.com> wrote:  
 
 
I have. It claims it is fully updated. Also note that I just downloaded and installed this image.

**Comment by CendioOssman** [comment]
Ah, I see. It did download something now. Unfortunately something seems to have gone wrong as I now get "Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)" :/

**Comment by CendioOssman** [comment]
Tried it again and same problem, so no fluke unfortunately. I can see something about "initrd: FAILED" during the update, but it's difficult to get any details as you cannot scroll and the window closes once it is done.

**Comment by Thinstation** [comment]
It’s just the checksum, failing is how it knows it needs to update.

**Comment by Doncuppjr** [comment]
Maybe call sync before you reboot.
    On Thursday, December 12, 2019, 06:51:19 AM MST, Pierre Ossman (Work account) <notifications@github.com> wrote:  
 
 
Tried it again and same problem, so no fluke unfortunately. I can see something about "initrd: FAILED" during the update, but it's difficult to get any details as you cannot scroll and the window closes once it is done.

**Comment by CendioOssman** [comment]
Same issue with a `sync` unfortunately. :/

Anything I can do to debug it?

**Comment by Doncuppjr** [comment]
md5 sum all the files in boot
I tried over here without issue.
    On Thursday, December 12, 2019, 08:16:06 AM MST, Pierre Ossman (Work account) <notifications@github.com> wrote:  
 
 
Same issue with a sync unfortunately. :/

Anything I can do to debug it?

**Comment by CendioOssman** [comment]
Found the issue. Apparently the system now requires more memory than suggested. The OOM killer was messing with the update (missing error handling since the UI still said ok?) and screwing things up.

After increasing to 4 GB the update went through.


And I can report that the new image fixes the Python bug. Thanks. :)

Unfortunately the network still doesn't work. Although an "Ethernet" configuration is created, it still prefers to use the automatic "ens192" connection. Is there something in the configuration I've overlooked?

**Comment by Doncuppjr** [comment]
I actually didn't do that piece of integration. Might be the networkmanager changed something, and now we need to set something else. I'll look into it, but it's also a extra reverse engineering.
    On Thursday, December 12, 2019, 08:58:42 AM MST, Pierre Ossman (Work account) <notifications@github.com> wrote:  
 
 
Found the issue. Apparently the system now requires more memory than suggested. The OOM killer was messing with the update (missing error handling since the UI still said ok?) and screwing things up.

After increasing to 4 GB the update went through.

And I can report that the new image fixes the Python bug. Thanks. :)

Unfortunately the network still doesn't work. Although an "Ethernet" configuration is created, it still prefers to use the automatic "ens192" connection. Is there something in the configuration I've overlooked?

**Comment by Thinstation** [comment]
I uncommented the following lines in Tweak DevStation, and all works as it is supposed to.
NET_IPV4_MODE=manual
NET_IPV4_ADDRESS=192.168.1.10/24
NET_IPV4_GATEWAY=192.168.1.1
NET_IPV4_DNS1=192.168.1.1
NET_IPV4_DNS2=8.8.8.8
NET_IPV4_DNS_SEARCH=thinstation.local
NET_HOSTNAME=DevStation_*

**Comment by CendioOssman** [comment]
That's odd.

I looked through the journal on the machine, but couldn't really see any issues. My config is very similar as yours:

```
#NET_USE=WLAN
NET_IPV4_MODE=manual
NET_IPV4_ADDRESS=10.47.255.120/16
NET_IPV4_GATEWAY=10.47.255.0
NET_IPV4_DNS1=10.47.255.0
#NET_IPV4_DNS2=8.8.8.8
NET_IPV4_DNS_SEARCH=lkpg.cendio.se
NET_HOSTNAME=DevStation_*
#NET_TELNETD_ENABLED=OFF
```

We have IPv6 configured on this network. Could that be a factor? The "ens192" config is oddly setup with IPv4 disabled and IPv6 in auto.

**Comment by Doncuppjr** [comment]
Is that a typo, or do you actually have those two values on the same line?


Sent from Yahoo Mail for iPhone


On Friday, December 13, 2019, 5:14 AM, Pierre Ossman (Work account) <notifications@github.com> wrote:


That's odd.

I looked through the journal on the machine, but couldn't really see any issues. My config is very similar as yours:
#NET_USE=WLAN
NET_IPV4_MODE=manual
NET_IPV4_ADDRESS=10.47.255.120/16
NET_IPV4_GATEWAY=10.47.255.0
NET_IPV4_DNS1=10.47.255.0
#NET_IPV4_DNS2=8.8.8.8
NET_IPV4_DNS_SEARCH=lkpg.cendio.se
NET_HOSTNAME=DevStation_*
#NET_TELNETD_ENABLED=OFF

We have IPv6 configured on this network. Could that be a factor? The "ens192" config is oddly setup with IPv4 disabled and IPv6 in auto.

**Comment by CendioOssman** [comment]
Which two values? Did github perhaps mangle something when it converted a comment to mail?

**Comment by Thinstation** [comment]
what are the contents of 
/etc/NetworkManager/system-connections ?

**Comment by CendioOssman** [comment]
Only `Ethernet.nmconnection` which has the settings from `thinstation.conf.user`.

**Comment by Thinstation** [comment]
But if config doesn’t agree?

**Comment by CendioOssman** [comment]
The contents of that file matches perfectly what I've configured. The problem is that NetworkManager isn't automatically activating those settings, instead preferring some automagically generated "ens192" config.

If I click the NM icon in the tray and manually select the "Ethernet" config then everything works fine. But I'd very much like the machine to boot with the correct configuration right away.

**Comment by Thinstation** [comment]
For sure, send the output of systemd-analyze plot > boot.svg

**Comment by Thinstation** [comment]
I see the problem. Stuff just changing......

**Comment by CendioOssman** [comment]
Great. Let us know when an update is ready and we can test it here as well.

**Comment by Thinstation** [comment]
Fixed. That was a hard one.

**Comment by CendioOssman** [comment]
Yay! I can confirm I'm seeing it fixed after an upgrade here as well. Nice work. :)
