### ISSUE TITLE
Get RDP running?

### ISSUE THREAD

**Issue by sr10952** [Thinstation/thinstation#517]
Hi, maybe I am doing something wrong, but I downloaded the latest ISO and see only a Terminal window available. How do I get RDP on this?
![vmconnect_2019-12-27_09-45-54](https://user-images.githubusercontent.com/32495578/71521201-b2979600-288d-11ea-822d-6487efb7760f.jpg)

**Comment by Thinstation** [comment]
That's the installer for DevStation, a special build of thinstation for making more thinstation builds.

Maybe you want the Multi-client Demo ISO
https://sourceforge.net/projects/thinstation/files/LiveCD/TS-Multiclient-Desktop-LiveCD-Demo.iso/download
