### ISSUE TITLE
MTU modification

### ISSUE THREAD

**Issue by mball212358** [Thinstation/thinstation#518]
All,
Whats the best way to modify the MTU settings on a thinstation build?  Apologize if this isn't the right spot for this, I'm new here.
Thanks,
Matt

**Comment by Doncuppjr** [comment]
NET_MTU="1500"

**Comment by mball212358** [comment]
Don, Thanks for the quick response.  I just tried adding that to the thinstation.defaults file with no success.  However, I'm in a unique environment where I get provided a thinstation ISO (I can't build my own) and a script to modify things like VDI connection server, thinstation.defaults etc.  I've made that change to the thinstation.defaults file, ran the iso package script and verified that the setting is persistent on the new thinstation ISO boot up, but MTU is still at 1500.  I need to change it to 1300.  Should that NET_MTU setting be "baked" in on the initial ISO generation? If so, then me modifying it on the provided ISO won't work.
Is there an alternative location that the MTU setting could be changed?  Like in an init network script?
Thanks in advance,
Matt

**Comment by Doncuppjr** [comment]
Is your ISO using networkmanager or autonet? You can place many simple settings on the kernel cmd line. Edit isolinux.cfg or syslinux.cfg accordingly.

**Comment by mball212358** [comment]
I believe NetworkManager

**Comment by Doncuppjr** [comment]
You might need to completely configure the network settings. 
https://github.com/Thinstation/thinstation/blob/6.2-Stable/ts/build/conf/networkmanager.conf.sample
https://github.com/Thinstation/thinstation/blob/6.2-Stable/ts/build/packages/networkmanager/build/extra/etc/init.d/nmcreatesysconn

**Comment by Doncuppjr** [comment]
I think you might also need full bash.

**Comment by Doncuppjr** [comment]
Hmmm. Thought I fixed that already. Anyways. git pull, update networkmanager and rebuild
