### ISSUE TITLE
FreeRDP updates

### ISSUE THREAD

**Issue by N0odlez** [Thinstation/thinstation#519]
Hi All,

It's been a while but I'm back at it. I've been trying to build the latest github branch of FreeRDP as they have rewritten the usb redirection code that now workes flawlessly. I was wondering if either you could let me know how to build this myself or to build it and update the repo?

I've tried prt-get update freerdp but as I say that fails.

Many thanks

**Comment by Thinstation** [comment]
prt-get update -fr -if freerdp
update freerdp
build

**Comment by N0odlez** [comment]
Worked a charm. May thanks for that :)
