### ISSUE TITLE
freerdp autologin

### ISSUE THREAD

**Issue by comsyspro** [Thinstation/thinstation#520]
I want to autoconnect with the freerdp package. For that I created a thinstation.conf-macaddress file booted via pxe server. The problem is that I can't find any SESSION option like SESSION_0_FREERDP_REMOTEUSER="username" or something like SESSION_0_FREERDP_PASSWORD="password" where you can fill out the credentials to autoconnect. So where can you change the package files so you could add these two variables? Or would there be a possibility to execute a custom script in a SESSION (something like for example SESSION_1_BASH="xfreerdp /u:username /p:password /v:server")?

Any ideas, help, solution?

**Comment by Doncuppjr** [comment]
Still working on that feature. For now, remove freerdp.getuser and freerdp.getpass , then just pass them in the options for the session.

**Comment by comsyspro** [comment]
Thank you, now it's working.
