### ISSUE TITLE
How to download version 6.2.3 tar.gz?

### ISSUE THREAD

**Issue by maa7** [Thinstation/thinstation#521]
I tried link https://github.com/Thinstation/thinstation/tarball/6.2-Stable
but this is downloading file Thinstation-thinstation-6.2.2-58-g8e4253d.tar.gz

**Comment by Doncuppjr** [comment]
Your behind a proxy. Try another internet connection or a vpn.

**Comment by maa7** [comment]
I do not use Proxy.
Also I tried 4 different providers.

**Comment by Doncuppjr** [comment]
What country?

**Comment by maa7** [comment]
Russia Moscow

**Comment by Doncuppjr** [comment]
Sooooo

**Comment by Doncuppjr** [comment]
I think VPN’s are illegal over there. You might have to find another way to smurf the archive. What does git do?

**Comment by maa7** [comment]
I tried also from Germany (Nuremberg).
Still Thinstation-thinstation-6.2.2-58-g8e4253d.tar.gz...

**Comment by Thinstation** [comment]
Try this link.
https://github.com/Thinstation/thinstation/archive/6.2-Stable.tar.gz

**Comment by maa7** [comment]
This link download file thinstation-6.2-Stable.tar.gz
How to determine the version more accurately?

**Comment by Doncuppjr** [comment]
We’re a rolling release. You could use the date as an absolute version.

**Comment by maa7** [comment]
thinstation-6.2-Stable.tar.gz size: 1 487 357 416 bytes
Thinstation-thinstation-6.2.2-58-g8e4253d.tar.gz size: 1 487 362 432 bytes

Inside both archives files have a date: 2020-01-14 04:05

thinstation-6.2-Stable.tar.gz is 6.2.2?

**Comment by Doncuppjr** [comment]
I don't know what github is doing there. Where did you get your original link? I'm not using that anywhere.
    On Thursday, January 16, 2020, 09:43:21 AM MST, maa7 <notifications@github.com> wrote:  
 
 
thinstation-6.2-Stable.tar.gz size: 1 487 357 416 bytes
Thinstation-thinstation-6.2.2-58-g8e4253d.tar.gz size: 1 487 362 432 bytes

Inside both archives files have a date: 2020-01-14 04:05

thinstation-6.2-Stable.tar.gz is 6.2.2?

**Comment by maa7** [comment]
from your comment: https://github.com/Thinstation/thinstation/issues/419#issuecomment-500164775
i just replace 6.1 to 6.2

**Comment by Thinstation** [comment]
Ty. I updated the comment.
