### ISSUE TITLE
multiple ip addresses on 1 nic for pxe boot possible?

### ISSUE THREAD

**Issue by comsyspro** [Thinstation/thinstation#522]
I have a setup where I have a dhcp running on network 192.168.1.0/24 which pointing to the thinstation server (next server) on static ip 192.168.1.100.  Now I want to know if I can boot up a thin client (having one 1gb/s nic) and can give him 2 ips (one pointing to 192.168.1.0/24 and one pointing to 192.168.2.0/24 network). So can I tell in the thinstation.conf-clientname file to configure 2 ip addresses?

**Comment by Doncuppjr** [comment]
There are no provisions for doing multiple static network configurations. Extreme corner case.

**Comment by Thinstation** [comment]
Technically, you could make a networkmanager connection file, put that into a package and then omit any network configuration from the .conf files. should work.

**Comment by comsyspro** [comment]
In the meantime I discovered that a thinclient sitting in 192.168.1.0/24 (lan network pfsense dhcp) can also reach the freerdp remote server sitting in 192.168.2.0/24 (wan network pfsense). I asked that question because I try to connect thin clients with remote servers sitting in another network and here normally you can only reach them if you have a second ip address in the same network region. Another possibility would be to create 192.168.0.0/20 networks so you can assign and reach bigger network regions or also to give the remote server an additional ip address in the thin client ip range. To your suggestion creating a networkmanager connection file I don't know how to do it.
Another question: When creating a pxe boot environment and using the wget method then you have normally a url for the pxe bootfiles and a folder like "ts6.2" in which the conf files are stored. These conf files are normally readable and accessible through the url. How can you protect the access of these conf files only for thin clients and deny access for any other computers in the network (because sometimes there are credentials stored in the conf files)?

**Comment by Thinstation** [comment]
Don’t store credentials there. :)
A truly secure transfer method was never implemented. It’s somewhat
expected that an end node is inherently insecure.
