### ISSUE TITLE
XFWM Kiosk with desktop shortcuts

### ISSUE THREAD

**Issue by N0odlez** [Thinstation/thinstation#524]
Does anyone know of a way with Thinstation to allow desktop icons in the XFWM kiosk mode? I have the icons created with kiosk mode disabled but as soon as it is enabled desktop icons disappear. Any ideas?

**Comment by Doncuppjr** [comment]
You try commenting out commands in xfwm4.functions. Not sure what kind of results your gonna get.

**Comment by N0odlez** [comment]
I've been able to remove the "xfconf-query -c xfce4-desktop -p /desktop-icons/style -t uint" -s 0 -n

Now just need to find a way of disabling right click

**Comment by N0odlez** [comment]
resorted to openbox kiosk instead.
