### ISSUE TITLE
Run package as root

### ISSUE THREAD

**Issue by N0odlez** [Thinstation/thinstation#525]
Hi all,

I'm using freerdp for our thinclient setup. For usb redirection it requires root access when running the program. How can I set the session options to run as root?

Many thanks

**Comment by Thinstation** [comment]
Maybe it just need squid

**Comment by Doncuppjr** [comment]
suid

**Comment by N0odlez** [comment]
And how would i be able to use siud or is it a change that needs to be made for Thinstation?

**Comment by Thinstation** [comment]
chmod u+s xfreerdp

**Comment by N0odlez** [comment]
Im sorry for being thick here but where does that chmod need to go? is it a file that needs to be made for the freerdp package? 

Sorry i know im a pain

**Comment by Doncuppjr** [comment]
It's a command you need to run on the main binary of the freerdp package. It's in /build/packages/freerdp/bin
It's just a guess at something that might work.

**Comment by N0odlez** [comment]
ah okay, so if i run that agains the binary on the devstation and then build it may work? the alternative is to change the permissions on the /etc/dev structure to allow the tsuser 0666 access to all usb devices.

**Comment by N0odlez** [comment]
This worked. Would appreciate if this could be added to the TS build.

**Comment by Doncuppjr** [comment]
I was talking with freerdp people, and they recommended a udev rule to own the node. They don’t like the suid maneuver:)

**Comment by Thinstation** [comment]
can you test this commit instead of suid?
https://github.com/Thinstation/thinstation/commit/b3a3120bc67681b8a3b0b0cc66d244275cfdfc6a

**Comment by N0odlez** [comment]
Sure, will test today.

**Comment by N0odlez** [comment]
Just tested and it doesn't work :(

**Comment by Thinstation** [comment]
Hmm lets try this then.
https://github.com/Thinstation/thinstation/commit/4a66f16b7ff14f4ad4e98816c335a4271bb6652c

**Comment by N0odlez** [comment]
Hi tried this. the device will add after plugging in the first time but will still show an access error to the usb. after unplugging and plugging in again it doesnt show in the vm. restart freerdp and it works again for the first time only. su makes the whole thing work correctly but it depends on what freerdp suggests and what you would like to implement.

**Comment by N0odlez** [comment]
seems like the permissions need to be 0666 according to a ubuntu forum post

**Comment by Doncuppjr** [comment]
Can you edit the rule and try?

**Comment by N0odlez** [comment]
yes of course. Also id like to hear your thoughts on using python scripts instead of bash? I'm happy to convert and test this. I believe it will help this project greatly. Also im going to do a lot of documentation regardless.

**Comment by Doncuppjr** [comment]
It depends on where you want to do that. Python has some neat stuff, but it’s really just another junkyard of code. It’s API is always in a state of flux. It takes up a lot of space....especially if your just making a kiosk that’s just going to start something written in C. What did you want to make?

**Comment by N0odlez** [comment]
Well i was thinking of just refactoring the code and change from bash to python. I thought it would make the project a bit more accessible to more developers and also remove duplicate code. Possibly change the config files/build files to json?

Its a big change but its just an idea at the moment.

**Comment by Thinstation** [comment]
You think json is easier to read than ini?

**Comment by N0odlez** [comment]
i think it will look cleaner, have sections in json rather than plain text in ini. i:e

```json
{
    "packages": {
        "freerdp": true,
        "rdesktop": false,
    },
    "parameters": {
    },
}
```

**Comment by Doncuppjr** [comment]
Keep thinking about it. I think what you really want is guard rails and context clues. I don’t think things would easily convert into that format, but maybe.

**Comment by N0odlez** [comment]
I've been testing usb redirection as much as possible and the only thing that consistently works is to suid the binary.

**Comment by N0odlez** [comment]
Now been testing this longer and i think freeRDP has an issue on their side as using the master branch just allows the usb to be plugged in once, remove it, plug in again and it doesn't load. Even if you run the package as root.

**Comment by N0odlez** [comment]
Maini issue with this is with FreeRDP. Will close this and continue to monitor
