### ISSUE TITLE
Thinstation.conf.user and USB redirection

### ISSUE THREAD

**Issue by Soogazp** [Thinstation/thinstation#526]
First of all,
I would like to know if it is possible to change the name
 of a thinstation using the file "thinstation.conf.user".
I already tried with NET_HOSTNAME=D-780-1 but it didn't work.

Then,
I have an issue with the "thinstation.conf.user" for example :
when I write :

NET_HOSTAME=D-780-1 

if I boot on the thinstation then the "thinstation.conf.user" become :

NET_HOSTAME=D-780-1
NET_HOSTAME=D-780-1 

NET_HOSTAME=D-780-1
NET_HOSTAME=D-780-1

I have no idea why the line has multiplied
I've already tested with an other command which is "LOCALE=fr_FR" while I used "LOCALE=us_US" in the "thinstation.conf.buildtime" and it worked well so the thinstation is reading the "Thinstation.conf.user" and even if it work i have the same issue that is it written 4 times instead of 1.

Lastly, 
I'm having trouble getting the USB redirection on the RDesktop.
I managed to get it to work with static redirection, 
but it doesn't work the way I want it to.

Thank you for your help

**Comment by N0odlez** [comment]
in terms of the usb redirection you'll be better off using FreeRDP. its recently had a rewrite and now works flawlessly.

**Comment by Thinstation** [comment]
We don't write to .user anywhere accept at install.....I don't know how your putting that line in there.

**Comment by Soogazp** [comment]
> We don't write to .user anywhere accept at install.....I don't know how your putting that line in there.

About that, I deleted STORAGE_CONFIG1=/mnt/disc/sda/part1 in the "thinstation.conf.buildtime" and i dont have the thinstation.conf.user problem anymore (multiplied lines) BUT i still can't name the thinstation  with that file. The thinstation.conf.user is stored locally on the physical machine.

I want to use one build for 4 computer and name each one with the config file that is locally stored.

**Comment by Doncuppjr** [comment]
STORAGE_CONFIGThere is an example of this. The DevStation build makes use of thinstation.conf.user to set the hostname. You can play with this by clicking "Tweak DevStation" under the "DevStation" Start menu item. Change the value of NET_HOSTNAME  to anything you like and reboot. I suspect you are having problems locating the file in the right place. 
You can use STORAGE_CONFIG items to set that location, and confirm that /etc/thinstation.user points to that location.






On Wednesday, January 29, 2020, 02:43:27 AM MST, Soogazp <notifications@github.com> wrote: 





>  
> We don't write to .user anywhere accept at install.....I don't know how your putting that line in there.
> 

About that, I deleted STORAGE_CONFIG1=/mnt/disc/sda/part1 in the "thinstation.conf.buildtime" and i dont have the thinstation.conf.user problem anymore (multiplied lines) BUT i still can't name the thinstation with that file. The thinstation.conf.user is stored locally on the physical machine.

I want to use one build for 4 computer and name each one with the config file that is locally stored.
