### ISSUE TITLE
DevStation does not install.

### ISSUE THREAD

**Issue by Canis-Lupis** [Thinstation/thinstation#528]
I tried versions TS-6.2.2-Installer-1222.iso and -1111.iso on both VMWare Workstatoin and Hyper-V and I get the same error both times: "During post install checks, we discovered /boot/boot/vmlinuz: missing.  Your installation is not likely to work. Aborting!"

After exiting and rebooting, I can get a simple menu screen listing "Standard" and Backup." No matter which one I choose, I get an "automatic boot in X seconds..." that counts down from 15 but then starts over, looping forever.

**Comment by Doncuppjr** [comment]
Try giving the machine more ram. I have a report that it takes 3+ gigs now


Sent from Yahoo Mail for iPhone


On Thursday, January 30, 2020, 12:26 PM, Canis-Lupis <notifications@github.com> wrote:


I tried versions TS-6.2.2-Installer-1222.iso and -1111.iso on both VMWare Workstatoin and Hyper-V and I get the same error both times: "During post install checks, we discovered /boot/boot/vmlinuz: missing. Your installation is not likely to work. Aborting!"

After exiting and rebooting, I can get a simple menu screen listing "Standard" and Backup." No matter which one I choose, I get an "automatic boot in X seconds..." that counts down from 15 but then starts over, looping forever.

**Comment by Canis-Lupis** [comment]
I had it set to 4 GB (4096) for both environments.  I did have it set to 2 GB but got errors right away that I didn't have enough memory, which is why I set it to 4 GB.  I'll try 6 GB.

**Comment by Doncuppjr** [comment]
Did you lose your internet connection during the install?

**Comment by Canis-Lupis** [comment]
Still same error at 6GB RAM with both VMWare and Hyper-V.  I'm running them on different systems as well, FYI.  Internet connection doesn't appear to be lost during install.  Would be weird if it was being lost at the exact same moment during 8 trail installs now on two different systems.

**Comment by Thinstation** [comment]
Before the reboot, open a terminal at get the contents of /boot

**Comment by Thinstation** [comment]
There should also be some install logs

**Comment by Canis-Lupis** [comment]
The contents of /boot is boot.
The contents of /boot/boot is syslinux

**Comment by Canis-Lupis** [comment]
The contents of /boot/boot/syslinux is:
extlinux
ldlinux.c32
ldlinux.sys
libcom32.c32
libutil.c32
mbr.bin
syslinux.cfg
syslinux.tpl
thinstation.txt
vesamunu.c32

**Comment by Thinstation** [comment]
Looks like sourceforge is having issues at the moment.

**Comment by Canis-Lupis** [comment]
FYI, when I click View log, all that shows up is:
Running window installer

**Comment by Thinstation** [comment]
There are 2 logs actually. both in /var/log installer and install.

**Comment by Canis-Lupis** [comment]
You are correct, I see both files there.  But I'm not sure how to how to copy the contents from the VM to my desktop to paste here.  Anything in particular I should look for?

**Comment by Thinstation** [comment]
thindev-default not finishing the download from sourceforge.

**Comment by Canis-Lupis** [comment]
What should the iso file size be when downloaded?  I get 585 MB (585,772 KB).

**Comment by Thinstation** [comment]
623

**Comment by Thinstation** [comment]
md5 d452df559ca2179aa3005969bc513f0c

**Comment by Canis-Lupis** [comment]
Sorry, I don't know how to use md5 hash to verify the download but it does appear the iso file is incomplete based on the size you stated.  I've downloaded 4 times now so I don't think its my attempts.

**Comment by Thinstation** [comment]
Not the ISO, but an auxiliary file that is downloaded during installation.
thindev-default-6.2.tar.xz

**Comment by Canis-Lupis** [comment]
Well, I'm no linux guru by any stretch, but here's what I get when I search the install.log and installer.log files for "thindev-default."

ts_000c29d41ae1:/var/log# grep thindev-default /var/log/install.log
+ '[' -e /mnt/cdrom0/thindev-default-6.2.tar.xz ']'
+ wget -t 3 -T 30 http://sourceforge.net/projects/thinstation/files/DevStation-Source/thindev-default-6.2.tar.xz
--2020-01-30 13:28:02--  http://sourceforge.net/projects/thinstation/files/DevStation-Source/thindev-default-6.2.tar.xz
Saving to: ‘thindev-default-6.2.tar.xz’
thindev-default-6.2     [ <=>                ]   4.90K  --.-KB/s    in 0s      
2020-01-30 13:28:02 (102 MB/s) - ‘thindev-default-6.2.tar.xz’ saved [5016]
+ tar -xvf thindev-default-6.2.tar.xz
+ rm thindev-default-6.2.tar.xz


ts_000c29d41ae1:/var/log# grep thindev-default /var/log/installer.log
+++ INSTALLER_ARCHIVE_NAME=thindev-default-6.2.tar.xz
ts_000c29d41ae1:/var/log#

**Comment by Thinstation** [comment]
whats after 
tar -xvf thindev-default-6.2.tar.xz

**Comment by Canis-Lupis** [comment]
Here is the next few lines after:

**+ tar -xvf thindev-default-6.2.tar.xz.**
tar: invalid tar magic.
+ rm thindev-default-6.2.tar.xz.
+ cp initrd initrd-backup.
cp: can't stat 'initrd': No such file or directory.
+ cp vmlinuz vmlinuz-backup.
cp: can't stat 'vmlinuz': No such file or directory.
+ cp lib.update lib.squash-backup.
cp: can't stat 'lib.update': No such file or directory.
+ is_enabled on.

**Comment by Thinstation** [comment]
So broken download. Sourceforge is having issues right now.

**Comment by ProgrammerVsita** [comment]
I also encountered the same issue during the installation process, so how was this issue handled?
