### ISSUE TITLE
Net-Files issue

### ISSUE THREAD

**Issue by N0odlez** [Thinstation/thinstation#529]
So interesting issue.

Followed through the net files guide and set the baseurl basepath and basename but the only var that is used in the network-files is basename.

There are a couple vars, SERVER_NAME SERVER_IP that arn't documented anywhere. Is it that these need to be changed to use basepath and baseurl?

**Comment by Thinstation** [comment]
baseurl is used in thinstation.functions:transport()
SERVER_IP is usually set by DHCP, but can be set manually. It's used for tftp and wget defaults.
SERVER_NAME is used by some packages, but most have a server set by session.

**Comment by N0odlez** [comment]
ah okay, but basepath and baseurl are never used in the netfiles functions at all. When it tries to get the default thinstation.conf.network it fails because the server_name and server_ip arn't set but this contradicts the netfiles documentation. So do we change the netfiles bash script or the documentation?

**Comment by Thinstation** [comment]
The documentation. SERVER_IP was once settable by DHCP. Might only work on the kernel cmd line and .conf.buildtime now.

**Comment by N0odlez** [comment]
but can the server_ip also be a dns name? should this var be renamed to server_address?

**Comment by Thinstation** [comment]
I think sometimes yes, and sometimes no. I don’t remember all the issues
with DNS

**Comment by N0odlez** [comment]
I think im just going to have to play and let you know my findings.

**Comment by N0odlez** [comment]
Just to add to this as well. HDUpdate runs before netfiles. so even if I had this working hdupdate still wouldn't work as it wouldn't know about the update on the server.

**Comment by N0odlez** [comment]
Ignore all the above, i should read more carefully instead of skimming.

One thing i now have is the network file is downloaded to /etc/thinstation.network but doesn't seem to merge with the config on the client already. This is then not allowing the hdupdate to take place.

**Comment by N0odlez** [comment]
so i have come to the conclusion that the downloaded thinstation.conf.network which saves to /etc/thinstation.network. This file either isn't read by the thinstation.global correctly or something else is blocking this...

Would appreciate your thoughts?

**Comment by N0odlez** [comment]
@Thinstation any ideas on this? I'm using the ts-classic package but netfiles is downloading the thinstation.conf.network is downloaded after hpupdate. Really need help with this!

**Comment by Thinstation** [comment]
What’s the systemd-analyze plot look like?

**Comment by Thinstation** [comment]
Try the latest commit

**Comment by N0odlez** [comment]
Works perfectly now,  thanks
