### ISSUE TITLE
DevStation does not install.

### ISSUE THREAD

**Issue by Canis-Lupis** [Thinstation/thinstation#530]
So, trying to install DevStation again today but still getting the same errors.  To recap my issue from yesterday, when attempting to install the latest version, I always get an error, "During post install checks, we discovered /boot/boot/vmlinuz: Missing Your installation is not likely to work. Aborting!"

Long story short, it appeared there was an issue with Sourceforge and my issue was closed.  However, a co-worker also downloaded from Sourceforge yesterday and the install went fine for him. The only difference is that he is using Virtualbox and I am trying on Hyper-V and VMWare Workstation Pro.

So...I'm at a loss now.  I even had him link me a copy of his download .iso and I still get the same error.  I turned off my virus scanner and downloaded from Sourceforge today and still get the same error.  I haven't tried using Virtualbox on my system yet but may do so soon.

Is it possible that DevStation just doesn't work anymore on VMWare or Hyper-V?  I'm running VMWare Workstation from my Windows 10 PC.  I'm giving the VM 6 GB RAM, 2 vCPUs with 2 cores, and 40 GB HD.  My Hyper-V system is running Hyper-V Standalone Server 2019.  I'm giving the VM the same resources as with the VMWare one.

**Comment by Canis-Lupis** [comment]
Update: Well, it worked for me as well from Virtualbox.  So, there's some issue with using Hyper-V and VMWare Workstation.

**Comment by Thinstation** [comment]
I use VMWare Workstation, so I know that's not it. Might be the 2gb chunk thing. Try making the disk a single file.

**Comment by N0odlez** [comment]
If your using hyperv use a generation 1 VM. gen 2 vms dont boot. I have witnessed this as well

**Comment by Canis-Lupis** [comment]
@Thinstation Already tried making the VMWare VM a single disk.  Same error.  
@AzureusNation You have a good point but I was already aware of that.  I'm using gen 1. Same error.

**Comment by Canis-Lupis** [comment]
Here are my steps and settings for VMWare:
1. Click "Create a new virtual machine" from Workstation 15.5 Pro home screen.
2. Choose Custom from the wizard (I've tried typical and still get the error).
3. Leave Hardware Compatibility at the default Workstation 15.x.
4. Select Installer Disk Image File and browse to the TS-6.2.3-Install-1222.iso file on my hard drive.
5.  Choose Linux OS with version of "Other Linux 5.x or later kernel 64-bit"
6. Name the VM "Devstation."
7. Set 2 processors with 2 cores per processor.
8. Set RAM to 6208MB or higher.
9. Select Bridged Network.
10. Leave SCSI Controller at default LSI Logic
11. Leave disk type as default SCSI (tried SATA once but same error)
12. Choose Create new virtual disk
13. Set disk size to 40 GB. Also select to allocate all space now and store as single file. (tried mult-file, too, but same error)
14. Accept default disk name.
15. Click Finish.
16. Power on VM.
17. Select Installer for DevStation.
18.Click OK at the Readme pop-up.  
19.  Select resolution. I keep it at default 1024x768
20. Select English-US
21. Click Yes at the warning about /dev/sda being erased.
22.  Installing window opens and scrolls install text.  
23. Eventually, the window closes and I get the pop-up error that the installation failed.

**Comment by Canis-Lupis** [comment]
Ok, I was able to get it installed on VMWare Workstation by making one change; in step #9 I set it to NAT instead of Bridged. Oddly, that did the trick. I went back into the DevStation guide and it shows to use bridged.  So, that is not working anymore but NAT does.  Weird since even on bridge I passed the connection test.  My VirtualBox test also is set to NAT, which is why that worked.

Hyper-V is a different beast--you can't set bridged or NAT. It uses a virtual switch and I have no idea what to change to get it to work.  Sadly, too, Hyper-V is the VM solution I really need this to work on.

What else is weird is that on all the fails and the two successes, files do seem to be downloading during the install process, such as with the git-clone command.  I see % of things downloading, too. So, I'm pretty sure the network connection is working fine with bridged or the virtual switch.

One difference I did notice is that with the success, at one point there's an actual graphic progress bar for something.  I never see that when the install fails.  I don't know what that's for, though, as it goes by fairly fast.

**Comment by Doncuppjr** [comment]
I think by default, bridging is auto. Might force it to a specified adapter. The best one.....sometimes people have more than one.





On Friday, January 31, 2020, 02:37:28 PM MST, Canis-Lupis <notifications@github.com> wrote: 





Ok, I was able to get it installed on VMWare Workstation by making one change; in step #9 I set it to NAT instead of Bridged. Oddly, that did the trick. I went back into the DevStation guide and it shows to use bridged. So, that is not working anymore but NAT does. Weird since even on bridge I passed the connection test. My VirtualBox test also is set to NAT, which is why that worked.

Hyper-V is a different beast--you can't set bridged or NAT. It uses a virtual switch and I have no idea what to change to get it to work. Sadly, too, Hyper-V is the VM solution I really need this to work on.

What else is weird is that on all the fails and the two successes, files do seem to be downloading during the install process, such as with the git-clone command. I see % of things downloading, too. So, I'm pretty sure the network connection is working fine with bridged or the virtual switch.

One difference I did notice is that with the success, at one point there's an actual graphic progress bar for something. I never see that when the install fails. I don't know what that's for, though, as it goes by fairly fast.

**Comment by Canis-Lupis** [comment]
Well, I only have one adaptor.

**Comment by Doncuppjr** [comment]
Gen 2 might work now

**Comment by Canis-Lupis** [comment]
With Gen 2 it won't boot from the iso.

**Comment by Thinstation** [comment]
Try the latest installer 0201

**Comment by Canis-Lupis** [comment]
FYI, the Thinstation website download button doesn't link to that version--it goes to 1222.  That's why I didn't see it. I finally found it and will try it now.

But am I to understand from the documentation that the .iso's you can create from DevStation are bootable only--that is, they don't install the Thinstation OS to a hard drive?  That might be a deal breaker for us in any case. Obviously, we're not going to burn 100's of CDs for each workstation to have one.  The PXE option is good, but the documentation states that doesn't scale well, so that's out as we may use it on 100's of workstations.  The best solution for us, then, would be to install the Thinstation OS onto PC hard drives, but that's not an availabe option.  Well, it is if you already have linux installed on the PC's, which we don't.  And I'm the only one here who understands even a little bit of linux, so that won't work as well.

May I suggest a build option that creates an iso that installs Thinstation onto hard drives automatically?

**Comment by Thinstation** [comment]
There have been a few solutions created for that problem. There is the
hdupdate package, the installer package. You could make something out of
mkgptdrv and mkmbrdrv. I also recently have ISO’s for refind and systemd
set up for usb writing with dd and Rufus. Really have to consider the site
objectives, partitions, how you want to manage updates.

**Comment by N0odlez** [comment]
I adapted the installer package so there are now variables. im going to start documenting but this is completely possible.

**Comment by Canis-Lupis** [comment]
@Thinstation, that was all Greek to me!  One of the things I love about Devstation is that you don't have to really know Linux to use it--it mostly uses text config files that can be configured from a desktop UI interface.  I know a little Linux but I still have to Google most things.  Installation was easy because I can follow directions. So having to create a solution myself would be a huge feat.  Of course, none of that is your concern; I get this was created for Linux users.  

I am looking to try the PXE option today but could you tell  me what the issues are with that not scaling well.  Is it all the workstations pulling the install files from Devstation? I would think that tftp server wouldn't be a bottle neck as it is sending small config files.  About how many clients can it handle before there are issues?  We may have up to 600 clients, but we have 3 locations, so we could conceivably setup 3 environments to minimize pushes to about 200 clients each location.  

Is it possible/recommended to setup the tftp server on Devstation?  I tried installing one using yum or apt-get (one of the few linux things I can do) but neither worked.  I assume those commands aren't part of the Devstation build unless there's another way I'm not aware of.  We don't want to setup another linux server just for tftp but could try on a Windows server.  Having it right on Devstation seems like the best option, though.

@AzureusNation would live to try your installer once you have it documented!

**Comment by Doncuppjr** [comment]
DevStation already has a running tftp and webserver. 

The scaling issue would be if you wanted to only use PXE for every single boot of every single client in a large network. Imagine 1000 employees all showing up in the morning, powering on and downloading a couple hundred MB all at the same time.

**Comment by Canis-Lupis** [comment]
Is the tftp server FileZilla?  I thought that was just FTP.  If not, where is it located so I can copy the files required to the tftp server root directory, as per the documentation.

Speaking of documentation, am I misunderstanding the PXE option?  I assumed it does not install anything to HD ("...no storage device is required") as with the iso.  You are right that we wouldn't want 100's of employees downloading the OS each and every morning.  Are you implying that the PXE does install the OS?

**Comment by Thinstation** [comment]
I think the tftpd is in.tftpd, but it's already set up by default. You only need to transfer away from DevStation, once your done developing and ready to deploy with your production server.

**Comment by Thinstation** [comment]
It's not part of the PXE boot spec to install an OS, but the hdupdate package provides the missing bits to get that done. Soooo, your images are only downloaded when they change, and not every poweron.

**Comment by Canis-Lupis** [comment]
I'll have to try and figure out hdupdate, then.  In the meantime, I was able to try PXE boot and I get errors.  It appears to find the tftp server just fine, but then I see:

`PXELINUX 6.04 PXE 6.04-pre2-11-gbf6db5b4* Copyright (C) 1994-2015 H. Peter Anvin et al
ThinStation Linux
Load ::/boot/vmlinuz... failed: No such file or directory
boot:`

If I type "vmlinuz" at the boot: prompt, vmlinuz starts to load but then eventually crashes with:

`Kernel panic - not syncing: VFS: Unable to mound root fs on unknown-block(0,0)
Kernel Offset: 0s34000000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
---[ end Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0) ]---`

This happens when attempting to boot from PXE from both Hyper-V and VMWare Workstation VMs.  The tftp logs shows a lot read requests for file but also a lot of "system cannot find the file specified" errors too.

Per the directions, I copied vmlinuz, initrd, files and the pxelinux directory to the home directory of the tftp server (I even copied out the files in pxelinux to the home directory as well). 

Are there other files that need to be copied that is missing from the document?

**Comment by Thinstation** [comment]
try lpxelinux. I'll look into pxelinux

**Comment by Thinstation** [comment]
might try killing in.tftpd. It should..... respawn.

**Comment by Canis-Lupis** [comment]
I think it might have something to do with assumed directory structure.  I put the files in the home directory of the tftp server, which is TFTPBase.  But I think it is looking for  vmlinuz  (as well as other files) from Boot\ or maybe TFTPBase\Boot.

**Comment by Thinstation** [comment]
DevStation drops everything in the right place. Don't need to move anything

**Comment by Canis-Lupis** [comment]
Not sure what you mean. Directions state, "All of the above files [vmlinuz, etc...] need to reside in the **TFTP server root directory** (“TFTP root”) tree that is served to thin clients."

So, that's what I did when I setup a tftp server.

**Comment by Thinstation** [comment]
Where did you set it up? Are you using DevStation ?

**Comment by Canis-Lupis** [comment]
No, I couldn't find it on DevStation. I setup TFTPD32 on a Windows 2012 R2 machine.

**Comment by Doncuppjr** [comment]
you should be able to mirror the contents of /build/boot-images/pxe to your tftp server

**Comment by Canis-Lupis** [comment]
Found this article that describes tftp on DevStation:  https://virtuallymikebrown.com/2015/02/23/how-to-build-thinstation-thin-client-images-and-exploring-config-files-part-ii/

So, I re-pointed the DHCP options 66 to the DevStation IP and 67 to /boot/pxelinux/pxelinux.0, per the article, but get an error, 

`TFTP.
PXE-T01: File not found
PXE-E3B: TFTP Error-File Not found`

Looks like it is hitting the DevStation tftp but can't find a file(s).

**Comment by Thinstation** [comment]
Open a Terminal(root) and run 
tftp -g -l favicon.ico -r favicon.ico localhost
does favicon.ico download?

**Comment by Canis-Lupis** [comment]
Yes

favicon.ico          100% |********************************| 32038  0:00:00 ETA

**Comment by Thinstation** [comment]
tftp -g -l pxelinux.0 -r /boot/pxelinux/pxelinux.0 localhost?

**Comment by Canis-Lupis** [comment]
DevStation_000c29d41ae1:/home/tsuser# tftp -g -l prelinux.0 -r /boot/prelinux/pr
elinux.0 localhost
tftp: server error: (1) File not found

Hope I spelled everything right.

**Comment by Canis-Lupis** [comment]
Looks like I had a typo:

DevStation_000c29d41ae1:/home/tsuser# tftp -g -l pxelinux.0 -r /boot/pxelinux/pxelinux.0 localhost
/boot/pxelinux/pxeli 100% |*****************************************************| 43047  0:00:00 ETA

**Comment by Canis-Lupis** [comment]
Copying and pasting /boot/pxelinux/pxelinux.0 to DHCP  just to make sure no typos there...  Looks like that worked. But now have new error: 

/lib is not a mountpoint
Fastboot was enabled, but something went wrong with the transfer or mount.

Dropping to shell.

**Comment by Thinstation** [comment]
There was a bug in the pxelinux.0 build code dealing with fastboot. Fixed just a hour ago.

**Comment by Canis-Lupis** [comment]
Will Update DevStation from the start menu fix that?

**Comment by Thinstation** [comment]
Factory Reset. Save your configs

**Comment by Canis-Lupis** [comment]
Reset. Ugh, now I'm back at FXE-T01: File not found errors.
tftp -g -l favicon.ico -r favicon.ico localhost succeeds but 
tftp -g -l pxelinux.0 -r /boot/pxelinux/pxelinux.0 localhost fails.

**Comment by Thinstation** [comment]
Try switching to lpxelinux
/boot/lpxelinux/lpxelinux.0

**Comment by Canis-Lupis** [comment]
Ok, I went back and set the virtual NIC to NAT as I remembered that was my initial problem--DevStation would not install properly with Bridged.  Of course, I can't set the tftp IP with NAT, so I had switched from NAT to Bridged.  Now, back on NAT, I was able to re-run Reset.  I then switched back to Bridged and ran a buld and the pxelinux files show back up.  However, when trying PXE boot from a client, I still getting the same "/lib is not a mountpoint" error.

I will try /boot/lpxelinux/lpxelinux.0 and see what happens.

**Comment by Canis-Lupis** [comment]
Tried /boot/lpxelinux/lpxelinux.0 but get same mountpoint error.  Is there any way to tell lpxelinux.0 is being used as opposed to pxelinux.0?  Maybe the DHCP change hasn't propagated yet to all the other servers.  I'll try again in a bit.

**Comment by Canis-Lupis** [comment]
I edited both the product.txt files in pxelinux and lpxelinux directories to make sure I'm loading the correct one.  So, my DHCP is set correctly and it is going to lpxelinux now.  However, as mentioned before, I'm still getting the /lib is  not a mountpoint error.

**Comment by Thinstation** [comment]
cat /var/log/fastboot.log

**Comment by Canis-Lupis** [comment]
fastboot.log does not exist.  Not sure why, but I did turn off fastboot and did a rebuild.  If that deletes the fastboot files, then that might be the answer.  Anyway, it works with fastboot off, which is fine with me.  So, I think I'm good to go with installing DevStation and getting PXE to work.  

Before I close this issue, though, I'd like to ask one last time if anyone knows of a solution available that installs Thinstation to HD without needing to install a Linux OS on the thin clients first?  That is, a Thinstation install .iso or PXE image that installs Thinstation to the HD (and installs hdupdate).  Or if anyone knows of a solution to the PXE scalability issue (we plan on having 500-600 workstations running as thin clients), I'd like to know that as well.

Other than that, I'd like to thank everyone for their help and suggestions. Thank you for your time, I appreciate your effort!

**Comment by Thinstation** [comment]
Look at the local-install package. You kind of need 2 builds. One installs the other, and the installer build can be PXE booted.
