### ISSUE TITLE
XFWM4 - Panel right click options

### ISSUE THREAD

**Issue by andysmithdfc** [Thinstation/thinstation#533]
Hi,

We are using XFWM4 as a Window Manager. Does anyone know of a way to hide, lock down or change the right click options for the panel?
![Panel](https://user-images.githubusercontent.com/60104079/73732644-72e88780-4732-11ea-9be0-4413bca1a304.jpg)

Cheers,

**Comment by Thinstation** [comment]
Depends on what your final vision is, but try XFWM4_KIOSK=true

**Comment by andysmithdfc** [comment]
Thanks for getting back. This hides the panel completely, which is not going to work for us. We are basically looking for a kiosk WM with a panel at the bottom, as the users will be switching between multiple windows. It needs to be completely locked down, so the user cannot change any settings. All they should be able to do is click on Applications, then click into the rdesktop sessions...
Any help would be much appreciated!

**Comment by Doncuppjr** [comment]
Look at xfwm4.functions lines 122-124, try commenting out each line

**Comment by andysmithdfc** [comment]
I have just tried this, unfortunately all I'm left with after that is a black screen with no mouse cursor?

**Comment by Thinstation** [comment]
You might have broken the syntax and thus the file.

**Comment by Thinstation** [comment]
Try one line at a time.  Not all

**Comment by andysmithdfc** [comment]
I've just tried this, still no panel unfortunately. Mouse cursor and black screen is all I've got..
Any other ideas? Your help is much appreciated.

**Comment by Thinstation** [comment]
O.k......So you for you, a little extra work. On a system that is booted and has the panels setup the way you want, you need to copy the profile .config/xfce4/xfconf/xfce-perchannel-xml/* from the user folder to your build system. Make a new package with a folder /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/, and put all the files in there. Now edit xfce4-panel.xml and change
\<channel name="xfce4-panel" version="1.0"> to \<channel name="xfce4-panel" version="1.0" locked="*" unlocked="root">. Add the package to your build.conf and rebuild.

**Comment by andysmithdfc** [comment]
Ok...I have copied the files from the users folder .config/xfce4/xfconf/xfce-perchannel-xml/* to my build machine.
I have then copied the 'template' package, and named it 'panel'. I have then created the directory structure /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/ and pasted the files into there.
I have made the changes to xfce4-panel.xml as above, and saved the file. I added 'package panel' into build.conf, and rebuilt. 
It doesn't look like the changes are carrying over to the users machine, as when I navigate to .config/xfce4/xfconf/xfce-perchannel-xml/*, the xfce4-panel.xml file hasn't been edited. Is there anything else I need to do to my custom package for the changes to apply?
Thanks again,

**Comment by Doncuppjr** [comment]
Did your file make it into the image? find /build/tmp-tree/etc/xdg/xfce4

**Comment by andysmithdfc** [comment]
I'm struggling to find that particular location, either on the build machine or the remote machine?

**Comment by Doncuppjr** [comment]
Then it didn’t make it in. /build/tmp-tree is pre compressed image result. If it’s not there, it’s not in the image.

**Comment by andysmithdfc** [comment]
Trying to get to /build/tmp-tree, the location doesn't exist?

**Comment by Doncuppjr** [comment]
It’s in the chroot

**Comment by andysmithdfc** [comment]
I'm in the chroot environment (Navigated to thinstation/build ./setup-chroot) but I still can't find /build/tmp-tree location. I'm a linux novice, learning as I go, so it's entirely possible I'm doing something wrong..

Just to confirm, I should be searching for this directory on the build server as opposed to the client?

**Comment by Thinstation** [comment]
on the build server
after ./setup-chroot, cd /build/tmp-tree
It's only going to be there after a build.

**Comment by andysmithdfc** [comment]
![IMG_5028](https://user-images.githubusercontent.com/60104079/74459270-eb61ed80-4e82-11ea-83e1-da005e39cbda.jpg)

I ran a build, but still no joy. Any idea where I'm going wrong?

**Comment by Doncuppjr** [comment]
Add —saved it to build command

**Comment by Doncuppjr** [comment]
—savedir

**Comment by andysmithdfc** [comment]
Ah...gotcha. 
Adding savedir has given me access to that directory. 
If I navigate to '/build/tmp-tree/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/' I can see my xfce4-panel.xml file there, with the changes
(<channel name="xfce4-panel" version="1.0" locked="*" unlocked="root">)
applied....However, there is no change to the panel itself. It is still allowing me to right click it and get into the properties on the client machine.
Any other ideas?

**Comment by Thinstation** [comment]
Are you running as a root user? 
This worked for me. It does not disable the right-click, but nothing can be changed. It just points to help.

**Comment by Thinstation** [comment]
Try the latest commit.

**Comment by andysmithdfc** [comment]
Using the latest commit has fixed the problem!
Thanks very much for all your help!
