### ISSUE TITLE
rDesktop - Printer Redirection

### ISSUE THREAD

**Issue by andysmithdfc** [Thinstation/thinstation#536]
Hello,
Does anyone have any advice on the commands needed to set up printer redirection for a network printer?
My current setup has a Thinstation client PXE booting into a XFWM4 environment. The user can then open up a RDesktop session into a Windows terminal server setup. I am looking to get a network printer available within this RDesktop session. I have played about with the -r flag within the RDESKTOP_OPTIONS, but am struggling to get this working.
Thanks!

**Comment by Thinstation** [comment]
Sooo, rdesktop doesn't support NLA. This is a critical security element of modern remote access systems. Consider switching to FreeRDP
