### ISSUE TITLE
UEFI Kernel Panic

### ISSUE THREAD

**Issue by N0odlez** [Thinstation/thinstation#538]
Hi all,

Got a Asus TP200SA that only has a UEFI bios. When ever i run a premade or a custom all-firmware installer on it, the kernel panics. I've ran a mem test and all fine but i think it might be an issue with running a BIOS version instead of a UEFI initrd.

```
Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
Kernel Offset: 0x2000000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
--[ end Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0) ]--
```

Any help would be appreciated.

**Comment by Thinstation** [comment]
Does it boot in CSM mode?

**Comment by Thinstation** [comment]
Is there a firmware update for the unit?

**Comment by N0odlez** [comment]
I've updated the bios to latest version which although was only 2017. But fully updated.

CSM is enabled and also tried disabled as well.

**Comment by Doncuppjr** [comment]
And the image works on other machines?

**Comment by N0odlez** [comment]
Yeah, image works fine on other machines. Other machines have both BIOS and UEFI but this particular laptop has only UEFI

**Comment by Thinstation** [comment]
CSM is bios emulation. Which EFI bootloader?

**Comment by N0odlez** [comment]
Ohh. Not sure what you mean by EFI. I use Rufus to put the iso to usb if that helps?

**Comment by Doncuppjr** [comment]
Which ISO?

**Comment by N0odlez** [comment]
I build an installer iso from a modified version of the installer configs.

**Comment by Thinstation** [comment]
Sure, but which one??

**Comment by Thinstation** [comment]
refind-iso or systemd-boot-iso?

**Comment by N0odlez** [comment]
Right just setting up a test now. I've set the boot to make syslinux, iso and refined. Will test refined iso in a sec. But the iso param is the one I was using before.

**Comment by Doncuppjr** [comment]
Before making the build, do prt-get install rufus, then also make the systemd-boot-iso

**Comment by Thinstation** [comment]
The systemd-boot-iso is the most complete. You should be able to write in both dd and iso modes with rufus. It should boot on Secureboot systems after enrolling loader and vmlinuz. It also should have rufus and the extra syslinux files it needs to convert from iso to disk mode without issue.

**Comment by Thinstation** [comment]
This still an issue?

**Comment by N0odlez** [comment]
Yes sorry, was busy last week installing wifi across a couple sites. Ive installed rufus but when i build im getting an error, /usr/share/syslinux/bios/ldlinux.sys no file or directory. And sure enough having a look there is no syslinux folder. Ive narrowed this down the the build script but i think its because i may not have installed rufus correctly. All i ran was prt-get install rufus. Is there anything after that i need to run?

**Comment by Thinstation** [comment]
No. rufus won't run in the build environment, it's just downloaded and put on the iso for convenience with all the syslinux bits dropped in the right place. Strange that your getting an error like syslinux is not installed. prt-get install syslinux.....

**Comment by N0odlez** [comment]
crisis averted prt-get -fr -if rufus done the trick. Now got the syslinux.

**Comment by ghost** [comment]
Same issue here.
Any workaround?

**Comment by Thinstation** [comment]
I don't think we ever really identified the cause of the issue reported here.
