### ISSUE TITLE
Booting Thinstation from Network boot

### ISSUE THREAD

**Issue by alijundi** [Thinstation/thinstation#541]
System boots but while trying to get file named lib.squash wget returns network unreachable cannot connect to host.

The above is shown in the fastboot.log file.

I really do not know what do at this point and would appreciate any help for this matter.

Thank you guys for the great work.

**Comment by Thinstation** [comment]
autonet or networkmanager?

**Comment by alijundi** [comment]
package networkmanager is used. which is the default in build.conf

**Comment by Thinstation** [comment]
Swap for autonet I’ll add another warning.

**Comment by alijundi** [comment]
done and it is working now... I am testing it actually. so far so good

**Comment by Thinstation** [comment]
Added more warnings.
