### ISSUE TITLE
Problem with dollar sign in password

### ISSUE THREAD

**Issue by iceemike** [Thinstation/thinstation#545]
I found a closed issue (issue #204) that talked about this, but it still seems like the problem is still active. It does seem like the issue is with the GTK dialog from dialog.functions

I placed set -x in dialog.functions and the run_dialog() function it is not holding the password with a dollar sign correctly.

++ run_dialog
++ I='
'
++ IFS=
+++ gtkdialog -c --program=MAIN_DIALOG
++ for STATEMENTS in '$(gtkdialog -c --program=MAIN_DIALOG)'
++ eval 'DIALOG_OPTIONS="/rfx /gfx-h264 /sec:nla /d:DOMAIN
/dvc:urbdrc,dev:04df:0030#04df:0012#04df:001f +auto-reconnect
/auto-reconnect-max-retries:0"
DIALOG_PASSWORD="23$temp12#"
DIALOG_SERVER="XXXXXX.XXXXX"
DIALOG_USER="test"
windowed="false"
EXIT="ok"'
+++ DIALOG_OPTIONS='/rfx /gfx-h264 /sec:nla /d:DOMAIN
/dvc:urbdrc,dev:04df:0030#04df:0012#04df:001f +auto-reconnect
/auto-reconnect-max-retries:0'
+++ DIALOG_PASSWORD=23#
+++ DIALOG_SERVER=XXX.XXX
+++ DIALOG_USER=test
+++ windowed=false
+++ EXIT=ok
++ IFS='

**Comment by Doncuppjr** [comment]
Is gnu bash in your build, or is it linked to busybox?

**Comment by Doncuppjr** [comment]
It looks like your using an older version of thinstation. I don't see the code that escapes $ being executed there.

**Comment by iceemike** [comment]
I'm using bash. 
The thinstation version is 5.6. The thin clients I'm using do not have 64bit processors, so I don't think I can upgrade to 6.X.
Where is the code for escaping $? Is it in a newer dialog.functions?

**Comment by Doncuppjr** [comment]
Yes. Likely need dialog.functions and thinstation.packages as well as the options file for the client application.

**Comment by iceemike** [comment]
That did the trick. Thanks for your help!
