### ISSUE TITLE
Horizon Client Smart Card

### ISSUE THREAD

**Issue by bcheck555** [Thinstation/thinstation#546]
Greetings,
First, Thank You for this great software.
My trouble is trying to get smart cards working with Horizon Client. I have enabled opensc and pcscd. The problem is that I do not know how to create a symlink to the location that Horizon Client looks for the driver.

Instructions from VMWare, 
mkdir -p  /usr/lib/vmware/view/pkcs11
sudo ln -s /usr/lib64/pkcs11/opensc-pkcs11.so /usr/lib/vmware/view/pkcs11/libopenscpkcs11.so

I've tried this in the chroot environment, but it does not seem to carry over.

ref: https://docs.vmware.com/en/VMware-Horizon-Client-for-Linux/5.3/horizon-client-linux-installation/GUID-6CB5F6EE-E7DC-4BF7-8E2A-4542E4A78182.html

**Comment by Thinstation** [comment]
So what you want to do here, is create a custom package, like
mkdir -p /build/packages/vmview-opensc
then make the folder
mkdir -p /build/packages/vmview-opensc/lib/vmware/view/pkcs11
then link the lib
ln -sf /lib/pkcs11/opensc-pkcs11.so
/build/packages/vmview-opensc/lib/vmware/view/pkcs11/libopenscpkcs11.so
create the dependencies file
echo "opensc" >  /build/packages/vmview-opensc/dependencies
then add the new package to your build.conf
package vmview-opensc

**Comment by bcheck555** [comment]
This worked, thank you.
