### ISSUE TITLE
Internet Connectivity Test Failed!

### ISSUE THREAD

**Issue by micneon** [Thinstation/thinstation#547]
Hi,

Internet Connectivity Test Failed!
http: Success HTTPS. Fail
Proxy Fail both

I have test ' echo "check_certificate=off" > ~/.wgetrc ' no positive result.
Then i have download image.md5 to an own Webserver and map sourceforge.net in /etc/hosts to that server. there i get only one request..

94.222.xxx.xxx - - [19/Mar/2020:22:13:14 +0000] "GET /projects/thinstation/files/DevStation-Source/image.md5 HTTP/1.0" 200 547 "-" "Wget/1.20.3 (linux-gnu)"

Is there something wrong @sourceforge an can the Online Test skipped ?

**Comment by Thinstation** [comment]
There is not much point in disabling the internet test. If you don't have good internet, the installer will not work.

**Comment by micneon** [comment]
I have two Lines 100 Mbit / 40 Mbit and 50 Mbit / 10 Mbit from two div. Providers Both Lines are working fine.  The Same error i get in a Virtual Server in a Datacenter.

**Comment by micneon** [comment]
this morning it works :-)
