### ISSUE TITLE
FreeRDP Autologin

### ISSUE THREAD

**Issue by avignat** [Thinstation/thinstation#548]
Hello,

I can't get FreeRDP autologin to work with Thinstation. Here is the config :
```
RECONNECT_PROMPT=On
LOG_COMMANDS=true
SESSION_0_TYPE=freerdp
SESSION_0_TITLE="TSE"
SESSION_0_AUTOSTART=On
SESSION_0_FREERDP_SERVER="192.168.1.20"
SESSION_0_FREERDP_OPTIONS="/d:DOMAIN /u:user /p:password /cert-ignore -sec-nla"
FREERDP_CERTIGNORE=on
FREERDP_GETUSER=off
```

I tested a lot of different config but I always get the prompt asking for user and password.
I'm also interested in the config that just autofill the user only.

Tools : 
Windows Server 2012 R2 (NLA disabled)
Thinstation 6.2 stable
Windows domain : domain.com

Thanks for your help

**Comment by Thinstation** [comment]
google freerdp.getuser
