### ISSUE TITLE
Unable to connect HP usb printer in thinstation 5.2

### ISSUE THREAD

**Issue by hananab** [Thinstation/thinstation#55]
I have booted a client with thinstation 5.2. A printer (HP 2300 Laser Jet) is connected to that machine
I am unable to find out that how this printer will be redirected through rdesktop or anyother war around that i can access that printer into my remote machine 

Assistance will be highly appreciated

**Comment by Thinstation** [comment]
This is really more of an rdesktop question than a Thinstation one.
However,

running

rdesktop --help

reveals that a -r switch followed by some other parameters specific to your
printer should get the job done.
I wish I could give you a more specific answer, but context is ever
important in making such exact determinations. I would recommend that you
have the printer plugged in when making your module set. This will ensure
that if Linux needs any modules to activate the port, they will be
available.
