### ISSUE TITLE
Kernel panic - not syncing: VFS: unable to mount root fs on unknown-nlock(0,0)

### ISSUE THREAD

**Issue by ghost** [Thinstation/thinstation#551]
Hello!
I was trying to build and ISO to burn it using rufus on USB-drive.
But when i'm testing final ISO using VMWare Workstation and "burned" USB with thinstation i have got this error.
Please help.
Many thanks.
![image](https://user-images.githubusercontent.com/53333224/79847061-7dc0c900-83bf-11ea-90fe-19fd7ce93900.png)

**Comment by ghost** [comment]
Also, i can't find anywhere possible parameters of "param bootimages" with proper description.
In my particular situation, i used "param bootimages "iso syslinux".

**Comment by Thinstation** [comment]
You can comment out, or remove 'param bootimages', and all image formats will be generated. That's much more of a legacy / time optimization for building. 

Maybe you are running out of memory.

**Comment by ghost** [comment]
> 
> 
> You can comment out, or remove 'param bootimages', and all image formats will be generated. That's much more of a legacy / time optimization for building.
> 
> Maybe you are running out of memory.

Hello!
Thanks for your reply.
But which one ISO image (from which folder) do i need to use to make USB bootable client?

About running out of memory, i have 8 Gb ram, tried to allocate 1 Gb at first then 2 Gb. Nothing changed. Error still happens.

**Comment by Thinstation** [comment]
systemd-boot-iso

**Comment by kviolka** [comment]
Hi, I get the same error. I try to build a new image for Fujitsu-Siemens Futro S900. When I build the -allmodules version for syslinux and transfer it to the built in disk, I get this kernel panic, after vmlinuz and inird did load. I tried to remove all unneccessary packages, but have the same result.

The machine has 2Gig ram, this initrd is 175M. I'm stuck, would appreciate any help. Could I pay you for an hour of support?

**Comment by Thinstation** [comment]
Sure, but remote debugging of hardware is tediously slow. I could likely figure this out much faster if I had the hardware in front of me.

**Comment by Thinstation** [comment]
Also, try the tiny build. do not build --allmodules, just tiny.

**Comment by kviolka** [comment]
Hmm, what do you mean by "tiny?" Thats not an option of the build script, as far as i see...

**Comment by Thinstation** [comment]
It’s a build/config pair to make a really tiny build.

**Comment by kviolka** [comment]
I tried it but it does not seem to load the right firmwares... I opened a new issue for the Futro config.
