### ISSUE TITLE
Question about SSL certificates

### ISSUE THREAD

**Issue by Sekainoshuhsi** [Thinstation/thinstation#554]
Hello.

I'm having some issues adding my Root and Intermediate certificates into my build.
I've created folders my-certificates/certs and /ca (all according to the instruction [here](https://github.com/Thinstation/thinstation/wiki/Certificates), added there my root certificate called root.pem and intermediate called inter.pem. Added "package my-certificates" line into build and created an iso image.

In the end when I'm booting from that ISO VMware Horizon doesn't trust that certificate and looks like that certs wasn't included in /etc/ssl/certs/ca-bundle which is causing that issue.
Is there something I'm missing in all of that?

**Comment by Thinstation** [comment]
I am guessing you missed a detail.

**Comment by cheasully** [comment]
Hello, I'm having a similar issue.. could someone please expound upon the detail we might be missing? I would greatly appreciate it! My .crt's are showing up in /etc/ssl/certs but not being trusted by firefox, or recognized by vmware horizon client.

**Comment by Doncuppjr** [comment]
Go ahead and post your .crt here

**Comment by cheasully** [comment]
I confirmed that the certs work properly on other linux boxes. I believe that it has something with how the VMware Horizon client script is building everything?

-----BEGIN CERTIFICATE-----
MIIEjzCCA3egAwIBAgICASswDQYJKoZIhvcNAQELBQAwWzELMAkGA1UEBhMCVVMx
GDAWBgNVBAoTD1UuUy4gR292ZXJubWVudDEMMAoGA1UECxMDRG9EMQwwCgYDVQQL
EwNQS0kxFjAUBgNVBAMTDURvRCBSb290IENBIDMwHhcNMTYxMTIyMTM1MDM1WhcN
MjIxMTIzMTM1MDM1WjBaMQswCQYDVQQGEwJVUzEYMBYGA1UECgwPVS5TLiBHb3Zl
cm5tZW50MQwwCgYDVQQLDANEb0QxDDAKBgNVBAsMA1BLSTEVMBMGA1UEAwwMRE9E
IFNXIENBLTUzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwTewS9iv
ChYtMvNBYEOjVcVqr+3VOAEgyjt7ieJUVPrFDgtL9Sz+eXX+uBXkJwYjS0gtex6L
RuNtdcLkukoJu34ZxnfUwc8rgTwNV8VtIyI2GJq/u/FjGwK8fHkzslOzwF8KoA6N
NTYvKy9XohBDrrYGpRq/RuDttVfiJ4Yvcii5J6+uZTvT9035EksqjV7A+sJkFVqI
3MZ83kN9O0ZJf4dEj4h4DKqQYHTRrpy/BL4pTGxmSpnQHne63ToqsoZntTYCYhB5
6izOakbsUTYVauwYqlNVf0j20IwcZibztp7wqV2NgGzA81LndhYLQh+8KsDabTSV
sZMvLHfEAeLdhwIDAQABo4IBXDCCAVgwHwYDVR0jBBgwFoAUbIqUonexgHIdgXoW
qvLczmbuRcAwHQYDVR0OBBYEFFHEizOZlMB+uzYd4+I6Bb0ydJ1TMA4GA1UdDwEB
/wQEAwIBhjA9BgNVHSAENjA0MAsGCWCGSAFlAgELJDALBglghkgBZQIBCycwCwYJ
YIZIAWUCAQsqMAsGCWCGSAFlAgELOzASBgNVHRMBAf8ECDAGAQH/AgEAMAwGA1Ud
JAQFMAOAAQAwNwYDVR0fBDAwLjAsoCqgKIYmaHR0cDovL2NybC5kaXNhLm1pbC9j
cmwvRE9EUk9PVENBMy5jcmwwbAYIKwYBBQUHAQEEYDBeMDoGCCsGAQUFBzAChi5o
dHRwOi8vY3JsLmRpc2EubWlsL2lzc3VlZHRvL0RPRFJPT1RDQTNfSVQucDdjMCAG
CCsGAQUFBzABhhRodHRwOi8vb2NzcC5kaXNhLm1pbDANBgkqhkiG9w0BAQsFAAOC
AQEACZtxX9lr6sye0RUSOLYzLCU4jVDNSQgz3qq8Kk7dJ97GdsuBzACcCIwFDpNd
tjMtD+mwNjgfeRY5ovyMEH3ZzVhIqGpQo4WLeE+bjy3fNcU3rsb2SHNaEpRddWQ3
jnOc3jlyg/sHaR6Jg4JfQ1G9za46AReVa1nJLHjt/BO5m/3D4iJmpJvq2Qp6N4eF
a2VL6s8uAZKnLCocjZU2B3wYZMyaSgppaE4TOe/Hc5HJw245/cFLUL8I02iYfv9E
KQDuTGqNzGrBuKp9LMpRrBWb0boFrZaONcVXjtCqi05fo1Fd/JhuvfraTpgxmVXi
1OvgVGwq5lsxW2pbjSpBFebaRw==
-----END CERTIFICATE-----

**Comment by Doncuppjr** [comment]
I'm not quite sure where you are falling off of the path.
When I follow the steps at: https://github.com/Thinstation/thinstation/wiki/Certificates,
I get the following layout in my build dir:
build/packages/my-certificates/
build/packages/my-certificates/dependencies
build/packages/my-certificates/certs
build/packages/my-certificates/certs/ca
build/packages/my-certificates/certs/ca/random.crt

after I run build, I find the certificate in all the right places:
grep -R tmp-tree/etc/* -e DNSQgz3qq8Kk 2>/dev/null
tmp-tree/etc/ssl/cert.pem:AQEACZtxX9lr6sye0RUSOLYzLCU4jVDNSQgz3qq8Kk7dJ97GdsuBzACcCIwFDpNd
tmp-tree/etc/ssl/certs/ec279b60.0:AQEACZtxX9lr6sye0RUSOLYzLCU4jVDNSQgz3qq8Kk7dJ97GdsuBzACcCIwFDpNd
tmp-tree/etc/ssl/certs/random.pem:AQEACZtxX9lr6sye0RUSOLYzLCU4jVDNSQgz3qq8Kk7dJ97GdsuBzACcCIwFDpNd

and in the nssdb at 

certutil -L -d tmp-tree/etc/pki/nssdb -h all

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

DOD SW CA-53                                                 CT,C,


If I boot the system, I can see the certificate in the firefox certificate utility
![image](https://user-images.githubusercontent.com/784950/82383225-39d2db00-99e2-11ea-9ea5-faf19769d250.png)


Maybe a few of those commands will help you solve your issue.
