### ISSUE TITLE
Audio webcam

### ISSUE THREAD

**Issue by trentasis** [Thinstation/thinstation#555]
Hi,

I'm trying to use a webcam, I can use image but no sound, I can see:
May 13 09:21:08 (none) user.info kernel: usb 2-6: reset high-speed USB device number 4 using ehci-pci
May 13 09:21:08 (none) user.info kernel: uvcvideo: Found UVC 1.00 device <unnamed> (046d:0825)
May 13 09:21:08 (none) user.info kernel: uvcvideo: No streaming interface found for terminal 5.
May 13 09:21:08 (none) user.info kernel: input: UVC Camera (046d:0825) as /devices/pci0000:00/0000:00:1d.7/usb2/2-6/2-6:1.0/input/input24
May 13 09:21:08 (none) user.info kernel: usb 2-6: set resolution quirk: cval->res = 384
May 13 09:21:08 (none) user.err pulseaudio[5774]: [pulseaudio] module-alsa-card.c: Failed to find a working profile.
May 13 09:21:08 (none) user.err pulseaudio[5774]: [pulseaudio] module.c: Failed to load module "module-alsa-card" (argument: "device_id="2" name="usb-046d_0825_97130150-02-U0x46d0x825" card_name="alsa_card.usb-046d_0825_97130150-02-U0x46d0x825" namereg_fail=false tsc

Any suggestions where is the issue? seems that alsa is installed but no mic and no sound..
thanks

**Comment by Thinstation** [comment]
allmodules and allfirmware build?

**Comment by trentasis** [comment]
was generated with allmodules, and using default build and thinstation.conf works, any suggestions what packages or config can generate issues with sound?

Thanks

**Comment by Thinstation** [comment]
maybe gnome-core and gnome-pulse

**Comment by trentasis** [comment]
Seems that in my confg is trying to ouptut mono and not stereo, and for that no sound, where and how is this configured?
thanks

**Comment by Doncuppjr** [comment]
Mono v stereo, probably in the pulse profiles or alsa profiles. We don't set that via TS configs.






On Wednesday, May 13, 2020, 09:31:32 AM PDT, trentasis <notifications@github.com> wrote: 







Seems that in my confg is trying to ouptut mono and not stereo, and for that no sound, where and how is this configured?

thanks

**Comment by trentasis** [comment]
correct this Mono v stereo, sorry but I'm searching any parameter con build or thinstation.conf.buldimt but I can't find... any suggestion where and how is this configured mono vs stereo?

thanks

**Comment by trentasis** [comment]
hi
I don't really understand and can find the difference, only recompiling and using builcd.conf.example and thisntation.conf.buldimte from original version works, but when I use my config not, and you described that is not a TS config... can you give some details where to debug this?

thanks

**Comment by Doncuppjr** [comment]
Are you using a window manager?


Sent from Yahoo Mail for iPhone


On Wednesday, May 13, 2020, 10:43 AM, trentasis <notifications@github.com> wrote:




hi
I don't really understand and can find the difference, only recompiling and using builcd.conf.example and thisntation.conf.buldimte from original version works, but when I use my config not, and you described that is not a TS config... can you give some details where to debug this?

thanks

**Comment by trentasis** [comment]
correct, xfwm4, in both situations.... comapred packages  and config and seems same...

I have detected taht with default config pcspeaker (mono device) is not recognized and only stereo is showed and for that enabled by default, and with other config both devices exist and by default is enabled pcspeaker (mono), I don't understand why...

**Comment by Doncuppjr** [comment]
The only audio we set are these twots/build/packages/alsa/build/extra/etc/init.d/audio

AUDIO_LEVEL=90
MIC_LEVEL=0, which are interpreted by 

ts/build/packages/alsa/build/extra/etc/init.d/audio




On Wednesday, May 13, 2020, 11:06:21 AM PDT, trentasis <notifications@github.com> wrote: 







correct, xfwm4, in both situations.... comapred packages and config and seems same...

**Comment by trentasis** [comment]
Yes, mic and audio were tested but is not the source of problem, seems default build.conf is no enabling speaker modules and my actual config is enabling, but I don't know where and why, I'm using in both config ./build --allmodules, how can I disable pcspeaker module for my build, is possible?

thanks

**Comment by trentasis** [comment]
I think that I have found ...param blacklist snd-pcsp.ko  now I'll try....
Thanks

**Comment by Doncuppjr** [comment]
param blacklist "snd-pcsp.ko pcspkr.ko"






On Wednesday, May 13, 2020, 11:29:12 AM PDT, trentasis <notifications@github.com> wrote: 







Yes, mic and audio were tested but is not the source of problem, seems default build.conf is no enabling speaker modules and my actual config is enabling, but I don't know where and why, I'm using in both config ./build --allmodules, how can I disable pcspeaker module for my build, is possible?

thanks

**Comment by trentasis** [comment]
perfect, works!

thanks for all
