### ISSUE TITLE
packages

### ISSUE THREAD

**Issue by trentasis** [Thinstation/thinstation#557]
Hi,

Checking version os some packages are not the latest, not sure if exist any incompatibility for example:
latest rdesktop 1.9 https://github.com/rdesktop/rdesktop/releases/tag/v1.9.0
latest freerdp 2.1.1 https://github.com/FreeRDP/FreeRDP/releases/tag/2.1.1
ccid https://github.com/LudovicRousseau/CCID/releases/tag/ccid-1.4.32
pcsc-lite https://github.com/LudovicRousseau/PCSC/releases/tag/pcsc-1.8.26
firefox https://download-installer.cdn.mozilla.net/pub/firefox/releases/68.8.0esr/linux-x86_64/en-US/firefox-68.8.0esr.tar.bz2

Any known incompatibility?

Second question, I need to add a new package, I'm searhing how to do this but I can't find doc,  where can I see an example how to create a new package?

Thanks

**Comment by Doncuppjr** [comment]
Those can be updated without issue. I do sometimes in test branch, I just don't always push updates, as sometimes they break things. An empty inbox is good sign(no bugs). Feel free to play with newer versions of those packages.

A video on how to add a package can be found here.
https://www.youtube.com/watch?v=4socE4i_mUc

**Comment by trentasis** [comment]
Thanks @Doncuppjr I'll try to test and if is possible I'll make a pull request

About youtube link appear private, after login I can't see

Thanks

**Comment by trentasis** [comment]
hi @Doncuppjr 

I'm trying to add this two packages https://www.fabulatech.com/webcam-for-remote-desktop-linux-packages.html

At this moment UI have installed ftwebcam is untar to /opt but now I'm trying to run on init, I have used as an example ocsinventory package... but is not starting... 

can you give access to this youtube video, appears as private

Another question .dna files how are update, manually or automatically using any command special?

Thanks

**Comment by trentasis** [comment]
I think that now almost I have.. I have questions about dna footprint, maybe with your youtube video can help...
thanks

**Comment by Doncuppjr** [comment]
Wooops, thought I made that public a long time ago. Fixed.

.dna is metadata that is used to update a package. Unless you add or remove files from your package, you shouldn't need to update the .dna. More than likely you want to use repackage style packages. Easier to maintain. Has a .dna, but doesn't really use it.

**Comment by trentasis** [comment]
thanks
