### ISSUE TITLE
cups 6.2

### ISSUE THREAD

**Issue by trentasis** [Thinstation/thinstation#559]
hi,

Seems that with latest versions 6.2 cups is not working to be used with cups groups https://github.com/Thinstation/thinstation/wiki/Printer-configuration (option B)

seems that issue is 
https://github.com/Thinstation/thinstation/issues/152

Problem is cups-filters that is configured with FileDevice Yes, if you kikk cups and restart then works, but not sure where to change to cofnigure before and tehn start cups.

With 5.5 was working because was configured on same cupsd.conf

Thanks

**Comment by trentasis** [comment]
hi
maybe moving 
cups-init this part
        # Requirement for cups printing to /dev/usb/lp0 and /dev/lp0 (filedevices)
        echo "FileDevice yes" >> /etc/cups/cups-files.conf
 to spcecific file and execute systemd with 
ExecStartPre=/path/to/your/script

Any other suggestion?

**Comment by trentasis** [comment]
with this  PR issue cna be solved
https://github.com/Thinstation/thinstation/pull/560

**Comment by Thinstation** [comment]
Maybe we should fix the systemd.service file, so that the cups-init runs before cupsd

**Comment by trentasis** [comment]
ok, no probem to change and replace the commit, but where is this file systemd.service? I can't find...
thanks!

**Comment by Doncuppjr** [comment]
Nm, I think your current solution is the best for the time being.

**Comment by trentasis** [comment]
Perfect, PR added, thanks for your help

Thanks
