### ISSUE TITLE
freerdp NLA

### ISSUE THREAD

**Issue by trentasis** [Thinstation/thinstation#561]
Hi,

I have seen multiple issues related with freerdp nla, but I'm not sure if thinstation (with or without gtkdialog) works, I have tried but I can only connect to server with options /cert-ignore and /sec:tls, I can't pass to command line user password, because is used by multiple users, and only options are enter pwd to dialog and then pass to freerdp command line or enter directly to windows prompt but then is asked two times

How it works freerdp nla in this environment? can be used without ask password two times?

Thanks

**Comment by Doncuppjr** [comment]
If you are being asked for the password by both TS and Windows, then NLA is disabled. You can tell TS not to ask for user and password, then only windows will ask.

**Comment by trentasis** [comment]
Hi,

What I have to use on thinstation to enable NLA? It is needed to use gtkdialog to be used with nla to only ask 1 tiem password or without nla?

Thanks

**Comment by Doncuppjr** [comment]
With Network Level Authentication, the username and password must be known before the connection to the server is made. The gtkdialog will collect that information. NLA is a requirement of the server PC. If NLA is disabled, the client will connect to the server, and show a regular windows logon page.

**Comment by trentasis** [comment]
thanks
