### ISSUE TITLE
usb automount

### ISSUE THREAD

**Issue by trentasis** [Thinstation/thinstation#562]
Hi,

seems that with latest 6.2 usb automount usb is not working, only is mounted on /mnt/usbdevice/sdx if usb is connected during boot, then if you remove and insert anotehr time is not remounted.

Same situation with 5.5 was working, I have seen some change on usb mount code, but not sure why was changed and why now is reproducing this situation

Cdrom mount and remount was working with 5.5 and with 6.2 works, only fail usb pendrive

thanks

**Comment by Doncuppjr** [comment]
Depends on which mounting system is in play. With fastboot enabled, some early mounting is required.  If automount is being used, then disks will always get mounted. If udisks is being used instead, they will not, unless you also include a fstab rule to mount them based on identifying information.

**Comment by trentasis** [comment]
Hi,

fastboot is disabled, and we use udisks, same config in 5.5 was
working and now on 6.2 not.
Can I enable automount and udisks at same configuration? any incompatibility?

what do you suggest?

thanks

Missatge de Donald A. Cupp Jr. <notifications@github.com> del dia dt.,
2 de juny 2020 a les 17:11:

**Comment by Doncuppjr** [comment]
Disable udisks or write an fstab mount rule.

**Comment by trentasis** [comment]
thanks
