### ISSUE TITLE
Unable to make builds!

### ISSUE THREAD

**Issue by alijundi** [Thinstation/thinstation#563]
I am not sure what happened in my case but I receive the below every time I try to build image! Any thoughts on why this is happening?

Script started on 2020-06-08 01:02:54-07:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="80" LINES="24"]
rmdir: failed to remove './temp-efi': Directory not empty
Checking for required commands... OK
Kernel +con doesn't exist, ERROR!!
rmdir: failed to remove './temp-efi': Directory not empty

Script done on 2020-06-08 01:02:55-07:00 [COMMAND_EXIT_CODE="1"]

**Comment by Doncuppjr** [comment]
Did you mount something at /boot in the chroot?


Sent from Yahoo Mail for iPhone


On Monday, June 8, 2020, 1:05 AM, alijundi <notifications@github.com> wrote:




I am not sure what happened in my case but I receive the below every time I try to build image! Any thoughts on why this is happening?

Script started on 2020-06-08 01:02:54-07:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="80" LINES="24"]
rmdir: failed to remove './temp-efi': Directory not empty
Checking for required commands... OK
Kernel +con doesn't exist, ERROR!!
rmdir: failed to remove './temp-efi': Directory not empty

Script done on 2020-06-08 01:02:55-07:00 [COMMAND_EXIT_CODE="1"]

**Comment by alijundi** [comment]
I actually did a clean reinstall and was able make builds. Closing this issue now.
