### ISSUE TITLE
Question about rdp and msappproxy

### ISSUE THREAD

**Issue by Sehoxo** [Thinstation/thinstation#565]
Hello,

I have some trouble with thinstation and configuration file. We have a rdp broker (we can call it : srv-broker)
I configured le .conf file with the mac address and the server : it works
Now, I have a new rdp broker. We can't access to it directly with rdp. I have to use the gatewayhostname (line gatewayhostname on .rdp file)
This gatewayhostname is our microsoft app proxy (msappproxy).
Do you know how can I add this proxy to my .conf for thinstation ?
I tried simply NET_GATEWAY but it doesn't work.

Thanks !
Regards,
Enzo

**Comment by Thinstation** [comment]
I was actually working on extending the framework for this, but I got distracted. I want to make something a little more dynamic, but for the time being, you could edit the /build/packages/freerdp/etc/cmd/freerdp.options file and add a line
MISC_OPTIONS="-g:\<gateway\>"

**Comment by Sehoxo** [comment]
Hello,

Thank you for your help, but I have a last question. The last admin who do the config for us did this :
He configured the linux machine, then run the script to past all the conf' files on a TFTP server. Now I have, on my TPTP, some folders (boot, cgi-bin and config)
On config, I have the thinstation.conf explained earlier.
On boot folder, I have some boot files. 
Is it possible to add the MISC_OPTIONS on one of these files ? Or do I need to recreate a linux machine ?
Regards,

Enzo

**Comment by Thinstation** [comment]
MISC_OPTIONS currently exists as a place holder for the framework
extensions I want to make. It's not mapped out to the conf files at this
time. The only way to get what you want is to edit the image itself, or
remake it.
