### ISSUE TITLE
pxe boot with uefi x64 don't start on an Intel NUC

### ISSUE THREAD

**Issue by teha-at** [Thinstation/thinstation#566]
Hello,

i already run a bunch of Intel NUC with a Thinstation 5.3 - all works fine. Now we need more devices and i bought a newer Intel NUC (NUC7PJYH2), but this boots only over UEFI. To test the new setup, i make a new build machine with Thinstation 6.2 and the build works fine.

The Intel NUC load the "efi64/syslinux.efi" than the "vmlinuz" and "initrd", after this the system hangup and freeze totally (no ping, no keyboard interaction).

`Loading http://...../boot/initrd... ok`

![IMG_2984](https://user-images.githubusercontent.com/47043401/84780633-1782ac00-afe6-11ea-92b1-2f38cd14e609.jpg)

I found the closed issues #436 and #479, both of them looks like the same problem but no one had a solution. 

The system use the syslinux version 6.04-pre2-2 and i tryed diffrent kernel versions (5.2.19, 5.3.6 and 5.4.33) and each with `./build --allmodules`

@Thinstation you think in https://github.com/Thinstation/thinstation/issues/479#issuecomment-545255498 that the problem might be in the splash_progress. Have you any recommendations for me to check if this my problem too?

On a "normal" Linux  distribution the kernel put out a lot of informations on his boot sequence, has anyone a suggestion for me how i enable the kernel command line output? Or is this step in booting up still a part of syslinux?

**Comment by Thinstation** [comment]
Please also make sure, that 
param allfirmware	true
is in build.conf

**Comment by teha-at** [comment]
It's already in there

```
[root@TS_chroot]/build# grep allfirmware build.conf
param allfirmware	true
```

**Comment by Thinstation** [comment]
networkmanager or autonet?

**Comment by teha-at** [comment]
autonet is enabled and networkmanager is disabled
```
#package networkmanager
package autonet
```

**Comment by Thinstation** [comment]
set your kernel cmd line to 
vt.global_cursor_default=1 loglevel=3 systemd.show_status=true udev.log_priority=3 rd.systemd.show_status=true rd.udev.log_priority=3 i915.fastboot=1

**Comment by teha-at** [comment]
the same behavior, after `Loading http://...../boot/initrd... ok` the device is dead/freezed.

Only for sure, i modify the `boot/efi64/pxelinux.cfg/default` file

```
TIMEOUT 0
DEFAULT default
DISPLAY product.txt

LABEL default
        KERNEL http://172.16.11.129/boot/vmlinuz
        APPEND initrd=http://172.16.11.129/boot/initrd vt.global_cursor_default=1 loglevel=3 systemd.show_status=true udev.log_priority=3 rd.systemd.show_status=true rd.udev.log_priority=3 i915.fastboot=1
```

I increase the verbosity of the tftpd and saw that the file is loaded from the client.

**Comment by Thinstation** [comment]
Is secure boot enabled?

**Comment by teha-at** [comment]
No, if i enable secure boot it will be stoped the boot sequence right after the client loaded the `syslinux.efi` with the message
```
Image Authorization Fail.
System can not boot to this device due to Security Violation
```

**Comment by Thinstation** [comment]
So we might need to change the kernel for you. If you go back to the FP unwinder instead of the ORC unwinder, you can use older versions of syslinux that start the kernel more reliably. grub might be an option, but I don't have a solution for that at this second.

**Comment by teha-at** [comment]
thanks a lot for the moment. I'll try later to modify the kernel to use the frame pointer unwinder.

**Comment by teha-at** [comment]
I tryed to use grub (grubnetx64.efi) as a bootloader. But the same result, after the loading of the initrd file are completed the system freeze. Do you still belief that the unwinder (FP vs. ORC) can be the problem?

FYI: I also make a bootable usb stick (`mkmbrdrv -o /build/boot-images/syslinux -p d:0:boot /dev/sdb`) and the result is the same, after the initrd freeze the system.

**Comment by Doncuppjr** [comment]
Possibly a firmware issue. Which nuc is it?

**Comment by teha-at** [comment]
This is a NUC7PJYH (at the label ist NUC7PJYH**2** printed). By your advise i updated the firmware to the lastest version (JY0054.bio) but same behavior. Also i reset the firmware to the default settings (except for secure boot).

There is only one new NUC by my site. I have to look if another NUC with UEFI is free for testing.

**Comment by Doncuppjr** [comment]
Try the tiny build, no extra modules, let’s see if we can get past kernel exec

**Comment by Thinstation** [comment]
https://github.com/Thinstation/thinstation/blob/6.2-Stable/ts/build/conf/tiny/build.conf.example

**Comment by teha-at** [comment]
No, with the tiny build the same behavior.

Because of a little bit of frustration i tryed diffrent things: My build machine is a Debian 10.4 (Buster) and i copyed the `/boot/vmlinuz-4.19.0-9-amd64` to the tftp directory as `boot/vmlinuz`. After the NUC loads the `vmlinuz` and `initrd` file with the same loading message the screen clears, a blinking cursor appears and then `Welcome to ThinStation 6.2 Alice!` show up at the screen. The start sequence of thinstation terminates a little bit later because of missing packages. 
I was able to replicate this with a kernel image from a Ubuntu 20.04 installation `vmlinuz-5.4.0-37-generic`.

I think this is a sign that the NUC + Firmware are ok. Now i had to see how to tune the thinstation kernel to work with this NUC. Have you any suggestion for me how i start this process? We already minimized the count of the modules with the tiny build. Make it sense to compare the thinstation kernel with one of the other deeper? I can try to start up the thinstation client fully with one of the other kernels to run the `hwlister.sh`, will this help?

**Comment by Thinstation** [comment]
Hmmm. well, use both the build.conf and conf.buildtime from tiny. https://github.com/Thinstation/thinstation/tree/6.2-Stable/ts/build/conf/tiny, that should fix the package issue, and drop to a shell almost always.

That is interesting about the different kernel working with our initrd. That at least means it is a kernel option, and those are easy to change, not always easy to find, but easy to change.

hwlister.sh will not help. we have diff modules selected for builtin and external than other distro's, but tiny does not need any modules, except net.......

Can you send me a unit? You comfy with make menuconfig?

**Comment by teha-at** [comment]
Use both from tiny works, i became a shell with a blinking cursor 😄  but the USB keyboard are not working 😞 
I think in the other kernels are not build in support for usbhid and thinstation build kernel modules are not loadable for the other kernels (of course).

Sending you an unit are difficult, because at the moment i have only this one and i'm in Germany. But if we still stuck to get running this stupid NUC this may be an option.

My last kernel build is around 15 years ago but i think menuconfig will bring up lots of memories - the question is only which kind of memories 😏 

I have make a bootable usb stick with an Ubuntu 20.04 Desktop installer and start `Try Ubuntu`to get a running console. I capture the output from some of the ls* commands:

- lsmod: https://gist.github.com/teha-at/c88b81658e4c80d14a872ba3a42f710f
- lscpu: https://gist.github.com/teha-at/c15e0d2faea2634cd3241207134e6505
- lshw: https://gist.github.com/teha-at/0a697e6429fff5714d865dbc36e78529
- lspci: https://gist.github.com/teha-at/b8cec1a4ea7354472e98ad6310e969d1
- lsusb: https://gist.github.com/teha-at/1688100e9e310536f8365657f75ffd00 

Maybe there a informations that can help use to build a working kernel for this NUC.

**Comment by Doncuppjr** [comment]
I can buy a unit for about $200 US. Make a donation, and then I can help with this.

**Comment by Thinstation** [comment]
Next Thursday......but ordered.

**Comment by teha-at** [comment]
@Thinstation Your support is great, thanks! Is there a (short) documentation how to build a modified kernel for the thinstation or maybe you can sketch the rough path? This also may usefull for other people.

**Comment by Thinstation** [comment]
https://github.com/Thinstation/thinstation/wiki/Custom-Kernel

**Comment by Thinstation** [comment]
So, a default Fedora kernel does not start either.  At least it's not just my config, will keep working on it.

**Comment by Thinstation** [comment]
Good news. I have a working kernel. Gonna take a few days to slim it down, but it boots.

**Comment by teha-at** [comment]
Oh ya, that's are good news. Are you able to share the kernel configuration (.config) even that the kernel very big at the moment? This will allow me to continue the configuration process of the whole ThinStation. After we have a slim kernel i can switch back to the official from you.

Did you find out which part(s) of the old kernel was missing?

**Comment by Thinstation** [comment]
I have not narrowed it down yet, drivers and maybe some other framebuffer options. Gonna take a few more days to work it out. This kind of works, but my fastboot technique does not.
[nuc7jy.zip](https://github.com/Thinstation/thinstation/files/4865141/nuc7jy.zip)

**Comment by Thinstation** [comment]
Try current HEAD.

**Comment by teha-at** [comment]
It works, i used the current HEAD of the 6.2-Stable branch and the NUC boot up the kernel. 

I saw, that you provide an extra machine folder `intel_nuc7jy` and i use this one in my `build.conf`. But i think there is a missing module, because the network adapter is not working. After a little bit of testing i added the `realtek` module (required by r8169)  and then the network interface start working.

For the extra module, i create a pull request: #582 

Thank you for your support!

**Comment by teissler** [comment]
I have exactly the same problem with an Intel Celeron J1900 System on Thinstation 6.2.13.
What can i provide to fix this issue?

**Comment by Thinstation** [comment]
Are you using grub or syslinux?

**Comment by teissler** [comment]
pxelinux

**Comment by Thinstation** [comment]
Switch to grub. It supports pxe and has better uefi support.

**Comment by teissler** [comment]
Where are the files created for grub pxe boot?
I can't find them below `ts/build/boot-images/pxe/`

**Comment by Thinstation** [comment]
/build/boot-images/grub/efi-source/pxeboot.img

**Comment by Thinstation** [comment]
/build/boot-images/grub/efi-source/boot/grub/pxeboot.img

**Comment by teissler** [comment]
strange... now it continuesly reboots after loading vmlinuz.
and pxeboot.img stops searching for configuration after grub.cfg-01-MAC-ADDRESS, grub.cfg-IP in hex and grub.cfg-IP in hex -1 but it should keeps searching until grub.cfg as documented at [here](https://www.gnu.org/software/grub/manual/grub/html_node/Network.html#Network)

**Comment by Thinstation** [comment]
BIOS or EFI

**Comment by Thinstation** [comment]
The EFI boot image is at
/build/boot-images/grub/efi-source/EFI/boot/bootx64.efi

**Comment by Thinstation** [comment]
/build/boot-images/grub/efi-source needs to be the root for your tftp server

**Comment by teissler** [comment]
BIOS.
I have set `/grub/pxeboot.img` as filename in DHCP.
This is my tftp root directory.

```
root@fw01:/srv/tftp# tree
.
├── boot
│   ├── efi32
│   │   ├── ldlinux.e32
│   │   ├── product.txt
│   │   ├── pxelinux.cfg
│   │   │   └── default
│   │   ├── syslinux.cfg
│   │   └── syslinux.efi
│   ├── efi64
│   │   ├── bootx64.efi
│   │   ├── ldlinux.e64
│   │   ├── product.txt
│   │   ├── pxelinux.cfg
│   │   │   └── default
│   │   ├── syslinux.cfg
│   │   └── syslinux.efi
│   ├── image.md5
│   ├── initrd
│   ├── lib.squash
│   ├── lpxelinux
│   │   ├── ldlinux.c32
│   │   ├── lpxelinux.0
│   │   ├── product.txt
│   │   └── pxelinux.cfg
│   │       └── default
│   ├── pxelinux
│   │   ├── ldlinux.c32
│   │   ├── product.txt
│   │   ├── pxelinux.0
│   │   └── pxelinux.cfg
│   │       └── default
│   └── vmlinuz
├── grub
│   ├── boot.img
│   ├── cdboot.img
│   ├── core.img
│   ├── grub.cfg
│   ├── grub.cfg-01-c0-3f-d5-a4-1b-54
│   ├── i386-pc
│   │   └── normal.mod
│   └── pxeboot.img
├── image.md5
├── initrd
├── ipxe.efi
├── ipxe.pxe
├── ldlinux.c32 -> ./boot/pxelinux/ldlinux.c32
├── product.txt -> ./boot/pxelinux/product.txt
├── pxelinux.0 -> boot/pxelinux/pxelinux.0
├── pxelinux.cfg -> boot/pxelinux/pxelinux.cfg
├── ts5.6
│   └── thinstation.conf.network
├── ts6.2
│   └── thinstation.conf.network
├── undionly.kpxe
└── vmlinuz

```

And this is what the client requests when booting:
```
Jul 28 09:58:44 fw01 in.tftpd[20462]: RRQ from 192.168.99.213 filename /grub/pxeboot.img
Jul 28 09:58:44 fw01 in.tftpd[20462]: tftp: client does not accept options
Jul 28 09:58:44 fw01 in.tftpd[20463]: RRQ from 192.168.99.213 filename /grub/pxeboot.img
Jul 28 09:58:44 fw01 in.tftpd[20464]: RRQ from 192.168.99.213 filename /grub/grub.cfg-01-c0-3f-d5-a4-1b-54
Jul 28 09:58:44 fw01 in.tftpd[20465]: RRQ from 192.168.99.213 filename /boot/grub/i386-pc/command.lst
Jul 28 09:58:44 fw01 in.tftpd[20465]: sending NAK (1, File not found) to 192.168.99.213
Jul 28 09:58:44 fw01 in.tftpd[20466]: RRQ from 192.168.99.213 filename /boot/grub/i386-pc/fs.lst
Jul 28 09:58:44 fw01 in.tftpd[20466]: sending NAK (1, File not found) to 192.168.99.213
Jul 28 09:58:44 fw01 in.tftpd[20467]: RRQ from 192.168.99.213 filename /boot/grub/i386-pc/crypto.lst
Jul 28 09:58:44 fw01 in.tftpd[20467]: sending NAK (1, File not found) to 192.168.99.213
Jul 28 09:58:44 fw01 in.tftpd[20468]: RRQ from 192.168.99.213 filename /boot/grub/i386-pc/terminal.lst
Jul 28 09:58:44 fw01 in.tftpd[20468]: sending NAK (1, File not found) to 192.168.99.213
Jul 28 09:58:44 fw01 in.tftpd[20469]: RRQ from 192.168.99.213 filename /grub/grub.cfg-01-c0-3f-d5-a4-1b-54
Jul 28 09:58:44 fw01 in.tftpd[20470]: RRQ from 192.168.99.213 filename /boot/vmlinuz


Jul 28 09:59:12 fw01 in.tftpd[20471]: RRQ from 192.168.99.213 filename /grub/pxeboot.img
Jul 28 09:59:12 fw01 in.tftpd[20471]: tftp: client does not accept options
Jul 28 09:59:12 fw01 in.tftpd[20472]: RRQ from 192.168.99.213 filename /grub/pxeboot.img
Jul 28 09:59:12 fw01 in.tftpd[20473]: RRQ from 192.168.99.213 filename /grub/grub.cfg-01-c0-3f-d5-a4-1b-54
Jul 28 09:59:12 fw01 in.tftpd[20474]: RRQ from 192.168.99.213 filename /boot/grub/i386-pc/command.lst
Jul 28 09:59:12 fw01 in.tftpd[20474]: sending NAK (1, File not found) to 192.168.99.213
Jul 28 09:59:12 fw01 in.tftpd[20475]: RRQ from 192.168.99.213 filename /boot/grub/i386-pc/fs.lst
Jul 28 09:59:12 fw01 in.tftpd[20475]: sending NAK (1, File not found) to 192.168.99.213
Jul 28 09:59:12 fw01 in.tftpd[20476]: RRQ from 192.168.99.213 filename /boot/grub/i386-pc/crypto.lst
Jul 28 09:59:12 fw01 in.tftpd[20476]: sending NAK (1, File not found) to 192.168.99.213
Jul 28 09:59:12 fw01 in.tftpd[20477]: RRQ from 192.168.99.213 filename /boot/grub/i386-pc/terminal.lst
Jul 28 09:59:12 fw01 in.tftpd[20477]: sending NAK (1, File not found) to 192.168.99.213
Jul 28 09:59:12 fw01 in.tftpd[20478]: RRQ from 192.168.99.213 filename /grub/grub.cfg-01-c0-3f-d5-a4-1b-54
Jul 28 09:59:12 fw01 in.tftpd[20479]: RRQ from 192.168.99.213 filename /boot/vmlinuz
```

As you can see the client reboots after requesting vmlinuz and tries again.

**Comment by Doncuppjr** [comment]
Try EFI


Sent from Yahoo Mail for iPhone


On Thursday, July 28, 2022, 1:00 AM, Timo Eissler ***@***.***> wrote:




BIOS.
I have set /grub/pxeboot.img as filename in DHCP.
This is my tftp root directory.
***@***.***:/srv/tftp# tree . ├── boot │   ├── efi32 │   │   ├── ldlinux.e32 │   │   ├── product.txt │   │   ├── pxelinux.cfg │   │   │   └── default │   │   ├── syslinux.cfg │   │   └── syslinux.efi │   ├── efi64 │   │   ├── bootx64.efi │   │   ├── ldlinux.e64 │   │   ├── product.txt │   │   ├── pxelinux.cfg │   │   │   └── default │   │   ├── syslinux.cfg │   │   └── syslinux.efi │   ├── image.md5 │   ├── initrd │   ├── lib.squash │   ├── lpxelinux │   │   ├── ldlinux.c32 │   │   ├── lpxelinux.0 │   │   ├── product.txt │   │   └── pxelinux.cfg │   │   └── default │   ├── pxelinux │   │   ├── ldlinux.c32 │   │   ├── product.txt │   │   ├── pxelinux.0 │   │   └── pxelinux.cfg │   │   └── default │   └── vmlinuz ├── grub │   ├── boot.img │   ├── cdboot.img │   ├── core.img │   ├── grub.cfg │   ├── grub.cfg-01-c0-3f-d5-a4-1b-54 │   ├── i386-pc │   │   └── normal.mod │   └── pxeboot.img ├── image.md5 ├── initrd ├── ipxe.efi ├── ipxe.pxe ├── ldlinux.c32 -> ./boot/pxelinux/ldlinux.c32 ├── product.txt -> ./boot/pxelinux/product.txt ├── pxelinux.0 -> boot/pxelinux/pxelinux.0 ├── pxelinux.cfg -> boot/pxelinux/pxelinux.cfg ├── ts5.6 │   └── thinstation.conf.network ├── ts6.2 │   └── thinstation.conf.network ├── undionly.kpxe └── vmlinuz

And this is what the client requests when booting:
`
Jul 28 09:58:44 fw01 in.tftpd[20462]: RRQ from 192.168.99.213 filename /grub/pxeboot.img
Jul 28 09:58:44 fw01 in.tftpd[20462]: tftp: client does not accept options
Jul 28 09:58:44 fw01 in.tftpd[20463]: RRQ from 192.168.99.213 filename /grub/pxeboot.img
Jul 28 09:58:44 fw01 in.tftpd[20464]: RRQ from 192.168.99.213 filename /grub/grub.cfg-01-c0-3f-d5-a4-1b-54
Jul 28 09:58:44 fw01 in.tftpd[20465]: RRQ from 192.168.99.213 filename /boot/grub/i386-pc/command.lst
Jul 28 09:58:44 fw01 in.tftpd[20465]: sending NAK (1, File not found) to 192.168.99.213
Jul 28 09:58:44 fw01 in.tftpd[20466]: RRQ from 192.168.99.213 filename /boot/grub/i386-pc/fs.lst
Jul 28 09:58:44 fw01 in.tftpd[20466]: sending NAK (1, File not found) to 192.168.99.213
Jul 28 09:58:44 fw01 in.tftpd[20467]: RRQ from 192.168.99.213 filename /boot/grub/i386-pc/crypto.lst
Jul 28 09:58:44 fw01 in.tftpd[20467]: sending NAK (1, File not found) to 192.168.99.213
Jul 28 09:58:44 fw01 in.tftpd[20468]: RRQ from 192.168.99.213 filename /boot/grub/i386-pc/terminal.lst
Jul 28 09:58:44 fw01 in.tftpd[20468]: sending NAK (1, File not found) to 192.168.99.213
Jul 28 09:58:44 fw01 in.tftpd[20469]: RRQ from 192.168.99.213 filename /grub/grub.cfg-01-c0-3f-d5-a4-1b-54
Jul 28 09:58:44 fw01 in.tftpd[20470]: RRQ from 192.168.99.213 filename /boot/vmlinuz

Jul 28 09:59:12 fw01 in.tftpd[20471]: RRQ from 192.168.99.213 filename /grub/pxeboot.img
Jul 28 09:59:12 fw01 in.tftpd[20471]: tftp: client does not accept options
Jul 28 09:59:12 fw01 in.tftpd[20472]: RRQ from 192.168.99.213 filename /grub/pxeboot.img
Jul 28 09:59:12 fw01 in.tftpd[20473]: RRQ from 192.168.99.213 filename /grub/grub.cfg-01-c0-3f-d5-a4-1b-54
Jul 28 09:59:12 fw01 in.tftpd[20474]: RRQ from 192.168.99.213 filename /boot/grub/i386-pc/command.lst
Jul 28 09:59:12 fw01 in.tftpd[20474]: sending NAK (1, File not found) to 192.168.99.213
Jul 28 09:59:12 fw01 in.tftpd[20475]: RRQ from 192.168.99.213 filename /boot/grub/i386-pc/fs.lst
Jul 28 09:59:12 fw01 in.tftpd[20475]: sending NAK (1, File not found) to 192.168.99.213
Jul 28 09:59:12 fw01 in.tftpd[20476]: RRQ from 192.168.99.213 filename /boot/grub/i386-pc/crypto.lst
Jul 28 09:59:12 fw01 in.tftpd[20476]: sending NAK (1, File not found) to 192.168.99.213
Jul 28 09:59:12 fw01 in.tftpd[20477]: RRQ from 192.168.99.213 filename /boot/grub/i386-pc/terminal.lst
Jul 28 09:59:12 fw01 in.tftpd[20477]: sending NAK (1, File not found) to 192.168.99.213
Jul 28 09:59:12 fw01 in.tftpd[20478]: RRQ from 192.168.99.213 filename /grub/grub.cfg-01-c0-3f-d5-a4-1b-54
Jul 28 09:59:12 fw01 in.tftpd[20479]: RRQ from 192.168.99.213 filename /boot/vmlinuz
`

As you can see the client reboots after requesting vmlinuz and tries again.

**Comment by teissler** [comment]
With EFI booting from `/EFI/boot/grubx64.efi` i get the error message

```
error: ../../grub-2.06/grub-core/loader/i386/efi/linux.c:357:kernel doesn't support 64-bit CPUs.s ]
error: ../../grub-2.06/grub-core/loader/i386/efi/linux.c:208:you need to load the kernel first.
```

**Comment by Doncuppjr** [comment]
Your system would need to be able to boot EFI PXE. It can not be in CSM mode.






On Thursday, July 28, 2022 at 12:31:06 PM PDT, Timo Eissler ***@***.***> wrote: 







With EFI booting from /EFI/boot/grubx64.efi i get the error message
error: ../../grub-2.06/grub-core/loader/i386/efi/linux.c:357:kernel doesn't support 64-bit CPUs.s ]
error: ../../grub-2.06/grub-core/loader/i386/efi/linux.c:208:you need to load the kernel first.

**Comment by teissler** [comment]
The system is not in CSM mode. Booting systemrescue via ipxe shows me that i'm in EFI mode (tested with `efibootmgr` and `[ -d /sys/firmware/efi ] && echo UEFI || echo BIOS`.

**Comment by Thinstation** [comment]
Have you tried CSM with pxeboot.img?

**Comment by teissler** [comment]
I have tried every option in the BIOS/EFI now, but this system just won't boot.
This is so strange, it worked without issues back with Thinstation 5.3 but i can't get 5.4 or 6.2 to boot...

**Comment by Thinstation** [comment]
How about disk booting?

**Comment by teissler** [comment]
This system has now disk, it's just a KVM (freerdp) for a remote VM.

**Comment by Thinstation** [comment]
You could try the Ubuntu kernel
prt-get install ubuntu-kernel
./build --kernel 5.8.0-63-generic

**Comment by Thinstation** [comment]
So it boots from disk, but not PXE?

**Comment by teissler** [comment]
I have a netboot.xyz based iPXE menu in my network from which it can boot systemrescuecd for example.
But it won't boot Thinstation.
I will try the ubuntu kernel and report back.
