### ISSUE TITLE
Loadbalance Info on thinstation

### ISSUE THREAD

**Issue by Sehoxo** [Thinstation/thinstation#569]
Hello, 
We want to add a loadbalance info for our broker to use thinstation with it.
Our rdp file has this line :
loadbalanceinfo:s:tsv://MS Terminal Services Plugin.1.Bureau

Do you know where can I add this line to my  ? 
I already tried with this line :
SESSION_0_FREERDP_OPTIONS="/d:'ourdomain' /u:'username' /p:'password' /bpp:24 /cert-ignore -sec-nla /network:lan /load-balance-info:"tsv://MS Terminal Services Plugin.1.Bureau""

But it doen't work :(

Thanks for your help,

Regards,

Enzo

**Comment by Thinstation** [comment]
What happens?

**Comment by Sehoxo** [comment]
Nothing. Instead of connecting me to my server, I have a black screen with 2 options : reconnect or shutdown.
If I use another server (and without the loadbalance info)it works perfectly. We just have some issues with this broker and this line.

**Comment by Doncuppjr** [comment]
Let’s simplify? Can you open a terminal and launch freerdp from the cli?

**Comment by Sehoxo** [comment]
Can you please tell me how to do that ? I'm a newbie with this.
I just boot on pxe with my laptop and it automaticaly load the pxe file present on our fileserver. I can't upload file here (it says error) but on my laptot it shows :
Loading : :/boot/vmlinuz ... ok
Loading ::/boot/initrd...ok
Then I have the blackscreen. I don't know how to open a terminal from this :(

**Comment by Doncuppjr** [comment]
It’s not hard. On your development machine, while in the chroot, type xfreerdp

**Comment by Sehoxo** [comment]
Ho ok, I need a new dev machine. I don't have it anymore, my ex colleague delete it. So I need to rebuild one ? I don't have other options ?

**Comment by Doncuppjr** [comment]
You need to work out the exact xfreerdp command for your network, then we can integrate it into ThinStation.

**Comment by Sehoxo** [comment]
I'll try on a new dev machine. But is freerdp compatible with 2019 server ?

**Comment by Thinstation** [comment]
I’m not sure, I don’t know it wouldn’t work, but you could ask in #freerdp

**Comment by Sehoxo** [comment]
Hello,

I just install a new dev machine. If i try in CLI :

xfreerdp /v:'server.domain.local' /d:'domain' /u:'user' /p:'password' /load-balance-info:'tsv://MS Terminal Services Plugin.1.Bureau'
it works perfectly.
Now if i copy those arguments in my thinstation.conf-MAK, nothing happens :
SESSION_0_TYPE=freerdp
SESSION_0_FREERDP_SERVER="server.domain.local"
SESSION_0_FREERDP_OPTIONS="/v:'server.domain.local' /d:'domain' /u:'user' /p:'password' /load-balance-info:'tsv://MS Terminal Services Plugin.1.Bureau' "
Do you have any suggestions ?

**Comment by Doncuppjr** [comment]
You mentioned that this was an old image. How old?

**Comment by glitchvern** [comment]
I don't think /v:'server.domain.local' belongs in the SESSION_0_FREERDP_OPTIONS.  I think the script picks that up from the SESSION_0_FREERDP_SERVER and combines it with the options.  I'm not sure though because I used the FREERDP_SELECT_SERVER, FREERDP_SERVER_0 style configuration to do this.  The load-balance-info as an option without a /v worked just fine using that style configuration.

**Comment by Sehoxo** [comment]
@Doncuppjr The image is 5 years old (2015) so it's kinda old right ? We are using Thinstation 5.1.1
@glitchvern Thanks for your help, but I tried to remove /v option and nothing changes -> black screen for minutes then it shows reconnect or shutdown.

**Comment by Thinstation** [comment]
That version might not support load balancers, I'm not sure when they added support. You might need to make a new build with up to date software.

**Comment by Sehoxo** [comment]
Hello,

Thanks for your help. I just upgraded my thinstation build and it works perfectly. 
Have a nice day !!

Enzo
