### ISSUE TITLE
eglGetDisplay() failed

### ISSUE THREAD

**Issue by glitchvern** [Thinstation/thinstation#571]
I think something is maybe wrong with the EGL library or it is the wrong version for AMD Radeon chips?  I get this error in the Xorg.0.log file on both a Dell Wyse D90D8 (AMD Radeon HD 6250) with the Radeon driver and a HP-t520 (Radeon(TM) R2E) with both the Radeon and AMDGPU drivers.  The R2E won't even bring up X with the Radeon driver.  It just gave a message about unable to go graphical.

I would have tried to recompile it from source, but couldn't figure out how (pkg-get update -rf _portname_ -if -im) or which port in the chroot goes into which package.  I am guessing libEGL.so.1.1.0 is coming from the libglvnd package in the chroot and going into xorg7-glamor package in Thinstation?  I don't really understand the format of the .dna files.  I am not sure if libEGL_mesa.so.0.0.0 from the chroot mesa3d package is needed too or what.  In any event the graphics drivers for at least some Radeon chipsets don't appear to be working correctly.

https://heap.ovh/running-gentoo-on-hp-t520-part-2.html is a blog about getting gentoo running on the same hardware complete with an Xorg.log file so I know it is possible.

See attached Xorg.0.log files for the thinstation Wyse D90D8 using Radeon, the thinstation HP-t520 using Radeon, the thinstation HP-t520 using AMDGPU, and lastly the log file from a blog about running Gentoo on the HP-t520 using AMDGPU which is close to what ours should look like.

[wyse-d90d8-thinstation.Xorg.0.log](https://github.com/Thinstation/thinstation/files/4834306/wyse-d90d8-thinstation.Xorg.0.log)

[hp-t520-thinstation-radeon.Xorg.0.log](https://github.com/Thinstation/thinstation/files/4834309/hp-t520-thinstation-radeon.Xorg.0.log)

[hp-t520-thinstation-amdgpu.Xorg.0.log](https://github.com/Thinstation/thinstation/files/4834311/hp-t520-thinstation-amdgpu.Xorg.0.log)

[hp-t520-gentoo-amdgpu.Xorg.0.log](https://github.com/Thinstation/thinstation/files/4834312/hp-t520-gentoo-amdgpu.Xorg.0.log)

**Comment by Thinstation** [comment]
Thanks for the report. I updated the libglvend port, and removed all the conflicting libraries. See if this solves your issue?

**Comment by glitchvern** [comment]
Now I'm back to "The system was not able to go graphical."  

[hp-t520-thinstation-amdgpu-libglvend.Xorg.0.log](https://github.com/Thinstation/thinstation/files/4859739/hp-t520-thinstation-amdgpu-libglvend.Xorg.0.log)

It appears there are dangling symlinks to a non-existent libGLX_mesa.so.0.0.0 and libEGL.so.1.1.0.

I am not that familiar with git and may have done something wrong with the upgrade.

First I created a myconfig branch and added and committed my config files and machine profiles.  Then I did a git fetch.  Then I did a git rebase 6.2-Stable. Did a build and deploy and eventually figured out I didn't actually have any of the new updates in my build.  Eventually figured out to do a git rebase origin/6.2-Stable.  Did a build and deploy on that that didn't work.  It's Xorg.0.log had an error way earlier about, I think libglx.so being missing, when it appeared to still exist.  Then I did a clean_chroot and  a ./setup-chroot.

During ./setup-chroot received a "ln: failed to access '/usr/lib/libGLX_mesa.so.0.0.0': No such file or directory" during Populating Package mesa3d and a "ln: failed to access '/usr/lib/libEGL.so.1.1.0': No such file or directory" during Populating Package xorg7-glamor.  After this I did my final build and deploy and got Xorg.0.log included above.

**Comment by Thinstation** [comment]
I pushed fixes for this.

**Comment by glitchvern** [comment]
Still at "The system was not able to go graphical."

[hp-t520-thinstation-amdgpu-3.Xorg.0.log](https://github.com/Thinstation/thinstation/files/4860530/hp-t520-thinstation-amdgpu-3.Xorg.0.log)

There are still dangling symlinks to a non-existent libEGL.so.1.1.0.

During ./setup-chroot there was a : 
Populating Package mesa3d
No .dna exists for package 'mesa3d'.

**Comment by Thinstation** [comment]
This fix was quite extensive. Save your configs away, and do a factory
reset.

**Comment by glitchvern** [comment]
I assumed factory reset meant to delete thinstation and do a new git clone, so that's what I did.  Created a diff first.  After new clone  of repository was created, patched in my configs.  X appears to now be functioning correctly now.

[hp-t520-thinstation-amdgpu-4.Xorg.0.log](https://github.com/Thinstation/thinstation/files/4892577/hp-t520-thinstation-amdgpu-4.Xorg.0.log)

Unfortunately freerdp doesn't so I haven't tested the Wyse D90D8 with these changes.  Freerdp barely connects to 2003 or 2008 servers for longer than it takes to log in.  Connects to 2012 R2 servers just fine.  Problem with freerdp appears to be upstream during the change from freerdp 2.1.1 to 2.1.2.  Freerdp pull request #6300 appears to resolve the problem for people.  Will wait for that to make the stable-2.0 branch before testing the Wyse D90D8.

Not sure if this issue should just be closed now or if the radeon driver needs to be tested first?

**Comment by Thinstation** [comment]
Nah, I pulled glvnd out. Looks like your only dealing with FreeRDP now, and that is easy to update. You could jump branches and pull head, maybe that will get FreeRDP where you want it.
