### ISSUE TITLE
https_proxy authentification

### ISSUE THREAD

**Issue by glitchvern** [Thinstation/thinstation#577]
setup-chroot has an ability to use a http proxy, use a http proxy with user authentication, and use a https proxy, but not use a https proxy with user authentication.

The following patch mostly worked for me.  Not sure if it breaks something else.

[setup-chroot.patch.txt](https://github.com/Thinstation/thinstation/files/4893227/setup-chroot.patch.txt)

The git command for intel-microcode failed.  It needed a git configured with http.proxy defined and http.proxyauthmethod set to ntlm.  I don't know an elegant way  of doing that in setup-chroot so I just did it within the chroot and then did a prt-get install intel-microcode -if.

**Comment by Thinstation** [comment]
merged
