### ISSUE TITLE
Detailed version information TS_VERSION

### ISSUE THREAD

**Issue by rohrbachger** [Thinstation/thinstation#583]
We are using TS on some stations, often different hardware.
Booting with iPXE, we are using different TS ISO for some reasons sometimes.
In general we are trying to use just one.
For changes we generate a new version with some changes.
TS_VERSION is just 6.2
Is there any easy way, to see, when the build was done?
Any other way, where we can put easy our own version number`?

We are collecting the information for all PC´s, thinstations, servers to a database automatically.
I would like to see the TS version with our own buidl number.

**Comment by Doncuppjr** [comment]
By default, TS sets the ctime and mtime for all files to midnight of the day the build was created.


Sent from Yahoo Mail for iPhone


On Tuesday, July 28, 2020, 4:23 AM, rohrbachger <notifications@github.com> wrote:




We are using TS on some stations, often different hardware.
Booting with iPXE, we are using different TS ISO for some reasons sometimes.
In general we are trying to use just one.
For changes we generate a new version with some changes.
TS_VERSION is just 6.2
Is there any easy way, to see, when the build was done?
Any other way, where we can put easy our own version number`?

We are collecting the information for all PC´s, thinstations, servers to a database automatically.
I would like to see the TS version with our own buidl number.

**Comment by rohrbachger** [comment]
How can I set a environment var with a package?
Idea is to create on version number on top of TS_Version.

**Comment by Thinstation** [comment]
You would make an init file in /etc/init.d, and systemd unit file that starts it. In the init file, you could make any routine you wanted to figure out and append a var to /etc/thinstation.runtime

**Comment by rohrbachger** [comment]
That sounds like a simple and good solution. Thanks
