### ISSUE TITLE
ISO Images size - make space eater visible

### ISSUE THREAD

**Issue by rohrbachger** [Thinstation/thinstation#585]
We are creating ISO´s and boot this with iPXE from a central server.
We do have Vmware Horizon Vlient 5.4 Client installed, and for some reasons python.

That works fine in general. The image size is about 440 MB. This takes in our network only
some seconds to download, so also this is fine.

But I want to identify space eater.
The Vmware Horizion in general is large, with my test 110MB.

Without Vmware our ISO has 333MB, ( python and some special modules included)

How would be best practise to analyse the space usage.
Is 300MB a common size or should it be much smaller?

**Comment by Doncuppjr** [comment]
You can do some test builds with fastboot off. Go to /build/temp-tree/lib and do du -sh * | grep -e M

**Comment by Thinstation** [comment]
A basic xfwm build, no apps, a single machine profile should be around 110mb. You can get smaller without a WM, or with a lower resource WM.

**Comment by rohrbachger** [comment]
Thanks for the info, I will do some analysis. I  have not that much packages but
gtk, 2, 3, python , thunar, ssl xwfm + extra
We have only few hardware integrated just for a few models,.
But we have nvidia card, noveau.

So I have to start with no package and then switch on step by step.
I think I do not use fastboot, I always comment it out so I guess it's off.
#param fastboot       true	

I`sure I will identify the space eater, and hopefully I can switch it off.

**Comment by Thinstation** [comment]
Fonts eat a lot of space too.

**Comment by rohrbachger** [comment]
Finally after some testing I was able to get a image size < 400 MB.
Including Vmware View Client and some Python Modules
.
Maybe I will find some time to analyse deeper, but I guess I probably won`t get it below 350.
It eats a lot of time for testing.
The 50MB makes in our network no difference....

**Comment by Doncuppjr** [comment]
Drop fonts, especially noto and liberation.
