### ISSUE TITLE
add script or .RDP file to tsuer dekstop

### ISSUE THREAD

**Issue by SolidCore-IA** [Thinstation/thinstation#587]
We would like to use thinstation to have some remote users with old computers be able to RDP into our system using USB flash drives. we have 2 gateways that they can use west coast or east coast. I want to add the RDP file or a script to launch the connection they need; without us having to send them a USB with the correct connection. 

Not sure how to get a file to stay saved on the tsuser's desktop in thinstation. is this done before i build the image? if so how do i slipstream the file into the iso?

**Comment by Thinstation** [comment]
You could make a persistent partition, and save the file there. You have to make a map when building the iso, (fstab entry), but pretty easy to do.

**Comment by SolidCore-IA** [comment]
no way to stick it on the desktop

**Comment by Thinstation** [comment]
You can store the whole user directory on the persistent partition, in which case you can have it on the desktop.

**Comment by SolidCore-IA** [comment]
that would be a partition on the usb. is that created manually on the usb (google fstab?) or in the thinstation build config?

**Comment by Thinstation** [comment]
Hmmm. Both. The rufus utility supports making partitioned usb drives. Thinstation needs to know what to do with it, so you would also define it in your configs.

**Comment by Thinstation** [comment]
Most people that want to do something like you want to do, don't even want the desktop. They want the computer to function like a kiosk. The put the RDP session details into a config file that is loaded by thinstation and turn on kiosk mode. No desktop, less files, faster booting, less to go wrong and support.

**Comment by SolidCore-IA** [comment]
> Most people that want to do something like you want to do, don't even want the desktop. They want the computer to function like a kiosk. The put the RDP session details into a config file that is loaded by thinstation and turn on kiosk mode. No desktop, less files, faster booting, less to go wrong and support.

We have 2 RDP gateways for redundancy. One east and one west coast. Ideally I would like to give the user both options in case one side is down. What is the best way to give both rdp options?

What we don't want is to have to maintain 2 images of thinstation for each coast.

**Comment by Thinstation** [comment]
We have a selector. I’d have to dig up the syntax for the config, but it’s
just a dialog box, and the user picks the server they want.

**Comment by Thinstation** [comment]
FREERDP_SELECT_SERVER=true
FREERDP_SERVER_0="1 Big_Bad_Server_Donald"
FREERDP_SERVER_0_OPTIONS="-sec-nla"
FREERDP_KNOWN_HOST_0="Big_Bad_Server_Donald 7a:a4:af:8a:98:da:50:52:ba:33:8d:e6:15:4e:49:7b:b3"
FREERDP_SERVER_1="2 Big_Bad_Server_Road_Runner"
FREERDP_SERVER_1_OPTIONS="-sec-nla /cert-ignore"

**Comment by SolidCore-IA** [comment]
how do I set a gateway for each option?

**Comment by Thinstation** [comment]
It's going to be in the server options.
   /g:<gateway>[:<port>]             Gateway Hostname
   /gateway-usage-method:[direct|detect]
   /gd:<domain>                      Gateway domain

**Comment by SolidCore-IA** [comment]
i was able to get to the options in the config for both gateways. did the recompile and tested. this is what im getting when i launch "ms windows" rdp icon
![08-31-15:43:17_scrot](https://user-images.githubusercontent.com/14935897/91760102-c0ca4e80-eba0-11ea-967b-519dc488502d.png)
![08-31-15:44:57_scrot](https://user-images.githubusercontent.com/14935897/91760204-efe0c000-eba0-11ea-9cfb-3c472e073928.png)

**Comment by Doncuppjr** [comment]
You might need to include thunar. It's the filemanager for xfce.






On Monday, August 31, 2020, 12:45:21 PM PDT, MannyB <notifications@github.com> wrote: 







i was able to get to the options in the config for both gateways. did the recompile and tested. this is what im getting when i launch "ms windows" rdp icon

**Comment by SolidCore-IA** [comment]
now just getting the usage for xdialog window.

**Comment by Doncuppjr** [comment]
Maybe you have missing or extra quotes in your options lines.

**Comment by SolidCore-IA** [comment]
not sure where is the issue?

`AUDIO_LEVEL=90
MIC_LEVEL=0
SESSION_0_TYPE=xfwm4
SESSION_0_AUTOSTART=on
XFWM4_COMPOSITING=true
XFWM4_RED=0
XFWM4_GREEN=0
XFWM4_BLUE=0
XFWM4_START_POSITION="BOTTOM"
DESKTOP_ICON_SIZE=48
DESKTOP_FONT_SIZE=8
DESKTOP_SHOWTRASH=false
DEKSTOP_SHOWHOME=false
DESKTOP_SHOWREMOVEABLE=true
DESKTOP_SHOWFILESYSTEM=false
GTK_THEME=Adwaita
XFWM4_THEME=Default
PANEL_PAGER=false
PANEL_USER=false
PANEL_REV_CLOCKSYSTRAY=true
ICONS_THEME="Adwaita"
ICONS_CUT_SIZES="256x256 scalable"
XFWM4_START_ICON=ThinStation
XTERM_CMD="xfce4-terminal"
NET_USE=BOTH
NET_USE_DHCP=on
NET_HOSTNAME=ts_*
NET_TELNETD_ENABLED=ON
TIME_ZONE=America/Los_Angeles
NET_TIME_SERVER=us.pool.ntp.org
NET_REMOTE_ACCESS_FROM="0.0.0.0"
TFTP_BLOCKSIZE=1024
BIND_MOUNT0="storage:/mnt/storage"
STORAGE_CONFIG1=/mnt/storage
STORAGE_CONFIG2=/thinstation.profile/thinstation.conf.user.1
USB_STORAGE_SYNC=on
LOCALE=en_US
MOUNT_0="LABEL=boot     /boot           auto    x-mount.mkdir,defaults  0       0"
MOUNT_1="LABEL=home     /home           auto    x-mount.mkdir,defaults  0       0"
MOUNT_2="LABEL=swap     swap            swap    defaults        0       0"
SET_RESOLUTION_MULTIMONITOR_EXPAND='left'
SET_RESOLUTION_MULTIMONITOR_AUTOSCALE='scale'
FREERDP_SELECT_SERVER=true
FREERDP_SERVER_0="servername"
FREERDP_SERVER_0_OPTIONS="/cert:ignore /g:eastgateway.com /f /multimon:force"
FREERDP_SERVER_1="servername"
FREERDP_SERVER_1_OPTIONS="/cert:ignore /g:westgateway.com /f /multimon:force"
`

**Comment by SolidCore-IA** [comment]
> i was able to get to the options in the config for both gateways. did the recompile and tested. this is what im getting when i launch "ms windows" rdp icon
> ![08-31-15:43:17_scrot](https://user-images.githubusercontent.com/14935897/91760102-c0ca4e80-eba0-11ea-967b-519dc488502d.png)
> ![08-31-15:44:57_scrot](https://user-images.githubusercontent.com/14935897/91760204-efe0c000-eba0-11ea-9cfb-3c472e073928.png)

@Thinstation any suggestions? Im still getting the xdialog info box

**Comment by Thinstation** [comment]
I pushed a fix.

**Comment by SolidCore-IA** [comment]
Just update my thinstation and recompile?

**Comment by Doncuppjr** [comment]
Yeah. Just some syntax changes. Used to need to put a tag in your server definition, but that wasn’t documented. Changed it so that numerical tags are generated.

**Comment by SolidCore-IA** [comment]
So, the last couple times i tired to build the iso. it gives me this when I try to boot the iso. Re-installed the devstation iso, made 0 changes to the configs, built the TS iso and same thing.

![09-03-09:12:47_scrot](https://user-images.githubusercontent.com/14935897/92121693-91962600-edc8-11ea-986e-f004ba47e2a0.png)

**Comment by Doncuppjr** [comment]
Hmmm. Looks like it thinks it’s booting from a hard drive. Can you try one of the other ISO’s?

**Comment by SolidCore-IA** [comment]
virtualbox vm is only set to boot from disk not HD (there is no HD set on this VM). i am able to boot an older iso that gave me the xdialog error, but not any newer one.

**Comment by Doncuppjr** [comment]
I’ll look into it. Disable fast boot for now.

**Comment by SolidCore-IA** [comment]
in virtualbox or TS?

*nm- got it in param fastboot. dang didnt even notice that my bad

**Comment by SolidCore-IA** [comment]
so, for param fastboot; i did true and lotsofmem and same issue

**Comment by Thinstation** [comment]
I think I found the problem. Try the latest.

**Comment by SolidCore-IA** [comment]
> I think I found the problem. Try the latest.

do i have to reinstall the devstation environment? i ran "update devstation" but it didnt find any updates.

**Comment by Doncuppjr** [comment]
A factory reset for sure will get it, but you only really need to do a git pull at /thinstation from a regular root terminal

**Comment by SolidCore-IA** [comment]
working now. going to redo the config and test

**Comment by SolidCore-IA** [comment]
I now have the menu showing but both options will not launch the connection or xfreerdp
Here is my config for the menu

FREERDP_SELECT_SERVER=true 
FREERDP_SERVER_0="APExternal-East" 
FREERDP_SERVER_0_OPTIONS="/cert:ignore /g:eastgateway.com /f /multimon:force /v:serverfarm.domain" 
FREERDP_SERVER_1="APExternal-west" 
FREERDP_SERVER_1_OPTIONS="/cert:ignore /g:westgateway.com /f /multimon:force /v:serverfarm.domain"

![09-08-11:52:56_scrot](https://user-images.githubusercontent.com/14935897/92499926-782b1a80-f1ca-11ea-89e0-56ec0a311da6.png)

**Comment by Doncuppjr** [comment]
I’m gonna rewrite this function. I hate how it is currently.

**Comment by Thinstation** [comment]
Do those names resolve?

**Comment by SolidCore-IA** [comment]
No those are placed holders. The real info will launch with those commands
if I run xfreerdp from a terminal

**Comment by SolidCore-IA** [comment]
ok menu seems to be working now. just need to get the rdp gateway login set.
is there a way to make this selection box pop up another input box?
![09-14-10:01:00_scrot](https://user-images.githubusercontent.com/14935897/93100505-38a37900-f677-11ea-80ee-ca4477dc6f18.png)

**Comment by Doncuppjr** [comment]
Right now, the user dialog is disabled when the serverselect routine is used. You could combine them, but the code is not there at the moment.

**Comment by Thinstation** [comment]
I have some code you could test. Might do what you want.

**Comment by SolidCore-IA** [comment]
@Thinstation sure

**Comment by Thinstation** [comment]
Pull the latest, and add the following to your thinstation.conf.buildtime.
SESSION_1_TYPE=freerdp
SESSION_1_AUTOSTART=on
SESSION_1_FREERDP_USER=testuser
SESSION_1_FREERDP_PASS_ENABLE=true

**Comment by SolidCore-IA** [comment]
i added that line and now i get this.
![09-16-10:19:46_scrot](https://user-images.githubusercontent.com/14935897/93350036-33286900-f806-11ea-9ed8-085cb1789693.png)

am i doing this config correctly?

AUDIO_LEVEL=90
MIC_LEVEL=0
SESSION_0_TYPE=xfwm4
SESSION_0_AUTOSTART=on
SESSION_1_TYPE=freerdp
SESSION_1_AUTOSTART=on
SESSION_1_FREERDP_USER=testuser
SESSION_1_FREERDP_PASS_ENABLE=true
XFWM4_COMPOSITING=true
XFWM4_RED=0
XFWM4_GREEN=0
XFWM4_BLUE=0
XFWM4_START_POSITION="BOTTOM"
DESKTOP_ICON_SIZE=48
DESKTOP_FONT_SIZE=8
DESKTOP_SHOWTRASH=false
DEKSTOP_SHOWHOME=false
DESKTOP_SHOWREMOVEABLE=true
DESKTOP_SHOWFILESYSTEM=false
GTK_THEME=Adwaita
XFWM4_THEME=Default
PANEL_PAGER=false
PANEL_USER=false
PANEL_REV_CLOCKSYSTRAY=true
ICONS_THEME="Adwaita"
ICONS_CUT_SIZES="256x256 scalable"
XFWM4_START_ICON=ThinStation
XTERM_CMD="xfce4-terminal"
NET_USE=BOTH
NET_USE_DHCP=on
NET_HOSTNAME=ts_*
NET_TELNETD_ENABLED=ON
TIME_ZONE=America/Los_Angeles
NET_TIME_SERVER=us.pool.ntp.org
NET_REMOTE_ACCESS_FROM="0.0.0.0"
TFTP_BLOCKSIZE=1024
BIND_MOUNT0="storage:/mnt/storage"
STORAGE_CONFIG1=/mnt/storage
USB_STORAGE_SYNC=on
LOCALE=en_US
MOUNT_0="LABEL=boot     /boot           auto    x-mount.mkdir,defaults  0       0"
MOUNT_1="LABEL=home     /home           auto    x-mount.mkdir,defaults  0       0"
MOUNT_2="LABEL=swap     swap            swap    defaults        0       0"
SET_RESOLUTION_MULTIMONITOR_EXPAND='mirror'
SET_RESOLUTION_MULTIMONITOR_AUTOSCALE='scale'
FREERDP_SELECT_SERVER=true
FREERDP_SERVER_0="APExternal-East"
FREERDP_SERVER_0_OPTIONS="/cert:ignore /g:reastateway.com /f /multimon:force /v:farm.local"
FREERDP_SERVER_1="APExternal-West"
FREERDP_SERVER_1_OPTIONS="/cert:ignore /g:westgateway.com /f /multimon:force /v:farm.local"

**Comment by SolidCore-IA** [comment]
@Thinstation if i press yes on that box it goes back to the rdp selection box. if i press no thinstation shutdown

**Comment by Thinstation** [comment]
I think I have it now. Try the latest

**Comment by SolidCore-IA** [comment]
so the server box will open the freerdp log in box, but the login box is not holding the server/gateway info.
![09-17-10:06:19_scrot](https://user-images.githubusercontent.com/14935897/93482304-8fa28b80-f8cd-11ea-882f-31dbf3834a9a.png)

**Comment by SolidCore-IA** [comment]
also, i tried to make 2 session entries in the conf.buildtime. session 1 and session 2; each going to one of the gateways. This seems to work and will open the 1 login box that resolves and lets me log in. seems tho to only give me the east coast gateway (session 1) and not sure how to get the session 2 login box working.

also, if i do it this way there is no title bar or anything that tells which rdp login goes to what gateway. but this feels a lot closer to working then using the select server. any way to add a title bar?

in the scrot: on the left is the login box that auto opens when I launch thinstation. this box will let me log in perfect all the way. if i double click on the "ms windows" icon it will open another freerdp log in showing the server info

**EDIT: i was able to confirm via top on the thinstation that both login boxes are going to session 1 and not session 2.

![09-17-10:12:35_scrot](https://user-images.githubusercontent.com/14935897/93483523-e492d180-f8ce-11ea-8dfb-219ec335e8a2.png)

**Comment by Thinstation** [comment]
I'm not quite sure where your config is right now. I suspect your autostarting 1 and not 2. It does appear to be populating correctly, if you just want to turn off server edit possibility, try setting ALLOW_SERVER_EDITS=false. You might also want to do a ICONMODE=MANUAL, and set SESSION_1_ICON=On for each session you want to be accessible. Also set a SESSION_1_TITLE="Some Gateway" to give each shortcut a unique name. I tried to use a hash to represent the number, but github issue tracker doesn't play nice.

**Comment by SolidCore-IA** [comment]
hot dam this looks good. so the start menu is missing some of the settings stuff (ex: display properties, sound and keyboard type stuff). is there a way to add those back? ICONMODE=MANUAL?

![09-17-11:32:22_scrot](https://user-images.githubusercontent.com/14935897/93493212-a7800c80-f8d9-11ea-837b-78175dc92413.png)

**Comment by Thinstation** [comment]
Yeah, but you'll get links in your menu and the desktop for everyone. That's why SERVER_SELECT was created.

**Comment by SolidCore-IA** [comment]
gotcha so all that isnt working with SERVER_SELECT was getting the freerdp options to load from the SERVER_SELECT function in the login freerdp box. is this tied to the SESSION settings?

**Comment by Thinstation** [comment]
I'm not sure when you last updated, but I have been testing SERVER_SELECT all morning, and it's working correctly. You don't need any sessions other than 0 which is the Window Manager

**Comment by SolidCore-IA** [comment]
I disabled the iconmode setting and that is good to go for me. let me test these icons and then I will try the server_select again

**Comment by SolidCore-IA** [comment]
this is perfect below. 

SESSION_1_TITLE="AP East"
SESSION_1_TYPE=freerdp
SESSION_1_AUTOSTART=off
SESSION_1_FREERDP_SERVER=farm.local
SESSION_1_FREERDP_OPTIONS="/cert:ignore /g:eastgateway.com /f /multimon:force"
SESSION_1_FREERDP_PASS_ENABLE=true
SESSION_1_ICON=On
#
SESSION_2_TITLE="AP West"
SESSION_2_TYPE=freerdp
SESSION_2_AUTOSTART=off
SESSION_2_FREERDP_SERVER=farm.local
SESSION_2_FREERDP_OPTIONS="/cert:ignore /g:westgateway.com /f /multimon:force"
SESSION_2_FREERDP_PASS_ENABLE=true
SESSION_2_ICON=On
#
ALLOW_SERVER_EDITS=false
#ICONMODE=MANUAL


![09-17-12:23:14_scrot](https://user-images.githubusercontent.com/14935897/93499083-91c21580-f8e0-11ea-9b5e-8a411a556802.png)

**Comment by Doncuppjr** [comment]
Glad you found something that worked.

**Comment by Thinstation** [comment]
I don't think you really want wifi-connect. Network manager applet is much cleaner.

**Comment by SolidCore-IA** [comment]
heads up. select_server is still doing a blank freerdp box. i did a reset on the devstation and re did the config.

![09-17-15:37:16_scrot](https://user-images.githubusercontent.com/14935897/93519072-ba0b3d80-f8fb-11ea-81d3-d683191e935e.png)

**Comment by Thinstation** [comment]
Hmmmm. I don't even see the server dialog when I do it. I only have the user and pass entry

**Comment by Thinstation** [comment]
You shouldn't have two windows visible.

**Comment by SolidCore-IA** [comment]
It doesn't show both. I opened the selection box again to only show it's
working. If I select one and hit connect it opens the free RDP as shown

**Comment by Thinstation** [comment]
I don't get it. I litterally only add these lines to a default config, and it works like you suggested you want.
FREERDP_SELECT_SERVER=true
FREERDP_SERVER_0="1 Big_Bad_Server_Donald"
FREERDP_SERVER_0_OPTIONS="-sec-nla /d:thinstation.local"
FREERDP_KNOWN_HOST_0="Big_Bad_Server_Donald 7a:a4:af:8a:98:da:50:52:ba:33:8d:e6:15:4e:49:7b:b3"
FREERDP_SERVER_1="2 192.168.1.10"
FREERDP_SERVER_1_OPTIONS="-sec-nla /cert-ignore /d:thinstation.local"

I pick a server click connect then, I have the user/pass entry. The server tab is not visible.

**Comment by OzzyPosse** [comment]
> 

Where is this config used? in the freerdp build. conf? 
Thanks
