### ISSUE TITLE
6.2.6 dev seems to have problems with VirtualBox / VMW Player

### ISSUE THREAD

**Issue by Gunnar-GO** [Thinstation/thinstation#588]
i tried several times to install the DEV. i tried different systems with different CPU / RAM combinations.
The conclusion is: that the install fails ; it can't boot up.

Maybe theres a trick or simple fix ? At the moment i can't use the tool.

Sadly theres no simple pre-built images. to test and compare. So the DEV Enviroment is needed for build examples. 

After install the Box freezes at this point:
![VirtualBox_ThinStation DEV_16_08_2020_14_14_26](https://user-images.githubusercontent.com/24938625/90337186-23d4b680-dfe1-11ea-9370-2da77875369c.png)

on VMWare Player its simply doesn't boot up after install.

**Comment by Doncuppjr** [comment]
Can you send me the install.log and installer.log ?






On Sunday, August 16, 2020, 07:56:30 AM PDT, Gunnar-GO <notifications@github.com> wrote: 







i tried several times to install the DEV. i tried different systems with different CPU / RAM combinations.
The conclusion is that the install fails. it can't boot up.

Maybe theres a trick or simple fix ? At the moment i can't use the tool.

Sadly theres no simple pre-built images. to test and compare. So the DEV Enviroment is needed for build examples.

**Comment by Thinstation** [comment]
Increase the display adapter memory. 64mb should be enough. 16 is not sufficient for the higher resolutions.
