### ISSUE TITLE
FreeRDP Login Prompt Issue

### ISSUE THREAD

**Issue by WeAnswerJake** [Thinstation/thinstation#589]
Hello! I have 2 issues here, I'd like to fix one of them, hope the following makes sense:

I plan to use freerdp to connect users to our Windows rds environment, they'd connect to our connection broker and then get directed to one of our hosts. 

If I disable FreeRDP asking for credentials by removing the getusr/getpass files, they get directed to the windows login page for the broker (which is great, exactly how I want it to work!) however, once logged in, it gets directed to a host and they have to enter their credentials a second time, which my end users will not like! 

I can get around this by enabling freerdp asking for credentials again, however it only lets me type in the username and password box when the mouse is hovered over the window, which I know isn't a massive deal but I really want the whole thing to be seamless! 

If you're aware of any fixes to the above 2 problems please let me know :)

Things I've tried: 
Group Policy settings on the hosts/broker to allow connections without credentials needing to be entered again

Tia,
Jake

**Comment by Thinstation** [comment]
The way that is exactly how you want it to work, likely isn't. That's an old security model and shouldn't be used. To fix the keyboard and mouse focus issue, you need to use a window manager. There are 3 available, and all offer a kiosk mode that hides everything but the login window.
