### ISSUE TITLE
variable MIC_LEVEL is empty

### ISSUE THREAD

**Issue by DeadPo01** [Thinstation/thinstation#592]
Thinstation 6.2.4
I need to redirect MIC over FreeRDP. I've set MIC_LEVEL to 100(or anything else, except 0) (in thinstation.network), but it's empty in final environment on host... 
On host, after booting "echo $AUDIO_LEVEL" will give you the value that was set in config, but "echo $MIC_LEVEL" will return empty value.
Bacause of this the MIC on is muted...
This variable is checked in "/thinstation/build/packages/alsa/etc/init.d/audio".

If i use "amixer sset Capture 50% cap" the MIC  starts to work on host and on RDP server.

The question is - how or where to set variable MIC_LEVEL to pass it to script of alsa audio.

**Comment by Thinstation** [comment]
Interesting. See if this commit fixes your issue.
https://github.com/Thinstation/thinstation/commit/dbef5901c4bbbaf0efa229c08dd8ea79107d6c45

**Comment by DeadPo01** [comment]
Yep, thx. This helped to pass variable MIC_LEVEL to script, now it contains the value from config.

But there is another problem in  "/thinstation/build/packages/alsa/etc/init.d/audio" script....
Variable MIC_DEVICE, it's being checked on zero value, and if it's true it will get value = "Mic", but i can't understand from where it (this variable) should get it's value before this check? Should i set it in config too and add to "thinstation.export"?

And function "have_control" is not correct, may be it should be updated.... Because i get wrong information about my system by this function...
I have "2 audio cards (internal and video-hdmi)", and i have "Capture" - it's internal 3,5-Microphone-Jack, but have no "Mic"... But by cards, i have "mic", thit is PVolume switch, and have "Capture" on that card that is CVolume switch but on card 1(hdmi) and it should be monitor mic....
Here is my CLI output:

> ts_d02788b065c9:\~$ amixer sget Mic
> amixer: Unable to find simple control 'Mic',0

> ts_d02788b065c9:\~$ amixer sget Capture
> Simple mixer control 'Capture',0
>   Capabilities: cvolume cswitch cswitch-joined
>   Capture channels: Front Left - Front Right
>   Limits: Capture 0 - 65536
>   Front Left: Capture 36701 [56%] [off]
>   Front Right: Capture 36701 [56%] [off]

> ts_d02788b065c9:~$ amixer sget -c 0 Mic
> amixer: Unable to find simple control 'Mic',0
> 
> ts_d02788b065c9:\~$ amixer sget -c 1 Mic
> Simple mixer control 'Mic',0
>   Capabilities: pvolume pswitch
>   Playback channels: Front Left - Front Right
>   Limits: Playback 0 - 31
>   Mono:
>   Front Left: Playback 0 [0%] [-34.50dB] [off]
>   Front Right: Playback 0 [0%] [-34.50dB] [off]

> ts_d02788b065c9:~$ amixer sget -c 0 Capture
> amixer: Unable to find simple control 'Capture',0
> 
> ts_d02788b065c9:~$ amixer sget -c 1 Capture
> Simple mixer control 'Capture',0
>   Capabilities: cvolume cswitch
>   Capture channels: Front Left - Front Right
>   Limits: Capture 0 - 31
>   Front Left: Capture 31 [100%] [30.00dB] [off]
>   Front Right: Capture 31 [100%] [30.00dB] [off]
> 

May be it will be better to somehow get Mic-Name and Mic-Volume from config? For example Mic_0_LEVEL=55 and Mic_0_DEVICE=Capture and so on...

Or get devices from card by "amixer -c $card controls" and search for mic or capture...

**Comment by DeadPo01** [comment]
For me i just changed if statement to this:

>  if [ -n "$MIC_LEVEL" ] && [ "$MIC_LEVEL" -gt "0" ]; then		
> 	if [ -z "$MIC_DEVICE" ]; then MIC_DEVICE=Mic; fi			
> 	amixer sset $MIC_DEVICE $MIC_LEVEL% unmute
> fi

I have only one microphone, and it's enough for me without MIC_№_DEVICE.
And i don't know how to pass over "thinstation.exports" variable with counter.

**Comment by DeadPo01** [comment]
And.... not working anyway =(( All variables exists with values.. but microphone is still muted on initialization of audio =(
And debug is empty... How to enable debug? I've set in build.conf package debug and bootverbosity 48 (packages and modules).. and debug is empty =(

**Comment by DeadPo01** [comment]
If i start script /etc/init.d/audio on client after boot (commented "if ! pkg_initialized") than script successfully enables microphone.

**Comment by Thinstation** [comment]
Are you plugging the mic in? 
Yeah, add MIC_DEVICE to your conf and to exports.

**Comment by Thinstation** [comment]
Debugging is a little different with systemd. There are two lines at the top of the audio script. uncomment and make a new build. You should get your debugging output.

**Comment by DeadPo01** [comment]
> Are you plugging the mic in?
> Yeah, add MIC_DEVICE to your conf and to exports.

Of course it's plugged in. And it works if start the script /etc/init.d/audio on client after boot (commented "if ! pkg_initialized"), under initialized system, but i need it to work on system start, without any additional comands from user.

> Debugging is a little different with systemd. There are two lines at the top of the audio script. uncomment and make a new build. You should get your debugging output.

I need to uncomment this lines?
```
#set -x
#exec </dev/null >/var/log/audio.log  2>&1

```
If so, i've tried..... nothing has changed.... no log anywhere.. or i've been searching not in right place.

**Comment by Doncuppjr** [comment]
I don't know where you are searching, but the log should be at /var/log/audio.log

**Comment by DeadPo01** [comment]
No log... =(
May be you can tell me, please, step by step what to do to enable debug? May be i missed something?! =(
I did:
1. enabled package debug
2. set param bootlogo to false
3. set param splash  to verbose (nothing changed, and on the boot screen only lines about loading vmlinuz and initrd)
4. set param bootverbosity to 48 (modules-16 + packages-32 = 48)
5. uncommented this lines in "/etc/init.d/audio":
```
set -x
exec </dev/null >/var/log/audio.log  2>&1
```

And no log anywhere... No log at all... about any package or module =( Only 600 bytes in boot.log (only lines about loading core and configs)

**Comment by DeadPo01** [comment]
Tried to add this lines in "/etc/init.d/audio":
```
echo "Device: " $MIC_DEVICE " level: " $MIC_LEVEL >> /var/log/audio.log		
amixer sset $MIC_DEVICE $MIC_LEVEL% cap	 >> /var/log/audio.log	
```
First line was added to log, second line didn't wrote anything to log....
But if i execute second line after boot under the user - it enables microphone and added record to log.... I'am confused.... o_O =(

**Comment by Thinstation** [comment]
I'm not sure whats happening over there. I don't change the boot verbosity, I only uncomment the two lines at the top of init.d/audio. This produces a log for me, in /var/log. The results are what I expect. Are you using the tsuser?

**Comment by DeadPo01** [comment]
Yes, i'am using tsuser.

**Comment by Thinstation** [comment]
I would say keep it simple for the time being. Disable the user switch by commenting out tsuser in build.conf. tsuser might not be able to view the logs.

**Comment by DeadPo01** [comment]
But for reading the logs and editing system i use "su".
Finally... i've got the logs! The cause was - bootverbosity.. i've set it back to 4(init), and now logs are in place. =)
But why is the connection refused?
```
+ pkg_initialized audio
+ '[' -f /var/packages/audio ]
+ return 1
amixer: Mixer attach default error: Connection refused
+ '[' -n 55 ]
+ '[' 55 -gt 0 ]
+ '[' -z Capture ]
+ echo '(in if statement) Device: ' Capture ' level: ' 55
+ amixer sset Capture '55%' cap
ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

amixer: Mixer attach default error: Connection refused
+ cut -c2
+ grep -e : /proc/asound/cards
grep: /proc/asound/cards: No such file or directory
+ pkg_set_init_flag audio
+ touch /var/packages/audio
```

**Comment by Thinstation** [comment]
It looks like your card isn't detected by the time that audio runs. Send me the file produced by systemd-analyze plot > boot.svg

**Comment by DeadPo01** [comment]
systemd-analyze: not found
May be i should enable some package and rebuild?

**Comment by Thinstation** [comment]
It's part of systemd....don't know why you can't find it. You'll need to be root

**Comment by DeadPo01** [comment]
Ok, here is the file.
[boot.zip](https://github.com/Thinstation/thinstation/files/5143492/boot.zip)
But this file is from Virtual Machine WMVare.... i have no access now to host, i'll do boot.svg from host on next week.
But on virtual machine audio.log is the same.

**Comment by Thinstation** [comment]
It's almost at the end, I don't know why your card isn't seen yet. You could try adding rngd(it took the longest) to the service file of audio as an after requirement.

**Comment by DeadPo01** [comment]
Am i did right? In file /build/packages/alsa/etc/systemd/system/audio.init.service
![123](https://user-images.githubusercontent.com/70272456/91603006-e7a43d00-e974-11ea-8b32-4010b2ed1ef8.png)

Nothing changed... PulseAudio connection refused =(

**Comment by Doncuppjr** [comment]
The pulseaudio message is a red herring, don't worry about that. /proc/asound/cards not found is more concerning.

**Comment by DeadPo01** [comment]
Sorry, because it's from Virtual Machine. On the real host there are two audio cards. I'll get log from real host on monday. 
Thanks for all your help!

**Comment by DeadPo01** [comment]
Here is the log from real host. Audio level for master channel is set as expected, from config... but not for Capture =(
```
 pkg_initialized audio
+ '[' -f /var/packages/audio ]
+ return 1

+ '[' -n 55 ]
+ '[' 55 -gt 0 ]
+ '[' -z Capture ]
+ amixer sset Capture '55%' cap
ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

amixer: Mixer attach default error: Connection refused
+ grep -e : /proc/asound/cards
+ cut -c2
+ '[' -n 81 ]
+ have_control Master
+ amixer sget -c 0 Master
+ return 1
+ have_control PCM
+ amixer sget -c 0 PCM
+ return 1
+ have_control CD
+ amixer sget -c 0 CD
+ return 1
+ have_control Video
+ amixer sget -c 0 Video
+ return 1
+ '[' -n 81 ]
+ have_control Master
+ amixer sget -c 1 Master
+ return 0
+ amixer sset -c 1 Master '81%' unmute
Simple mixer control 'Master',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback 0 - 31
  Mono: Playback 26 [84%] [-7.50dB] [on]
+ have_control PCM
+ amixer sget -c 1 PCM
+ return 1
+ have_control CD
+ amixer sget -c 1 CD
+ return 1
+ have_control Video
+ amixer sget -c 1 Video
+ return 1
+ pkg_set_init_flag audio
+ touch /var/packages/audio

```
And boot.svg from real host is in attached zip file.
[boot_host.zip](https://github.com/Thinstation/thinstation/files/5149073/boot_host.zip)

**Comment by Thinstation** [comment]
Alsa won't connect to pulse during startup. Pulse is started in the user session, and takes over from alsa mixer. The error message is annoying, but meaningless. I'll do some tests.

**Comment by Thinstation** [comment]
It's working for me......

**Comment by DeadPo01** [comment]
For me it's not working =( Only master volume is set on boot from config, but not microphone =(
I've found the way out over the command 'amixer sset Capture % cap' inserted into the host config.

**Comment by sqnoc** [comment]
I had same pbm with my Intel integrated sound card.
I resolved it with added this command in the /etc/init.d/audio script:
amixer -c $card sset Capture cap
in line 30:

                if [ -n "$MIC_LEVEL" ] && [ "$MIC_LEVEL" -gt "0" ]; then
                        if [ -z "$MIC_DEVICE" ]; then MIC_DEVICE=Mic; fi
                        if have_control $MIC_DEVICE; then
                                if have_control Capture; then
                                        **amixer -c $card sset Capture cap**
                                        amixer sset Capture $MIC_LEVEL% unmute
                                fi
                                amixer sset $MIC_DEVICE playback mute
                                amixer sset $MIC_DEVICE $MIC_LEVEL% cap
                        elif have_control Capture; then
                                amixer sset Capture 0%
                        fi
                fi

**Comment by Thinstation** [comment]
added

**Comment by sqnoc** [comment]
Other comment for a part of audio script: packages/alsa/etc/init.d/audio
```
if ! pkg_initialized $PACKAGE; then
        for card in `grep -e ":" /proc/asound/cards |cut -c2`; do
```
When I plug my Dell USB SoundBar I obtien with this :
```
hostname:~# cat /proc/asound/cards
 0 [Intel          ]: HDA-Intel - HDA Intel
                      HDA Intel at 0xf7adc000 irq 33
 1 [SoundBar       ]: USB-Audio - Dell AC511 USB SoundBar
                      Dell Dell AC511 USB SoundBar at usb-0000:00:1a.0-2, full speed
hostname:~# grep -e ":" /proc/asound/cards
 0 [Intel          ]: HDA-Intel - HDA Intel
 1 [SoundBar       ]: USB-Audio - Dell AC511 USB SoundBar
                      Dell Dell AC511 USB SoundBar at usb-0000:00:1a.0-2, full speed
hostname:~# grep -e ":" /proc/asound/cards |cut -c2
0
1

hostname:~#
```

There is 3 lines greped with the script and consequetly the result of the last value of "card" is empty.
I have change `grep -e ":" ` to `grep -e "]:" ` to exclude the bad values
