### ISSUE TITLE
Network don`t start automatical r8169

### ISSUE THREAD

**Issue by blcorp** [Thinstation/thinstation#593]
Hi!
I have Gigabyte nettop with realtek gigabit network adapter which use r8169 kernel module.
Booting by PXE via TFTP. 
I have build latest realese 6.2.6 and network don`t start automatic.  
In build.conf packages autonet, netfiles are enable. Also try with ts-classic with same result - after downloading image network don`t start automatic and by ifconfig I see only local inteface.
In console I try to disable kernel module by rmmod r8169 and after that do modprobe r8169 and after that network up automatical.
With Realese 6.1.1 all was fine.
What changes in latest realese whith network?

**Comment by Thinstation** [comment]
An out of tree kernel module was added. Perhaps you don't need it.

**Comment by blcorp** [comment]
What can I do to get the network up automatically?

**Comment by Doncuppjr** [comment]
You can use either 
package autonet
or
package networkmanager
but you can't use both.

**Comment by DoctorDeatch** [comment]
it helped me to collect with the parameter  ./build --allmodules

**Comment by blcorp** [comment]
Adding the 'realtek' module solved my problem.
