### ISSUE TITLE
Freerdp Server selection broken

### ISSUE THREAD

**Issue by Xenomes** [Thinstation/thinstation#594]
The server selection is broken with the latest change.
modified: ts/build/packages/freerdp/build/extra/etc/cmd/freerdp.options

**Comment by Doncuppjr** [comment]
The documentation didn't match the code. It wasn't what input was expected to make select_server work correctly. We should nail that down, write the documentation and then I will make the code work.

**Comment by Xenomes** [comment]
OK it looks like there was added a counter to the line. Look forward to see the updated sample config.

**Comment by Doncuppjr** [comment]
Probably gonna redo that whole function, I just need to decide what is really needed from a UI perspective.

**Comment by Thinstation** [comment]
Can you provide an example that worked with the previous code? I need to figure this out.

**Comment by Xenomes** [comment]
Yes off course. This i have in my config to select a server. Removed my options 😉
```
FREERDP_SELECT_SERVER=true
FREERDP_SERVER_0="RDS_Server 192.168.1.105"
FREERDP_SERVER_0_OPTIONS='/u:'
‎#FREERDP_KNOWN_HOST_0=""
FREERDP_SERVER_1="RDS_Server_New 192.168.1.106"
FREERDP_SERVER_1_OPTIONS='/u:'
‎#FREERDP_KNOWN_HOST_1=""
```

**Comment by Doncuppjr** [comment]
Ugh, two pieces of info in a single field. Nightmare. That is gonna change.

**Comment by Xenomes** [comment]
Did i use it wrong? this is what in the sample provide.
```
FREERDP_SELECT_SERVER=true
FREERDP_SERVER_0="1 Big_Bad_Server_Donald"
FREERDP_SERVER_0_OPTIONS="-sec-nla"
FREERDP_KNOWN_HOST_0="Big_Bad_Server_Donald 7a:a4:af:8a:98:da:50:52:ba:33:8d:e6:15:4e:49:7b:b3"
FREERDP_SERVER_1="2 Big_Bad_Server_Road_Runner"
FREERDP_SERVER_1_OPTIONS="-sec-nla /cert-ignore"
```

**Comment by Doncuppjr** [comment]
No, that was a user contribution, but I don’t like how it was done.

**Comment by Thinstation** [comment]
Try the current commit. I think it will handle both cases.
