### ISSUE TITLE
Firefox preset profile script ignore always the FF.tar.gz file

### ISSUE THREAD

**Issue by teha-at** [Thinstation/thinstation#596]
Hi,

in the `firefox-init` script there is a functionality to add a pre configured Mozilla-Profile (.mozilla) which has to be in the file `FF.tar.gz`.
see here: https://github.com/Thinstation/thinstation/blob/6.2-Stable/ts/build/packages/firefox/etc/init.d/firefox-init#L13

But there is a condition which checks if there a `.mozilla` directory and if, then the `FF.tar.gz` file will be not unpacked.

Unfortunately in the firefox package is a [file](https://github.com/Thinstation/thinstation/blob/6.2-Stable/ts/build/packages/firefox/etc/skel/.mozilla/firefox/crashreporter.ini) under  `.mozilla/firefox/` and this mean, that the `FF.tar.gz` will never been considered.

Maybe the simplest change is to remove the first condition:

from
```sh
if [ ! -e $HOME/.mozilla ] && [ -e /etc/FF.tar.gz ]; then
		tar -C $HOME -zxvf /etc/FF.tar.gz
	else
```

to

```sh
if [ -e /etc/FF.tar.gz ]; then
		tar -C $HOME -zxvf /etc/FF.tar.gz
	else
```

If a user put a `FF.tar.gz` under `/etc/` then he has to take care what he do.

**Comment by Thinstation** [comment]
Sounds good.
