### ISSUE TITLE
Lenovo Thinkcentre M715Q AMDGPU issues

### ISSUE THREAD

**Issue by rohrbachger** [Thinstation/thinstation#597]
With the actual thinstation version, ( checked out the source some minutes ago)
With an version about 7 month ago, this has been working fine.

package xorg7-amdgpu is enabled, but the module seems not to load.
It might be related to a newer kernel or X11 version

I guess with lspci -k  I should see somewhere amdgpu, but is not there.

In Xorg.0.log I do see:Unable to find a valid framebuffer device
" Cannot run in framebuffer mode.
How I can get this running again, where is a start point to search the error?

**Comment by Thinstation** [comment]
I would do an allmodules build. Also enable allfirmware in build.conf

**Comment by rohrbachger** [comment]
Thanks, this pointed in the right direction. I added some modules, that solved the issues.
Also I can rotate now the screen, what before on the Lenovo did not worked.
Old Kernel version was 5.4.6TS...
