### ISSUE TITLE
Thinstation Mountpoint Issue

### ISSUE THREAD

**Issue by FocusAndrew** [Thinstation/thinstation#598]
Hi All,
New here so please be gentle...

Trialling Thinstation and boot via PXE.
Client PC boots and connects to Thinstation server but errors:
/lib is not a mountpoint
Fastboot was enabled, but something went wrong with the transfer or mount.

Interestingly this works 100% in a VMWare VM set to PXE boot so i know the image and server are working fine.

The test client is an HP Prodesk with a new SSD inside.

My linux knowledge is limited (currently learning fast) but any pointers would be most welcome.

TIA!

**Comment by Doncuppjr** [comment]
You might be missing a network module or firmware. Make an allmodules build or turn off fast boot in build.conf


Sent from Yahoo Mail for iPhone


On Monday, September 28, 2020, 5:30 AM, FocusAndrew <notifications@github.com> wrote:




Hi All,
New here so please be gentle...

Trialling Thinstation and boot via PXE.
Client PC boots and connects to Thinstation server but errors:
/lib is not a mountpoint
Fastboot was enabled, but something went wrong with the transfer or mount.

Interestingly this works 100% in a VMWare VM set to PXE boot so i know the image and server are working fine.

The test client is an HP Prodesk with a new SSD inside.

My linux knowledge is limited (currently learning fast) but any pointers would be most welcome.

TIA!

**Comment by FocusAndrew** [comment]
That seems to have worked, thank you!
On to the next issue now :)
