### ISSUE TITLE
Thinstation: install thinstation to local disk via usb

### ISSUE THREAD

**Issue by jmosley205** [Thinstation/thinstation#599]
Good Morning,  
Is there a way I can create a bootable USB stick that partitions a local disk and installs thinstation to that newly formatted disk?
Thank you for any advice, I definitely appreciate it!

**Comment by jmosley205** [comment]
Scratch this, we are going to use Clonezilla to clone/restore the disk on to the computers using our samba server and a Clonezilla live USB. Thanks for the help!

**Comment by Doncuppjr** [comment]
Yes. Of course, but if you have a clonezilla infrastructure, that should work too.






On Monday, September 28, 2020, 10:04:33 AM PDT, jmosley205 <notifications@github.com> wrote: 







Good Morning,
Is there a way I can create a bootable USB stick that partitions a local disk and installs thinstation to that newly formatted disk?
Thank you for any advice, I definitely appreciate it!
