### ISSUE TITLE
firefox - actual version 80.0.1

### ISSUE THREAD

**Issue by rohrbachger** [Thinstation/thinstation#600]
I have trie dto use the firefox 80.0.1 instead of the old 60.0.1 version.

When started on TS, I get an error message, firefox does not start.

XPCOMGlueLoad error for file /lib/firefox/libxul.so
/lib/firefox/libnss3.so version NSS_3.47 not found ( required by lib/firefox/libxul.so
Could not load XPCOM
Both files are there, 

In the install script I do see a line patchelf --set-rpath /lib/firefox $INSTALLDIR/firefox/libnss3.so

I do see, firefox delivers another libnss3.so, much smaller.
But this is not installed in TS, so probably the patchelf is doing that.

Replacing libnss3.so with the original small from firefox made the firefox starting,
but it does not work. Only empty browser windows.

So libnss3 seems to create the problem.

Can anyone help with the right hint?

**Comment by Thinstation** [comment]
Firefox usually requires upgrades to nss and nspr. Done. Factory Reset and try again.

**Comment by rohrbachger** [comment]
works fine.
I noticed the kernel is also updated.
Some of our TS freezes with the older version sometimes, some once a day.
No keyboard / mouse, and with that no chance to look at logs.
I hope with the actual version is will go away, so we will get feedback next week.
It might be related to the actual VM View client, so we switched back to an older one also.
This is hard to figure out, I will try next time to get remote by telnet or ssh a connection.

**Comment by Doncuppjr** [comment]
Hmmm, well at least let me know about the hardware that is giving you trouble. Might be a power saving thing.

**Comment by rohrbachger** [comment]
I don't think its hardware.
We do have Dell optiplex 790 with nvidia card in use and Lenovo 715q.
Letś wait 1-2 weeks, I have changed to an older Horizon View Client and will use the actual version.
It stops during working, just somewhere in the middle. All user are just using the View client.
