### ISSUE TITLE
Kernel Panic

### ISSUE THREAD

**Issue by DoctorDeatch** [Thinstation/thinstation#603]
Hello friends
I make my own assembly in which only vmviev is included, but in all cases I get a kernel panic:(
https://drive.google.com/file/d/1oQEaPQubXvPUrEEqoFyvT7hmIWFdS5bz/view?usp=sharing
what could be wrong?

**Comment by Doncuppjr** [comment]
Not enough RAM in the test machine

**Comment by DoctorDeatch** [comment]
> 
> 
> Not enough RAM in the test machine

What are his minimum requirements now?
6.1 worked 1 GB

**Comment by Thinstation** [comment]
Depends on what you include. Try more RAM.

**Comment by DoctorDeatch** [comment]
thanks
