### ISSUE TITLE
Intel NUC don't start after initrd.

### ISSUE THREAD

**Issue by ProkopMax** [Thinstation/thinstation#605]
Hello.
I am trying to load nuc7cjyh2 by pxe uefi with thinstation os 6.2. 
I am getting error like following this link [https://github.com/Thinstation/thinstation/issues/566](url) and I rebuilt the kernel with config from the nuc7jy.zip but kernel building with error.
![ts62](https://user-images.githubusercontent.com/72852008/96545752-a44db700-12b1-11eb-8612-f5bed71917da.JPG)

My build.conf [build.conf.zip](https://github.com/Thinstation/thinstation/files/5402797/build.conf.zip)

**Comment by ProkopMax** [comment]
I excluded nvidia drivers and kernel building with no errors and my nuc boot succsess, but usb don't work with machine intel_nuc7jy.
I will try to collect machine with --allmodules.

**Comment by ProkopMax** [comment]
How can I record efi.iso, because nuc supports uefi boot only ? Only legasy image is collected in the iso folder with a size of about 2 gb.

**Comment by Thinstation** [comment]
use the refind-iso or systemd-boot-iso

**Comment by Thinstation** [comment]
I pushed a config that should work for you. It's called nuc-june.config, and I put it in the kernel-TS folder. overwrite ts.config, then run pkgmk -um, then pkgmk -u, pkgmk -uf, pkgmk -u

**Comment by ProkopMax** [comment]
I got error 
![ts62](https://user-images.githubusercontent.com/72852008/96730401-caad4880-13be-11eb-83a5-67dd1ec1a552.JPG)

I installed a new devstation os 6.2 and try rebuild kernel with nuc-june.config. 

But same error.
![ts63](https://user-images.githubusercontent.com/72852008/96737127-fc75dd80-13c5-11eb-93eb-16b118f59a6d.JPG)

**Comment by Doncuppjr** [comment]
Looks like it worked the second time.

**Comment by ProkopMax** [comment]
I cleared the folder and ran the build kernel and the same error.
But with the config ts.config.ubuntu from nuc7jy and disabling nvidia drivers, the kernel built successfully.

**Comment by Thinstation** [comment]
That could be the gcc plugins. I don't know why it doesn't complete for you though. It's working fine over here.

**Comment by ProkopMax** [comment]
Can you build a kernel with nuc-june.conf and put it in a different folder?

**Comment by Thinstation** [comment]
I added a kernel for you. You can build with --kernel JC. It's a localmodconfig for that JuneCanyon NUC

**Comment by ProkopMax** [comment]
Thanks. It worked with this kernel.
