### ISSUE TITLE
Download progress

### ISSUE THREAD

**Issue by DoctorDeatch** [Thinstation/thinstation#606]
Hello friends
in TS 5.5 when loading the kernel there was a progress bar
how to enable this feature in TS 6.2?

**Comment by Thinstation** [comment]
I'm not sure what you mean.

**Comment by DoctorDeatch** [comment]
[Loading TS6.2](https://drive.google.com/file/d/1Sp8TlWkAoWmU-G8vbmkBiM7Uy9l20AEC/view?usp=sharing)
[Loading TS5.52](https://drive.google.com/file/d/1ByLAR5hy1iBFXhJOOYktUkG-jQPKiMzy/view?usp=sharing)
in 5.5 there are dots showing the download process by tftp
in 6.2 there is no such
this is very annoying to the support service, since users think that everything is hanging and they are rebooting the stations

**Comment by Thinstation** [comment]
What does your pxelinux.cfg look like?

**Comment by DoctorDeatch** [comment]
TIMEOUT 0
DEFAULT default
DISPLAY product.txt

LABEL default
        KERNEL ::/boot/vmlinuz
        APPEND initrd=::/boot/initrd  splash=silent,theme:default console=tty1 LM=3

**Comment by Thinstation** [comment]
You could try going back to syslinux 6.03.

**Comment by Thinstation** [comment]
Or use the new grub functionality.
