### ISSUE TITLE
Citrix ICA Client download failure

### ISSUE THREAD

**Issue by smith51** [Thinstation/thinstation#608]
Building Thinstation with Citrix ICA. Can't load ica client from citrix site because theris the new version. Now file name is `linuxx64-20.10.0.6.tar.gz`

```
INSTALLING ICA
cp: cannot stat '//downloads/linuxx64-20.9.0.15.tar.gz': No such file or directory

Error has occured copying file
Build Aborted
```

I manually downloaded file `linuxx64-20.10.0.6.tar.gz`. placed it to `downloads` folder. made simlink.

**Comment by Thinstation** [comment]
Updated build.urls.
