### ISSUE TITLE
ISO vs PXE boot

### ISSUE THREAD

**Issue by versus2** [Thinstation/thinstation#612]
Have been using the same build in PXE (Ipxelinux.'0) and ISO . PXE boots on the same hardware without a problem applying network settings in network config file. Even ISO image mounted on VM works. ISO mounted on USB stick doesn't . What should I be looking into?

**Comment by Thinstation** [comment]
How did you put the iso on USB?

**Comment by versus2** [comment]
Rufus

**Comment by Thinstation** [comment]
Did you use the rufus that is on the CD, or your own install?

**Comment by versus2** [comment]
My own install. Windows. Devstation is on VM. Iso copied from Devstation  boot-images/iso/thinstation.iso

**Comment by Thinstation** [comment]
So we use a patched version of syslinux for efi. rufus doesn't know were to find the pieces it needs to make the thumb bootable. Before making your image, do prt-get install rufus. Then rufus will be placed on the ISO. Use that version of rufus, and you should be good.

**Comment by versus2** [comment]
Will it help with system stopping mid way as stick is actually booting up to a point until throwing that it cannot find global config file (netwok file)  or /dev is not a mountpoint error?
It’s not that is not booting at all. 
I had smiliar type of errors with PXE booting normal pxelinux and fastboot. Ipxelinux works flawlessly over PXE. Maybe becuse it loads something like http://192.168.10.229/boot/vmlinuz and not just only /vmlinuz. Difference in config folder file.
ISO booting is similar like normal pxelinux booting and it fails at the same place. Surprisingly booting from ISO in VM works without a problem.

**Comment by Thinstation** [comment]
That could be the volume label. You might need to adjust your mount definitions. Make MOUNT_0 look like 
MOUNT_0="LABEL=THINSTATION     /boot           auto    x-mount.mkdir,defaults  0       0"
Then when Rufus mangles the ISO label from ThinStation to THINSTATION, you should be good.

**Comment by versus2** [comment]
Wouldn't it be the same for PXE and VM ISO boot?  These two go all the way to gui without a problem. Somehow machine usb boot differs from these two.  Network works ok in USB  and TFTP is accessible (test file transfer).  Sent from my Huawei phone-------- Original Message --------Subject: Re: [Thinstation/thinstation] ISO vs PXE boot (#612)From: ThinStation To: Thinstation/thinstation CC: versus2 ,Author 
That could be the volume label. You might need to adjust your mount definitions. Make MOUNT_0 look like
MOUNT_0="LABEL=THINSTATION     /boot           auto    x-mount.mkdir,defaults  0       0"

**Comment by Thinstation** [comment]
When booting from ISO, we look for an Optical drive, there is usually only one. When booting from network, there again is usually only one option. When booting from disk(usb), there are often many partitions that we could look at, so we make a mount definition to tell the core how to find the rest of the files.

**Comment by rohrbachger** [comment]
I do not know if this helps:
We ae using iPXE since a while, as this is much faster than the ftfp. We are also using for WinPE Boot.
Standard Windows DHCP with some options set.

So if you want more information let me know. 

Thats from the iPXE Menu. 
:my.thinstation
        initrd http://172.26.51.2/pxe/iso/thinstation.iso
        chain http://172.26.51.2/pxe/memdisk iso raw || goto MENU
        goto MENU

Special configs for the TS clients we are generating from DB to the iPXE server.
No local config

**Comment by versus2** [comment]
> That could be the volume label. You might need to adjust your mount definitions. Make MOUNT_0 look like
> MOUNT_0="LABEL=THINSTATION /boot auto x-mount.mkdir,defaults 0 0"
> Then when Rufus mangles the ISO label from ThinStation to THINSTATION, you should be good.

Great. You've helped me a lot to make it work both from CD and USB stick. 
But been a silly ass,  I wanted to make it a bit faster (slow CD) or not dependent on additional hardware (USB sticks). Therefore I wanted it to boot from internal HD. Was also looking for automated solution (not manually extracting and copying files to partitions and making them bootable. I seemed to have found a perfect solution in EasyBCD (Rufus won't burn to internal HD) which allows to add ISO image as boot option which it then boots either from disk or memory (two options). Booting from HD was considerably faster   But ,alas, I was hit again by dreaded /lib is not a mountpoint. The same image works perfectly from both USB and CD. Any ideas what should I change in configs to make it work on HD? 

Wouldn't it be ideal if you could produce also a VM image from build that could be easily transferred to internal HD.

**Comment by Thinstation** [comment]
You can use dd to write an iso to hd.

**Comment by versus2** [comment]
So if I wanted to write thinstation.iso to station’s HD I would boot some  Linux Live CD and issue what commands?
Is dd part of the standard content?
Can it be done with anything else Windows wise in WinPE? I have some lovely WinPE 10 stick by Sergei Strelec with plenty of utilities.
I am more familiar with Windows environment.

**Comment by Doncuppjr** [comment]
dd is a standard unix utility. You could make a bootable USB drive, and boot from it on the machine you want to install to HD. 
If the HD is dectected as sda, and the USB drive is sdb, then do
dd if=/dev/sdb of=/dev/sda bs=1M, when it finishes, remove USB and reboot.






On Tuesday, December 15, 2020, 03:13:43 PM PST, versus2 <notifications@github.com> wrote: 






So if I wanted to write thinstation.iso to station’s HD I would boot some Linux Live CD and issue what commands?
Is dd part of the standard content?
Can it be done with anything else Windows wise in WinPE? I have some lovely WinPE 10 stick by Sergei Strelec with plenty of utilities.
I am more familiar with Windows environment.

**Comment by versus2** [comment]
You mean I could use thinstation itself to both boot to linux and have dd available and then copy itself to staion’s HD?
Sounds pretty simple. Wil get back to you if it works.

**Comment by versus2** [comment]
Some wierd command this dd. While copying terminal  window was full of scrolling garbage than it stopped but didn't give back any result.  Will check if anything was copied at all.

Nothing got copied. I have windows xp partition on sda (sda1)

I got the commands wrong. Typed "if" instead of "of" in the second part of the command line

EDIT: Now I have a blinking cursor at boot. Obviously some boot code is missing. Any chance of cloned USB booting from HD?

**Comment by Thinstation** [comment]
That's what the dd command does. Is this BIOS or EFI booting?

**Comment by versus2** [comment]
EFI with legacy MBR support. (I’ve used thinstation-efi.iso)
Finally  (by issuing the proper commands which I didn’t do on the first run and hence the garbled screen) I managed to clone the USB stick to HD but it won’t boot (flashing cursor only)
I see a proper size partition on HD but it gets stuck on booting sequence.
Should I try with Clonezilla Live CD? Better to clone iSO or physical USB?

**Comment by Thinstation** [comment]
Try this script. You might need to clear the head and tail of the target drive before doing the dd. You could also maybe set the drive up as MBR only.

device=$1
disk_size=`blockdev --getsz $device`
dd if=/dev/zero of=$device bs=1M count=2
dd if=/dev/zero of=$device bs=512 count=32 seek=$(($disk_size - 32))

**Comment by versus2** [comment]
> Try this script. You might need to clear the head and tail of the target drive before doing the dd. You could also maybe set the drive up as MBR only.
> 
> device=$1
> disk_size=`blockdev --getsz $device`
> dd if=/dev/zero of=$device bs=1M count=2
> dd if=/dev/zero of=$device bs=512 count=32 seek=$(($disk_size - 32))

My bad. After cloning I would pull out CD and USB and seeing cursor blinking i would assume that HD fails to boot.
Once I left USB in and cursor was still blinking and I asked myself what is now wrong with USB as it was booting OK previously.
Then I found out, pressing a boot menu, that there are 2 options for the SAME device and when UEFI was selected USB won't boot. Then it dawned on me. When I selected legacy boot from HD....VOILA it boots perfectčy to GUI. NO ERRORS.
Fine. 
As a last step I would like to get rid of a TFTP server that stores network client configs. I would like to have those integrated on the stick and have different  RDP configs loading from HD. What should i copy where from TFTP server to have everything on HD.?

Thanks for the help

**Comment by Thinstation** [comment]
Use the solution that got you to booted, but complained about /lib not being a mount point. go to /boot/syslinux or /boot/isolinux, and change the .cfg file contents replacing LM=4 with LM=2, save and reboot

**Comment by versus2** [comment]
Once I figured out why blinking cursor appears (UEFI boot instead of legacy selected) everything is fine with cloned version, booting all the way to the GUI. 
Booted and read the config files from network OK. 
Now I just want to get rid of the TFTP server and inculde each stations specific settings on the HD. How do I achieve this?

**Comment by Thinstation** [comment]
on the partition that gets mounted at /boot, create a directory called thinstation.profile, and put a thinstation.conf.user file in that directory. In your thinstation.conf.build, add STORAGE_CONFIG1=/boot

**Comment by versus2** [comment]
Thank you very much . You have been extremely helpful and patient.
