### ISSUE TITLE
DevStation - Internet Connectivity Test Failed for https

### ISSUE THREAD

**Issue by An-dre-as** [Thinstation/thinstation#614]
First of all I want to congratulate you for the excellent DevStation tool.

But I'm having difficulty installing with TS-6.2.6-Installer-0803.iso, my internet connection is working normal, but the messages appear as attached.

![image](https://user-images.githubusercontent.com/75777479/101736531-db776200-3ac3-11eb-976c-3bcd1cfb2a56.png)

I put check_certificate=off into ~/.wgetrc and then I have tried in a terminal session:
A) wget -t 3 -T 30 http://sourceforge.net/projects/thinstation/files/DevStation-Source/image.md5 --> successful
B) wget -t 3 -T 30 https://sourceforge.net/projects/thinstation/files/DevStation-Source/image.md5 --> successful
C)  wget -t 2 -T 10 https://www.ssllabs.com/ssltest/viewMyClient.html --> NOT successful, run into a time out

![image](https://user-images.githubusercontent.com/75777479/101737385-13cb7000-3ac5-11eb-9f26-00cc520dbf6a.png)

Would you help me?

Thank you so much.

**Comment by Thinstation** [comment]
you can comment out line 146 of bin/install.sh and line 414 of
bin/installer, then launch the installer again.

**Comment by Thinstation** [comment]
or update line 54 of /bin/proxy-setup with the larger timeout.

**Comment by theoestor** [comment]
I have a similar issue but I'm getting the error:
```
**Connecting to clienttest.ssllabs.com|64.41.200.100|:8443... connected
Unable to establish SSL connection**
```

But I can't edit the files you mentioned above, because of the error:
`**'/bin/installer' Read-only file system**`

I've tried running as root but still get the same error.
And also tried chmod 744 /bin/ - But this gives me
`chmod: /bin/ Read-only file system`

Many thanks for the help :+1:

**Comment by Doncuppjr** [comment]
I'll release a new build tonight with the longer timeout.

**Comment by Thinstation** [comment]
Try the latest installer. https://sourceforge.net/projects/thinstation/files/latest/download
