### ISSUE TITLE
DevStation failing to install

### ISSUE THREAD

**Issue by UTSBen** [Thinstation/thinstation#618]
I'm trying to install the DevStation onto a physical machine. While installing from USB it hangs at "mount: /thinstation: mount point does not exist." 

If I close the terminal window I get an error of "/boot/boot/lib.update: Missing"

Any thoughts?
Thanks.

**Comment by Thinstation** [comment]
Interesting. I'm working on the installer now, I'll try and sort that one out. Try writing the installer image in dd mode.

**Comment by UTSBen** [comment]
Now it's not even making it to the OS.

"/lib is not a mountpoint
Fastboot was enabled, but something went wrong with the transfer or mount."
...
"syslinux: /boot was not mounted, maybe check your mount declarations.

Dropping to shell."

**Comment by Thinstation** [comment]
Thanks for reporting. I’ll release a new installer on the first.

**Comment by Thinstation** [comment]
Do you have multiple volumes inserted that have the label THINSTATION already?

**Comment by Doncuppjr** [comment]
Here is a beta....
https://sourceforge.net/projects/thinstation/files/thinstation/thinstation-6/TS-6.2.7-Installer-1230.iso/download

**Comment by UTSBen** [comment]
I do not have multiple volumes inserted. Is there a preferred method of formatting I should try on the drive I'm installing to?

Beta downloaded. Will test sometime this morning. Thanks!

**Comment by Thinstation** [comment]
Nothing special about the format. I think I worked it out.

**Comment by UTSBen** [comment]
Just burned and tested. It's working perfectly!

Thanks a lot!
I really appreciate your quick responses.
