### ISSUE TITLE
USB Autoconnect Issue

### ISSUE THREAD

**Issue by mcsn747** [Thinstation/thinstation#619]
Hi,
We tested USB Device Redirection from various VMware Horizon clients in several Thinstation builds.
1. Thinstation 6.1 + Horizon Client 4.10 = autoconnect at startup OK, autoconnect on insert OK
2. Thinstation 6.1 + Horizon Client 5.5 = autoconnect at startup OK, autoconnect on insert FAIL ("USB device already shared")
3. Thinstation 6.2.7 + Horizon Client 5.5 = autoconnect at startup OK, autoconnect on insert FAIL ("USB device already shared")
4. Thinstation 6.2.7 + Horizon Client 2006 = autoconnect at startup OK, autoconnect on insert FAIL ("USB device already shared")
In addition we tested USB Redirection on Debian 10.3 with Horizon Client 5.5 - autoconnect work fine.

**Comment by Doncuppjr** [comment]
What usb device are you trying to share?

**Comment by Thinstation** [comment]
Can you provide more details about your complete testing pipeline? What recipe did you use to build thinstation? What device are you trying to share?

**Comment by mcsn747** [comment]
> What usb device are you trying to share?

USB stick. I used two sticks for testing: USB 2.0 Silicon Motion 2 Gb with FAT file system and USB 3.0 Kingston 16 Gb with NTFS, with the same result.
When I boot Thinstation with USB stick plugged in, 'Autoconnect on startup' option works fine, stick is accessible from guest (Windows 7). If I unplug stick and plug it again, or boot Thinstation with USB unplugged, 'Autoconnect on insert' option doesn't work. Thinstation mounts stick in /mnt/storage/sda1 correctly, but Horizon Client cannot redirect it to guest, with 'Already shared' state in 'Connect USB Device' menu.

**Comment by mcsn747** [comment]
USBArb logs:
[ts6.1_hc4.10_vmware-usbarb-5155.log](https://github.com/Thinstation/thinstation/files/5753274/ts6.1_hc4.10_vmware-usbarb-5155.log)
[ts6.2.7_hc5.5_vmware-usbarb-6675.log](https://github.com/Thinstation/thinstation/files/5753275/ts6.2.7_hc5.5_vmware-usbarb-6675.log)
[lin4.19.0_hc5.5_vmware-usbarb-24270.log](https://github.com/Thinstation/thinstation/files/5753279/lin4.19.0_hc5.5_vmware-usbarb-24270.log)

Thinstation build config files:
[build.conf.example.txt](https://github.com/Thinstation/thinstation/files/5753284/build.conf.example.txt)
[thinstation.conf.buildtime.3.txt](https://github.com/Thinstation/thinstation/files/5753527/thinstation.conf.buildtime.3.txt)
[view-preferences.txt](https://github.com/Thinstation/thinstation/files/5753513/view-preferences.txt)

**Comment by Doncuppjr** [comment]
I would say, disable automount if you want to share usb drives with a remote host, at least for a test.

**Comment by mcsn747** [comment]
> I would say, disable automount if you want to share usb drives with a remote host, at least for a test.

The automount package is disabled.

**Comment by mcsn747** [comment]
The automount package is disabled in build.conf for a test.
Now the USB drive is connected to the remote host by checking it manually in the "connecting USB devices" section. But I need autoconnect without any manual actions.

**Comment by mcsn747** [comment]
Hi,
we solved the issue. This is a situation of misunderstanding.
First, the autoconnect package is disabled.
Second, we added view.shareRemovableStorage="FALSE" option in view-preferences file. We found it in the configuration on a Debian PC.
