### ISSUE TITLE
Intel NUC can't boot UEFI

### ISSUE THREAD

**Issue by maa7** [Thinstation/thinstation#621]
I already wrote about it: https://github.com/Thinstation/thinstation/issues/586
but the topic was closed for unknown reasons.
issue still present on 6.2.9.

**Comment by Thinstation** [comment]
It was closed, because a separate kernel was provided for June Canyon NUC's. You can use it in your build by appending --kernel JC to your build command.

**Comment by Doncuppjr** [comment]
I changed a kernel option that should allow the June Canyon NUC's to boot. zero on free by default will not work on that machine.
