### ISSUE TITLE
DevStation start always slowly with a scan of the disk

### ISSUE THREAD

**Issue by Ivanof-Kouglof** [Thinstation/thinstation#623]
Hello everybody.

I have downloaded the last version of DevStation (TS-6.2.9-Installer-0111.iso).
On two machines I have the exact same problem :
- I did not encounter any problem during the installation. 
- At each start, the boot is slow and there is a hard disk check

DevStation runs on a classic Intel motherboard (DQ67SW) and a 320 Gb hard drive. With version 6.1.1 of Thinstation on the same machine, I don't have this problem...

See below

![image](https://user-images.githubusercontent.com/77665399/105012484-7e65b900-5a3e-11eb-8924-cbb75541ae49.png)

**Comment by Thinstation** [comment]
Anything in the log about fsck?

**Comment by Thinstation** [comment]
That’s grub. Maybe you have a bad drive. Try zeroing it out, then
re-install.

**Comment by Doncuppjr** [comment]
Do you get a graphical menu?

**Comment by Doncuppjr** [comment]
I think I know whats up.

**Comment by Doncuppjr** [comment]
It's not scanning, but rather loading the kernel and initrd. I just had a debug flag set, and I forget to unset it.

**Comment by Doncuppjr** [comment]
New installer posted.

**Comment by Ivanof-Kouglof** [comment]
Thank's
Dat work
