### ISSUE TITLE
Non-root user dmidecode fail

### ISSUE THREAD

**Issue by lesync** [Thinstation/thinstation#627]
dmidecode command fail with error message:

> /sys/firmware/dmi/tables/smbios_entry_point: Permission denied

Build 6.2.9, logged as non-root tsuser.
smbios_entry_point permissions:

>  -r--------    1 root     root            31 Feb  2 09:18 smbios_entry_point

But in 6.2.7 dmidecode runs ok with tsuser rights and with the same build.conf content.
And smbios_entry_point permissions are:

> -r--r--r--    1 root     root            31 Feb  2 10:39 smbios_entry_point

If I log in as root in 6.2.9 and run chmod 444 -R /sys/firmware/dmi/tables, and run dmidecode as tsuser - it works OK

**Comment by Doncuppjr** [comment]
Sound like a kernel change.

**Comment by lesync** [comment]
6.2.7 kernel 5.4.83
![6 2 7_kernel_5 4 83](https://user-images.githubusercontent.com/74227779/106743949-d99fca00-6640-11eb-9595-823194dd3f4a.JPG)

6.2.8 kernel 5.4.86
![6 2 8_kernel_5 4 86](https://user-images.githubusercontent.com/74227779/106743951-da386080-6640-11eb-96da-c9b56450068a.JPG)

6.2.9 kernel 5.4.86
![6 2 9_kernel_5 4 86](https://user-images.githubusercontent.com/74227779/106743953-dad0f700-6640-11eb-9287-c3df4c406598.JPG)


> Sound like a kernel change.

**Comment by Doncuppjr** [comment]
You could write a service file that runs dmidecode during startup. There is a kernel security option that is now enabled that restricts access to several kernel structures for non-root users.

**Comment by lesync** [comment]
> You could write a service file that runs dmidecode during startup.

dmidecode runs periodically by Lansweeper's sheduled monitoring job.

> There is a kernel security option that is now enabled that restricts access to several kernel structures for non-root users.

How can I automatically execute commands (e.g. chmod) after boot?

**Comment by Doncuppjr** [comment]
You can write systemd service files. They can execute individual commands, or you could start a script for any and all custom commands.

**Comment by lesync** [comment]
I had solved the problem by enabling _package autoruns_ in **build.conf** file.

Line in **thinstation.conf.buildtime**:

`AUTORUNS_RC5_0="chmod -R u=rwX,go=rX /sys/firmware/dmi/tables/"`
