### ISSUE TITLE
Horizon SSL Chek

### ISSUE THREAD

**Issue by DoctorDeatch** [Thinstation/thinstation#629]
Hello friends Tell me how to disable certificate checking in the Horizon client?

**Comment by Doncuppjr** [comment]
You would be better off following the instructions to install the certificate.

**Comment by DoctorDeatch** [comment]
The question is precisely in disabling the verification, since these machines are prohibited from going out to the Internet and they cannot check the validity of any certificates in the print chain

**Comment by Thinstation** [comment]
Tha'ts not how PKI works.

If you install the issuing CA public key in the CA Key Store, they will not
go out to the internet.

**Comment by DoctorDeatch** [comment]
Send instructions on how to do this?

**Comment by Thinstation** [comment]
They are in the WIKI

**Comment by DoctorDeatch** [comment]
I tried this instruction, it still swears at a certificate error

**Comment by DoctorDeatch** [comment]
VMVIEW_SSLVERIFYMODE=3 - disables checking SSL
