### ISSUE TITLE
gst-plugins-base-compat error compile /ts/ports/relegated/gst-plugins-base-compat/

### ISSUE THREAD

**Issue by awsswa** [Thinstation/thinstation#634]
/ts/ports/relegated/gst-plugins-base-compat/
version
gstreamer-0.10.36.tar.xz

**Comment by Doncuppjr** [comment]
Relegated ports are not supported, they are only there for reference.

**Comment by awsswa** [comment]
dependencies vmware vmview

file /vmview/dependencies
change
#gst-compat
gstreamer

file /vmview/build/install
change
from **gst-plugins-base-compat** to **gst-plugins-base**
from gst-compat to gstreamer

build vmview

**Comment by Doncuppjr** [comment]
Fair enough.
