### ISSUE TITLE
How to put the desired icon on the desktop, can you give me specific instructions

### ISSUE THREAD

**Issue by vmcitrix** [Thinstation/thinstation#637]
How to put the desired icon on the desktop, can you give me specific instructions，thank you.

**Comment by Doncuppjr** [comment]
What kind of icon are you trying to put on the desktop?

**Comment by vmcitrix** [comment]
Plan to put the printer control panel on the desktop, buid.conf Which parameter needs to be enabled

**Comment by Doncuppjr** [comment]
edit packages/system-config-printer/build/extra/lib/menu/system-config-printer, and remove nodesktop="true";

**Comment by vmcitrix** [comment]
![111111111](https://user-images.githubusercontent.com/48155419/114860230-51972700-9e1e-11eb-97ef-a0dd5cc7da0b.jpg)
Can you give me the configuration file
I'm not sure how to configure the system config printer file. Can you explain it in detail? I'm already here build.conf Package printer is added to the file, but it has no effect

**Comment by Thinstation** [comment]
run
update -c system-config-printer
update system-config-printer
then rerun your build

**Comment by vmcitrix** [comment]
The command has been executed, but there is no system config printer after compilation. What else do you need to do
