### ISSUE TITLE
Citrix Receiver Package Dependency 

### ISSUE THREAD

**Issue by NoMoreFood** [Thinstation/thinstation#638]
Before I sink too much time into figuring this out, I was hoping somebody might be able to tell me how to get the "glib-networking" package included?  Certain functionality in the Citrix Receiver requires this package in order to operate properly (or at least it claims so when manually launching it via command line) and trying to connect to a workspace:

`Loading of page failed with error :TLS/SSL support not available; install glib-networking`

**Comment by Doncuppjr** [comment]
I might have broken something with a recent update. :|

**Comment by Doncuppjr** [comment]
glib-networking is basic and almost always included. I wonder if you got a bad checkout.

**Comment by NoMoreFood** [comment]
Okay, I think you were correct.  Did a fresh build, enabled the minimum to do my test, and things are getting further.  However, now I'm seeing a FIPS related error from Receiver (note: backend Citrix gateway is FIPS enabled).  I tried the same version of the Citrix Receiver on Ubuntu and it works fine.  Any thoughts on why Thinstation might be trying to negotiate using SHA-1?

![image](https://user-images.githubusercontent.com/12881023/114812118-6374bd80-9d7d-11eb-867f-0f27393a24ba.png)

**Comment by Doncuppjr** [comment]
So the standard policies have blackballed sha1.  You might be able to re-enable sha1 by editing or deleting /build/packages/base/etc/crypto-policies/DEFAULT/back-ends/gnutls.config , but that is considered insecure. FIPS is even more restrictive.

**Comment by Doncuppjr** [comment]
Possibly might have to edit /ts/ports/opt/gnutls/Pkgfile and remove the fips option, then run prt-get update -fr gnutls, clean_chroot, setup-chroot

**Comment by Doncuppjr** [comment]
This could also be the cert of the server. Might just get the text of that and see what hash algo it uses.

**Comment by NoMoreFood** [comment]
Thanks for the quick replies.  I still have a problem with getting it to work properly (still getting a TLS error despite copying cacerts from a working system and verifying all certs have a sig alg of SHA256), but have determined with your help and by comparison to Ubuntu that the aforementioned issues are not causal.  I'll close this out while I explore more.  Thanks!

**Comment by Doncuppjr** [comment]
I would check the certs on any servers gateways and proxies that might be in the loop.

**Comment by NoMoreFood** [comment]
Alright; I think I may have found my issue.  Given that we are leveraging the p11 trust store in gnutls compilation params, shouldn't it automatically include the p11-kit package?  I'm going to rebuild from scratch to be sure, but I think this is what finally got it working for me.  In my case, I just manually added the p11-kit package.

**Comment by Doncuppjr** [comment]
interesting.

**Comment by Doncuppjr** [comment]
Some recent security updates have attempted to prohibit the use of sha1. This has a lot of implications, and what I think is actually happening here, is that gnutls and nss are much more rigid than before. p11-kit is providing a fallback/backchannel for doing sha1 in your case. I've recently reenabled sha1(mixed feelings), so you may not need p11-kit anymore.
