### ISSUE TITLE
TFTP root path - fault?

### ISSUE THREAD

**Issue by RadioSTech** [Thinstation/thinstation#640]
Dear Developers.

Have installed the latest iso TS-6.2.9-Installer-0120.iso with default values.
Trying to use the PXE functionality, but is seems like the tftp root in the image is pointing into wrong folder?

Looks like tftproot is: **/ts/build/boot-images/systemd-boot-iso/efi-source**
but all pxe files are in the following folder: **/ts/build/boot-images/pxe**

In short - when tftp into the server I can reach all the Efi-source files, but not the pxe files...

Do I need to copy all the pxe files manually to the systems-boot-iso folder, or should the fttpserver have pointed to the pxe folder?

Thanks in advance.

**Comment by Thinstation** [comment]
Are you booting legacy bios systems, or EFI?

**Comment by RadioSTech** [comment]
Legacy bios system on the test I have done so far.

**Comment by Doncuppjr** [comment]
Those have not been manufactured in over a decade. If your hardware is even close to modern, you probably want EFI.

**Comment by RadioSTech** [comment]
Will try EFI on another machine.

But is the tftp folder on the server different between EFI and Legacy bios?

Checked one of the video on YouTube (Getting started - https://www.youtube.com/watch?v=9R5eKjE618s) and when you opened chrome to view the pxe folder you got the files from the PXE folder. I'm getting a different folder. (something like /ts/build/boot-images/systemd-boot-iso/efi-source)

**Comment by Thinstation** [comment]
It can be. Syslinux.EFI would work in the legacy folder for EFI systems,
but the syslinux project is dead and deprecated. Grub also handles both.
Systemd would only do EFI.

**Comment by Doncuppjr** [comment]
Yes, I've updated the paths internally for grub, but I haven't updated the video. Tech Debt.

**Comment by Doncuppjr** [comment]
I changed the root path back to syslinux.
