### ISSUE TITLE
NX package won't install (not in gzip format)

### ISSUE THREAD

**Issue by aknisly** [Thinstation/thinstation#644]
I am having the same issue that was reported [here](https://github.com/Thinstation/thinstation/issues/570), but I'm having trouble forming the URL correctly. The [download button](https://www.nomachine.com/download/download&id=9) at NoMachine pulls up a javascript window without giving me a link I can copy. My attempts at guessing the link format based on the build script output haven't been successful. Any ideas?

Or is there a way I can download the package and manually drop it in the right location for the build process? 

Thanks much for your help.

----

_INSTALLING NX
NX is not installed, we need to setup binary file.
This only needs to be done once.

Continue? (Y/N)
y

Downloading from Net.....
Using system proxy, or not using any proxy to connect to Internet.
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2021-06-02 02:06:31--  https://download.nomachine.com/download/6.11/Linux/nomachine-enterprise-client_6.11.2_1_x86_64.tar.gz
Resolving download.nomachine.com... 83.222.232.25
Connecting to download.nomachine.com|83.222.232.25|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://www.nomachine.com [following]
--2021-06-02 02:06:32--  https://www.nomachine.com/
Resolving www.nomachine.com... 80.92.83.99, 80.92.83.101, 80.92.83.98
Connecting to www.nomachine.com|80.92.83.99|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: './wget_tmp/nomachine-enterprise-client_6.11.2_1_x86_64.tar.gz'

./wget_tmp/nomachine     [  <=>                  ] 142.86K   285KB/s    in 0.5s    

2021-06-02 02:06:34 (285 KB/s) - './wget_tmp/nomachine-enterprise-client_6.11.2_1_x86_64.tar.gz' saved [146288]

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
/ts/build/packages/nx/build/install: line 10: wget_tmp/NX/nxclient: No such file or directory

Error has occured while installing package nx
Build Aborted_

**Comment by Doncuppjr** [comment]
You can place it in /downloads


Sent from Yahoo Mail for iPhone


On Wednesday, June 2, 2021, 5:03 AM, aknisly ***@***.***> wrote:




I am having the same issue that was reported here, but I'm having trouble forming the URL correctly. The download button at NoMachine pulls up a javascript window without giving me a link I can copy. My attempts at guessing the link format based on the build script output haven't been successful. Any ideas?

Or is there a way I can download the package and manually drop it in the right location for the build process?

Thanks much for your help.

_INSTALLING NX
NX is not installed, we need to setup binary file.
This only needs to be done once.

Continue? (Y/N)
y

Downloading from Net.....
Using system proxy, or not using any proxy to connect to Internet.
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2021-06-02 02:06:31-- https://download.nomachine.com/download/6.11/Linux/nomachine-enterprise-client_6.11.2_1_x86_64.tar.gz
Resolving download.nomachine.com... 83.222.232.25
Connecting to download.nomachine.com|83.222.232.25|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://www.nomachine.com [following]
--2021-06-02 02:06:32-- https://www.nomachine.com/
Resolving www.nomachine.com... 80.92.83.99, 80.92.83.101, 80.92.83.98
Connecting to www.nomachine.com|80.92.83.99|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: './wget_tmp/nomachine-enterprise-client_6.11.2_1_x86_64.tar.gz'

./wget_tmp/nomachine [ <=> ] 142.86K 285KB/s in 0.5s

2021-06-02 02:06:34 (285 KB/s) - './wget_tmp/nomachine-enterprise-client_6.11.2_1_x86_64.tar.gz' saved [146288]

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
/ts/build/packages/nx/build/install: line 10: wget_tmp/NX/nxclient: No such file or directory

Error has occured while installing package nx
Build Aborted_

**Comment by aknisly** [comment]
Thanks for the speedy reply! After a little trial-and-error, I got this to work. I documented my steps [here](https://github.com/Thinstation/thinstation/wiki/Building-ThinStation-for-booting-off-SSD-(Goal:-NoMachine-Thin-Clients)#nomachine-package-wont-install). I'm satisfied with handling it this way, but if there is an easier way, I'd be happy to include that in my notes.

I'm very grateful for your excellent work on TS!

**Comment by Doncuppjr** [comment]
Nice! Ty for the contribution. You can change the name of the file in /build/build.urls.

**Comment by aknisly** [comment]
OK, I'll make a note of it, but since I'm still not figuring out how to get the URL to the download, I think it's just as easy to rename the downloaded file to match the name in build.urls.

Thanks again! I'll be donating to the cause soon. I can't help much, but I really want to see this project thrive.
