### ISSUE TITLE
Firmware not found when building --allmodules

### ISSUE THREAD

**Issue by orioldelos** [Thinstation/thinstation#645]
I am trying to build a LiveUSB that should be able to recognize as much different hardware as possible. For that I tried using the LiveCDISO build.conf and thinstation.conf.buildtime , but when I try building with --allmodules I start getting messages like the following and the ISO created does not recognize the hardware that the original downloaded live ISO does.

-------8<-------8<-------
Firmware: /lib/firmware/nvidia/gm206/acr/ucode_load.bin
Firmware: /lib/firmware/radeon/JUNIPER_pfp.bin
Firmware: /lib/firmware/i915/icl_huc_9.0.0.bin
Firmware: /lib/firmware/amdgpu/hawaii_pfp.bin
	**Notice, Firmware nvidia/gm206/acr/bl.bin not found
	Notice, Firmware nvidia/gm204/acr/ucode_load.bin not found
	Notice, Firmware nvidia/gm204/acr/bl.bin not found**
Firmware: /lib/firmware/nvidia/gm200/acr/ucode_load.bin
Firmware: /lib/firmware/i915/icl_guc_33.0.0.bin
Firmware: /lib/firmware/radeon/REDWOOD_smc.bin
Firmware: /lib/firmware/amdgpu/bonaire_mec.bin
Firmware: /lib/firmware/amdgpu/bonaire_rlc.bin
Firmware: /lib/firmware/i915/ehl_huc_9.0.0.bin
Firmware: /lib/firmware/radeon/REDWOOD_rlc.bin
Firmware: /lib/firmware/nvidia/gm200/acr/bl.bin
Firmware: /lib/firmware/amdgpu/bonaire_ce.bin
Adding extra module firmware for ast.ko
	**Notice, Firmware ast_dp501_fw.bin not found**
Firmware: /lib/firmware/radeon/REDWOOD_me.bin
Firmware: /lib/firmware/nvidia/gp100/acr/ucode_unload.bin
Firmware: /lib/firmware/i915/ehl_guc_33.0.4.bin
Firmware: /lib/firmware/amdgpu/bonaire_me.bin
Firmware: /lib/firmware/radeon/REDWOOD_pfp.bin
Firmware: /lib/firmware/nvidia/gm206/acr/ucode_unload.bin
Firmware: /lib/firmware/i915/tgl_huc_7.5.0.bin
	**Notice, Firmware nvidia/gm204/acr/ucode_unload.bin not found**
-------8<-------8<-------

How can I make sure my DevStation hass all available firmware?
The only reason I can think of why the firmware is not available in the DevStation is that when I installed it, at some point it kept trying unsuccessfully to connect to some *Mike* url.
Thanks

**Comment by Doncuppjr** [comment]
prt-get install -fr /ts/ports/binary-core/*

If your hardware support issue is related to missing firmware, you should see some messages in the journal. As root, journalctl -xe |grep -ie firmware

**Comment by Doncuppjr** [comment]
As an aside, a lot of modules say the depend on firmwares, when they don't really need them.

**Comment by orioldelos** [comment]
I get the following when executing "prt-get install -fr /ts/ports/binary-core/*"

-----8<-----------------8<-----------
-- Packages not found
/ts/ports/binary-core/README
/ts/ports/binary-core/edk2
/ts/ports/binary-core/firmware
/ts/ports/binary-core/firmware-alsa
/ts/ports/binary-core/firmware-ap6214a
/ts/ports/binary-core/firmware-atmel
/ts/ports/binary-core/firmware-b43
/ts/ports/binary-core/firmware-ipw
/ts/ports/binary-core/firmware-libertas
/ts/ports/binary-core/firmware-p54
/ts/ports/binary-core/firmware-zd1211
/ts/ports/binary-core/intel-microcode
/ts/ports/binary-core/refind-binary
/ts/ports/binary-core/rufus
/ts/ports/binary-core/shim-fedora
/ts/ports/binary-core/wireless-regdb
-----8<-----------------8<-----------

The issue is not simply the fact that I get those messages when building the image, but the fact that if I use the downloaded LiveISO it recognizes all my hardware without any issues, butWhen I try to build it myself, it won't recognize my wifi, webcam, etc.

**Comment by Doncuppjr** [comment]
Hmm yeah, you might need to drop into that dir first.
cd /ts/ports/binary-core/
prt-get install -fr *

You could try adding 
package allfirmware as well as
param allfirmware true. The package is really big though.....Webcams and wifi should work. What kind of cam/wifi? You have device ID's?

**Comment by Doncuppjr** [comment]
There is also a log of firmwares not found per module at /ts/firmware_notfound. Might shed some light on this.

**Comment by orioldelos** [comment]
After dropping into the directory the prt-get did work.

How exactly should I add the package allfirmware and where chould I set the param allfirmware true (In build.conf?)

**Comment by orioldelos** [comment]
I just checkjed and the "param allfirmware true" is already set.

**Comment by Thinstation** [comment]
Yes, in build.conf

**Comment by orioldelos** [comment]
I amstiull getting firmware not foundmessages, but I will try a build with allfirmware package and let you know

Thank you for your help

**Comment by orioldelos** [comment]
Is there any way I can download the files that appear in the /ts/firmwares_notfound?

**Comment by Doncuppjr** [comment]
You will always get such messages. I have collected as many as possible, but sometimes modules optionally take firmware from the module developers that are never released to the public.

**Comment by Doncuppjr** [comment]
You can try and track them down, but I've never needed more than what I collected so far.

**Comment by orioldelos** [comment]
> Hmm yeah, you might need to drop into that dir first.
> cd /ts/ports/binary-core/
> prt-get install -fr *
> 

After executing this, the ISO that is created now recognizes my wifi, camera and microphone without a glitch.

Thank you very much for your help
