### ISSUE TITLE
Disable display LVDS

### ISSUE THREAD

**Issue by ghost** [Thinstation/thinstation#648]
At the start of the session a monitor called laptop (LVDS) is automatically enabled, and I want to disable it so that at the start of rdesktop it does not enlarge the screen

![WhatsApp Image 2021-06-10 at 10 45 07](https://user-images.githubusercontent.com/56385755/121494425-0726c680-c9d9-11eb-8a58-06ca5a3ca685.jpeg)
![WhatsApp Image 2021-06-10 at 10 46 51](https://user-images.githubusercontent.com/56385755/121494634-376e6500-c9d9-11eb-8f5d-fb5a0e496715.jpeg)

**Comment by Thinstation** [comment]
You could use xrander or set a kernel option to disable the output.

**Comment by Thinstation** [comment]
uncomment the line 
param extra_vid      LVDS-1:d
in build.conf
