### ISSUE TITLE
Dev Station Installer issues (how to choose the correct disc)

### ISSUE THREAD

**Issue by ant0nwax** [Thinstation/thinstation#650]
I try to install a ThinStation USB Pendrive

I successfully created a USB Pendrive with DevStation on a 4 GB USB Pendrive

Goal is to install on a 60 GB external SSD Drive (internal SSD is broken)

Steps:
- I connect the Boot Pendrive with 4 GB
- Power On Surface Pro 1. Gen so that it boots DevStation
- connect 60 GB USB Drive, too, during 10 seconds Boot Menu
- DevStation is booting, this works
- In order to get Install to HD to work further than the Internet check i needed to create a file
echo "check_certificates=no" to ~/.wgetrc (workaround should be presented in the Errormessage, or asked to user if this file shall be created think about normal users or consumers and not about admins or developers, i am admin myself)
- Now I cannot chose the USB Drive for the installer, it is just telling me Harddisk is too small, you need at least 30 GB, but i have 60 GB
- I think the installer finds the broken Harddisk of the Surface Pro 1. Gen which shows also in other USB boot ISOs a size of 0 Bytes

Expectiation would be to be able to chose between the 0 Bytes disk and the 60 GB Disk

Does this make sense to anyone?

Thank you and kind regards

**Comment by Thinstation** [comment]
I understand what you are trying to do, but I don't know why. DevStation is component of a network lab. Most people install it into a VM. Why are you using real hardware?

**Comment by ant0nwax** [comment]
Hi, meanwhile I found how to do that.
I installed it on VM too and got a boot iso for usb pendrive for my surface

you may close this topic.

compared to IGEL OS i have to say that from
scratch neither WiFi nor Bluetooth work on my Surface Pro 1 (2013 device)
after setting up the packages and parameters in build.conf

Further there is only OpenVPN on board
i would need to integrate weeks in order to get these things working. 1:0
for IGEL OS, sorry to say.

I think I will try to install a plain ubuntu 20 on a pendrive and see how
that discovers the correct hardware devices.


Kind Regards From Phoneland
