### ISSUE TITLE
Freerdp asking for username

### ISSUE THREAD

**Issue by marierau98** [Thinstation/thinstation#651]
Hello! 
I am trying to create a image for our thinclients with freerdp but freerdp is always asking for a username "you must enter value for Username". Is there a way to connect directly to the terminal server? our users should be entering their username and password via windows login screen.

my current config:

SESSION_0_TITLE="test"
SESSION_0_TYPE=freerdp
SESSION_0_FREERDP_SERVER=IP-ADDRESS
SESSION_0_FREERDP_OPTIONS="/cert-ignore /sec-rdp /u: /p: /d:DOMAIN /bpp:32 /rfx /gfx:AVC444 /sound:sys:pulse +auto-reconnect +heartbeat +fonts"
SESSION_0_CUSTOM_CONFIG=On
SESSION_0_AUTOSTART=On

Thanks!

**Comment by Doncuppjr** [comment]
That's an insecure authentication method. You should make sure your environment supports NLA, and enter the username and password when requested.

**Comment by marierau98** [comment]
but there should be a way to connect to my server without giving him a username beforehand. if iam entering a space it will connect me to my server, but i dont want the freerdp window to open before.

**Comment by Thinstation** [comment]
You are not requiring NLA on your server. That is bad. That is very old and
insecure way of authenticating. You should change your server to require
NLA and enter credentials on the thin client.
