### ISSUE TITLE
Custom boot splash not loading

### ISSUE THREAD

**Issue by marierau98** [Thinstation/thinstation#655]
Hello,
I want to create an Image with a custom boot logo. I´ve already copied the file into "thinstation/build/utils/tools/splash/default" and also into "etc/splash/default" (its in the desired resolution folder) but when Iam trying to boot its still showing the orginal thinstation picture (I´ve renamed my picture into silent aswell). Am I missing any further steps? How can I configure my own picture during boot?

Thanks in advance!

marierau98

**Comment by Thinstation** [comment]
The first time you run build, it will convert the 1024x768 theme into all known resolutions. Subsequent runs will not. If you need to regen all the resolutions, remove all the resolutions besides 1024x768. Place a silent.jpg of 1024x768 in that folder, and run build again. Alternatively, you can use a scalable image. make a folder in the resolutions folder called scalable. Copy the 1024x768.cfg into that folder along with a silent.svg, remove 1024x768 folder,  then run build.

**Comment by marierau98** [comment]
> 
> 
> The first time you run build, it will convert the 1024x768 theme into all known resolutions. Subsequent runs will not. If you need to regen all the resolutions, remove all the resolutions besides 1024x768. Place a silent.jpg of 1024x768 in that folder, and run build again. Alternatively, you can use a scalable image. make a folder in the resolutions folder called scalable. Copy the 1024x768.cfg into that folder along with a silent.svg, remove 1024x768 folder, then run build.

i'm getting a black screen if i proceed as instructed.

**Comment by Thinstation** [comment]
Which instructions? scalable or jpg

**Comment by marierau98** [comment]
The blackscreen appears when i use jpg. When I use scalable Iam seeing the screen where it shows that its loading the thinstation file (no boot image nor progress bar).

**Comment by Thinstation** [comment]
I know the .jpg is a little sensitive. Might try editing the existing one, and pasting the pixels in that you want. Not sure where your going wrong with scalable.

**Comment by Thinstation** [comment]
Actually I think I know what's up with scalable. Before doing the first build, edit the 1024x768.cfg, and change silent.jpg to silent.png

**Comment by Thinstation** [comment]
I've added a scalable theme template. To use it, change boottheme in build.conf to scalable, and replace the silent.svg in build/utils/tools/splash/scalable/scalable/

**Comment by marierau98** [comment]
Iam getting a blackscreen now just like the jpg.
My steps:
1) create "scalable" folder in /thinstation/build/utils/tools/splash
2) change boottheme in build.conf to scalable
3) create "scalable" folder in /thinstation/build/utils/tools/splash/scalable
4) copy silent.svg (I´ve renamed the file beforehand) and 1024x768.cfg (the one with silent.png) into /thinstation/build/utils/tools/splash/scalable/scalable
5) run ./build
6) copy rufus & boot folder to usb drive and boot device

(The resolution folders are deleted except the created scalable) 

Ive also attached the used svg file.

[test picture svg.zip](https://github.com/Thinstation/thinstation/files/6997891/test.picture.svg.zip)

Am I missing out a step or doing one wrong?

**Comment by marierau98** [comment]
Nevermind, I forgot to nename the config from 1024x768.cfg to scalable.cfg. Its working now, thank you for your help!
