### ISSUE TITLE
Generating hardware module list error

### ISSUE THREAD

**Issue by marierau98** [Thinstation/thinstation#656]
Hello,

Iam trying to generate my own module list to reduce the size of my image. Ive uncomment "lshw" and used the default config, when I was booting my device and tried to open lshw I couldnt see anything so I was using the lshw command in my terminal. It didnt generate a module list instead it threw me a error message "std::length_error what(): cannot create std::vector larger than max_size()"
How can I generate a module list and why am I getting the stated error?

Thanks in advance

marierau98

**Comment by Doncuppjr** [comment]
hwlister.sh

**Comment by marierau98** [comment]
> 
> hwlister.sh Sent from Yahoo Mail for iPhone On Monday, August 9, 2021, 5:27 AM, marierau98 ***@***.***> wrote: Hello, Iam trying to generate my own module list to reduce the size of my image. Ive uncomment "lshw" and used the default config, when I was booting my device and tried to open lshw I couldnt see anything so I was using the lshw command in my terminal. It didnt generate a module list instead it threw me a error message "std::length_error what(): cannot create std::vector larger than max_size()" How can I generate a module list and why am I getting the stated error? Thanks in advance marierau98 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android 

If iam doing it on my devstation, I cant see the files on my disk and if Iam doing it on my client I get hwlisterlsh not found. Do I need to run it as sudo on my client? Or what am I doing wrong?

**Comment by Thinstation** [comment]
You need to put
package hwlister
in build.conf
Also make sure you
param allfirmware true
is set, and build with 
--allmodules.

**Comment by marierau98** [comment]
> 
> 
> You need to put
> package hwlister
> in build.conf
> Also make sure you
> param allfirmware true
> is set, and build with
> --allmodules.

Thank you! I was missing the hwlister package and had to delete the tsuser.
