### ISSUE TITLE
intel NUC 7jy

### ISSUE THREAD

**Issue by BulyginDA** [Thinstation/thinstation#659]
How to use the option --kernel JC.
I'm trying to use it in the latest version Devstation. and I get a message kernel JC doesn`t exist. 

which of the assemblies did you add it to for the operation of this platform when loading uefi pxe

**Comment by Doncuppjr** [comment]
The kernel option that required me make a separate kernel config for June Canyon was ascertained.(Zero on Init). I incorporated it into the standard kernel, and you shouldn’t need to use a —kernel JC anymore.
