### ISSUE TITLE
Running ThinStation on a Raspberry Pi

### ISSUE THREAD

**Issue by austinkregel** [Thinstation/thinstation#66]
Hello, I have recently been getting more involved in virtualization and Raspberry Pis. 
I was wondering if anyone has tried running Thinstation on a Raspberry Pi, if so were there any special steps that need to be taken to use Thinstation on it? Or if no one knows if it's been done, do you believe it's possible to be done?

**Comment by ropetry** [comment]
Hi, perhaps this helps more for a rasp 8-)..

http://rpitc.blogspot.de/


looks goot, but lags a little bitt he central configuration i think..
bye
roman

Von: Austin [mailto:notifications@github.com]
Gesendet: Donnerstag, 7. Mai 2015 23:34
An: Thinstation/thinstation
Betreff: [thinstation] Running ThinStation on a Raspberry Pi (#66)


Hello, I have recently been getting more involved in virtualization and Raspberry Pis.
I was wondering if anyone has tried running Thinstation on a Raspberry Pi, if so were there any special steps that need to be taken to use Thinstation on it? Or if no one knows if it's been done, do you believe it's possible to be done?
