### ISSUE TITLE
Freerdp server select

### ISSUE THREAD

**Issue by yamcia** [Thinstation/thinstation#661]
I would like to get (after booting) a list of rdp connection. My thinststion.conf.build (part of) looks like this:

###MULTI
SESSION_0_TYPE=freerdp
SESSION_0_TITLE="Server Select"
SESSION_0_AUTOSTART=On
#SESSION_0_ICON=On
SESSION_0_FREERDP_SERVER="DUMMY.COM"
SESSION_0_FREERDP_OPTIONS="DUMMY OPTIONS"
FREERDP_SELECT_SERVER=YES
FREERDP_SERVER_0 = 10.0.1.10
FREERDP_SERVER_0_OPTIONS = " /cert-ignore /multimon /d:www /smartcard /usb:auto"
FREERDP_SERVER_1 = 10.0.1.11
FREERDP_SERVER_1_OPTIONS = " /cert-ignore /multimon /d:www /smartcard /usb:auto"

Unfortunately it doesn't work. After booting I receive a xdialog man page.
What is wrong with it?

**Comment by Thinstation** [comment]
You don't need SESSION_0_FREERDP_SERVER or _OPTIONS.
The FREERDP_SERVER_0 and _1, need to have a numerical tag starting at 1 along with the IP or DNS name. It's a little un-intuitive, as the SERVER index starts at 0, and the tag index starts at 1. 'IP' might need some single tick inner quotes. In the example you can see it looks like this.
FREERDP_SERVER_0="1 Big_Bad_Server_Donald"
FREERDP_SERVER_0_OPTIONS="-sec-nla /d:thinstation.local"
FREERDP_SERVER_1="2 Big_Bad_Server_Road_Runner"
FREERDP_SERVER_1_OPTIONS="-sec-nla /cert-ignore /d:thinstation.local"

**Comment by yamcia** [comment]
I did as you suggested. Now I receive a list of servers but I can't connect to any. After choosing one of those I get fields to put my cridentials (an user name and a password). After pressing "Connect" a prompt with reconnection appears. Single connection works very well. Is any log to verify connections?

**Comment by Thinstation** [comment]
Sorry, not really my code. I updated it a little bit. Got rid of those silly tags. Try the latest commit.

**Comment by yamcia** [comment]
Unfortunately the changes haven't helped. I receive a prompt with reconnection option. Is there any option to log this operation?

**Comment by Thinstation** [comment]
Drop the index tag.

You could add set -x to etc/cmd/freerdp.options, then call pkg window
freerdp from command line

**Comment by yamcia** [comment]
See nothing :( at least nothing I could understand. May be select_server option is not working any more

**Comment by Thinstation** [comment]
It works for me. I have updated the example documentation.

**Comment by yamcia** [comment]
I can't find it

**Comment by Thinstation** [comment]
https://github.com/Thinstation/thinstation/blob/6.2-Stable/ts/build/packages/freerdp/build/conf/50freerdp

**Comment by yamcia** [comment]
Thanks, I will keep struggling may problems :)
