### ISSUE TITLE
Unable to add CA Certificate to ICA client

### ISSUE THREAD

**Issue by orioldelos** [Thinstation/thinstation#667]
Hi, I have been trying for a while to add a CA certificate to the ICA client but I can't figure out how.

What I have done so far is the following:

- First I tested the process in an ubuntu system, just to make sure the certificate I was trying to use was the correct one. It worked fine in ubuntu by following this instruction:
   
- [ ]    Download CA certificate in PEM format. 
- [ ]    Save the certificate with .crt file extension. 
- [ ]    Switch to root user and copy the .crt CA certificate file to /opt/Citrix/ICAClient/keystore/cacerts/ folder. 
- [ ]    Make sure the CA certificate file is owned by Root user and Group, and it has -rw-r--r-- or 644 as the File permissions. 
- [ ]    Run  /opt/Citrix/ICAClient/util/ctx_rehash 

My understanding is that in order to install the same certificate into the thinstation ICA client, I simply need to copy that same certificate into the "**/build/packages/ica/opt/Citrix/ICAClient/keystore/cacerts**" directory and then the finalize script will take care of the rehashing when I build the ISO image.

Having done that though, the certificate is still not recognized. When trying to connect I get the error that the go-dady CA authority certificate is not trusted.

Any ideas on what I might be doing wrong?

**Comment by Thinstation** [comment]
Try these instructions.

https://github.com/Thinstation/thinstation/wiki/Certificates

**Comment by orioldelos** [comment]
It worked great. thanks
