### ISSUE TITLE
USB Label & USB Mount Syntax

### ISSUE THREAD

**Issue by marierau98** [Thinstation/thinstation#672]
I wanted to ask if there is a possibility to define a label for usb sticks like a name or a letter. Additionally I wanted to ask if someone can explain me the following syntax from our old configuration:

SESSION_0_FREERDP_OPTIONS="/vc:ftrdpbr /drive:H,/mnt/usbdevice" 
(of course there are more parameters but I dont quite understand what vc and drive do)

**Comment by Thinstation** [comment]
USB_MOUNT_USELABEL="Yes"

/vc means to use a specific channel service. Usually not needed.
/drive tells freerdp to share /mnt/usbdevice as H: on the remote server

**Comment by marierau98** [comment]
Thanks
