### ISSUE TITLE
Freerdp password pass

### ISSUE THREAD

**Issue by LittleITworld** [Thinstation/thinstation#673]
My image was working fine and after some little changes, it didnt connect to my terminal server anymore.
Ive used "SESSION_0_FREERDP_PASS_ENABLE=false" to override password input but now it doesnt work anymore. When I include xfwm4 session it states that a password is required even tho I cant enter it and if I exclude xfwm4 session like it should be later on, it only shows a black screen with the cursor. Is that a bug from freerdp? It doesnt require a username and the value /p: for a blank password is set on options...

edit: nla is disabled

**Comment by Thinstation** [comment]
Try modifying this example.
https://github.com/Thinstation/thinstation/tree/6.2-Stable/ts/build/conf/freerdp

I just checked, and I'm not having any issue with your described scenario.

**Comment by LittleITworld** [comment]
Ive used your example and modified username, password and of course server ip. The result: Iam getting freerdp window with my chosen parameters and when I click on connect it states "You must enter value for password". The password is already set with /p:'password'. I dont understand that sudden behaviour :/

**Comment by Thinstation** [comment]
Delete the .getuser and .getpass from freerdp/etc/cmd

**Comment by LittleITworld** [comment]
Ive deleted both and still same result. Ive also reinstalled my devstation beforehand.

**Comment by Doncuppjr** [comment]
You must be testing an old image or something. Possibly try "no" instead of "false", maybe it's a language thing.






On Friday, September 24, 2021, 03:59:58 AM PDT, LittleITworld ***@***.***> wrote: 







Ive deleted both and still same result. Ive also reinstalled my devstation beforehand.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by marierau98** [comment]
> 
> You must be testing an old image or something. Possibly try "no" instead of "false", maybe it's a language thing. On Friday, September 24, 2021, 03:59:58 AM PDT, LittleITworld ***@***.***> wrote: Ive deleted both and still same result. Ive also reinstalled my devstation beforehand. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

unfortunately thats not the case

**Comment by a1v85** [comment]
> e thing. On Friday, September 24, 2021, 03:59:58 AM PDT, LittleITworld _**@**_.***> wrote: Ive deleted both and still same result.

Hello LittleITworld! 
Could you tell me, how you resolve this problem?

**Comment by LittleITworld** [comment]
> > e thing. On Friday, September 24, 2021, 03:59:58 AM PDT, LittleITworld _**@**_.***> wrote: Ive deleted both and still same result.
> 
> Hello LittleITworld! Could you tell me, how you resolve this problem?

Ive set "SESSION_0_FREERDP_PASS_ENABLE=false and FREERDP_GETUSER=off" in my buildconf and its working fine. I can send you my complete config if that would help you (tomorrow)

**Comment by a1v85** [comment]
> > > e thing. On Friday, September 24, 2021, 03:59:58 AM PDT, LittleITworld _**@**_.***> wrote: Ive deleted both and still same result.
> > 
> > 
> > Hello LittleITworld! Could you tell me, how you resolve this problem?
> 
> Ive set "SESSION_0_FREERDP_PASS_ENABLE=false and FREERDP_GETUSER=off" in my buildconf and its working fine. I can send you my complete config if that would help you (tomorrow)

Will be very pleasefull

**Comment by a1v85** [comment]
> > > e thing. On Friday, September 24, 2021, 03:59:58 AM PDT, LittleITworld _**@**_.***> wrote: Ive deleted both and still same result.
> > 
> > 
> > Hello LittleITworld! Could you tell me, how you resolve this problem?
> 
> Ive set "SESSION_0_FREERDP_PASS_ENABLE=false and FREERDP_GETUSER=off" in my buildconf and its working fine. I can send you my complete config if that would help you (tomorrow)

LittleITworld, I solve problem with your parametres, Thank you very much!

**Comment by LittleITworld** [comment]
[config.zip](https://github.com/Thinstation/thinstation/files/7886867/config.zip)

> LittleITworld, I solve problem with your parametres, Thank you very much!

iam glad to hear it was working for you :)
maybe you can use some other parameters from my config aswell ;)
