### ISSUE TITLE
Issues with TSV info

### ISSUE THREAD

**Issue by jonny190** [Thinstation/thinstation#674]
With the following config the 
SESSION_0_FREERDP_SERVER=connectionbroker.domain.com
SESSION_0_FREERDP_OPTIONS="/cert-ignore +drives /g:gateway.domain.com /d:internal.domain /load-balance-info:"tsv://MS Terminal Services Plugin.1.Team3""
SESSION_0_FREERDP_USER="domain_user"
SESSION_0_FREERDP_PASS_ENABLE=true

ends up with
![vmware_CUyjkh9Qds](https://user-images.githubusercontent.com/8059327/135245999-17889c6d-f9e1-4e14-bbfa-a8c0b90f5e28.png)
:

**Comment by Thinstation** [comment]
Use ' instead of " for the outside quotes.

**Comment by Thinstation** [comment]
Actually, it's better to use ' as the inner quote and " as the outer quote.

**Comment by jonny190** [comment]
> Actually, it's better to use ' as the inner quote and " as the outer quote.

when I try this the booted OS shows /load-balance-info:"/tsv://MS Terminal Services Plugin.1.Team3/" 

then when trying to connect it fails. if i remove the "/"'s leaving /load-balance-info:"tsv://MS Terminal Services Plugin.1.Team3" life is good just means every boot i need to make a manual change.

Any ideas?

**Comment by Thinstation** [comment]
It was a bug. I fixed it. You could swap the quotes around, or get the latest code.

**Comment by jonny190** [comment]
> It was a bug. I fixed it. You could swap the quotes around, or get the latest code.

I've tried swapping the quotes over and the compiled version has the options empty haha

Ive tried  running update devstation and shows no updates available

**Comment by Thinstation** [comment]
Factory reset
