### ISSUE TITLE
Building thinstation gives lots of errors and fails since beginning of May

### ISSUE THREAD

**Issue by jens-maus** [Thinstation/thinstation#68]
Since your latest changes to thinstation building it shows now the following error:

```
[...]
Adding Library Dependencies

perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "POSIX",
	LC_ALL = (unset),
	LC_COLLATE = "POSIX",
	LC_CTYPE = "en_US.UTF-8",
	LC_TIME = "C",
	LANG = "C"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").

[...]

find: `boot-images/pkg-packages/ca-bundle/lib': No such file or directory
rm: missing operand
Try 'rm --help' for more information.
find: `boot-images/pkg-packages/ca-bundle/lib': No such file or directory
find: `boot-images/pkg-packages/ca-bundle/lib': No such file or directory
rm: missing operand
Try 'rm --help' for more information.
find: `boot-images/pkg-packages/ca-bundle/lib': No such file or directory
rm: missing operand
Try 'rm --help' for more information.

[...]

+ Adding splash boot logo

1024x768

Stripping Enabled
	RAM Usage before stripping	251088 KiloBytes
./setup-chroot: line 143: 14263 Segmentation fault      (core dumped) chroot /$PWD /bin/bash --rcfile ./ts/TS_ENV
```

As you can see there seem to be 3 problems:

1. While search/adding library dependencies perl complains about a missing en_US.UTF-8 locale. However, nothing has changed here.
2. we are adding 'ca-bundle' as a pkg here in our conf file and it seems something is not working correctly anymore with that approach
3. When preparing the final images thinstation segfaults now when stripping binaries.

Would be good if these problems could be solved quickly, especially the 3. issue seems to be quite worse.

**Comment by jens-maus** [comment]
I am happy to report that since your latest checkin building thinstation works again. However, there is one last issue showing up:

```
[...]
Making boot image for pxe Type....

sed: -e expression #1, char 28: unterminated `s' command
sed: -e expression #1, char 28: unterminated `s' command
sed: -e expression #1, char 28: unterminated `s' command

Notes about build:
[...]
```

So something is calling sed with an incorrect expression.

**Comment by Thinstation** [comment]
Do you have multiple network adapters?

**Comment by jens-maus** [comment]
yes, actually it is a server with a bunch of network adapters :)

**Comment by Doncuppjr** [comment]
Set param bootserver to the IP address of the prefered adapter in build.conf


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------
