### ISSUE TITLE
hdupdate nvme support

### ISSUE THREAD

**Issue by MeadowBlue** [Thinstation/thinstation#681]
Greetings,
I'm trying to use the hdupdate package but it doesn't seem to support nvme drives. I've tried adding entries in ts/build/packages/hdupdate/etc/init.d/hdupdate before building the image to no avail. Any pointers?

Thanks!

**Comment by Thinstation** [comment]
Hmmm. I have not played with nvme yet. I would guess you need to add something like nvme0n1p to the disk list.

**Comment by MeadowBlue** [comment]
I figured it out. Just had to make sure the volume label for the /boot mountpoint declaration are correct (case sensitive) in thinstation.conf.buildtime, and edit ts/build/packages/hdupdate/etc/init.d/hdupdate to check for vmlinuz at in /boot/boot.
