### ISSUE TITLE
VMware View Additional Configuration

### ISSUE THREAD

**Issue by phantomsignal1** [Thinstation/thinstation#682]
Hi Team,

I'm very new to ThinStation - still working on developing & deploying my first ThinStation image. 

I use VMware View and need to do some extra configuration which I haven't been able to find some working examples for... specifically disabling H.264 on the VMware Blast protocol.
I found some Github issue (https://github.com/Thinstation/thinstation/issues/468) where they suggested adding some configuration into ./packages/vmview/etc/skel/.vmware  however, after building (error free) there doesn't seem to be any different to the VMware View configuration.

![image](https://user-images.githubusercontent.com/92279169/143317079-0692d865-eb82-4841-b9b4-1920755054b6.png)

My build.conf and thinstation.conf.buildtime files are exact copies of the ones provided in the example here: https://github.com/Thinstation/thinstation/tree/6.2-Stable/ts/build/conf/vmview

I haven't been able to find a good repository of documentation around VMware View and all the different customizable settings. Does such a thing exist?

**Comment by rohrbachger** [comment]
Which client version you are running? We have issues with the actual client versions, good working seems an older 2006 Version..
But we are running IPCOP and not Blast.

Our standard settings, probably will not help in your case.

VMVIEW_SSLVERIFYMODE=1
VMVIEW_DEFAULTBROKER=View.MyServer.de

SESSION_1_ICON=ON
SESSION_1_TITLE="View-Horizon"
SESSION_1_TYPE=vmview
SESSION_1_AUTOSTART=ON
SESSION_1_VMVIEW_ONCE=True

**Comment by phantomsignal1** [comment]
Running 2103 here. I've got the configuration you've outlined above working OK, but I'd love to have some more of the additional configurations available. To date, I've only used the Windows Clients which are extremely configurable. There seems to be a lot of options available... as I write this, I just thought about using a shell script during the deployment to add/configure the files under /etc/vmware/view-mandatory-config and you can then use the configurations outlined in https://docs.vmware.com/en/VMware-Horizon-Client-for-Linux/2103/horizon-client-linux-installation/GUID-AB6F0B4D-03DD-4E7A-AE16-BAB77CE4D42D.html
