### ISSUE TITLE
python PIP install

### ISSUE THREAD

**Issue by rohrbachger** [Thinstation/thinstation#683]
In the actual TS I have the problem to install python stuff like in the versions before.
In the chroot
pip install pyodbc

Requirement already satisfied: pyodbc in /usr/lib/python3.9/site-packages (4.0.32)
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv

python 3.8 and python 3.9 are in the lib folder.

Probably how I´m doing is wrong, but it has worked in older versions..

How I have to implement tools like pyodbc or pywinrm?

**Comment by Doncuppjr** [comment]
It’s just a warning not a failure.


Sent from Yahoo Mail for iPhone


On Thursday, November 25, 2021, 7:05 AM, rohrbachger ***@***.***> wrote:




In the actual TS I have the problem to install python stuff like in the versions before.
In the chroot
pip install pyodbc

Requirement already satisfied: pyodbc in /usr/lib/python3.9/site-packages (4.0.32)
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv

python 3.8 and python 3.9 are in the lib folder.

Probably how I´m doing is wrong, but it has worked in older versions..

How I have to implement tools like pyodbc or pywinrm?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rohrbachger** [comment]
But the ODBC connection is not working anymore, the module is missing or not correctly installed.
So I will try at the weekend to get this fixed. With pywinrm I have also issues.
Both probably have the same reason.

**Comment by Thinstation** [comment]
Do you need those in the chroot, or the final image? If it’s the final
image, you can create a pip2.freeze or pip3.freeze in a package/build
folder.

**Comment by rohrbachger** [comment]
I need it in the final image, it was always ugly...
I copied the /lib python folders, as I was not able to figure out which files really were needed.
So a lot of spaces needed, I guess it is near to 100MB.
Is there any special way to do this? I did not found a similar package

**Comment by Thinstation** [comment]
Look at my octoprint package for an example of how to do python

**Comment by rohrbachger** [comment]
I looked at octoprint, but did not got it. Complex.

For my special needs I do need.
unixodbc and freetds.
I think it is similar to other ports.
get the source and ./configure, make make install. 
( currently I copy the lib files by script, dirty, but works a long time already.
But I think I can create now a package for this, maybe someone else can use this.
This has a learning effect.

For python I'm doing
pip install pyodbc
pip install pywinrm
pip install pywinrm[credssp]

I copy /usr/lib/python3.9/distutils and site-packages folder.
This makes my iso large, but I did not figured the needed files out.

**Comment by Thinstation** [comment]
Look at pip2.freeze in octoprint

**Comment by rohrbachger** [comment]
I have to spend time for testing, in general I understood.
But some details I have to figure out.

**Comment by rohrbachger** [comment]
In general I got it working , the octoprint sample was a good help.
I have created pyodbc, pywinrm, requests-credssp.
In the Pgkfile I use 
source=( http://DESVR-PXE/jobs/requests-credssp-$version.tar.gz )

A web source to this py package seems not to work ( only python modules) , so I placed the file on our own server.
This is a little bit dirty, 
But 
source=( file://DESVR-PXE/jobs/requests-credssp-$version.tar.gz ) seems not to work.
I did not found a hint in build for this.
Is there another script doint the ts/ports/nocache PgKfile?
I would like to have the same logic like in the build.url

**Comment by Thinstation** [comment]
You don't need to make python ports unless you need python in the chroot. If you only need python packages in a build, use a pip2.freeze or pip3.freeze. Octoprint has both a port and a package. I wanted you to look at the package, and specifically at the pip2.freeze https://github.com/Thinstation/thinstation/blob/6.2-Stable/ts/build/packages/octoprint/build/pip2.freeze

**Comment by rohrbachger** [comment]
Got it, now I know how to build a port also...
For the pyodbc and pywinrm port is not necessary, I know now.

with packages like unixodbc and freetds I still have ports, probably I do not need post also.
I will test it also, I do need it only in the ts final image not in chroot.
