### ISSUE TITLE
The system was not able to go graphical

### ISSUE THREAD

**Issue by RichCoop** [Thinstation/thinstation#694]
Hello, first of all I am pretty new to the thinstation, so I am pretty sure i have some sort of newbie mistakes, but still.
I tried to run thinstation on the hard drive, downloaded the latest one. I used Debian to build it. Once i run the thinstation it says this:

"The system was not able to go graphical. This could indicate a problem with missing kernel modules or Xorg drivers.
There are no autostarted sessions!
Dropping to shell."

Does it mean I have something wrong in my configs?
[thinstation.conf.buildtime.txt](https://github.com/Thinstation/thinstation/files/7903027/thinstation.conf.buildtime.txt)
[build.conf.txt](https://github.com/Thinstation/thinstation/files/7903028/build.conf.txt)

**Comment by Thinstation** [comment]
You should watch my getting started with ThinStation video. The link is in
the wiki.

Try building with —allmodules.

**Comment by RichCoop** [comment]
Just tried that, still the same thing.

I also tried building with --allmodules --autodl --kernel 64 just like in the video.
For kernel 64 it says: "Kernel 64 doesn't exist, ERROR!!"

Maybe this has to do something with my error.

**Comment by Thinstation** [comment]
I would need to see Xorg.0.log

**Comment by RichCoop** [comment]
[Xorg.0.log](https://github.com/Thinstation/thinstation/files/7912269/Xorg.0.log)

Hope this is the right one.

**Comment by Doncuppjr** [comment]
I was thinking of the build that failed, but this might help too. In build.conf, make allfirmware is true, the xorg7-ati and Radeon are selected, then build —allmodules.

Sent from Yahoo Mail for iPhone


On Friday, January 21, 2022, 2:00 AM, RichCoop ***@***.***> wrote:




Xorg.0.log

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by RichCoop** [comment]
> I was thinking of the build that failed, but this might help too. In build.conf, make allfirmware is true, the xorg7-ati and Radeon are selected, then build —allmodules.

How exatly should i write the 'radeon' parts
Like this:
'package xorg7_radeon'?

The rest was done since the beginning.

**Comment by RichCoop** [comment]
I don't know how to include radeon package, on all my attempts it says that it can't find such. The rest things are on and the issue is the same.

**Comment by Thinstation** [comment]
The package name changed. The two packages for radeon are 
xorg7-amdgpu and xorg7-ati
You might have missing firmware from a bad unwind. Check for logs at /var/log/pkgbuild and missing firmware at /ts/firmware_notfound in a log for the kernel module for your gpu, like amdgpu.ko. Beyond that, I would need log files like Xorg.0.log from a failed attempt.

**Comment by RichCoop** [comment]
OK, i will try it all. I will send the log files after that.

**Comment by RichCoop** [comment]
"xorg7-amdgpu and xorg7-ati" these were ON since the beginning.
"/ts/firmware_notfound" there is no 'firmware_notfound' in such directory. 
"/var/log/pkgbuild" here however there is one log file (edk2.log)
[edk2.log](https://github.com/Thinstation/thinstation/files/7931299/edk2.log)

So Xorg.0.log is the same.
[Xorg.0.log](https://github.com/Thinstation/thinstation/files/7931344/Xorg.0.log)


In short at the time i got this error for the first time:

allfirmware was set to true, package xorg7-ati and package xorg7-amdgpu were ON (uncommented)

**Comment by RichCoop** [comment]
Just in case I tried this again, same issue.
However, there is no Xorg.0.log in the thinstation\... directory, only in the parent directory then \var\log
[Xorg.0.log](https://github.com/Thinstation/thinstation/files/7932196/Xorg.0.log)

**Comment by Thinstation** [comment]
I need the log from the system from the boot attempt that gives you the can't go graphical error. If you booted from a thumb drive, you could do the following,
su, password by default is pleasechangeme
cp /var/log/Xorg.0.log /boot/.

**Comment by Thinstation** [comment]
also journalctl -xe > /boot/journal.log

**Comment by RichCoop** [comment]
Funny, there is no /boot/ directory in the actual thinstation, however i managed to get the log files. Here they are
[journal.log](https://github.com/Thinstation/thinstation/files/7941169/journal.log)
[Xorg.0.log](https://github.com/Thinstation/thinstation/files/7941170/Xorg.0.log)
:

**Comment by Thinstation** [comment]
Hmmmmm. I'll take a look over the weekend. I don't have any radeon systems handy at the moment.

**Comment by RichCoop** [comment]
Thank you nevertheless.

**Comment by Thinstation** [comment]
Lets try this.

make a file /ts/build/packages/base/etc/X11/xorg.conf.d/00-noglamoregl.conf

Section "Module"
	Disable "glamoregl"
EndSection

Then build and boot.

**Comment by RichCoop** [comment]
Ok, i will try this.
I assume this file doesn't exist in that directory untill I make it, right?
If it is so i just need to copy these:
"Section "Module"
Disable "glamoregl"
EndSection"
So it will be the file only with these lines, yes?
Sorry to ask such dumb questions, it is because i will be able to do the edits this monday.

**Comment by icecy29** [comment]
Hi, I have the same problem, but I am able to run it on "5.6-Stable", hope this works for you.

**Comment by Thinstation** [comment]
I don't have a system that uses the xorg7-ati package. I did go ahead and rollup the xorg and mesa packages. Maybe give the latest commit a try.

**Comment by RichCoop** [comment]
So, i should update the thinstation and try to build it again?

**Comment by Thinstation** [comment]
Yep

**Comment by RichCoop** [comment]
OK, will do it tomorrow.

**Comment by RichCoop** [comment]
Now the Thinstation isn't loading, it says:
"kernel panic not syncing no working init found try passing init..."

**Comment by RichCoop** [comment]
Tried, same issue.

**Comment by Doncuppjr** [comment]
You could try using the modeset driver. Remove xorg7-ati and xorg7-amdgpu

**Comment by Thinstation** [comment]
I found a patch for the xorg7-ati driver. I have applied and pushed. Let me know if that fixes it.

**Comment by RichCoop** [comment]
I will try all of these, just in case, to use newest features, first i need to rmove thinstation like this:
"cd thinstation
./setup-chroot
clean_chroot
exit"
Then update it with this:
"git pull"
Then run ./setup-chroot and the rest of the things, yes?

**Comment by Thinstation** [comment]
Yes.

**Comment by RichCoop** [comment]
OK, I will test my luck tomorrow.

**Comment by RichCoop** [comment]
Turns out it runs now, I see a window which asks me to write login and password. It suppose to fill it from the thinstation.conf.buildtime, but it doesn't, and i got freerdp error if i try to type it manually. I think it is because connecting to the RDS is a bit tricky. Anyway this is a different problem so yeah, the issue is solved, i suppose.

Thank you all.
