### ISSUE TITLE
Thinstation connecting to an RDS Farm

### ISSUE THREAD

**Issue by RichCoop** [Thinstation/thinstation#696]
Hello, I m trying to connect my thinstaion (latest) to the RDS Farm, but it doesn't work i got several erorrs:

1.[ERROR][com.winpr.timezone] - Unable to get current timezone rule.

2.[INFO][com.freerdp.core] - ERRINFO_CB_CONNECTION_ERROR_INVALID_SETTINGS: The settings contained in the routingToken field of the X.224 Connection Request PDU (selection 2.2.1.1) cannot be validated.

3.[ERROR][com.freerdp.core] - rdp_set_error_info:freerdp_set_last_error_ex ERRINFO_CB_CONNECTION_ERROR_INVALID_SETTINGS
Then i got 2 and 3 again, and in the end:

4. [ERROR][com.freerdp.core] - rdp_set_error_info: T0D0: Trying to set error code  ERRINFO_CB_CONNECTION_ERROR_INVALID_SETTINGS, but ERRINFO_CB_CONNECTION_ERROR_INVALID_SETTINGS already set!

The parameters I use: 
xfreerdp /f /v:server /u:user /p:password /d:domain /cert-ignore /load-balance-info:'MS Terminal Services Plugin.1.Sample' /g: gateway

If I try to connect to the something but the farm, it works just fine.

The rdp file to connect to the farm from windows OS looks like this:

redirectclipboard:i:1
redirectprinters:i:1
redirectcomports:i:0
redirectsmartcards:i:0
devicestoredirect:s:*
drivestoredirect:s:*
redirectdrives:i:1
session bpp:i:32
prompt for credentials on client:i:1
server port:i:<port>
allow font smoothing:i:1
promptcredentialonce:i:1
videoplaybackmode:i:1
audiocapturemode:i:0
gatewayusagemethod:i:2
gatewayprofileusagemethod:i:1
gatewaycredentialssource:i:0
full address:s:<address>
gatewayhostname:s:<gateway>
workspace id:s:<address>
use redirection server name:i:1
loadbalanceinfo:s:tsv://MS Terminal Services Plugin.1.Sample
use multimon:i:1
username:s:domain\

Perhaps I post this toping a wrong place, but perhaps you know the solution or where can i find it?

**Comment by Doncuppjr** [comment]
I would go to the freerdp irc channel. 






On Friday, February 4, 2022, 08:52:54 AM PST, RichCoop ***@***.***> wrote: 







Hello, I m trying to connect my thinstaion (latest) to the RDS Farm, but it doesn't work i got several erorrs:

1.[ERROR][com.winpr.timezone] - Unable to get current timezone rule.

2.[INFO][com.freerdp.core] - ERRINFO_CB_CONNECTION_ERROR_INVALID_SETTINGS: The settings contained in the routingToken field of the X.224 Connection Request PDU (selection 2.2.1.1) cannot be validated.

3.[ERROR][com.freerdp.core] - rdp_set_error_info:freerdp_set_last_error_ex ERRINFO_CB_CONNECTION_ERROR_INVALID_SETTINGS
Then i got 2 and 3 again, and in the end:

     
    1. [ERROR][com.freerdp.core] - rdp_set_error_info: T0D0: Trying to set error code ERRINFO_CB_CONNECTION_ERROR_INVALID_SETTINGS, but ERRINFO_CB_CONNECTION_ERROR_INVALID_SETTINGS already set!
    

The parameters I use:
xfreerdp /f /v:server /u:user /p:password /d:domain /cert-ignore /load-balance-info:'MS Terminal Services Plugin.1.Sample' /g: gateway

If I try to connect to the something but the farm, it works just fine.

The rdp file to connect to the farm from windows OS looks like this:

redirectclipboard:i:1
redirectprinters:i:1
redirectcomports:i:0
redirectsmartcards:i:0
devicestoredirect:s:*
drivestoredirect:s:*
redirectdrives:i:1
session bpp:i:32
prompt for credentials on client:i:1
server port:i:
allow font smoothing:i:1
promptcredentialonce:i:1
videoplaybackmode:i:1
audiocapturemode:i:0
gatewayusagemethod:i:2
gatewayprofileusagemethod:i:1
gatewaycredentialssource:i:0
full address:s:

gatewayhostname:s:
workspace id:s:
use redirection server name:i:1
loadbalanceinfo:s:tsv://MS Terminal Services Plugin.1.Sample
use multimon:i:1
username:s:domain\


Perhaps I post this toping a wrong place, but perhaps you know the solution or where can i find it?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by RichCoop** [comment]
That's what i did, in short the thing was to write /load-balance-info value properly, which should look like tsv://'Sample'.
Thinstation reads it properly from the thinstation.conf.buildtime and so all works fine.

**Comment by RichCoop** [comment]
Turns out there is a problem here anyway.
Thinstation doesn't want to connect to the RDS Farm, in the same time if use the same settings to connect to it from Debian like xfreerdp /key1 /key2 etc all works.

**Comment by RichCoop** [comment]
I just tried it this way, i removed "Session_0_freerp_server" line from the config.
And so i was able to edit server section and options section directly from the thinstation.
I ve found a combination which allowed me to connect, it was quite simple, i had to put /load-balance-info value into the double " instead of the double ' .
The problem is, if i try to write it the same way in the thinstaion.conf.buildtime i receive an error during the ./build phase. How can i write this to let it build properly?

**Comment by Thinstation** [comment]
Use a \ to escape any extra “ you need to insert

**Comment by RichCoop** [comment]
So, i should write it like:

SESSION_0_FREERDP_OPTIONS="/1 /2 /3 /load-balance-info:\MS....\ /4 /5"

No?

**Comment by RichCoop** [comment]
Lul, I'm stupid, i got that you meant and yeah, it worked, thanks.

If anyone will look for this, i got to write it this way:

SESSION_0_FREERDP_OPTIONS="/1 /2 /3 /load-balance-info:\"tsv://MS....\" /4 /5"
