### ISSUE TITLE
Client léger thinstation

### ISSUE THREAD

**Issue by 29TssrCyril01986** [Thinstation/thinstation#708]
Hello everyone what does error 24 mean?
![image](https://user-images.githubusercontent.com/103580921/163210647-7ff6e182-2641-4916-ae4c-44f30cb7eee4.png)
Can you help me?

**Comment by Thinstation** [comment]
View Log

**Comment by Thinstation** [comment]
in error.h, I see
#define ERRINFO_SERVER_CSRSS_CRASH 0x00000018
Which would equate to decimal 24

**Comment by 29TssrCyril01986** [comment]
![image](https://user-images.githubusercontent.com/103580921/163335436-203a5b84-cc33-4632-b991-6ff9959576a6.png)

**Comment by 29TssrCyril01986** [comment]
https://www.transfernow.net/dl/20220414ur3x6Ge8

Link to the config file build.conf and thinstation.conf.buildtime. I simply changed some sensitive details such as the server address.

Thank you for your help

**Comment by 29TssrCyril01986** [comment]
No one to help me?

**Comment by Thinstation** [comment]
The issue is with FreeRDP and your server, not ThinStation. Try at freerdp.

**Comment by Doncuppjr** [comment]
Looks like bad arguments.
