### ISSUE TITLE
FreeRDP Autologin

### ISSUE THREAD

**Issue by paraigor** [Thinstation/thinstation#709]
Hello,
I understand, that same issue had been posted before, but, since there wasn't any working solution, try to ask again.
Freerdp app always ask for user and password, even if options are set up.
Current config (thinstation.conf.buildtime):
SESSION_0_TYPE=freerdp
SESSION_0_FREERDP_SERVER=192.168.0.2
SESSION_0_FREERDP_OPTIONS="/u:user /p:pass /cert:ignore"
RECONNECT_PROMPT=FORCE
SESSION_0_AUTOSTART=on

RDS server: Windows Server 2012 R2 (NLA enabled)
ThinStation 6.2.13
Client boot from USB drive

Tryed different combinations of /cert and /sec options. No luck.
Tryed to delete /etc/cmd/freerdp.getuser and freerdp.getpass files. This cause freerdp faild to start. It seems like this worked for older versions of ThinStation, 5.x
Searching for freerdp.getuser over internet suggesting options, mentioned above.

Advise please, what to do, to make freerdp autologin?
Or maybe you could point to code where CLI command is forming for freerdp during image building.

Thank you

**Comment by Doncuppjr** [comment]
Try this.

SESSION_0_FREERDP_OPTIONS="/p:pass /cert:ignore"
SESSION_0_FREERDP_USER=user
SESSION_0_FREERDP_PASS_ENABLE=false

**Comment by paraigor** [comment]
Hello Donald,
It works !
Thank you very much
