### ISSUE TITLE
Horizon View Client 2203 - 8.5.0 autostart DNS resolving issue

### ISSUE THREAD

**Issue by rohrbachger** [Thinstation/thinstation#711]
In general the actual client works fine in our environment.
But as we do use autostart for the view client, at first start comes an error message,
that the server name can not resolved.
A manual connect works without issues.

I would need a hint, how to delay the autostart some seconds. Probably that is the easiest way to solve the issue.
Probably another dirty way would be to edit the hosts file. Probably 3-5 seconds are okay already.
Or maybe there is another easy way to solve this small issue.

**Comment by Thinstation** [comment]
make a /build/packages/vmview/etc/cmd/vmview.options file, put sleep 5 in there.
