### ISSUE TITLE
What is the format of the IceWM menu file content?

### ISSUE THREAD

**Issue by alexanderzhirov** [Thinstation/thinstation#714]
In the icewm file.functions it is possible to add your own menu for IceWM. Through the global constants MENU_EXTRA and MENU_EXTRA_DIR, it is possible to specify the directory with the menu file. Only in what format to specify the contents of the file - I did not understand.

I can't add new menu items in this format:

```
MENU_EXTRA=only
MENU_EXTRA_DIR="/etc/icewm/menu_dir"
```

file `menu` in `/etc/icewm/menu_dir/`

```
~# cat /etc/icewm/menu_dir/menu
"Удаленный рабочий стол" "mstsc" mstsc
"Midnight Commander" "mc" mc
```

![изображение](https://user-images.githubusercontent.com/37277056/164993771-d674c94c-d2b3-4b80-9c0d-28b847ef0a03.png)

```
~# cat /root/.icewm/menu 
prog "" "" 
prog "" "" 
menu Resolution resolution_menu {
prog "1280x1024" "1280x1024" setres 1280x1024
}
menu Logout logout_menu {
prog "Shutdown" "shutdown" poweroff
prog "Reboot" "reboot" reboot
}
```

**Comment by alexanderzhirov** [comment]
UPD

The same goes for `idesk`. How to add programs and menu items correctly. Something is not clear at all.

**Comment by Thinstation** [comment]
All that stuff is ancient.

**Comment by Doncuppjr** [comment]
Look at /lib/menu


Sent from Yahoo Mail for iPhone


On Sunday, April 24, 2022, 1:22 PM, Alexander Zhirov ***@***.***> wrote:




UPD

The same goes for idesk. How to add programs and menu items correctly. Something is not clear at all.

**Comment by alexanderzhirov** [comment]
> Look at /lib/menu

Yes, it was necessary to create files with the configuration of the menu item in `/lib/menu` (in packages). Everything worked out! Thanks!
