### ISSUE TITLE
Network issue loading config files IPV6 Issue

### ISSUE THREAD

**Issue by rohrbachger** [Thinstation/thinstation#715]
I do noticed a strange network issue, in one VLAN in our network I do see in boot.log the message
Error network not initialized!. With that the hostname on this PC is not set, in the ts folder there is a list of Mac addreses
with hostnames. In general this has been working since years.
In our producton VLANS that works well, but not in our testing VLAN.
I double checked, the VLAN´s DHCP settings are correct, nor firewall or other specials should stop.

For testing I played aaroung with several settings e.g., but no improvement.
NET_LINKWAIT=5000
NET_IPV6_MODE=disabled

I would like to switch off IPV6 in total, to make sure that there are no site effects.
But even with the above setting ifconfig shows an IPV6 address.
network interface is enp2s0f0

I´m using: package ts-classic, because in the past I had some issues with the network manager.

After the TS is started the network works fine, but of course the hostname is not applied.

Do you have any idea how I can disable IPV6 in total and/or debug this strange issue?

**Comment by Thinstation** [comment]
add  ipv6.disable=1 to the kernelcmdline

**Comment by rohrbachger** [comment]
Well, ipv6 is disabled now. This is good for deeper analysis.

Still I have the issue in some VLAN´s. They all are configured in the same way.
But on some the first network connecton does not work like expected. 

It might be, that the DHCP lease information takes longer, and this is creating the later issues.
I tried to understand the boot processes, to write some additiona logs and put same sleep commands.

I think the problem is before autonet. Probably the /etc/udev/scripts/pre-net.sh and net.sh
So for my understanding at some point the DHCP options are written. 
In case of the working VLANS I do see in /var/log/net/enp2s0f0 e.g. the boot_file is filled.
In case of the none working VLANS I do see in /var/log/net/enp2s0f0 e.g. there are less entries, no boo_tfile
(but also the client has booted by PXE )

Can you give a hint, how the order of scripts during boot is?
I would like to place a sleep before the dhcp options are got from the network.

**Comment by rohrbachger** [comment]
In thinstation.conf.buildtime this seems to fix my issues.

NET_DHCP_TIMEOUT=8
5 was not enough
