### ISSUE TITLE
Localizing freerdp dialog window

### ISSUE THREAD

**Issue by klemens-st** [Thinstation/thinstation#721]
I am trying to make a freerdp login window for my non English speaking users. I assume locale packages and settings have no effect on this because I have already tried it. Where can I find the source of the freerdp package to make my changes?

**Comment by Thinstation** [comment]
build/packages/base/etc/dialog.functions

**Comment by klemens-st** [comment]
Thanks! Not only have I achieved what I wanted but after examining the source I finally understand how the dialogs work and how the configuration affects them.
