### ISSUE TITLE
Intel Jasper Lake Kernel 5.15+?

### ISSUE THREAD

**Issue by fanuelsen** [Thinstation/thinstation#722]
Hi, as i understand Intel Jasper Lake (Q12021) needs 5.15 or later. Would there be an "easy" way for me to edit the current settings in thinstation to upgrade to this kernel? I was looking at the custom kernel wiki but don't quite understand it.

I get it to boot on 5.10.89 but no sound or graphics are working properly. 

Can anyone point me in the right direction about building a newer kernel? Thanks :)

**Comment by Thinstation** [comment]
update /ts/ports/kernel-modules/VERSION, then run rebuild-kernels -a
