### ISSUE TITLE
The global variable PS1 is not overridden

### ISSUE THREAD

**Issue by alexanderzhirov** [Thinstation/thinstation#725]
I want to redefine a variable. I add the installation to the `~/.profile`, but after the launch, the old value remains anyway, although the `EDITOR` and `XDG_RUNTIME_DIR` is redefined:

```sh
root@ts_080027b3b812:~$ cat .profile 
export EDITOR=mcedit
export PS1="\[\033[38;5;081m\]\u\[\033[38;5;245m\]@\[\033[38;5;206m\]$CLIENT_IP \[\033[38;5;245m\]\w \[\033[38;5;081m\]\n # \[\e[0m\]"
export XDG_RUNTIME_DIR=/run/user/$(id -u)
```

If I do `source ~/.profile`, then everything is executed

**Comment by Thinstation** [comment]
PS1 might be overridden by thinstation.global. Put your PS1 in thinstation.conf.buildtime and see if that works.

**Comment by alexanderzhirov** [comment]
> Put your PS1 in thinstation.conf.buildtime and see if that works.

Unfortunately, it doesn't work either.

**Comment by Thinstation** [comment]
I see PS1 defined in two places.
base/etc/ashrc:PS1='\h:\w\$ '                 # for busybox
base/etc/thinstation.env:PS1='\h:\w\$ '  # for bash

**Comment by alexanderzhirov** [comment]
@Thinstation I can change the configuration files, but I don't want to go into the settings of the TS itself. I'm thinking how to change it through my package.

**Comment by Thinstation** [comment]
Use sed with a finalize script in your package to update the config inside
the new image.

**Comment by Thinstation** [comment]
Or keep modified copies of those files in your package.

**Comment by alexanderzhirov** [comment]
> Use sed with a finalize script in your package to update the config inside the new image.

Here is such a perversion turned out, but it works!

![изображение](https://user-images.githubusercontent.com/37277056/169624106-48c2b442-e239-4df4-8eae-c8f0e1d9e5bb.png)


I put all this in `finalize`:

```sh
sed -i 's/PS1='\''\\h:\\w\\$ '\''/PS1='\''\\[\\033[38;5;081m\\]\\u\\[\\033[38;5;245m\\]@\\[\\033[38;5;206m\\]\$CLIENT_IP \\[\\033[38;5;245m\\]\\w \\[\\033[38;5;081m\\]\\n # \\[\\e[0m\\]'\''/g' /etc/thinstation.env
sed -i 's/PS1='\''\\h:\\w\\$ '\''/PS1='\''\\[\\033[38;5;081m\\]\\u\\[\\033[38;5;245m\\]@\\[\\033[38;5;206m\\]\$CLIENT_IP \\[\\033[38;5;245m\\]\\w \\[\\033[38;5;081m\\]\\n # \\[\\e[0m\\]'\''/g' /etc/ashrc
```

P.S. Works by default on the input with `ash`.
