### ISSUE TITLE
 help with image creation

### ISSUE THREAD

**Issue by jumabape** [Thinstation/thinstation#727]
Hello, I'm sorry for my bad English, but I need help, I've already created at least 4 images and I can't get it to work on my LTSP server. When I take the ISO and install it on the LTSP server, it tells me that it can't find vmlinuz or intrd. What I have managed to do is force it by copying and pasting the files in the LTSP configuration area, but nothing stays loading for a long time

![image](https://user-images.githubusercontent.com/106191110/170280135-f87378a6-f3c9-465c-a858-07304b59cdbc.png)

I don't know if I'm doing something wrong or if you could pass me an iso already prepared for thin client

**Comment by alexanderzhirov** [comment]
Try to build a minimal build - `build/conf/tiny`

**Comment by jumabape** [comment]
how do i do it?

![image](https://user-images.githubusercontent.com/106191110/170354102-dd408263-07b7-4915-b0d4-bc1e928e9c73.png)

I don't see the build file

**Comment by alexanderzhirov** [comment]
> how do i do it?

```
sudo ./setup-chroot
cd build
cp conf/tiny/* .
./build
```

You just use other configurations for the build that are defined in these two files. They need to be copied to the `build` directory to build.
Inside the `build.conf.example` file is a list of packages included in the build. The more packages, the larger the size. Perhaps old PCs may not load due to their large size.

And how old are computers? What is the bit depth? TS 6.2, if I'm not mistaken, is x64.

**Comment by jumabape** [comment]
I tell you, this goes on an LTSP server that distributes thin clients, but when I try to make the LTSP kernel (image or iso) it does not catch me or find the intrd or vmlinuz files, which in another iso does detect me and it works fine 
and thin clients are virtual machines

it does not work

![image](https://user-images.githubusercontent.com/106191110/170356548-f3f3517c-e02d-400f-8012-a93350cef377.png)

**Comment by Thinstation** [comment]
ThinStation and LTSP both do the same thing. I don't know why you are trying to mix them.

**Comment by jumabape** [comment]
Because it is for a class project, Yes I lose but I need another image from a system other than ubuntu for ltsp,  It is to be able to have several options to choose from and as a thinstation it is also capable of making images

**Comment by Thinstation** [comment]
vmlinuz and initrd are available under /boot
I don't know what issue LTSP takes with it, but the files should be there.
