### ISSUE TITLE
DevStation pxe on Ubuntu

### ISSUE THREAD

**Issue by justthenitguy** [Thinstation/thinstation#728]
Hi,

I've installed devstation os and it works fine but i need to match security measures in my compagny so i had to move it, so i installed it on Ubuntu and again work just fine but i can't get the pxe to contact the server.

I didn't need to turn it on for the devstation os, so does the pxe need to be manually activated on ubuntu?

Regards

**Comment by Thinstation** [comment]
Yes. You will need to stand up all your own services like tftp and http, and point them at the build output directory of your choice.

**Comment by justthenitguy** [comment]
Ok thanks.

At the end of the compiling when "Making boot image for pxe..." is it possible to change the output to point to a NAS or DFS directly? Because the image will be used for around a thousand laptop maybe more so i need to be sure that the server won't burn all of the sudden

**Comment by Thinstation** [comment]
Idk. I have never tried. I guess you could mount something at the output branch. Else, just have a post script push everything where you want it.

**Comment by Thinstation** [comment]
And use the grub output instead of syslinux PXE.

**Comment by Thinstation** [comment]
Another user setup iPXE, and created a peer booting protocol to avoid network bottlenecks. Very cool.
