### ISSUE TITLE
Thinstation http boot

### ISSUE THREAD

**Issue by RichCoop** [Thinstation/thinstation#731]
Hello everyone, I've faced a quite strange problem.
I managed to configure my thinstation the way I wanted, it was booting through the http, everything is fine, more or less.
But few days ago I tried to change the config file a little, to test some stuff, I rebuilt the thinstation, uploaded new files to my server, but to my surprise the thinstation loaded as there were no changes.
I tried many things, even complete erase and redo the thinstation on the server, yet it loads the same old configuration.
Another weird thing, it can load the thinstation with just pxelinux.cfg folder! It seems, it takes the files from somewhere else, but where? If I delete everything from the server, I'll get the standard error as the client machine doesn't know where to take the files. So it definetely searches for the files on my server, but once it has pxelinux.cfg, it loads the old files. Where should I look? Can it be something with DHCP?
[thinstation.conf.buildtime.txt](https://github.com/Thinstation/thinstation/files/8916889/thinstation.conf.buildtime.txt)
[build.conf.txt](https://github.com/Thinstation/thinstation/files/8916890/build.conf.txt)

**Comment by alexanderzhirov** [comment]
Most likely there is a problem with your server, since the TS build does not affect the download in any way.

**Comment by RichCoop** [comment]
Ok, i ll try it with the other server, the current tftp server is on Debian Bullseye, let's see how it goes with Windows based tftp.

UPDATE: It worked, turns out something happened with the tftp server indeed, though i have other problem now, fat32 usb and smartcards don't work, but guess its another topic.

**Comment by RichCoop** [comment]
> Most likely there is a problem with your server, since the TS build does not affect the download in any way.

Thank you.
