### ISSUE TITLE
Xfce monitor configuration

### ISSUE THREAD

**Issue by herotm** [Thinstation/thinstation#733]
For Dual Monitors

Is there a way to configure which monitor goes to the left or right without doing it on the xfwm4 desktop

**Comment by Thinstation** [comment]
USE_XRANDR

**Comment by herotm** [comment]
i found some google tutorials

do i just add
xrandr=value

on the thinstation.conf.buildtime or is there or a particilar command since i dont see it on the faq

**Comment by herotm** [comment]
nvm i think i found some leads

**Comment by Thinstation** [comment]
I was gonna say, look at /build/conf/x-advanced.conf.sample

**Comment by herotm** [comment]
thank you, all figured out.
