### ISSUE TITLE
How to install openldap from /ports/opt into build packages?

### ISSUE THREAD

**Issue by Decafpancakes** [Thinstation/thinstation#735]
I'm trying to install openldap from /ts/ports/opt but everything that i'm following does not seem to be working. Im getting an error that says: 
Adding Package Dependencies
Adding 5.10.119TS module dependencies on other packages
Dependencies are clean!
Adding and install non-distributable binaries
objdump: './build-openldap/openldap/lib/liblber.so': No such file
MISSING SONAME ./build-openldap/openldap/lib/liblber.so.2

Error has occured while installing package
Build Aborted

I'm going to attach my build log as well, any help would be greatly appreciated! 
[build.log](https://github.com/Thinstation/thinstation/files/8942044/build.log)

**Comment by Thinstation** [comment]
Should be fixed now

**Comment by Decafpancakes** [comment]
How do I properly install it from ports? Do I just copy the folder into packages? And how do I get the updated version?

**Comment by Thinstation** [comment]
Do a 
git pull
rm -rf /build/packages/openldap
mkrepackage openldap

**Comment by Decafpancakes** [comment]
So I did that and rebuilt the image, but not 100% sure it worked. In the openldap folder in packages there is an empty dependency file along side a build folder with just install and remove. Also, does installing it automatically add entries to thinstation.conf.sample to configure it or is that something that is done a different way?

**Comment by Thinstation** [comment]
Right now there is no openldap package, you are making it. It has no
configuration script, but you could write one that runs off of the .conf
files. Please use good variable names. Or just put your configuration into
profile package.

Add
package openldap
To build.conf
