### ISSUE TITLE
add ".deb" a medical viewer

### ISSUE THREAD

**Issue by cubanitoalex** [Thinstation/thinstation#736]
Help how to add "deb" a medical viewer that I need for the hospital where I work Weasis DICOM Viewer in last version TS6.2

https://github.com/nroduit/Weasis/releases/download/v4.0.1/weasis_4.0.1-1_arm64.deb

Will it be possible???????????????

**Comment by Thinstation** [comment]
Look at the edge and teams packages for examples of how to do a .deb import.

**Comment by Thinstation** [comment]
You will also need an entry in /build/build.urls

**Comment by cubanitoalex** [comment]
> You will also need an entry in /build/build.urls

If I'm reading the steps, if I achieve this, many doctors will thank me, and most importantly, bye-bye Windows!!! Thanks for answering me.
