### ISSUE TITLE
Weird Keyboard Issue

### ISSUE THREAD

**Issue by herotm** [Thinstation/thinstation#737]
Burn built image USB with Rufus (EFI), Boot System with ISO, Everything works dandy.

scp SAME syslinux boot files to PXE, boots fine BUT keyboard doesnt work ( unless replug )

built with ./build --allmodules

USB Iso works perfectly fine with keyboard and everything, but once i PXEboot, keyboard doesnt work unless i replug the Usb Keyboard.

PXE is Legacy Mode ( cant test with EFI PXE, bios doesnt support it )

Linux Kernel Version: 5.18

PXE Boot Options
=========================
label Thinstation Kernel 5.18
  menu label Thinstation Kernel 5.18
  kernel http://192.168.50.254/pxe/images/thinstation5.18/boot/vmlinuz
  append initrd=http://192.168.50.254/pxe/images/thinstation5.18/boot/initrd splash=verbose,theme:default console=tty1 LM=2

**Comment by herotm** [comment]
I found a related bug post on this but I am not sure how to implement this solution can anyone shed some light, thank you

https://github.com/ckb-next/ckb-next/issues/42

**Comment by Thinstation** [comment]
So is that with all keyboards? Or are you just testing with one model?

**Comment by herotm** [comment]
Just this specific one, I am pretty sure the other generic ones will work fine

**Comment by Thinstation** [comment]
What is special about this keyboard?

**Comment by herotm** [comment]
Nothing really  just the same gaming keyboard ive been using for the past  8 years. I am just going to close issue since its a special case
