### ISSUE TITLE
VirtualBox shared folder doesn't mount

### ISSUE THREAD

**Issue by vhst** [Thinstation/thinstation#739]
Shared folder doesn't mount in VirtualBox (tested with version 6.1.32). vboxguest package is installed.

`/sbin/mount.vboxsf: mounting failed with the error: No such device`

After a long research I've found out that the module vboxsf has not been compiled. Apparently it's because the code in the [script file](https://github.com/Thinstation/thinstation/blob/6.2-Stable/ts/build/packages/vboxguest/build/install) is commented. I've tried to uncomment, install kernel-keys port and compile the module but with no luck. vboxsf doesn't load:

`modprobe: ERROR: could not insert 'vboxsf': Key was rejected by service`

What was the reason for commenting that part of code? Is there a way to fix it somehow?

**Comment by Thinstation** [comment]
vboxsf code was merged into kernel 5.14. Try upgrading to that kernel
