### ISSUE TITLE
last change to splash_comm_send() causes login to stall

### ISSUE THREAD

**Issue by jens-maus** [Thinstation/thinstation#74]
I have just noticed that you latest change to splash_comm_send() causes that a ssh login or console login to be stalled because the /lib/splash/cache/.splash fifo file is still present and the /etc/profile file tries to ensure that the splash screen is not active due to enforcing splash_exit() again. This end up in a login to stall.

With the following change I tried to compensate for that, but IMHO it is not perfect to assign tsuser rights to the fifo file:

https://github.com/hzdr/thinstation/commit/8ee93ebd8dcf0bbcb9d640a5a1dc42fa9e2f0c27

A better approach would be if the splash daemon itself could remove the fifo or at least the corresponding pid file so that within splash_comm_send() we can check if the daemon is still running by checking if the pid file still exists. Or do you have any other smoother idea in mind?

**Comment by Doncuppjr** [comment]
I have no better idea, and that should work.

Sent from Yahoo Mail on Android
