### ISSUE TITLE
foxconn-nT330i network issue

### ISSUE THREAD

**Issue by DeadPo01** [Thinstation/thinstation#740]
Hi.
We have foxconn-nt330i barebones, and we load them by PXE - everything OK during booting, but there is an issue after full Thinstation boot with network connection.
We are pinging test machine and ping is around 1ms, right after getting an ip address from DHCP untill full Thinstation boot, then ping grows to 1000-2000ms... So RDP connection from Thinstation is impossible and VNC connection to thinstation is impossible... it connects, but freezes and disconnects.
We tryed to boot Windows 10 LiveCD and Ubuntu 22.04 LiveCD on this barebone - everything OK with network, ping - 1ms.
So the trouble is in Thinstation.
How to fix this network issue? What to try?

**Comment by Thinstation** [comment]
Is it a firmware issue?

**Comment by Thinstation** [comment]
Which network stack? That is a very strange issue.

**Comment by DeadPo01** [comment]
"Is it a firmware issue?" - i don't know =(
"Which network stack?" - Atheros AR8131

**Comment by Doncuppjr** [comment]
networkmanager or autonet?






On Sunday, July 17, 2022 at 11:34:50 PM PDT, DeadPo01 ***@***.***> wrote: 







"Is it a firmware issue?" - i don't know =(
"Which network stack?" - Atheros AR8131

**Comment by DeadPo01** [comment]
networkmanager/autonet - same problem

**Comment by Thinstation** [comment]
build with 
param allfirmware true

**Comment by DeadPo01** [comment]
Tried - same result...

**Comment by Thinstation** [comment]
That's a really old system. Maybe try an older kernel.

**Comment by DeadPo01** [comment]
Ubuntu 22.04 on kernel 5.15 and no problem.
I tried another terminal system based on linux (WtWare), and got same result on PXE boot..... BUT! Problem disapears when boot from USB Flash Drive....
Unfortunately i can't boot Thinstation from USB to try network, because this build, that i boot from PXE freezes on boot from USB =(

**Comment by DeadPo01** [comment]
On boot from USB it stuck on downloading global config. If i disconnect ethernet cable, it fails to get config and will boot, but without network connection, even if i connect the cable back. =(

**Comment by DeadPo01** [comment]
Tried to change autonet to newtworkmanager on USB build.
Client tried to access global config, didn't find it, wrote "Will boot in 5 seconds..." and stuck again....
But i can't see any access on http server for config files, when PXE boot i can see that client dowloading config files... But from USB http logs are empty, and tftp-hpa log is silent too...

**Comment by Thinstation** [comment]
I don't think netfiles works with networkmanager

**Comment by DeadPo01** [comment]
Returned to autonet.. but logs are silent, anyway. How to boot from USB?
Built iso image same as PXE, wrote it to flash by rufus from iso, boot... stuck on "Getting global config from (Serv_IP)"

**Comment by DeadPo01** [comment]
Ok. Managed to load from USB.
USB load can't boot with NET_FILE_METHOD=wget, only with NET_FILE_METHOD=tftp, configs loaded over tftp correctly and Thinstation started. And ping is stable, 1-2ms!
But.. what is the problem with network after load over PXE?!

**Comment by Thinstation** [comment]
You could try the ubuntu kernel.
prt-get install ubuntu-kernel
./build --kernel 5.8.0-63-generic

**Comment by DeadPo01** [comment]
Same problem. =(
So... i think it's device problem, specifically atheros module. Because other our devices have no such problem with PXE.
Will boot them from USB.
