### ISSUE TITLE
How to install yad

### ISSUE THREAD

**Issue by DeadPo01** [Thinstation/thinstation#741]
Hi.
I need help with adding port of "Yet Another Dialog" for gtk-2 https://github.com/step-/yad , but getting error on install =(
Help, please.
Pgkrfile:

```
name=yad
version=0.42.43
release=1
build() {
git clone https://github.com/step-/yad.git yad_gtk2
	cd yad_gtk2 &&
	git checkout maintain-gtk2 &&
	autoreconf -ivf &&
	intltoolize &&
	./configure --prefix=/usr --sysconfdir=/etc --enable-shared --disable-static &&
	make &&
	: install with: make install DESTDIR="$PKG"
}

```

Error:
```
...................
make[2]: Leaving directory '/ts/ports/gnome/yad/work/src/yad_gtk2'
make[1]: Leaving directory '/ts/ports/gnome/yad/work/src/yad_gtk2'
+ : install with: make install DESTDIR=/ts/ports/gnome/yad/work/pkg
=======> Build result:
bsdtar: *: Cannot stat: No such file or directory
bsdtar: Error exit delayed from previous errors.
=======> ERROR: Building '/ts/ports/gnome/yad/yad#0.42.43-1.pkg.tar.xz' failed.

-- Packages where install failed
yad

```
What dirrectory it can't stat?

**Comment by Doncuppjr** [comment]
You don't need all those &&, that's maybe something you would do outside of a port, but not in a port.

    git clone https://github.com/step-/yad.git yad_gtk2
    cd yad_gtk2
    git checkout maintain-gtk2
    autoreconf -ivf
    intltoolize
    ./configure --prefix=/usr --sysconfdir=/etc --enable-shared --disable-static
    make
    make install DESTDIR="$PKG"

**Comment by DeadPo01** [comment]
Thx. Package successfully installed.
But how to add it to final build to folder packages?
There not so much information about that in faq =(

**Comment by DeadPo01** [comment]
Found here about command mkrepackage "package_name", and got my package installed successfully during ./build process.
#633 
Thx for help with Pkgwile!

**Comment by Doncuppjr** [comment]
mkrepackage yadThen add package yad To build.conf
