### ISSUE TITLE
How to make changes made on thin station persistent? 

### ISSUE THREAD

**Issue by rm1740** [Thinstation/thinstation#743]
Hey so newbie question, I have installed and configured the image for thinstation. However there are some configuration changes that need to be made within VM Horizon client that cannot be done from the configuration file. When we make the changes in the client they work, but as soon as the machine is rebooted the changes are reset. How can we make it so that changes made are saved? 

Thanks!

**Comment by Thinstation** [comment]
Can you elaborate on the changes you need to make persistent. We generally try and avoid persistence.

**Comment by rm1740** [comment]
Hey, 

So there is a USB redirection setting. We are using different Published applications and only one application needs to have the usb redirected. When USB device is connected it shows up but we have to manually set which application to connect. It works during that session but once thin-station is rebooted the settings are wiped. From the config file we are able to only set USB redirection for full desktop sessions and not application.

**Comment by Thinstation** [comment]
The thing to do here, is export whatever  file ends up holding that
setting, and roll it into image.

**Comment by rm1740** [comment]
Thanks! Do you possibly know what file that would be and where it would be located? 

Also once I find the file and the settings required, where in the thin station build would I put it? Would it go in the buildtime or VMware Horizon client folder?

**Comment by rm1740** [comment]
Also, if needed is there a way to allow changes to be persistent?

**Comment by Thinstation** [comment]
I don’t know. A good place to start looking is at the TS user home dir. You
could copy all the files and make them into a profile package under
/build/packages/your_package/home/ts

You can also mount a rw volume there.

**Comment by Thinstation** [comment]
If your drive has two volumes, one called boot and the other called home, you should have some persistence.
The following two standard lines in thinstation.conf.buildtime make this possible.
MOUNT_0="LABEL=boot     /boot           auto    x-mount.mkdir,defaults  0       0"
MOUNT_1="LABEL=home     /home           auto    x-mount.mkdir,defaults  0       0"

**Comment by Thinstation** [comment]
I would make boot fat32 and home ext4.

**Comment by Thinstation** [comment]
https://github.com/Thinstation/thinstation/wiki/Persistence
