### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by biftabravo** [Thinstation/thinstation#744]
Hi,

I'm running the latest build of devstation 6.2.13. Fresh install, twice! When I build any image I keep getting the same error and looked at it to long now to figure it out! 

"line 20: can't open /etc/thinstation.functions : permission denied" 

Any help would be great!

**Comment by Thinstation** [comment]
What are the permissions on the file?

**Comment by biftabravo** [comment]
-rw-r-----

This on the booted image. It tries then fails with this error.

**Comment by Thinstation** [comment]
And the user.group?

**Comment by Thinstation** [comment]
What locale?

**Comment by biftabravo** [comment]
everything in etc is root 0

**Comment by Thinstation** [comment]
You might a umask issue. Perms should be rw.r..r..

**Comment by biftabravo** [comment]
strange its only the one file in there rest are fine. 

How can I change that?

**Comment by Thinstation** [comment]
Are you using an altered thinstation.functions in a custom package?

**Comment by biftabravo** [comment]
no. nothing special not changed anything. I've set my session_0 stuff for rdesktop and nothing else. Then build with --allmodules

**Comment by Thinstation** [comment]
And in the resulting image, only thinstation.functions has bad perms?

**Comment by biftabravo** [comment]
yep. everything else is what it should be. 
![Capture](https://user-images.githubusercontent.com/101673361/188990747-8fbee4a9-4405-4799-87a5-f83564a3e46b.PNG)

**Comment by Thinstation** [comment]
Looks like thinstation.packages is also getting baked. Should be rwxr-xr-x
What locale?

**Comment by Thinstation** [comment]
Look at your checkout and verify the perms on the files in /build/packages/base/etc

**Comment by biftabravo** [comment]
locale in dev env shows as C. guessing ive never set it.

**Comment by biftabravo** [comment]
> 

Looking at that now. 

Apricate the help

**Comment by biftabravo** [comment]
permissions are correct in /build/packages/base/etc

**Comment by Thinstation** [comment]
find /build/packages -name thinstation.functions

**Comment by Thinstation** [comment]
Also check dialog.functions

**Comment by biftabravo** [comment]
permissions are the same on the dialog file as well. Fine before build but in the image no read permissions

**Comment by Thinstation** [comment]
What is "your" locale?

**Comment by biftabravo** [comment]
UK lol

**Comment by Thinstation** [comment]
Those are core files, and that they are the files that are being disabled gives me pause. I would usually expect someone to customize those files for language, but you say that you have not done that.  ¯\_(ツ)_/¯

**Comment by biftabravo** [comment]
I thought it was me as well!! 

Fresh download and clean install. no changes made and nothing extra added to config. 

Just doing it again but on different hardware...

**Comment by Thinstation** [comment]
Could also try another base distro to host the clone. DevStation is a teacher, but maybe not the best host OS.

**Comment by biftabravo** [comment]
ok I have a ubuntu box I can use so ill add it there if one doesnt work

**Comment by biftabravo** [comment]
new hardware, same image, same config, working fine! 

The hypervisor was update a few weeks ago guessing a network driver or something like raid controller is causing an issue! 2 days well spent! 

Owe you a beer my friend!

**Comment by Thinstation** [comment]
That does not really explain why core files had there perms altered, but glad your back on track.
