### ISSUE TITLE
Feature request - build parameter to override the "/boot/" prefix easily

### ISSUE THREAD

**Issue by nneul** [Thinstation/thinstation#756]
Currently, the build script and internals expect the files to always be in /boot/.

I'd like to see a build parameter to either:

A) Allow prepending a value ("/somethingelse/boot/...")
or
B) Change /boot/ to /somethingelse/

The use case is having multiple distinct builds easily served from the same network boot server, but at different prefix paths.

**Comment by Thinstation** [comment]
5k

**Comment by nneul** [comment]
@Thinstation I don't understand the response and closure? Are you saying it would be a $5000 feature? Are you open to a PR implementing that capability?

**Comment by Thinstation** [comment]
Sure, but most just send a PR when they have the talent to do so.

**Comment by nneul** [comment]
#757

**Comment by Thinstation** [comment]
Please also modify the grub section, as that is the current way of doing
PXE, though that will really mess with ISO booting, but should not matter
for people only doing PXE

**Comment by nneul** [comment]
It seems weird to intentionally break the non-pxe ones though.... Would it be preferred to have the 'bootprefix' be specific to pxe in name? i.e. pxebootprefix ?

**Comment by Thinstation** [comment]
We would need to make a separate folder for grub pxe, but as it is the grub
output satisfies all boot methods even EFI PXE. Your mod would break
everything but PXE( when used ), and I guess that is okay.

**Comment by nneul** [comment]
Do you have a pointer to example of using the grub hierarchy with pxe
deployment? I can try that out, but thought the docs all refererred to
using lpxelinux as the standard boot method for network.  (What do you
even point to as the bootloader served on the initial tftp response from
dhcp server in that case?)

When I run this with all boot targets enabled (iso, syslinux, etc), I
only see it modifying configs/files under the boot-images/pxe/
hierarchy, so not sure how it would affect anything non-pxe related.

with bootserver=1.1.1.1 and bootprefix="test/":

```

root@tsbuild:/local/thinstation/thinstation-test (bootprefix)$ grep -r test/boot *
build/boot-images/pxe/boot/lpxelinux/pxelinux.cfg/default:	KERNEL http://1.1.1.1/test/boot/vmlinuz
build/boot-images/pxe/boot/lpxelinux/pxelinux.cfg/default:	APPEND initrd=http://1.1.1.1/test/boot/initrd  splash=verbose,theme:default  LM=3
build/boot-images/pxe/boot/pxelinux/pxelinux.cfg/default:	KERNEL ::/test/boot/vmlinuz
build/boot-images/pxe/boot/pxelinux/pxelinux.cfg/default:	APPEND initrd=::/test/boot/initrd  splash=verbose,theme:default  LM=3
build/boot-images/pxe/boot/efi64/pxelinux.cfg/default:	KERNEL http://1.1.1.1/test/boot/vmlinuz
build/boot-images/pxe/boot/efi64/pxelinux.cfg/default:	APPEND initrd=http://1.1.1.1/test/boot/initrd  splash=verbose,theme:default  LM=3
build/boot-images/pxe/boot/efi64/syslinux.cfg:	KERNEL http://1.1.1.1/test/boot/vmlinuz
build/boot-images/pxe/boot/efi64/syslinux.cfg:	APPEND initrd=http://1.1.1.1/test/boot/initrd  splash=verbose,theme:default  LM=3
build/boot-images/pxe/boot/efi32/pxelinux.cfg/default:	KERNEL http://1.1.1.1/test/boot/vmlinuz
build/boot-images/pxe/boot/efi32/pxelinux.cfg/default:	APPEND initrd=http://1.1.1.1/test/boot/initrd  splash=verbose,theme:default  LM=3
build/boot-images/pxe/boot/efi32/syslinux.cfg:	KERNEL http://1.1.1.1/test/boot/vmlinuz
build/boot-images/pxe/boot/efi32/syslinux.cfg:	APPEND initrd=http://1.1.1.1/test/boot/initrd  splash=verbose,theme:default  LM=3
ts/build/boot-images/pxe/boot/lpxelinux/pxelinux.cfg/default:	KERNEL http://1.1.1.1/test/boot/vmlinuz
ts/build/boot-images/pxe/boot/lpxelinux/pxelinux.cfg/default:	APPEND initrd=http://1.1.1.1/test/boot/initrd  splash=verbose,theme:default  LM=3
ts/build/boot-images/pxe/boot/pxelinux/pxelinux.cfg/default:	KERNEL ::/test/boot/vmlinuz
ts/build/boot-images/pxe/boot/pxelinux/pxelinux.cfg/default:	APPEND initrd=::/test/boot/initrd  splash=verbose,theme:default  LM=3
ts/build/boot-images/pxe/boot/efi64/pxelinux.cfg/default:	KERNEL http://1.1.1.1/test/boot/vmlinuz
ts/build/boot-images/pxe/boot/efi64/pxelinux.cfg/default:	APPEND initrd=http://1.1.1.1/test/boot/initrd  splash=verbose,theme:default  LM=3
ts/build/boot-images/pxe/boot/efi64/syslinux.cfg:	KERNEL http://1.1.1.1/test/boot/vmlinuz
ts/build/boot-images/pxe/boot/efi64/syslinux.cfg:	APPEND initrd=http://1.1.1.1/test/boot/initrd  splash=verbose,theme:default  LM=3
ts/build/boot-images/pxe/boot/efi32/pxelinux.cfg/default:	KERNEL http://1.1.1.1/test/boot/vmlinuz
ts/build/boot-images/pxe/boot/efi32/pxelinux.cfg/default:	APPEND initrd=http://1.1.1.1/test/boot/initrd  splash=verbose,theme:default  LM=3
ts/build/boot-images/pxe/boot/efi32/syslinux.cfg:	KERNEL http://1.1.1.1/test/boot/vmlinuz
ts/build/boot-images/pxe/boot/efi32/syslinux.cfg:	APPEND initrd=http://1.1.1.1/test/boot/initrd  splash=verbose,theme:default  LM=3

```

**Comment by Thinstation** [comment]
/boot/grub/pxeboot.img for BIOS/CSM
/EFI/boot/bootx64.efi for 64 bit
I guess I don't have EFI 32 bit setup......

**Comment by nneul** [comment]
Updated. Also added note to build.conf to call out the specific incompatibility with non-network grub boots.

**Comment by Thinstation** [comment]
Looks good. One little note, you need to make changes to
/build/conf/default/build.conf.example as well, as this will overwrite
/build/build.conf.example with every clean_chroot

**Comment by nneul** [comment]
Done.
