### ISSUE TITLE
spice-client-glib-usb-acl-helper is missing

### ISSUE THREAD

**Issue by grisuchris1** [Thinstation/thinstation#759]
After activating the Spice package.
The remote viewer works. But the USB redirection does not. Here comes the error message /usr/libexec/spice-client-glib-usb-acl-helper not found.

**Comment by Thinstation** [comment]
mkrepackage spice-gtk

Then add
package spice-gtk
to build.conf

**Comment by grisuchris1** [comment]
Thank you for the quick help. After I also run chmod u+s in the package folder for spice-client-glib-usb-acl-helper (setuid) it works perfectly
