### ISSUE TITLE
Chrome starting fullscreen

### ISSUE THREAD

**Issue by ssteinz** [Thinstation/thinstation#765]
Hey,

I got a question. When we start a chrome session on thinstation it always starts with the fullscreen flag. It creates a desktop icon with "pkg fullscreen Chrome "http://VM-NC-01/dashboard/room/2" "

SESSION_1_TITLE=test
SESSION_1_TYPE=chrome
SESSION_1_AUTOSTART=On
SESSION_1_ICON=On
SESSION_1_FULLSCREEN=Off
SESSION_1_CHROME_SERVER=http://VM-NC-01/dashboard/room/2

Can we force Chrome to start windowed mode? That it will start with "PKG window Chrome "http://VM-NC-01/dashboard/room/2" "

**Comment by Doncuppjr** [comment]
When you autostart a session, TS uses the global command to launch. For Chrome, that is fullscreen. You can edit here.

https://github.com/Thinstation/thinstation/blob/6.2-Stable/ts/build/packages/chrome/etc/cmd/chrome.global






On Monday, February 20, 2023 at 02:07:24 AM PST, ssteinz ***@***.***> wrote: 







Hey,

I got a question. When we start a chrome session on thinstation it always starts with the fullscreen flag. It creates a desktop icon with "pkg fullscreen Chrome "http://VM-NC-01/dashboard/room/2" "

SESSION_1_TITLE=test
SESSION_1_TYPE=chrome
SESSION_1_AUTOSTART=On
SESSION_1_ICON=On
SESSION_1_FULLSCREEN=Off
SESSION_1_CHROME_SERVER=http://VM-NC-01/dashboard/room/2

Can we force Chrome to start windowed mode? That it will start with "PKG window Chrome "http://VM-NC-01/dashboard/room/2" "

**Comment by ssteinz** [comment]
Thanks I will look into it
