### ISSUE TITLE
How to specify to install ports in build.conf?

### ISSUE THREAD

**Issue by nneul** [Thinstation/thinstation#767]
In particular, I'm looking to add the requests python port for python3 support. It appears to be in the build tree, but unclear how to tell to install when just running a build with:

`./setup-chroot -a -b -o --license ACCEPT --savedir --allmodules`

Is there any standard way to "run additional commands at end of build but prior to packaging into iso/bootimg/etc"? I'm working around this now by creating a custom package, but is there any "simple" option?

**Comment by Doncuppjr** [comment]
You can make a pip freeze file. See octoprint for an example of including some python packages in your build. 

https://github.com/Thinstation/thinstation/tree/6.2-Stable/ts/build/packages/octoprint/build


On Wednesday, March 29, 2023 at 08:45:21 AM MDT, Nathan Neulinger ***@***.***> wrote: 







In particular, I'm looking to add the requests python port for python3 support. It appears to be in the build tree, but unclear how to tell to install when just running a build with:

./setup-chroot -a -b -o --license ACCEPT --savedir --allmodules

Is there any standard way to "run additional commands at end of build but prior to packaging into iso/bootimg/etc"? I'm working around this now by creating a custom package, but is there any "simple" option?

**Comment by nneul** [comment]
That seemed to work nicely so far. Thank you!
