### ISSUE TITLE
Isolinux chokes on Older Machines

### ISSUE THREAD

**Issue by dundir** [Thinstation/thinstation#77]
Hello, this project looks very promising. 

I ran across this issue the other day while testing this on several older machines. I realize this issue is with ISOLinux however I thought you should be aware of it as well since it will impact users of this project if they are not aware of it, and have similar hardware to what I was using. 

The issue is that the bootloader (ISOLinux) would fail to boot and hang. 
The Motherboard was a G31T-M V1.0. AMI Bios release 2010. The CD-Rom drives were IDE cabled from Dell. The same issue occurs with the Optiplex 210L as well and most likely with the Dell Optiplex line motherboards older than Optiplex 320, and/or with their CD-Roms.

It is recommended in the FAQ to use the Smart Boot Manager bootloader as an alternative for these machines, unfortunately it was not entirely straightforward on how to successfully integrate this into a working Thinstation CD on these machines. Additionally it didn't help matters that there is a lot of misinformation out there when researching any solution related to bootable cd images. 

In the end I simply didn't have the time to pursue a solution further. I have included what I attempted in the hope it saves time for whoever is seeking a solution moving forward.

Several attempts were made with the Smart Boot Manager that failed,  the build appeared to be successful and would work on the newer machines with no issue, however; these specific machines would not boot, (hang).

The next promising solution was to use Grub4Dos to wrap the ISO but unfortunately this fails at the initrd stage which is understandable since it is an experimental feature and there appears to be a known issue addressing the device once the isolinux bootloader enters protected mode. 

This was very close and I feel like a solution might be forthcoming given enough time. It would boot and load the isolinux bootloader and vmlinuz kernel however it hangs at the initrd phase which is more than any other solution I tried.

Varying configurations below were attempted to bypass this issue, however; none worked: 

For devices, hd32 and 0xFF were tried, the +1 syntax was tried for chainloader (both omitting boot and including) to load the entire partition. map --mem was also attempted once to determine if the boot issue was due to non-contiguous files, it was not.

Title Thinstation
map (bd)/TS.iso (hd32)
map --hook
root (hd32)
chainloader (hd32)
boot //removed for chainloader+1

Best Regards,
D.

**Comment by Thinstation** [comment]
How big is the initrd of these failing machines?

**Comment by Thinstation** [comment]
Are these machines 64 bit?

**Comment by dundir** [comment]
IIRC the machines had 512MB of RAM, and were x86 Dell Workstations. They
were manufactured cerca 2006-8, It was a common issue with isolinux
specific to older hardware right around the time HDD sizes were increasing
from 512 bytes per sector to 4K. The hardware has since been replaced so is
no longer an issue for us.
