### ISSUE TITLE
View Horizon Client 2303 - libstdc

### ISSUE THREAD

**Issue by rohrbachger** [Thinstation/thinstation#770]
I tried the actual view horizon client.
It installs, but when I call I`m getting some error messages.
libstdc++.so.6 version GLIBCXX_3.4.29 not found
libstdc++.so.6 version GLIBCXX_3.4.30 not found
libstdc++.so.6 version CXXABI_1.3.13 not found

Vmware did a lo of updates, the support for Ubuntu 18 ended.

How I can update this library?

**Comment by Thinstation** [comment]
Update glibc

**Comment by rohrbachger** [comment]
with my limited knowledge I changed under /ts/ports/core/glibc the version to 2.36
pkgmk -um fixed the md5 sum error 
pkgmk -i -d  downloaded the file and started doing a lot

but
=======> ERROR: Footprint mismatch found:
some lines later
=======> ERROR: Building '/ts/ports/core/glibc/glibc#2.36-1.pkg.tar.xz' failed
Is that version maybe to new and has some other dependencies?

Where is the place to look what the error is? 

Is that the right way I did?

**Comment by Thinstation** [comment]
Pkgmk -uf #update footprint, will need to clean_chroot afterwards.

**Comment by rohrbachger** [comment]
Yes those steps worked now
I did a clean_chroot
I exit the build env and started setup-chroot again.
Maybe this was wrong! The new glibc under ports disappeared

It did the initial setup after this, this reset also my build.conf and all the rest.
Also the port update I did.

 After creating a new image I get still the libstdc error message when starting view client.
But this is clear, I wiped my changes .
The clean_chroot I probably need to do in a different way or additional step.

**Comment by Doncuppjr** [comment]
Hmmmm, the clean_chroot should have preserved the port update. Did you do a git checkout too?


Sent from Yahoo Mail for iPhone


On Wednesday, April 5, 2023, 11:56 AM, rohrbachger ***@***.***> wrote:




Yes those steps worked now
I did a clean_chroot
I exit the build env and started setup-chroot again.
Maybe this was wrong! The new glibc under ports disappeared

It did the initial setup after this, this reset also my build.conf and all the rest.
Also the port update I did.

After creating a new image I get still the libstdc error message when starting view client.
But this is clear, I wiped my changes .
The clean_chroot I probably need to do in a different way or additional step.

**Comment by rohrbachger** [comment]
I'm using ubuntu 22.04 on hardware and just git clone . No git checkout

**Comment by Thinstation** [comment]
I don’t know why the env would reset then. Are your changes present in the
Pkgfile? Maybe you need to make sure the port gets installed after the
compile before the clean.

**Comment by rohrbachger** [comment]
Another try, different way.
git clone --depth 1 https://github.com/Thinstation/thinstation.git
cd thinstation/ts/core/glibc
change in the pkg file the version and copy the downloaded file in this folder, deleted the old one.
version=2.36
start setup-chroot

strings /usr/lib/libstdc++.so.6 | grep GLIBC
still not showing newer versions.
.......
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
......
Thats in /usr/lib, so old version still
rwxr-xr-x   1 root root     39592 Sep  3  2019 libstartup-notification-1.so.0.0.0
-rw-r--r--   1 root root   4921440 Jun 18  2021 libstd-4f09a0a416e0f37c.so
-rw-r--r--   1 root root   5744034 Jun 17  2021 libstdc++.a
-rwxr-xr-x   1 root root       957 Jun 17  2021 libstdc++.la
lrwxrwxrwx   1 root root        19 Jun 17  2021 libstdc++.so -> libstdc++.so.6.0.28
lrwxrwxrwx   1 root root        19 Jun 17  2021 libstdc++.so.6 -> libstdc++.so.6.0.28
-rwxr-xr-x   1 root root   1874536 Jun 17  2021 libstdc++.so.6.0.28

**Comment by Doncuppjr** [comment]
prt-get update -fr -im -if -is glibc

Sent from Yahoo Mail for iPhone


On Thursday, April 6, 2023, 11:29 AM, rohrbachger ***@***.***> wrote:




Another try, different way.
git clone --depth 1 https://github.com/Thinstation/thinstation.git
cd thinstation/ts/core/glibc
change in the pkg file the version and copy the downloaded file in this folder, deleted the old one.
version=2.36
start setup-chroot

strings /usr/lib/libstdc++.so.6 | grep GLIBC
still not showing newer versions.
.......
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
......
Thats in /usr/lib, so old version still
rwxr-xr-x 1 root root 39592 Sep 3 2019 libstartup-notification-1.so.0.0.0
-rw-r--r-- 1 root root 4921440 Jun 18 2021 libstd-4f09a0a416e0f37c.so
-rw-r--r-- 1 root root 5744034 Jun 17 2021 libstdc++.a
-rwxr-xr-x 1 root root 957 Jun 17 2021 libstdc++.la
lrwxrwxrwx 1 root root 19 Jun 17 2021 libstdc++.so -> libstdc++.so.6.0.28
lrwxrwxrwx 1 root root 19 Jun 17 2021 libstdc++.so.6 -> libstdc++.so.6.0.28
-rwxr-xr-x 1 root root 1874536 Jun 17 2021 libstdc++.so.6.0.28

**Comment by rohrbachger** [comment]
Still no success

strings /usr/lib/libstdc++.so.6 | grep GLIBC
still not showing newer versions.

Is libstdc++ updated with glibc? Maybe this is the wrong package?

**Comment by Doncuppjr** [comment]
Yeah, might be part of Gcc. Prt-get fsearch libstdc\*


Sent from Yahoo Mail for iPhone


On Friday, April 7, 2023, 11:43 AM, rohrbachger ***@***.***> wrote:




Still no success

strings /usr/lib/libstdc++.so.6 | grep GLIBC
still not showing newer versions.

Is libstdc++ updated with glibc? Maybe this is the wrong package?

**Comment by rohrbachger** [comment]
Is TS is based on CRUX3.6 somehow?
CRUX 3.7 comes with a multilib toolchain which includes glibc 2.36, gcc 12.2.0 and binutils 2.39
This sounds like some work...
I would like to learn and spend some time with this. Did you planned any update in this direction?

I tried , and found that there is an issue with pkgmk 
From Crux....
pkgmk now defines LC_ALL=C.UTF-8 instead of LC_ALL=POSIX. This should avoid errors like: bsdtar: Pathname can’t be converted from UTF-8 to current locale

That`s the message coming when I try to pkgmk -i -d
=======> Building '/ts/ports/core/gcc/gcc#12.2.0-1.pkg.tar.xz'.
bsdtar -p -o -C /ts/ports/core/gcc/work/src -xf /ts/ports/core/gcc/isl-0.26.tar.bz2
bsdtar -p -o -C /ts/ports/core/gcc/work/src -xf /ts/ports/core/gcc/gcc-12.2.0.tar.xz
bsdtar: Pathname can't be converted from UTF-8 to current locale.
bsdtar: Pathname can't be converted from UTF-8 to current locale.
bsdtar: Error exit delayed from previous errors.
=======> ERROR: Building '/ts/ports/core/gcc/gcc#12.2.0-1.pkg.tar.xz' failed.

**Comment by Doncuppjr** [comment]
TS forked from CRUX back at 3.0. Since then it’s just been a reference. You can set the locale to whatever you want, but a UTF8 one makes sense.


Sent from Yahoo Mail for iPhone


On Saturday, April 8, 2023, 11:47 AM, rohrbachger ***@***.***> wrote:




Is TS is based on CRUX3.6 somehow?
CRUX 3.7 comes with a multilib toolchain which includes glibc 2.36, gcc 12.2.0 and binutils 2.39
This sounds like some work...
I would like to learn and spend some time with this. Did you planned any update in this direction?

I tried , and found that there is an issue with pkgmk
From Crux....
pkgmk now defines LC_ALL=C.UTF-8 instead of LC_ALL=POSIX. This should avoid errors like: bsdtar: Pathname can’t be converted from UTF-8 to current locale

That`s the message coming when I try to pkgmk -i -d
=======> Building '/ts/ports/core/gcc/gcc#12.2.0-1.pkg.tar.xz'.
bsdtar -p -o -C /ts/ports/core/gcc/work/src -xf /ts/ports/core/gcc/isl-0.26.tar.bz2
bsdtar -p -o -C /ts/ports/core/gcc/work/src -xf /ts/ports/core/gcc/gcc-12.2.0.tar.xz
bsdtar: Pathname can't be converted from UTF-8 to current locale.
bsdtar: Pathname can't be converted from UTF-8 to current locale.
bsdtar: Error exit delayed from previous errors.
=======> ERROR: Building '/ts/ports/core/gcc/gcc#12.2.0-1.pkg.tar.xz' failed.

**Comment by rohrbachger** [comment]
Tried that, but no success (yet)
Changed TS_ENV
export TSVER=6.2
export TSWRKNG=/ts/build
export TSPKGROOT=ts/build/packages
export TSCOMPROOT=ts/components

export LANG=C.UTF-8
export LANGUAGE=C.UTF-8
export LC_ALL=C.UTF-8

I did not figured out yet, my understanding is I have to generate C.UTF-8

[root@TS_chroot]/# locale 
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=C.UTF-8
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=C.UTF-8


That`s the message coming when I try to pkgmk -i -d
=======> Building '/ts/ports/core/gcc/gcc#12.2.0-1.pkg.tar.xz'.
bsdtar -p -o -C /ts/ports/core/gcc/work/src -xf /ts/ports/core/gcc/isl-0.26.tar.bz2
bsdtar -p -o -C /ts/ports/core/gcc/work/src -xf /ts/ports/core/gcc/gcc-12.2.0.tar.xz
bsdtar: Pathname can't be converted from UTF-8 to current locale.
bsdtar: Pathname can't be converted from UTF-8 to current locale.

**Comment by Thinstation** [comment]
You have to create the locale first with localedef

**Comment by rohrbachger** [comment]
I tried a lot but nothing helped. 

The problem is because of line (near to end)  of pkgmk:
export LC_ALL=POSIX

Without this line it extracts without errors.
I found this hint, and  yes now files are extracted, I´m running now in a problem with isl,
but probably I need the right version for compiling only. I used 026 for gcc 12.2.

**Comment by Thinstation** [comment]
Congratulations.

**Comment by rohrbachger** [comment]
After compiling some hours unfortunately an error... Only a little bit success
libstdc++.so.6 is not created, the old one seems to be deleted.


root@TS_chroot]/ts/ports/core/gcc# pkgmk -i -u
=======> Package '/ts/ports/core/gcc/gcc#12.2.0-1.pkg.tar.xz' is up to date.
=======> Installing '/ts/ports/core/gcc/gcc#12.2.0-1.pkg.tar.xz'.
pkgadd -u /ts/ports/core/gcc/gcc#12.2.0-1.pkg.tar.xz
/usr/bin/pkgmk: line 583:  5600 Floating point exception(core dumped) $COMMAND
=======> ERROR: Installing '/ts/ports/core/gcc/gcc#12.2.0-1.pkg.tar.xz' failed.

pkgmk Line 583
install_package() {
	local COMMAND

	info "Installing '$TARGET'."

	if [ "$PKGMK_INSTALL" = "install" ]; then
		COMMAND="pkgadd $TARGET"
	else
		COMMAND="pkgadd -u $TARGET"
	fi

	cd $PKGMK_ROOT
	echo "$COMMAND"
	$COMMAND

	if [ $? = 0 ]; then
		info "Installing '$TARGET' succeeded."
	else
		error "Installing '$TARGET' failed."
		exit 1
	fi
}

**Comment by Thinstation** [comment]
Maybe RAM again. Try unwinding manually.

**Comment by rohrbachger** [comment]
I did on different machines, same effect.
What means unwinding, how to do?

Parallel I will now clone the source again, and try to build the package gcc with all the original files and settings.
This should work. 
Also I will try to analyse the install script of gcc 12.2. In which folder all the compiling / linking files are stored?

**Comment by rohrbachger** [comment]
Hipp, hipp, hooray,
I hope I can reproduce it once.... ( currently I do not know exactly why it worked)
GCC 12.2 compiled, installed
libstdc++ is updated automatically

Horzion View Client 2303 installed, works now.

So I will try the build again and will document the steps.
That was a good learning lesson.

**Comment by Doncuppjr** [comment]
ThinStation was my teacher for sure.


Sent from Yahoo Mail for iPhone


On Saturday, April 15, 2023, 6:03 AM, rohrbachger ***@***.***> wrote:




Hipp, hipp, hooray,
I hope I can reproduce it once.... ( currently I do not know exactly why it worked)
GCC 12.2 compiled, installed
libstdc++ is updated automatically

Horzion View Client 2303 installed, works now.

So I will try the build again and will document the steps.
That was a good learning lesson.
