### ISSUE TITLE
update rdesktop to 1.8.3 and ccid to 1.4.19

### ISSUE THREAD

**Issue by trentasis** [Thinstation/thinstation#78]
Please update rdesktop and ccid to latest versions in Pkgfile, this contains solved bugs.

Thanks

**Comment by trentasis** [comment]
I have updated rdesktop using:
 /ts/ports/contrib/rdesktop 
		cp Pkgfile Pkgfile.orig
		Double click "Pkgfile" , it will be opened by "geany" editor 
		change "version=1.8.2" to "version=1.8.3"
		add --without-sound (ull \ a la línai prèvia)  and save file, exit. 
		open Terminal Chroot, Q 
		cd /ts/ports/contrib/rdesktop 
		pkgmk -u -d -um 
		pkgmk -u 
		pkgmk -uf 
		pkgmk -u 
		update rdesktop 

And works perfect


Now I'm trying to upgrade ccid to latest versions 1.4.19 with same steps but we have problems we receive this error during  first pkgmk -u 

***************

copy the src/92_pcscd_ccid.rules file in udev directory (/etc/udev/rules.d/)

***************

make[1]: Leaving directory '/ts/ports/components/ccid/work/src/ccid-1.4.19/src'
make[1]: Entering directory '/ts/ports/components/ccid/work/src/ccid-1.4.19'
make[2]: Entering directory '/ts/ports/components/ccid/work/src/ccid-1.4.19'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/ts/ports/components/ccid/work/src/ccid-1.4.19'
make[1]: Leaving directory '/ts/ports/components/ccid/work/src/ccid-1.4.19'
+ mkdir -p /ts/ports/components/ccid/work/pkg/etc/udev
+ mkdir -p /ts/ports/components/ccid/work/pkg/usr/bin /ts/ports/components/ccid/work/pkg/usr/sbin
+ cp src/92_pcscd_ccid.rules /ts/ports/components/ccid/work/pkg/etc/udev/.
+ cp contrib/Kobil_mIDentity_switch/Kobil_mIDentity_switch /ts/ports/components/ccid/work/pkg/usr/sbin/.
+ cp contrib/RSA_SecurID/RSA_SecurID_getpasswd /ts/ports/components/ccid/work/pkg/usr/bin/.
=======> Build result:
drwxr-xr-x  0 root   root        0 Jul 27 09:22 etc/
drwxr-xr-x  0 root   root        0 Jul 27 09:22 etc/udev/
-rw-r--r--  0 root   root      711 Jul 27 09:22 etc/udev/92_pcscd_ccid.rules
drwxr-xr-x  0 root   root        0 Jul 27 09:22 usr/
drwxr-xr-x  0 root   root        0 Jul 27 09:22 usr/lib/
drwxr-xr-x  0 root   root        0 Jul 27 09:22 usr/sbin/
drwxr-xr-x  0 root   root        0 Jul 27 09:22 usr/bin/
-rwxr-xr-x  0 root   root     5776 Jul 27 09:22 usr/bin/RSA_SecurID_getpasswd
-rwxr-xr-x  0 root   root     5376 Jul 27 09:22 usr/sbin/Kobil_mIDentity_switch
drwxr-xr-x  0 root   root        0 Jul 27 09:22 usr/lib/pcsc/
drwxr-xr-x  0 root   root        0 Jul 27 09:22 usr/lib/pcsc/drivers/
drwxr-xr-x  0 root   root        0 Jul 27 09:22 usr/lib/pcsc/drivers/ifd-ccid.bundle/
drwxr-xr-x  0 root   root        0 Jul 27 09:22 usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/
drwxr-xr-x  0 root   root        0 Jul 27 09:22 usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Linux/
-rw-r--r--  0 root   root    32845 Jul 27 09:22 usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Info.plist
-rwxr-xr-x  0 root   root   105188 Jul 27 09:22 usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Linux/libccid.so
=======> ERROR: Footprint mismatch found:
MISSING   drwxr-xr-x      root/root       bin/
MISSING   -rwxr-xr-x      root/root       bin/RSA_SecurID_getpasswd
MISSING   drwxr-xr-x      root/root       sbin/
MISSING   -rwxr-xr-x      root/root       sbin/Kobil_mIDentity_switch
NEW       drwxr-xr-x      root/root       usr/bin/
NEW       -rwxr-xr-x      root/root       usr/bin/RSA_SecurID_getpasswd
NEW       drwxr-xr-x      root/root       usr/sbin/
NEW       -rwxr-xr-x      root/root       usr/sbin/Kobil_mIDentity_switch
=======> ERROR: Building '/ts/ports/components/ccid/ccid#1.4.19-1.pkg.tar.gz' failed.


then with nexts steps we receive:


[root@TS_chroot]/ts/ports/components/ccid# pkgmk -uf
=======> Footprint updated.

[root@TS_chroot]/ts/ports/components/ccid# pkgmk -u
=======> Package '/ts/ports/components/ccid/ccid#1.4.19-1.pkg.tar.gz' is up to date.
=======> Installing '/ts/ports/components/ccid/ccid#1.4.19-1.pkg.tar.gz'.
pkgadd -u /ts/ports/components/ccid/ccid#1.4.19-1.pkg.tar.gz
pkgadd: rejecting etc/udev/92_pcscd_ccid.rules, keeping existing version
=======> Installing '/ts/ports/components/ccid/ccid#1.4.19-1.pkg.tar.gz' succeeded.



What are the correct steps to update ccid to 1.4.19 from a 1.4.18 version? Can you update on master branch?

Thanks

**Comment by Doncuppjr** [comment]
It looks to me like you succeeded to at least compile the new ports. Good job. The last step is to update the packages with the new files.
update rdesktopupdate ccidreader 


     On Monday, July 27, 2015 7:28 AM, trentasis <notifications@github.com> wrote:
   

 I have updated rdesktop using:
 /ts/ports/contrib/rdesktop 
 cp Pkgfile Pkgfile.orig
 Double click "Pkgfile" , it will be opened by "geany" editor 
 change "version=1.8.2" to "version=1.8.3"
 add --without-sound (ull \ a la línai prèvia) and save file, exit. 
 open Terminal Chroot, Q 
 cd /ts/ports/contrib/rdesktop 
 pkgmk -u -d -um 
 pkgmk -u 
 pkgmk -uf 
 pkgmk -u 
 update rdesktop And works perfectNow I'm trying to upgrade ccid to latest versions 1.4.19 with same steps but we have problems we receive this error during first pkgmk -u copy the src/92_pcscd_ccid.rules file in udev directory (/etc/udev/rules.d/)make[1]: Leaving directory '/ts/ports/components/ccid/work/src/ccid-1.4.19/src'
make[1]: Entering directory '/ts/ports/components/ccid/work/src/ccid-1.4.19'
make[2]: Entering directory '/ts/ports/components/ccid/work/src/ccid-1.4.19'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/ts/ports/components/ccid/work/src/ccid-1.4.19'
make[1]: Leaving directory '/ts/ports/components/ccid/work/src/ccid-1.4.19'   
   - mkdir -p /ts/ports/components/ccid/work/pkg/etc/udev
   - mkdir -p /ts/ports/components/ccid/work/pkg/usr/bin /ts/ports/components/ccid/work/pkg/usr/sbin
   - cp src/92_pcscd_ccid.rules /ts/ports/components/ccid/work/pkg/etc/udev/.
   - cp contrib/Kobil_mIDentity_switch/Kobil_mIDentity_switch /ts/ports/components/ccid/work/pkg/usr/sbin/.
   - cp contrib/RSA_SecurID/RSA_SecurID_getpasswd /ts/ports/components/ccid/work/pkg/usr/bin/.=======> Build result:drwxr-xr-x 0 root root 0 Jul 27 09:22 etc/drwxr-xr-x 0 root root 0 Jul 27 09:22 etc/udev/-rw-r--r-- 0 root root 711 Jul 27 09:22 etc/udev/92_pcscd_ccid.rulesdrwxr-xr-x 0 root root 0 Jul 27 09:22 usr/drwxr-xr-x 0 root root 0 Jul 27 09:22 usr/lib/drwxr-xr-x 0 root root 0 Jul 27 09:22 usr/sbin/drwxr-xr-x 0 root root 0 Jul 27 09:22 usr/bin/-rwxr-xr-x 0 root root 5776 Jul 27 09:22 usr/bin/RSA_SecurID_getpasswd-rwxr-xr-x 0 root root 5376 Jul 27 09:22 usr/sbin/Kobil_mIDentity_switchdrwxr-xr-x 0 root root 0 Jul 27 09:22 usr/lib/pcsc/drwxr-xr-x 0 root root 0 Jul 27 09:22 usr/lib/pcsc/drivers/drwxr-xr-x 0 root root 0 Jul 27 09:22 usr/lib/pcsc/drivers/ifd-ccid.bundle/drwxr-xr-x 0 root root 0 Jul 27 09:22 usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/drwxr-xr-x 0 root root 0 Jul 27 09:22 usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Linux/-rw-r--r-- 0 root root 32845 Jul 27 09:22 usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Info.plist-rwxr-xr-x 0 root root 105188 Jul 27 09:22 usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Linux/libccid.so=======> ERROR: Footprint mismatch found:MISSING drwxr-xr-x root/root bin/MISSING -rwxr-xr-x root/root bin/RSA_SecurID_getpasswdMISSING drwxr-xr-x root/root sbin/MISSING -rwxr-xr-x root/root sbin/Kobil_mIDentity_switchNEW drwxr-xr-x root/root usr/bin/NEW -rwxr-xr-x root/root  usr/bin/RSA_SecurID_getpasswdNEW drwxr-xr-x root/root usr/sbin/NEW -rwxr-xr-x root/root usr/sbin/Kobil_mIDentity_switch=======> ERROR: Building '/ts/ports/components/ccid/ccid#1.4.19-1.pkg.tar.gz' failed.
then with nexts steps we receive:[root@TS_chroot]/ts/ports/components/ccid# pkgmk -uf
=======> Footprint updated.[root@TS_chroot]/ts/ports/components/ccid# pkgmk -u
=======> Package '/ts/ports/components/ccid/ccid#1.4.19-1.pkg.tar.gz' is up to date.
=======> Installing '/ts/ports/components/ccid/ccid#1.4.19-1.pkg.tar.gz'.
pkgadd -u /ts/ports/components/ccid/ccid#1.4.19-1.pkg.tar.gz
pkgadd: rejecting etc/udev/92_pcscd_ccid.rules, keeping existing version
=======> Installing '/ts/ports/components/ccid/ccid#1.4.19-1.pkg.tar.gz' succeeded.What are the correct steps to update ccid to 1.4.19 from a 1.4.18 version? Can you update on master branch?Thanks—

**Comment by trentasis** [comment]
Hi,

rdesktop updated and working perfects.

with ccid not sure, we receive some errors during compilation, for example as it was described in last comment:

error or warning 1:
***************

copy the src/92_pcscd_ccid.rules file in udev directory (/etc/udev/rules.d/)

***************

error 2:
drwxr-xr-x  0 root   root        0 Jul 27 09:22 usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Linux/
-rw-r--r--  0 root   root    32845 Jul 27 09:22 usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Info.plist
-rwxr-xr-x  0 root   root   105188 Jul 27 09:22 usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Linux/libccid.so
=======> ERROR: Footprint mismatch found:
MISSING   drwxr-xr-x      root/root       bin/
MISSING   -rwxr-xr-x      root/root       bin/RSA_SecurID_getpasswd
MISSING   drwxr-xr-x      root/root       sbin/
MISSING   -rwxr-xr-x      root/root       sbin/Kobil_mIDentity_switch
NEW       drwxr-xr-x      root/root       usr/bin/
NEW       -rwxr-xr-x      root/root       usr/bin/RSA_SecurID_getpasswd
NEW       drwxr-xr-x      root/root       usr/sbin/
NEW       -rwxr-xr-x      root/root       usr/sbin/Kobil_mIDentity_switch
=======> ERROR: Building '/ts/ports/components/ccid/ccid#1.4.19-1.pkg.tar.gz' failed.


Warning 3:
92_pcscd_ccid_rules deeping previous version:
 pkgmk -u
=======> Package '/ts/ports/components/ccid/ccid#1.4.19-1.pkg.tar.gz' is up to date.
=======> Installing '/ts/ports/components/ccid/ccid#1.4.19-1.pkg.tar.gz'.
pkgadd -u /ts/ports/components/ccid/ccid#1.4.19-1.pkg.tar.gz
pkgadd: rejecting etc/udev/92_pcscd_ccid.rules, keeping existing version
=======> Installing '/ts/ports/components/ccid/ccid#1.4.19-1.pkg.tar.gz' succeeded.


update ccidreader was made, but we receive this 3 errors and we need to ensure that all is compiled correctly.

Can you detail how to recompile ccid without errors? or a best option, upgrade PKgfile and then I'll try to recompile from new source?

Thanks

**Comment by Doncuppjr** [comment]
It looks like they moved some things to /usr, no biggie. just pkgmk -uf to update the footprint. I doubt that anything changed in the rules file, but you could remove the etc/udev/92_pcscd_ccid.rules manually, before doing pkgmk -u to get around the issue.



On Tuesday, July 28, 2015 12:16 AM, trentasis <notifications@github.com> wrote:



Hi,
rdesktop updated and working perfects.
with ccid not sure, we receive some errors during compilation, for example as it was described in last comment:
error or warning 1:
________________________________

copy the src/92_pcscd_ccid.rules file in udev directory (/etc/udev/rules.d/)
________________________________

error 2:
drwxr-xr-x  0 root  root      0 Jul 27 09:22 usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Linux/
-rw-r--r--  0 root  root   32845 Jul 27 09:22 usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Info.plist
-rwxr-xr-x  0 root  root  105188 Jul 27 09:22 usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Linux/libccid.so
=======> ERROR: Footprint mismatch found:
MISSING  drwxr-xr-x    root/root     bin/
MISSING  -rwxr-xr-x    root/root     bin/RSA_SecurID_getpasswd
MISSING  drwxr-xr-x    root/root     sbin/
MISSING  -rwxr-xr-x    root/root     sbin/Kobil_mIDentity_switch
NEW     drwxr-xr-x    root/root     usr/bin/
NEW     -rwxr-xr-x    root/root     usr/bin/RSA_SecurID_getpasswd
NEW     drwxr-xr-x    root/root     usr/sbin/
NEW     -rwxr-xr-x    root/root     usr/sbin/Kobil_mIDentity_switch
=======> ERROR: Building '/ts/ports/components/ccid/ccid#1.4.19-1.pkg.tar.gz' failed.
Warning 3:
92_pcscd_ccid_rules deeping previous version:
pkgmk -u
=======> Package '/ts/ports/components/ccid/ccid#1.4.19-1.pkg.tar.gz' is up to date.
=======> Installing '/ts/ports/components/ccid/ccid#1.4.19-1.pkg.tar.gz'.
pkgadd -u /ts/ports/components/ccid/ccid#1.4.19-1.pkg.tar.gz
pkgadd: rejecting etc/udev/92_pcscd_ccid.rules, keeping existing version
=======> Installing '/ts/ports/components/ccid/ccid#1.4.19-1.pkg.tar.gz' succeeded.
update ccidreader was made, but we receive this 3 errors and we need to ensure that all is compiled correctly.
Can you detail how to recompile ccid without errors? or a best option, upgrade PKgfile and then I'll try to recompile from new source?
Thanks

**Comment by Thinstation** [comment]
Done
