### ISSUE TITLE
freerdp /u, /p parameter issue

### ISSUE THREAD

**Issue by matreicht** [Thinstation/thinstation#780]
Hi,

I wanted to create a thinclient that runs freerdp on the start, fills out username and password, ignores certificates and connects to remote windows server. I used the following configuration options in the thinstation.conf.buildtime file to achieve this:
SESSION_0_TITLE="RDP"
SESSION_0_TYPE=freerdp
SESSION_0_FREERDP_SERVER="IPADDR"
SESSION_0_FREERDP_OPTIONS="/u:USER /p:PASSWORD /cert-ignore"
SESSION_0_AUTOSTART=ON
Unfortunately the username and password are not being filled out for some reason, the server ip and the ignore certificates part works fine.
If i run the command from terminal like:
xfreerdp /v:ip_address /u:username /p:password /cert:ignore
I can connect just fine, but i want thinclient to do this on it's own.
Any ideas what the solution may be?

**Comment by Doncuppjr** [comment]
Try this

SESSION_0_TITLE="RDP"
SESSION_0_TYPE=freerdp
SESSION_0_FREERDP_SERVER="IPADDR"
SESSION_0_FREERDP_OPTIONS="/p:PASSWORD /cert-ignore"
SESSION_0_AUTOSTART=ON
SESSION_0_FREERDP_USER="user"
SESSION_0_FREERDP_PASS_ENABLE=false

**Comment by matreicht** [comment]
Thanks for the quick answer, it works like this!
