### ISSUE TITLE
Thinstation + VMview. Sound interruptions.

### ISSUE THREAD

**Issue by simonzsay** [Thinstation/thinstation#783]
Colleagues, I'm making a lightweight image, where there is nothing except the Horizon Client. With the exception of some small things, everything that I need works perfect. However, I can't fix the audio stability in video and some web applications.

I'm testing on YouTube or, for example, making a voice call in one web messenger, I observe short freezes / interruptions + the browser starts to freeze, but just a little. The video plays stably. Interestingly, cursor movements also cause similar sound problems. If the mouse is not touched, then the sound hangs a little less often. At the same time, any office software that were installed on the server works well.

Given:
Many-many Intel de3815tyke
Assembly with thinstation 6.2.13.
Out of the box TS comes with VMware-Horizon-Client-2111-8.4.0-18957622.x64.bundle (all installation keys with "no")
The server has the latest Horizon Agent.

I'm attaching the configs. In short - from the beginning with allmodules, then with hwlister. Then a specific assembly. 

By the way, on average laptops with the same versions of the client (both from Linux and from Windows), everything works without problems at all - sound, video, microphone, etc. Do I have an old thin clients ? Drivers?

Can you tell me how to fix my problem?
Configs:
[Thinstation Horizon.zip](https://github.com/Thinstation/thinstation/files/12410877/Thinstation.Horizon.zip)

**Comment by rohrbachger** [comment]
We are using TS with Vmware Horizon too.
Latest rollled out client is: 2212.1-8.8.1, I think that should work in standard environment TS.
Currently I'm trying to get a newer version installed.
The 2303-8.9.0 needs a newer gcc version, I figured that out to get it running, but I did not rolled out for user tests.
The 2306.8.10 does not install in general in TS, so it will take time to figure this out.
We are using Dell Optiplex 790, and Lenovo. Lenovo with only 2 cores have obviously not enough power for videos.

**Comment by simonzsay** [comment]
All my problems really was because of extremely old park of thin clients. I was able to make tests with numerous brand new machines and stopped at Intel NUC 11 Essential Kit Atlas Canyon Celeron N5105 BNUC11ATKC40000 (not advertising). For the most part, the choice is determined by the reasonable price offer in my region, but in global market there are a lot of vendors who offer similar machines. So, watching fullHD video and meetings in Zoom/etc became very comfortable.

Assembly with thinstation 6.2.13.
VMware-Horizon-Client-2111-8.4.0-18957622.x64.bundle
The latest Horizon Agent 2306

**Comment by rohrbachger** [comment]
Probably you are not too familiar with Thinstation yet.
We have an environment with about 100 thinstation running HorizonView 8.
Our experience is to use a new client especially Teams , Video where improved  a lot.

It's no big deal to get a newer horizon client installed.
We are using PXE Boot, so nothing is installed on the ThinClients. We have Lenovo and Dell Hardwae in use,
the ISO Image is the same for the different models.
The stations are setup for PXE boot,Windows DHPC Server, but the ISO Image is served by an ubuntu server.

Rolling out a new version is simple, and with the TS possibility you can rollout to each hardware an different image.

Sure, in the moment you can not use the 2306 version in TS. I'm working on this, looks not bad.
But it's really no big deal to get the VMware-Horizon-Client-2212-8.8.0-21079016.x64.bundle installed.

If your are interested, I can assist you. Let me know how many ThinClients you have to get an idea of the environemnt.
