### ISSUE TITLE
Change the upload image

### ISSUE THREAD

**Issue by shurik8129** [Thinstation/thinstation#792]
How to change the upload image in "initrd"

**Comment by Doncuppjr** [comment]
That’s literally what the TS build system does.


Sent from Yahoo Mail for iPhone


On Thursday, October 5, 2023, 4:13 AM, shurik8129 ***@***.***> wrote:




How to change the upload image in "initrd"

**Comment by shurik8129** [comment]
is it possible to do this in an already created image?

**Comment by Doncuppjr** [comment]
Yes, but you need skills.


Sent from Yahoo Mail for iPhone


On Thursday, October 5, 2023, 7:42 PM, shurik8129 ***@***.***> wrote:




is it possible to do this in an already created image?
