### ISSUE TITLE
Trying to install drivers for a New PC

### ISSUE THREAD

**Issue by VolksDude** [Thinstation/thinstation#797]
Hey guys
Love the project. It has been working great, but I’ve been trying to push the envelope.
I would like to run Thinstation on a Dell optiplex micro plus 7010. It’s a 13th Gen i7 with the Intel UHD Graphics.
I’ve tried running it on our current setup with Horizon. First, it looks like the Video Driver is not loading properly. In display settings, instead of saying my display type, I just get “Default”. The wallpaper doesn’t even load.
Next, I’m able to login to Horizon, but video performance is very poor. I’m assuming h264 decoding is not happening since the latest video driver is not loaded. 
the system PXE boots perfectly.

I tried downloading and installing mesa package with no success. Doesn’t seem like it’s getting added to the image. I can’t find proper documentation to do this.

Can someone help?
Thanks

**Comment by Doncuppjr** [comment]
Possibly a new kernel is needed. Try an allmodules build, and include all the xorg packages as well 
Sent from Yahoo Mail for iPhone


On Tuesday, November 21, 2023, 3:54 PM, VolksDude ***@***.***> wrote:




Hey guys
Love the project. It has been working great, but I’ve been trying to push the envelope.
I would like to run Thinstation on a Dell optiplex micro plus 7010. It’s a 13th Gen i7 with the Intel UHD Graphics.
I’ve tried running it on our current setup with Horizon. First, it looks like the Video Driver is not loading properly. In display settings, instead of saying my display type, I just get “Default”. The wallpaper doesn’t even load.
Next, I’m able to login to Horizon, but video performance is very poor. I’m assuming h264 decoding is not happening since the latest video driver is not loaded.
the system PXE boots perfectly.

I tried downloading and installing mesa package with no success. Doesn’t seem like it’s getting added to the image. I can’t find proper documentation to do this.

Can someone help?
Thanks

**Comment by VolksDude** [comment]
Just tried and same result.
Kernel version getting loaded is 5.15.51TS
I'm assuming that's the latest available with ThinStation?

**Comment by VolksDude** [comment]
I was able to replicate the problem on a VM instead.

If I configure my Test Thin VM with BIOS (Legacy) Boot, everything starts fine. I even get the wallpaper to load.
If I configure my Test Thin VM with EFI, It boots, but I do not get the wallpaper and the display says "default". Same Build.conf and thinstation.conf.buildtime.

I've tried allmodules and all xorg packages.

Any ideas?

**Comment by Doncuppjr** [comment]
Interesting observation. I will take a look.
    On Friday, November 24, 2023 at 06:42:25 AM MST, VolksDude ***@***.***> wrote:  
 
 


I was able to replicate the problem on a VM instead.

If I configure my Test Thin VM with BIOS (Legacy) Boot, everything starts fine. I even get the wallpaper to load.
If I configure my Test Thin VM with EFI, It boots, but I do not get the wallpaper and the display says "default". Same Build.conf and thinstation.conf.buildtime.

I've tried allmodules and all xorg packages.

Any ideas?

**Comment by VolksDude** [comment]
Thanks Don...

Extra info
Using latest DevStation build from TS-6.2.13-Installer-0311.iso

On DHCP Server, for EFI Boot, using /boot/efi64/syslinux.efi
On DHCP Server for BIOS/Legacy Boot, using /boot/pxelinux/pxelinux.0

*Edit* Typed egi instead of efi

**Comment by Doncuppjr** [comment]
Try the grub bootloader, syslinux didn't do efi well at all.
    On Friday, November 24, 2023 at 06:56:32 AM MST, VolksDude ***@***.***> wrote:  
 
 


Thanks Don...

Extra info
Using latest DevStation build from TS-6.2.13-Installer-0311.iso

On DHCP Server, for EFI Boot, using /boot/egi64/syslinux.efi
On DHCP Server for BIOS/Legacy Boot, using /boot/pxelinux/pxelinux.0

**Comment by VolksDude** [comment]
Stupid question here....how?

> Try the grub bootloader, syslinux didn't do efi well at all.

**Comment by VolksDude** [comment]
Well, after adding "grub" in the "bootimages" and serving it, it's doing the same thing.

**Comment by VolksDude** [comment]
Adding the "About" window from a booted Thinstation...

Thinstation version: 6.2
Linux kernel version: 5.15.51TS
X.Org X Server 1.21.1.3

**Comment by VolksDude** [comment]
What would be the way to try an updated kernel? I saw that Kernel 5.18 could work with Gen13th Intel CPUs.
I tried changing the version number in "/ts/ports/kernel-modules/VERSION" and running "pkgmk -u -d", however after a long source build, I got a Build Failed.

**Comment by Doncuppjr** [comment]
I'm doing 6.1.63 now. Kernel updates are tricky things for sure. I'll let you know how it goes.
    On Tuesday, November 28, 2023 at 06:55:20 AM MST, VolksDude ***@***.***> wrote:  
 
 


What would be the way to try an updated kernel? I saw that Kernel 5.18 could work with Gen13th Intel CPUs.
I tried changing the version number in "/ts/ports/kernel-modules/VERSION" and running "pkgmk -u -d", however after a long source build, I got a Build Failed.

**Comment by VolksDude** [comment]
I saw a few updates in the code. I decided to give it a try. Seems to be working perfectly. Running VMware Horizon Client Version 2309 Build 22660930 and performance is perfect.
Anything else I should know before going further?

**Comment by Thinstation** [comment]
Not that I can think of. Glad it’s working.

**Comment by VolksDude** [comment]
Thanks
Closing issue
