### ISSUE TITLE
The problem of booting on real hardware in EFI mode

### ISSUE THREAD

**Issue by alexanderzhirov** [Thinstation/thinstation#800]
Donald, hi! Can you tell me which way to dig about EFI booting? In Legacy mode, the disk is loaded. Even on VirtualBox it is loaded into EFI, but on a real piece of hardware it gives this error. The ISO disk structure is given below.

![photo_2024-01-16_16-30-08](https://github.com/Thinstation/thinstation/assets/37277056/e21fa9e6-2245-4ac9-a3e3-25aa4fbe3b96)

```
.
├── boot
│   ├── grub
│   │   └── grub.cfg
│   ├── image.md5
│   ├── initrd
│   ├── isolinux
│   │   ├── boot.cat
│   │   ├── isolinux.bin
│   │   ├── isolinux.cfg
│   │   ├── ldlinux.c32
│   │   └── product.txt
│   ├── syslinux
│   │   ├── ldlinux.c32
│   │   ├── product.txt
│   │   ├── syslinux
│   │   └── syslinux.cfg
│   └── vmlinuz
├── EFI
│   ├── boot
│   │   ├── boot.efi
│   │   ├── bootx64.efi
│   │   ├── drivers_x64
│   │   │   ├── btrfs_x64.efi
│   │   │   ├── ext2_x64.efi
│   │   │   ├── ext4_x64.efi
│   │   │   ├── hfs_x64.efi
│   │   │   ├── iso9660_x64.efi
│   │   │   └── reiserfs_x64.efi
│   │   ├── grubx64.efi
│   │   ├── icons
│   │   │   ├── arrow_left.png
│   │   │   ├── arrow_right.png
│   │   │   ├── boot_linux.png
│   │   │   ├── boot_win.png
│   │   │   ├── func_about.png
│   │   │   ├── func_bootorder.png
│   │   │   ├── func_csr_rotate.png
│   │   │   ├── func_exit.png
│   │   │   ├── func_firmware.png
│   │   │   ├── func_hidden.png
│   │   │   ├── func_install.png
│   │   │   ├── func_reset.png
│   │   │   ├── func_shutdown.png
│   │   │   ├── mouse.png
│   │   │   ├── os_arch.png
│   │   │   ├── os_artful.png
│   │   │   ├── os_bionic.png
│   │   │   ├── os_centos.png
│   │   │   ├── os_chakra.png
│   │   │   ├── os_chrome.png
│   │   │   ├── os_clover.png
│   │   │   ├── os_crunchbang.png
│   │   │   ├── os_debian.png
│   │   │   ├── os_devuan.png
│   │   │   ├── os_elementary.png
│   │   │   ├── os_fedora.png
│   │   │   ├── os_freebsd.png
│   │   │   ├── os_frugalware.png
│   │   │   ├── os_gentoo.png
│   │   │   ├── os_gummiboot.png
│   │   │   ├── os_haiku.png
│   │   │   ├── os_hwtest.png
│   │   │   ├── os_kubuntu.png
│   │   │   ├── os_legacy.png
│   │   │   ├── os_linuxmint.png
│   │   │   ├── os_linux.png
│   │   │   ├── os_lubuntu.png
│   │   │   ├── os_mac.png
│   │   │   ├── os_mageia.png
│   │   │   ├── os_mandriva.png
│   │   │   ├── os_netbsd.png
│   │   │   ├── os_network.png
│   │   │   ├── os_opensuse.png
│   │   │   ├── os_redhat.png
│   │   │   ├── os_refind.png
│   │   │   ├── os_refit.png
│   │   │   ├── os_slackware.png
│   │   │   ├── os_suse.png
│   │   │   ├── os_systemd.png
│   │   │   ├── os_trusty.png
│   │   │   ├── os_ubuntu.png
│   │   │   ├── os_unknown.png
│   │   │   ├── os_void.png
│   │   │   ├── os_win8.png
│   │   │   ├── os_win.png
│   │   │   ├── os_xenial.png
│   │   │   ├── os_xubuntu.png
│   │   │   ├── os_zesty.png
│   │   │   ├── svg
│   │   │   │   ├── boot_win.svg
│   │   │   │   ├── func_csr_rotate.svg
│   │   │   │   ├── mouse.svg
│   │   │   │   ├── os_clover.svg
│   │   │   │   ├── os_debian.svg
│   │   │   │   ├── os_devuan.svg
│   │   │   │   ├── os_elementary.svg
│   │   │   │   ├── os_gummiboot.svg
│   │   │   │   ├── os_haiku.svg
│   │   │   │   ├── os_legacy.svg
│   │   │   │   ├── os_mac.svg
│   │   │   │   ├── os_netbsd.svg
│   │   │   │   ├── os_redhat.svg
│   │   │   │   ├── os_refind.svg
│   │   │   │   ├── os_refit.svg
│   │   │   │   ├── os_win.svg
│   │   │   │   ├── os_xenial.svg
│   │   │   │   ├── tool_fwupdate.svg
│   │   │   │   ├── tool_memtest.svg
│   │   │   │   └── tool_rescue.svg
│   │   │   ├── tool_apple_rescue.png
│   │   │   ├── tool_fwupdate.png
│   │   │   ├── tool_memtest.png
│   │   │   ├── tool_mok_tool.png
│   │   │   ├── tool_netboot.png
│   │   │   ├── tool_part.png
│   │   │   ├── tool_rescue.png
│   │   │   ├── tool_shell.png
│   │   │   ├── tool_windows_rescue.png
│   │   │   ├── transparent.png
│   │   │   ├── vol_external.png
│   │   │   ├── vol_internal.png
│   │   │   ├── vol_net.png
│   │   │   └── vol_optical.png
│   │   ├── keys
│   │   │   ├── altlinux.cer
│   │   │   ├── canonical-uefi-ca.cer
│   │   │   ├── canonical-uefi-ca.crt
│   │   │   ├── centos.cer
│   │   │   ├── centos.crt
│   │   │   ├── fedora-ca.cer
│   │   │   ├── fedora-ca.crt
│   │   │   ├── microsoft-kekca-public.cer
│   │   │   ├── microsoft-pca-public.cer
│   │   │   ├── microsoft-uefica-public.cer
│   │   │   ├── openSUSE-UEFI-CA-Certificate-4096.cer
│   │   │   ├── openSUSE-UEFI-CA-Certificate-4096.crt
│   │   │   ├── openSUSE-UEFI-CA-Certificate.cer
│   │   │   ├── openSUSE-UEFI-CA-Certificate.crt
│   │   │   ├── refind.cer
│   │   │   ├── refind.crt
│   │   │   ├── SLES-UEFI-CA-Certificate.cer
│   │   │   └── SLES-UEFI-CA-Certificate.crt
│   │   ├── mmx64.efi
│   │   └── refind.conf
│   └── Microsoft
│       └── Boot
│           ├── bootmgfw.efi
│           ├── grubx64.efi
│           └── mmx64.efi
├── rufus
│   ├── rufus.exe
│   └── rufus_files
│       └── syslinux-6.04
│           └── pre2-11-gbf6db5b4
│               ├── ldlinux.bss
│               └── ldlinux.sys
└── ThinStation-UEFI-CA.cer
```

**Comment by Doncuppjr** [comment]
Use grub. Syslinux has broken EFI support.


Sent from Yahoo Mail for iPhone


On Tuesday, January 16, 2024, 6:53 AM, Alexander Zhirov ***@***.***> wrote:




Donald, hi! Can you tell me which way to dig about EFI booting? In Legacy mode, the disk is loaded. Even on VirtualBox it is loaded into EFI, but on a real piece of hardware it gives this error. The ISO disk structure is given below.

photo_2024-01-16_16-30-08.jpg (view on web)
.
├── boot
│   ├── grub
│   │   └── grub.cfg
│   ├── image.md5
│   ├── initrd
│   ├── isolinux
│   │   ├── boot.cat
│   │   ├── isolinux.bin
│   │   ├── isolinux.cfg
│   │   ├── ldlinux.c32
│   │   └── product.txt
│   ├── syslinux
│   │   ├── ldlinux.c32
│   │   ├── product.txt
│   │   ├── syslinux
│   │   └── syslinux.cfg
│   └── vmlinuz
├── EFI
│   ├── boot
│   │   ├── boot.efi
│   │   ├── bootx64.efi
│   │   ├── drivers_x64
│   │   │   ├── btrfs_x64.efi
│   │   │   ├── ext2_x64.efi
│   │   │   ├── ext4_x64.efi
│   │   │   ├── hfs_x64.efi
│   │   │   ├── iso9660_x64.efi
│   │   │   └── reiserfs_x64.efi
│   │   ├── grubx64.efi
│   │   ├── icons
│   │   │   ├── arrow_left.png
│   │   │   ├── arrow_right.png
│   │   │   ├── boot_linux.png
│   │   │   ├── boot_win.png
│   │   │   ├── func_about.png
│   │   │   ├── func_bootorder.png
│   │   │   ├── func_csr_rotate.png
│   │   │   ├── func_exit.png
│   │   │   ├── func_firmware.png
│   │   │   ├── func_hidden.png
│   │   │   ├── func_install.png
│   │   │   ├── func_reset.png
│   │   │   ├── func_shutdown.png
│   │   │   ├── mouse.png
│   │   │   ├── os_arch.png
│   │   │   ├── os_artful.png
│   │   │   ├── os_bionic.png
│   │   │   ├── os_centos.png
│   │   │   ├── os_chakra.png
│   │   │   ├── os_chrome.png
│   │   │   ├── os_clover.png
│   │   │   ├── os_crunchbang.png
│   │   │   ├── os_debian.png
│   │   │   ├── os_devuan.png
│   │   │   ├── os_elementary.png
│   │   │   ├── os_fedora.png
│   │   │   ├── os_freebsd.png
│   │   │   ├── os_frugalware.png
│   │   │   ├── os_gentoo.png
│   │   │   ├── os_gummiboot.png
│   │   │   ├── os_haiku.png
│   │   │   ├── os_hwtest.png
│   │   │   ├── os_kubuntu.png
│   │   │   ├── os_legacy.png
│   │   │   ├── os_linuxmint.png
│   │   │   ├── os_linux.png
│   │   │   ├── os_lubuntu.png
│   │   │   ├── os_mac.png
│   │   │   ├── os_mageia.png
│   │   │   ├── os_mandriva.png
│   │   │   ├── os_netbsd.png
│   │   │   ├── os_network.png
│   │   │   ├── os_opensuse.png
│   │   │   ├── os_redhat.png
│   │   │   ├── os_refind.png
│   │   │   ├── os_refit.png
│   │   │   ├── os_slackware.png
│   │   │   ├── os_suse.png
│   │   │   ├── os_systemd.png
│   │   │   ├── os_trusty.png
│   │   │   ├── os_ubuntu.png
│   │   │   ├── os_unknown.png
│   │   │   ├── os_void.png
│   │   │   ├── os_win8.png
│   │   │   ├── os_win.png
│   │   │   ├── os_xenial.png
│   │   │   ├── os_xubuntu.png
│   │   │   ├── os_zesty.png
│   │   │   ├── svg
│   │   │   │   ├── boot_win.svg
│   │   │   │   ├── func_csr_rotate.svg
│   │   │   │   ├── mouse.svg
│   │   │   │   ├── os_clover.svg
│   │   │   │   ├── os_debian.svg
│   │   │   │   ├── os_devuan.svg
│   │   │   │   ├── os_elementary.svg
│   │   │   │   ├── os_gummiboot.svg
│   │   │   │   ├── os_haiku.svg
│   │   │   │   ├── os_legacy.svg
│   │   │   │   ├── os_mac.svg
│   │   │   │   ├── os_netbsd.svg
│   │   │   │   ├── os_redhat.svg
│   │   │   │   ├── os_refind.svg
│   │   │   │   ├── os_refit.svg
│   │   │   │   ├── os_win.svg
│   │   │   │   ├── os_xenial.svg
│   │   │   │   ├── tool_fwupdate.svg
│   │   │   │   ├── tool_memtest.svg
│   │   │   │   └── tool_rescue.svg
│   │   │   ├── tool_apple_rescue.png
│   │   │   ├── tool_fwupdate.png
│   │   │   ├── tool_memtest.png
│   │   │   ├── tool_mok_tool.png
│   │   │   ├── tool_netboot.png
│   │   │   ├── tool_part.png
│   │   │   ├── tool_rescue.png
│   │   │   ├── tool_shell.png
│   │   │   ├── tool_windows_rescue.png
│   │   │   ├── transparent.png
│   │   │   ├── vol_external.png
│   │   │   ├── vol_internal.png
│   │   │   ├── vol_net.png
│   │   │   └── vol_optical.png
│   │   ├── keys
│   │   │   ├── altlinux.cer
│   │   │   ├── canonical-uefi-ca.cer
│   │   │   ├── canonical-uefi-ca.crt
│   │   │   ├── centos.cer
│   │   │   ├── centos.crt
│   │   │   ├── fedora-ca.cer
│   │   │   ├── fedora-ca.crt
│   │   │   ├── microsoft-kekca-public.cer
│   │   │   ├── microsoft-pca-public.cer
│   │   │   ├── microsoft-uefica-public.cer
│   │   │   ├── openSUSE-UEFI-CA-Certificate-4096.cer
│   │   │   ├── openSUSE-UEFI-CA-Certificate-4096.crt
│   │   │   ├── openSUSE-UEFI-CA-Certificate.cer
│   │   │   ├── openSUSE-UEFI-CA-Certificate.crt
│   │   │   ├── refind.cer
│   │   │   ├── refind.crt
│   │   │   ├── SLES-UEFI-CA-Certificate.cer
│   │   │   └── SLES-UEFI-CA-Certificate.crt
│   │   ├── mmx64.efi
│   │   └── refind.conf
│   └── Microsoft
│       └── Boot
│           ├── bootmgfw.efi
│           ├── grubx64.efi
│           └── mmx64.efi
├── rufus
│   ├── rufus.exe
│   └── rufus_files
│       └── syslinux-6.04
│           └── pre2-11-gbf6db5b4
│               ├── ldlinux.bss
│               └── ldlinux.sys
└── ThinStation-UEFI-CA.cer

**Comment by alexanderzhirov** [comment]
Can I get a tip on where to start?

**Comment by Thinstation** [comment]
For boot_images make sure you have grub in the list. A grub iso will be
built.

**Comment by Thinstation** [comment]
bootimages

**Comment by alexanderzhirov** [comment]
I rather missed something, because GRUB was not added to the ISO image.

```
param initrdcmd         "squashfs"
param bootimages        "grub iso"
```

```
.
├── boot
│   ├── image.md5
│   ├── initrd
│   ├── isolinux
│   │   ├── boot.cat
│   │   ├── isolinux.bin
│   │   ├── isolinux.cfg
│   │   ├── ldlinux.c32
│   │   └── product.txt
│   ├── syslinux
│   │   ├── ldlinux.c32
│   │   ├── product.txt
│   │   ├── syslinux
│   │   └── syslinux.cfg
│   └── vmlinuz
└── rufus
    ├── rufus.exe
    └── rufus_files
        └── syslinux-6.04
            └── pre2-11-gbf6db5b4
                ├── ldlinux.bss
                └── ldlinux.sys
```

**Comment by alexanderzhirov** [comment]
My mistake. Everything is going to be ready. Lies in `/build/boot-images/grub/thinstation-efi.iso`. Thanks!:)
