### ISSUE TITLE
Generation of UEFI ISO file not found

### ISSUE THREAD

**Issue by KhryG** [Thinstation/thinstation#813]
hey, 

I want to make a bootable key with an "iso" in uefi mode, after several rechecking on the github, I notice that several people have the folder/build/boot-images/grub/ but when generating my image with the command ". /build --allmodules", I have the folder "GRUB" but no image of type iso "/build/boot-images/grub/thinstation-efi.iso"

In the configuration of my build.conf file, I have the line:
param bootimages " grub iso"

I’m not an expert in the linux environment but if you have an idea

Thank you all 

![thinstation](https://github.com/Thinstation/thinstation/assets/162110399/8d1a008f-198b-4dcf-81b5-9c0215c1d2e7)

**Comment by Thinstation** [comment]
It be being redefined somewhere else in the build.conf. Make sure it's only being declared once.

**Comment by KhryG** [comment]
hey 

Thank you for your feedback, I look in my file but I do not see another statement, here is my build.conf file

**Comment by KhryG** [comment]
[build.txt](https://github.com/Thinstation/thinstation/files/14492455/build.txt)

**Comment by KhryG** [comment]
it seems that my malfunction came from the host machine, after a clean reboot, my image of type iso is present
