### ISSUE TITLE
Problem with monitor resolution

### ISSUE THREAD

**Issue by Aleksa2022** [Thinstation/thinstation#818]
Found a problem with some monitors - EDID is not picked up and the resolution is set to 1024x768, even though the monitors are widescreen and support 1600x900 resolution.
I updated drivers and other Xorg components, but for some reason it didn't help much.
I connected the problem monitor to a thick client - the resolution is fine.
I have tried different options to fix the problem in Thinstation, but no luck so far.
Saved the EDID from the thick client, now we need to include it correctly in the image.
What is the correct way to enable the correct EDID in Thinstation to fix the resolution problem?

**Comment by Doncuppjr** [comment]
I've only ever seen that when there is a physical problem. Perhaps a bad pin on a cable or the port your plugging the monitor into on the client. You can review the xorg log to see what EDID information is gathered.
    On Sunday, April 7, 2024 at 09:54:06 PM MDT, Alesandro ***@***.***> wrote:  
 
 


Found a problem with some monitors - EDID is not picked up and the resolution is set to 1024x768, even though the monitors are widescreen and support 1600x900 resolution.
I updated drivers and other Xorg components, but for some reason it didn't help much.
I connected the problem monitor to a thick client - the resolution is fine.
I have tried different options to fix the problem in Thinstation, but no luck so far.
Saved the EDID from the thick client, now we need to include it correctly in the image.
What is the correct way to enable the correct EDID in Thinstation to fix the resolution problem?

**Comment by Aleksa2022** [comment]
You're right. I am. In this case, the monitor was connected through an adapter. I was confused by the fact that our technical support claimed that everything was working for the user and suddenly stopped, and that the available resolutions for the monitor are defined normally, except for the necessary one - 1600x900.
The problem was in the adapter, as in similar cases before. In this case, EDID was empty, so I had the idea to somehow slip the EDID of used monitors into the image.
