### ISSUE TITLE
The overlayfs package gives an error when loading

### ISSUE THREAD

**Issue by alexanderzhirov** [Thinstation/thinstation#820]
When loading the image, an error is generated that occurs at [this location](https://github.com/Thinstation/thinstation/blob/66691b0c077a13d2fc0982bad588f1edb244cf44/ts/build/packages/overlayfs/sbin/overlayfs#L9). How critical is it?

```
pivot_root: failed to change root from `.' to `/mnt/union/oldroot': Invalid argument
```

![изображение](https://github.com/Thinstation/thinstation/assets/37277056/3969b552-4700-45cb-8ad3-bda93dae500a)

**Comment by Doncuppjr** [comment]
That would leave the entire file system except tmpfs mounts read only.


Sent from Yahoo Mail for iPhone


On Friday, April 12, 2024, 8:28 AM, Alexander Zhirov ***@***.***> wrote:




When loading the image, an error is generated that occurs at this location. How critical is it?
pivot_root: failed to change root from `.' to `/mnt/union/oldroot': Invalid argument

default.png (view on web)

**Comment by alexanderzhirov** [comment]
That is, the instruction, it turns out, has no meaning when used?

**Comment by Thinstation** [comment]
When using the overlay package you need to change the initrd to squashfs
