### ISSUE TITLE
VMware Horizon Issue - Dark ToolBar

### ISSUE THREAD

**Issue by VolksDude** [Thinstation/thinstation#830]
Hi,

I have this issue sometimes when the Horizon Client Toolbar becomes "Gray". Can't see what's on it, but still responds to the click in it.

I tried updating to the latest Horizon Client (8.12.1) but performance is horrible.

It's running on a I7-13th Gen CPU and on the Kernel 6.1.63TS.

I'm wondering if there's an issue with the Graphics drivers. Is it possible to upgrade the Kernel to a newer LTS version?

Thanks

**Comment by Doncuppjr** [comment]
Which video card and xorg driver are being used?
    On Tuesday, May 28, 2024 at 07:06:59 AM MDT, VolksDude ***@***.***> wrote:  
 
 


Hi,

I have this issue sometimes when the Horizon Client Toolbar becomes "Gray". Can't see what's on it, but still responds to the click in it.

I tried updating to the latest Horizon Client (8.12.1) but performance is horrible.

It's running on a I7-13th Gen CPU and on the Kernel 6.1.63TS.

I'm wondering if there's an issue with the Graphics drivers. Is it possible to upgrade the Kernel to a newer LTS version?

Thanks

**Comment by VolksDude** [comment]
Thinstation 6.2
Linux Kernel 6.1.63TS
X.Org Server 1.21.1.3
Intel UHD Graphics 770

**Comment by Doncuppjr** [comment]
Is it using the intel xorg driver, or vesa fallback?
    On Tuesday, May 28, 2024 at 07:30:11 AM MDT, Don Cupp ***@***.***> wrote:  
 
  Which video card and xorg driver are being used?
    On Tuesday, May 28, 2024 at 07:06:59 AM MDT, VolksDude ***@***.***> wrote:  
 
 


Hi,

I have this issue sometimes when the Horizon Client Toolbar becomes "Gray". Can't see what's on it, but still responds to the click in it.

I tried updating to the latest Horizon Client (8.12.1) but performance is horrible.

It's running on a I7-13th Gen CPU and on the Kernel 6.1.63TS.

I'm wondering if there's an issue with the Graphics drivers. Is it possible to upgrade the Kernel to a newer LTS version?

Thanks

**Comment by VolksDude** [comment]
Intel-Xorg-Driver

**Comment by Doncuppjr** [comment]
You could try a `prt-get update -fr xorg-xf86-video-intel`, followed with an `update xorg7-intel` and see what that does.
    On Tuesday, May 28, 2024 at 08:00:40 AM MDT, VolksDude ***@***.***> wrote:  
 
 


Intel-Xorg-Driver

**Comment by VolksDude** [comment]
Just did
I was able to reproduce problem.. :(

**Comment by Doncuppjr** [comment]
I pushed the latest 6.1 kernel, which is LTS.
They are many parts of the video subsystem that could be doing this. Mesa, the compositor. Try switching off the compositor if it is on, or switching if on if it is off.
    On Tuesday, May 28, 2024 at 09:04:44 AM MDT, VolksDude ***@***.***> wrote:  
 
 


Just did
I was able to reproduce problem.. :(

**Comment by VolksDude** [comment]
Let me try this and I'll get back to you
Thanks

**Comment by VolksDude** [comment]
I haven't seen the problem since the update.
cross-fingers
