### ISSUE TITLE
Create ThinStation Iso Installer For non-UEFI systems 

### ISSUE THREAD

**Issue by sajjadsabzkar** [Thinstation/thinstation#831]
Hi, how i can build for non-uefi system iso image?

**Comment by Doncuppjr** [comment]
The grub image works for all systems bios and UEFI

**Comment by sajjadsabzkar** [comment]
but i wont able to boot from my computer.Is there a way to check the log? Because it is only displayed on the underline flash screen after boot?

**Comment by sajjadsabzkar** [comment]
![10](https://github.com/Thinstation/thinstation/assets/33274732/bc9bbdde-7f7e-4507-881c-5a4cfaca94df)
When burning with rufus software, for both mbr and gpt options 
There is only UEFI(non csm).

**Comment by Thinstation** [comment]
So, the image actually contains everything that is needed to boot in BIOS mode. Rufus is not detecting that, I'll mention it to the developer of that project. There is a utility in ts/bin called mkmbrdrv and another simple simple utility called flash that will call mkmbrdrv. They will flash a drive directly from you build environment that will boot as either BIOS or UEFI.

**Comment by sajjadsabzkar** [comment]
> So, the image actually contains everything that is needed to boot in BIOS mode. Rufus is not detecting that, I'll mention it to the developer of that project. There is a utility in ts/bin called mkmbrdrv and another simple simple utility called flash that will call mkmbrdrv. They will flash a drive directly from you build environment that will boot as either BIOS or UEFI.

Thanks for your application, it works, but I feel that the iso file does not burn or cannot be called! Because I took the build in an iso file containing vmware and it is correct on the virtual machine, but on the flash containing the boot by mkmbrdrv, it is only a tty environment and does not even have startx.

**Comment by sajjadsabzkar** [comment]
Of course, I think I misunderstood the structure, probably inside the efi-source folder are the same contents inside the ISO file, and since I built the hwlister, I definitely see the same written on the flash and the tty environment again. It is true ?

**Comment by Thinstation** [comment]
The hwlister build does not have X. It is a minimal config that was build to detect most of the modules that are necessary for a system, but not all, as X does sometimes load some extra stuff. Really the idea behind that build was for memory constrained systems. A full build like DevStation also has the hwlister.sh utility and will generate a complete list.
    On Saturday, June 15, 2024 at 09:56:10 AM MDT, Sajjad Sabzkar ***@***.***> wrote:  
 
 


Of course, I think I misunderstood the structure, probably inside the efi-source folder are the same contents inside the ISO file, and since I built the hwlister, I definitely see the same written on the flash and the tty environment again. It is true ?

**Comment by sajjadsabzkar** [comment]
Thank you for your reply and your unique project. As a last question, how can I lower the resolution and frame rate? The boot splash screen is correct but after that the monitor gives out of range
