### ISSUE TITLE
faild to boot grub image

### ISSUE THREAD

**Issue by sajjadsabzkar** [Thinstation/thinstation#840]
Hi, i'm compile iso and when i boot from usb below error message shows.
``` lib/relocator.c:1455: couldn't find suitable memory target. %7.39MiB/s] ```

![012](https://github.com/Thinstation/thinstation/assets/33274732/d63ea21a-fc3a-4138-a43d-7ccf971d42e9)

**Comment by Thinstation** [comment]
You ran out of memory. You can either add more ram or make a smaller image.

**Comment by sajjadsabzkar** [comment]
Does the vmware config image require more than 4GB of RAM?

**Comment by sajjadsabzkar** [comment]
Apparently, everything is ok until the fastboot parameter is set to false, this happens. I even increased the amount of RAM to 8 GB

**Comment by Thinstation** [comment]
The vmware machine profile does not really change the size of the image, it only selects the modules necessary to run on most VMware machine configurations. I don't know how much stuff you are sticking into the image, but fastboot is one of the ways to get past memory constraints. Depending on the initrd compression mode, more or less memory might be required to decompress the image during boot. https://github.com/Thinstation/thinstation/wiki/Booting-Modes-and-Compression
