### ISSUE TITLE
Module exception when building when using --allmodules

### ISSUE THREAD

**Issue by plastilincheg** [Thinstation/thinstation#842]
Greetings. There's a problem. I want to use ntfs-3g via fuse, but if I run the build with the --allmodules option when connecting a USB drive, it is mounted using the ntfs module. Accordingly, the flash drive is not writeable. There is some way to exclude certain modules from the assembly that will definitely not be needed, for example in my case module ntfs

**Comment by Thinstation** [comment]
Putparam blacklist "ntfs.ko"
in your build.conf    On Friday, July 5, 2024 at 01:26:43 AM MDT, plastilincheg ***@***.***> wrote:  
 
 


Greetings. There's a problem. I want to use ntfs-3g via fuse, but if I run the build with the --allmodules option when connecting a USB drive, it is mounted using the ntfs module. Accordingly, the flash drive is not writeable. There is some way to exclude certain modules from the assembly that will definitely not be needed, for example in my case module ntfs
