### ISSUE TITLE
Enable boot message by default

### ISSUE THREAD

**Issue by sajjadsabzkar** [Thinstation/thinstation#843]
is possible to Enable boot message by default

**Comment by Thinstation** [comment]
add
param kernelcmdline 'vt.global_cursor_default=1 systemd.show_status=true rd.systemd.show_status=true' to the kernelcmd'
to your build.conf






On Tuesday, July 16, 2024 at 11:11:06 PM MDT, Sajjad Sabzkar ***@***.***> wrote: 







is possible to Enable boot message by default

**Comment by sajjadsabzkar** [comment]
also param bootlogo = false.
Thanks
