### ISSUE TITLE
Is the a way to send multiple CRON_JOB in the config file

### ISSUE THREAD

**Issue by gibranabdulla** [Thinstation/thinstation#850]
In the config files.  How can we send multiple cron jobs?  I don't want to have to rebuild the iso to include some of the other CRON jobs we need as they have kiosk specific configs.

CRON_JOB="0 2 * * 0 /sbin/reboot"
CRON_JOB="@reboot ntpdate time.myntp.com"

**Comment by Thinstation** [comment]
CRON_JOB1="0 2 * * 0 /sbin/reboot"
CRON_JOB2="@reboot ntpdate time.myntp.com"

**Comment by gibranabdulla** [comment]
Awesome!  Works great!  Thanks!
