### ISSUE TITLE
vmview how to send Ctrl Alt Del to vm

### ISSUE THREAD

**Issue by jason-wl** [Thinstation/thinstation#851]
i what use thinstation build a horizon view client with fullscreen ，but view.sendCtrlAltDelToVM notwork  how  to send Ctrl Alt Del to VM not alert button to send.

**Comment by sajjadsabzkar** [comment]
Can you provide a screenshot?
Usually, you should be able to send  AltCtrlDel keys with the software itself

**Comment by jason-wl** [comment]
My server cannot connect now. The pop-up window is indeed caused by the software, but the settings view.sendCtrlAltDelToVM given by the software are not work. I modified the configuration file as /etc/vmware/view-mandatory-config  /etc/vmware/view-default-config  /.vmware/view-preferences  /etc/skel/.vmware/view-preferences  set view.sendCtrlAltDelToVM=true  but it all not work .

![20240909101002099](https://github.com/user-attachments/assets/859b00de-75de-4555-ac4e-c8aeef5ec8a2)

**Comment by jason-wl** [comment]
My server cannot connect now. The pop-up window is indeed caused by the software, but the settings view.sendCtrlAltDelToVM given by the software are not work. I modified the configuration file as /etc/vmware/view-mandatory-config  /etc/vmware/view-default-config  /.vmware/view-preferences  /etc/skel/.vmware/view-preferences  set view.sendCtrlAltDelToVM=true  but it all not work .

![20240909101002099](https://github.com/user-attachments/assets/859b00de-75de-4555-ac4e-c8aeef5ec8a2)

**Comment by sajjadsabzkar** [comment]
Perhaps the best thing to do is to test the software version on other Linux distributions

**Comment by jason-wl** [comment]
The problem has been resolved, there is a slight difference between the format provided by the official and the system recognition

**Comment by Thinstation** [comment]
You could elaborate for others in the event that they encounter the same issue.
