### ISSUE TITLE
PXE Boot : Unable to find boot device

### ISSUE THREAD

**Issue by VolksDude** [Thinstation/thinstation#859]
Hi,

Tried to deploy the new version. Everything builds properly, but when my system tries to PXE Boot, I get this error...

`../../grub2.12/grub-core/commands/bli.c:98 Unable to find Boot Device`

Did you guys see any of this before?

EDIT : Mistype the error

**Comment by Doncuppjr** [comment]
Interesting. I’m guessing EFI PXE?

**Comment by VolksDude** [comment]
Yes, EFI PXE

**Comment by Doncuppjr** [comment]
Give me a sec and I’ll push a version without the bli module compiled in.

**Comment by Thinstation** [comment]
Ugh, looks like grub2.12 has some EFI PXE issues. This could take a bit.

**Comment by Thinstation** [comment]
Okay, looks like it's localized to some or one of the Fedora patches. I'll try and work it out.

**Comment by Thinstation** [comment]
Alright, tracked it down.
exit the chroot
git pull
./setup-chroot
prt-get update grub2-efi

rebuild your image.

**Comment by Thinstation** [comment]
Thanks for the bug report

**Comment by VolksDude** [comment]
Sorry for the late reply.
It boot now, however, after loading initrd, I see this quickly before the splash screen....
`failed to change root from . to /mnt/union/oldroot`
However all works.

**Comment by Thinstation** [comment]
What is your initrd command from build.conf?

**Comment by VolksDude** [comment]
Found my problem....totally me.
I have "Fastboot" set to no and I had package overlayfs enabled.
Removed overlayfs and I don't see the error now.
Thanks again!!
