### ISSUE TITLE
VMware and Intel VA-API Hardware Decoding

### ISSUE THREAD

**Issue by VolksDude** [Thinstation/thinstation#865]
When connecting to a VMware Horizon Pool, the session appears to be accelerated. However, upon checking the log file located at /tmp/vmware-tsuser/vmware-mks-123435.log, I encounter the following error:
"Failed to initialize FFmpeg for vaapi2.7."

The session functions with H.264 but relies on software decoding. I want to enable hardware decoding instead. After reviewing the documentation, I found this resource:

https://docs.omnissa.com/bundle/HorizonClientLinuxGuideV2406/page/ConfigureBlastOptionsforHorizonLinuxClient.html
"To use H.264 with an Intel GPU, the Intel VA-API driver and the GLX VA-API libraries are required. Running the command vainfo shows the H.264 profiles."

On ThinStation, I noticed there’s a package called libva, but it appears to be empty. Further research led me to the libva-intel-driver package under Crux, which includes the file /usr/lib/dri/i965_drv_video.so.

What would be the easiest way to add this driver to ThinStation to see if it helps to enable hardware decoding?

**Comment by Doncuppjr** [comment]
If the libva package is empty, it's likely not included in a build, and hasn't been populated yet. There should be a build/install script for it that only gets run if the package was included in a build at least once. 

lib/dri/i965_drv_video.so should already be available from the xorg7-intel package.

**Comment by VolksDude** [comment]
I'm closing this as the issue is totally with the Horizon Client. After looking at logs, they are using their own libraries which are too old for the HW Decoding to be enabled. Thanks
