### ISSUE TITLE
Include .rdp file 

### ISSUE THREAD

**Issue by DanKothlow** [Thinstation/thinstation#866]
We are using a vdi solution, and need to specify the .rdp file to allow connection through the broker.
If we specify just the server, the connection is refused.
We have tested specifying the connection rdp file in the Live Test iso using FreeRDP, so we know it will work. 
How can we add the .rdp file itself to the image?

**Comment by Doncuppjr** [comment]
Is this with  Remmina

**Comment by Doncuppjr** [comment]
If just using straight FreeRDP, I would guess something like
Delete these two files,
/build/packages/freerdp/etc/cmd/freerdp.getuser
/build/packages/freerdp/etc/cmd/freerdp.getip 

Then make a session entry in thinstation.conf.buildtime
SESSION_1_TITLE="Connection by .rdp"
SESSION_1_TYPE=freerdp
SESSION_1_AUTOSTART=ON
SESSION_1_FREERDP_OPTIONS="<some path>connection.rdp"

Place the file in a custom package with a relative path you would like to use, and put that relative path into the entry above, include the custom package in your build and make a build.

**Comment by DanKothlow** [comment]
Thank you for replying. 
We are using FreeRDP.

Can you provide some details on how to do a custom package, please?

**Comment by Doncuppjr** [comment]
I can maybe make some better detailed responses tomorrow, but there is a wiki page on the subject here  https://github.com/Thinstation/thinstation/wiki/Packaging

**Comment by DanKothlow** [comment]
Creating a packages just to include a single file seems a bit over the top. 
But, if that's what it takes.
I'll toy around with it, but if you can put together better details tailored to my situation, I would appreciate it.

Happy Thanksgiving.

**Comment by DanKothlow** [comment]
I think I was a bit overwhelmed with all the other items in the package wiki. 

Getting the .rdp file added was actually straightforward. I simply created a new package folder, with a lib folder nested, and added the .rdp file to the lib folder. 

I think I'm good. Won't know for sure until Monday.

**Comment by Doncuppjr** [comment]
Another possibility is to just set /g:gateway.server.com as one of the freerdp options. I think it should work as long as the gateway credentials are the same as the destination server credentials.

**Comment by DanKothlow** [comment]
I'll let you know next week how it goes. 
Thank you for your time.

**Comment by DanKothlow** [comment]
I was able to get by without using the package and the .rdp file. 
I specified the /load-balance-info that the actual.rdp file showed, and it worked as expected. 

Thank you again for your assistance.
