### ISSUE TITLE
Use MAC address in config

### ISSUE THREAD

**Issue by sanbroz** [Thinstation/thinstation#868]
Hi, I wonder if it's possible to use CLIENT_MAC in config files similer to SERVER_IP

**Comment by Doncuppjr** [comment]
The netfiles should try and get a config file by MAC, but it's the last thing tried. If its not working, then I might have to do some digging. The timing on this can get a little tricky.

**Comment by sanbroz** [comment]
MAC address in config files works fine, I want to use CLIENT_MAC inside config files as variable, I want to use macaddress as FreeRDP username, I don't see any MAC related variable in environment settings. 

I can use the following to export MAC
export MAC=$(ip link show eth0 | awk '/ether/ {print $2}' | tr -d ':')

let me know how to run custom startup script.

**Comment by Doncuppjr** [comment]
You could maybe work something out here, build/packages/freerdp/build/extra/etc/cmd/freerdp.options

**Comment by sanbroz** [comment]
sorry, I think I messed up my query, I just want the following

```
#SESSION_1_FREERDP_SERVER=192.168.1.2
SESSION_1_FREERDP_SERVER=${SERVER_IP}
#SESSION_1_FREERDP_USER=user
SESSION_1_FREERDP_USER=${CLIENT_MAC}
SESSION_1_FREERDP_PASS_ENABLE=false
SESSION_1_FREERDP_OPTIONS="/p:password /cert:ignore"
```

${SERVER_IP} is working fine, but how to make ${CLIENT_MAC} to work, I think it need to be exported to env first, I try autoruns package to export MAC to env var with 
`AUTORUNS_RC5_0="export CLIENT_MAC=$(ip link show eno1 | awk '/ether/ {print $2}' | tr -d ':')"` 
but it didn't work.

Can something similar can be used in config file
`SESSION_1_FREERDP_USER=$(ip link show eno1 | awk '/ether/ {print $2}' | tr -d ':')`

**Comment by Doncuppjr** [comment]
If SERVER_IP works, try adding CLIENT_MAC to thinstation.exports


Sent from Yahoo Mail for iPhone


On Wednesday, December 11, 2024, 11:08 PM, Sanbroz ***@***.***> wrote:




sorry, I think I messed up my query, I just want the following
#SESSION_1_FREERDP_SERVER=192.168.1.2
SESSION_1_FREERDP_SERVER=${SERVER_IP}
#SESSION_1_FREERDP_USER=user
SESSION_1_FREERDP_USER=${CLIENT_MAC}
SESSION_1_FREERDP_PASS_ENABLE=false
SESSION_1_FREERDP_OPTIONS="/p:password /cert:ignore"

${SERVER_IP} is working fine, but how to make ${CLIENT_MAC} to work, I think it need to be exported to env first, I try autoruns package to export MAC to env var with
AUTORUNS_RC5_0="$(ip link show eno1 | awk '/ether/ {print $2}' | tr -d ':')"
but it didn't work.

Can something similar can be used in config file
SESSION_1_FREERDP_USER=$(ip link show eno1 | awk '/ether/ {print $2}' | tr -d ':')

**Comment by sanbroz** [comment]
"Thank you so much! It works perfectly. I've been following and using your project since version 2.2, and I recently started using ThinStation again after almost 15 years."
