### ISSUE TITLE
Browser certificate

### ISSUE THREAD

**Issue by mazzex321** [Thinstation/thinstation#872]
I have an issue making the thinstation chrome work with my websrv i have local trusted certificate need to import to chrome as it will not work by copying to cert directory i found a solution to copy my cert to client machine and i have a script to impot to cert9.db but unable to find a soultion how to make this script run when the machine boots 
Regards

**Comment by Doncuppjr** [comment]
https://github.com/Thinstation/thinstation/wiki/Certificates

Sent from Yahoo Mail for iPhone


On Wednesday, December 25, 2024, 1:26 PM, mazzex321 ***@***.***> wrote:




I have an issue making the thinstation chrome work with my websrv i have local trusted certificate need to import to chrome as it will not work by copying to cert directory i found a solution to copy my cert to client machine and i have a script to impot to cert9.db but unable to find a soultion how to make this script run when the machine boots
Regards

**Comment by mazzex321** [comment]
@Doncuppjr thank you for your fast reply
As i know on linux if u added a cert.pem file to ca folder it will be trusted by system but not browser for browser need to import manualy , but any way maybe iam wrong and missed that idea ill try what u seggested and get back to u 
Many thanks

**Comment by mazzex321** [comment]
@Doncuppjr you are right i was wrong the solution u provided worked the cert now is imported to chrome to now its showing as untrusted and i did make the trusted folder

regards

**Comment by mazzex321** [comment]
thank you i found a solution is to edit the finalize script and replace the trust command form P to TCu,Cu,Cu  i dont know if this is the true solution but at least it worked

**Comment by Doncuppjr** [comment]
If it is a CA certificate, it should go in the ca folder, but if it’s just a peer certificate, the P,, should be correct for importing it into the cert9.db. CT,C,C effectively tells your client to trust any certificate that is signed by the imported certificate as if it was a CA.


Sent from Yahoo Mail for iPhone


On Thursday, December 26, 2024, 3:55 AM, mazzex321 ***@***.***> wrote:




thank you i foud a solution is to edit the finalyze script and replace the trust command form P to TCu,Cu,Cu i dont know if this is the true solution but at least it worked
