### ISSUE TITLE
package dmidecode

### ISSUE THREAD

**Issue by trentasis** [Thinstation/thinstation#88]
It is possible to add dmidecode as package in thinstation, I have checked that in crux this package exist, can you add or detail how can I add?

Thanks

**Comment by Thinstation** [comment]
Pushed to master

**Comment by trentasis** [comment]
Thanks! This is a great tool and our environment is 5.4 version, can you add this package to 5.4 branch, our developments are in 5.4 branch and dmidecode is a great tool for hardware inventory
Thanks!
