### ISSUE TITLE
errors.txt contains 2 errors

### ISSUE THREAD

**Issue by trentasis** [Thinstation/thinstation#89]
Hi,

With Thinstation 5.4 we have detected that in /var/log/errors.txt cotnains 2 errors:

Sep 23 12:38:39 (none) user.err kernel: devpts: called with bogus options
Sep 23 12:38:39 (none) user.err kernel: bbswitch: version magic '3.18.20TS preempt mod_unload 686 ' should be '3.18.20TS_SMP SMP preempt mod_unload 686 '

I don't know where is the source of this problems, what can I do to solve?

Thanks

**Comment by trentasis** [comment]
With latest branch 5.4 errors are not showed, now only show :+1: 
Oct  5 10:51:40 (none) user.err kernel: bbswitch: No discrete VGA device found

Not sure if this is correct....

**Comment by Doncuppjr** [comment]
Yes, that is what is supposed to happen. 


     On Monday, October 5, 2015 2:27 AM, trentasis <notifications@github.com> wrote:
   

 With latest branch 5.4 errors are not showed, now only show  
Oct 5 10:51:40 (none) user.err kernel: bbswitch: No discrete VGA device foundNot sure if this is correct....—
