### ISSUE TITLE
Not work param keyfile ./id_rsa

### ISSUE THREAD

**Issue by shweew** [Thinstation/thinstation#90]
In a script of build the **skel** folder is passed (the way of **./tmp-tree/etc/.ssh** needs to be changed to **./tmp-tree/etc/skel/.ssh**)

>echo -e "Checking for Key File"
>
>if [ -e $PACDIR/keyfile.param ]; then
	if [ -e "$ts_keyfile" ] ; then
		if [ ! -e ./tmp-tree/etc/skel/.ssh ] ; then
			mkdir -p ./tmp-tree/etc/skel/.ssh
		fi
		cp $ts_keyfile ./tmp-tree/etc/skel/.ssh
	else
		echo "Key file not found, build aborted."
		remove_files
       		exit 1
	fi
fi

**Comment by Thinstation** [comment]
I think this is fixed.
