### ISSUE TITLE
Autoconnection SAMBA folder

### ISSUE THREAD

**Issue by shweew** [Thinstation/thinstation#91]
In thinstation there is no **smbmount**.
For automatic connection of the samba folder it is necessary to change in the **packages/netfiles/etc/init.d/filesystem_network** file 

>if ! pkg_initialized $PACKAGE; then
if [ -n "$NET_SMB_SERVER" ] \
&& [ -e /bin/smbmount ] \
&& [ -e /bin/smbmnt ]; then
mkdir /mnt/smb
smbmount $NET_SMB_SERVER /mnt/smb -n -o \
username=$NET_SMB_USER,\
password=`cat /etc/.storage`,\
workgroup=$NET_SMB_WORKGROUP

to 

>if ! pkg_initialized $PACKAGE; then
if [ -n "$NET_SMB_SERVER" ]; then
mkdir /mnt/smb
mount -t cifs -o user=$NET_SMB_USER,\
password=`cat /etc/.storage` \
$NET_SMB_SERVER /mnt/smb

to uncomment in build.conf.example **module cifs** and **package samba-client**, and to set **param storagepasswd**.

**Comment by Thinstation** [comment]
Merged.
