### ISSUE TITLE
add perl to thinstation from ports

### ISSUE THREAD

**Issue by trentasis** [Thinstation/thinstation#98]
I have a problem about ports with thinstation, I have searched in thinstation list and wiki and I can't find any information about how to install a package from a port, for example I need to install perl and some modules of perl, for example  
    Digest::MD5
    XML::Simple
    Net::IP: 
    LWP

It seems that this software is in default ports of thinstation, but I can't find how to install and configure, I have tried with package perl and package perl or package perl-digest-md5 in build.conf but we always receive package not found, where is my problem?

Thanks

**Comment by Doncuppjr** [comment]
You need a little bit of glue between the port src build system, and the image building package system. I made a script to help with that, mkrepackage <port> , before putting into build.conf.

**Comment by trentasis** [comment]
thanks!

It will be interesting to add some ports of perl, for example:
p5-lwp
p5-net-ssleay
p5-net-ip
p5-uri

and detected that perl ports has some issues with permissions, some
examples:

./build: line 1053: ./packages/perl-digest-md5/build/install: Permission
denied

./build: line 1053: ./packages/perl-libwww-perl/build/install: Permission
denied

./build: line 1053: ./packages/perl-xml-simple/build/install: Permission
denied

./build: line 1053: ./packages/perl/build/install: Permission denied

./build: line 1053: ./packages/p5-lwp/build/install: Permission denied


Thanks

2015-09-26 21:00 GMT+02:00 Donald A. Cupp Jr. <notifications@github.com>:

**Comment by Doncuppjr** [comment]
chmod +x


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by trentasis** [comment]
Thanks great job

**Comment by ggbce** [comment]
Hi, 

Do you known if someone tried to add Perl packages in ThinStation OS to add and use "FusionInventory-Agent" also ?

We have a very large network (over 20 000 PC) and we manage all the inventory in one centralized tool called GLPI, our issue is that ThinStation is not supporting the FusionInventory-Agent application and these PC are not in our inventory. We known that we can use a central console for ThinStation and get his inventory, but it still standalone of all the network inventory.

Please feed us some information if you have a tip about that.

Regards,
GGBce

**Comment by Doncuppjr** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } You could certainly integrate your inventory tool into ThinStation. I have never used that one, so I don't know how much work it is, but if it supports Linux, it will work.


Sent from Yahoo Mail for iPhone


On Friday, November 25, 2016, 12:57 PM, ggbce <notifications@github.com> wrote:


Hi,

Do you known if someone tried to add Perl packages in ThinStation OS to add and use "FusionInventory-Agent" also ?

We have a very large network (over 20 000 PC) and we manage all the inventory in one centralized tool called GLPI, our issue is that ThinStation is not supporting the FusionInventory-Agent application and these PC are not in our inventory. We known that we can use a central console for ThinStation and get his inventory, but it still standalone of all the network inventory.

Please feed us some information if you have a tip about that.

Regards,
GGBce
